### ISSUE TITLE
Auto-close not work

### ISSUE THREAD

**Issue by tin-pham** [kyazdani42/nvim-tree.lua#1005]
OS: PopOS
Nvim Version: v0.7.0-dev
Nvim-tree-version: I just update this plugin, but i don't know how to check version of this
Bug: auto-close not work
Step to reproduce: Close the buffer while the tree open
![image](https://user-images.githubusercontent.com/20679090/154821320-5bb5890e-3399-441b-9101-61b3fae7a303.png)

![image](https://user-images.githubusercontent.com/20679090/154821325-f99e34a5-fe2a-48d1-a188-85541ceed0f5.png)

**Comment by vlstv** [comment]
doesn't work for me as well

**Comment by bryant-the-coder** [comment]
> OS: PopOS
> Nvim Version: v0.7.0-dev
> Nvim-tree-version: I just update this plugin, but i don't know how to check version of this
> Bug: auto-close not work
> Step to reproduce: Close the buffer while the tree open
> ![image](https://user-images.githubusercontent.com/20679090/154821320-5bb5890e-3399-441b-9101-61b3fae7a303.png)
> 
> 
> ![image](https://user-images.githubusercontent.com/20679090/154821325-f99e34a5-fe2a-48d1-a188-85541ceed0f5.png)
> 

font? it doesn't work for me as well

**Comment by kyazdani42** [comment]
cannot reproduce, can you provide your configuration and the exact steps to reproduce ?

**Comment by tin-pham** [comment]
Open like this
![image](https://user-images.githubusercontent.com/20679090/154866176-398af319-e6de-4ffc-aa4f-2849d34c74a1.png)
While the cursor in the buffer, press :wq or :q to quit 

The tree still live
![image](https://user-images.githubusercontent.com/20679090/154866195-98acb33b-e971-4811-b4b4-c9df3179f825.png)


I don't know but other people have the same issue as me, I think that the new update problem, when I update this issue start occur

**Comment by kyazdani42** [comment]
cannot reproduce, can you share you complete nvim-tree configuration ?
Also if you are using packer, you can navigate to `~/.local/share/nvim/site/pack/packer/start/nvim-tree.lua` and do a `git log`

**Comment by tin-pham** [comment]
> cannot reproduce, can you share you complete nvim-tree configuration ? Also if you are using packer, you can navigate to `~/.local/share/nvim/site/pack/packer/start/nvim-tree.lua` and do a `git log`

https://github.com/tin-pham/NeoVimLua

nvim-tree inside lua/nvim-tree-config

**Comment by kyazdani42** [comment]
cannot reproduce with your config :/ are you sure you are on latest master ?

**Comment by tin-pham** [comment]
> cannot reproduce with your config :/ are you sure you are on latest master ?

Yep i have updated to the last master
![image](https://user-images.githubusercontent.com/20679090/155241989-0ecc6c86-1162-4b18-b0ca-7b0da9bd0e97.png)

Some hour ago I saw the auto-close fix update, but it still not work

**Comment by bryant-the-coder** [comment]
@tin-pham what is your font? Auto close works for me now xD

**Comment by tin-pham** [comment]
> @tin-pham what is your font? Auto close works for me now xD

I used Operator Mono. I still have no luck 😞

**Comment by bryant-the-coder** [comment]
so, i was mistaken xD... it didnt close by itself. Do u hvlave operator mono the latest version? @tin-pham

**Comment by tin-pham** [comment]
> so, i was mistaken xD... it didnt close by itself. Do u hvlave operator mono the latest version? @tin-pham

I don't know, I installed it 3-4 month ago

**Comment by tin-pham** [comment]
For a couple of day, now i have figured it out that NeoVim problem, i reinstall it again and now it worked.

**Comment by tin-pham** [comment]
=)), it sooooo weird, after coding for a little while, it can't auto close again

**Comment by bryant-the-coder** [comment]
xD i hv nvim tree just in case

**Comment by kyazdani42** [comment]
@nobleach what you describe has nothing to do with this issue. Try setting `open_on_tab` to false.

Sorry people but i cannot reproduce this issue, i'll leave it open if someone wants to give a shot at fixing it.

**Comment by nobleach** [comment]
> @nobleach what you describe has nothing to do with this issue. Try setting `open_on_tab` to false.
> 
> Sorry people but i cannot reproduce this issue, i'll leave it open if someone wants to give a shot at fixing it.

Then I'm very sorry, I'll open another issue as `open_on_tab` still won't close the tree when I open a file in a new tab.

**Comment by clee088** [comment]
Are you calling, `require'nvim-tree'.setup {}` twice by any chance?  When I first configured nvim-tree via packer, I included `config = function() require'nvim-tree'.setup {} end`; however, I also set up an individual config file, with `auto_close = true`,  which called the setup function again.  Removed the call to setup in my packer plugins file and got `auto_close` to work.

**Comment by pagankeymaster** [comment]
After making changes you should recompile packer plugin specifications better known as the `:PackerCompile` command (assuming you're using `packer.nvim`)
See if this helps:

https://user-images.githubusercontent.com/80379926/158729032-f39ae2fb-fddc-46ad-9f6a-2a1c781d8aed.mp4

My [config](https://github.com/pagankeymaster/KrakenVim/blob/main/lua/configs/workflow/nvimtree.lua).

**Comment by nobleach** [comment]
I truly appreciate the time you took to put this together! Unfortunately, `PackerCompile` seems to do nothing. I see you have a notification plugin that alerts you to its success. I'd typically see some sort of success message in my command lines. I see no indication that anything is happening at all. I do notice your config differs quite a bit from mine, so I might look at wiping my nvim-tree config (it's from almost a year ago) and starting from scratch.

**Comment by pagankeymaster** [comment]
Ah.. you should do that then. But, note that if you're lazy loading the plugin then you'd need to set the [global variables](https://github.com/kyazdani42/nvim-tree.lua/blob/master/README.md?plain=1#L39) beforehand.. (before the plugin is loaded) naturally that you mean that you wouldn't be able to override it's behavior if your using the config key and it'll use defaults! The [require part](https://github.com/kyazdani42/nvim-tree.lua/blob/master/README.md?plain=1#L108) doesn't matter.. you can set it anywhere.
```lua
-- Putting everything in config won't work.
use {
  "kyazdani42/nvim-tree.lua",
  cmd = { "NvimTreeToggle", "NvimTreeRefresh", "NvimTreeFocus" },
  config = require "nvimtree",
}
```
This works for me IMO
```lua
use {
  "kyazdani42/nvim-tree.lua",
  cmd = { "NvimTreeToggle", "NvimTreeRefresh", "NvimTreeFocus" },
  setup = require("configs.workflow.nvimtree").before,
  config = require("configs.workflow.nvimtree").after,
  wants = "nvim-notify",
}
```
**NOTE**: This only applies if you're lazy loading.
Also, don't forget to compile. Atleast compile/restart 4 times lmao.

**Comment by kyazdani42** [comment]
@nobleach do not worry about opening a new issue if you have a bug or something you cannot manage to fix. Even if it is an opensource project on people free time, we chose whenever we have time for it, it's not like it's a burden :smile:
And yes, you should update your config, it has changed quite a lot in the past year.

**Comment by lgds-01** [comment]
i also meet this problem.And I find when I close the buffer first using :wq, I press q to close the tree, and then the origin buffer will reappear, which means i dont close the buffer completely or reopen the buffer? Need help

**Comment by lgds-01** [comment]
When I use the following settings, this question seems to be solved. But another question appears. When I close one of the buffers(yes, I open many buffers, so there is not only the tree in a window), all of the buffers and tree are closed.
Here is my plugins.lua
```shell
use {
    'kyazdani42/nvim-tree.lua',
    requires = {
      'kyazdani42/nvim-web-devicons', -- optional, for file icon
    },
    config = function() require'plugin-config.nvim-tree' end
}
```
Here is my plugin-config/nvim-tree.lua
```shell
require'nvim-tree'.setup {
  auto_close = true,
  git = {
      enable = false
  }
}
``` 
Here is my directory structure
```shell
├── init.lua
├── lua
│   ├── basic.lua
│   ├── keybindings.lua
│   ├── lsp
│   │   ├── lua.lua
│   │   ├── nvim-cmp.lua
│   │   └── setup.lua
│   ├── plugin-config
│   │   ├── bufferline.lua
│   │   ├── nvim-tree.lua
│   │   └── nvim-treesitter.lua
│   └── plugins.lua
└── plugin
    └── packer_compiled.lua
```

**Comment by alex-courtis** [comment]
> But another question appears. When I close one of the buffers(yes, I open many buffers, so there is not only the tree in a window), all of the buffers and tree are closed.

Could you please raise a new [bug report](https://github.com/kyazdani42/nvim-tree.lua/issues/new/choose) for this @lgds-01 ? It will get lost in this issue otherwise ;)

**Comment by kyazdani42** [comment]
@alex-courtis i've been thinking of removing the auto_close functionnality since it behaves strangely for many people, and provide a documentation example on how this could be achieved. What do you think about that ?

**Comment by alex-courtis** [comment]
I used to use something like [How can I close Vim or a tab automatically when NERDTree is the last window?](https://github.com/preservim/nerdtree#how-can-i-close-vim-or-a-tab-automatically-when-nerdtree-is-the-last-window). I think I removed it as it did not work reliably or threw exceptions.

`BufEnter` can be problematic: the state of other buffers/tabs/windows is not always their correct state at the time of the event. Some plugins etc. do not use `++nested` on their autocommands, which adds more confusion as events are "lost".

Remove `auto_close`. It is of questionable value and just causes problems. We can point users to an example similar to NERDTree's if they wish to live dangerously.

**Comment by alex-courtis** [comment]
We could put it in the Tips and Reminders section:

6. You can automatically close nvim-tree when it is the last window in the tab. WARNING: other plugins or automation may interfere with this:
```vim
autocmd BufEnter * ++nested if winnr('$') == 1 && bufname() == 'NvimTree_' . tabpagenr() | quit | endif
```
7. ...

**Comment by kyazdani42** [comment]
in your configuration, where you want

**Comment by tomkimsour** [comment]
> in your configuration, where you want

But this is not lua right? So what if I want to put it in a lua file ?

**Comment by WingLim** [comment]
> 

You can call `nvim_create_autocmd` to use it like this

```lua
vim.api.nvim_create_autocmd('BufEnter', {
    command = "if winnr('$') == 1 && bufname() == 'NvimTree_' . tabpagenr() | quit | endif",
    nested = true,
})
```

**Comment by beauwilliams** [comment]
This does not work for be but manually running `:if winnr('$') == 1 && bufname() == 'NvimTree_' . tabpagenr() | quit | endif` does close the window.

Must be something to do with BufEnter. I suspect maybe caused by wilder.nvim?

**Comment by beauwilliams** [comment]
Still does not work for me on my setup. Pretty sure issue with wilder.nvim. Anyways. I propose we update readme as this method is cleaner and will fire less often.
 
```
vim.api.nvim_create_autocmd('Filetype', {
    pattern = "NvimTree",
    command = "if winnr('$') == 1 && bufname() == 'NvimTree_' . tabpagenr() | quit | endif | echo 'hello'",
    nested = true,
})
```

**Comment by alex-courtis** [comment]
> Still does not work for me on my setup. Pretty sure issue with wilder.nvim.

This "solution" is very hacky and is unlikely to work in complex configurations, hence we removed it from nvim-tree

> I propose we update readme as this method is cleaner and will fire less often.

Does the FileType approach work more reliably?

**Comment by Mariownyou** [comment]
why auto-close feature was removed? I don't need tree every time I open the file. How can I disable this?

**Comment by alex-courtis** [comment]
> why auto-close feature was removed? I don't need tree every time I open the file. How can I disable this?

auto_close would close vim/tab when nvim-tree was the last window.

I think the functionality you want is `:help nvim-tree.actions.open_file.quit_on_open`

**Comment by Mariownyou** [comment]
Thanks, this is really what I was looking for

**Comment by YanzhaoW** [comment]
> 



> > 
> 
> You can call `nvim_create_autocmd` to use it like this in lua:
> 
> ```lua
> vim.api.nvim_create_autocmd('BufEnter', {
>     command = "if winnr('$') == 1 && bufname() == 'NvimTree_' . tabpagenr() | quit | endif",
>     nested = true,
> })
> ```

This is really bad. It can cause neovim to break if you accidentally quit without saving. After that you have to shut down the whole terminal to quit neovim.

**Comment by kyazdani42** [comment]
@YanzhaoW do not use it if you don't want to.

**Comment by alex-courtis** [comment]
This is getting silly. There is no solution here and we will not build one, nor support hacks to do it:
- remove from readme/tips
- add a note to help or readme like "Functionality to automatically close the tab/vim when nvim-tree is the last window in the tab is not present and will not be added, due to complexities in vim's event system."

@kyazdani42 ?

**Comment by kyazdani42** [comment]
I wouldn't remove it from the readme since people might just ask how to do it again, but maybe adding more information about why we will not help people with this might be useful.

**Comment by theopn** [comment]
> > 
> 
> > > 
> > 
> > 
> > You can call `nvim_create_autocmd` to use it like this in lua:
> > ```lua
> > vim.api.nvim_create_autocmd('BufEnter', {
> >     command = "if winnr('$') == 1 && bufname() == 'NvimTree_' . tabpagenr() | quit | endif",
> >     nested = true,
> > })
> > ```
> 
> This is really bad. It can cause neovim to break if you accidentally quit without saving. After that you have to shut down the whole terminal to quit neovim.

It is not elegant, but you certainly do not have to close the terminal to close the Neovim. Just don't repeatedly type `:q` to produce million error message, use `q:` to bring up the command history and choose `wq` or `q!` to close the buffer.

**Comment by alex-courtis** [comment]
> I wouldn't remove it from the readme since people might just ask how to do it again, but maybe adding more information about why we will not help people with this might be useful.

Done

**Comment by PROxZIMA** [comment]
Here's a small change to make it work with unsaved files.

Also I'm extremely new to `neovim` and `lua` stuff so any suggestions are welcomed.

```lua
-- nvim-tree is also there in modified buffers so this function filter it out
local modifiedBufs = function(bufs)
    local t = 0
    for k,v in pairs(bufs) do
        if v.name:match("NvimTree_") == nil then
            t = t + 1
        end
    end
    return t
end

vim.api.nvim_create_autocmd("BufEnter", {
    nested = true,
    callback = function()
        if #vim.api.nvim_list_wins() == 1 and
        vim.api.nvim_buf_get_name(0):match("NvimTree_") ~= nil and
        modifiedBufs(vim.fn.getbufinfo({bufmodified = 1})) == 0 then
            vim.cmd "quitall"
        end
    end
})
```

**Comment by willchao612** [comment]
> Open like this ![image](https://user-images.githubusercontent.com/20679090/154866176-398af319-e6de-4ffc-aa4f-2849d34c74a1.png) While the cursor in the buffer, press :wq or :q to quit
> 
> The tree still live ![image](https://user-images.githubusercontent.com/20679090/154866195-98acb33b-e971-4811-b4b4-c9df3179f825.png)
> 
> I don't know but other people have the same issue as me, I think that the new update problem, when I update this issue start occur

@tin-pham Not related to this issue, but I cannot seem to find an answer to this elsewhere. What is it that made this fancy italic on, for example, "require" and "setup"? I have installed the tree-sitter but it is not doing this. Is this another plugin that you are using or some other feature? I am also using Operator Mono BTW, if that helps.

**Comment by alex-courtis** [comment]
@PROxZIMA  I have added a [wiki page](https://github.com/nvim-tree/nvim-tree.lua/wiki/Auto-Close) covering auto close.

I have added the above solution as it does function in a minimal setup. Please update if you have any new discoveries or enhancements!

**Comment by carlos-rodrigo** [comment]
The easiest way I found to do this is following the docs and setup the plugin in this way
```
require("nvim-tree").setup {
  actions = {
    open_file = {
      quit_on_open = true,
    },
  },
}
```

**Comment by ruperlopez** [comment]
In what part of my config should I put the function(s) provided? 
I tried in both: nvim-tree.lua and also as a config inside of my packer manager file. Neither worked.

**Comment by gegoune** [comment]
@ruperlopez What functions? This seems like a generic configuration question, not an issue, please ask under Discussions.
