### ISSUE TITLE
Cannot expand symlinks linked to directories

### ISSUE THREAD

**Issue by chinnkarahoi** [kyazdani42/nvim-tree.lua#101]
Create a symlink to a directory, but cannot list files by opening the symliink within this plugin.

**Comment by kyazdani42** [comment]
please explain

**Comment by smartding** [comment]
symlinks are useful to me too.
I work in an open source project where parts of the source tree are symlinks to other parts.

**Comment by yamatsum** [comment]
If it is a directory symbolic link, the icon should also be a directory!

**Comment by kyazdani42** [comment]
hum i do not agree, it would not be clear the link is a link, maybe adding an icon after the arrow to indicate which filetype it is (or directory).

**Comment by yamatsum** [comment]
Other well-known filer plugins such as Nedtree and coc-explorer can open directory symlinks.
There is also an icon for it.
https://github.com/ryanoasis/vim-devicons/pull/221
https://github.com/weirongxu/coc-explorer/blob/880818c79297cfdd677926bbb5c902d6e9d25278/src/icons.nerdfont.json#L11-L13

**Comment by kyazdani42** [comment]
i like the way vim-devicons does it. I'll add that at some point if nobody wants to give it a shot

**Comment by kyazdani42** [comment]
fixed in master. Open an issue if you want more customizations over the link status
