### ISSUE TITLE
Is it possible to disable resizing splits when opening / closing nvim-tree?

### ISSUE THREAD

**Issue by riddlew** [kyazdani42/nvim-tree.lua#1010]
I really like this plugin and this is the only thing that bothers me about it. I like to keep my buffers a specific size, such as keeping an open todo file as a very narrow split buffer on the side. However, whenever I open or close nvim-tree, it resizes the buffers to be equal size. Is it possible to disable this so I don't have to constantly resize my splits any time I open or close nvim-tree? Or does the plugin rely on this to work?

**Comment by kyazdani42** [comment]
Hi ! does #999 fix you issue ? You'll have to set the option to false

**Comment by riddlew** [comment]
Unfortunately it did not fix the issue. Here is a picture of what happens when I use it (left) vs what I'm trying to achieve (right). https://imgur.com/a/ULKIWTy

**Comment by riddlew** [comment]
> Hi ! does #999 fix you issue ? You'll have to set the option to false

Unfortunately that did not fix the issue. Here is a picture of what happens (left) vs what I'm trying to achieve (right). https://imgur.com/a/ULKIWTy

**Comment by kyazdani42** [comment]
just a mistake about me, set the option to true it should preserve the window size

**Comment by riddlew** [comment]
I did try it as true, but it did not work (ignore the fact that the screen shot shows it in 'true' quotes, I corrected that afterwards and it still did not work)

**Comment by rlch** [comment]
Have you tried using [kwkarlwang/bufresize.nvim](https://github.com/kwkarlwang/bufresize.nvim)? I haven't come across this problem and I suspect this plugin is why.

@kyazdani42 thoughts on having this functionality supported out-of-the-box? It could make sense if `preserve_window_proportions` also accounts for this use-case. If so I'm happy to include in #999.

**Comment by riddlew** [comment]
@rlch I just installed bufresize to see if it would work, and it did not fix the issue. It did work for toggleterm so I can confirm the plugin was working correctly, however even with bufresize and nvim-tree from commit 99f93edc62e4a87e6794b6f616a97714007eacf5 with `preserve_window_proportions = true` did not seem to work.

**Comment by kyazdani42** [comment]
hi @riddlew i think this is because the PR has one last window resize to guard for.

**Comment by alex-courtis** [comment]
https://github.com/kyazdani42/nvim-tree.lua/commit/5af3cfa1 along with `actions.open_file.resize_window` implements this feature.

Please open an issue if you experience further problems.

**Comment by xbladesub** [comment]
same issue, ```lua preserve_window_proportions = true``` doesn't work

**Comment by kyazdani42** [comment]
@xbladesub please open a new issue and follow the template. "Doesnt work" doesn't help us understand where the issue comes from.
