### ISSUE TITLE
Strange behavior on closing/deleting current buffer.

### ISSUE THREAD

**Issue by kevinm6** [kyazdani42/nvim-tree.lua#1012]
**OS**
> macOS Monterey, 12.0.1 (21A559)

**Neovim version**
> NVIM v0.6.1
> Build type: Release
> LuaJIT 2.1.0-beta3
> Compiled by brew@Monterey

**Nvim-tree version**
master, commit [41f515e](https://github.com/kyazdani42/nvim-tree.lua/commit/41f51508e368e01910bd371e75610d6f301558b0)

**Describe the bug**
When closing/delete current buffer,  nvim-tree gains focus but it occupies all the window and to get again the view of the other buffers I have to pass from nvim-tree or use the mouse to click on the relative tab.

**To Reproduce**
Open more than one buffer with nvim-tree open, focus on one buffer and close or delete it.

**Expected behavior**
I suppose that on closing/deleting a buffer, the focus will be gained by the next/previous buffer open or even nvim-tree, but the window of that buffer became the new one that replace the deleted/closed one.

https://user-images.githubusercontent.com/72861758/154839617-8f21b480-cde2-42f8-ab2e-9f9bfae56f7c.mov

**Comment by kyazdani42** [comment]
well this is not really expected, as replacing a buffer by another one is not a default in neovim when closing a window.
This is something out of the scope of nvim-tree, because this should be done in your config by binding a command to do that.
for instance: `command CloseReplace :bd | :bnext`

**Comment by OuJin-Show** [comment]
This is my configuration, try to use <C-d> to close the current buffer
``` vim
function! DeleteCurrentBuffer()
    let current_buffer_number = bufnr('%')
    let buffer_list = getbufinfo({'buflisted':1})
    let buffer_number = len(buffer_list)
    if buffer_number <= 1
        execute 'bdelete'
    elseif current_buffer_number == buffer_list[buffer_number-1].bufnr
        execute 'bprevious|bdelete #'
    else
        execute 'bnext|bdelete #'
    endif
endfunction
noremap <C-d> :call DeleteCurrentBuffer()<CR>
```
