### ISSUE TITLE
Help not showing `H` information

### ISSUE THREAD

**Issue by danymat** [kyazdani42/nvim-tree.lua#1016]
https://github.com/kyazdani42/nvim-tree.lua/blob/95df001185d2fac18cf36e66bc56e0eb19140469/doc/nvim-tree-lua.txt#L589-L597

Hello, it seems that the `H` information means to toggle dot files, however it is not listed in the help section above. Is it possible to add it ?

**Comment by kyazdani42** [comment]
done :)
