### ISSUE TITLE
packer.nvim: Error running config for nvim-tree.lua: attempt to call a nil value 

### ISSUE THREAD

**Issue by anurag3301** [kyazdani42/nvim-tree.lua#1017]
**OS**
Linux arch 5.16.10-arch1-1 #1 SMP PREEMPT Wed, 16 Feb 2022 19:35:18 +0000 x86_64 GNU/Linux

**Neovim version**
NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser

**Nvim-tree version**
master, 95df001185d2fac18cf36e66bc56e0eb19140469

**Describe the bug**
Not Sure what it is but getting this error when I open nvim
![image](https://user-images.githubusercontent.com/52702259/154886737-9c824174-579b-437e-b879-3e7abfd955ca.png)
Dont have any clue whats the mistake in the config

**To Reproduce**
I have stock nvim config installed using packer.nvim

**Comment by anurag3301** [comment]
Nvim-tree config
```lua
require'nvim-tree'.setup {
  disable_netrw       = true,
  hijack_netrw        = true,
  open_on_setup       = false,
  ignore_ft_on_setup  = {},
  auto_close          = true,
  open_on_tab         = false,
  update_to_buf_dir   = {
    enable = true,
    auto_open = true,
  },
  hijack_cursor       = false,
  update_cwd          = false,
  diagnostics = {
    enable = false,
    icons = {
      hint = "",
      info = "",
      warning = "",
      error = "",
    }
  },
  update_focused_file = {
    enable      = false,
    update_cwd  = false,
    ignore_list = {}
  },
  system_open = {
    cmd  = nil,
    args = {}
  },

  view = {
    width = 30,
    height = 30,
    side = 'left',
    auto_resize = false,
    mappings = {
      custom_only = false,
      list = {}
    }
  }
}
vim.cmd("let g:nvim_tree_quit_on_open = 1")
```
Inside Packer config
```lua
  use {
    'kyazdani42/nvim-tree.lua',
    requires = 'kyazdani42/nvim-web-devicons',
    config = function() require'nvim-tree'.setup {} end
  }
```

**Comment by kyazdani42** [comment]
hi, did you run `:PackerSync` ?

**Comment by anurag3301** [comment]
Sorry, I ran only `:PackerUpdate`, Didnt know I have to use that. Thanks for letting me know.
BTW one problem `quit_on_open` isn't working
```lua
vim.cmd("let g:nvim_tree_quit_on_open = 1")
```
Did some changes have been made for this? I want nvim to close as I open a file.

**Comment by kyazdani42** [comment]
check `:help nvim-tree.actions`. quit on open was moved in the setup.
Closing this then :)
