### ISSUE TITLE
Error upon opening in a directory with spaces

### ISSUE THREAD

**Issue by nathunsmitty** [kyazdani42/nvim-tree.lua#102]
Setup: I have a project tracked with git in the following path `~/dir with spaces/my-project`. When opening `my-project` with Neovim, I get the following error:

```
Error detected while processing VimEnter Autocommands for "*":                                                                                                                                                                          
E5108: Error executing lua ...g/nvim/pack/packager/start/nvim-tree.lua/lua/lib/git.lua:69: attempt to concatenate local 'git_root' (a nil value)                                                                                        
Press ENTER or type command to continue
```

This error does not occur if the path to my project does not include spaces.

I did some sleuthing on this error and found that the `path` arg of `get_git_root` is formatted as:  `~/dir\ with\ spaces/my-project` whereas `roots` expects the path with spaces not escaped by `\`. Stripping the `\`s from the path fixes the issue for me.

Happy to make a PR for this but figured I'd raise as an issue first to see if anyone more familiar with the code has a better solution.

I'm on macOS Catalina, would be curious if this issue and fix work the same way on Linux.

**Comment by kyazdani42** [comment]
this is #28 :) You are the first one to exactly pin point where the issue comes from, so thanks for that, i'll push a small refactoring of this git path matching today ! it happens on linux too

**Comment by kyazdani42** [comment]
thanks, i've had this error since a long time and i didn't know how to reproduce it ! Many many thanks :)

**Comment by nathunsmitty** [comment]
Ah sorry I missed the earlier issue! Glad I could help 🙂
