### ISSUE TITLE
is there a way to move the cursor from nvim-tree to the other window automatilcly when a file is specified?

### ISSUE THREAD

**Issue by ghost** [kyazdani42/nvim-tree.lua#1020]
the current behavior is that nvim tree takes the focus [cursor] when i open a file, i want nvim tree to detect that i opend a file and  give the focus [cursor] to the file that i want to edit here is an example that is been used by nerd tree i want this from nvim tree [sorry for my bad english im not a native american]

[ " Start NERDTree. If a file is specified, move the cursor to its window.
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * NERDTree | if argc() > 0 || exists("s:std_in") | wincmd p | endif ]

I Want Nvim Tree To change Focus when i open a file  From this 

![pic2](https://user-images.githubusercontent.com/100243267/155417377-5c206f01-3071-4e4f-8d8d-1dcf36b5a1e9.png)

To This automatically

![1pic2](https://user-images.githubusercontent.com/100243267/155417549-7a38c99f-eba2-46a2-a21f-62b5b2872a46.png)

any help will Appreciated

**OS**
Arch linux 

**Neovim version**
NVIM v0.6.1

**Nvim-tree version**
1.6.7

**Comment by kyazdani42** [comment]
I don't understand your issue. Isn't this default behavior ?

**Comment by micro-aries** [comment]
i didn't explaing my issue very well, here what i was referring to, i want nvim-tree to detect that i opened i file and give the cursor [the focus] to the file that i'm editing instead of keeping it on it's buffer, the current behavior is that nvim-tree keep the cursor on its buffer until i move it manually to the file that i'm editing i hope that make sense, when i was running nerd tree there was an option to do exactly that 

[ " Start NERDTree. If a file is specified, move the cursor to its window.
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * NERDTree | if argc() > 0 || exists("s:std_in") | wincmd p | endif ]

**Comment by micro-aries** [comment]
yes @alex-courtis that's exactly what i'm talking about, i disabled this option that you referring to `open_on_setup` and enabled this option `require"nvim-tree".toggle(true, true) ` which does the same as `open_on_setup` but it toggle nvim-tree with an empty buffer or with a file, the only thing that is missing is the cursor \ focus stays on the nvim-tree buffer 
is what you said this is feature request and it will be much better to have this option.

**Comment by alex-courtis** [comment]
It is up to @kyazdani42 to decide whether to add this feature.

This can be automated around, however that is undersirable. Something like this (incomplete, untested) on startup:
```vim
if strlen(bufname()) == 0
  NvimTreeOpen
else
  NvimTreeFindFile
  wincmd p
endif
```

**Comment by micro-aries** [comment]
the command  ` wincmd p` change focus to the buffer that the file but only if the option `open_on_setup` not with this `require"nvim-tree".toggle(true, true)`
yes like what you said  (incomplete, untested)

**Comment by alex-courtis** [comment]
Yes, you would need to disable open_on_setup; that automation is to replace it.

**Comment by kyazdani42** [comment]
@micro-aries you need to pass false the 2nd parameter of toggle if you don't want to focus the tree.

**Comment by alex-courtis** [comment]
Options have been added to allow this functionality. See:

`:help nvim-tree.open_on_setup`
`:help nvim-tree.open_on_setup_file`

You can further customise:
`:help nvim-tree.ignore_buffer_on_setup`
`:help nvim-tree.ignore_ft_on_setup`

Please reopen if you have any further questions or this functionality doesn't meet your use case.

**Comment by alex-courtis** [comment]
(reporter is a @ghost who no longer exists)
