### ISSUE TITLE
Is there a way to `chmod` a file?

### ISSUE THREAD

**Issue by ofirgall** [kyazdani42/nvim-tree.lua#1021]

**Comment by kyazdani42** [comment]
there is not. With https://github.com/kyazdani42/nvim-tree.lua/pull/1024 you'll be able to run any command on the file

**Comment by Gelio** [comment]
With #1024 merged, it is possible now :smile: After focusing the file you want to `chmod`, press `.` and then use the `:!` vim command to run a shell command

```
:!chmod file_path_here
```

You will notice `file_path_here` will be the path to the currently focused file.

I believe we can close this issue

**Comment by kyazdani42** [comment]
indeed, thanks @Gelio for noticing
