### ISSUE TITLE
C-t for opening files in new tab does not work

### ISSUE THREAD

**Issue by neunenak** [kyazdani42/nvim-tree.lua#1026]
**OS**
Arch linux

**Neovim version**
output of `nvim --version`
```
NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Nvim-tree version**

commit `48e76bc0317de95ac154ae3a26193bf8881340a1`

I install nvim-tree using Packer with the configuration:

```
    use {
        'kyazdani42/nvim-tree.lua',
        requires = 'kyazdani42/nvim-web-devicons',
        config = function() require'nvim-tree'.setup
            { hijack_unnamed_buffer_when_opening = false, open_on_tab = true, hijack_cursor = true, auto_close = true }
        end
    }
```

**Describe the bug**

Pressing C-t while having the cursor over an entry in nvim-tree causes the new file to replace the contents of the current tab, not open that file in a new tab.

**To Reproduce**

Invoke `:NvimTreeToggle` to open up nvim-tree, move the cursor over a file, then hit C-t.

**Expected behavior**

A new nvim tab should be opened.

**Comment by kyazdani42** [comment]
Can reproduce, i'll tackle this soon

**Comment by kyazdani42** [comment]
should be fixed in latest master
