### ISSUE TITLE
Improve Bug Report Template

### ISSUE THREAD

**Issue by alex-courtis** [kyazdani42/nvim-tree.lua#1033]
It is often necessary to ask users to provide their opts after they create the bug report. It might be better to be proactive.

Adding configuration and plugin sections.

Reducing version to short commit hash, as we are not using tags or branches right now.

# Proposal

**OS**
Operation system's name and version

**Neovim version**
output of `nvim --version`

**Nvim-tree version**
nvim-tree commit: `cd <your-package-directory>/nvim-tree.lua` `git log --format="%h" -n 1`

**Nvim-tree configuration**
```lua
require'nvim-tree'.setup {
	...
}
```

**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior

**Expected behavior**

**Comment by gegoune** [comment]
I think removing `Other Plugins` and providing minimal required configuration (see [telescope's one](https://github.com/nvim-telescope/telescope.nvim/blob/master/.github/ISSUE_TEMPLATE/bug_report.yml) for example) will shift responsibility of providing easily reproducible configuration to users. Otherwise I can easily see responses like 'I don't know', 'I don't think so', etc requiring further effort from @kyazdani42.

**Comment by alex-courtis** [comment]
> I think removing `Other Plugins`

That is reasonable. Removed.

**Comment by alex-courtis** [comment]
> providing minimal required configuration

I like that. I have a minimal configuration that I use for local dev/test; having one for users would be fantastic. Also, using the "textbox" approach is a big improvement.

I never knew that the template was stored in the repo... now I can create a proper PR for it.

AC actions:

1. Create minimal config (I would be grateful for your testing/feedback @gegoune)
2. Upgrade template as per telescope's
3. PR

**Comment by alex-courtis** [comment]
Idea: script to scrape DEFAULT_OPTS from nvim-tree.lua and update README.md, nvim-tree-lua.txt and the issue template.

**Comment by kyazdani42** [comment]
I'd be 100% for it. I actually thought about adding that a few times. Oh man the telescope template is great. I'm losing so much time asking the same thing over and over again :smile:
The feature request template could be added too, the issues are basically 60 feature requests against 10 bugs :smile:

**Comment by alex-courtis** [comment]
I'll look at bug first, then feature.

I really enjoy using bug templates like that - it forces me to enter all the necessary information, highlights things I had not considered and makes it easy to create a reproducible test case.

**Comment by kyazdani42** [comment]
I've added the feature template yesterday :)
