### ISSUE TITLE
nvim-tree keep resizing with `auto_resize=false` option

### ISSUE THREAD

**Issue by Avimitin** [kyazdani42/nvim-tree.lua#1034]
**OS**
Arch Linux 5.16.10

**Neovim version**

NVIM v0.7.0-dev+1129-g30c9c8815b

**Nvim-tree version**

Master branch. Latest commit:  3d8912ca53e6407063d07bad0e14d9e12c476f16

**Describe the bug**

After resizing the nvim-tree panel, if I open a new file, the nvim-tree panel will resize back to the default size.

**To Reproduce**

`:NvimTreeToggle` => `:vertical resize-10` => Open new file with enter.

**Expected behavior**

I've set view.auto_resize = false, so it should keep the sizes.

**Comment by kyazdani42** [comment]
you should move the definition to `actions.open_file.resize_window` now :)
