### ISSUE TITLE
Focus current buffer when using nvim-tree in "vinegar" mode

### ISSUE THREAD

**Issue by steliyan** [kyazdani42/nvim-tree.lua#1038]
## Is your feature request related to a problem? Please describe.
Focus current buffer when using **nvim-tree** in "vinegar" mode

## Additional context
I am testing out the "vinegar"-style of **nvim-tree**, but what's bugging me is that the `cwd` is set to the buffer's dir and that the buffer itself is not focused.

## Describe the solution you'd like
The perfect solution for me is to actually keep the UI state (collapsed/expanded dirs) and the tree and focus the buffer you're coming from.

## Describe alternatives you've considered
That's what I am using, heavily inspired by [your code](https://github.com/kyazdani42/nvim-tree.lua/blob/0e7856fd8de18edaaee8fa0c2f2c9432c973aef5/lua/nvim-tree.lua#L48).

```lua
M.open_replacing_current_buffer = function()
  if view.is_visible() then
    return
  end

  local buf = vim.api.nvim_get_current_buf()
  local bufname = vim.api.nvim_buf_get_name(buf)
  if bufname == '' or vim.loop.fs_stat(bufname) == nil then
    return
  end

  lib.init(vim.fn.getcwd())
  require('nvim-tree').find_file(false, buf)

  view.open_in_current_win({ hijack_current_buf = false, resize = false })
  require('nvim-tree.renderer').draw()
end
```

**Comment by kyazdani42** [comment]
i've just pushed a fix that should be less hacky :smile:
