### ISSUE TITLE
Change the sort order

### ISSUE THREAD

**Issue by bdwiel** [kyazdani42/nvim-tree.lua#1039]
**Is your feature request related to a problem? Please describe.**
I use nvim to edit my notes with ~/notes. This dir has dozens of files and it'd be nice to sort by recently updated instead of always alphabetically.

**Describe the solution you'd like**
An option passed to setup like `sort_order = "modification_time"` or similar. A second option to control if dirs are always ordered first or not might be good, too.

**Describe alternatives you've considered**
None

**Comment by kyazdani42** [comment]
this could be extended indeed. If you make a clean PR that doesn't affect performance too much i'd gladly accept it :)
