### ISSUE TITLE
Support opening a folder from NvimTreeOpen

### ISSUE THREAD

**Issue by xaljer** [kyazdani42/nvim-tree.lua#104]
- open from working directory
- open from root directory of VSC repository
- open from directory which current file in

**Comment by kyazdani42** [comment]
not sure what this means.

**Comment by doubleloop** [comment]
@xaljer please correct me if I am wrong, here is how I understand this might work:

Here is example directory tree:
```
$ cd ~/tmp/example_workspace
$ tree
.
├── notes.txt
├── project1
│   ├── README.md
│   └── src
│       └── main.c
└── project2
    └── foo.py
```
### open from working directory
```
$ cd project1
$ vim
```
inside vim
```vim
:cd src
:LuaTreeOpen
```
expected tree root: `~/tmp/example_workspace/src` (same as if you run `:pwd` inside (n)vim)
(actual tree root: `~/tmp/example_workspace`)

### open from root directory of VSC repository
```
$ cd project1
$ git init
$ cd src
$ vim +LuaTreeOpenVSCRoot
```
expected tree root: ~/tmp/example_workspace/project1 (same as if you run `$ git root`)

### open from directory which current file in

```
$ cd project1
$ vim
```
inside vim
```vim
:e src/main.c
:LuaTreeOpenFileRoot    ; expected tree root: ~/tmp/example_workspace/src
:e ../project2/foo.py
:LuaTreeOpenFileRoot    ; expected tree root: ~/tmp/example_workspace/project2
:e ~/.bashrc
:LuaTreeOpenFileRoot    ; expected tree root: ~/
```

note: LuaTreeOpenFileRoot root could be also used as fallback for `LuaTreeFindFile` if edited file is not under current working directory.

**Comment by xaljer** [comment]
sorry i am not actually used this plugin, i am just finding a tree plugin to fit my workflow. Thanks for @doubleloop 's example, and it almost explain what i want. My usage is in the Android like system development, as description below:
```
my workspace
.repo/                           <- :pwd in vim (1)
    git_repo_1/
        .git/                   <- (2)
        src/
        this/is/a/deep/path/      <- (3)
             some_file
    git_repo_2/
    so many git repos ...
```
so, in a huge directory tree, I just want to explore files in part of path, that's open the tree view from different level of the whole workspace. 

 - open from working directory: 1
 - open from root directory of VSC repository: 2
 - open from directory which current file in: 3

I have tried FindFiles command in nerd tree. But it locate current file a the whole workspace causing so many  indent (spaces) before the file name.

**Comment by kyazdani42** [comment]
this is not the purpose of this plugin, you can use vim-rooter to change de root of your vim pwd (which will automatically adapt the tree root).

**Comment by xaljer** [comment]
vim-rooter doesn't meet my need. First, my work-flow needs to keep the `pwd`. Second, I am not mean to open from one root always but sometimes for some root.
I think the most flexible way for a tree view plugin to implement this is that providing a parameter to let user open the tree from any path. So that user can specify the path by himself.

**Comment by kyazdani42** [comment]
well if you want to implement this go for it, i'll accept a PR :)

**Comment by peach-lasagna** [comment]
You want to create https://github.com/dbakker/vim-projectroot ?

**Comment by dgrabla** [comment]
I would also love to have an option to somehow :NvimTreeOpen with a specific path

**Comment by doubleloop** [comment]
> I would also love to have an option to somehow :NvimTreeOpen with a specific path

With path being optional argument user could for example:
*  `:NvimTreeOpen %:p:h` to open directory with current file in
*  `:exec('NvimTreeOpen ' . trim(system('git rev-parse --show-toplevel')))` to open root directory of git repository

**Comment by dgrabla** [comment]
A way to open nvim-tree on the current working directory (like telescope) instead of the project route would be also great.

**Comment by kyazdani42** [comment]
has been fixed, open can take a cwd argument
