### ISSUE TITLE
Keybinding to close currently opened directory

### ISSUE THREAD

**Issue by onsails** [kyazdani42/nvim-tree.lua#105]
It would be nice to have a keybinding which closes an opened directory under cursor or above it.
Such keybinding allows to explore nested roots more conveniently, like:

```
- src
  + foo
  - bar
     baz.c <-- cursor is here
```

press, for example, `<S-o>` to get this:

```
- src
  + foo
  + bar <-- cursor is here
```

repeat

```
+ src <-- cursor is here
```

**Comment by stsewd** [comment]
I think moving to the parent directory or between directories would be cool to have and maybe make this feature easy to implement or map.

**Comment by kyazdani42** [comment]
i think it would not be too hard, if someone want's to give it a try otherwise i'll do it when i have some time :)
