### ISSUE TITLE
Bug: sometimes the collapse command leads to duplicate file entries in the tree

### ISSUE THREAD

**Issue by be-ndee** [kyazdani42/nvim-tree.lua#1059]
### Description

This is a bug, I sometimes experience, but at the moment I don't have certain "rules" when this happens. I hope that somebody has an idea, when this could happen or which part of the code could be a possible problem, so we could narrow down the problem.

Sometimes when I use `W` to collapse the whole tree, it results in duplicate file entries in the tree-view. Given the following directories and files:

```
dir-a/
  file-a1
  file-a2
dir-b/
  file-b1
  file-b2
```

Now my nvim-tree window looks like this:

```
dir-a/
  file-a1
  file-a2
dir-b/
```

Then I use `W` and the nvim-tree looks like this (which is correct):

```
dir-a/
dir-b/
```

But then, when I open the `dir-a`, it will look like this:

```
dir-a/
  file-a1
  file-a1
  file-a2
  file-a2
dir-b/
```

And when I open `dir-b`, it looks like this:

```
dir-a/
  file-a1
  file-a1
  file-a2
  file-a2
dir-b/
  file-b1
  file-b2
```

**KEEP IN MIND:** This is just an example, it can also be possible, that the `dir-b` also has duplicate file entries. Or everything is correct. I think it depends on, which directories are expanded and which files are open in buffers, but I could not reproduce "rules" when this happens exactly...

### Neovim version

```markdown
NVIM v0.7.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-de1BJ3/neovim-0.7.0~ubuntu1+git202203050047-83fc91433-dd05b3569=. -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim-de1BJ3/neovim-0.7.0~ubuntu1+git202203050047-83fc91433-dd05b3569/build/config -I/build/neovim-de1BJ3/neovim-0.7.0~ubuntu1+git202203050047-83fc91433-dd05b3569/src -I/build/neovim-de1BJ3/neovim-0.7.0~ubuntu1+git202203050047-83fc91433-dd05b3569/.deps/usr/include -I/usr/include -I/build/neovim-de1BJ3/neovim-0.7.0~ubuntu1+git202203050047-83fc91433-dd05b3569/build/src/nvim/auto -I/build/neovim-de1BJ3/neovim-0.7.0~ubuntu1+git202203050047-83fc91433-dd05b3569/build/include
Compiled by buildd@lcy02-amd64-030

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

### Operating system and version

Linux 20.04.1-Ubuntu

### nvim-tree version

master

### Steps to reproduce

I can't really reproduce it at the moment... it just sometimes happens. See description.

### Expected behavior

When I use the keybinding `W` or the commands `:NvimTreeCollapse` or `:NvimTreeCollapseKeepBuffers` to collapse the nvim-tree, then it should correctly collapse and don't show duplicate file entries.

### Actual behavior

When I use the keybinding `W` or the commands `:NvimTreeCollapse` or `:NvimTreeCollapseKeepBuffers` to collapse the nvim-tree, then it collapses correctly, but sometimes has duplicate file entries afterwards.

### Minimal config

```Lua
require'nvim-tree'.setup {
  disable_netrw       = true,
  hijack_netrw        = true,
  open_on_setup       = false,
  ignore_ft_on_setup  = {},
  auto_close          = false,
  open_on_tab         = false,
  hijack_cursor       = false,
  update_cwd          = false,
  update_to_buf_dir   = {
    enable = true,
    auto_open = true,
  },
  diagnostics = {
    enable = false,
    icons = {
      hint = "",
      info = "",
      warning = "",
      error = "",
    }
  },
  update_focused_file = {
    enable      = false,
    update_cwd  = false,
    ignore_list = {}
  },
  system_open = {
    cmd  = nil,
    args = {}
  },
  filters = {
    dotfiles = false,
    custom = {}
  },
  git = {
    enable = true,
    ignore = true,
    timeout = 500,
  },
  view = {
    width = 40,
    --height = 30,
    hide_root_folder = true,
    side = 'left',
    auto_resize = true,
    mappings = {
      custom_only = false,
      list = {
        {key = 'C', action = 'cd'}
      }
    },
    relativenumber = true,
    signcolumn = "yes"
  },
  trash = {
    cmd = "trash",
    require_confirm = true
  }
}
```

**Comment by kyazdani42** [comment]
i wasn't able to reproduce, did you reproduce this somehow consistently ?

**Comment by alex-courtis** [comment]
I have seen this a few times when using search. The problem appeared to be related to expanding nodes during a failed search, then expanding them again for a successful search.

@be-ndee have you been using search? Are you changing up and down directories before this happens?

**Comment by lu5je0** [comment]
I have seen this a few time too when collapse or open directory.

**Comment by alex-courtis** [comment]
Added some protection against duplicates: #1143 

Please report any further occurrences if this still occurs after the above is merged.

**Comment by be-ndee** [comment]
Thank you @alex-courtis. I did not see this error anymore, so I think it's fixed :)
