### ISSUE TITLE
Add files or folders from empty root

### ISSUE THREAD

**Issue by kristijanhusak** [kyazdani42/nvim-tree.lua#106]
Hi,

I noticed that when you open up a folder that's completely empty as cwd, you are not able to add any files/folders, because cursor is always at the root, which ignores all keybindings. I go around this by doing the first thing manually (for example `:!mkdir folder`), but I think it should allow adding files to the cwd from the root entry.

**Comment by kyazdani42** [comment]
yep i agree the fs handling is quite clunky compared to the speed of rendering :) I'll work on a refactoring soon, which will make the fs integration much better !

**Comment by kyazdani42** [comment]
this was fixed some time ago :)
