### ISSUE TITLE
Shift git symbols

### ISSUE THREAD

**Issue by VDuchauffour** [kyazdani42/nvim-tree.lua#1061]
Hi,
Any idea how to shift git symbols to the right side of Nvimtree ? Like in VSCode. Thank
![Screenshot_2022-03-09_22:37:51_(367x297)](https://user-images.githubusercontent.com/40724343/157541776-36a15ce0-867a-45c5-9ceb-3741811361f7.png)

**Comment by kyazdani42** [comment]
Not feasible rn, this has been asked before already. I plan to make it possible at some point, but i have some refactoring to do first in order to make this possible. Closing as a duplicate :)

**Comment by brancobruyneel** [comment]
Any update on this?

**Comment by alex-courtis** [comment]
> Any update on this?

See #1510
