### ISSUE TITLE
Error is thrown when copy/pasting a file

### ISSUE THREAD

**Issue by steliyan** [kyazdani42/nvim-tree.lua#1064]
### Description

Can't copy/paste file with `c`/`p`. Happens if I try to copy in the same dir and in different dirs.

### Neovim version

```markdown
NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@iMac-Pro
```

### Operating system and version

macOS

### nvim-tree version

2457e141ae5c2e9c5d94a9550b37b421d25cfff1

### Steps to reproduce

1. Open neovim
2. ... do a whole day of work ...
3. Open Nvim-Tree in vinegar mode
4. Copy a file
5. Paste the file in the same dir

Can't provide exact steps, happens after a whole day of work.

Opening/closing tabs/buffers/etc.

### Expected behavior

The file is copy/pasted.

### Actual behavior

Error is shown:

```Lua
vim.api.nvim_set_keymap(
  'n',
  '<M-e>',
  ':lua require("nvim-tree").open_replacing_current_buffer()<CR>',
  { noremap = true, silent = true }
)
```

### Minimal config

```Lua
require('nvim-tree').setup({
  hijack_netrw = true,
  hijack_cursor = true,
  nvim_tree_respect_buf_cwd = false,
  update_cwd = false,

  view = {
    mappings = {
      list = {
        { key = { '<CR>', 'o', '<2-LeftMouse>' }, action = 'edit_in_place' },
        { key = '<C-e>', action = 'edit' },
      },
    },
  },

  actions = {
    open_file = {
      quit_on_open = true,
    },
    change_dir = {
      enable = false,
      global = false,
    },
  },

  update_focused_file = {
    enable = false,
    update_cwd = false,
    ignore_list = {},
  },

  git = {
    enable = true,
    ignore = false,
    timeout = 500,
  },
})```
```

**Comment by alex-courtis** [comment]
Please post the actual error you received.

Such "happens after a whole day of work" problems are always difficult.

I have added some more error checks and logs around copy-paste: https://github.com/kyazdani42/nvim-tree.lua/pull/1076 

Let's wait until that is released and you can collect logs during your workday. Alternatively, you could pull the branch and use that whilst waiting for the merge.

**Comment by steliyan** [comment]
Fair enough, I've updated the plugin. :)
Actually, I've got the error, just it got lost while prepping the bug report. 🤦

**Comment by kyazdani42** [comment]
@steliyan you can enable the log for copy_paste in master, i've merged alex's PR. If you manage to encounter it again, can you provide logging information on why this has happened ? thanks :)

**Comment by alex-courtis** [comment]
@steliyan are you still experiencing this problem?

**Comment by steliyan** [comment]
@alex-courtis, this hasn't happened ever since. I encountered another copy & rename bug, will create a new ticket.

Closing this now. :)
