### ISSUE TITLE
Can't open 2 nvim trees in vinegar mode

### ISSUE THREAD

**Issue by steliyan** [kyazdani42/nvim-tree.lua#1065]
### Description

I can't open 2 nvim trees when used in vinegar mode. 

### Neovim version

```markdown
NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@iMac-Pro
```

### Operating system and version

macOS

### nvim-tree version

2457e141ae5c2e9c5d94a9550b37b421d25cfff1

### Steps to reproduce

1. Open neovim
2. *Nvim-tree* opens (see config below)
3. Open a file
4. Open a vim split (`:split`)
5. Go to buffer 1 - open nvim-tree in vinegar mode
6. *Nvim-tree* opens
7. Go to buffer 2 - try open nvim-tree in vinegar mode

### Expected behavior

Opens a second nvim-tree.

### Actual behavior

Nothing happens.

NOTE: Something kinda weird happens if you first do the split. Then the initial buffer (the one split from, I guess) doesn't respond to any events, but the second one - does. :|

### Minimal config

```Lua
vim.api.nvim_set_keymap(
  'n',
  '<M-e>',
  ':lua require("nvim-tree").open_replacing_current_buffer()<CR>',
  { noremap = true, silent = true }
)


```Lua
require('nvim-tree').setup({
  hijack_netrw = true,
  hijack_cursor = true,
  nvim_tree_respect_buf_cwd = false,
  update_cwd = false,

  view = {
    mappings = {
      list = {
        { key = { '<CR>', 'o', '<2-LeftMouse>' }, action = 'edit_in_place' },
        { key = '<C-e>', action = 'edit' },
      },
    },
  },

  actions = {
    open_file = {
      quit_on_open = true,
    },
    change_dir = {
      enable = false,
      global = false,
    },
  },

  update_focused_file = {
    enable = false,
    update_cwd = false,
    ignore_list = {},
  },

  git = {
    enable = true,
    ignore = false,
    timeout = 500,
  },
})```
```

**Comment by kyazdani42** [comment]
Hi, this is expected because there cannot be 2 different trees at the moment, since there is only 1 state managed throughout the plugin. Closing since this would be more like a feature request. Open a new feature request if you wish this behavior, but this might be quite complicated to implement :)
