### ISSUE TITLE
Remove Defaults From Minimal Config

### ISSUE THREAD

**Issue by alex-courtis** [kyazdani42/nvim-tree.lua#1068]
I just raised an issue and it was annoying to remove the default config.

Other user bugs have been posting just their changes without defaults.

OK with this @gegoune @kyazdani42 ?

**Comment by kyazdani42** [comment]
go for it.

**Comment by kyazdani42** [comment]
@alex-courtis  can we close this ?

**Comment by alex-courtis** [comment]
All resolved in #1074
