### ISSUE TITLE
How to put git icons behind file name like in README screenshot

### ISSUE THREAD

**Issue by weilbith** [kyazdani42/nvim-tree.lua#1069]
The title is already quite expressive. 😅 

Maybe I'm misinterpreting the screenshot, but it looks like the red `` signs are git icons (part of the relevant configuration not visible)? If so, for some reason they are behind the folder names. Though for files they are between filetype icon and filename.
I kinda like to put the git icon behind the file name, because it "unclutters" a little bit the filetype and git status icons. And second it keeps all file names aligned together after their filetype icon, no matter if they have a git icon or not.

Here the screenshot I'm referring to:

![image](https://user-images.githubusercontent.com/12543647/157855085-4802c914-912e-43a4-b151-0d11e8d3b424.png)

**Comment by kyazdani42** [comment]
Yeah i'm not sure since this was an old screenshot, the behavior might have been changed at some point.
The renderer is a big mess rn and i have a few refactorings planned for it after if finish the live filter, which will make it more extensible.

**Comment by alex-courtis** [comment]
Following in #246
