### ISSUE TITLE
Failed to close single buffer opened in nvim-tree

### ISSUE THREAD

**Issue by ray-x** [kyazdani42/nvim-tree.lua#107]
Minium config:
```vim
if &compatible
  set nocompatible
endif
" Add the dein installation directory into runtimepath
set runtimepath+=~/.cache/dein/repos/github.com/Shougo/dein.vim

if dein#load_state('~/.cache/dein')
  call dein#begin('~/.cache/dein')

  call dein#add('~/.cache/dein/repos/github.com/Shougo/dein.vim')
  call dein#add('kyazdani42/nvim-web-devicons')
  call dein#add('kyazdani42/nvim-tree.lua')
  call dein#end()
  call dein#save_state()
endif
```

Open LuaTree and with it, open multiple files.
use `:bd` to close one buffer. 

bd suppose to close current buffer, but with LuaTree opened. `:bd`will close all buffers.
If LuaTree closed, `:bd` will close current buffer.

**Comment by kyazdani42** [comment]
are those buffers visible inside a window ? lua tree will close with the option to close when it's the last active window, not the last buffer.

**Comment by ray-x** [comment]
If I use LuaTree open 3 files in buffer with buffer number 1,3,4
and 4 is current buffer.
Then I close buffer 4 with `bd 4` or `bd`. It will also close 1 and 3 as well.

But if I close buffer 1 with `bd 1`, only buffer 1 closed.

If I open buffer 1,3,4 and close LuaTree, 'bd' will close buffer 4 while 1 and 3 remain open.

**Comment by kyazdani42** [comment]
this is expected behavior because the feature to close the tree expects the tree to be in the last **window** and not buffer.
from the readme: `let g:lua_tree_auto_close = 1 "0 by default, closes the tree when it's the last window`

**Comment by kyazdani42** [comment]
well i just checked and i don't have this issue.

**Comment by ray-x** [comment]
If I setup `let g:lua_tree_auto_close = 0`
And have 3 buffer opened. Type `bd` will close all 3 buffers and only LuaTree remain open. I am running on Mac+kitty

**Comment by kyazdani42** [comment]
i definitely cannot reproduce this. Can you give me your neovim version and config ?

**Comment by ray-x** [comment]
My vimrc:
```
set encoding=utf-8
if has('nvim')
  let s:config_home = stdpath('config')
else
  let s:config_home = '~/.config/nvim'
endif
call plug#begin('~/.vim/plugged')
if has('nvim')
  Plug 'kyazdani42/nvim-web-devicons'
  Plug 'kyazdani42/nvim-tree.lua' " , { 'on': 'LuaTreeToggle' }
endif
call plug#end()
set mouse=a
set termguicolors
" let g:lua_tree_auto_close = 0
```
My nvim version NVIM v0.5.0-728-gf6ac37560, which is a nightly.

To reproduce:
1) LuaTreeOpen
2) with `e 1`, `e 2`, `e 3` open 3 buffers
3) `bd` to close current buffer
4) notice all buffer had been closed.

**Comment by kyazdani42** [comment]
cannot reproduce even with a super minimal configuration. Are you sure another plugin is not conflicting here ?

**Comment by ray-x** [comment]
It is wired. May related to my setup. In fact I only have nvim-tree enabled in Plug and disabled all key bindings.

**Comment by akinsho** [comment]
@ray-x FYI if you have any files in your `.config/.nvim/` like `ftplugin` or `after/ftplugin`  etc. then opening vim with a minimal `init.vim` will still source all of those files so it could be some logic that is in one of those files

**Comment by ray-x** [comment]
In fact, those ftplugin directories are empty.
My nvim startup log as below:
```log
005.893  001.581  001.581: sourcing /Users/ray/.local/share/nvim/site/autoload/plug.vim
013.348  004.999  004.999: sourcing /usr/local/share/nvim/runtime/filetype.vim
013.583  000.082  000.082: sourcing /usr/local/share/nvim/runtime/ftplugin.vim
013.755  000.033  000.033: sourcing /usr/local/share/nvim/runtime/indent.vim
014.616  000.235  000.235: sourcing /usr/local/share/nvim/runtime/syntax/syncolor.vim
014.713  000.462  000.227: sourcing /usr/local/share/nvim/runtime/syntax/synload.vim
014.739  000.671  000.209: sourcing /usr/local/share/nvim/runtime/syntax/syntax.vim
014.765  010.623  003.257: sourcing /Users/ray/github/dotfiles/init.plug.min
014.770  000.259: sourcing vimrc file(s)
015.199  000.031  000.031: sourcing /Users/ray/.vim/plugged/nvim-web-devicons/plugin/nvim-web-devicons.vim
015.447  000.071  000.071: sourcing /Users/ray/.vim/plugged/nvim-tree.lua/plugin/tree.vim
016.480  000.166  000.166: sourcing /usr/local/share/nvim/runtime/plugin/gzip.vim
016.611  000.015  000.015: sourcing /usr/local/share/nvim/runtime/plugin/health.vim
016.794  000.072  000.072: sourcing /usr/local/share/nvim/runtime/plugin/man.vim
018.302  000.166  000.166: sourcing /usr/local/share/nvim/runtime/pack/dist/opt/matchit/plugin/matchit.vim
018.364  001.490  001.325: sourcing /usr/local/share/nvim/runtime/plugin/matchit.vim
018.576  000.138  000.138: sourcing /usr/local/share/nvim/runtime/plugin/matchparen.vim
018.673  000.021  000.021: sourcing /usr/local/share/nvim/runtime/plugin/netrwPlugin.vim
018.941  000.014  000.014: sourcing /Users/ray/.local/share/nvim/rplugin.vim
018.963  000.219  000.205: sourcing /usr/local/share/nvim/runtime/plugin/rplugin.vim
019.211  000.115  000.115: sourcing /usr/local/share/nvim/runtime/plugin/shada.vim
019.361  000.027  000.027: sourcing /usr/local/share/nvim/runtime/plugin/spellfile.vim
019.561  000.123  000.123: sourcing /usr/local/share/nvim/runtime/plugin/tarPlugin.vim
019.715  000.076  000.076: sourcing /usr/local/share/nvim/runtime/plugin/tohtml.vim
019.810  000.021  000.021: sourcing /usr/local/share/nvim/runtime/plugin/tutor.vim
020.046  000.164  000.164: sourcing /usr/local/share/nvim/runtime/plugin/zipPlugin.vim
```


Also if I add `autocmd BufLeave * echo "leave buffer"` in vimrc, when I type in `bd`, and suppose I have 1.txt, 2.txt, 3.txt opened in buffer and have LuaTreeTree open, got log as bellow:
```
Executing BufLeave Autocommands for "*"
autocommand echo "leave buffer"

Executing: echo "leave buffer"
leave buffer
Executing WinEnter Autocommands for "*"
autocommand call s:Highlight_Matching_Pair()

Executing: call s:Highlight_Matching_Pair()
calling function <SNR>16_Highlight_Matching_Pair()


function <SNR>16_Highlight_Matching_Pair returning #0

continuing in WinEnter Autocommands for "*"

Executing BufEnter Autocommands for "*"
autocommand lua require'tree'.buf_enter()

Executing: lua require'tree'.buf_enter()
Executing CursorMoved Autocommands for "*"
autocommand call s:Highlight_Matching_Pair()

Executing: call s:Highlight_Matching_Pair()
calling function <SNR>16_Highlight_Matching_Pair()


function <SNR>16_Highlight_Matching_Pair returning #0

continuing in CursorMoved Autocommands for "*"


Executing: bd
Executing BufLeave Autocommands for "*"
autocommand echo "leave buffer"

Executing: echo "leave buffer"
                              leave buffer
Executing WinClosed Autocommands for "*"
autocommand lua require'tree'.on_leave()

Executing: lua require'tree'.on_leave()
Executing WinEnter Autocommands for "*"
autocommand call s:Highlight_Matching_Pair()

Executing: call s:Highlight_Matching_Pair()
calling function <SNR>16_Highlight_Matching_Pair()

function <SNR>16_Highlight_Matching_Pair returning #0

continuing in WinEnter Autocommands for "*"

Executing CursorMoved Autocommands for "*"
autocommand call s:Highlight_Matching_Pair()

Executing: call s:Highlight_Matching_Pair()
calling function <SNR>16_Highlight_Matching_Pair()

function <SNR>16_Highlight_Matching_Pair returning #0

continuing in CursorMoved Autocommands for "*"

Executing BufEnter Autocommands for "*"
autocommand lua require'tree'.buf_enter()

Executing: lua require'tree'.buf_enter()
Executing: :qa!
```

**Comment by kyazdani42** [comment]
Something in your configs must be wrong, nobody ever reported such issue and i definitely cannot reproduce.
@akinsho can you reproduce this on your end ?

**Comment by akinsho** [comment]
Not near a computer at the moment but will check later. I've never had an issue like that before though although I can't remember if I use the `autoclose` option

**Comment by ray-x** [comment]
In fact, the issue I saw is not related to nvim-tree.
It could be reproduce without nvim-tree installed.  Simply open some files in buffer and vsplit another file, switch back to the windows with multiple files opened and run `bd` it will close all the buffer in current split window.
Did try reinstall all packages in brew and also tried start nvim with `-u NONE`, and even tried vim/macvim. All have same issue :-(

Feel free to comment any possibilities. Also I am closing this one as it not nvim-tree related.
