### ISSUE TITLE
Highlight group for folder icons doesn't work

### ISSUE THREAD

**Issue by weilbith** [kyazdani42/nvim-tree.lua#1070]
To be honest I'm not sure if it was working in the past or not because I had linked both highlight groups (`NvimTreeFolderName` and `NvimTreeFolderIcon`) the same. But now I tried to to set them differently and it doesn't work.

So if I open the tree window and for example do `:highlight! NvimTreeFolderName guifg=#ff0000`. Folder icon and name change to screaming red. If I now execute `:highlight! NvimTreeFolderIcon guifg=#00ff00`, I would expect the name to stay red and the icon to become green. But nothing happens at all. Also the background color has no affect to it.

What is the issue here?

**Comment by weilbith** [comment]
I'm very sorry that I did not use the Bug report form 🙈

**Comment by kyazdani42** [comment]
also i tried on my configs and it worked as expected to me. This might be because there is a link set from a plugin you've installed.
Please send a minimal config from the bug report form, and make sure your highlight links does not link foldername to folder icon or the invert.

**Comment by ichigozero** [comment]
Same thing happened to me. Most likely you set the following somewhere in your config.
```
vim.g.nvim_tree_highlight_opened_files = 1
```

Looking at the code `hl_icon` value will be something other than `NvimTreeFolderIcon` if the `vim.g.nvim_tree_highlight_opened_files` is set to 1. In other words, `NvimTreeFolderIcon` highlight will never be used.

https://github.com/kyazdani42/nvim-tree.lua/blob/d93a93c9c1a12748f09c5e01867908e9985cfccc/lua/nvim-tree/renderer/init.lua#L55-L59

As a work around I made some modification to `set_folder_hl` function in my [fork](https://github.com/ichigozero/nvim-tree.lua/commit/b17c879c6cf8e931b519495c8897f3ad7f2afa4b). I will make PR if it is okay.

**Comment by kyazdani42** [comment]
does #1086 fix your issue ? Thanks for the patch @ichigozero :)

**Comment by alex-courtis** [comment]
Looks fixed to me. Please reopen if you experience further issues.
