### ISSUE TITLE
Nvim-tree opens on half of the screen when file is opened

### ISSUE THREAD

**Issue by comchieu3mon** [kyazdani42/nvim-tree.lua#1071]
### Description

Nvim-tree opens on half of the screen when file is opened. After that, when i close the tree and reopen again, it go back to the size in my config 

### Neovim version

```markdown
NVIM v0.6.1
Build type: Debug
LuaJIT 2.1.0-beta3
```

### Operating system and version

Manjaro 21.2.4 Qonos

### nvim-tree version

Latest nvim-tree version, i just updated it

### Steps to reproduce

1. Open with nvim
2. Choose file and open it
3. See bug
![image](https://user-images.githubusercontent.com/34432166/157868840-b50119ce-43e0-4ff5-a03c-d0f9532a99e6.png)

### Expected behavior

Nvim-tree should keep it's original size

### Actual behavior

Nvim-tree opens on half screen

### Minimal config

```Lua
-- following options are the default
-- each of these are documented in `:help nvim-tree.OPTION_NAME`
vim.g.nvim_tree_icons = {
  default = "",
  symlink = "",
  git = {
    unstaged = "",
    staged = "S",
    unmerged = "",
    renamed = "➜",
    deleted = "",
    untracked = "U",
    ignored = "◌",
  },
  folder = {
    default = "",
    open = "",
    empty = "",
    empty_open = "",
    symlink = "",
  },
}

local status_ok, nvim_tree = pcall(require, "nvim-tree")
if not status_ok then
  return
end

local config_status_ok, nvim_tree_config = pcall(require, "nvim-tree.config")
if not config_status_ok then
  return
end

local tree_cb = nvim_tree_config.nvim_tree_callback

nvim_tree.setup {
  disable_netrw = true,
  hijack_netrw = true,
  open_on_setup = false,
  ignore_ft_on_setup = {
    "startify",
    "dashboard",
    "alpha",
  },
  auto_close = true,
  open_on_tab = false,
  hijack_cursor = false,
  update_cwd = true,
  update_to_buf_dir = {
    enable = true,
    auto_open = true,
  },
  diagnostics = {
    enable = true,
    icons = {
      hint = "",
      info = "",
      warning = "",
      error = "",
    },
  },
  update_focused_file = {
    enable = true,
    update_cwd = true,
    ignore_list = {},
  },
  system_open = {
    cmd = nil,
    args = {},
  },
  filters = {
    dotfiles = false,
    custom = {},
  },
  git = {
    enable = true,
    ignore = true,
    timeout = 500,
  },
  view = {
    width = 30,
    height = 30,
    hide_root_folder = false,
    side = "left",
    auto_resize = true,
    mappings = {
      custom_only = false,
      list = {
        { key = { "l", "<CR>", "o" }, cb = tree_cb "edit" },
        { key = "h", cb = tree_cb "close_node" },
        { key = "v", cb = tree_cb "vsplit" },
      },
    },
    number = false,
    relativenumber = false,
  },
  trash = {
    cmd = "trash",
    require_confirm = true,
  },
  quit_on_open = 0,
  git_hl = 1,
  disable_window_picker = 0,
  root_folder_modifier = ":t",
  show_icons = {
    git = 1,
    folders = 1,
    files = 1,
    folder_arrows = 1,
    tree_width = 30,
  },
}
```

**Comment by freitagfelipe** [comment]
actions = {
    open_file = {
        resize_window = true
    }
}

I belive that if you put this in your setup your issue will be resolved.

**Comment by freitagfelipe** [comment]
```
actions = {
    open_file = {
        resize_window = true
    }
}
```

Try to put this in your setup.

**Comment by comchieu3mon** [comment]
Yes, it works. Thank you for helping me

**Comment by TikiCat7** [comment]
@freitagfelipe thank you! this was driving me crazy 😆

**Comment by piqoni** [comment]
> ```
> actions = {
>     open_file = {
>         resize_window = true
>     }
> }
> ```
> 
> Try to put this in your nvim-tree setup. Also I hope I was able to help you!

Hi there, can you please share what file (path) is that? New to nvim.

**Comment by freitagfelipe** [comment]
> Hi there, can you please share what file (path) is that? New to nvim, just installed Lunarvim and encountered the same issue.

As I can see in Lunarvim repository the setup file of nvim-tree is in the following path `lua/lvim/nvimtree.lua`, you will find the resize_window option in the line 138.

**Comment by piqoni** [comment]
Thanks a lot for the help. Works now :)
