### ISSUE TITLE
NvimTree opens on wrong side when opening file for first time

### ISSUE THREAD

**Issue by SethGunnells** [kyazdani42/nvim-tree.lua#1072]
### Description

When opening a directory like so: `nvim .` and hitting `Enter` on some file, NvimTree ends up on the right side of the screen instead of the left. Upon closing and reopening it, it appears on the left as intended.

If important, it is also showing on 50% of the screen as described in #1071.

### Neovim version

```markdown
NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

macOS Monterey, 12.1

### nvim-tree version

2457e14

### Steps to reproduce

1. `nvim .`
2. `Enter` on any file

### Expected behavior

NvimTree remains open on left size, sized correctly

### Actual behavior

NvimTree remains open on right size, taking up 50% of screen

### Minimal config

```Lua
require'paq' {
  'kyazdani42/nvim-tree.lua';
}

require'nvim-tree'.setup()
```

**Comment by freitagfelipe** [comment]
I had this same issue this morning. I solved with this line in my nvim settings:
`
vim.opt.splitright = true
`

**Comment by kyazdani42** [comment]
indeed this is unrelated to the tree, as the option is global. Setting resize_window to true will fix the issue as the tree will be moved and resized when opening the file.
