### ISSUE TITLE
Locate current open file in nvim-tree

### ISSUE THREAD

**Issue by neevek** [kyazdani42/nvim-tree.lua#1073]
Is your feature request related to a problem? Please describe.
---
No, it's just a handy feature found in NERDTree.
Not sure if this feature exists in nvim-tree, I read the doc and searched the issues but couldn't find one.

Describe the solution you'd like
---
Locate the current opened file in nvim-tree, just like `:NERDTreeFind`.

Describe alternatives you've considered
---
No

Additional context
---
No

**Comment by neevek** [comment]
After using nvim-tree for a while, I find that I don't need it in nvim-tree at all.
When navigating from a buffer to nvim-tree, the cursor is always positioned exactly on the opened file.

**Comment by kyazdani42** [comment]
it is actually implemented under NvimTreeFindFile
