### ISSUE TITLE
On pressing <C-]> the workspace should be updated.

### ISSUE THREAD

**Issue by askfiy** [kyazdani42/nvim-tree.lua#1081]
It's not a lot to use <C-]> , but it should be able to do better.

Switching workspaces with the lcd command while <C-]> should be great.

**Comment by kyazdani42** [comment]
Hi, why did you close this ?

**Comment by askfiy** [comment]
I don't remember very well. Can this be achieved?

**Comment by kyazdani42** [comment]
this is already the case if i understand correctly:
`:help nvim-tree.actions` -> change_dir
`change_dir.global = false` (will lcd, not cd)
`change_dir.enable = true` (false will not do either lcd nor cd)

**Comment by askfiy** [comment]
thank you
