### ISSUE TITLE
[Help wanted] How to keep nvim_tree open when opening a new file or buffer?

### ISSUE THREAD

**Issue by LC0117** [kyazdani42/nvim-tree.lua#1084]
I tried `quit_on_open = false` but it seems to be another option.

**Comment by gegoune** [comment]
@kyazdani42 I would like to suggest enabling discussions for this repository - you are getting plenty of questions here that aren't really issue reports.

@LC0117 You have omitted bug issue report template.

**Comment by LC0117** [comment]
Thanks for the notice but this is neither a bug report nor a feature request.

**Comment by kyazdani42** [comment]
actions.open_file.quit_on_open (`:help nvim-tree.actions`)
