### ISSUE TITLE
Open certain files with custom command

### ISSUE THREAD

**Issue by sarmong** [kyazdani42/nvim-tree.lua#1085]
I want to open images from nvim-tree in another application, because seeing binary code is useless.

So, this would pretty much mean that nvim-tree needs a functionality to map a custom command for opening specific filetypes (mimetypes). So, for `png` or `jpg` images I want to run `xdg-open` when I press `l`

Is this possible to do?

**Comment by gegoune** [comment]
It's mentioned in README:

`{ key = "s",                            action = "system_open" }`

**Comment by kyazdani42** [comment]
closing since this is already implemented.
