### ISSUE TITLE
Unrecognized git state "RM"

### ISSUE THREAD

**Issue by Stanislav-Lapata** [kyazdani42/nvim-tree.lua#109]
I got message after save file
> [LuaTree] Unrecognized git state "RM". Please open up an issue on https://github.com/kyazdani42/nvim-tree.lua/issues with this message.
```
Changes to be committed:
    renamed:    staging/anycable-go.yaml -> staging/anycable-go/deployment.yml
    ...
Changes not staged for commit:
    modified:   staging/anycable-go/deployment.yml
    ...
```

**Comment by kyazdani42** [comment]
Another one :) thanks for reporting this, i'll have a look soon

**Comment by kyazdani42** [comment]
fixed in master
