### ISSUE TITLE
Coc-diagnostics not functioning

### ISSUE THREAD

**Issue by green726** [kyazdani42/nvim-tree.lua#1091]
### Description

Coc diagnostics are not showing in Nvim-tree

Coc java diagnostics are not displaying in the nvim-tree
As can be seen in the below image, there is an error detected by Coc however it is not displayed in nvim-tree

![Capture](https://user-images.githubusercontent.com/59667714/159144950-ec060efc-189c-421d-aafa-8f12be85cce5.PNG)

I printed in several spots of the Nvim-tree source code, and the issue seems to be that the utils.find_node function in diagnostics.lua is returning nil.

below image is with the minimal config:
![neovim-minimal-tree-bug](https://user-images.githubusercontent.com/59667714/159145133-95d3f55f-b826-4b22-ab91-d781e03f0dcc.PNG)

### Neovim version

```markdown
NVIM v0.6.0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

### Operating system and version

Windows 10

### nvim-tree version

9eea0ca

### Steps to reproduce

1. Install coc-java
2. Open any code, make an error
3. Nvim-tree refresh / open nvim-tree

### Expected behavior

Nvim-tree displays coc diagnostic erros

### Actual behavior

Nvim tree does not display coc diagnostic errors

### Minimal config

```Lua
vim.cmd([[set runtimepath=$VIMRUNTIME]])
vim.cmd([[set packpath=/tmp/nvt-min/site]])
local package_root = "/tmp/nvt-min/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
	require("packer").startup({
		{
			"wbthomason/packer.nvim",
			"kyazdani42/nvim-tree.lua",
			"kyazdani42/nvim-web-devicons",
			{ "neoclide/coc.nvim", branch = "release" },

			-- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
		},
		config = {
			package_root = package_root,
			compile_path = install_path .. "/plugin/packer_compiled.lua",
			display = { non_interactive = true },
		},
	})
end
if vim.fn.isdirectory(install_path) == 0 then
	print("Installing nvim-tree and dependencies.")
	vim.fn.system({ "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path })
end
load_plugins()
require("packer").sync()
vim.cmd([[autocmd User PackerComplete ++once echo "Ready!" | lua setup()]])
vim.opt.termguicolors = true
vim.opt.cursorline = true

-- MODIFY NVIM-TREE SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
_G.setup = function()
	require("nvim-tree").setup({
		diagnostics = {
			enable = true,
			icons = {
				hint = "",
				info = "",
				warning = "",
				error = "",
			},
		},
	})
end
```

**Comment by alex-courtis** [comment]
Thanks for the detailed instructions. Unfortunately I couldn't reproduce with the above configuration, after running `:CocInstall coc-java`

I have added some diagnostics to a branch so that we may see if we are actually attempting to find a change, or failing to match. Please switch to the https://github.com/kyazdani42/nvim-tree.lua/tree/%231091-diagnostics-logging branch. You can then enable logging via:
```lua
        require("nvim-tree").setup({
                log = {
                        enable = true,
                        truncate = true,
                        types = {
                                diagnostics = true,
                        },
                },
...
```

Here's what I get when there is a problem:
```
[2022:03:26 16:30:13] [diagnostics] update
[2022:03:26 16:30:13] [diagnostics]  bufname '/tmp/hw/HelloWorld.java' severity 1
[2022:03:26 16:30:13] [diagnostics]   checking node '/tmp/hw/HelloWorld.java'
[2022:03:26 16:30:13] [diagnostics]  matched node '/tmp/hw/HelloWorld.java'
```


To switch to the branch you can:
```
cd <your-plugin-directory>/nvim-tree.lua
git pull
git checkout '#1091-diagnostics-logging'
```

When done:
```
git checkout master
```

**Comment by green726** [comment]
Hello, sorry for the late response. This is my log file:

it seems to log 
```
[2022:04:02 17:35:36] [diagnostics]  bufname 'e:\Coding\robotics\2022\MiniSteve\src\main\java\frc\robot\commands\AutoBall.java' severity 4
```
along with a lot of
```
[2022:04:02 17:35:36] [diagnostics]   checking node 'E:\Coding\robotics\2022\MiniSteve\.idea'
```
or something similar

[nvim-tree.log](https://github.com/kyazdani42/nvim-tree.lua/files/8403395/nvim-tree.log)

**Comment by alex-courtis** [comment]
Ouch... windows. I see the window title is powershell, and I'm am concluding that nvim isn't running inside a POSIX shell, hence the windows style path names.

I was under the impression that windows users would run nvim inside a shell like bash, which would provide "proper" paths.

It looks like we have a mismatch in the case of the buffer and the node. I'll investigate that.

**Comment by alex-courtis** [comment]
I have "canonicalised" the buffer and node paths before matching, on the above branch.

Please update that branch and see if it works for you.

I have tested on linux but cannot test on windows.

**Comment by alex-courtis** [comment]
@green726 are you still experiencing this problem?

**Comment by green726** [comment]
Sorry for not responding, I attempted to swap to linux(I love it!) and accidentally broke my windows install (had to reinstall that), and have been using mostly linux for development now. I also messed with neovim, and now can't get coc to run on windows (so I can't test this). Thank you for fixing this issue though!
