### ISSUE TITLE
Some files do not have icons

### ISSUE THREAD

**Issue by cevhyruz** [kyazdani42/nvim-tree.lua#1109]
I don't know if this is the right place to submit the issue but some filenames don't have file icons. screenshot below.
was this intentional? I can't seem to find any documentation on this.

![Screenshot from 2022-03-26 23-14-27](https://user-images.githubusercontent.com/20886353/160245830-f248d726-66bc-42bf-861f-80e9bf67c93f.png)

here is my packer config
```lua
  use { 'kyazdani42/nvim-tree.lua',
    requires = { 'kyazdani42/nvim-web-devicons' },
    config = function() require('package_config.nvim-tree') end
  }
```
package_config/nvim-tree:
```lua
require('nvim-tree').setup {
  auto_close = true,
  hijack_cursor = false,
  auto_reload_on_write = true,
  view = {
    width = 35,
    height = 35,
    preserve_window_proportions = true,
    mappings = {
      list = {
        { key = '<Space>', action = 'edit' }
      }
    }
  },
  filters = {
    custom = { '.git', 'node_modules' },
  },
  diagnostics = {
    enable = true,
    show_on_dirs = true,
    icons = {
      hint = "",
      info = "",
      warning = "",
      error = "",
    },
  },
  open_file = {
    quit_on_open = true,
    window_picker = {
      enable = false
    }
  },
  git = {
    enable = false,
    ignore = true,
    timeout = 500
  }
}
```

**Comment by alex-courtis** [comment]
Not all file types have a specific [icon](https://github.com/kyazdani42/nvim-web-devicons), such as `.editorconfig`.

You could add such an icon by finding the [Nerd Font](https://www.nerdfonts.com/cheat-sheet) icon that is suitable and raising a PR to add it to [nvim-web-devicons](https://github.com/kyazdani42/nvim-web-devicons).

When there is no icon available, nvim-tree shows nothing. This can be changed via, say:
```vim
  let g:nvim_tree_icons = {
      \ 'default':        '',
      \ 'symlink':        '',
```

I note that the readme specifies the above, not the current empty default. Updating the readme now.

**Comment by cevhyruz** [comment]
@alex-courtis Thank you! hopefully this will be added soon on nvim-web-devicons

**Comment by kyazdani42** [comment]
@cevhyruz thing is, it cannot be added until nerd-fonts haven't been updated. Nvim-web-devicon is pretty much up to date otherwise :)
