### ISSUE TITLE
add function to search root when buf change

### ISSUE THREAD

**Issue by chenjie199234** [kyazdani42/nvim-tree.lua#1113]
**Is your feature request related to a problem? Please describe.**
when i jump into some third packages i imported in my project,the nvim-tree can refresh the tree,but the new root is not the package's root.it is just the root of the buffer file.

**Describe the solution you'd like**
add a function to look up for some file or dir name,like .git or makefile etc to consider whether this is the root

**Comment by kyazdani42** [comment]
I think this would be something implemented by a rooter plugin ? like `project.nvim` or `rooter.nvim` or `vim-rooter` or `lsp-rooter.nvim` ?

**Comment by chenjie199234** [comment]
@kyazdani42 thx,project.nvim work fine
