### ISSUE TITLE
E518: Unknown option: cursorlineopt=line

### ISSUE THREAD

**Issue by Enayaaa** [kyazdani42/nvim-tree.lua#1114]
### Description

The following error occurs when trying to run `:NvimTreeToggle` or `:NvimTreeOpen`:
`E5108: Error executing lua .../share/nvim/plugged/nvim-tree.lua/lua/nvim-tree/view.lua:108: Vim(setlocal):E518: Unknown option: cursorlineopt=line`.

The repo is up to date with master. Removing the option in `view.lua` line `108` let's me open nvim-tree. I don't know what the option does or why it doesn't work.

### Neovim version

```markdown
NVIM v0.5.0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

### Operating system and version

Linux pop-os 5.16.11-76051611-generic

### nvim-tree version

524758a

### Steps to reproduce

1. `nvim`
2. `:NvimTreeOpen`

### Expected behavior

nvim-tree opens a sidebar listing files and folders.

### Actual behavior

`E5108: Error executing lua .../share/nvim/plugged/nvim-tree.lua/lua/nvim-tree/view.lua:108: Vim(setlocal):E518: Unknown option: cursorlineopt=line`
The above error occurs.

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvt-min/site]]
local package_root = "/tmp/nvt-min/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup {
    {
      "wbthomason/packer.nvim",
      "kyazdani42/nvim-tree.lua",
      "kyazdani42/nvim-web-devicons",
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  }
end
if vim.fn.isdirectory(install_path) == 0 then
  print "Installing nvim-tree and dependencies."
  vim.fn.system { "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path }
end
load_plugins()
require("packer").sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua setup()]]
vim.opt.termguicolors = true
vim.opt.cursorline = true

-- MODIFY NVIM-TREE SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
_G.setup = function()
  require("nvim-tree").setup {}
end
```

**Comment by alex-courtis** [comment]
> ### Neovim version
> ```gfm
> NVIM v0.5.0
> Build type: RelWithDebInfo
> LuaJIT 2.1.0-beta3
> ```

Can you please try updating neovim? [v0.6.1](https://github.com/neovim/neovim/releases/tag/v0.6.1) is the current stable release.
