### ISSUE TITLE
position wrong

### ISSUE THREAD

**Issue by chenjie199234** [kyazdani42/nvim-tree.lua#1118]
### Description

![1](https://user-images.githubusercontent.com/29348971/160589269-9f7bb4c0-8ff2-455e-bd43-f482d5b30070.gif)

### Neovim version

```markdown
NVIM v0.6.1
```

### Operating system and version

windows

### nvim-tree version

5eef618

### Steps to reproduce

1.open neovim
2.open a dir
3.open a file in this dir
4.the nvim-tree will go to the right of the window,but the set of nvim-tree is to place on left
5.close the nvim-tree
6.open the nvim-tree.now it show in left.

### Expected behavior

always show in the right place

### Minimal config

```Lua
require("nvim-tree").setup{}
```

**Comment by kyazdani42** [comment]
`:set nosplitright`

**Comment by nschurmann** [comment]
This option is not working for me. I still have the window on the left. Config is minimal.

**Comment by alex-courtis** [comment]
> This option is not working for me. I still have the window on the left. Config is minimal.

No other plugins? Are you running `nvt-min.lua` as per the [bug report](https://github.com/kyazdani42/nvim-tree.lua/issues/new?assignees=&labels=bug&template=bug_report.yml)?

**Comment by gheorghitahurmuz** [comment]
I have same problem on MacOs:


<img width="835" alt="Screenshot 2022-06-30 at 16 04 36" src="https://user-images.githubusercontent.com/12661929/176684274-031cecfc-e563-466f-9e43-b91a0bf3b6ea.png">

These are the plugins:
```lua
require("packer").startup(function(use)
  use "wbthomason/packer.nvim"
  use "akinsho/bufferline.nvim"
  use "kyazdani42/nvim-tree.lua"
  use "kyazdani42/nvim-web-devicons"
  use "EdenEast/nightfox.nvim"
  use "nvim-lualine/lualine.nvim"
  use "williamboman/nvim-lsp-installer"
  use "neovim/nvim-lspconfig"
  use "nvim-treesitter/nvim-treesitter"
  use "lukas-reineke/indent-blankline.nvim"
  use "terrortylor/nvim-comment"
end)
```

And my nvim-tree config:
```lua
require("nvim-tree").setup{}
```

**Comment by kyazdani42** [comment]
you need to `set nosplitright` in your config.

**Comment by pureink** [comment]
try `:set splitright` instead.
