### ISSUE TITLE
Automatically open file upon creation

### ISSUE THREAD

**Issue by Cgboal** [kyazdani42/nvim-tree.lua#1120]
**Is your feature request related to a problem? Please describe.**
When you create a file, it gets put into the file list in alphabetical order which means you have to navigate down to the newly created file in order to open it. 

**Describe the solution you'd like**
It would be great if nvim-tree could automatically open newly created files.

**Comment by kyazdani42** [comment]
you could do it yourself :)
```lua
require"nvim-tree.events".on_file_created(function(file) vim.cmd("edit "..file) end)
```

**Comment by magoz** [comment]
It shows as deprecated.  
What's the new way of calling `nvim-tree.events.on_file_created`?

**Comment by alex-courtis** [comment]
Take a look at `:help nvim-tree-events`.

`Event.FileCreated` is the one.

**Comment by magoz** [comment]
Thank you!  
This worked for me:

```lua
local api = require("nvim-tree.api")
api.events.subscribe(api.events.Event.FileCreated, function(file)
  vim.cmd("edit " .. file.fname)
end)
```

**Comment by MuhametSmaili** [comment]
if you search with h:nvim-tree

**Comment by MuhametSmaili** [comment]
You can set inside options:
```
require("nvim-tree").setup {
		actions = {
			open_file = {
				quit_on_open = true,
			},
		},
}
```

**Comment by alex-courtis** [comment]
> 

Fantastic! Could you please add this useful [Recipe to the Wiki](https://github.com/nvim-tree/nvim-tree.lua/wiki/Recipes)? Don't forget to credit yourself...

**Comment by magoz** [comment]
Done! :-)

**Comment by alex-courtis** [comment]
> Done! :-)

Many thanks!
