### ISSUE TITLE
Provide a `node.absolute_path` placeholder for the trash command

### ISSUE THREAD

**Issue by EPadronU** [kyazdani42/nvim-tree.lua#1123]
**Is your feature request related to a problem? Please describe.**
I'm a KDE/Plasma user and I would like to use the command `kioclient move 'url' trash:/` in order to trash files/dirs with vim-tree.
I don't see how to make it works with the current implementation of vim-tree's trash.

**Describe the solution you'd like**
This is a local workaround I tried and works: `vim.fn.jobstart(string.gsub(M.config.trash.cmd, "%%u", node.absolute_path), {`

As you see, I can "inject" the node's path wherever I need to, as follows: `cmd = "kioclient move '%u' trash:/"`

**Additional context**
A similar approach can be taken in order to offer more flexibility for the trash command. Like checking for the presence of the placeholder and do the injection, and avoiding said injection if no placeholder is present (as it is now).

**Comment by kyazdani42** [comment]
It would work with a simple string.format, but would break existing implementation. 
currently, what you could do, is pass `true` as trash.cmd, and add an event on file_removed

**Comment by EPadronU** [comment]
I appreciate the idea, @kyazdani42. Next is the code I created for this in case it can be of used for others:
```lua
-- Workaround for trashing files/folders with `kioclient`
if vim.fn["executable"]("kioclient") then
  local events = require("nvim-tree.events")

  local function send_to_trash_with_kioclient(uri)
    vim.fn.jobstart(string.format("kioclient move '%s' trash:/", uri), {
      detach = true, on_exit = require("nvim-tree.actions.reloaders").reload_explorer
    })
  end

  events.on_file_removed(function(payload)
    send_to_trash_with_kioclient(payload.fname)
  end)

  events.on_folder_removed(function(payload)
    send_to_trash_with_kioclient(payload.folder_name)
  end)
end
```
