### ISSUE TITLE
Changing the color of file icons

### ISSUE THREAD

**Issue by knubie** [kyazdani42/nvim-tree.lua#1124]
**Is your feature request related to a problem? Please describe.**
There's no way to change the color of file icons.

**Describe the solution you'd like**
There is a highlight group for folder icons (`NvimTreeFolderIcon`), but no highlight group for file icons (`NvimTreeFileIcon`)

**Comment by alex-courtis** [comment]
1. The file icon and its colour will be from nvim-web-devicons
1. If not using nvim-web-devicons, it will be `vim.g.nvim_tree_icons.default` coloured `NvimTreeNormal`

Which one are you suggesting to colourise with `NvimTreeFileIcon`?

**Comment by kyazdani42** [comment]
Closing, since this is related to nvim-web-devicons

**Comment by knubie** [comment]
@alex-courtis I'm not sure I understand your question. I just want to set the color for file icons (all of them, I don't want a separate color for each file type). I couldn't find any documentation on `NvimTreeNormal` so I'm not sure what it's supposed to affect, but the name suggests it affects everything that doesn't have its own highlight.

Is it possible for the highlight of file icons to be different from file text? Is it possible to change the default color for file icons without affecting the color of other elements in the tree?
