### ISSUE TITLE
Opening a file with Telescope creates a new window

### ISSUE THREAD

**Issue by omida86** [kyazdani42/nvim-tree.lua#1126]
### Description

After commit [6da74679449897dd95eaecaefe8dea80fc7eb3de](https://github.com/kyazdani42/nvim-tree.lua/commit/6da74679449897dd95eaecaefe8dea80fc7eb3de) a bug appeared where if the caret is in the nvim-tree file explorer and I use Telescope to open a file, it always creates a new window instead of using an existing window. This bug is of course also present in latest commit.

Before this commit it worked fine. I attached a video to show what I mean.

https://user-images.githubusercontent.com/5972574/161289369-6cd05d8c-1d8c-465a-944a-ed45093b889d.mp4

### Neovim version

```markdown
NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

macOS 12.3

### nvim-tree version

5958fd5d068877fbf3d083abff03dccb4d8286a1

### Steps to reproduce

1. Place caret in nvim-tree filetree window. 
2. Execute lua require('telescope.builtin').find_files() command
3. Open a file

File will open in new window

### Expected behavior

File should open in existing window

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvt-min/site]]
local package_root = "/tmp/nvt-min/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup {
    {
      "wbthomason/packer.nvim",
      "kyazdani42/nvim-tree.lua",
      "kyazdani42/nvim-web-devicons",
      "nvim-telescope/telescope.nvim"
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  }
end
if vim.fn.isdirectory(install_path) == 0 then
  print "Installing nvim-tree and dependencies."
  vim.fn.system { "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path }
end
load_plugins()
require("packer").sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua setup()]]
vim.opt.termguicolors = true
vim.opt.cursorline = true

-- MODIFY NVIM-TREE SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
_G.setup = function()
  require("nvim-tree").setup {}
end
```

**Comment by alex-courtis** [comment]
This behaviour is not unique to telescope. Opening  a file via `:e filename..` has the same effect.

**Comment by alex-courtis** [comment]
view.open_window is doing an unconditional vsplit

We will need to have it look for an existing window, as per open-file behaviour.

**Comment by kyazdani42** [comment]
this behavior is not linked to open_window. The behavior is related to prevent_buffer_override which just reopen a new nvim-tree window if the current one gets hijacked.

**Comment by alex-courtis** [comment]
Working.

Behaves as expected for files as well as buffers such as bufexplorer.

Window picker is shown, however the first window's window picker shows as `^^^^^^^^^^^^^^^^^^^A^^^^^^^^^^^^^^^^^^^^^`. This is because vim "helpfully" injects them when StatusLine and StatusLineNC are the same. Not worth fixing IMO.
