### ISSUE TITLE
NvimTreeOpen moves the cursor to the top

### ISSUE THREAD

**Issue by mauriciopoppe** [kyazdani42/nvim-tree.lua#1129]
### Description

I saw this after an update, what I'd usually do is open the sidebar, navigate to the file that I want and open it, then reopen the sidebar to open a new file. On this last step the cursor position is no longer saved and the cursor is moved to the top which is very annoying.

### Neovim version

```markdown
NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@HMBRW-A-001-M1-004.local
```

### Operating system and version

MacOS Monterrey 12.1

### nvim-tree version

51d1af4

### Steps to reproduce

1. Install nvim-tree.lua
2. Create some files and directories, open a file and then open the sidebar with `NvimTreeOpen`, see that the cursor moved to the top of the buffer

### Expected behavior

The cursor position should be respected and not moved to the top on NvimTreeOpen

### Actual behavior

The cursor position moves to the top on NvimTreeOpen

### Minimal config

```Lua
call plug#begin('~/.config/nvim/plugged')
Plug 'kyazdani42/nvim-tree.lua'
call plug#end()

lua << EOF
require'nvim-tree'.setup {}
EOF
```

**Comment by kyazdani42** [comment]
This is expected since the buffer and window are not persistent anymore (since a few months). 
Not sure how to fix that tbh.

**Comment by maxmax1992** [comment]
I have the same issue, please fixxx

**Comment by alex-courtis** [comment]
You can work around this by using `NvimTreeFindFile` instead of `NvimTreeOpen` or by using `update_focused_file.enable`.

Changing to feature request.
