### ISSUE TITLE
When closing on buffer a reopen splits nvim-tree and the buffer window in half

### ISSUE THREAD

**Issue by ivankovnatsky** [kyazdani42/nvim-tree.lua#1135]
### Description

Usually opening nvim in a dir and it spins for me nvim-tree on setup. Then opening a file.

When I need to change the pwd I do close a buffer of a opened file go ahead and change the pwd in nvim-tree, the width of the nvim-tree grows to a half of the display somehow, splits in other words, somehow, this start to appears just recently. 

https://asciinema.org/a/G7O04Q3gX4ES9hkUGpnB3XrYs

### Neovim version

```markdown
NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

Linux 5.17.1, NixOS 22.05 (Quokka)

### nvim-tree version

nvim-tree.lua-2022-03-20 / e87ee0e3c30368fa97085125ffe13ee37c0daf70

### Steps to reproduce

1. **nvim**
2. open a file using nvim-tree
3. do a `ZZ` or `:x` or close a buffer
4. open another file from a nvim-tree

### Expected behavior

Keep the nvim-tree width as defined in config

### Actual behavior

Grows the nvim-tree width to the half of the screen

### Minimal config

```Lua
let g:nvim_tree_respect_buf_cwd = 1
let g:nvim_tree_icons = {
  \ 'default': '',
  \ }

lua << EOF
require'nvim-tree'.setup {
  disable_netrw       = false,
  update_to_buf_dir   = {
    enable = true,
    auto_open = true,
  },
  open_on_setup = true,
  view = {
    side = 'left',
    width = 40,
    preserve_window_proportions = true,
  },
  git = {
    enable = true,
    ignore = false,
    timeout = 500,
  },
}

require'nvim-tree.view'.View.winopts.relativenumber = true
EOF
```

**Comment by kyazdani42** [comment]
try setting `actions.open_file.resize_window`

**Comment by ivankovnatsky** [comment]
It worked, thanks.
