### ISSUE TITLE
Use vim.notify for messages

### ISSUE THREAD

**Issue by Shatur** [kyazdani42/nvim-tree.lua#1136]
**Is your feature request related to a problem? Please describe.**
Currently messages from the plugin is displayed in the command area. But it would be great to display such messages nicely.

**Describe the solution you'd like**
Use built-in `vim.notify` function that allow third-party plugins on user end customize messages. For example, we have https://github.com/rcarriga/nvim-notify
It won't introduce any dependency and other people without any plugins will continue to see messages as before.

**Comment by kyazdani42** [comment]
if you would like to tackle this go for it, otherwise i'll implement this when i have some time (next week i guess :) )

**Comment by gegoune** [comment]
That should be closed as done, shouldn't it?
