### ISSUE TITLE
nvim_buf_set_name breaks LuaTreeToggle

### ISSUE THREAD

**Issue by kristijanhusak** [kyazdani42/nvim-tree.lua#114]
Hi,

i was messing around with some of my lua plugins, and noticed that tree cannot be opened with `:LuaTreeToggle` once the `nvim_buf_set_name` is called. Here are steps to reproduce:

1. Open neovim
2. Close lua tree if opened
3. do `:call nvim_buf_set_name(bufnr(''), 'test')`
4. Try `:LuaTreeToggle`

This happens because `is_file_readable` in `find_file` returns false. I think tree should be opened no matter if file can be found or not.

Edit: `g:lua_tree_follow` needs to be set to `1` for this to be reproducible.

**Comment by kyazdani42** [comment]
fixed in latest master, thanks :)
