### ISSUE TITLE
Preview command shouldn't open new buffers

### ISSUE THREAD

**Issue by sarmong** [kyazdani42/nvim-tree.lua#1145]
When I use `tab` key to fire `preview` command, a new buffer opens for each file.
This is a bit annoying, because it clutters the buffer line and isn't really a preview anymore.

It would be nice to close the buffer of a previously _previewed_ file after opening another one, so that there can be only one _previewed_ file at a time.

As additional feature, a buffer could be made persistent if a user enters it with a cursor.

This may be a bit tricky to implement, but it kinda resembles the features of modern IDEs

**Comment by kyazdani42** [comment]
I think this is a bit tricky to implement indeed, because neovim works with buffers only :smile:
What may be done is setting some options on the preview buffers to not appear in the buffer list.

**Comment by lu5je0** [comment]
It maybe better to show preview in a float window.
![1](https://user-images.githubusercontent.com/17700877/162582632-8bec065e-b155-4a92-9d3a-60ca28b88876.gif)

**Comment by alex-courtis** [comment]
> close the buffer of a previously _previewed_ file after opening another one

> options on the preview buffers to not appear in the buffer list

preview close will only hide the buffer as per normal `:close` rules, and I can't see any options to change that. However, we could just attempt a `:bdelete` after closing the window. We could be smart in deleting e.g. only delete if the buffer was not open before the preview.

> It maybe better to show preview in a float window.

That would be great! How did you put together that demo @lu5je0 ?

**Comment by alex-courtis** [comment]
See #135 for preview floating windows.

Let's keep this issue about deleting buffers after preview.

**Comment by sarmong** [comment]
I found a `bufhidden` option. 
Not sure which option would suit better for this case.

From the help:
```
	This option specifies what happens when a buffer is no longer
	displayed in a window:
	  <empty>	follow the global 'hidden' option
	  hide		hide the buffer (don't unload it), also when 'hidden'
			is not set
	  unload	unload the buffer, also when 'hidden' is set or using
			|:hide|
	  delete	delete the buffer from the buffer list, also when
			'hidden' is set or using |:hide|, like using
			|:bdelete|
	  wipe		wipe out the buffer from the buffer list, also when
			'hidden' is set or using |:hide|, like using
			|:bwipeout|

```

**Comment by lu5je0** [comment]
> That would be great! How did you put together that demo @lu5je0 ?

I created a floating window by `nui.nvim`, and edit file in it.😆

**Comment by alex-courtis** [comment]
> I found a `bufhidden` option. We could set it automatically for preview buffers.

Buffer local; clever.

**Comment by alex-courtis** [comment]
> I created a floating window by `nui.nvim`, then edit file in it.

We need this feature!

**Comment by ShiChenCong** [comment]
maybe like `trouble.nvim` preview window?

**Comment by serhez** [comment]
I have a problem with the changed behaviour of the plugin due to this issue: now, I can't open several files at once without having to re-open `nvim-tree` for each file I want to open. 

Before this idea was implemented, I could:
1. Open a file and have `nvim-tree` being closed automatically using `Enter`
2. Open a file while keeping `nvim-tree` open and the cursor focused on it using `Tab`, for whenever I had to open several files at once.

This change has made this impossible, as far as I know, and it seems to me like a very natural usage of the plugin. If someone knows how to have the same behaviour as before, PLMK. Otherwise, please consider reverting or at least having both sets of use cases coexisting 🙏🏻

**Comment by kyazdani42** [comment]
You could just make a function to do:
```lua
local nt_api = require "nvim-tree.api"
function preview_custom()
    local node = nt_api.tree.get_node_under_cursor()
	nt_api.node.open.edit(node)
    nt_api.tree.focus()
end
```

**Comment by serhez** [comment]
@kyazdani42 this does not work; it doesn't open the tree after creating the a buffer for the selected file. I've tried also calling `nt_api.tree.open()` before `nt_api.tree.focus()` but the result is the same, the tree does not open.

**Comment by kyazdani42** [comment]
please open a new issue with more detailled informations. i've made it on my end and it works just fine.
