### ISSUE TITLE
Soft linked folder is not collapsed properly.

### ISSUE THREAD

**Issue by lu5je0** [kyazdani42/nvim-tree.lua#1148]
### Description

Cursor should back to parent node instead of top node after collapse folder on child node of soft linked folder, and 
soft linked folder should be collapsed.
![2](https://user-images.githubusercontent.com/17700877/162583429-91a66993-ea6c-4058-9d4b-fb9e808b15f4.gif)

### Neovim version

```markdown
NVIM v0.7.0-dev+1392-gdaa8ac051
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

### Operating system and version

Linux 5.4.0-77-generic #86-Ubuntu

### nvim-tree version

347218d

### Steps to reproduce

1. collapse soft linked node on it's child node

### Expected behavior

Soft linked node has been collapsed properly.

### Actual behavior

Soft linked node is not collapsed properly.

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvt-min/site]]
local package_root = "/tmp/nvt-min/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup {
    {
      "wbthomason/packer.nvim",
      "kyazdani42/nvim-tree.lua",
      "kyazdani42/nvim-web-devicons",
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  }
end
if vim.fn.isdirectory(install_path) == 0 then
  print "Installing nvim-tree and dependencies."
  vim.fn.system { "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path }
end
load_plugins()
require("packer").sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua setup()]]
vim.opt.termguicolors = true
vim.opt.cursorline = true

-- MODIFY NVIM-TREE SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
_G.setup = function()
  require("nvim-tree").setup {}
end
```

**Comment by lu5je0** [comment]
I fixed it in commit https://github.com/lu5je0/nvim-tree.lua/commit/00fd8aefe016ff2665e4479627ec977b411133d1 but it's probably not the best way.

**Comment by alex-courtis** [comment]
> I fixed it in commit [lu5je0@d62336a](https://github.com/lu5je0/nvim-tree.lua/commit/d62336adca34faa7b977dbd43a013cd234c73dbe), but it's probably not the best way.

I'm not sure about the backlink `parent_path`, which needs to be maintained.

Another solution might be to change collapse-all to match the link path or absolute path, as per find-file 
```lua
      local abs_match = vim.startswith(fname_real, node.absolute_path .. utils.path_separator)
      local link_match = node.link_to and vim.startswith(fname_real, node.link_to .. utils.path_separator)
      local path_matches = node.nodes and (abs_match or link_match)
```

**Comment by lu5je0** [comment]
> > I fixed it in commit [lu5je0@d62336a](https://github.com/lu5je0/nvim-tree.lua/commit/d62336adca34faa7b977dbd43a013cd234c73dbe), but it's probably not the best way.
> 
> I'm not sure about the backlink `parent_path`, which needs to be maintained.
> 
> Another solution might be to change collapse-all to match the link path or absolute path, as per find-file
> 
> ```lua
>       local abs_match = vim.startswith(fname_real, node.absolute_path .. utils.path_separator)
>       local link_match = node.link_to and vim.startswith(fname_real, node.link_to .. utils.path_separator)
>       local path_matches = node.nodes and (abs_match or link_match)
> ```

Actually I used action close_node on child node of symlinked node instead of collapse-all, and is there `link_to` in child nodes of symlinked  node?

**Comment by lu5je0** [comment]
> > I fixed it in commit [lu5je0@d62336a](https://github.com/lu5je0/nvim-tree.lua/commit/d62336adca34faa7b977dbd43a013cd234c73dbe), but it's probably not the best way.
> 
> I'm not sure about the backlink `parent_path`, which needs to be maintained.
> 
> Another solution might be to change collapse-all to match the link path or absolute path, as per find-file
> 
> ```lua
>       local abs_match = vim.startswith(fname_real, node.absolute_path .. utils.path_separator)
>       local link_match = node.link_to and vim.startswith(fname_real, node.link_to .. utils.path_separator)
>       local path_matches = node.nodes and (abs_match or link_match)
> ```

Thanks @alex-courtis, it's great idea to match them both, maybe i can create a PR to fix it.

**Comment by alex-courtis** [comment]
> Thanks @alex-courtis, it's great idea to match them both, but if the tree contains the symlink folder and the original folder, node might still can't be closed.

I see. This solution is more difficult than I am seeing. We really need a means of identifying the parent _in the tree_.

There will be a solution, although I do not have time to dig and investigate until next weekend.

I really appreciate your work @lu5je0 , however we cannot use a backlink, as it adds great complexity that is used only for one case.

**Comment by alex-courtis** [comment]
Looks like https://github.com/lu5je0/nvim-tree.lua/commit/bf1625194bcaea4f83fcee73a0928b69909d74e7 covers this one.

Please reopen if that doesn't work for you @lu5je0

**Comment by lu5je0** [comment]
https://github.com/kyazdani42/nvim-tree.lua/commit/bf1625194bcaea4f83fcee73a0928b69909d74e7 still is not working sometimes when the tree contains the symlink folder and the original folder.Cusor might jump to original folder when we closed symlink folder.
