### ISSUE TITLE
How do I go back to luatree?

### ISSUE THREAD

**Issue by smartding** [kyazdani42/nvim-tree.lua#115]
I accidentally opened a file in the luatree split window, How do I go back to luatree? 
I tried `R` and `:LuaTreeRefresh` to refresh luatree, I also tried `<C-o>`, neither of them worked.

**Comment by smartding** [comment]
`:LuaTreeOpen` and `:LuaTreeToggle` will just show LuaTree in a new split window, still not what I want

**Comment by smartding** [comment]
> i know that's an issue i had too. i disabled some plugins so i cannot open a file in the tree.
> basically i have and opening fzf, so i just mapped C-p and C-b to luatree preview and it prevents opening fzf in the luatree window. I cannot do anything else about that sorry (or thats not something i'm aware of) :)

Could you provide an example of how to remap C-p to do luatree preview for the luatree buffer

**Comment by numToStr** [comment]
This might help you

```lua
-- utils.lua

local U = {}

-- Key mapping
function U.map(mode, key, result, opts)
    opts = opts or {}

    fn.nvim_set_keymap(
        mode,
        key,
        result,
        {
            noremap = opts.noremap or true,
            silent = opts.silent or true,
            expr = opts.expr or false,
            script = opts.script or false
        }
    )
end

-- For moments when I don't want my cursor to stay on the tree
function U.move_cursor_from_tree()
    n = vim.fn.bufname()
    nr = vim.api.nvim_get_current_buf()
    if string.find(n, 'LuaTree') and nr > 1 then
        vim.cmd('exe "normal! \\<C-W>\\<C-W>"')
    end
end

return U
```
```lua
-- fzf.lua

local U = require("utils")

function FZFOpen(cmd_str)
    U.move_cursor_from_tree()
    vim.cmd(cmd_str)
end

-- Ctrl-p = fuzzy finder
U.map("n", "<C-P>", "<CMD>lua FZFOpen(':Files')<CR>")
```

**Comment by smartding** [comment]
I remapped C-p to luatree refresh with this autocmd:
```vim
  autocmd FileType LuaTree nnoremap <silent> <buffer> <C-p> :lua require'tree'.refresh()<CR>
```
I don't know why the following one doesn't work:
```vim
  autocmd BufEnter FileType LuaTree nnoremap <silent> <buffer> <C-p> :lua require'tree'.refresh()<CR>
```
@kyazdani42

**Comment by kyazdani42** [comment]
you cannot bind BufEnter FileType, you can only do one autocmd at a time.

**Comment by smartding** [comment]
> you cannot bind BufEnter FileType, you can only do one autocmd at a time.

ok, got it, thanks
