### ISSUE TITLE
LSP diagnostic not visible in nvim-tree

### ISSUE THREAD

**Issue by yshadow** [kyazdani42/nvim-tree.lua#1157]
### Description

I'm trying to make nvim-tree display the lsp diagnostic errors, but it doesn't seem to work.

![Screenshot from 2022-04-12 09-59-58](https://user-images.githubusercontent.com/13028856/162911036-6d6f1831-0345-4e4a-a895-1fb764ca7092.png)

As you can see from the attached image. I tried the approach described here: [coc-diagnostic](https://github.com/kyazdani42/nvim-tree.lua/issues/1091) by using your feature branch #1091-diagnostics-logging, but there is not log in the ~/.cache/nvim/lsp.log related to diagnostic, just this:

`[START][2022-04-12 09:54:59] LSP logging initiated
`

### Neovim version

```markdown
NVIM v0.6.1
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az87-780
```

### Operating system and version

Ubuntu 20.04

### nvim-tree version

9c272b9

### Steps to reproduce

1. install golang like: rm -rf /usr/local/go && tar -C /usr/local -xzf go1.18.linux-amd64.tar.gz
2. set env variables: export PATH=$PATH:/usr/local/go/bin
3. verify installation go version
4. install gopls: go install golang.org/x/tools/gopls@latest
5. create simple project: 
6. mkdir simple; cd simple
7. nvim main.go
8. paste the following code:
9. `package main
func main() {
    fmt.Println("test")
}
`
10. :w<cr>

you should see this:

![Screenshot from 2022-04-12 10-26-51](https://user-images.githubusercontent.com/13028856/162916345-1d44849b-6092-4f33-bdf2-2ac6b60b3b28.png)

### Expected behavior

Correct icon displayed in the nvim-tree next to the file name of the current buffer.

### Actual behavior

No icon displayed
![Screenshot from 2022-04-12 10-17-20](https://user-images.githubusercontent.com/13028856/162914398-41d0e3fb-d6ec-47aa-8ed8-2351b74bd1f7.png)
.

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvt-min/site]]
local package_root = "/tmp/nvt-min/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup {
    {
      "wbthomason/packer.nvim",
      "kyazdani42/nvim-tree.lua",
      "kyazdani42/nvim-web-devicons",
      "neovim/nvim-lspconfig",
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  }
end
if vim.fn.isdirectory(install_path) == 0 then
  print "Installing nvim-tree and dependencies."
  vim.fn.system { "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path }
end
load_plugins()
require("packer").sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua setup()]]
vim.opt.termguicolors = true
vim.opt.cursorline = true

-- MODIFY NVIM-TREE SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
_G.setup = function()
  require("nvim-tree").setup {
     disable_netrw = true,
     hijack_cursor = true,
     update_focused_file = {
         enable      = true,
         open_on_tab = true,
     },

     diagnostic = {
       enable = true,
       show_on_dirs = true,
       icons = {
         hint = "",
         info = "",
         warning = "",
         error = "",
       },
     },

     view = {
       width = 40,
       side = 'left',
       signcolumn = 'yes',
     },

     log = {
       enable=true,
       truncate=true,
       types={
           diagnostic=true,
       },
     },
  }

  local nvim_lsp = require('lspconfig')
  nvim_lsp.gopls.setup{
      cmd = {'gopls'},
          settings = {
            gopls = {
                analyses = {
                  unusedparams = true,
                  shadow = true,
               },
               staticcheck = true,
               gofumpt = true,
              },
          },
  }
end
```

**Comment by ananta** [comment]
Same behavior on mine too,
Env: Mac OS
Nvim-Tree Version: Latest as of today
LSP Version: Latest as of today

**Comment by alex-courtis** [comment]
You are missing the `s` at the end of `.diagnostics` and `.log.types.diagnostics`.

![2022-04-16-124355_1555x1024_scrot](https://user-images.githubusercontent.com/1505378/163658544-0ab8d51c-0c79-4c2e-94a6-cdd0f11fb59f.png)

**Comment by alex-courtis** [comment]
Merging diagnostics logging and profiling: #1170

**Comment by alex-courtis** [comment]
Please reopen if you have any further questions or issues.

**Comment by yshadow** [comment]
Ok thanks, you were right. Anyway a small niche. When I do:

- nvim 
- :e main.go<cr>
- NvimTreeToggle or NvimTreeOpen<cr>

where the main.go contains an error, I must do <shift>r to reload the tree to display the error. It's not a big deal, but would be nice if it was refreshed by itself. Anyway thank you for this great plugin. IMHO better than nerdtree and definitely better than netrw ;-)

**Comment by alex-courtis** [comment]
> I must do r to reload the tree to display the error.

1. nvim-tree does not display the errors for an open buffer with errors until the buffer is written or the tree is explicitly reloaded.

That is a problem. Investigating.

2. However... if I `nvim -nu /tmp/nvt-min.lua main.go` no errors are shown. I need to reload the unload and reload the buffer before I can see any errors. That indicates a problem with the lspconfig plugin, as nvim-tree is not involved.

I suggest raising an issue at nvim-lspconfig

**Comment by alex-courtis** [comment]
Another problem:

:e main.go
:NvimTreeFindFile
R
move cursor to .. and <CR>

incorrect entry is flagged until R
