### ISSUE TITLE
How to open this file's directory?

### ISSUE THREAD

**Issue by g0J0na** [kyazdani42/nvim-tree.lua#1158]
# How I can switch the directory in nvim-tree to the file's directory?
Example : 
- I open this file in /home/username/Desktop/Work/test.cpp
- And type :e $MYVIMRC ,then open nvim-tree , the tree do not switch directory
![image](https://user-images.githubusercontent.com/90030004/162924240-a772b05f-1e7c-4f7c-b447-6a1de02660f8.png)
  How I can change it to this file's directory? I'm using default settings , I got it after I update my packer ( sorry if u dont understand , my english bad )

**Comment by kyazdani42** [comment]
try setting the `update_focused_file.update_cwd` option to true :)
PS: `:help nvim-tree.update_focused_file`.
This should be set in the setup function btw.
