### ISSUE TITLE
Automatic expand the tree to current file

### ISSUE THREAD

**Issue by ydzhou** [kyazdani42/nvim-tree.lua#1161]
**Is your feature request related to a problem? Please describe.**
If I am editing a file and toggle the tree. The tree is using `pwd` path as the root node.

**Describe the solution you'd like**
I like to add an option so that when I toggle the tree, the tree root node is still `pwd`, but also it expand the path or subtree all the way to my editing file.
For example, my `cd` folder is `/home/username` and file I am editing is `/home/username/example/hw/hello.txt`

Currently, when I toggle the tree, it looks like,
```
/home/username
    ...
    example
    ...
```
With automatic expansion to current file, the tree looks like,
```
/home/username
    ...
    example
        hw
            hello.txt
    ...
```

**Comment by gegoune** [comment]
There is `NvimTreeFindFile` that should do just that.

There also are options like
```lua
  update_focused_file = {
    enable = <bool>,
    update_cwd = <bool>.,
  },
```
which might interest you.

**Comment by ydzhou** [comment]
Wow works like charm with `update_focused_file.enable`

Thanks!
