### ISSUE TITLE
How to connect the same icons as on the screenshot in the dock?

### ISSUE THREAD

**Issue by AntonMamedov** [kyazdani42/nvim-tree.lua#1164]
I did everything according to the instructions, but instead of icons, unreadable characters are shown
![image](https://user-images.githubusercontent.com/63814059/163365003-46c23cc8-edf1-4ac7-8065-04fd681f30eb.png)

I tried to put the icon I needed, but nothing changed
![image](https://user-images.githubusercontent.com/63814059/163365156-443894db-a3e6-4f6e-88c1-a582cd0cc0c3.png)
How to set it up correctly?

**Comment by gegoune** [comment]
You need nerd font icons (either patched font or some sort of fallback mechanism through your terminal emulator).

**Comment by alex-courtis** [comment]
Please reopen if you have any further questions.
