### ISSUE TITLE
Collapse nested folder structure to one until file is found

### ISSUE THREAD

**Issue by megawubs** [kyazdani42/nvim-tree.lua#1165]
**Is your feature request related to a problem? Please describe.**
When I'm working on projects with a lot of folder nesting its frustrating to navigate all the "empty" folders to just get to that one that contains the actual file. See the screenshot of what I try to describe.

<img width="246" alt="Schermafbeelding 2022-04-14 om 15 14 13" src="https://user-images.githubusercontent.com/2302867/163398254-49f46d22-04cb-4bb4-951f-e244ffc9bad4.png">

**Describe the solution you'd like**
I would like the nested folders to be collapsed like Github does:
![image](https://user-images.githubusercontent.com/2302867/163399209-b9e478ed-4aad-43d5-8983-6a8247537f4f.png)

**Describe alternatives you've considered**
None so far, i've tried searching for it but I have a difficult time coming up with the right name for it.

**Additional context**
None.

**Comment by alex-courtis** [comment]
`:help g:nvim_tree_group_empty`

Please reopen if that doesn't work for you or you have further questions.

**Comment by megawubs** [comment]
Thank you! 👍  works just like I want :)
