### ISSUE TITLE
Validate configuration against schema

### ISSUE THREAD

**Issue by gegoune** [kyazdani42/nvim-tree.lua#1166]
**Is your feature request related to a problem? Please describe.**
Keys of a table passed into `setup()` function are plenty, nested and can be very easily misplaced by users. There were issues reported in the past which were simply result of wrong nesting. 

**Describe the solution you'd like**
It would greatly help if plugin was validating table against schema ensuring passed in configuration is valid.

**Describe alternatives you've considered**
Do nothing.

**Additional context**
Edit: this is how b0o achieved it in incline https://github.com/b0o/incline.nvim/blob/main/lua/incline/config/schema.lua.

**Comment by alex-courtis** [comment]
That would be very useful.

nvim-tree has a more complex configuration than incline, however it could cover the tables with entries e.g. `view.mappings` `actions.open_file` etc.

**Comment by alex-courtis** [comment]
Here's a case that this would have prevented #1157

**Comment by alex-courtis** [comment]
Turned out to be quite simple #1177

**Comment by kyazdani42** [comment]
should be implemented in #1195

**Comment by will** [comment]
Yikes. I apparently had a lot of bad options!

```
NvimTree  WARN unknown option: disable_window_picker | unknown option: show_icons | unknown option: update_
to_buf_dir | unknown option: root_folder_modifier | unknown option: quit_on_open | unknown option: git_hl | unknown option: view
.auto_resize
```

**Comment by vohol** [comment]
> Yikes. I apparently had a lot of bad options!
> 
> ```
> NvimTree  WARN unknown option: disable_window_picker | unknown option: show_icons | unknown option: update_
> to_buf_dir | unknown option: root_folder_modifier | unknown option: quit_on_open | unknown option: git_hl | unknown option: view
> .auto_resize
> ```
i have same issue

**Comment by kyazdani42** [comment]
see #674 and recheck your setup options if they are incorrect :)
