### ISSUE TITLE
git highlight not updated

### ISSUE THREAD

**Issue by smartding** [kyazdani42/nvim-tree.lua#117]
I'm using git highlight ( `let g:lua_tree_git_hl = 1` ) without git icon. 
It seems git highlight is only updated the first time luatree is opened. git highlight is't updated when a file is changed, nor is  highlight updated after I manually run the command `:LuaTreeRefresh()`

**Comment by kyazdani42** [comment]
works fine on my end. Maybe you didn't save the file before refreshing ?

**Comment by smartding** [comment]
> works fine on my end. Maybe you didn't save the file before refreshing ?

I found that git highlight is only automatically updated if I enable git icon too. Is it designed this way?

**Comment by kyazdani42** [comment]
really ? it's not designed that way no, i'm gonna fix this

**Comment by kyazdani42** [comment]
fixed in master
