### ISSUE TITLE
Non colored file icons

### ISSUE THREAD

**Issue by Diaoul** [kyazdani42/nvim-tree.lua#1172]
**Is your feature request related to a problem? Please describe.**
I find colored icons too distracting in nvim-tree.
![image](https://user-images.githubusercontent.com/319220/163686094-2c8aea88-5849-4de7-b600-5c659047324a.png)

**Describe the solution you'd like**
The ability to show the icon in the same color as the text with an option or the ability to customize it entirely (like the folder icons)

[feline.nvim](https://github.com/feline-nvim/feline.nvim) has a [`colored_icon` option](https://github.com/feline-nvim/feline.nvim/blob/master/lua/feline/providers/file.lua#L80-L82) that allows to get the icon without the color.
![image](https://user-images.githubusercontent.com/319220/163686059-e988fd07-a9c2-47ad-9785-29e2c46c0a8c.png)

Here is an example with exa that seems to use non-colored icons by default as well (and probably another set of icons):
```exa -al --icons```

![image](https://user-images.githubusercontent.com/319220/163686218-79ede651-212b-4672-a084-a00fa99a321b.png)

**Describe alternatives you've considered**
Using `NvimTreeFileIcon` highlight group does not work.

**Additional context**
:shrug:

**Comment by alex-courtis** [comment]
Looks like we forgot to add the note that the HL group doesn't apply to web-devicons: https://github.com/kyazdani42/nvim-tree.lua/pull/1131

Changing web-devicons can be done: take a look at the conversation in the PR and you should be able to put something together. PRs are always welcome :)

**Comment by Diaoul** [comment]
Wow that was fast and looks like a clean fix in the PR. Thanks a lot :+1:

**Comment by alex-courtis** [comment]
I would be grateful if you could test this branch:

`#1172-non-coloured-webdev-file-icons`

PR is still open, so best to catch issues now.
