### ISSUE TITLE
[Feature Request]: Add "extension" on "sort-by" configuration

### ISSUE THREAD

**Issue by KKD4yv1d** [kyazdani42/nvim-tree.lua#1181]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
A way to sort the files by extension like:
```
~/FolderX/
   > src
    > utils
      utils.h
      view.h
      expr.h
      signal.h
      utils.c
      view.c
      expr.c
      signal.c
    main.c
```

But only have `modification_time` and `name` on the `sort_by` configuration on nvim-tree.setup {}

**Additional context**
Nothing

**Comment by alex-courtis** [comment]
That would be quite useful.
