### ISSUE TITLE
Question - background for folder icons

### ISSUE THREAD

**Issue by MijikHna** [kyazdani42/nvim-tree.lua#1196]
After some update I have got this blue background for folder icons. I thought maybe it would be fixed in next update. But now it seems to me like it is an option that is enabled on my device. I have tried with
![Nvim-Tree](https://user-images.githubusercontent.com/25016507/164994665-5fe7c413-2a82-4c18-9da3-49f1f81cdf98.png)
```
highlight NvimTreeBg guibg=None cterm=None
highlight NvimTreeFolderIcon guibg=None ctermbg=None
```
But it seem to be the wrong option. I also haven't found anything else related to color in README.
Can you please provide me a hint what config options I should change.

**Comment by alex-courtis** [comment]
The background is blue. That is interesting as that matches the [setup example](https://github.com/kyazdani42/nvim-tree.lua#setup).

What does `hi NvimTreeFolderIcon` show?

Please attempt to reproduce this using the minimal configuration as per the [bug report](https://github.com/kyazdani42/nvim-tree.lua/issues/new/choose)

**Comment by MijikHna** [comment]
`hi NvimTreeFolderIcon` Output is `NvimTreeFolderIcon xxx guibg=blue`. 
But actually I change this setting here <https://github.com/MijikHna/dotfiles/blob/main/nvim/plugin/colors.vim>.

**Comment by kyazdani42** [comment]
use `highlight!` to override existing hl groups which muight have been set by your colorscheme.

**Comment by MijikHna** [comment]
Nevermind. You can close this issue. I have set `NvimTreeFolderIcon` in other file to blue.

**Comment by alex-courtis** [comment]
👍
