### ISSUE TITLE
Remove VimEnter event?

### ISSUE THREAD

**Issue by glepnir** [kyazdani42/nvim-tree.lua#120]
Hey check here. First It will take some startuptime time. Second If we lazyload nvim-tree by dein `on_cmd`, dein will add the  nvim-tree.lua to `rtp` we trigger command `LuaTreeToggle`, So it will not trigger `tree.on_enter` function in `augroup LuaTree`. so will cause #119 ,  If use `on_event` with `BufEnter`, nvim-tree works fine. but check startuptime. vimenter events  will take some startuptime.
https://github.com/kyazdani42/nvim-tree.lua/blob/87a4d60bbcdf1161cb70d54a700106fd84b07f0f/plugin/tree.vim#L17

I write a function that works fine with dein `on_cmd  = LuaTreeToggle`, Just need to manually add nvim-tree to rtp before calling the command. This doesn't take startuptime and works fine.
```lua
function M.load_nvim_tree()
  if not vim.o.runtimepath:find("nvim-tree.lua") then
    vim.o.runtimepath = vim.o.runtimepath ..','.. global.cache_dir ..'dein/repos/github.com/kyazdani42/nvim-tree.lua'
  end
  local has_tree,tree = pcall(require,'tree')
  if has_tree then
    tree.on_enter()
  end
  pcall(vim.cmd,'LuaTreeToggle')
end

```
So is it more correct to add the on_enter function to `open` and `toggle`?

```log
110.599  033.494: VimEnter autocommands
110.614  000.015: UIEnter autocommands
110.620  000.006: before starting main loop
112.923  002.303: first screen update
112.926  000.003: --- NVIM STARTED ---
```

After: 
```log
075.940  007.822: VimEnter autocommands
075.943  000.003: UIEnter autocommands
075.947  000.003: before starting main loop
079.055  003.108: first screen update
079.058  000.003: --- NVIM STARTED ---
```

**Comment by glepnir** [comment]
![image](https://user-images.githubusercontent.com/41671631/96743067-2f37ca00-13f6-11eb-93c0-a336e98bb1a9.png)

**Comment by kyazdani42** [comment]
i think the plugin architecture is not really made for lazy loading anyway, i'm thinking about doing a big rewrite to setup the tree with lua and provide users with functions to handle the tree appearance / disappearance manually which would provide more flexibility.
Also i wanted to make the whole think asynchronous, so i could dispatch watch events for the fs which would enable dynamic refresh, but i did not yet manage to grasp how to work with lua coroutines.

**Comment by glepnir** [comment]
Lua's coroutine is not complicated, I will see what I can do for nvim-tree when I have time

**Comment by kyazdani42** [comment]
though i must say, 10ms to load vimenter events is not that big of a deal. My startuptime is 64ms, with a bunch of plugins. Yours is 84, which is not even distinguishable by eye ^^

**Comment by kyazdani42** [comment]
I removed the Vimenter event to run on_enter on package load. If it doesn't fix this issue, please reopen.
