### ISSUE TITLE
How to hide `gitignore`d files by default?

### ISSUE THREAD

**Issue by dycw** [kyazdani42/nvim-tree.lua#1204]
I find myself often having to hide `gitignore`d files every time I start up:

![image](https://user-images.githubusercontent.com/10572122/165405573-28fc36b2-ca31-40a3-84eb-1d1187c2b2cf.png)

#828 showed me `filters.dotfiles` can hide dotfiles by default, but what about `gitignore`d files?

**Comment by be-ndee** [comment]
There is the `git` config, to hide/show them by default:

```
git = {
  enable = true,
  ignore = true,
  timeout = 400,
},
```

Does this help you?

A little bit more search in the issues should have brought you to #1083 :)

**Comment by kyazdani42** [comment]
closing this ^^
