### ISSUE TITLE
Wrong type check for view.width

### ISSUE THREAD

**Issue by cstsunfu** [kyazdani42/nvim-tree.lua#1207]
### Description

This plugin is support number or string format value of view.width, but when set it a string, raise an `invalid option: view.width expected: number actual: string` warning.
 
` ``
 - |view.width|: width of the window, can be either a `%` string or
    a number representing columns. Only works with |view.side| `left` or `right`
      type: `string | number`
      default: `30`
```

### Neovim version

```markdown
any
```

### Operating system and version

any

### nvim-tree version

newest

### Steps to reproduce

Just set view.width to a string

### Minimal config

```Lua
any
```

**Comment by kyazdani42** [comment]
indeed we forgot that @alex-courtis i'm going to change the code to have multiple possible values for width and height

**Comment by alex-courtis** [comment]
Thanks for reporting this @cstsunfu
