### ISSUE TITLE
bring back update_to_buf_dir

### ISSUE THREAD

**Issue by ChristianChiarulli** [kyazdani42/nvim-tree.lua#1210]
**Is your feature request related to a problem? Please describe.**
update_to_buf_dir option is unavailable

**Describe the solution you'd like**
update_to_buf_dir option is back

**Additional context**
Seems to have been removed via this commit: https://github.com/kyazdani42/nvim-tree.lua/commit/3ac443207f21bed29a2a3c2402f64098842ab753

![image](https://user-images.githubusercontent.com/29136904/165685405-9cfcf4e2-7d49-4b53-b68c-31a951c969fb.png)

**Comment by kyazdani42** [comment]
hum sorry this was renamed to hijack_directories !

**Comment by kyazdani42** [comment]
leaving that open to fix the code that silently renames update_to_buf_dir to hijack_directories

**Comment by shaeinst** [comment]
```lua
require'nvim-tree'.setup {
	auto_close = false,
	view = {
	    auto_resize = true,
	},
}

```
and what ```auto_close``` and ```auto_resize``` options renamed to?

**Comment by alex-courtis** [comment]
> and what `auto_close`

This does not exist. You now need to manually automate this: https://github.com/kyazdani42/nvim-tree.lua#tips--reminders

> auto_resize options renamed to?

`actions.open_file.resize_window`
