### ISSUE TITLE
Extra diagnostic sign

### ISSUE THREAD

**Issue by rockyzhang24** [kyazdani42/nvim-tree.lua#1213]
### Description

There is a redundant diagnostic sign when the focus is on the file buffer. If I move the focus to the tree, it is disappeared.

<img width="1728" alt="Screen Shot 2022-04-28 at 13 02 13" src="https://user-images.githubusercontent.com/11582667/165836259-ce031d06-61bc-4de7-ab63-2129eaacabfe.png">

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/11582667/165835949-5c5116db-6ddc-49b2-88e6-3d2e77d924a3.png">

Thank you. 

### Neovim version

```markdown
NVIM v0.8.0-dev+1527-g521e91e1c
```

### Operating system and version

macOS

### nvim-tree version

The latest

### Steps to reproduce

See above. 

### Expected behavior

The extra signs should not be there.

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvt-min/site]]
local package_root = "/tmp/nvt-min/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup {
    {
      "wbthomason/packer.nvim",
      "kyazdani42/nvim-tree.lua",
      "kyazdani42/nvim-web-devicons",
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  }
end
if vim.fn.isdirectory(install_path) == 0 then
  print "Installing nvim-tree and dependencies."
  vim.fn.system { "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path }
end
load_plugins()
require("packer").sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua setup()]]
vim.opt.termguicolors = true
vim.opt.cursorline = true

-- MODIFY NVIM-TREE SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
_G.setup = function()
  require("nvim-tree").setup {
    diagnostics = {
      enable = true,
    }
  }
end
```

**Comment by alex-courtis** [comment]
Another case of #1157

#1174 covered some but not all cases.

Renderer rewrite may make this simpler.

**Comment by alex-courtis** [comment]
I can't replicate this. @rockyzhang24 can you please provide a repo and exact steps to replicate this.

Regardless, there are still some issues (timing?) with regards to showing signs: sometimes an explicit write or refresh is required to update the tree.

**Comment by alex-courtis** [comment]
Problem cases in #1157 are still fixed.

**Comment by rockyzhang24** [comment]
@alex-courtis Thank you for the investigating. 

I post my whole nvim config [here](https://github.com/rockyzhang24/dotfiles/tree/master/.config/nvim) because I have no idea which parts cause this issue. Actually I just use the common plugins and for nvim-tree, I mainly config the mappings and use its default config. 

To reproduce, just open any file and nvim-tree window. Then type anything which causes diagnostic errors. In the nvim-tree, I will see the extra error sign, and it is always on the front of the 3rd entry in the tree. 

Thank you very much.

**Comment by alex-courtis** [comment]
> I post my whole nvim config [here](https://github.com/rockyzhang24/dotfiles/tree/master/.config/nvim) because I have no idea which parts cause this issue. Actually I just use the common plugins and for nvim-tree, I mainly config the mappings and use its default config.

We won't diagnose your vim plugins and configuration. That is up to you.

Suggested actions for you:

1. Start with the minimum config above and run `nvim -nu /tmp/nvt-min.lua`. Add your plugins and configuration until the issue appears.
2. Start with your full config and remove plugins / settings / customisations until the issue goes away.

Please reopen the ticket if you find a case that we can reproduce, providing the minimal configuration for that reproducer.

**Comment by rockyzhang24** [comment]
I think this issue is caused by `foldsigns.nvim`. I already opened an [issue](https://github.com/lewis6991/foldsigns.nvim/issues/3) there.
