### ISSUE TITLE
Opening a second file is creating a new window

### ISSUE THREAD

**Issue by be-ndee** [kyazdani42/nvim-tree.lua#1214]
### Description

I have disabled the window_picker. And when I open two files, then it creates a new window for both of the files. So I end up having 3 windows: nvim-tree, file A and file B. Any other file will be opened in the window of file B.

I've tried to fix this bug, but I did not understand the behavior 100%. What I noticed, is that the `_prevent_buffer_override()` function is called when opening file B, but not while opening file A. And then the line `a.nvim_win_close(curwin, { force = true })` is called. But when I look at the window numbers which are used, everything looks good...

Maybe you have a clue or can give me a hint when the `_prevent_buffer_override` should be called.

### Neovim version

```markdown
NVIM v0.8.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

### Operating system and version

Linux 20.04.1-Ubuntu

### nvim-tree version

master

### Steps to reproduce

IMPORTANT: window_picker must be disabled

1. Open neovim
2. Open a file with pressing enter in nvim-tree
3. Cursor should be in a new buffer with the new file
4. Navigate the cursor to the nvim-tree
5. Open a different file with pressing enter in nvim-tree

### Expected behavior

The second file should not create a third window. It should replace the file in the second window:

Windows:

```
1. nvim-tree
2. file B
```

Buffers:

```
1. nvim-tree
2. file A
3. file B
```

### Actual behavior

The second file is creating a third window:

Windows:

```
1. nvim-tree
2. file A
3. file B
```

Buffers:

```
1. nvim-tree
2. file A
4. file B
```

### Minimal config

```Lua
require'nvim-tree'.setup {
  disable_netrw = true,
  view = {
    width = 40,
    hide_root_folder = true,
    relativenumber = true,
  },
  actions = {
    open_file = {
      resize_window = true,
      window_picker = {
        enable = false,
      }
    }
  }
}
```

**Comment by alex-courtis** [comment]
I can't replicate this; I'm doing something wrong:

[![asciicast](https://asciinema.org/a/491180.svg)](https://asciinema.org/a/491180)

Should I be opening a new split somewhere in there?

**Comment by kyazdani42** [comment]
Cannot reproduce either, i don't think this is related to nvim-tree somehow.

**Comment by be-ndee** [comment]
That is strange... because to test this, I've just removed all plugins. So my neovim config looks just like this:

```
call plug#begin(stdpath('data') . '/plugged')

Plug 'kyazdani42/nvim-web-devicons'
Plug 'kyazdani42/nvim-tree.lua'

call plug#end()

luafile ~/.config/nvim/setup_plugins.lua
```

setup_plugins.lua:

```
vim.opt.splitright = true
require'nvim-tree'.setup {
  actions = {
    open_file = {
      window_picker = {
        enable = false,
      }
    }
  }
}
```

And the problem still exists... do you have any idea how I can debug this behavoir?

https://user-images.githubusercontent.com/5873296/166196529-2c487e09-d798-4e29-ae39-f866a78dac99.mov

**Comment by alex-courtis** [comment]
Sorry... I still can't replicate. I see how it is happening for you.

> NVIM v0.8.0-dev

Let's try with 0.7.0. I don't think 0.8 will be very stable...

Out of interest: does your distro's (debian?) package manager install the latest / dev versions of packages? Should we expect that others will be using an unstable version?

**Comment by be-ndee** [comment]
I'm using different os. At home its linux with neovim 0.8.0-dev and at work I use macos with neovim 0.7.0. And I experience this issue in both neovim versions..

**Comment by be-ndee** [comment]
Do you have any idea how I can debug this? It has something todo with the `autocommand` which is used to prevent neovim to replace the nvim-tree with an opening file. I tried to analyse the window/buffer ids, but I did not figure out the problem...

**Comment by alex-courtis** [comment]
> It has something todo with the `autocommand` which is used to prevent neovim to replace the nvim-tree with an opening file.

Could you try commenting that out? Maybe some other :au as well?

**Comment by be-ndee** [comment]
If I remove this line the first file will be opened correctly, but the second file will be opened in the window of the tree and replaces the tree.

```
vim.cmd "au BufWipeout NvimTree_* lua require'nvim-tree.view'._prevent_buffer_override()"
```

I've logged the `target_winid` inside the `function M.fn(mode, filename)` in `open-file.lua`:

```
function M.fn(mode, filename)
  if mode == "tabnew" then
    open_file_in_tab(filename)
    return
  end

  ...

      found = true
      api.nvim_set_current_win(id)
      break
    end
  end
  
  -- LOGGING
  print("target " .. target_winid)

  if not found then
    if not target_winid or not vim.tbl_contains(win_ids, target_winid) then
      -- Target is invalid, or window does not exist in current tabpage: create
      -- new window
      local split_cmd = get_split_cmd()
      local splitside = view.is_vertical() and "vsp" or "sp"
      vim.cmd(split_cmd .. " " .. splitside)
      target_winid = api.nvim_get_current_win()
      lib.target_winid = target_winid

  ...
```

The result was:

```
first file: 1000
second file: 1000
third file: 1004
```

**Comment by alex-courtis** [comment]
Replicated

```lua
require('packer').startup(function()
	use "wbthomason/packer.nvim"
	use "kyazdani42/nvim-tree.lua"
	use "kyazdani42/nvim-web-devicons"
end)

require("nvim-tree").setup {
	actions = {
		open_file = {
			window_picker = {
				enable = false,
			}
		}
	},
	log = {
		enable = true,
		truncate = true,
		types = {
			all = true,
		},
	},
}
```

[![asciicast](https://asciinema.org/a/492733.svg)](https://asciinema.org/a/492733)

Logs
```
[2022-05-07 12:13:47] [profile] START draw
[2022-05-07 12:13:47] [profile] END   draw  0ms
[2022-05-07 12:13:47] [profile] START draw
[2022-05-07 12:13:47] [profile] END   draw  0ms
[2022-05-07 12:13:50] [open-file] filename '/tmp/1214/A'  target_winid 1000
[2022-05-07 12:13:54] [open-file] filename '/tmp/1214/B'  target_winid 1000
[2022-05-07 12:13:54] [profile] START draw
[2022-05-07 12:13:54] [profile] END   draw  0ms
[2022-05-07 12:13:54] [open-file] filename '/tmp/1214/B'  target_winid 1000
[2022-05-07 12:13:58] [open-file] filename '/tmp/1214/C'  target_winid 1004
```

Important
* must start via `nvim -nu /tmp/nvt-min.lua .`
* use existing packer packages so that we don't have a race condition with netrw
* `window_picker.enable = false` is necessary

Noteworthy
* first editor is opened on the left
* nvim-tree is shifted to the left after opening second file

**Comment by be-ndee** [comment]
Thank you @alex-courtis for looking at this issue and @kyazdani42 for fixing it. I've not experienced this error again :)
