### ISSUE TITLE
Git Status For Symlinks

### ISSUE THREAD

**Issue by alex-courtis** [kyazdani42/nvim-tree.lua#1217]
**Is your feature request related to a problem? Please describe.**
Git status is not shown for symlinks: direct file links or folder links.

**Describe the solution you'd like**
Git status shown, with folder symlinks showing status in the same manner as real folders.

**Describe alternatives you've considered**
Do nothing.

**Additional context**
N/A

**Comment by alex-courtis** [comment]
Do this after #1203 is merged.

I've had a quick play and we can achieve this with some tweaking of `node-builders.link`.

**Comment by alex-courtis** [comment]
WIP: https://github.com/kyazdani42/nvim-tree.lua/tree/1217-symlink-git-status

TODO: `reload.update_status`

**Comment by kyazdani42** [comment]
waiting for feedback on my renderer PR

**Comment by kyazdani42** [comment]
should've been closed by #1203

**Comment by alex-courtis** [comment]
Still not quite right.
1. Icons are correct for symlink files/dirs themselves i.e. symlinks added/staged
1. Icons are missing when symlinks are committed and their contents are dirty

Directory target:
```
ln -s scripts scripts-linked
untracked: scripts-linked

open scripts-linked/setup-hooks.sh or scripts/setup-hooks.sh
modify setup-hooks.sh
unstaged: scripts, scripts/setup-hooks.sh, scripts-linked/setup.hooks.sh

git add scripts-linked
staged: scripts-linked

git commit -m "add scripts-linked"
no icon: scripts-linked <- INCORRECT
```

File target:
```
ln -s README.md README.md.linked
untracked: README.md.linked

git add README.md.linked
staged: README.md.linked

open README.md.linked
modify README.md.linked
unstaged: README.md
no icon: README.md.linked <- INCORRECT
```

I think the correct approach is display 1 first, then 2 if the symlinks themselves are not dirty.

WIP branch addresses that. I'll work on it.

**Comment by kyazdani42** [comment]
I see :) i did not understand that ^^
