### ISSUE TITLE
Do not reset tree width when opening a document

### ISSUE THREAD

**Issue by kristijanhusak** [kyazdani42/nvim-tree.lua#122]
Today I was working with some nested folders, where I had to increase the width of the tree window to see full name of the file. Once the file is opened (or previewed), tree size goes back to the default size, which is really annoying when you have to preview multiple things.

**Comment by kristijanhusak** [comment]
Ok, I found a setting in code that is not documented, that does exactly this.

```vim
let g:lua_tree_width_allow_resize = v:true
```

I guess we could just add it to docs.

**Comment by kyazdani42** [comment]
was added this week, i'll update the docs soon

**Comment by kristijanhusak** [comment]
Also note that it will not work if it's set to `1`, so I guess we should either emphasize that in the docs, or make it work for both `true` and `1`.

**Comment by kyazdani42** [comment]
it should work both for true and 1. I'll fix that altogether

**Comment by kyazdani42** [comment]
fixed in latest master :)
