### ISSUE TITLE
call NvimTreeToggle, Invalid parameter

### ISSUE THREAD

**Issue by tttoad** [kyazdani42/nvim-tree.lua#1221]
### Description

When I call NvimTreeToggle, I get an error

![image](https://user-images.githubusercontent.com/14021602/166121877-5c4d9750-b14c-4019-8e0a-4545ad9ca5e3.png)

### Neovim version

```markdown
NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

macOS 11.2.3

### nvim-tree version

86d573d

### Steps to reproduce

:NvimTreeToggle

### Minimal config

```Lua
-- init.lua
vim.o.ignorecase=true

vim.opt.encoding="UTF-8"
vim.o.number=true
-- 设置行会导致输入指令后乱码...
-- vim.o.lines=60
vim.opt.mouse="a"
vim.o.cursorline=true
vim.opt.laststatus=2
vim.o.autoindent=true
vim.opt.tabstop=4
vim.o.smarttab=true
vim.opt.shiftwidth=4
vim.opt.softtabstop=4
vim.opt.backspace="eol,start,indent"
vim.o.showcmd=true
vim.o.whichwrap=vim.o.whichwrap.."<,>,h,l"
vim.opt.scrolloff=3
vim.opt.history=1000
vim.opt.cmdheight=2


require'nvim-tree'.setup {
}
return require('plugins')
```

**Comment by gulliver-madrid** [comment]
Same issue in Windows 10, NVIM 0.6.1, default configuration.

**Comment by alex-courtis** [comment]
The above minimal config does not run. Please provide a full nvt-min.lua as per the [bug report](https://github.com/kyazdani42/nvim-tree.lua/issues/new/choose) so that we can try to reproduce.

**Comment by alex-courtis** [comment]
Could not replicate with minimal configuration nvim 0.6.1

I've added some logging and the following is being successfully executed:
```
setlocal winhl=EndOfBuffer:NvimTreeEndOfBuffer,Normal:NvimTreeNormal,CursorLine:NvimTreeCursorLine,WinSeparator:NvimTreeWinSeparator,StatusLine:NvimTreeStatusLine,StatusLineNC:NvimTreeStatuslineNC,SignColumn:NvimTreeSignColumn,NormalNC:NvimTreeNormalNC
```

I cannot exactly compare this to your error as you have not provided the error text, just a picture.

E474 may be ambiguous without the message. Please can you provide the english translation of the message.

**Comment by alex-courtis** [comment]
Actions:

@tttoad 
- translate the E474 error message

@ttoad @gulliver-madrid 
- test with a minimal configuration as per [bug report](https://github.com/kyazdani42/nvim-tree.lua/issues/new/choose)
- attempt to execute some of the command via vim command e.g. `setlocal winhl=EndOfBuffer:NvimTreeEndOfBuffer`, repeating until you receive the error

**Comment by Marko-Sanchez** [comment]
Similar issue when calling `:NvimTreeOpen`
```
E5108: Error executing lua ...im/autoload/plugged/nvim-tree.lua/lua/nvim-tree/view.lua:121: Vim(setlocal):E474: Invalid argument: winhl=EndOfBuffer:NvimTreeEndOfBuffer,Normal:NvimTreeNormal,CursorLine:NvimTreeCurs
orLine,WinSeparator:NvimTreeWinSeparator,StatusLine:NvimTreeStatusLine,StatusLineNC:NvimTreeStatuslineNC,SignColumn:NvimTreeSignColumn,NormalNC:NvimTreeNormalNC                                                     
stack traceback:                                                                                                                                                                                                     
        [C]: in function 'cmd'                                                                                                                                                                                       
        ...im/autoload/plugged/nvim-tree.lua/lua/nvim-tree/view.lua:121: in function 'set_local'                                                                                                                     
        ...im/autoload/plugged/nvim-tree.lua/lua/nvim-tree/view.lua:139: in function 'set_window_options_and_buffer'                                                                                                 
        ...im/autoload/plugged/nvim-tree.lua/lua/nvim-tree/view.lua:193: in function 'open'                                                                                                                          
        ...vim/autoload/plugged/nvim-tree.lua/lua/nvim-tree/lib.lua:97: in function 'open_view_and_draw'                                                                                                             
        ...vim/autoload/plugged/nvim-tree.lua/lua/nvim-tree/lib.lua:123: in function 'open'                                                                                                                          
        ...ig/nvim/autoload/plugged/nvim-tree.lua/lua/nvim-tree.lua:47: in function 'open'                                                                                                                           
        [string ":lua"]:1: in main chunk                  
```

Problem seems to be in view.lua, the setlocal() function was added to solve this [issue](https://github.com/neovim/neovim/issues/14670)

My specs: `nvim --version` On Ubuntu 18.04.6 LTS x86_64
```
NVIM v0.6.1
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```
with default build config. 
```
-- following options are the default
-- each of these are documented in `:help nvim-tree.OPTION_NAME`
vim.g.nvim_tree_icons = {
  default = "",
  symlink = "",
  git = {
    unstaged = "",
    staged = "S",
    unmerged = "",
    renamed = "➜",
    deleted = "",
    untracked = "U",
    ignored = "◌",
  },
  folder = {
    default = "",
    open = "",
    empty = "",
    empty_open = "",
    symlink = "",
  },
}

local status_ok, nvim_tree = pcall(require, "nvim-tree")
if not status_ok then
  return
end

local config_status_ok, nvim_tree_config = pcall(require, "nvim-tree.config")
if not config_status_ok then
  return
end

nvim_tree.setup{}
```

**Comment by fakeYanss** [comment]
Similar issue when calling :NvimTreeOpen

<img width="1538" alt="image" src="https://user-images.githubusercontent.com/30440198/166130766-8f1a7773-8934-4970-af58-d00f219cad1f.png">

My specs: nvim --version On macOS 12.3 (21E230):
```
My nvim version
NVIM v0.7.0-dev+1135-gfdea15723
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

with default build config.
```
require('nvim-tree').setup {
}
```

**Comment by alex-courtis** [comment]
> Problem seems to be in view.lua, the setlocal() function was added to solve this [issue](https://github.com/neovim/neovim/issues/14670)

The upstream issue is complex and does not appear to have been resolved.

setlocal is correctly setting the window option winhl in neovim 0.6.1 and 0.7.0.

Therefore we will not investigate it when diagnosing this bug, unless all other avenues have been exhausted.

> E5108: Error executing lua ...im/autoload/plugged/nvim-tree.lua/lua/nvim-tree/view.lua:121: Vim(setlocal):E474: Invalid argument:

This indicates that we are attempting to set the value for a highlight-group that is not built-in. See `:help winhl`

The simple test `:setlocal winhl=AAA:ZZZ` demonstrates this, `:setlocal winhl=NormalNC:ZZZ` does not.

**Comment by alex-courtis** [comment]
### Actions: @tttoad @gulliver-madrid @Marko-Sanchez @fakeYanss :

Execute this and put the results into a file. This will discover the bulit-in highlight groups.
```vim
redir @" | silent hi | redir end | let @+ = @"
```

Execute the following until an error occurs.
```vim
:setlocal winhl=EndOfBuffer:NvimTreeEndOfBuffer
:setlocal winhl=Normal:NvimTreeNormal
:setlocal winhl=CursorLine:NvimTreeCursorLine
:setlocal winhl=WinSeparator:NvimTreeWinSeparator
:setlocal winhl=StatusLine:NvimTreeStatusLine
:setlocal winhl=StatusLineNC:NvimTreeStatuslineNC
:setlocal winhl=SignColumn:NvimTreeSignColumn
:setlocal winhl=NormalNC:NvimTreeNormalNC
:setlocal winhl=EndOfBuffer:NvimTreeEndOfBuffer,Normal:NvimTreeNormal,CursorLine:NvimTreeCursorLine,WinSeparator:NvimTreeWinSeparator,StatusLine:NvimTreeStatusLine,StatusLineNC:NvimTreeStatuslineNC,SignColumn:NvimTreeSignColumn,NormalNC:NvimTreeNormalNC
```

Repeat the above, starting neovim via `nvim --clean`.

### Actions: @alex-courtis :

Depending on the results of the above
- attempt a fix
- create a branch with some diagnostics

**Comment by evantancy** [comment]
Idk what's going on but setting the commit using vim-plug for https://github.com/kyazdani42/nvim-tree.lua/commit/428898154f909d2e1d07b185b2f82e412882d5f2 seems to fix

**Comment by anpin** [comment]
hi @alex-courtis, I'm on win10 and after running suggested commands I found that E474 occurs at `:setlocal winhl=WinSeparator:NvimTreeWinSeparator` and `:setlocal winhl=EndOfBuffer:NvimTreeEndOfBuffer,Normal:NvimTreeNormal,CursorLine:NvimTreeCursorLine,WinSeparator:NvimTreeWinSeparator,StatusLine:NvimTreeStatusLine,StatusLineNC:NvimTreeStatuslineNC,SignColumn:NvimTreeSignColumn,NormalNC:NvimTreeNormalNC` also see the requested output here  [nvim.txt](https://github.com/kyazdani42/nvim-tree.lua/files/8598383/nvim.txt)

**Comment by alex-courtis** [comment]
> I found that E474 occurs at `:setlocal winhl=WinSeparator:NvimTreeWinSeparator`

That's great, thank you. We can see that the `WinSeparator` highlight group is definitely not present. This can be investigated.

In the meantime, I might hack together a temporary hacky fix that doesn't set this group if it's not available.

**Comment by alex-courtis** [comment]
Reverted #1219

Please update to latest nvim-tree.lua and test.

**Comment by alex-courtis** [comment]
https://github.com/neovim/neovim/issues/18325 indicates that VertSplit is no longer an independent highlight group however it is still present, hence the revert is safe.

**Recommended long term fix:**
Test whether `WinSeparator` is available and use that, falling back to `VertSplit`.
I'm not seeing any useful API; we could just use `pcall(vim.cmd, ":hi WinSeparator")`

**Comment by anpin** [comment]
@alex-courtis works as before, thanks!

**Comment by alex-courtis** [comment]
Revert reported successful.

The link WinSeparator -> VertSplit in nvim 0.7+ seems permanent, so nothingto do here.

**Comment by tttoad** [comment]
@alex-courtis Thank you for your help,nvim-tree is now working properly.  I'm on holiday these days, I can't reply to your message, sorry.

**Comment by valentino-sm** [comment]
Reproduce the error:

```
call plug#begin()
Plug 'dracula/vim', { 'as': 'dracula' }
Plug 'kyazdani42/nvim-web-devicons' " for file icons
Plug 'kyazdani42/nvim-tree.lua'
call plug#end()

colorscheme dracula
lua require('nvim-tree').setup()
```

**Comment by alex-courtis** [comment]
> Reproduce the error:

If you are still experiencing this error, please ensure that you have updated your nvim-tree.lua version via, say, `:PlugUpdate`.

Failing the above please raise a new issue and complete the full bug report form.

**Comment by valentino-sm** [comment]
> Failing the above please raise a new issue and complete the full bug report form.

I don't know if it's worthy actually.
The error occurs only if setup() is under that specific colorscheme.
