### ISSUE TITLE
Updated that broke config

### ISSUE THREAD

**Issue by Grzanka99** [kyazdani42/nvim-tree.lua#1224]
### Description

```
require("nvim-tree").setup({
	-- open_on_startup = false,
	open_on_tab = false,
	update_focused_file = {
		enable = true,
	},
	diagnostics = {
		enable = true,
		icons = {
			hint = "",
			info = "",
			warning = "",
			error = "",
		},
	},
	view = {
		width = 40,
		side = "right",
		-- auto_resize = false,
		mappings = {
			custom_only = false,
		},
	},
	-- show_icons = {
	-- 	git = 1,
	-- 	folders = 1,
	-- 	files = 1,
	-- 	folder_arrows = 1,
	-- 	tree_width = 30,
	-- },
	-- ignore = { ".git", "node_modules", ".cache" },
	filters = {
		custom = { ".git", "node_modules", ".cache" },
	},
	-- hide_dotfiles = true,
	-- git_hl = true,
	-- root_folder_modifier = ":t",
	update_cwd = true,
	-- respect_buf_cwd = false,
	-- allow_resize = true,
	-- auto_ignore_ft = { "startify", "dashboard" },
	-- icons = {
	-- 	default = "",
	-- 	git = {
	-- 	symlink = "",
	-- 		unstaged = "",
	-- 		staged = "S",
	-- 		unmerged = "",
	-- 		renamed = "➜",
	-- 		deleted = "",
	-- 		untracked = "U",
	-- 		ignored = "◌",
	-- 	},
	-- 	folder = {
	-- 		default = "",
	-- 		open = "",
	-- 		empty = "",
	-- 		empty_open = "",
	-- 		symlink = "",
	-- 	},
	-- },
})
```
I had to comment out like half of my config after some update bcs. it was broken. No notification. I think time to find better tree.

### Neovim version

```markdown
NVIM v0.7.0
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

Linux 5.17.4-arch1-1

### nvim-tree version

483f155

### Steps to reproduce

Run my attached config

### Expected behavior

To work fine or atleast for some time and indicate depracated and new names of options

### Actual behavior

Warning without explaining new names of options

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvt-min/site]]
local package_root = "/tmp/nvt-min/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup {
    {
      "wbthomason/packer.nvim",
      "kyazdani42/nvim-tree.lua",
      "kyazdani42/nvim-web-devicons",
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  }
end
if vim.fn.isdirectory(install_path) == 0 then
  print "Installing nvim-tree and dependencies."
  vim.fn.system { "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path }
end
load_plugins()
require("packer").sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua setup()]]
vim.opt.termguicolors = true
vim.opt.cursorline = true

-- MODIFY NVIM-TREE SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
_G.setup = function()
  require("nvim-tree").setup {}
end
```

**Comment by alex-courtis** [comment]
> I had to comment out like half of my config after some update bcs. it was broken. No notification. I think time to find better tree.

How was the tree broken? Was there an error message? We cannot investigate a problem without any information.

**Comment by alex-courtis** [comment]
> ### Expected behavior
> To work fine or atleast for some time and indicate depracated

Refactored options are silently copied to the new option and will continue to work. You are now warned about this so that you may update your config.

Removed options are noted e.g. "auto close feature has been removed, see note in the README (tips & reminder section)"

No options are deprecated.

>  and new names of options

This is possible. We could maintain mappings to add information for the message e.g.
view.auto_resize -> actions.open_file.resize_window

**Comment by Grzanka99** [comment]
Thank, good to know that things should work like previously, but would be really nice if there will be documentation on github or something fully explains all options and for what they change, maybe instead warning message, some kind like deprecated and link to docs?

**Comment by kyazdani42** [comment]
closing since this completely out of our scope. The documentation exists and is full explained `:help nvim-tree`, please read this first before making such unpleasant comments.
