### ISSUE TITLE
Feature: close_node behaviour depends on focussed node state

### ISSUE THREAD

**Issue by fgheng** [kyazdani42/nvim-tree.lua#1226]
### Description

look at this picture
![image](https://user-images.githubusercontent.com/50551377/166195973-fcdb31ab-0a05-43ff-8a2e-3f04b223b40f.png)

My cursor is at the node of vime, but if I close the node, it not close the vime rather than close the  dir lua.

I want to close the dir vime.

### Neovim version

```markdown
NVIM v0.8.0-dev+95-g07660193a
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

### Operating system and version

arch linux

### nvim-tree version

483f155

### Steps to reproduce

always exists

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvt-min/site]]
local package_root = "/tmp/nvt-min/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup {
    {
      "wbthomason/packer.nvim",
      "kyazdani42/nvim-tree.lua",
      "kyazdani42/nvim-web-devicons",
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  }
end
if vim.fn.isdirectory(install_path) == 0 then
  print "Installing nvim-tree and dependencies."
  vim.fn.system { "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path }
end
load_plugins()
require("packer").sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua setup()]]
vim.opt.termguicolors = true
vim.opt.cursorline = true

-- MODIFY NVIM-TREE SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
_G.setup = function()
  require("nvim-tree").setup {}
end
```

**Comment by alex-courtis** [comment]
Cannot replicate with 483f155

I see you have some customisations in that picture. Please confirm the bug using `nvim -nu /tmp/nvt-min.lua`.

> NVIM v0.8.0-dev+95-g07660193a

Please try with the stable 0.7.0 release.

**Comment by fgheng** [comment]
Using neovim 0.7 and using `nvim -nu /tmp/nvt-min.lua`, quertion still exists, look at this picture, I want to close the dir 'vime' (pic1) while the cursor stay on it, but the command 'close node' closed vime's parent node 'lua' (pic2).

pic1
![image](https://user-images.githubusercontent.com/50551377/166407552-4cea3180-4075-49a1-9a7d-6f2c1ed07e68.png)
pic2
![image](https://user-images.githubusercontent.com/50551377/166407566-2b3015c5-c59f-4489-8cb4-737a338b3c10.png)

what I wanted is that if the cursor on a dir node, close it rather than close its parent like pic3

pic3
![image](https://user-images.githubusercontent.com/50551377/166407625-d1701438-290a-4ea6-8baa-cc84be5659f4.png)


### neovim version :
NVIM v0.7.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by runner@fv-az316-460

**Comment by alex-courtis** [comment]
I understand. You are using `close_node` ; I was using `edit`. That is expected behaviour for `close_node`.

I think you might want a new action like `close_children`.

**Comment by fgheng** [comment]
> I understand. You are using `close_node` ; I was using `edit`. That is expected behaviour for `close_node`.
> 
> I think you might want a new action like `close_children`.

Yes, thank you very much

**Comment by eirabben** [comment]
Hi

I'm currently dealing with the same thing as @fgheng. I think there might have been a change in the behavior of `close_node` a little while ago, because I cannot remember this happening before.

What I expect to happen when i call the `close_node` action is this: If the cursor is positioned on an open folder, I expect that folder to close. If the current folder is closed, or the cursor is on a file, I expect the parent folder to close. 

In the current version of nvim-tree, the parent folder closes regardless of the state of the folder under the cursor.

I'm not sure that a `close_children` action will solve this.

Although, if the current behavior of `close_node` is the intended one, I would like to request an example of how to setup this functionality in my config.

**Comment by alex-courtis** [comment]
> I'm not sure that a `close_children` action will solve this.

Yes. `close_children` would not be that useful.

> Although, if the current behavior of `close_node` is the intended one, I would like to request an example of how to setup this functionality in my config.

My usage patterns is simple: use `close_node` to collapse the whole directory, `edit` to close the focussed directory.

**Comment by alex-courtis** [comment]
The feature request:

**`close_node`: If the cursor is positioned on an open folder, I expect that folder to close. If the current folder is closed, or the cursor is on a file, I expect the parent folder to close.**

Options:
* breaking change to `close_node` behaviour
* option to enable this behaviour for `close_node`
* new action

**Comment by kyazdani42** [comment]
It might have changed indeed because i've made a bit of refactoring and very much simplified the original code. I think the behavior can be reinstated easily though :)
Can you see #1239 if this fix it back to the original behavior ?
