### ISSUE TITLE
Unwanted tab switch

### ISSUE THREAD

**Issue by igorlfs** [kyazdani42/nvim-tree.lua#1227]
### Description

When multiple instances of nvim-tree are open in different tabs, closing nvim-tree in one of them, moves you to the next tab with nvim-tree open. 

### Neovim version

```markdown
NVIM v0.7.0
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

Linux 5.17.4

### nvim-tree version

483f155

### Steps to reproduce

1. `nvim -nu /tmp/nvt-min.lua`
2. `:NvimTreeOpen`
3. `:tabnew`
4. `:NvimTreeOpen`
5. `gt` (return to first tab)
6. `:NvimTreeClose`

### Expected behavior

Closing an instance shouldn't switch tabs.

### Actual behavior

Closing switches tabs.

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvt-min/site]]
local package_root = "/tmp/nvt-min/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup {
    {
      "wbthomason/packer.nvim",
      "kyazdani42/nvim-tree.lua",
      "kyazdani42/nvim-web-devicons",
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  }
end
if vim.fn.isdirectory(install_path) == 0 then
  print "Installing nvim-tree and dependencies."
  vim.fn.system { "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path }
end
load_plugins()
require("packer").sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua setup()]]
vim.opt.termguicolors = true
vim.opt.cursorline = true

_G.setup = function()
  require("nvim-tree").setup {}
end
```

**Comment by alex-courtis** [comment]
That's great, thank you @igorlfs . That test case is very replicable.

**Comment by alex-courtis** [comment]
When closing, the focus is shifted to the previous window at the time of that tree opening.

Closing this issue and tracking in #1228 which demonstrates the same.
