### ISSUE TITLE
Auto open on current selected view port

### ISSUE THREAD

**Issue by kaykhancheckpoint** [kyazdani42/nvim-tree.lua#1229]
If i create multiple viewports in nvim. And i want to open a new file in the bottom viewport (B) by pressing enter on the filename in nvim-tree it asks me which viewport i want to open that file in (A or B) is there a way to make it automatically open it up in the view i was in.

**Comment by alex-courtis** [comment]
`actions.open_file.window_picker.enable`

See `:help nvim-tree.actions`.

The most recently used window (viewport?) will be used.

**Comment by alex-courtis** [comment]
Please reopen if you have any further questions.

**Comment by kaykhancheckpoint** [comment]
> `actions.open_file.window_picker.enable`
> 
> See `:help nvim-tree.actions`.
> 
> The most recently used window (viewport?) will be used.

Thats already enabled for me and im still having to select

**Comment by alex-courtis** [comment]
> Thats already enabled for me and im still having to select

I think you will need to set enable to false for the behaviour you desire.
