### ISSUE TITLE
plugin updated but still seeing the issue on nvim start,  ERROR: [NvimTree] unknown option

### ISSUE THREAD

**Issue by preethamveeranna** [kyazdani42/nvim-tree.lua#1231]
### Description

complete error description:
**[NvimTree] unknown option: update_to_buf_dir | unknown option: quit_on_open | unknown option: git_hl | unknown option: disable_window_picker | unknown option: root_folder_modifier | unknown option: show_icons**

### Neovim version

```markdown
NVIM v0.7.1-dev+9-gaff05c573
Build type: Debug
LuaJIT 2.1.0-beta3
```

### Operating system and version

Ubuntu WSL

### nvim-tree version

aff05c573

### Steps to reproduce

1. open nvim
2. error shown

### Expected behavior

NO error

**Comment by alex-courtis** [comment]
Those are not valid options or they are not in the correct place.

See `:help nvim-tree.setup` for the available options and their defaults.

**Comment by Johan-Palacios** [comment]
I have the smame issue 

NVIM v0.8.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

Ubuntu WSL2

NvimTree Commit

483f1550d1c53f7dcf261d40af5f993ffcb8b9c3


<img width="960" alt="image" src="https://user-images.githubusercontent.com/77251405/166510240-c0b1c6f5-bfff-44d5-abc8-d7322b8900ca.png">

**Comment by preethamveeranna** [comment]
updated with new config options. thanks.
