### ISSUE TITLE
luatree remains in old dir after changing working dir

### ISSUE THREAD

**Issue by smartding** [kyazdani42/nvim-tree.lua#124]
I changed neovim's global working directory with  `vim.api.nvim_set_current_dir()`, I checked with `pwd`, and it says I'm in the new directory.
But when I open luatree with `require('tree').toggle()`, luatree still shows me the old directory.

**Comment by kyazdani42** [comment]
there are some issues with the path handling indeed. I'm currently working on a rewrite of this plugin to provide a better and extensible api and more features.

**Comment by kyazdani42** [comment]
this should have been fixed a long time ago, closing :)
