### ISSUE TITLE
Make refactoring files/folders easier

### ISSUE THREAD

**Issue by sangdth** [kyazdani42/nvim-tree.lua#1247]
**Is your feature request related to a problem? Please describe.**
After a while, the project usually need to be refactored. It requires a lot of creating/moving/renaming folders. The repetitive makes me less productive.

**Describe the solution you'd like**
The ability to select files/folders, then combine with next action.

Example of using:
- I select a folder `/example` (with lot of files/folders inside it)
- Run refactor, type new name `new-folder`
- The structure now is `/new-folder/example/...`

Another example of using I posted in discussion https://github.com/kyazdani42/nvim-tree.lua/discussions/1232

**Describe alternatives you've considered**
Another "lite" version could be `add-and-move` the current file/folder that the cursor is staying on top.
- Move the cursor on top of a file, `/example.ts`.
- Run `add-and-move`, type `new-folder/`
- The new structure will be `/new-folder/example.ts`

**Additional context**
I will update when I can have more information of it.

**Comment by kyazdani42** [comment]
Hi @sangdth, will that be closed by https://github.com/kyazdani42/nvim-tree.lua/pull/1419 ?

**Comment by mario-amazing** [comment]
@kyazdani42 I didn't find multi rename at once feature like in fern.
Could I request it in this issue or should I create a new one?

**Comment by alex-courtis** [comment]
> @kyazdani42 I didn't find multi rename at once feature like in fern. Could I request it in this issue or should I create a new one?

Multi rename is a possibility. There are many ways it could be achieved.

Please open a feature request specifying:
* capabilities of the feature
* stories for each capability, specifying mappings and prompts
* examples for a variety of cases
