### ISSUE TITLE
vim.defer_fn doesn't work with lazyload of plugin mangement

### ISSUE THREAD

**Issue by glepnir** [kyazdani42/nvim-tree.lua#125]
`vim.defer_fn(M.on_enter, 1)` this will not load `M.on_enter` when use dein lazyload.

**Comment by kyazdani42** [comment]
lazy loading and loading plugins on start shouldn't be used together. You lazy load plugins when you need to activate plugins on demand, not at start.
Anyway, it will be possible to use lazy loading with on start once i'm done with the rewrite.
