### ISSUE TITLE
Trailing whitespaces of file and folder names

### ISSUE THREAD

**Issue by arturonavax** [kyazdani42/nvim-tree.lua#1253]
### Description

I use LunarVim, and I have a linter activated that warns me of lines with trailing whitespaces.

According to this, it seems that now **NvimTree.lua** is putting trailing whitespaces at the end of everything, to solve this I started to search through the last commits of **NvimTree.lua** until I got to the one where this was not happening to fix it temporarily... the commit is `ec888d08ce80bc3ee6efde6405f9bb564f897add`

Temporarily deactivate the flashlight to check more manually this...
```sh
:match ExtraWhitespace /\s\+$/
:highlight ExtraWhitespace guibg=red
```

And indeed, there seem to be blank spaces at the end of lines

![Screenshot from 2022-05-09 22-53-06](https://user-images.githubusercontent.com/7986426/167539432-b822b880-030d-4258-8707-83620008af76.png)

### Neovim version

```text
NVIM v0.7.0
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

Linux Ubuntu 20.04.4 LTS

### nvim-tree version

47732b6

### Minimal config

```lua
Occurs with LunarVim vanilla
```

### Steps to reproduce

Occurs with LunarVim vanilla

**Comment by alex-courtis** [comment]
@arturonavax Please test branch fix branch at #1259

**Comment by arturonavax** [comment]
It seems to keep happening, there is still a trail spaces at the end of each filename

(I am in commit `7293f8dc709f9f207e3d71338599649dc3d76996`)

![Screenshot from 2022-05-14 09-19-19](https://user-images.githubusercontent.com/7986426/168429706-ee981415-ec44-4fdf-9ba7-9c4a8c35982e.png)

**Comment by alex-courtis** [comment]
> It seems to keep happening, there is still a trail spaces at the end of each filename

Yes, except in the case of "after" for git dirty.
