### ISSUE TITLE
git_placement attribute set the failure

### ISSUE THREAD

**Issue by linqingyao** [kyazdani42/nvim-tree.lua#1255]
### Description

git_placement attribute set the failure

### Neovim version

```text
NVIM v0.7.0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compiled by runneradmin@fv-az320-113
```

### Operating system and version

Windows11

### nvim-tree version

543c07a

### Minimal config

```lua
-- plugin.lua
vim.cmd [[packadd packer.nvim]]

return require('packer').startup(function() 
	use "wbthomason/packer.nvim" -- Have packer manage itself
	use 'kyazdani42/nvim-web-devicons'
	use {
   		'kyazdani42/nvim-tree.lua',
   		tag = 'nightly'
	}
end)

_________________________________________________________________________


-- nvim-tree.lua
require("plugin")

require("nvim-tree").setup {
  renderer = {
    icons = {
      git_placement = "after", -- before/after
    }
  },
}
```

### Steps to reproduce

 nvim -nu .\nvim-tree.lua

[NvimTree] unknown option: renderer.icons.git_placement

### Expected behavior

The Git icon appears after the file name

### Actual behavior

![QQ截图20220512205245](https://user-images.githubusercontent.com/83944508/168079038-0377a9e8-b1c0-4336-9e08-214ea8987e6d.png)

**Comment by jiashun0011** [comment]
I have the same issue and I cannot find any references what this error msg means.

**Comment by alex-courtis** [comment]
The `renderer.icons.git_placement` functionality is not present at the `nightly` tag.

Please:
* use the latest (`master`) release of the plugin to gain this functionality
* wait until the feature reaches the `nightly` tag

**Comment by linqingyao** [comment]
I see. Thank you very much for your answer. Nvim-tree is a very useful extension

**Comment by kyazdani42** [comment]
This is now available in nightly :)
