### ISSUE TITLE
How to force nvim-tree to recognize filetype and draw correct icon?

### ISSUE THREAD

**Issue by Liverm0r** [kyazdani42/nvim-tree.lua#1257]
### Description

Seems like nvim-tree can't recognize a filetype and draw default icon:
<img width="216" alt="image" src="https://user-images.githubusercontent.com/14236531/168178259-959d90d1-5b83-483a-9a81-5a72ce7e8400.png">

Didn't have this problem with the NERDTree.

### Neovim version

```text
0.7.0
```

### Operating system and version

macOS 12.3.1

### nvim-tree version

82ec79a

### Minimal config

```lua
default config + autocmd to recognize `*.cljd` files as `clojure`:

local function set_cljd(args)
  vim.api.nvim_command("setfiletype clojure")
end
vim.api.nvim_create_autocmd("BufRead,BufNewFile", {pattern = "*.cljd", callback = set_cljd})
```

### Steps to reproduce

1. set up autocmd to recognize `*.cljd` files as `clojure` and open `any.cljd` file.

### Expected behavior

`Clojure` icon show.

### Actual behavior

`Default` icon shown.

**Comment by alex-courtis** [comment]
nvim-tree uses [nvim-web-devicons](https://github.com/kyazdani42/nvim-web-devicons) to draw the icon based on the file's extension. `&filetype` is not used.

It [currently recognises](https://github.com/kyazdani42/nvim-web-devicons/blob/bdd43421437f2ef037e0dafeaaaa62b31d35ef2f/lua/nvim-web-devicons.lua#L276) `clj` `cljc` `cljs` but not `cljd`.

Please raise a feature request at [nvim-web-devicons](https://github.com/kyazdani42/nvim-web-devicons)

**Comment by kyazdani42** [comment]
closing since this is unrelated, please open a PR at nvim-web-devicons :)

**Comment by Liverm0r** [comment]
thank you, pr https://github.com/kyazdani42/nvim-web-devicons/pull/129
