### ISSUE TITLE
Auto refresh git status when git push?

### ISSUE THREAD

**Issue by glepnir** [kyazdani42/nvim-tree.lua#126]
I found that git status not refresh when I git push. I think can provide a autocmd like `LuaGitStatusChange`? then bind 

`LuaTreeRefresh` with it. What do you think?

**Comment by kyazdani42** [comment]
I might add a watcher in the rewrite, or soon after :)

**Comment by glepnir** [comment]
create a coroutine to watch git change?   If keep using git command to get the status in coroutine, will there be no problem?

**Comment by kyazdani42** [comment]
creating a setinterval non blocking check in the bg with libuv maybe.

**Comment by kyazdani42** [comment]
not with git command but with modified stats of files and folders from root dir.

**Comment by glepnir** [comment]
Sounds good .Thanks for work.
