### ISSUE TITLE
Jump to previous/next diagnostic keymap

### ISSUE THREAD

**Issue by askfiy** [kyazdani42/nvim-tree.lua#1266]
Is there a button to quickly jump to the previous or next diagnosis?

Just like git, we can jump quickly with `[c` or `]c`.

It would be great if diagnostics could be done too, like `[g` or `]g` for quick jumps.

Is it possible to add this?

**Comment by kyazdani42** [comment]
There is not yet, but that would be a great addition :)

**Comment by askfiy** [comment]
Okay, looking forward to it coming out.

**Comment by alex-courtis** [comment]
Already raised: https://github.com/kyazdani42/nvim-tree.lua/issues/1245

Closing this one.
