### ISSUE TITLE
Too big white arrows

### ISSUE THREAD

**Issue by xbladesub** [kyazdani42/nvim-tree.lua#1268]
How can I reduce the size of white arrows on left? And may be change color also? Tried everything - no success
![Screen Shot 2022-05-14 at 19 19 51](https://user-images.githubusercontent.com/45129790/168423661-0f2f630b-b78f-4a07-820a-cab590b595ec.png)

NVIM v0.7.0
Build type: Release
LuaJIT 2.1.0-beta3

**Comment by kyazdani42** [comment]
highlight -> `NvimTreeIndentMarker`
arrows -> `nvim_tree_icons.folder.arrow_open|arrow_closed`
You can check arrow icons in https://www.nerdfonts.com/cheat-sheet
