### ISSUE TITLE
folder name  word color error

### ISSUE THREAD

**Issue by xaotag** [kyazdani42/nvim-tree.lua#1269]
### Description

![image](https://user-images.githubusercontent.com/40427877/168428182-2924b22f-24c6-459f-9649-baf48c39b092.png)
![image](https://user-images.githubusercontent.com/40427877/168428265-47c1b665-0c26-407f-b009-8e2c1e983ac7.png)

### Neovim version

```text
NVIM v0.8.0-dev+203-g9e4286294f
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

### Operating system and version

arch 5.17.6-arch1-1

### nvim-tree version

90d7b8e

### Minimal config

```lua
require'nvim-tree'.setup { -- BEGIN_DEFAULT_OPTS
} -- END_DEFAULT_OPTS
vim.cmd([[
 let g:nvim_tree_icons = {
    \ 'default': "",
    \ 'symlink': "",
    \ 'git': {
    \   'unstaged': "✗",
    \   'staged': "✓",
    \   'unmerged': "",
    \   'renamed': "➜",
    \   'untracked': "",
    \   'deleted': "",
    \   'ignored': "◌"
    \   },
    \ 'folder': {
    \   'arrow_open': "",
    \   'arrow_closed': "",
    \   'default': "",
    \   'open': "",
    \   'empty': "",
    \   'empty_open': "",
    \   'symlink': "",
    \   'symlink_open': "",
    \   }
    \ }
 ]])
```

### Steps to reproduce

/

**Comment by alex-courtis** [comment]
This is a recently introduced bug, which has been reverted #1259

Please update to the latest version of nvim-tree.lua or the `nightly` tag.
