### ISSUE TITLE
Can I disable git but use I key for toggle ignore files?

### ISSUE THREAD

**Issue by nshen** [kyazdani42/nvim-tree.lua#1274]
I can't enable git, because it is too slow, and I don't want to see the icons

but I do want to use I key for toggle gitignore files, is that possible ? 

It doesn't work, when I set as below
```
  git = {
    enable = false,
    ignore = true,
  },
```

**Comment by alex-courtis** [comment]
No. git is used to determine which files are ignored.

It may be possible to add such functionality:
* read `.gitignore` and `.git/info/exclude`
* parse these patterns
* apply these patterns when `git.enable = false` and `git.ignore = true`

See [gitignore](https://git-scm.com/docs/gitignore) doc and an implementation by [the_silver_searcher](https://github.com/ggreer/the_silver_searcher/blob/master/src/ignore.c).

Marking this feature request as "PR Please".

**Comment by kyazdani42** [comment]
We once tried this but decided to remove it in favor of using git itself for gitignored files.
Also i'd like to avoid writing and maintaining a parser for gitignore files.

**Comment by alex-courtis** [comment]
An workaround for you @nshen :

Add `filters.custom` with a vim regex that matches your `.gitignore` patterns.

Closing request.

**Comment by paulodiovani** [comment]
> A workaround for you @nshen :
> 
> Add `filters.custom` with a vim regex that matches your `.gitignore` patterns.
> 
> Closing request.

Sorry, but this is no solution.
Would be nice to parse ignore files, instead. That way we could use `.gitignore` or `.dockerignore`, for example.

**Comment by alex-courtis** [comment]
> Sorry, but this is no solution. Would be nice to parse ignore files, instead. That way we could use `.gitignore` or `.dockerignore`, for example.

That would be great, unfortunately that is a non-trivial amount of work.

See #2367
