### ISSUE TITLE
Create directory

### ISSUE THREAD

**Issue by jw3126** [kyazdani42/nvim-tree.lua#1277]
First of all, thanks a lot for creating nvim-tree, it is awesome! 
You can press the 'a' key to create a new file. Is there a similar way to create a new directory?

**Comment by jw3126** [comment]
Ok I found out you can create a directory by passing a name that ends with '/' to create file.

**Comment by jw3126** [comment]
This is even documented, sorry for the noise!

**Comment by alex-courtis** [comment]
Today I learned.
