### ISSUE TITLE
There is no command to make a copy of a file

### ISSUE THREAD

**Issue by albertas** [kyazdani42/nvim-tree.lua#1284]
**Is your feature request related to a problem? Please describe.**
Sometimes I want to make a copy of an existing file and then change the content of the copied file. I cannot find a shortcut for such an action in the README. I see only `r` to rename a file and `a` to add a new one.

**Describe the solution you'd like**
A new shortcut, e.g. `C` to make a copy of a file (in the file system) which is under the cursor. This command should work just like `r`, but should keep the original file untouched.

**Describe alternatives you've considered**
Now I have to create a new file, and copy the content of previous file manually, which requires additional clicks and time.

**Comment by alex-courtis** [comment]
From README:
* type `c` to add/remove file/directory to copy clipboard
* type `p` to paste from clipboard. Cut clipboard has precedence over copy (will prompt for confirmation)

Please read carefully before opening an issue.
