### ISSUE TITLE
expand_all to expand all folders to make live_filter more awesome

### ISSUE THREAD

**Issue by dbarrosop** [kyazdani42/nvim-tree.lua#1289]
**Is your feature request related to a problem? Please describe.**

The new feature "live filter" is pretty awesome but it is not very usable due to two reasons:

1. It only searches expanded folders (I actually think this is desirable). 
2. There is no shortcut for expanding all folders

**Describe the solution you'd like**

I think it'd make sense to add a shortcut to expand all folders. There is already one to colapse_all but not to do the opposite.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by alex-courtis** [comment]
Known limitation. It needs a recursive filesystem search: https://github.com/kyazdani42/nvim-tree.lua/pull/1056#issuecomment-1126889142

Changed to feature request.

**Comment by dbarrosop** [comment]
You mean the `expand_all` or the ability to search everywhere? Just to be clear, I think the current behavior makes sense (only search in expanded folders). I don't expect to be using this plugin to actually search in my entire worktree, for that I think telescope+fzf makes more sense, I expect to be using this though to narrow down the list of files I want to see in a set of folders while working on a feature or bug (kinda like a "focus" mode).

What I am arguing for in this issue is to have a shortcut to expand all folders. Right now this plugin has `W : collapse_all` so having the opposite could help with this. This way if someone wants to filter in the entire tree they can expand_all first and then trigger `live_filter`.

**Comment by kyazdani42** [comment]
expand_all has been asked already, i'm going to implement it soon i think, it's not too hard. Although this could be very slow if you run the command on the home folder or the / folder :)
