### ISSUE TITLE
msys2 git support

### ISSUE THREAD

**Issue by bstaint** [kyazdani42/nvim-tree.lua#1290]
**Is your feature request related to a problem? Please describe.**
msys2 git support

**Describe the solution you'd like**
msys git path like `/e/Downloads/testc`(E:\Downloads\testc)

**Describe alternatives you've considered**

**Additional context**
patch:
```diff
diff --git a/lua/nvim-tree/git/utils.lua b/lua/nvim-tree/git/utils.lua
index 21f2c7f..cb28f8d 100644
--- a/lua/nvim-tree/git/utils.lua
+++ b/lua/nvim-tree/git/utils.lua
@@ -10,6 +10,10 @@ function M.get_toplevel(cwd)
 
   -- git always returns path with forward slashes
   if vim.fn.has "win32" == 1 then
+    -- msys2
+    if vim.fn.executable('cygpath') then
+        toplevel = vim.fn.system("cygpath -w " .. vim.fn.shellescape(toplevel))
+    end
     toplevel = toplevel:gsub("/", "\\")
   end
```

**Comment by alex-courtis** [comment]
I have no way to verify this; I don't know what msys2 is and I don't have a windows environment to validate with.

@kyazdani42 I'm happy to just accept this, as it is an unreachable code path for most cases.

**Comment by kyazdani42** [comment]
Something like this would be good yes, but just doing the cygpath check globally instead of each time running the `get_toplevel` function. I have no idea what msys2 is and i don't have a windows environment either.
@bstaint please just make a PR if you need this :)
