### ISSUE TITLE
[Feature request] Display node whose name length is wider than the width of nvim-tree window in floating window.

### ISSUE THREAD

**Issue by lu5je0** [kyazdani42/nvim-tree.lua#1297]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Display node whose name length is wider than the width of nvim-tree window in floating window just like IntelliJ IEAD.
![2](https://user-images.githubusercontent.com/17700877/170813946-b0289158-d47b-44fb-89b3-f16809ae988f.gif)

**Additional context**
I can submit a PR if you guys find it useful.

**Comment by kyazdani42** [comment]
go for it, looks like a good feature to me :)

**Comment by alex-courtis** [comment]
I like that. Users could use this or #1293 to show the file names.
