### ISSUE TITLE
renderer git icon no work

### ISSUE THREAD

**Issue by xaotag** [kyazdani42/nvim-tree.lua#1299]
### Description

![image](https://user-images.githubusercontent.com/40427877/170823220-087f4fe6-2436-4809-a77d-b6c8ef730473.png)

### Neovim version

```text
NVIM v0.8.0-dev+317-ge2940d3c79
```

### Operating system and version

arch 

### nvim-tree version

c3b7be8

### Minimal config

```lua
require'nvim-tree'.setup { -- BEGIN_DEFAULT_OPTS
  renderer = {icons = {glyphs = {git = {untracked = ""}}}}
} -- END_DEFAULT_OPTS
```

### Steps to reproduce

/

**Comment by xaotag** [comment]
old api 
![image](https://user-images.githubusercontent.com/40427877/170823347-809f0ce2-f178-4abd-88cc-27c4d9da3120.png)

**Comment by alex-courtis** [comment]
Nice dwm setup ;)

Unfortunately I cannot reproduce this at c3b7be8
Tried an [nvt-min.lua.gz](https://github.com/kyazdani42/nvim-tree.lua/files/8792470/nvt-min.lua.gz) with the your minimal setup shows the correct icon.

Can you please try that one?

**Comment by xaotag** [comment]
![image](https://user-images.githubusercontent.com/40427877/170848956-777944ee-20c9-4cf8-bbba-7980f212a681.png)

**Comment by kyazdani42** [comment]
Yes nvim-web-devicons sometimes conflicts between plugins. I think i should rethink the way it's starting up.
