### ISSUE TITLE
Popping a warn info every time I open it

### ISSUE THREAD

**Issue by OliverChao** [kyazdani42/nvim-tree.lua#1303]
I know a lot of global variables are moved into setup options in https://github.com/kyazdani42/nvim-tree.lua/issues/674. But  I use the default configuration, it also pop a warn msg.
This problem occurs after I updated nvim-tree. 
It works fine before. Who knows how to stop it? It is annoying.

https://user-images.githubusercontent.com/39361033/170858572-5f4382eb-dedf-4258-83c3-45635f3f3d57.mp4

**Comment by gegoune** [comment]
You ignored bug report form so it's impossible to know what even a problem here is, but my guess is that even though you are not changing anything in setup call you still have some global variables hanging around. Check your config for string reported in notification you are getting.

**Comment by OliverChao** [comment]
> 

OH, thanks for your reply. 
Yep, I mess my variables up, and I ignored some in other files.
Thanks! @gegoune
