### ISSUE TITLE
Error on startup after commit 2002b21be705187c59f10015f0eb2d85a4ea6312

### ISSUE THREAD

**Issue by Abh15h3k** [kyazdani42/nvim-tree.lua#1311]
### Description

Error on startup

<img width="902" alt="image" src="https://user-images.githubusercontent.com/40197742/171475390-15db73fe-84ad-4b70-9157-22468ace63a4.png">

when setting `view.side = "bottom"`
`get_size()` in `view.lua` attempts to get the height of the `View`. but the height is initialised later. 

<img width="609" alt="image" src="https://user-images.githubusercontent.com/40197742/171476315-6217e24c-9836-49de-afb2-5ac0761b831f.png">

### Neovim version

```text
NVIM v0.8.0-dev+1792-ge86901eb6
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

M1 macOS

### nvim-tree version

master

### Minimal config

```lua
exact config as in github README.

except `view.side = "bottom"`
```

### Steps to reproduce

nvim

**Comment by alex-courtis** [comment]
> exact config as in github README.

That is clearly not the case. It looks like you are directly modifying the internal state of nvim-tree.

Please pass your configuration via the setup function as documented.

If you are still experiencing issues, please produce an `nvt-min.lua` as instructed in the [bug report form](https://github.com/kyazdani42/nvim-tree.lua/issues/new?assignees=&labels=bug&template=bug_report.yml).

**Comment by alex-courtis** [comment]
`nvim-tree.view.side` bottom and top are not currently functional. Please use `left` or `right`.

* clarify doc
* validate `nvim-tree.view.side` value
