### ISSUE TITLE
Readme.md bug: not able to see glyphs on MacOS Monterey, iPhone 15.4.1, or Windows 10

### ISSUE THREAD

**Issue by vtrinh2** [kyazdani42/nvim-tree.lua#1314]
### Description

In the Setup chapter of Readme.md, the various glyphs render as whitespace (MacOS Monterey with Safari, iPhone 15.4 with Safari) or as ? (question mark inside a square) on Windows 10 with Edge v101

### Neovim version

```text
N/A
```

### Operating system and version

MacOS Monterey, iPhone, and Windows

### nvim-tree version

N/A

### Minimal config

```lua
N/A
```

### Steps to reproduce

Using Safari on MacOS or iPhone, or Edge on Windows, open the readme.md.  Scroll down or search for "glyphs".  The various icons will not display correctly.  They will show as whitespace or ?.

### Expected behavior

I'm not sure, the icons should be like in the screenshots I guess?

**Comment by vtrinh2** [comment]
![image](https://user-images.githubusercontent.com/104380221/171565198-07397384-4d00-4be9-a219-a206f872b919.png)

Screenshot above is from Safari on MacOS.

**Comment by alex-courtis** [comment]
A [patched font](https://github.com/kyazdani42/nvim-web-devicons) is required to render these icons, which will display correctly in your terminal. The icons will not render in the browser using its default fonts.

Experimentation has revealed that it is possible to use the patched font in a browser. Google chrome on linux:
![20220604_125044 727x241](https://user-images.githubusercontent.com/1505378/171976304-04e01f0a-8efb-4ecc-b48c-86fc356a77d5.png)
![20220604_125118 328x732](https://user-images.githubusercontent.com/1505378/171976433-82339d64-165e-401c-8b1a-22a4618d31c5.png)
