### ISSUE TITLE
Folder Arrows are not being rendered

### ISSUE THREAD

**Issue by asciialex** [kyazdani42/nvim-tree.lua#1316]
### Description

I have recently switched from using VSCode as my main editor to Neovim, I have installed this package and the package seems to be functioning fine, except for the arrows not appearing next to the folders, and I'm not sure what to do next in order to diagnose the problem, I have tried the following:

- Tried multiple fonts (including multiple `nerd-fonts`), my default is Input
- Tried specifying an ascii character in `glyphs = { folder = { arrow_closed = "X", arrow_open = "Y",` setting
- Tried to log diagnostics, but nothing is logged
- uninstall and re-install
- Tried different terminal applications, my default is Iterm2

### Neovim version

```text
NVIM v0.7.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Monterey

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.7.0/share/nvim"

Run :checkhealth for more info
```

### Operating system and version

MacOS 12.4

### nvim-tree version

a0f7059

### Minimal config

```lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvt-min/site]]
local package_root = "/tmp/nvt-min/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup {
    {
      "wbthomason/packer.nvim",
      "kyazdani42/nvim-tree.lua",
      "kyazdani42/nvim-web-devicons",
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  }
end
if vim.fn.isdirectory(install_path) == 0 then
  print "Installing nvim-tree and dependencies."
  vim.fn.system { "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path }
end
load_plugins()
require("packer").sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua setup()]]
vim.opt.termguicolors = true
vim.opt.cursorline = true

-- MODIFY NVIM-TREE SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
_G.setup = function()
  require("nvim-tree").setup {
      renderer = {
          icons = {
              show = {
                  file = false,
                  folder = false,
                  folder_arrow = true,
                  git = false
              }
          }
      }
  }
end
```

### Steps to reproduce

1. `nvim -nu nvt-min.lua`
2. `:NvimTreeToggle`

### Expected behavior

To be able to see folder arrows

### Actual behavior

I can't see folder arrows

**Comment by alex-courtis** [comment]
Folder arrows require `renderer.icons.show.folder=true` and `renderer.indent_markers.enable=false`

See `:help nvim-tree.renderer.icons.show`

**Comment by asciialex** [comment]
I see, I reconfigured and it works as described, apologies I didn't see that. Is there a specific reason as for why they are mutually exclusive?

**Comment by alex-courtis** [comment]
> I see, I reconfigured and it works as described, apologies I didn't see that. Is there a specific reason as for why they are mutually exclusive?

No apologies needed.

There is no specific reason for the exclusivity; the functionality just does not exist.

A PR to add this functionality would be gratefully appreciated.

**Comment by kyazdani42** [comment]
Indeed, i also don't think it's too hard to implement, you could open a feature request also since this hasn't yet been asked i believe.
