### ISSUE TITLE
[coc.nvim] Error on request (diagnosticList)

### ISSUE THREAD

**Issue by JohnTheCoolingFan** [kyazdani42/nvim-tree.lua#1317]
### Description

```
Error on request (diagnosticList): Vim(return):Error invoking 'diagnosticList' on channel 3 (coc):                                                                                                   
ch 3 returned a response with an unknown request id. Ensure the client is properly synchronized
```
After that, coc.nvim loses connection to language server

### Neovim version

```text
NVIM v0.7.0
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

Arch Linux 5.17.9-zen1-1-zen

### nvim-tree version

25921aa

### Minimal config

```lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvt-min/site]]
local package_root = "/tmp/nvt-min/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup {
    {
      "wbthomason/packer.nvim",
      "kyazdani42/nvim-tree.lua",
      "kyazdani42/nvim-web-devicons",
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
      {"neoclide/coc.nvim", branch = "release"}
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  }
end
if vim.fn.isdirectory(install_path) == 0 then
  print "Installing nvim-tree and dependencies."
  vim.fn.system { "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path }
end
load_plugins()
require("packer").sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua setup()]]
vim.opt.termguicolors = true
vim.opt.cursorline = true

-- MODIFY NVIM-TREE SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
_G.setup = function()
  require("nvim-tree").setup {
    diagnostics = {enable=true, show_on_dirs=true}
  }
end
```

### Steps to reproduce

1. :NvimTreeOpen
2. :CocInstall rust-analyzer to replicate how I do it
3. Open a file that contains coc.nvim diagnostics. For example, `src/prototypes/mod.rs` in https://github.com/JohnTheCoolingFan/factorio-lib-rs
4. Wait for error to occur

**Comment by alex-courtis** [comment]
Installed Arch packages:
```
rust 1:1.61.0-1
rust-src 1:1.61.0-1
```

**Comment by alex-courtis** [comment]
Replicated.

Notable:
* The coc update / scan is incredibly slow ~30sec
* `CocDiagnosticChange` is sent 5-7 times
* First few updates sometimes succeed, depending on timing

**Comment by alex-courtis** [comment]
Prevent concurrent CocAction:
```diff
diff --git a/lua/nvim-tree/diagnostics.lua b/lua/nvim-tree/diagnostics.lua
index 685a1c8..47529d0 100644
--- a/lua/nvim-tree/diagnostics.lua
+++ b/lua/nvim-tree/diagnostics.lua
@@ -68,13 +68,23 @@ local function from_nvim_lsp()
   return buffer_severity
 end

+local coc_running = false
 local function from_coc()
   if vim.g.coc_service_initialized ~= 1 then
     return {}
   end

+  if coc_running then
+    log.line("diagnostics", "from_coc doing nothing, run in progress")
+    return {}
+  end
+
+  coc_running = true
+  log.line("diagnostics", "from_coc running")
   local diagnostic_list = vim.fn.CocAction "diagnosticList"
   if type(diagnostic_list) ~= "table" or vim.tbl_isempty(diagnostic_list) then
+    log.line("diagnostics", "from_coc complete, no results")
+    coc_running = false
     return {}
   end

@@ -97,6 +107,8 @@ local function from_coc()
     end
   end

+  coc_running = false
+  log.line("diagnostics", "from_coc complete, showing results")
   return buffer_severity
 end
```

"from_coc running" : 9
"from_coc doing nothing" : 34
"from_coc complete" : 9

**Comment by alex-courtis** [comment]
@JohnTheCoolingFan please try the above patch to see how it works in a real world scenario.

I'm not sure that this is the best approach; we will lose some diagnostics for the events that have been throttled.

What do you think @kyazdani42 ?

**Comment by alex-courtis** [comment]
@JohnTheCoolingFan this doesn't directly address your issue, however I recommend that you try native neovim LSP. I moved from coc and it is a much smoother experience, which offers some nice features that coc doesn't offer.

Official neovim plugin: https://github.com/neovim/nvim-lspconfig
Officially recommended completion and utility plugins: https://github.com/hrsh7th/nvim-cmp/  https://github.com/hrsh7th/vim-vsnip

**Comment by JohnTheCoolingFan** [comment]
@alex-courtis the patch fixed the issue.

Thanks for your suggestion, I'll think about moving to lspconfig. I like the UX of coc because you can just install the lsp extension and it works right away.

**Comment by kyazdani42** [comment]
I think we could potentially apply this patch, although i think this issue should be upstreamed to coc.nvim, sounds strange to me that so many events occur.

**Comment by alex-courtis** [comment]
I'd like to improve it a bit first, so that we don't miss any trailing events. The same pattern can also be applied to lsp diagnostics and even git.

**Comment by alex-courtis** [comment]
#1320 is a work in progress.

**Comment by alex-courtis** [comment]
Looking at this one now: debouncing and preventing concurrent executions of diagnostic updates.

Issue: inconsistent bug in debouncer in which a closed timer will still complete, throwing a nil at utils 347. Appears to be exacerbated by the pcall to close. Having the release / execute in a `vim.schedule_wrap` probably doesn't help. We can move it around.

Experimentation with `timer_again` instead of destroying the old timer has been positive, however the timer is firing too early. It may be safer and more reliable to explicitly hold / release references.

**Comment by alex-courtis** [comment]
Making some progress. Debouncer is now thread safe and reschedules concurrent jobs, working for git.

Outstanding: preventing execution of cancelled jobs whose timer has expired.

**Comment by nothingIsSomething** [comment]
> @JohnTheCoolingFan this doesn't directly address your issue, however I recommend that you try native neovim LSP. I moved from coc and it is a much smoother experience, which offers some nice features that coc doesn't offer.
> 
> Official neovim plugin: https://github.com/neovim/nvim-lspconfig Officially recommended completion and utility plugins: https://github.com/hrsh7th/nvim-cmp/ https://github.com/hrsh7th/vim-vsnip

Do you know of a way to use rust semantic highlighting without coc?

the semantic highlighting of coc for rust works for me without nvim-tree, I don't know what conflict there is between coc and nvim-tree because only when I disable nvim-tree everything works fine.
