### ISSUE TITLE
nvim-tree has problem with directories using decomposed UTF-8 (UTF-8-MAC)

### ISSUE THREAD

**Issue by ronisbr** [kyazdani42/nvim-tree.lua#1318]
### Description

When trying to create a file inside a directory in which the path has accented characters using decomposed UTF-8 (UTF-8-MAC), nvim-tree create a file in another path in which all the accents are removed.

For example, if we are in `/tmp/seção` and try to create a file, nvim-tree creates in `/tmp/secao`.

The problem here is that every time in macOS you create a directory using Finder with accents, they will use this decomposed UTF-8. Hence, this issue leads to lot of problems.

### Neovim version

```text
NVIM v0.7.0
Build type: Release
LuaJIT 2.1.0-beta3
Compilado por brew@Monterey

Features: +acl +iconv +tui
See ":help feature-compile"

    arquivo vimrc de sistema: "$VIM/sysinit.vim"
            padrão para $VIM: "/usr/local/Cellar/neovim/0.7.0/share/nvim"

Run :checkhealth for more info
```

### Operating system and version

macOS 12.4

### nvim-tree version

25921aa

### Minimal config

```lua
The bug happens with the default nat-min.lua.
```

### Steps to reproduce

Execute:

```
cd /tmp
mkdir tmp
mv tmp `echo seção | iconv -f UTF-8 -t UTF-8-MAC`
cd seção
```

Open neovim and nvim-tree.
Type `a` to create a new file.

### Expected behavior

The input line should be:

```
Create file /tmp/seção/
```

in which a new file will be created in the current directory.

### Actual behavior

The input line is:

```
Create file /tmp/secao/
```

in which a new file will be created in the wrong directory.

**Comment by alex-courtis** [comment]
Working on linux:

`Create file /tmp/1318/seção/`

This might be tricky.

**Comment by alex-courtis** [comment]
I don't have an environment (mac) on which I can test this.

@ronisbr could you attempt to fix this yourself?

In the meantime I'll take a look and see if anything obvious becomes apparent.

**Comment by alex-courtis** [comment]
Are there any other nvim-tree situations in which such problems occur? Is it only for create-file?

**Comment by ronisbr** [comment]
Hi @alex-courtis !

Thanks for the quick response.

> Unfortunately that proves nothing as I cannot perform the iconv.

Yes, without iconv it will use composed UTF-8, which works fine.

> @ronisbr could you attempt to fix this yourself?

I have almost no knowledge in Lua, but I will try to at least debug the problem!

> Are there any other nvim-tree situations in which such problems occur? Is it only for create-file?

I have only seen this problem when creating a file. For example, nvim-tree can delete files inside this directory successfully.

**Comment by ronisbr** [comment]
I found! The problem is in `vim.ui.input`!

```
:lua vim.ui.input({prompt = "Create", default = "seção"}, function() end)
secao
```

**Comment by kyazdani42** [comment]
works well on linux. Could you upstream this to neovim then ? 
Also check https://stackoverflow.com/questions/4606570/os-x-terminal-utf-8-issues if this could solve your issue.
Closing then since unrelated to nvim-tree itself :)

**Comment by ronisbr** [comment]
Thanks @kyazdani42 

I just opened. The problem is not the terminal. The problem is that all folders with accented characters created in Finder has decompressed UTF-8. Apparently, `vim.ui.input` cannot handle those well.

**Comment by ronisbr** [comment]
However, can you add some workaround here for Mac users like me until it is fixed upstream?

I have a proposal:

Add an option, and, if this option is true, pass to `vim.ui.input` the directory as the option `prompt` instead the option `default`. The problem is that the user will not have the ability to change the directory they want to create a file, but it will partially fix the problem for my use case.

**Comment by ronisbr** [comment]
By the way, I think I can do a PR to add this. We can name the option `lock_directory_on_file_creation` or something.

**Comment by ronisbr** [comment]
They fixed in the speed of light :D Everything is working now in neovim `master`. The patch was also already back ported to 0.7 release.

**Comment by alex-courtis** [comment]
Wow!

**Comment by kyazdani42** [comment]
indeed it was fast :)
