### ISSUE TITLE
[Followup] Missing steps for stable filesystem watchers

### ISSUE THREAD

**Issue by kyazdani42** [kyazdani42/nvim-tree.lua#1320]
## To implement

- [x] implement watcher for symlinked directories
- [x] cleanup watchers whenever directories are removed / renamed
- ~[ ] more `.git` watchers (optional, might not be needed)~
- [x] handle concurrent git jobs
- [x] replace fs_poll with something more efficient and targeted
- [x] abandon git update on invalid path https://github.com/kyazdani42/nvim-tree.lua/pull/1373#discussion_r907919332
- [x] resolve debouncer concurrency issues: https://github.com/kyazdani42/nvim-tree.lua/issues/1317#issuecomment-1173013254

#### Windows

**Comment by alex-courtis** [comment]
See #1317 for similar issue RE concurrest LSP jobs. A generic solution may be used for git, coc and lsp.

**Comment by alex-courtis** [comment]
This repo (with submodules populated) is good for stress testing: https://github.com/qmk/qmk_firmware/

**Comment by kyazdani42** [comment]
@alex-courtis i'm not sure i understand the last comment, did you maybe comment on the wrong issue :) ?

**Comment by alex-courtis** [comment]
I'm using that qmk repo to test git watcher concurrency:  modify a few files in differect directories then git checkout. That takes a long time.

**Comment by kyazdani42** [comment]
I'd like to see how a firmware can be used to do that ! Do you have a sample repository ?

**Comment by gegoune** [comment]
@kyazdani42 I think what @alex-courtis is saying is that qmk repo *is* his test repository. :)

**Comment by kyazdani42** [comment]
:smile: oh now i understand !

**Comment by alex-courtis** [comment]
Drafted some ideas around concurrency: #1343

**Comment by alex-courtis** [comment]
> implement watcher for symlinked directories

This is working now:
* symlinked directories are watched, via a watcher on the target
* works for symlinks inside the tree and outside
* newly created and destroyed links have their watchers created / destroyed

To do:
1. too many watchers new'd for the target directory, resulting in `Watcher:new using existing`
a. link remove destroys the watcher for the target directory

**Comment by alex-courtis** [comment]
> * more `.git` watchers (optional, might not be needed)

I don't think there are any valuable git watchers that will find events that the node watchers will not.

The only real candidate is `.git/info` however that is such a niche case that it is not worth it.

**Comment by kyazdani42** [comment]
i think we can close this after #1453 is merged ?

**Comment by alex-courtis** [comment]
> i think we can close this after #1453 is merged ?

Yes. I think it's also time to remove `filesystem_watchers.enabe` and always use watchers.

After successful rollout we can remove the redundant codepaths.

**Comment by kyazdani42** [comment]
i've enabled the watchers by default, after updating the nightly tag. I hope everything goes well :)
