### ISSUE TITLE
NvimTreeFocus on a file outside cwd does not work

### ISSUE THREAD

**Issue by lixvbnet** [kyazdani42/nvim-tree.lua#1322]
Hi,

First of all, thanks for creating this wonderful plugin!

**My config**
```lua
update_cwd = true,
update_focused_file = {
    enable = true,
    update_cwd = false,
},
```

**Description**
NvimTreeFocus on a file outside cwd does not work.

**Expected behavior**:
Allow NvimTreeFocus to update cwd to locate and focus the file. (Or make its behavior configurable ? 🤔 )

I've read issue #986 and got the following config.

```lua
  update_focused_file = {
    update_cwd  = true
  },
```

This would also solve this issue, but I'd like to avoid setting this. 

Suppose I open nvim in `~/MyProject/`, with the above config, when I **first open a file outside the initial directory** such as `/usr/local/test.out`, and **then open a file inside its subfolder**, say `~/MyProject/folderA/a.txt`, the working directory will be changed to that subfolder, then I would only see files under folderA.

But I wish to have cwd remain to be my initial folder `~/MyProject/` unless I choose to change it by running NvimTreeFocus on a file outside it.  Is this possible at all?

**Screenshot**
![image](https://user-images.githubusercontent.com/75612664/172055289-827d21ba-c9a9-47de-ae1c-5878bdbdbd48.png)

Here I'm unable to locate `encode.go` , which is outside my initial working directory.

**Comment by kyazdani42** [comment]
This should be the case though. If the node is found under the current cwd, it should not update the cwd.
Are you using macos ?

**Comment by lixvbnet** [comment]
> This should be the case though. If the node is found under the current cwd, it should not update the cwd. Are you using macos ?

Yes I use macos.    What I am suggesting is allow NvimTreeFocus **update the cwd** if the node is **not found** in current cwd (or, in other words, outside current cwd).  What do you think ?

**Comment by kyazdani42** [comment]
We could add parameters indeed, the focus function is quite small and could be extended.
Feel free to open a PR.
Sorry i misunderstood your request :)

**Comment by lixvbnet** [comment]
Sure, I’ll take a try!
