### ISSUE TITLE
Allow to define custom commands

### ISSUE THREAD

**Issue by weilbith** [kyazdani42/nvim-tree.lua#133]
Hey,
thanks for this cool plugin! :pray: 

The title already states it: it would be pretty cool if you could allow to define custom commands or overwrite existing ones. For example I would love to add an `open` command or adopt the `edit` one to make the window where to place the buffer selectable. For example the is the [vim-choosewin](https://github.com/t9md/vim-choosewin) a cool addition here (I wrote a plugin for NERDTree [here](https://github.com/weilbith/nerdtree_choosewin-plugin)). 
If this is already possible (only glanced some minutes at the implementation), it would be cool if you could document that. 

Looking forward to any feedback.

**Comment by kyazdani42** [comment]
Hi, thanks for the kind words :)
well, i'm currently rewriting the whole plugin so adding too many addition wouldn't be the best move right know.
Although i believe writing custom commands would not be too difficult actually. If you need to overwrite a lua plugin, you could do something like:
```lua
lua require'some_plugin.module'.some_func = function() ... end
```

**Comment by kyazdani42** [comment]
When the refactoring is done, the tree will propose a small api for users to play with or extend the tree (basically like the node tree, the tree buffer or window, the formatted lines or highlight data... etc, etc)

**Comment by weilbith** [comment]
The overwrite hint is pretty cool. Thanks.

Alright. Then I close this issue and await the changes. What would be the best option to get notified about it? Do you do GitHub releases one could subscribe to?

**Comment by kyazdani42** [comment]
I dont really do github releases because there is no versionning for this plugin. Maybe just check #14 and subscribe to it if you wish to get notified about it :)
