### ISSUE TITLE
NvimTree is not refreshed after paste -> rename and cut -> paste

### ISSUE THREAD

**Issue by steliyan** [kyazdani42/nvim-tree.lua#1331]
### Description

The file is not visible after copy & rename (you can check the video).

https://user-images.githubusercontent.com/1850292/173069618-ffe6e73f-8515-4ab2-966d-37e943a306a9.mov

### Neovim version

```text
NVIM v0.7.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@iMac-Pro
```

### Operating system and version

macOS 11.15.7

### nvim-tree version

1caca6285427ebd2b4f0eb10f4d1ae3956ff09c0

### Minimal config

```lua
require('nvim-tree').setup({
  hijack_netrw = true,
  hijack_cursor = true,
  update_cwd = false,

  renderer = {
    icons = {
      glyphs = {
        default = '',
      },
    },
  },

  view = {
    mappings = {
      list = {
        { key = { '<CR>', 'o', '<2-LeftMouse>' }, action = 'edit_in_place' },
        { key = '<C-e>', action = 'edit' },
      },
    },
  },

  actions = {
    open_file = {
      quit_on_open = true,
    },
    change_dir = {
      enable = false,
      global = false,
    },
  },

  update_focused_file = {
    enable = false,
    update_cwd = false,
    ignore_list = {},
  },

  git = {
    enable = true,
    ignore = false,
    timeout = 500,
  },
})
```

### Steps to reproduce

1. Open nepvim in a dir with at least 1 file
1. Open NvimTree - `:lua require('nvim-tree').open_replacing_current_buffer()`
2. Copy a file
3. Paste the file in the same dir
4. Click `(r)ename`
5. Specify a new name - e.g. append a `2`

Expected:

### Expected behavior

The newly renamed file is visible.

### Actual behavior

The newly copied file is not visible but is after refreshing (with `R`).

**Comment by steliyan** [comment]
It look related to this: #1329

**Comment by alex-courtis** [comment]
This is replicable.

**Comment by kyazdani42** [comment]
note that everything is fine with the watchers.
i'll fix that today.
