### ISSUE TITLE
unknown options warning on startup

### ISSUE THREAD

**Issue by farukara** [kyazdani42/nvim-tree.lua#1334]
### Description

I got following warning during launch of the neovim:

```
[NvimTree] unknown option: view.centralize_selection | unknown 
option: filesystem_watchers | unknown option: renderer.full_nam
e | unknown option: renderer.indent_markers.icons.item | unknow
n option: log.types.watcher
```

options were more than that but after uninstall/install cycle only these were left. 
Any idea why thats happening?

### Neovim version

```text
neovim 0.7.0
```

### Operating system and version

macos monterey 12.3.1

### nvim-tree version

latest

### Minimal config

```lua
default config from readme file with no change
```

### Steps to reproduce

happens on startup. No negative effect obseved

**Comment by alex-courtis** [comment]
It looks like you might be using the `nightly` tag. A large overhaul of options has happened since then.

Please use the default options from :help OR use the latest version.

#1327 is currently underway which cleans up the README, which will prevent future issues like this.

**Comment by farukara** [comment]
Thanks yeah that solved it. One more question, I got that :
`nvim-tree.lua setup called multiple times`
config file only has one setup call. Where would be the other one? Could not find it.

**Comment by alex-courtis** [comment]
> config file only has one setup call

Does packer config call setup? Are you reloading your vim config?

An option to suppress that warning is incoming, however it is best to fix this problem at the root.

**Comment by alex-courtis** [comment]
> How about maintaining a blacklist other than whitelist. Here is my configuration, and `initialize` will be the so-called **unknown option**.

I see what you mean with your example, however I'm not quite sure what you are proposing with the blacklist.

How do we generate this blacklist? We're trying to detect situations like `diagnostic.enable` instead of `diagnostics.enable`.

**Comment by weeebdev** [comment]
Same here.
<img width="892" alt="image" src="https://user-images.githubusercontent.com/48881444/179413368-499f215b-e70f-444a-b9fa-5a5bb9d3f2e0.png">
I am a newbie in nvim. What do I do?

**Comment by kyazdani42** [comment]
auto resize needs to be moved to `actions.open_file.resize_window` and follow_update_path needs to be moved to `update_focused_file`

**Comment by kyazdani42** [comment]
see `:help nvim-tree.OPTION_NAME`

**Comment by alex-courtis** [comment]
Added :help hint:
`[NvimTree] unknown option: live_filter.always_show_folder | unknown option: trash.require_confir | see :help nvim-tree-setup for available configuration options`

**Comment by alex-courtis** [comment]
Closing as there is nothing further to do here; blacklist is not possible.
