### ISSUE TITLE
idempotent setup capable of multiple invocations

### ISSUE THREAD

**Issue by alex-courtis** [kyazdani42/nvim-tree.lua#1338]
**Is your feature request related to a problem? Please describe.**
setup may only be called once, with a suppressable warning raised on subsequent calls, which are a NOP.

- Users do not like this warning #1333
- User may not invoke setup again with a different configuration
- Valid use cases such as hot-reloading the vim config exist

**Describe the solution you'd like**
setup may be called multiple times, with all new options being applied.

**Describe alternatives you've considered**
Continue warning the user with subsequent setup calls being a NOP

**Additional context**
Changes needed, but not limited to:
- Audit each module's setup to ensure idemoptency
- Ensure all computed fields such as `View.winopts` are reset
- Teardown autocommands. Using an augroup is not sufficient as some autocommands are dependent on options.
- Teardown watchers

**Comment by kyazdani42** [comment]
I think using an augroup would be sufficient though ? using clear = true on the augroup will just clear it whenever we set it back again i think.
We should just make sure that any `.setup` invocation in the plugin is idempotent, i think it should be easy to do.
