### ISSUE TITLE
'preserve_window_proportions' seems doesn't do what it should

### ISSUE THREAD

**Issue by xbladesub** [kyazdani42/nvim-tree.lua#1341]
I want to use split term and editor. After I set ```preserve_window_proportions = true``` it keeps splits on nvim-tree open, but when I close it - splits become equal in my case. Is there any solution to keep splits same size constantly when I open/close nvim-tree?

On video you can see the split size. Before I open - it's normal, after open - also, but when I close nvim-tree - it start's to resize split

https://user-images.githubusercontent.com/45129790/173231672-0cf9b7ff-be0c-478d-8461-e833580d70ce.mp4

**Comment by kyazdani42** [comment]
`:help winfixwidth` ?

**Comment by xbladesub** [comment]
> 

works, had no idea about this property) thanks!
