### ISSUE TITLE
can we independently set sidescrolloff in NvimTree ?

### ISSUE THREAD

**Issue by MRVAX** [kyazdani42/nvim-tree.lua#1346]
I tried to use autocmd to change sidescrolloff independently in NvimTree, is there any options in setting can config this for me?
```
vim.api.nvim_create_autocmd("FileType", {
    pattern = { "NvimTree" },
    callback = function ()
        vim.b.sidescrolloff = 1
    end,
})
```

**Comment by MRVAX** [comment]
btw, is there any options can set diagnostics info's position?

**Comment by gegoune** [comment]
https://github.com/kyazdani42/nvim-tree.lua#tips--reminders

**Comment by kyazdani42** [comment]
`require "nvim-tree.view".View.winopts.sidescrolloff = 1`
