### ISSUE TITLE
preserve_window_proportions=true still resizes tree window when opening file.

### ISSUE THREAD

**Issue by collinvandyck** [kyazdani42/nvim-tree.lua#1347]
### Description

I have

nvim-tree.view.preserve_window_proportions = true
equalways = false

If while editing i increase the vertical res of the tree window and then open a file, it resizes the tree window back to its original size after the file is opened. I thought `nvim-tree.view.preserve_window_proportions` would ensure that the window does not resize.

### Neovim version

```text
➜  nvim --version
NVIM v0.7.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by runner@fv-az316-460

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info
```

### Operating system and version

Linux ip-10-0-0-61 5.13.0-1025-aws #27~20.04.1-Ubuntu SMP Thu May 19 15:17:13 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### nvim-tree version

bdb6d4a

### Minimal config

```lua
require'nvim-tree'.setup {
  update_cwd = true,
  view = {
    adaptive_size = false,
    centralize_selection = true,
  },
  update_focused_file = {
    enable = false,
    update_cwd = false,
  },
}
```

### Steps to reproduce

1. Open file
2. Focus on file in tree window
3. :vertical res +5
4. press enter

### Expected behavior

The tree window stays the same width

### Actual behavior

The tree window resizes back to its original size after opening the file from the tree window.

**Comment by appcreatorguy** [comment]
I'm having this issue too.

**Comment by alex-courtis** [comment]
Replicated with default options.

**Comment by kyazdani42** [comment]
i believe this is unrelated, preserve_window_proportions is not about keeping the window of the tree. What you are looking for is:
```
    *nvim-tree.actions.open_file.resize_window*
    Resizes the tree when opening a file.
      Type: `boolean`, Default: `true
```

**Comment by collinvandyck** [comment]
Thanks!

**Comment by eleijonmarck** [comment]
https://github.com/kyazdani42/nvim-tree.lua/issues/1347#issuecomment-1159402913

I have a hard time setting this option to true.

Could you give an example to show how this would look like?

**Comment by alex-courtis** [comment]
> [#1347 (comment)](https://github.com/kyazdani42/nvim-tree.lua/issues/1347#issuecomment-1159402913)
> 
> I have a hard time setting this option to true.
> 
> Could you give an example to show how this would look like?

How about
```lua
  require("nvim-tree").setup({
    --
    actions = {
      --
      open_file = {
        resize_window = true,
        --
      },
      --
    },
    --
  })
```

**Comment by eleijonmarck** [comment]
>       preserve_window_proportions = false,

what is this setting? interesting. I would think the open-file:resize-window would be sufficient

**Comment by alex-courtis** [comment]
> what is this setting? interesting. I would think the open-file:resize-window would be sufficient

`:help nvim-tree.view.preserve_window_proportions`

It's about the proportions of the windows other than nvim-tree.

resize_window is about the size of the tree itself.

**Comment by rohit-kumar-j** [comment]
I was seeing some other issues regarding this setting (`preserve_window_proportions`). Why not make this default to true?

**Comment by gegoune** [comment]
Changing defaults is a breaking change and needs good reason behind.

**Comment by bruteforks** [comment]
I'm having a similar issue, but the commands mentioned didn't fix it.

**Comment by nimaai** [comment]
>I'm having a similar issue, but the commands mentioned didn't fix it.
same with me

**Comment by alex-courtis** [comment]
There are several discussions that have branched off here and it's not clear which of the topics we are discussing.

Please raise a new:
[Q&A discussion](https://github.com/nvim-tree/nvim-tree.lua/discussions/categories/q-a discussion) for questions
or
[bug report](https://github.com/nvim-tree/nvim-tree.lua/issues/new?assignees=&labels=bug&projects=&template=bug_report.yml) for a specific problem
