### ISSUE TITLE
Discord channel for doubts? 

### ISSUE THREAD

**Issue by hermesalvesbr** [kyazdani42/nvim-tree.lua#1350]
I'm in my first month using "neovim" and I come from VSCODE. Your plugin is extremely useful for my adaptation.

I have dozens, maybe hundreds, of doubts about the correct update and I don't think this repository is the right place for Q&A. Is there already a discord channel? Could you tell me the invite link?

Some doubts:
  - To close the tree is q, but I didn't find the key to open it, just :NvimTreeOpen
- To search is / , but pressing enter doesn't take me to the next one.
- How to close a tab? :q 'closes' the file, but the tab is at the top of my terminal.

And so it goes, hahahah.

**Comment by alex-courtis** [comment]
> * To close the tree is q, but I didn't find the key to open it, just :NvimTreeOpen

You can bind a key e.g.

`nnoremap <leader>n :NvimTreeOpen<CR>`

This is a standard pattern for vim plugins.

> * To search is / , but pressing enter doesn't take me to the next one.

I presume you mean regular vim search in a buffer. `n` and `N`. See `:help n`

> * How to close a tab? :q 'closes' the file, but the tab is at the top of my terminal.

`:tabclose`. See `:help tabpage`

**Comment by alex-courtis** [comment]
> I have dozens, maybe hundreds, of doubts about the correct update and I don't think this repository is the right place for Q&A. Is there already a discord channel? Could you tell me the invite link?

Your questions aren't really nvim-tree specific, more general vim questions.

`:help` and `:help index.txt` are entry points to all vim documentation.

A quick web search found a guide for beginners through to experts: https://thevaluable.dev/vim-commands-beginner/ Yes, it covers search and tabs.

**Comment by alex-courtis** [comment]
There is no chat server or discord. If you have any nvim-tree specific questions please start a [discussion](https://github.com/kyazdani42/nvim-tree.lua/discussions)

**Comment by kyazdani42** [comment]
@alex-courtis i think we could open a matrix chat room, wdyt ?

**Comment by hermesalvesbr** [comment]
I found this https://discord.gg/YbGC2RkN 

Thanks for all answers (y)

**Comment by alex-courtis** [comment]
> @alex-courtis i think we could open a matrix chat room, wdyt ?

We could do an nvim-tree specific one. I think there are many nvim-tree users who can help each other.

I don't think I will look at vi-tality as there is a lot of noise...

**Comment by kyazdani42** [comment]
I'll manage that :) We'll see if it's helpful or if we get too many people that just dont read the docs ^^
