### ISSUE TITLE
2 questions, git sync and specific git highlighting

### ISSUE THREAD

**Issue by ThatOneOcto** [kyazdani42/nvim-tree.lua#1354]
**Is your feature request related to a problem? Please describe.**
Can I have nvim-tree sync with git like if I do git add, it'll update and I'll see the staged symbol cause it doesn't do that
How can I make the renderer.highlight_git option only highlight gitignored files so that they appear grey

**Comment by ThatOneOcto** [comment]
How can I change the color for git unstaged icons

**Comment by alex-courtis** [comment]
> How can I change the color for git unstaged icons

`:help nvim-tree-highlight`

`NvimTreeGitDirty` sounds like unstaged.

**Comment by alex-courtis** [comment]
> Can I have nvim-tree sync with git like if I do git add, it'll update and I'll see the staged symbol cause it doesn't do that

See the experimental (default off) feature: `:help nvim-tree.filesystem_watchers`

It's still a work in progress: #1320 however it is functioning; I use it every day.

**Comment by alex-courtis** [comment]
> How can I make the renderer.highlight_git option only highlight gitignored files so that they appear grey

See `:help nvim-tree-highlight`

Unlink `NvimTreeGitIgnored` from `Comment`
```vim
:hi link NvimTreeGitIgnored NONE
```

Set `NvimTreeGitIgnored` e.g.
```vim
:hi NvimTreeGitIgnored guifg=red gui=bold,underline
```

Remove other nvim-tree git colours e.g.:
```vim
:hi clear NvimTreeGitDirty
:hi clear NvimTreeGitNew
...
```

**Comment by alex-courtis** [comment]
`NvimTreeGitIgnored` and its link to `Comment` is missing from `:help`. Changing this issue to doc for later fixing.

**Comment by alex-courtis** [comment]
Issues are for feature requests and bugs. Please raise future questions in [discussions](https://github.com/kyazdani42/nvim-tree.lua/discussions).
