### ISSUE TITLE
 module 'nvim-tree' not found

### ISSUE THREAD

**Issue by Lilja** [kyazdani42/nvim-tree.lua#1360]
### Description

I'm using `~/XDG_CONFIG_HOME/vim/vimrc` as my vim configuration, in there lies:

```vim
if has('nvim')
    Plug 'kyazdani42/nvim-web-devicons' " optional, for file icons
    Plug 'kyazdani42/nvim-tree.lua'
    lua << EOF
require("nvim-tree").setup()
EOF
endif
```

Running vim:

```
Error detected while processing /home/lilja/dotfiles/vim/vimrc:
line   29:
E5108: Error executing lua [string ":lua"]:1: module 'nvim-tree' not found:
        no field package.preload['nvim-tree']
        no file './nvim-tree.lua'
        no file '/home/runner/work/neovim/neovim/.deps/usr/share/luajit-2.1.0-beta3/nvim-tree.lua'
        no file '/usr/local/share/lua/5.1/nvim-tree.lua'
        no file '/usr/local/share/lua/5.1/nvim-tree/init.lua'
        no file '/home/runner/work/neovim/neovim/.deps/usr/share/lua/5.1/nvim-tree.lua'
        no file '/home/runner/work/neovim/neovim/.deps/usr/share/lua/5.1/nvim-tree/init.lua'
        no file './nvim-tree.so'
        no file '/usr/local/lib/lua/5.1/nvim-tree.so'
        no file '/home/runner/work/neovim/neovim/.deps/usr/lib/lua/5.1/nvim-tree.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'require'
        [string ":lua"]:1: in main chunk
```

### Neovim version

```text
NVIM v0.7.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by runner@fv-az316-460

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"
```

### Operating system and version

Ubuntu 20.04 under windows WSL 2.0

### nvim-tree version

f262236

### Minimal config

```lua
set rtp+=$XDG_CONFIG_HOME/vim
set rtp+=$XDG_CACHE_HOME/vim

call plugin#begin("$XDG_CACHE_HOME/" . (has('nvim') ? "nvim" : "vim") .  "/plugged")

if has('nvim')
    Plug 'kyazdani42/nvim-web-devicons' " optional, for file icons
    Plug 'kyazdani42/nvim-tree.lua'
    lua << EOF
require("nvim-tree").setup()
endif
call plug#end()
```

### Steps to reproduce

1. `nvim`

**Comment by kyazdani42** [comment]
Did you run `:PlugUpdate` first ?

**Comment by Lilja** [comment]
> Did you run :PlugUpdate first ?
Yes, everything is up to date.

```
lilja in ~/.c/n/p/nvim-tree.lua on master λ git log
commit f2622361072f3743bac98835a2029a9c88b81beb (grafted, HEAD -> master, origin/master, origin/HEAD)
Author: Kiyan <...>
Date:   Sun Jun 19 10:49:53 2022 +0200

    chore: add matrix link to readme
lilja in ~/.c/n/p/nvim-tree.lua on master λ pwd
/home/lilja/.cache/nvim/plugged/nvim-tree.lua
```

Could it be a pathing issue? I'm using `XDG_CONFIG_HOME` vars and custom directory placements in the machine...

**Comment by kyazdani42** [comment]
I'm not too sure about that tbh. It should work regardless. Does this happen with other plugins that needs a setup run or just nvim-tree ?

**Comment by Lilja** [comment]
I'm new to neovim and i've yet to migrate from vimscript to lua config. Could it therefore be a problem with heredoc?

It's only nvim-tree as far as I can tell... If you know a very neovim specific plugin that I can install and try with let me know.

**Comment by kyazdani42** [comment]
something like gitsigns.nvim or telescope for instance

**Comment by kyazdani42** [comment]
if you would be able to write your config in lua, i'd suggest loading your lua config with luafile and switching to packer.nvim instead of plug, which is more adapted to modern neovim configurations.

**Comment by Lilja** [comment]
![telescope](https://i.imgur.com/7MU2Vj8.png)

telescope seems to be working with vim-plug

**Comment by kyazdani42** [comment]
the provided configurations are incorrect, nvim loads `init.vim` from `~/.config/nvim`, not vimrc.
Also, the call to plug#end must come before the lua heredoc. Closing this since i've misread the configuration and it was explicit.

**Comment by Lilja** [comment]
Moving it after `call plug#end()` made it work! Thanks!

**Comment by adaptivedev** [comment]
> ```lua
>     lua << EOF
> require("nvim-tree").setup()
> ```

Looks nice! Share your init.vim or init.lua on gist please. Thanks!
