### ISSUE TITLE
how to stop nvimtree from opening on switching buffers

### ISSUE THREAD

**Issue by WilsonOh** [kyazdani42/nvim-tree.lua#1363]
Hi, I don't know if this is because of a recent update, but whenever I switch to a buffer in *another directory* using `bnext` or `bprevious`, nvimtree always opens up on every switch. 

This is my setup file for nvimtree:

```lua
nvimtree.setup {
  filters = { custom = { '*.tmp', '.git' } },
  disable_netrw = true,
  hijack_netrw = true,
  open_on_setup = true,
  ignore_ft_on_setup = { 'alpha' },
  open_on_tab = false,
  hijack_cursor = true,
  update_cwd = true,
  update_focused_file = { enable = true, update_cwd = true, ignore_list = {} },
  system_open = {
    cmd = nil,
    args = {},
  },
  view = {
    width = 25
    side = 'left',
    mappings = { custom_only = false, list = {} },
  },
  renderer = {
    indent_markers = { enable = true, icons = { corner = '└ ', edge = '│ ', none = '  ' } },
  },
}
```

I found that setting `update_focused_file.update_cwd` to `false` disables that behavior, but I also lose the automatic directory switching which I really like.

Is there any way to keep the automatic directory switching while disabling nvimtree from opening up on every buffer switch?

neovim version:
```console
NVIM v0.8.0-dev+1841-g3cd22a348
Build type: Release
LuaJIT 2.1.0-beta3
```

nvimtree commit: `104292c`

Thank you!

**Comment by alex-courtis** [comment]
replicated

**Comment by alex-courtis** [comment]
#1328

We are not obeying `with_open` during [find_file](https://github.com/kyazdani42/nvim-tree.lua/pull/1328/files#diff-d2d7203cea884a09928ac1574693d436d6e3db28e62daabfa53f5f9f7740f51aR141).

`change_root` should not call `lib.open` when not `with_open`. In that case it should just call [change_dir.fn(...](https://github.com/kyazdani42/nvim-tree.lua/pull/1328/files#diff-d2d7203cea884a09928ac1574693d436d6e3db28e62daabfa53f5f9f7740f51aL107).

I did not test nvim-tree closed when testing the change.

@lixvbnet  please create a PR to fix.

**Comment by WilsonOh** [comment]
Ah, should I just wait for an update or is there a quick and dirty fix for this?

**Comment by alex-courtis** [comment]
It's not a one line change...

nightly tag ( 84c2bd7 right now ) is before this change.

**Comment by WilsonOh** [comment]
Ok, thank you!

**Comment by lixvbnet** [comment]
> #1328
> 
> We are not obeying `with_open` during [find_file](https://github.com/kyazdani42/nvim-tree.lua/pull/1328/files#diff-d2d7203cea884a09928ac1574693d436d6e3db28e62daabfa53f5f9f7740f51aR141).
> 
> `change_root` should not call `lib.open` when not `with_open`. In that case it should just call [change_dir.fn(...](https://github.com/kyazdani42/nvim-tree.lua/pull/1328/files#diff-d2d7203cea884a09928ac1574693d436d6e3db28e62daabfa53f5f9f7740f51aL107).
> 
> I did not test nvim-tree closed when testing the change.
> 
> @lixvbnet please create a PR to fix.

well, I didn't test that case either...  PR is on the way

**Comment by lixvbnet** [comment]
PR #1365 does the fix.  Replaced lib.open calls in M.change_root.
with_open is checked in [find_file](https://github.com/kyazdani42/nvim-tree.lua/blob/master/lua/nvim-tree.lua#L156) before calls into M.change_root.

**Comment by alex-courtis** [comment]
Thanks for the fast fix @lixvbnet . Unfortunately I won't be able to review until next weekend.

@WilsonOh please test the fix above.

**Comment by WilsonOh** [comment]
Yup, works great on my machine. Thank you @lixvbnet!
