### ISSUE TITLE
Warn users when trash command is not available

### ISSUE THREAD

**Issue by mvllow** [kyazdani42/nvim-tree.lua#1366]
### Description

If `gio trash` is not available on the user's system, attempting to trash a file instead permanently deletes the file with no warning to the user. For anyone who was using `trash` before, after #1323 they would now be deleting files without knowing.

### Neovim version

```text
NVIM v0.8.0-dev+1894-gc57f6b28d
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

macOS 13.0 Beta

### nvim-tree version

79258f1

### Minimal config

```lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvt-min/site]]
local package_root = "/tmp/nvt-min/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup {
    {
      "wbthomason/packer.nvim",
      "kyazdani42/nvim-tree.lua",
      "kyazdani42/nvim-web-devicons",
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  }
end
if vim.fn.isdirectory(install_path) == 0 then
  print "Installing nvim-tree and dependencies."
  vim.fn.system { "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path }
end
load_plugins()
require("packer").sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua setup()]]
vim.opt.termguicolors = true
vim.opt.cursorline = true

-- MODIFY NVIM-TREE SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
_G.setup = function()
  require("nvim-tree").setup {}
end
```

### Steps to reproduce

1. touch delete-me.txt
2. nvim -nu nvt-min.lua
3. `:NvimTreeToggle`
4. hover "delete-me.txt" and press `D` (confirming the deletion)

### Expected behavior

Pressing `D` to trash a file should either trash the file, in this case `gio trash` must be available, or fail the operation.

### Actual behavior

Pressing `D` to trash a file will permanently a file if `gio trash` is not available.

**Comment by alex-courtis** [comment]
> Pressing D to trash a file will permanently a file if gio trash is not available.

I'm not seeing this behaviour; trash failure results in the file silently remaining.

Created https://github.com/kyazdani42/nvim-tree.lua/tree/1366-warn-when-trash-cmd-missing which warns on trash failure.

@mvllow please test the branch.

**Comment by mvllow** [comment]
Unfortunately this issue still persists after upgrading to the latest commit. `D` asks "Trash <file> ? y/n" and confirming with "y" deletes the file (skipping trash and no warning). Changing the trash cmd to `trash` (what I use on macOS) then it does successfully trash the file.

**Comment by kyazdani42** [comment]
seems weird to me, there is not such code where a delete can be possible using `D`. I've pushed another fix to avoid running trash when it's not executable.

**Comment by mvllow** [comment]
I updated to the latest commit (https://github.com/kyazdani42/nvim-tree.lua/commit/21516f447baf42f6f11421a017cd69306d5d5ff3).

With no extra config, e.g. using `require('nvim-tree').setup()`, `D` still deletes a file.

Setting a custom trash cmd which doesn't exist, however, does _not_ delete a file and outputs "[NvimTree] fake-trash is not executable" which is perfect. Just not sure why it's deleting when no custom trash cmd is set. Hmm.

Because no one else seems to be having this issue I don't mind leaving it closed – I appreciate the help. If I end up finding the problem outside of user error I'll make a PR 😌

**Comment by kat0h** [comment]
The `gio trash` command in macOS moves files to `$XDG_DATA_HOME/Trash` or `~/.local/share/Trash/files` by default so the files aren't removed.
But users expect that the trash command moves files into `~/.Trash`. I think we should present a better way for macOS. 
For example, we can use `osascript -e 'tell app "Finder" to move the POSIX file "%s" to trash'`.

**Comment by alex-courtis** [comment]
> The `gio trash` command in macOS moves files to `$XDG_DATA_HOME/Trash` or `~/.local/share/Trash/files` by default so the files aren't removed. But users expect that the trash command moves files into `~/.Trash`. I think we should present a better way for macOS. For example, we can use `osascript -e 'tell app "Finder" to move the POSIX file "%s" to trash'`.

You could change `:help nvim-tree.trash.cmd` to "trash". I do not have access to a MacOS environment however I recall that command works with Finder ~/.Trash

**Comment by kennyishihara** [comment]
For anyone on macOS, run `brew install trash` then add this to the config

```
require('nvim-tree').setup {
  trash = {
    cmd = "trash"
  }
}
```

Now `D` should place the file to `~/.Trash` folder

**Comment by alex-courtis** [comment]
> Slightly off topic but was mentioned in the discussion. For anyone on macOS, run `brew install trash` then add this to the config
> 
> ```
> require('nvim-tree').setup {
>   trash = {
>     cmd = "trash"
>   }
> }
> ```
> 
> Now `D` should place the file to `~/.Trash` folder.

We have marked trash as unavailable on macos: https://github.com/nvim-tree/nvim-tree.lua/blob/3b62c6bf2c3f2973036aed609d02fd0ca9c3af35/doc/nvim-tree-lua.txt#L2291

I don't have access to macos to test this. Please:
1. provide the output of `:lua print(vim.fn.has("unix"))`
2. remove `cmd = "trash"` and report the behaviour on `D`

We could:
1. remove the unsupported note, advising the above config
2. default `cmd = "trash"` on macos

**Comment by kennyishihara** [comment]
> 1. provide the output of `:lua print(vim.fn.has("unix"))`

Using my current setup explained in my previous comment, this command returns `1`

> 2. remove `cmd = "trash"` and report the behaviour on `D`

Without this, the trashed file goes into `~/.local/share/Trash/files/` and not into `~/.Trash` as @kat0h mentioned. I do not get any error message.

The thing is by default, macOS doesn't come with the command `trash` so you will have to install it via `brew install trash`. Else, you have to just `mv` the file to the `~/.Trash` folder.

**Comment by alex-courtis** [comment]
> > 3\. ``
> 
> Without this, the trashed file goes into `~/.local/share/Trash/files/` and not into `~/.Trash` as @kat0h mentioned. I do not get any error message.

I see. It looks like `gio trash` does do something on macos, using the standard XDG paths.

Is gio part of a standard macos installation or did you have to install it yourself?

What are your experiences @gegoune ?

**Comment by kennyishihara** [comment]
> Is gio part of a standard macos installation or did you have to install it yourself?

Yes, I believe gio comes installed as I don't remember installing it manually but it is available on my mac. I am using M1 chip, not sure if that makes any difference.

**Comment by alex-courtis** [comment]
By default `gio trash` is being used instead of `trash`. That does trash the file, but not in the correct location.

No changes are needed around the warning as it is currently functioning correctly with the default `"gio trash"` and `"trash"`.

It seems that we could change the default for macos and add trash installation to the documentation.

I feel I might be taking down Chesterton's Fence here; the limitation was explicitly documented.

**Comment by kennyishihara** [comment]
@alex-courtis Yup agreed and we can customize our own trash command if needed. 

There is a bit of inconsistency in the doc however because [here](https://github.com/nvim-tree/nvim-tree.lua/blob/273c1700eb68c27dce4e518efafc8144fd7ce4ab/doc/nvim-tree-lua.txt#L2290) we are saying Trash is unavailable for MacOS, but in reality `gio trash` is a valid command and [here](https://github.com/nvim-tree/nvim-tree.lua/blob/273c1700eb68c27dce4e518efafc8144fd7ce4ab/doc/nvim-tree-lua.txt#L1151) we are saying Trash is valid for unix. macOS is unix system.

**Comment by gegoune** [comment]
For me `gio` came from `Homebrew` package `glib`.

```
/opt/homebrew/bin/gio -> ../Cellar/glib/2.76.4/bin/gio
```

I have never used it though.

**Comment by kennyishihara** [comment]
> For me `gio` came from `Homebrew` package `glib`.

You are right. I just verified that `glib` and `gio` come from homebrew so my mistake @alex-courtis. I suppose without homebrew, `D` will not work.

**Comment by alex-courtis** [comment]
> I have never used it though.

It does not seem to be very useful, using XDG paths.

**Comment by alex-courtis** [comment]
Please review https://github.com/nvim-tree/nvim-tree.lua/pull/2336
