### ISSUE TITLE
Not using lua for setup

### ISSUE THREAD

**Issue by sozoalvin** [kyazdani42/nvim-tree.lua#1376]
### Description

In the instructions, it is stated that this should be used 
`require("nvim-tree").setup()` if using a vim file. 

There were not a lot of other instructions available for i found some help on google and ended up with someone suggesting to copy paste this `lua require'nvim-tree'.setup {}` into init.vim which i did. 

And lo and behold it works! There wasnt even a need for me to disable netwr. 

However, I think im missing something. There are some tutorials online that suggests files such as .. 

`keymaps.lua`  and `nvim-tree-config.lua` that sit in ~/.config/nvim/user/

I tried to manually create these sub directories and files.. but the custom configs don't work. For example, I tried changing a staged/ commit emoticon but it wouldnt work when i did some file changes. 

Since im not using packer from lua, and no proper init.lua file .. is this the reason? 

If yes, how can people who are not using lua .. implement their own keymaps or config? 

Hope my question is clear! And Many thanks in advance for your kind assistance

### Neovim version

```text
NVIM v0.7.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@iMac-Pro

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.7.0/share/nvim"
```

### Operating system and version

mac os 10.15.7

### nvim-tree version

7a795d7

### Minimal config

```lua
-
```

### Steps to reproduce

-

### Expected behavior

custom config changes should be reflected

### Actual behavior

custom config changes are not reflected

**Comment by gegoune** [comment]
This isn't really nvim-tree specific. Have a look at https://github.com/nanotee/nvim-lua-guide. it will most likely answer all your questions.

**Comment by alex-courtis** [comment]
See `:help lua-heredoc` for information on passing configuration to setup from a .vim file.

That is not very practical. See my [init.vim](https://github.com/alex-courtis/arch/blob/f3cbc45d310ff9e4b6362929f437e8839f61552d/config/nvim/init.vim#L101) which calls [nvim-tree.lua](https://github.com/alex-courtis/arch/blob/f3cbc45d310ff9e4b6362929f437e8839f61552d/config/nvim/lua/amc/nvim-tree.lua) to start nvim-tree.

**Comment by sozoalvin** [comment]
> 

thank you for your help. followed your set up but an entire suite of errors ensued. Since the tree works for now; i will just use it for now. When i have more time dedicated to move to lua or learn more. ill close it now and reopen when that day comes!
