### ISSUE TITLE
Floating nvim-tree window

### ISSUE THREAD

**Issue by utilyre** [kyazdani42/nvim-tree.lua#1377]
**Is your feature request related to a problem? Please describe.**
I always have this problem with file explorer plugins that when I close a window or a buffer the explorer will take over the entire screen or all my layouts mess up.

**Describe the solution you'd like**
Although plugins like vim-bbye exist, I came up with another solution. That being making all non-file windows float. Such as explorer, buffer switcher, terminal, etc. So does nvim-tree!

**Comment by alex-courtis** [comment]
This is a very ambitious feature. Other plugins, terminal etc. are outside of the scope of nvim-tree and will not be considered.

Please explain exactly how this will work:
- mockups of the floating nvim-tree
- configuration options to control this feature
- how the floating window will interact with tabs
- details on window (re)sizing and placement of signs / icons

Building this functionality and raising a PR is the realistic way to achieve this feature. It is highly unlikely that the nvim-tree team will build such a feature.

**Comment by utilyre** [comment]
> This is a very ambitious feature. Other plugins, terminal etc. are outside of the scope of nvim-tree and will not be considered.

Maybe I explained my idea a little confusing. All I meant was to have an option to make nvim-tree float. I brought the terminal and buffer switcher examples to show what I meant by "non-file" windows.

The floating window should be an exact clone of the current side-window except for the fact that it should close its-self right after pressing enter on a file (the `edit` action in keymaps basically) in order to focus on the opened file.

In addition, having some options to control the style of the floating window wouldn't hurt. Such as `border`, `winblend`, etc.

**Comment by kyazdani42** [comment]
I though it was asked already but cannot find the issue. Please open a PR if you feel like it, it might be a bit complex feature though :)
