### ISSUE TITLE
Question for close keymapping

### ISSUE THREAD

**Issue by LoydAndrew** [kyazdani42/nvim-tree.lua#138]
Is there a shortcut for close when inside nvim-tree, I can't find anything related in README? For example in nerdtree you can use `q` to close tree.

**Comment by kyazdani42** [comment]
you have to map it yourself. (`:LuaTreeClose`). You could write something like
```vim
au FileType LuaTree lua vim.api.nvim_buf_set_keymap('n', '<somekeymap>', ':LuaTreeClose<CR>', {})
```

**Comment by LoydAndrew** [comment]
That works, thanks.
