### ISSUE TITLE
when enable filesystem_watchers , the git highlight not automatic display

### ISSUE THREAD

**Issue by tomasky** [kyazdani42/nvim-tree.lua#1381]
### Description

when enable filesystem_watchers , the git highlight not automatic display

### Neovim version

```text
nvim 0.7.2
```

### Operating system and version

ubuntu

### nvim-tree version

latest

### Minimal config

```lua
filesystem_watchers = {
      enable = true,
   },
   git = {
      enable = true,
      ignore = false,
   },

```

### Steps to reproduce

1. nvim some.lua in a git proj
2. ctrl-e
3. delete some line in some.lua

**Comment by alex-courtis** [comment]
Thank you for testing this experimental feature.

Please indicate which version you are running: `cd <your-package-directory>/nvim-tree.lua ; git log --format='%h' -n 1`

Please enable [logging](https://github.com/kyazdani42/nvim-tree.lua#diagnostic-logging) and send us the file, and indicate the time that the issue occurs.

```lua
    log = {
      enable = true,
      truncate = true,
      types = {
        profile = true,
        watcher = true,
      },
    },
```

**Comment by tomasky** [comment]
3 . delete some line in some.lua

**Comment by tomasky** [comment]
maybe my machine config problem ,close it.

**Comment by alex-courtis** [comment]
> my git proj is located /tmp/somegit dir , but if it is located ~/somegit , it works,it is so strange

Aha! File system watchers do not behave as expected for files under /tmp, due to the nature of tmpfs. This may (probably won't) change with further watcher optimisation.

**Comment by kyazdani42** [comment]
I'll take a look if this could be fixed this weekend

**Comment by kyazdani42** [comment]
I could not reproduce even in a tmpfs folder
