### ISSUE TITLE
Unmerged files not being highlighted in tree

### ISSUE THREAD

**Issue by sozoalvin** [kyazdani42/nvim-tree.lua#1382]
### Description

staged, unstaged, ignored files get displayed properly and according to their status and their symbols defined in the nvim tree config

_unmerged_ on the other hand doesn't display the symbol. Is this is a known bug? :)

### Neovim version

```text
NVIM v0.7.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@iMac-Pro
```

### Operating system and version

MacOS 10.15.7

### nvim-tree version

7285898

### Minimal config

```lua
sorry i can't seem to get this to work. 

i saved nvt-min.lua into ~/.config/nvim/lua/user/tmp/
and ran nvim -nu ./tmp/nvt-min.lua while i was cd-ed into the user directory

and the file in /tmp/nvt-min.lua didnt change. The same as i copy pasted from your link of nvt-min.lua
```

### Steps to reproduce

Git add a file -> file  symbol changes to to unstaged to staged
Git commit a file -> file symbol doesn't change to unmerged

### Expected behavior

Git add a file -> file  symbol changes to to unstaged to staged
Git commit a file -> file symbol changes to merged

symbols should be governed by renderer.icons.git.

### Actual behavior

Git add a file -> file  symbol changes to to unstaged to staged
Git commit a file -> file symbol doesn't change to unmerged

**Comment by kyazdani42** [comment]
`unmerged` is a bit misleading, it refers to a file in conflict during merge/rebase.
committing a file just removes its status from the worktree since its change have been committed to the previous commit.

**Comment by sozoalvin** [comment]
thank you - i always had my original impression. is your definition of unmerged stated anywhere? if not i can do a PR just to correct that.

**Comment by kyazdani42** [comment]
please do if you have some time, something like `merging` would be more appropriate. Although this might break many existing configurations.

**Comment by sozoalvin** [comment]
wanted to very quickly just add in the docs but access was denied when doing a PR. I would love to change unmerge into merging but im not good in lua. would definitely love to contribute asap though!

**Comment by kyazdani42** [comment]
just fork the repository and create a PR :)
