### ISSUE TITLE
Is there any ways to recover nvim-tree delete directory?

### ISSUE THREAD

**Issue by NEX-S** [kyazdani42/nvim-tree.lua#1387]
I want to use E to expand but accidently press D....

**Comment by kyazdani42** [comment]
This is not something related to nvim-tree, plus i cannot answer if i don't have more context.

**Comment by kyazdani42** [comment]
`D` is trash so refer to the trash comment of your system.

**Comment by reaz1995** [comment]
@NEX-S 
if you pressed D it mean it was deleted by Trash command and it went to:
```
~/.local/share/Trash/files
```
how to restore when you currently at nvim-tree bar?
1. MAKE SURE YOU ON NVIM-TREE BAR
2.  move coursor to  dir where was the deleted file
3.  well just press  colon :   then type   !trash-restore   then choose which file you want to restore

for more info:
man trash  
man restore-trash

**Comment by NEX-S** [comment]
Thanks <3
