### ISSUE TITLE
Next / Prev Git File Item

### ISSUE THREAD

**Issue by alex-courtis** [kyazdani42/nvim-tree.lua#1389]
**Is your feature request related to a problem? Please describe.**
`next_git_item` will take you to the directory containing the git item. It would be useful to navigate directly to the file.

In this case, you need to `next_git_item` 5 times to get to the file.

![20220703_094542 409x466](https://user-images.githubusercontent.com/1505378/177019228-2410885b-335c-4e8f-afb4-cfb6218b3547.png)

**Describe the solution you'd like**
`next_git_file_item` to navigate directly to the file.

**Describe alternatives you've considered**
Directories could also be recursively opened until the file item is found.

**Additional context**
I find myself using `next_git_item` `edit` `next_git_item` `edit` `next_git_item` ... very frequently.

**Comment by alex-courtis** [comment]
An alternative might be simply a `show_on_dirs` option for git, as per diagnostics.

Both would be nice.

**Comment by kyazdani42** [comment]
Maybe just skipping if the file is a directory in the next/prev action would work too.

**Comment by kyazdani42** [comment]
@alex-courtis is this working now ?

**Comment by alex-courtis** [comment]
Closing. `show_on_dirs` is a good enough solution.

I'd still like some means of finding the git items down the tree, however I don't have a user story for that.
