### ISSUE TITLE
QUESTION - Don't change directory for files not in git repo

### ISSUE THREAD

**Issue by trankchung** [kyazdani42/nvim-tree.lua#1393]
### Description

What is the settings that stops the tree from finding the next top level git repo and make it the root folder? Evey time I open a file that's in deep in my ~/.config folder tree kept on making my home directory as the root folder b/c that's the folder that has .git folder in it.

### Neovim version

```text
N/A
```

### Operating system and version

Linux

### nvim-tree version

master

### Minimal config

```lua
N/A
```

### Steps to reproduce

1. Change into ~/.config/some/folder/to/run/vim
2. Run nvim
3. Open a file in that folder

The tree makes the ~ folder the root folder instead of the current folder

### Expected behavior

Root folder should be current folder.

### Actual behavior

Made home folder current folder.

**Comment by kyazdani42** [comment]
there is none, this should be coming from a rooter plugin.
