### ISSUE TITLE
`.git` folder should be included in `gitignore`-ignores

### ISSUE THREAD

**Issue by mosauter** [kyazdani42/nvim-tree.lua#1395]
**Is your feature request related to a problem? Please describe.**
If I ignore only `gitignored` files and _not_ dotfiles the `.git` folder is still shown. I have multiple dotfiles in the repository so I don't want to ignore those. But `.git` is rarely necessary and even though it is not explicitly in the `gitignore` it is implicitly there.

Even if I explicitly add `.git` to the `gitignore` it will not hide the folder. (This could be a bug, but I didn't look too closely into it).

**Describe the solution you'd like**
The "Ignore gitignore files" option, should also hide `.git`

**Describe alternatives you've considered**
Alternatively an explicit option for `.git` but I personally don't see a use-case. 

**Additional context**
![image](https://user-images.githubusercontent.com/9122366/177130017-521c284c-1f2f-48ad-97e9-931a61e8cc00.png)

**Comment by kyazdani42** [comment]
`filter = { custom = { ".git$" } }`

**Comment by mosauter** [comment]
Ah did not know about this, awesome thanks!

For anyone finding this afterwards, the actual option is `filters` with the `s`:

```
filters = { custom = { ".git$" } }
```

**Comment by alex-courtis** [comment]
https://github.com/kyazdani42/nvim-tree.lua#tips--tricks
