### ISSUE TITLE
NvimTreeOpen resizes the splits

### ISSUE THREAD

**Issue by jefersonsanchesmms** [kyazdani42/nvim-tree.lua#1397]
### Description

So I noticed that every time I open NvimTree, my split panes get resized to equal sizes.

I searched the docs and could not find how to maintain the splits' sizes after opening the tree.
![nvim_rec](https://user-images.githubusercontent.com/76951633/177253611-e5ad18e3-c6b1-44af-9571-ccda732daab4.gif)

### Neovim version

```text
❯ nvim --version
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@BigSur

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.7.2/share/nvim"

Run :checkhealth for more info
```

### Operating system and version

macOS 11.6.6

### nvim-tree version

7285898

### Minimal config

```lua
nmap tt :NvimTreeToggle<CR> "this is all I have outside of icons configs
```

### Steps to reproduce

1. Create a horizontal split
2. Resize the bottom split to, say, 10 rows tall
3. Open :NvimTreeOpen (works toggling too)

### Expected behavior

I expected the split below to remain with it's current size of 10

### Actual behavior

Both horizontal splits end up with the same size

**Comment by kyazdani42** [comment]
`:help nvim-tree.view.preserve_window_proportions` ?

**Comment by jsanchesleao** [comment]
oh, my bad...
will close this

thank you for that

**Comment by sungkang** [comment]
`nvim-tree.view.preserve_window_proportions` doesn't seem to respect vertical splits.

**Comment by kyazdani42** [comment]
what do you mean ? 
Could you open an issue with more information please ?

**Comment by doshpin** [comment]
Is there a way to also preserve vertical splits?

**Comment by alex-courtis** [comment]
> Is there a way to also preserve vertical splits?

Vertical splits are preserved. If that isn't working for you, please raise a new [Bug Report](https://github.com/nvim-tree/nvim-tree.lua/issues/new?assignees=&labels=bug&projects=&template=bug_report.yml)
