### ISSUE TITLE
Navigating between git items only works when lua_tree_show_icons.git == 1

### ISSUE THREAD

**Issue by cooperuser** [kyazdani42/nvim-tree.lua#140]
Pretty self explanatory from the title. using `[c` and `]c` only jump when the user has not disabled `lua_tree_show_icons.git`. I am trying to disable the git icons and show git status just from color, but I would still like to be able to jump between git items.

**Comment by kyazdani42** [comment]
i could implement that in the rewrite, should be fairly easy to do. The current implementation is a hack :)

**Comment by cooper-anderson** [comment]
Yeah I am assuming it jumps between the git icons themselves or something along those lines.

**Comment by kyazdani42** [comment]
exactly. A better approach would be to do some kind of node search in the tree. I don't really use this feature so i won't bother implementing it, but feel free to do it :)

**Comment by alex-courtis** [comment]
Implemented by #972
