### ISSUE TITLE
"Unknown option 1"

### ISSUE THREAD

**Issue by kotvmrc** [kyazdani42/nvim-tree.lua#1402]
### Description

I got following warning during launch of the neovim:

`[NvimTree] unknown option: 1`

Any idea why thats happening?

### Neovim version

```text
NVIM v0.7.0
```

### Operating system and version

ArchLinux fully upgraded

### nvim-tree version

Latest

### Minimal config

```lua
Default config from readme file + autocomand to auto close from  [#1115](https://github.com/kyazdani42/nvim-tree.lua/discussions/1115)
```

### Steps to reproduce

Happens on startup

### Expected behavior

No warnings

### Actual behavior

Warning about unknown option 1

**Comment by kotvmrc** [comment]
This is the content of my nvim-tree config file:
```lua
local status_ok, nvim_tree = pcall(require, "nvim-tree")
if not status_ok then
  return
end


nvim_tree.setup({
  vim.api.nvim_create_autocmd("BufEnter", {
    nested = true,
    callback = function()
      if #vim.api.nvim_list_wins() == 1 and vim.api.nvim_buf_get_name(0):match("NvimTree_") ~= nil then
        vim.cmd "quit"
      end
    end
  })
)
```
And every time I open NeoVim, appers this:
![image](https://user-images.githubusercontent.com/82162277/177802908-bfa3dd34-dc24-439a-9deb-4436af584a82.png)

Nvim-tree continue working as expected and the "auto_close" workaround works like a charm.

**Comment by kyazdani42** [comment]
sure, the vim.api.nvim_create_autocmd is not supposed to be passed in setup

**Comment by kyazdani42** [comment]
closing since this is an error with the config.

**Comment by kyazdani42** [comment]
PS:
```lua
nvim_tree.setup({})
vim.api.nvim_create_autocmd...
```

**Comment by kotvmrc** [comment]
> PS:
> 
> ```lua
> nvim_tree.setup({})
> vim.api.nvim_create_autocmd...
> ```

Thanks, it works!
