### ISSUE TITLE
[file rename] run :edit to reload filetype when buffer is loaded and renamed

### ISSUE THREAD

**Issue by ignamartinoli** [kyazdani42/nvim-tree.lua#1404]
**Is your feature request related to a problem? Please describe.**
It's not really a bug. But it would be cool that if somebody renames a file to a different filetype, `nvim-tree.lua` could check if there was an **LSP** or a `nvim-treesitter` module to load.

**Describe the solution you'd like**
After renaming, try to activate `nvim-treesitter` and **LSP**

**Describe alternatives you've considered**
Turn it on myself ahah

**Comment by kyazdani42** [comment]
Do you mean just running `:edit` on the buffer that was renamed ? This way the filetype would change ?

**Comment by ignamartinoli** [comment]
Yes, that would trigger `nvim-treesitter` syntax highlighting.

For the LSP, I just made a test and it's bit trickier.
If, for example, you had a **Java** file, and were to rename it to a `*.py`, after running `:edit` you would have both **Java** and **Python** LSPs running.

I'm not sure if it's possible to fix that from `nvim-tree`.

**Comment by kyazdani42** [comment]
I'm not sure, this sounds to me this is the lsp client job, not nvim-tree. At least triggering an edit if the buffer exists for a renamed file would be enough, the rest should be left to whatever plugin uses filetype detection. I'm renaming this since its unrelated to other plugins but more related to neovim internals.

**Comment by alex-courtis** [comment]
This would be very useful for a pattern I often follow:
* `a` create a new file
* add `#!/bin/sh` to the first line
* `.` `!chmod 755 ...`
* `:set ft=sh`

We could adapt this solution to automate that last step.

**Comment by ignamartinoli** [comment]
@kyazdani42  I added [this](https://github.com/ignamartinoli/nvim-tree.lua/blob/master/lua/nvim-tree/actions/rename-file.lua#L36) line on `rename-file.lua`

```lua
vim.cmd [[silent! edit]]
```

But it doesn't work like when the user runs the command himself, I read the `man` page and tried different variants, do you happen to know where I'm missing the point?

**Comment by kyazdani42** [comment]
you need to edit _after_ reloading the buffers

**Comment by ignamartinoli** [comment]
@kyazdani42 I'm really sorry. I surrender ahaha, I can't fix it. If you're able I would love to see how it's done

**Comment by kyazdani42** [comment]
no worries :) i'll fix this then

**Comment by ignamartinoli** [comment]
Thanks!
