### ISSUE TITLE
Disabling folder icons disables folder arrows

### ISSUE THREAD

**Issue by milessabin** [kyazdani42/nvim-tree.lua#1406]
### Description

As discussed in #1405, setting,
```lua
renderer = {
  icons = {
    show = {
      file = true,
      folder = false,
      folder_arrow = true,
      git = true
    }
  }
}
```
Disables the arrows as well as the icons, whereas the expectation is that arrows would continue to be rendered.

### Neovim version

```text
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

Linux 5.18.9-arch1-1

### nvim-tree version

4bd919a

### Minimal config

```lua
renderer = {
icons = {
  show = {
    file = true,
    folder = false,
    folder_arrow = true,
    git = true
  }
}
```

### Steps to reproduce

1. Modify config as above.
2. Observe lack of arrows rendered.

### Expected behavior

Folder arrows shown, no folder icons.

### Actual behavior

No folder arrows shown, no folder icons.

**Comment by alex-courtis** [comment]
We could also allow with indent markers.

            *nvim-tree.renderer.icons.show.folder_arrow*
            Show a small arrow before the folder icon.
            Requires |renderer.icons.show.folder| `= true` and |renderer.indent_markers.enable| `= false`
              Type: `boolean`, Default: `true`

**Comment by kyazdani42** [comment]
thanks alex :) I was going to patch this, but i see you've already went and done it :)
