### ISSUE TITLE
copy / cut / delete action to multiple file

### ISSUE THREAD

**Issue by afdallah** [kyazdani42/nvim-tree.lua#1407]
Thanks for making this plugin.
**Is your feature request related to a problem? Please describe.**
Let's say we want to move multiple files from folder A to folder B, currently, we can only do it one by one. 

**Describe the solution you'd like**
Selecting multiple files by pressing `v` similar to vim visual mode then do copy/cut/delete all at once

**Comment by alex-courtis** [comment]
This is desirable functionality. Duplicate of #221
