### ISSUE TITLE
Conflict with coc and vim-lsp

### ISSUE THREAD

**Issue by nothingIsSomething** [kyazdani42/nvim-tree.lua#1426]
### Description

I don't know how it is related to these 2 plugins but the semantic highlighting doesn't work with nvim-tree activated, I deactivate nvim-tree and everything works fine, both plugins (coc and vim-lsp) offers semantic highlighting for rust, it stops working just when I enable nvim-tree.

This is my init.lua
```lua
 	local Plug = vim.fn['plug#']
	vim.call('plug#begin', '~/.config/nvim/plugged')

	Plug 'prabirshrestha/vim-lsp'
	Plug 'mattn/vim-lsp-settings'
	
	Plug 'christianchiarulli/nvcode-color-schemes.vim'
 	Plug 'kyazdani42/nvim-web-devicons'
	--
 	--Plug 'kyazdani42/nvim-tree.lua'
	--

	vim.call('plug#end')

	 vim.cmd([[
		set t_Co=256
		syntax enable
		silent! colorscheme nvcode
		set background=dark
		set number
	 ]])


	vim.g.lsp_semantic_enabled = 1
        --require("nvim-tree").setup()
```
Open a rust file and run
```
:LspInstallServer
```
wait for rust-analizer to load, sometimes it takes a while, then the syntax is colored,
but with nvim-tree enabled, it does not work, the same happens with coc.

### Neovim version

```text
NVIM v0.7.2
```

### Operating system and version

Windows 10

### nvim-tree version

449b5bd

### Minimal config

```lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvt-min/site]]
local package_root = "/tmp/nvt-min/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup {
    {
      "wbthomason/packer.nvim",
      "kyazdani42/nvim-tree.lua",
      "kyazdani42/nvim-web-devicons",
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
	  "christianchiarulli/nvcode-color-schemes.vim",
	  "prabirshrestha/vim-lsp",
	  "mattn/vim-lsp-settings"
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  }
end
if vim.fn.isdirectory(install_path) == 0 then
  print "Installing nvim-tree and dependencies."
  vim.fn.system { "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path }
end
load_plugins()
require("packer").sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua setup()]]
vim.opt.termguicolors = true
vim.opt.cursorline = true

vim.g.lsp_semantic_enabled = 1

-- MODIFY NVIM-TREE SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
_G.setup = function()
  require("nvim-tree").setup {}
end
```

### Steps to reproduce

Open a rust file and run
```
:LspInstallServer
```
wait for rust-analyzer to install, restart nvim, wait for rust-analyzer to load, sometimes it takes a while, then the syntax is colored,
but with nvim-tree enabled, it does not work.

### Expected behavior

Highlighting semantic syntax

### Actual behavior

With nvim-tree enabled, nothing is highlighted.

**Comment by alex-courtis** [comment]
There are known issues with diagnostics: https://github.com/kyazdani42/nvim-tree.lua/issues/1317, especially coc.

It is not a simple fix and is a work in progress.

Closing in favour of https://github.com/kyazdani42/nvim-tree.lua/issues/1317

Please reopen if you experience problems after that is resolved.
