### ISSUE TITLE
Open new tab in background

### ISSUE THREAD

**Issue by dtk9289** [kyazdani42/nvim-tree.lua#1428]
**Is your feature request related to a problem? Please describe.**
i can't open newtab without jumping into it

**Describe the solution you'd like**

**Describe alternatives you've considered**
Add few lines into nvim-tree/actions/node/open-file.lua
```lua
local function open_file_in_bgtab(filename)
  if M.quit_on_open then
    view.close()
  end
  vim.cmd("tabe " .. vim.fn.fnameescape(filename) .. "| tabprevious")
end

function M.fn(mode, filename)
...
if mode == "bgtab" then
    return open_file_in_bgtab(filename)
  end
...
```

**Comment by kyazdani42** [comment]
looks like you are missing a space in the vim.cmd after tthe concatenation.

**Comment by dtk9289** [comment]
> looks like you are missing a space in the vim.cmd after tthe concatenation.

![image](https://user-images.githubusercontent.com/48422877/179350019-52d134e0-b53e-4ef3-90e2-ebc5582c8d0b.png)
it still working

**Comment by kyazdani42** [comment]
works fine for me if you add `"SPACE_HERE | tabprevious"`

**Comment by kyazdani42** [comment]
PS: you should bind this to a keybinding yourself, no need to update the code in nvim-tree ^^

**Comment by dtk9289** [comment]
> PS: you should bind this to a keybinding yourself, no need to update the code in nvim-tree ^^

i find another way around but it isn't good as the solution above, open files with same name in different folder will not work
```lua
autocmd FileType NvimTree nmap <buffer> <S-t> <C-w>gF:tabprev<CR>
```

**Comment by kyazdani42** [comment]
why not using the setup...?
`mappings = { list = { key = "<S-t>", action = "bg_tab", action_cb = your_lua_function } } }`

**Comment by dtk9289** [comment]
> why not using the setup...? `mappings = { list = { key = "<S-t>", action = "bg_tab", action_cb = your_lua_function } } }`

thanks
