### ISSUE TITLE
Removing files input problem with cmdheight = 0

### ISSUE THREAD

**Issue by arsham** [kyazdani42/nvim-tree.lua#1434]
### Description

When the `cmdheight` is `0` and hitting `d` for removing files, it [prints](https://github.com/kyazdani42/nvim-tree.lua/blob/06e48c29c4543331eee41753e69e3bd2235bf430/lua/nvim-tree/actions/fs/remove-file.lua#L71) a prompt waiting for user to enter `y`/`n`, which is hidden behind the status bar.
I would recommend using `vim.ui.select()` API.

### Neovim version

```text
NVIM v0.8.0-dev-nightly-4-g5ccdf6a88d-dirty
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

Arch Linux 

### nvim-tree version

acd4821

### Minimal config

```lua
Any config would do. Just add:

vim.opt.cmdheight = 0
```

### Steps to reproduce

1. nvim
2. :set cmdheight=0
3. NvimTreeOpen
4. (choose a file)
5. d

### Expected behavior

To show the prompt in a manner that would be visible.

**Comment by kyazdani42** [comment]
indeed, i think we have not yet migrated everthing to vim.ui, see #1294
