### ISSUE TITLE
Blocking pop-up notifications when creating a folder/file

### ISSUE THREAD

**Issue by wintermonth2298** [kyazdani42/nvim-tree.lua#1448]
### Description

I press "a" to create a file/folder, type name, and then press enter.
After that i get a message at the bottom which says "[NimvTree] path/to/file was properly created. Press enter to continue". I have to press enter again to continue using nvim-tree. 

When i delete file/folder i get the same notification but i don't need to press enter to confirm it (this works correctly). 

### Neovim version

```text
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

Linux 5.15.55-1-lts

### nvim-tree version

08ab346

### Minimal config

```lua
Behavior is reproduced with a standard config
```

### Steps to reproduce

1. open any file/folder in nvim
2. open nvim-tree
3. create file/directory with "a" hotkey

### Expected behavior

Don't wait for enter after notification pop-up

### Actual behavior

Have to press enter to confirm that i read notification

**Comment by Shougo** [comment]
I think you should set the config.

set cmdheight=2
