### ISSUE TITLE
Scp support

### ISSUE THREAD

**Issue by motephyr** [kyazdani42/nvim-tree.lua#145]
I really like the plugin to give us more fast file experience.
But It seems that only if I can use SCP to link remote server when I use netrw. 

Do we have any solution for SCP?

**Comment by kyazdani42** [comment]
Hi, there are no solutions for SCP and i might not want to support it. I would accept a PR that respects two conditions:
- code is well scoped and doesn't make it more spaghetti than it already is
- it doesn't slow down the local usage.

I'm not even sure how we would be able to use this over SCP though, so give it a go if you want :)

**Comment by motephyr** [comment]
I think remote file editing is a big project.

Later, I made some settings. Since Netrw does a good job of editing remote files, when I edit and browse remote files, I use Netrw, and I still use luatree on the local side.

Thank you for your reply!
