### ISSUE TITLE
Highlight most recent active buffer file

### ISSUE THREAD

**Issue by halafi** [kyazdani42/nvim-tree.lua#1451]
**Describe the solution you'd like**
It would be nice to see in the tree the file you are currently editing in an active buffer (the most recent active)

if that part of the tree would be collapsed then this would not be visible

**Comment by alex-courtis** [comment]
`:help nvim-tree.update_focused_file` shows the file you are currently editing. That does expand the tree to show that file. Is that an acceptable compromise?

An ideal solution might be an option `update_focused_file.expand` option, defaulting to true for current behaviour. This may require `update_root` disabled; further experimentation would be needed.

**Comment by kyazdani42** [comment]
This issue is about `update_focused_file`, closing :)
@alex-courtis i don't think we should add more specific behaviors for this feature, which might confuse people more than help them :)
