### ISSUE TITLE
LuaTreeFindFile positions cursor at the top

### ISSUE THREAD

**Issue by yujinyuz** [kyazdani42/nvim-tree.lua#146]
Cursor should be positioned to the current file opened and not the top

Exists on this commit ba4dac1e5904ddf91f3993bb9119d0487cb16a1d

**Comment by kyazdani42** [comment]
which top ? the tree window ?

**Comment by yujinyuz** [comment]
Here, the current file is `.vimrc` and the cursor points to `.vimrc` in the tree

![Screen Shot 2020-12-01 at 4 11 49 PM](https://user-images.githubusercontent.com/10972027/100713870-ec531400-33ef-11eb-94f6-a0b58a10b915.png)

But here, the cursor is at the top:

![Screen Shot 2020-12-01 at 4 11 12 PM](https://user-images.githubusercontent.com/10972027/100713940-0987e280-33f0-11eb-9051-4bfdd6da81ff.png)

**Comment by kyazdani42** [comment]
i cannot reproduce. can you `set debug=throw` and see if any error occurs ?

**Comment by yujinyuz** [comment]
I tried `:set debug=throw` and then `:LuaTreeFindFile`.

I'll try to see if it's an issue with other plugins. For now I just checked out in this commit: d3eb9cc because it has no errors

**Comment by katsika** [comment]
Just to quickly chime in. I can confirm that behaviour, `: LuaTreeFindFile` no longer positions cursor on file which it was called from. Also it does not change directory to git root but opens from `~` instead.

**Comment by yujinyuz** [comment]
Thanks for confirming @katsika . I don't have to check which plugins cause this :D

**Comment by kyazdani42** [comment]
`Also it does not change directory to git root but opens from ~ instead.` please elaborate i do not have any idea what is your issue here.
I'll take a look and see if it's easily fixable.

**Comment by kyazdani42** [comment]
@yujinyuz i have no idea how to reproduce this. the behavior is exactly the same on master and d3eb9cc on my machine(s).
Could you provide a better step by step way to reproduce your issue please ?

**Comment by kyazdani42** [comment]
oh and also can you give me a minimal config from which this issue can be reproduced ?

**Comment by katsika** [comment]
> `Also it does not change directory to git root but opens from ~ instead.` please elaborate i do not have any idea what is your issue here.

I think it's the same as https://github.com/kyazdani42/nvim-tree.lua/issues/124.

**Comment by yujinyuz** [comment]
```viml
set nocompatible hidden laststatus=2

if !filereadable('/tmp/plug.vim')
  silent !curl --insecure -fLo /tmp/plug.vim
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

source /tmp/plug.vim
call plug#begin('/tmp/plugged')
Plug 'kyazdani42/nvim-tree.lua'
call plug#end()

autocmd VimEnter * PlugClean! | PlugUpdate --sync | close

let g:lua_tree_width = 40 "30 by default
let g:lua_tree_follow = 1
let g:lua_tree_quit_on_open = 1
let g:lua_tree_indent_markers = 1

augroup LuaTree
  autocmd!
  autocmd FileType LuaTree setlocal signcolumn=no nowrap
augroup END


nnoremap <silent> <C-n> <cmd>LuaTreeToggle<CR>
```

[![asciicast](https://asciinema.org/a/6uHpfNZlJx4NRPiMf4yeWcMTV.svg)](https://asciinema.org/a/6uHpfNZlJx4NRPiMf4yeWcMTV)

**Comment by kyazdani42** [comment]
would have never understood that it was happening on open without this. Fixed
