### ISSUE TITLE
 Large indent level when indent_markers is enable

### ISSUE THREAD

**Issue by yamatsum** [kyazdani42/nvim-tree.lua#1460]
### Description

The indent level is large when indent_markers is enable with folder_arrow.
![CleanShot 2022-07-25 at 11 53 27](https://user-images.githubusercontent.com/42740055/180686233-37bf6c01-b018-4c26-822d-ca900cd12574.png)

Like the file tree on Github.com and neo-tree, it looks good to be indent at the arrow part
![CleanShot 2022-07-25 at 11 54 11](https://user-images.githubusercontent.com/42740055/180687392-938e6a9e-2709-4c83-a9be-fad5fb8e889f.png)
![CleanShot 2022-07-25 at 11 55 10](https://user-images.githubusercontent.com/42740055/180687422-79ca844f-0852-4714-9f21-b2a63fa163fc.png)

### Neovim version

```text
NVIM v0.8.0-dev-nightly-238-g1a655b71a
```

### Operating system and version

macOS 12.4

### nvim-tree version

master

### Minimal config

```lua
require("nvim-tree").setup({
  open_on_tab = true,
  update_cwd = true,
  update_focused_file = {
    enable = true,
    update_cwd = true,
  },
  respect_buf_cwd = true,
  git = {
    enable = false,
  },
  renderer = {
    root_folder_modifier = ":t",
    icons = {
      padding = "  ",
      show = {
        file = true,
        folder = true,
        folder_arrow = true,
      },
    },
    indent_markers = {
      enable = true,
    },
  },
})

```
```


### Steps to reproduce

1. set folder_arrow
2. set indent_markers

### Expected behavior

_No response_

### Actual behavior

_No response_

**Comment by alex-courtis** [comment]
That is working as intended.

You are welcome to attempt a change in behaviour. PRs are gratefully accepted.

**Comment by Shougo** [comment]
The indentation level seems same with neo-tree.

github.com uses half width separator instead of double width separator in nvim-tree.

**Comment by yamatsum** [comment]
Maybe my explanation was bad.
The claim is that the indent line should appear below the arrow, not below the directory icon (except at the end of the directory).

**Comment by alex-courtis** [comment]
> The claim is that the indent line should appear below the arrow, not below the directory icon (except at the end of the directory).

That change may be possible. As stated earlier, PRs are gratefully accepted.

**Comment by kyazdani42** [comment]
In neo-tree, it looks incorrect to me since there are indent markers that do not represent indent level under the arrows. Neo tree does show the right indent level under the folders.
