### ISSUE TITLE
Getting error on import API module: field < copy >

### ISSUE THREAD

**Issue by kevinm6** [kyazdani42/nvim-tree.lua#1461]
### Description

(First, great work on this plugin, I really like it and use everyday).

I tried to improve my `nvim-tree` config replacing some `nvim-tree.lib` with the relatives from the new `Api` module.
But on trying I’m always getting an error in import that module, specifically this [field copy in api](https://github.com/kyazdani42/nvim-tree.lua/blob/86b9da5ca52eb81f9869de853faf2b22d0a14987/lua/nvim-tree/api.lua#L40)!

> The error is : **attempt to index field copy (a function value)**

### Neovim version

```text
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Monterey
```

### Operating system and version

macOS 12.0.1

### nvim-tree version

86b9da5

### Minimal config

```lua
local ok, nvim_tree = pcall(require, "nvim-tree")
if not ok then return end

local api = require "nvim-tree.api"

local function trash_file()
  local node = api.get_node_under_cursor()

  -- code
  api.tree.reload()
end

local function vsplit_preview()
  local node = api.get_node_under_cursor()

  if node.link_to and not node.nodes then
    api.tree.open(node.link_to)
  else
    api.tree.open(node.absolute_path)
  end
  api.tree.focus()
end
```

### Steps to reproduce

nvim

**Comment by kevinm6** [comment]
I’ve just try to fix-it myself checking the `api module` and the functions calls and I think I get the problem:
 
```lua
local Api = {
  tree = {},
  node = { navigate = { sibling = {}, git = {}, diagnostics = {} }, run = {}, open = {} },
  events = {},
  marks = { bulk = {}, navigate = {} },
  fs = { copy = {} },
  git = {},
  live_filter = {},
}
```

here `copy` is a table and is being populate by some of `Api.fs` calls like:
```lua
Api.fs.copy = inject_node(require("nvim-tree.actions.fs.copy-paste").copy)
Api.fs.cut = inject_node(require("nvim-tree.actions.fs.copy-paste").cut)
Api.fs.paste = inject_node(require("nvim-tree.actions.fs.copy-paste").paste)
Api.fs.print_clipboard = require("nvim-tree.actions.fs.copy-paste").print_clipboard
Api.fs.copy.absolute_path = inject_node(require("nvim-tree.actions.fs.copy-paste").copy_absolute_path)
Api.fs.copy.filename = inject_node(require("nvim-tree.actions.fs.copy-paste").copy_filename)
Api.fs.copy.relative_path = inject_node(require("nvim-tree.actions.fs.copy-paste").copy_path)
```

but I think this 
`Api.fs.copy = inject_node(require("nvim-tree.actions.fs.copy-paste").copy)`
should be 
`Api.fs.copy.copy = inject_node(require("nvim-tree.actions.fs.copy-paste").copy)`

**Comment by kyazdani42** [comment]
good catch :) thanks. You can use `copy.name` now.

**Comment by kyazdani42** [comment]
@kevinm6 use copy.node instead of copy.name. Copy.name is actually already copy.filename.
