### ISSUE TITLE
watchers are refreshing indefinitely when using telescope on a large set of files

### ISSUE THREAD

**Issue by kyazdani42** [kyazdani42/nvim-tree.lua#1465]
### Description

https://user-images.githubusercontent.com/23156099/180972934-05a82ef8-eb2c-4a65-a906-940d4c3ab41d.mp4

### Neovim version

```text
latest master
```

### Operating system and version

nixos 22.05

### nvim-tree version

latest master

### Minimal config

```lua
-
```

### Steps to reproduce

- open nvim-tree in the root
- open telescope find_files
- wait a few seconds
- close telescope
- observe the cursor blinking

### Expected behavior

There should be no refresh since no files are modified

-> to note: telescope or the underlying programs must do something to the filesystem since i could not reproduce in other folders.

### Actual behavior

-

**Comment by kyazdani42** [comment]
@alex-courtis, this is not urgent, i'm leaving that here so we can investigate further, i could not reproduce in other folders on my system.
Also this might be related to nix.

**Comment by alex-courtis** [comment]
That's no good... it would be great if you could enable profile and watcher logs.

It could be the watchers or the debouncer that is misbehaving.

**Comment by kyazdani42** [comment]
Not sure why but seems to be related to the /dev folder. 
`/dev/input` and `/dev/pts/%d` trigger a lot of events.
seems to be happening without telescope, when opening the /dev folder it happens immediately.

**Comment by kyazdani42** [comment]
But i think this is to be expected.
/dev/pts are console device files, and /dev/input is holding event files for input devices.
Should we avoid binding to the /dev filesystem at all ?

**Comment by alex-courtis** [comment]
> But i think this is to be expected. /dev/pts are console device files, and /dev/input is holding event files for input devices. Should we avoid binding to the /dev filesystem at all ?

That is sensible. `/sys` and `/proc` too.
