### ISSUE TITLE
disable icons

### ISSUE THREAD

**Issue by spelb** [kyazdani42/nvim-tree.lua#1469]
Hi ,  I don't use icons . Tell me a way to disable them all. Thanks

**Comment by kyazdani42** [comment]
please read `:help nvim-tree.renderer.icons.show`

**Comment by spelb** [comment]
It gives me error. Please tell me by command to disable them. If each icons is to be disabled by commands for each like for git and files then just reply with command to disble file icons and I will get the idea. Thanks 
I already read the documentation and sorry I am not able to understand.
![46](https://user-images.githubusercontent.com/108426549/181240559-4847ce62-2b2e-4e10-9177-2272d1778732.png)

**Comment by spelb** [comment]
> please read `:help nvim-tree.renderer.icons.show`

..

**Comment by kyazdani42** [comment]
Please learn lua, it takes ~1hour to get the basic. 
the setup argument is a table. renderer is a table. within renderer, icons is a table.
so it's written `{ renderer = { icons = { show = false } } }`

**Comment by spelb** [comment]
Thank you so much and sorry for this but I solved the problem. 
![55](https://user-images.githubusercontent.com/108426549/181260534-a26e2b30-1b38-48d5-8f3d-340993627ddd.png)

**Comment by spelb** [comment]
> Please learn lua, it takes ~1hour to get the basic. the setup argument is a table. renderer is a table. within renderer, icons is a table. so it's written `{ renderer = { icons = { show = false } } }`

yes i will learn lua ..Thank you
