### ISSUE TITLE
After moving up and down the file tree with transparent background, the file name cannot be displayed

### ISSUE THREAD

**Issue by jicvi** [kyazdani42/nvim-tree.lua#1477]
**Is your feature request related to a problem? Please describe.**
normal display:
![2022-07-31_09-50](https://user-images.githubusercontent.com/14210650/182030053-2736dc6d-6a2f-43e4-b6b8-cf9bdbd2c901.png)

**Describe the solution you'd like**
Unable to display file：
![2022-07-31_09-50_1](https://user-images.githubusercontent.com/14210650/182030110-b387a1a6-1cfb-4539-b53f-6e5a1a75a8b7.png)

**Describe alternatives you've considered**

**Additional context**

**Comment by alex-courtis** [comment]
This looks like a bug that we can fix.

Please raise a [bug report](https://github.com/kyazdani42/nvim-tree.lua/issues/new?assignees=&labels=bug&template=bug_report.yml) with an nvt-min.lua that we can use to reproduce the problem.

**Comment by jicvi** [comment]
@alex-courtis 
ok
