### ISSUE TITLE
passing "s" to nvim-tree.remove_keymaps, but system_open still triggers.

### ISSUE THREAD

**Issue by angarc** [kyazdani42/nvim-tree.lua#1479]
### Description

`remove_keymaps` option not working as expected, or maybe I'm just not setting it right. I want to disable "s" key on nvim tree as I use it to switch between panes. But after using remove_keymaps option and passing "s" to it, system_open still gets invoked.

### Neovim version

```text
NVIM v0.7.0
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

macOS 12.4

### nvim-tree version

451901c

### Minimal config

```lua
use {
    'kyazdani42/nvim-tree.lua',
    requires = {
      'kyazdani42/nvim-web-devicons', -- optional, for file icon
    },
    config = function() require'nvim-tree'.setup {
      remove_keymaps = {"s"}
    } end
  }
```

### Steps to reproduce

I use the config mentioned above, and toggle nvim-tree and hit "s" on a file or directory.

### Expected behavior

For the system_open command to not run. In fact, it'd be nice if nvim-tree just didn't listen for "s" at all as it's interfering with another part of my config.

### Actual behavior

`system_open` still runs.

**Comment by alex-courtis** [comment]
Thanks for raising.

Please update to latest and advise if this is resolved.

**Comment by waldemarnt** [comment]
Just tested on latest and it's working again 🚀
