### ISSUE TITLE
Use `vim.ui.select` for selecting an option instead of `vim.ui.input`

### ISSUE THREAD

**Issue by nghialm269** [kyazdani42/nvim-tree.lua#1483]
**Is your feature request related to a problem? Please describe.**

https://github.com/kyazdani42/nvim-tree.lua/commit/8dc2144e878921111c75a942af6abed685e15c01 switched from `vim.ui.select` to `vim.ui.input`, which causes a problem for me: when the filename is too long, the title is truncated and I couldn't see the choices (y/n/r).

**Describe the solution you'd like**

I think using `vim.ui.select` is a better fit since in this case we're selecting an option rather than inputting something. If user doesn't happy with the UI/UX, they can override `vim.ui.select` instead.

**Additional context**
![image](https://user-images.githubusercontent.com/13317164/182387646-ac8d9197-c469-4082-94dc-6d91796df40c.png)

In this image, I'm copying and pasting a file into the same folder, `nvim-tree` prompts for overriding or renaming the file, but the title is truncated and I couldn't see the possible choices/what to enter.

**Comment by mosheavni** [comment]
I experience the same thing.
Very much needed.

**Comment by alex-courtis** [comment]
Resolved https://github.com/kyazdani42/nvim-tree.lua/commit/ac8d259badf915cd9aaad406503d116230296c44
