### ISSUE TITLE
Allow folders to not be sorted before files

### ISSUE THREAD

**Issue by npezza93** [kyazdani42/nvim-tree.lua#1490]
**Is your feature request related to a problem? Please describe.**
No problem

**Describe the solution you'd like**
I'd like a configuration option to not group folders before files and instead have them all listed alphabetactically. 
<img width="282" alt="image" src="https://user-images.githubusercontent.com/5059927/183291327-a7cfa7fa-08bb-4189-abe9-6dcbcffac530.png">

What it currently looks like
<img width="259" alt="image" src="https://user-images.githubusercontent.com/5059927/183291358-63c1134b-7ccf-4fed-b207-8b903b28d536.png">

**Describe alternatives you've considered**
N/A

**Additional context**
I didnt see a config option but let me know if imissed it!

**Comment by alex-courtis** [comment]
`sort_by` provides several sorting options however a directory option would not be appropriate, as it is orthogonal to the existing options.

An additional option like `sort_directories_first` would be appropriate.

PRs are very welcome.
