### ISSUE TITLE
git runner logging error during table concat with nil

### ISSUE THREAD

**Issue by AxLauri** [kyazdani42/nvim-tree.lua#1494]
### Description

When **git** option is enabled and the .gitconfig contains no value for status.showUntrackedFiles, an _invalid value (nil) at index 5 in table for 'concat'_ is encountered. This is worked around by adding an appropriate value to the .gitconfig for status.showUntrackedFiles. 

Appears this could be be resolved by handling the nil prior to loggingthis could be handled with a check for the _nil_ value in that table pri

### Neovim version

```text
NVIM v0.8.0-dev-699-gcbfae548e
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

### Operating system and version

Windows 10

### nvim-tree version

261a5c3

### Minimal config

```lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvt-min/site]]
local package_root = "/tmp/nvt-min/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup {
    {
      "wbthomason/packer.nvim",
      "kyazdani42/nvim-tree.lua",
      "kyazdani42/nvim-web-devicons",
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  }
end
if vim.fn.isdirectory(install_path) == 0 then
  print "Installing nvim-tree and dependencies."
  vim.fn.system { "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path }
end
load_plugins()
require("packer").sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua setup()]]
vim.opt.termguicolors = true
vim.opt.cursorline = true

-- MODIFY NVIM-TREE SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
_G.setup = function()
  require("nvim-tree").setup {
      git = {
        enable = true,
      }
  }
end
```

### Steps to reproduce

1. **.gitconfig** for cwd should have no entry for **status.showUntrackedFiles**
2. _nvim -nu /tmp/nvt-min.lua_
3. _:NvimTreeOpen_
4. Create new file within NvimTree

### Expected behavior

Expect NvimTree to open without error

### Actual behavior

**Encounter error:**

Error executing vim.schedule lua callback: ...\packer\start\nvim-tree.lua/lua/nvim-tree/git/runner.lua:89: invalid value (nil) at index 5 in table for 'concat'
stack traceback:
	[C]: in function 'concat'
	...\packer\start\nvim-tree.lua/lua/nvim-tree/git/runner.lua:89: in function '_run_git_job'
	...\packer\start\nvim-tree.lua/lua/nvim-tree/git/runner.lua:146: in function 'run'
	...ck\packer\start\nvim-tree.lua/lua/nvim-tree/git/init.lua:38: in function 'reload_project'
	...ker\start\nvim-tree.lua/lua/nvim-tree/explorer/watch.lua:10: in function 'reload_and_get_git_project'
	...ker\start\nvim-tree.lua/lua/nvim-tree/explorer/watch.lua:50: in function 'refresh_path'
	...ker\start\nvim-tree.lua/lua/nvim-tree/explorer/watch.lua:68: in function 'callback'
	...\pack\packer\start\nvim-tree.lua/lua/nvim-tree/utils.lua:358: in function <...\pack\packer\start\nvim-tree.lua/lua/nvim-tree/utils.lua:357>

**Comment by dlobue** [comment]
I'm running into this problem as well. Same version of nvim-tree.lua, but on macos. I'm not sure the specific setting `status.showUntrackedFiles` is related as I have this set to a valid value: `no`. The lines in my stacktrace differ as well:
```
Error executing vim.schedule lua callback: .../packer/start/nvim-tree.lua/lua/nvim-tree/git/runner.lua:87: invalid value (nil) at index 5 in tab
le for 'concat'
stack traceback:
        [C]: in function 'concat'
        .../packer/start/nvim-tree.lua/lua/nvim-tree/git/runner.lua:87: in function '_run_git_job'
        .../packer/start/nvim-tree.lua/lua/nvim-tree/git/runner.lua:144: in function 'run'
        ...ck/packer/start/nvim-tree.lua/lua/nvim-tree/git/init.lua:38: in function 'reload_project'
        ...ker/start/nvim-tree.lua/lua/nvim-tree/explorer/watch.lua:10: in function 'reload_and_get_git_project'
        ...ker/start/nvim-tree.lua/lua/nvim-tree/explorer/watch.lua:50: in function 'refresh_path'
        ...ker/start/nvim-tree.lua/lua/nvim-tree/explorer/watch.lua:68: in function 'callback'
        .../pack/packer/start/nvim-tree.lua/lua/nvim-tree/utils.lua:358: in function <.../pack/packer/start/nvim-tree.lua/lua/nvim-tree/utils.lu
a:357>
```

**Comment by AxLauri** [comment]
It looks like there are two issues:

1. **Git.Runner** attempts concatenation without accounting for nils.
2. **Git.Utils.should_show_untracked** is looking for a boolean value for _Status.showUntrackedFiles_.
     This error appears in the log

`[2022-08-12 23:38:45] [git] git -C C:\dev\external\nvim-tree.lua config --type=bool status.showUntrackedFiles
fatal: bad boolean config value 'normal' for 'status.showuntrackedfiles'
`
I created a pull request with changes that worked for me.
