### ISSUE TITLE
NvimTree opening document on the wrong side

### ISSUE THREAD

**Issue by lockieluke** [kyazdani42/nvim-tree.lua#1497]
### Discussed in https://github.com/kyazdani42/nvim-tree.lua/discussions/1496

<div type='discussions-op-text'>

<sup>Originally posted by **lockieluke** August 10, 2022</sup>
https://user-images.githubusercontent.com/25424409/183872555-f5b3ae01-252c-46cd-af84-f9d9aae00ade.mov

nvim tree is vspliting the first document on the wrong side, it would be working correctly again after opening the first document</div>

**Comment by alex-courtis** [comment]
Please raise a [bug](https://github.com/kyazdani42/nvim-tree.lua/issues/new?assignees=&labels=bug&template=bug_report.yml) with a minimal config so that we may reproduce.

**Comment by alex-courtis** [comment]
Duplicate #1626, following there.
