### ISSUE TITLE
Default icon

### ISSUE THREAD

**Issue by romgrk** [kyazdani42/nvim-tree.lua#15]
Would it be possible to add a default icon so that files that don't match any filetype/filename icon are aligned at the same level as the rest?

![Screenshot from 2020-05-22 00-14-37](https://user-images.githubusercontent.com/1423607/82630566-0e5a1700-9bc1-11ea-8624-b9796e7fa4f1.png)

**Comment by kyazdani42** [comment]
Hi.
Well i prefer not having icons on unknown filetypes, so i might just add an option for that. I'll add that in the refactoring though, in the meantime, you can edit `lua/lib/format.lua` and comment line 58, this will fix this issue.
