### ISSUE TITLE
Feature Request (?) - Padding to the left/right window border

### ISSUE THREAD

**Issue by weilbith** [kyazdani42/nvim-tree.lua#150]
Hey,
the question is simple and the title basically states it. For me who opens the window on the left side (default) the content of the tree is sticking to the left edge of the window. This is a bit annoying. Is it already possible to change this? Or should I use trick like a ftplugin with a forced sign column or so?

**Comment by kyazdani42** [comment]
hum i think padding should be done by the terminal and not the programs inside it. There is not way to add padding to a nvim window so i don't think i should add support for that sorry.

**Comment by kyazdani42** [comment]
i've added signcolumn=yes to the window options, could you tell me if it resolves this issue ?

**Comment by marioortizmanero** [comment]
@kyazdani42 This apparently doesn't work right now:

![image](https://user-images.githubusercontent.com/25647296/117048083-e6e95500-ad12-11eb-8a37-53782032167d.png)

It should be like this:

![image](https://user-images.githubusercontent.com/25647296/117048127-f23c8080-ad12-11eb-9e0a-a53874b7529f.png)


If I manually use `:set signcolumn` after opening nvim-tree I do get rid of the extra column. But this doesn't work by default nor when I use something like `autocmd FileType NvimTree set signcolumn=no`.

So there's probably something else setting it to `yes`... But I've managed to reproduce this with a clean install, so I don't know what it could be.
