### ISSUE TITLE
Update_focused_file.update_root acting incorrectly for window working directory

### ISSUE THREAD

**Issue by alexisgeoffrey** [kyazdani42/nvim-tree.lua#1503]
### Description

Background - I have the following options enabled:

- `sync_root_with_cwd = true`
- `update_focused_file = {
    enable = true,
    update_root = true,
    ignore_list = {'help'}
  }`

Scenario: 
1. I have a single tab with 1 file open, where the window `lcd` is set to a certain directory.
2. I open another window with `:new` and open a file in a different directory.
3. I use :NvimTreeToggle to open nvim-tree and see that the root is set to the correct directory of the file that I just opened.
4. Within the window of the new file, I `:lcd ..` to one level up. Again, nvim-tree is updated properly.
5. If I then close and reopen nvim-tree two times with :NvimTreeToggle, then the root is updated to the direct parent directory of the file, which seems to contradict the intended behavior of `Update_focused_file.update_root`.

This does not happen when changing focus between two windows. The root of nvim-tree is properly updated without resetting directly to the parent directory of the second file. Also, it seems like it has to be the bottom window in the layout for it to reset. It doesn't happen with the top one.

### Neovim version

```text
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@HMBRW-A-001-M1-004.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.7.2_1/share/nvim"

Run :checkhealth for more info
```

### Operating system and version

macOS 12.5

### nvim-tree version

1685484

### Minimal config

```lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvt-min/site]]
local package_root = "/tmp/nvt-min/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup {
    {
      "wbthomason/packer.nvim",
      "kyazdani42/nvim-tree.lua",
      "kyazdani42/nvim-web-devicons",
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  }
end
if vim.fn.isdirectory(install_path) == 0 then
  print "Installing nvim-tree and dependencies."
  vim.fn.system { "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path }
end
load_plugins()
require("packer").sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua setup()]]
vim.opt.termguicolors = true
vim.opt.cursorline = true

-- MODIFY NVIM-TREE SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
_G.setup = function()
  require("nvim-tree").setup {
    sync_root_with_cwd = true,
    update_focused_file = {
      enable = true,
      update_root = true,
      ignore_list = {'help'}
    }
  }
end
```

### Steps to reproduce

1. Open a file in Nvim.
2. Do `:new`
3. Open a file in a different directory in the second window.
4. Do `:lcd ..`
5. Execute `:NvimTreeToggle` twice.
6. See the root of nvim-tree reset to the parent of the lower file.

### Expected behavior

The root should not reset to the parent directory because according to the description of `update_focused_file.update_root`, It should only `Update the root directory of the tree if the file is not under current
    root directory.`

### Actual behavior

After toggling nvim-tree a few times, the root is updated to the containing directory of the file.

**Comment by alexisgeoffrey** [comment]
After looking through the code for a little, I saw: https://github.com/kyazdani42/nvim-tree.lua/blob/master/lua/nvim-tree/view.lua#L189-L199
```lua
  for _, win in pairs(a.nvim_list_wins()) do
    if tree_win ~= win and a.nvim_win_get_config(win).relative == "" then
      a.nvim_win_close(tree_win, true)
      local prev_win = vim.fn.winnr "#" -- this tab only
      if tree_win == current_win and prev_win > 0 then
        a.nvim_set_current_win(vim.fn.win_getid(prev_win))
      end
      events._dispatch_on_tree_close()
      return
    end
  end
```

I'm not very experienced with nvim plugin development so correct me if I'm wrong, but it seems like when closing nvim-tree, the nvim-tree window is closed first, and then the current window is set to the previous one. 

Should this instead set the current window to the previous one, and then close nvim-tree's window? 

This was what I was thinking could be why it happens for the lower window but not the upper window, because when toggling back to the lower window, nvim-tree closing sets the current window to the upper one for a brief moment, and then nvim_set_current_win sets it to the lower one.

**Comment by alex-courtis** [comment]
A quick experiment under `nvim --clean` confirms this behaviour. When closing a window via `<C-w>c` it focuses the top, even if the previous window `<C-w>p` was the bottom.

Your analysis is great. Raised #1509
