### ISSUE TITLE
'paste' does not work when a file is copied to buffer

### ISSUE THREAD

**Issue by brymon68** [kyazdani42/nvim-tree.lua#1507]
### Description

When copying a file within nvim-tree, and then pasting said file, I am prompted to provide a new name for the file (as expected). However, when hitting enter, the file is not pasted / created. 

### Neovim version

```text
NVIM v0.8.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

### Operating system and version

macOS 12.5 - M1 Pro

### nvim-tree version

master

### Minimal config

lua
local status_ok, nvim_tree = pcall(require, "nvim-tree")

if not status_ok then
    return
end

nvim_tree.setup()

### Steps to reproduce

1. nvim
2. ```:NvimTreeOpen```
3. Hover over file in tree
4. ```c``` <--- to copy file
5. ```p``` <--- to paste file
6. Rename file to unique name
7. File is not created

### Expected behavior

I should be able to write a new file after providing new name 

### Actual behavior

File is not created . See attached

https://user-images.githubusercontent.com/8397405/184511533-deb37262-f53a-448d-bc7a-2a5d011cd9c8.mp4

**Comment by alex-courtis** [comment]
That appears to be a bug.

You have some customisation going there, including the popup dialogue.

Please provide a standalone [`nvt-min.lua`](https://github.com/kyazdani42/nvim-tree.lua/issues/new?assignees=&labels=bug&template=bug_report.yml) so that we may reproduce.

**Comment by brymon68** [comment]
Yeah this is definitely fault on my end. Resolving

**Comment by alex-courtis** [comment]
> Yeah this is definitely fault on my end. Resolving

Please let us know the cause for future users experiencing the same issue.

**Comment by asmodeus812** [comment]
I am also facing the same issue, the problem is before i did sync the plugin in was working fine, now all of a sudden paste stopped working as well, nothing happens when you do "p"

**Comment by alex-courtis** [comment]
> I am also facing the same issue, the problem is before i did sync the plugin in was working fine, now all of a sudden paste stopped working as well, nothing happens when you do "p"

What customisation and plugins are you running in addition to nvim-tree? This problem appears to be some interference from outside nvim-tree.

Please raise a [bug report](https://github.com/kyazdani42/nvim-tree.lua/issues/new?assignees=&labels=bug&template=bug_report.yml) with an nvt-min.lua that we may use to replicate.

**Comment by curious-toast** [comment]
For me, I had a conflict with dressing.nvim. Posting incase someone else runs into this.

Added
```
require("dressing").setup({
  input = {
    override = function(opt)
      if vim.api.nvim_buf_get_option(0, "filetype") == "NvimTree" then
        opt.anchor = "SW"
        opt.col = 1
        opt.row = vim.o.lines - vim.o.cmdheight - 1
        opt.relative = "editor"
      end
    end,
  },
})
```

See here.
https://github.com/stevearc/dressing.nvim/issues/29

**Comment by alex-courtis** [comment]
Thanks for the update @curious-toast

**Comment by brymon68** [comment]
I can confirm my update was getting rid of dressing as well @alex-courtis

**Comment by alex-courtis** [comment]
Thank you @brymon68
