### ISSUE TITLE
Feature Request - Color file names as icon

### ISSUE THREAD

**Issue by weilbith** [kyazdani42/nvim-tree.lua#151]
Hi :upside_down_face: 
On the terminal many people use `LS_COLORS` to color their `ls` output based on the file type. Here we have a icon based on the filetype which includes a custom color. What do you think about extending this color the full name of the file? According to the help doc file there are a couple of additional highlight groups for certain filetypes. Is that necessary? :thinking:

**Comment by kyazdani42** [comment]
> What do you think about extending this color the full name of the file
not sure what you mean here.
When i started this plugin, i wanted to use the lscolors, but at the end i didn't really wanted to have that much colors. Also the icons are highlighted with nvim-web-devicons so maybe this request should go there.
I didn't really clean up the docs for quite a long time so there might be some unecessary stuff, but i think most of it is still up to date.

**Comment by weilbith** [comment]
Okay I you think it is too colorful, than thats how it is. I thought it would look nice as in the console. :shrug:

**Comment by phanen** [comment]
<img src="https://github.com/user-attachments/assets/ba04b92c-b70a-4cb3-b928-946cc5b567ac" align="right" width=20%>

I prefer the way like `LS_COLORS` instead of prepending a icons. It's easy to make nvim-tree behave like that. For anyone who is interesting, you can use the following patch (for lazy.nvim user, this can be convenient with https://github.com/polirritmico/lazy-local-patcher.nvim).

```diff
diff --git a/lua/nvim-tree/renderer/builder.lua b/lua/nvim-tree/renderer/builder.lua
index e08eb9e..6bd1067 100644
--- a/lua/nvim-tree/renderer/builder.lua
+++ b/lua/nvim-tree/renderer/builder.lua
@@ -288,6 +288,15 @@ function Builder:build_line(node, idx, num_children)
 
   -- decorated node icon and name
   local icon, name = self:icon_name_decorated(node)
+  icon.str = ''
+  if name.hl[1] == 'NvimTreeOpenedFolderName' then
+    name.str = name.str .. '/'
+    name.hl = { 'NvimTreeRootFolder' }
+  elseif name.hl[1] == 'NvimTreeFolderName' then
+    name.hl = { 'NvimTreeRootFolder' }
+  else
+    name.hl = icon.hl
+  end
 
   local line = self:format_line(indent_markers, arrows, icon, name, node)
   table.insert(self.lines, self:unwrap_highlighted_strings(line))
```

**Comment by alex-courtis** [comment]
> For anyone who is interesting, you can use the following patch (for lazy.nvim user, this can be convenient with https://github.com/polirritmico/lazy-local-patcher.nvim).

Very nice! You can now implement your own [Decorator](https://github.com/nvim-tree/nvim-tree.lua/wiki/Decorators) to achieve that functionality, without the need for patching.
