### ISSUE TITLE
NvimtreeFindFileToggle when triggered from keybinding doesn't close split on second trigger

### ISSUE THREAD

**Issue by benwainwright** [kyazdani42/nvim-tree.lua#1513]
### Description

I have `NvimTreeFindFileToggle` mapped to `<C-e>`

- When I trigger it once, it works as expected.
- The second time it is triggered, the NvimTree split **remains open**, but the split reverts back to the file that is open in the other split

Curiously, I ONLY get this behaviour when triggering the command via keymap. If I manually trigger the command by typing it into command mode, it works as expected.

### Neovim version

```text
NVIM v0.7.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Monterey

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.7.0/share/nvim"

Run :checkhealth for more info
```

### Operating system and version

MacOS Monterey 12.4 Beta (21F5071b)

### nvim-tree version

261a5c3

### Minimal config

```lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvt-min/site]]
local package_root = "/tmp/nvt-min/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup {
    {
      "wbthomason/packer.nvim",
      "kyazdani42/nvim-tree.lua",
      "kyazdani42/nvim-web-devicons",
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  }
end
if vim.fn.isdirectory(install_path) == 0 then
  print "Installing nvim-tree and dependencies."
  vim.fn.system { "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path }
end
load_plugins()
require("packer").sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua setup()]]
vim.opt.termguicolors = true
vim.opt.cursorline = true

_G.setup = function()
  require("nvim-tree").setup {}
  vim.api.nvim_set_keymap('n', '<C-e>', '<cmd>NvimTreeFindFileToggle<CR>', { noremap = true })
end
```

### Steps to reproduce

1. nvim -nu nvt-min.lua
2. :e <a file in your current directory>
3. Press <C-e>
4. Press <C-e> again

### Expected behavior

On step 4, the nvimtree split should close

### Actual behavior

On step 4, the nvimtree split remains open and contains the contents of the file you were editing in the other split

**Comment by alex-courtis** [comment]
`<c-e>` is bound to the `edit_in_place` action by default. See `:help nvim-tree-default-mappings`.

Unmap it by setting `action = ""`.
