### ISSUE TITLE
Segmentation fault (core dumped) when opening files in the nvim-tree which is the last window

### ISSUE THREAD

**Issue by BreakingLead** [kyazdani42/nvim-tree.lua#1516]
### Description

Segmentation fault (core dumped) when opening files in the nvim-tree which is the last window. Sorry for the bad English xD.

### Neovim version

```text
NVIM v0.8.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

### Operating system and version

Linux 5.15.60-1-lts(arch)

### nvim-tree version

09a5126

### Minimal config

```lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvt-min/site]]
local package_root = "/tmp/nvt-min/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup {
    {
      "wbthomason/packer.nvim",
      "kyazdani42/nvim-tree.lua",
      "kyazdani42/nvim-web-devicons",
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  }
end
if vim.fn.isdirectory(install_path) == 0 then
  print "Installing nvim-tree and dependencies."
  vim.fn.system { "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path }
end
load_plugins()
require("packer").sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua setup()]]
vim.opt.termguicolors = true
vim.opt.cursorline = true

-- MODIFY NVIM-TREE SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
_G.setup = function()
  require("nvim-tree").setup {}
end
```

### Steps to reproduce

1. `nvim -nu /tmp/nvt-min.lua`
2. `:NvimTreeToggle`
3. Open some file
4. Delete the file window (Input `:q`)
5. Now there's only nvimtree window, and open any file arbitrarily.
6. Segmentation fault (core dumped)

### Expected behavior

Create a new window when opening some files in the nvim-tree window which is the last window.
Or is there any way to retain a window when input `:q`?
#413 seems not useful to me.
Thanks for the best file explorer plugin in neovim:)

**Comment by alex-courtis** [comment]
Could not reproduce with:

```
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
```

nor a neovim build from `1a57cd383`

```
NVIM v0.8.0-dev-896-g1a57cd383-dirty
Build type: Debug
LuaJIT 2.1.0-beta3
```

Please try using a stable 0.7 neovim.

**Comment by BreakingLead** [comment]
After I tried stable neovim, the problem disappeared, thanks^_^.
