### ISSUE TITLE
Unrecognized git state " A"

### ISSUE THREAD

**Issue by kutsan** [kyazdani42/nvim-tree.lua#152]
After adding a file with `git add --intent-to-add <file>` I started to get the error below.

```
[LuaTree] Unrecognized git state " A". Please open up an issue on https://github.com/kyazdani42/nvim-tree.lua/issues with this
message.
```

**Comment by kyazdani42** [comment]
indeed i do not handle these states. How do you think we should represent that ?
from the docs: 
```
                    [AMD]   not updated
```

**Comment by kyazdani42** [comment]
Mmmmh i did not know about this but it seems this add the file to the git unstaged changes, so maybe we should show this as a new icon but with a red color

**Comment by kyazdani42** [comment]
fixed in master !

**Comment by kutsan** [comment]
Thanks but they should be under same highlight group as modified but unstaged files. I guess it's `LuaTreeGitDirty` in this case.

**Comment by kyazdani42** [comment]
i'm might rethink the whole git display now that i understand this git porcelain format better. I'll keep it as it is for now
