### ISSUE TITLE
Not showing changes immideatly

### ISSUE THREAD

**Issue by Abh15h3k** [kyazdani42/nvim-tree.lua#1540]
### Description

Any newly created files or folders.
Deleted files
don't show till manually refreshed.

https://user-images.githubusercontent.com/40197742/185981394-a540e0d9-5f7b-4408-a58b-841b1d2197ae.mov

this seems to be only happening when in inside any folder with path `/home/abhishek/Documents/git/<folder>`
other paths like `/home/abhishek/Documents/<anything-but-git>/<folder>`

edit 1: specifically for folders inside `git` folder. if i rename that folder to `Git` works fine
edit 2: the issue is happening in any folder inside a folder that ends with `git` (all lowercase)

### Neovim version

```text
NVIM v0.8.0-dev-917-gbaaaa1f2b3
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

### Operating system and version

Arch Linux 5.19.2-arch1-1

### nvim-tree version

e3353c4

### Minimal config

```lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvt-min/site]]
local package_root = "/tmp/nvt-min/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup {
    {
      "wbthomason/packer.nvim",
      "kyazdani42/nvim-tree.lua",
      "kyazdani42/nvim-web-devicons",
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  }
end
if vim.fn.isdirectory(install_path) == 0 then
  print "Installing nvim-tree and dependencies."
  vim.fn.system { "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path }
end
load_plugins()
require("packer").sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua setup()]]
vim.opt.termguicolors = true
vim.opt.cursorline = true

-- MODIFY NVIM-TREE SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
_G.setup = function()
  require("nvim-tree").setup {}
end
```

### Steps to reproduce

mkdir ${HOME}/Documents/git/nvim-tree-test-folder -p
cd ${HOME}/Documents/git/nvim-tree-test-folder
nvim -nu /tmp/nvt-min.lua

create/edit/delete files and folder

### Expected behavior

nvim-tree auto refreshes and shows created/edited/(doesn't show)deleted files and folder

### Actual behavior

have to manually refresh nvim-tree

**Comment by alex-courtis** [comment]
Fixed on master. Please update and test test test.

**Comment by alex-courtis** [comment]
Optimistically closing. Please reopen if further problems occur.
