### ISSUE TITLE
show the last part of a long root folder

### ISSUE THREAD

**Issue by minusf** [kyazdani42/nvim-tree.lua#1544]
**Is your feature request related to a problem? Please describe.**
when the root (top) folder is a long pathname (e.g. `/Volumes/work_projects/client_name/some_project/`), with a 30ish window width all i can see in the top line is `/Volumes/work_projects/client_name/som`.

**Describe the solution you'd like**
I'd like to see `/Volumes/.../client_name/some_project/` or `...k_projects/client_name/some_project/`, etc.

**Comment by alex-courtis** [comment]
Bug.

Definitely fix: when `renderer.full_name` is set, the too-long names show on hover. This does not occur for the root.

Maybe fix (will change behaviour): `actions.open_file.resize_window` and `view.adaptive_size` do not account for the root.

**Comment by alex-courtis** [comment]
related #1596

**Comment by alex-courtis** [comment]
Tracked in #1596
