### ISSUE TITLE
`hijack_unnamed_buffer_when_opening` should open NvimTree automatically after closing last buffer

### ISSUE THREAD

**Issue by cpea2506** [kyazdani42/nvim-tree.lua#1560]
**Is your feature request related to a problem? Please describe.**

I remember in some ancient commits of this project, whenever a `[No Name]` buffer appears, it should automatically open `NvimTree` instead of having to run `NvimTreeOpen` by hand.

**Describe the solution you'd like**

`NvimTree` should automatically hijack `[No Name]` buffer whenever it opens.

**Describe alternatives you've considered**

We could have a table like `hijack_directories`, so we can decide when it should automatically open:

```lua
hijack_unamed_buffer = {
 enable = false, -- enable this option
 auto_open = false -- should auto open nvimtree on `unnamed_buffer`
}
```

Thanks for you concern!

**Comment by alex-courtis** [comment]
Testing in a minimal configuration showed that the unnamed buffer is successfully hijacked when opening nvim with no arguments:

```lua
    hijack_unnamed_buffer_when_opening = true,
    open_on_setup = true,
```

Does that satisfy your use case?

I'll update the documentation if so, specifying that `open_on_setup` is required for `hijack_unnamed_buffer_when_opening`.

**Comment by cpea2506** [comment]
Sorry for not being more specific. I want the Tree to be opened when I close last active buffer instead of `[No Name]` buffer after that.

https://user-images.githubusercontent.com/42694704/187119502-6bbe05c7-ab38-4862-b86d-cbe2b5a6d063.mov

**Comment by alex-courtis** [comment]
I see. That would prevent the user from starting a new buffer via, say, `:enew` as it would immediately be hijacked.

This behaviour would cause problems when other plugins or automations create noname buffers that they then populate: &ft and &buftype cannot be set until after the buffer is created.

I'm sorry but we can't implement this functionality. You could try implementing this yourself however I think you will run into difficulties with nvim-tree itself getting into an infinite loop.

**Comment by cpea2506** [comment]
Ah, I see! I think it could be easily achieved with an autocommand. 

Thanks for your response and enthusiastic help.
