### ISSUE TITLE
Support copying directories recursively from one repo to another

### ISSUE THREAD

**Issue by jgarciaokode** [kyazdani42/nvim-tree.lua#1567]
**Describe the solution you'd like**
When you press c or y in nvimtree in one repo and then switch to another one, i expect the directories are pasted in the new repository

<img width="1905" alt="image" src="https://user-images.githubusercontent.com/79897391/187615845-7a8f8ea9-dbdd-4465-9437-5c0d2c40644a.png">

**Comment by alex-courtis** [comment]
> in nvimtree in one repo and then switch to another one

Do you mean multiple nvim instances?

See #1549

**Comment by jgarciaokode** [comment]
That's right, i close this since it is a duplicate
