### ISSUE TITLE
Could not start the fs_event watcher for path ?

### ISSUE THREAD

**Issue by Frey1a** [kyazdani42/nvim-tree.lua#1586]
### Description

![image](https://user-images.githubusercontent.com/78993276/188908656-8c150cce-22f1-4619-bd41-2db15a90394f.png)

### Neovim version

```text
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser
```

### Operating system and version

5.19.4-arch1-1 

### nvim-tree version

3e49d9b

### Minimal config

```lua
normal
```

### Steps to reproduce

normal

### Expected behavior

Show git icon

**Comment by gegoune** [comment]
This bug report is utterly useless. Did you even try to use minimal configs?

**Comment by Frey1a** [comment]
> This bug report is utterly useless. Did you even try to use minimal configs?

I tried with minimal configuration but it's completely normal.  Thank you!

**Comment by Frey1a** [comment]
I don't understand why my path has such strange characters. That stops it from running .git

**Comment by alex-courtis** [comment]
This bug report is incomplete. Please do not raise a report like this in the future.

Please reproduce with a minimal configuration and post logs as per https://github.com/kyazdani42/nvim-tree.lua#troubleshooting
