### ISSUE TITLE
weird dotted line 

### ISSUE THREAD

**Issue by siduck76** [kyazdani42/nvim-tree.lua#159]
I see this weird blue dotted line on the left of the  tree indentline and even persists after I close it .
![image](https://user-images.githubusercontent.com/59060246/102246199-7d63d800-3f24-11eb-94a6-1625b7a4c816.png)
![image](https://user-images.githubusercontent.com/59060246/102246858-388c7100-3f25-11eb-92bd-ff0f210fd57d.png)

**Comment by kyazdani42** [comment]
not sure why this would happen in the plugin. might be something to do with your nvim window configurations.

**Comment by siduck76** [comment]
this just happened with this filetree tho . defx and nerdtree worked fine

**Comment by akinsho** [comment]
@siduck76 try disabling foldcolumn and signcolumn in the tree buffer your config or theme might include some highlights for those

**Comment by siduck76** [comment]
that didnt work and this just happens when the terminal's maximized https://www.youtube.com/watch?v=57avmRqmHOU

**Comment by kyazdani42** [comment]
this might be something to do with your colorscheme or your terminal, i cannot reproduce this

**Comment by siduck76** [comment]
PlugUpdate fixed everything , thanks
