### ISSUE TITLE
NvimTreeFindFile cannot navigate to different directory trees

### ISSUE THREAD

**Issue by antoineco** [kyazdani42/nvim-tree.lua#1590]
### Description

With a file open in `:pwd`, opening another file in a different directory tree (different part of the file system) then executing `:NvimTreeFindFile` causes nvim-tree to remain in the current directory instead of locating the open file.

For example, if current `:pwd` is `/home/alice/git/myproject` and I open a file in `/usr/local/go/src/strings/builder.go` (with `:e` or any other action such as `gd`), then `:NvimTreeFindFile` inside that file, nvim-tree remains in `/home/alice/git/myproject` and doesn't locate the file I'm editing.

### Neovim version

```text
NVIM v0.8.0-dev-1092-g89b9eab63
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

### Operating system and version

Ubuntu 22.04

### nvim-tree version

fb8735e

### Minimal config

```lua
require'nvim-tree'.setup()
```

### Steps to reproduce

1. `$ cd $HOME`
1. `$ nvim`
1. `:e /etc/os-release`
1. `:NvimTreeFindFile`

### Expected behavior

![image](https://user-images.githubusercontent.com/3299086/190339236-377eeeab-d9d9-4c0f-aa5b-da08f89da88b.png)

### Actual behavior

![image](https://user-images.githubusercontent.com/3299086/190339058-45e0d5e0-db83-4f6d-ab53-7771924eeb58.png)

**Comment by alex-courtis** [comment]
You can set `:help nvim-tree.update_focused_file.update_root` to achieve your desired behaviour.

**Comment by antoineco** [comment]
Looks like it indeed, thanks for the hint.

This is a surprising default to me though. In any IDE, "locate file" navigates to the actual location of the file. The user doesn't have to think about where `cwd` is rooted, the file explorer _just works_. In the Vim world, NERDTree does this correctly too.

If there is no plan to change that behavior, I would at least mention the dependency on that setting in the help of the `NvimTreeFindFile` command.

**Comment by rebelot** [comment]
what is the point of `NvimTreeFindFile` then? when `update_focused_file` and `update_root` are enabled the behavior is the same. I would have imaginded `NvimTreeFindFile` to "just work" regardless of user settings.

**Comment by alex-courtis** [comment]
> Looks like it indeed, thanks for the hint.
> 
> This is a surprising default to me though. In any IDE, "locate file" navigates to the actual location of the file. The user doesn't have to think about where `cwd` is rooted, the file explorer _just works_. In the Vim world, NERDTree does this correctly too.
> 
> If there is no plan to change that behavior, I would at least mention the dependency on the `update_root` setting in the help of the `NvimTreeFindFile` command.

`update_root` changing the root even with `update_focused_file` disabled is a "happy accident" and was not intended behaviour.

Raised #1593 to allow for more explicit behaviour.

**Comment by alex-courtis** [comment]
> what is the point of `NvimTreeFindFile` then? when `update_focused_file` and `update_root` are enabled the behavior is the same. 

`NvimTreeFindFile` will find the file within the tree's root. Users don't tend to use `NvimTreeFindFile` with `update_focused_file`.

> I would have imaginded `NvimTreeFindFile` to "just work" regardless of user settings.

> Also, `NvimTreeFindFile` should _not_ try to change the current working directory, either locally or globally.

Thank you for your feedback.

> I think that the directory focused by `NvimTree` and the actual local/global `cwd` should always be separate concepts: users will have some mappings to reconcile the two, eg: `C` will change global cwd to NvimTree root and `gc` will change NvimTree root to global cwd.

The functionality to change directories is present and desirable to some users.

There are many options to change this behaviour:
`:help nvim-tree.sync_root_with_cwd`
`:help nvim-tree.respect_buf_cwd`
`:help nvim-tree.actions.change_dir`

You may tweak these options to suit your preferences.

If the current options do not meet your use cases, you may raise a feature request, describing the exact behaviour you desire. Examples should be provided, describing the current and proposed behaviour for each. Please note that existing behaviour will not be changed, so as not to disrupt existing user's experience. Any proposed changes must be behind a new option.

> `update_root` is not a "sane" default, as it makes it impossible to freeze the tree view on some relevant directory Use case:
> 
> * I have global cwd on a project
> * I open a recent file not in the project dir
> * I need to view some siblings of that external file and run `NvimTreeFindFile`

`update_focused_file.enable` and `update_focused_file.update_root` are not enabled by default.

Those options result in a very different user experience that is desirable by a subset of users.

Please see https://github.com/kyazdani42/nvim-tree.lua/issues/1590#issuecomment-1250532763

> * Now, provided I have set `update_root` to `true`, the tree has changed, however, if the external file is open in a vertical split window not adjacent to NvimTree, I cannot navigate back to the tree without it changing back to the pwd of the buffer displayed next to it and I must either use the mouse or close any other window... Also, if `actions.change_dir.global` is `true`, the global now cwd has also changed.

Does `:NvimTreeFocus` navigate back to the tree as you expect?

**Comment by alex-courtis** [comment]
Turns out there is an undocumented bang `:NvimTreeFindFile!`. Documented it.

Added `:NvimTreeFindFileToggle!`

**Comment by alex-courtis** [comment]
@antoineco please ensure that the above works for you and reopen if needed.

**Comment by antoineco** [comment]
Thanks Alex! Exactly what I needed.
