### ISSUE TITLE
Add a new sort option to sort files by old modified time

### ISSUE THREAD

**Issue by siduck** [kyazdani42/nvim-tree.lua#1592]
**Is your feature request related to a problem? Please describe.**
Related to https://github.com/kyazdani42/nvim-tree.lua/pull/1040#issuecomment-1249497644, the `sort = modification_time` currently sorts by prioritizing new modified files on the top and old ones at the bottom.

**Describe the solution you'd like**
It would be helpful to allow a possible value like `modified_time_old` and change the current `modification_time` value to `modified_time_new`

**Comment by alex-courtis** [comment]
`sort_reverse` may be a more generic solution that applies to existing as well as future sort options.
