### ISSUE TITLE
chore: remove side top / bottom

### ISSUE THREAD

**Issue by alex-courtis** [kyazdani42/nvim-tree.lua#1595]
Side top/bottom are not completely functional and show some inconsistencies.
Remove them.
Side not top/bottom/left/right has catastrophic results.

Migration options:
* silently default anything but left/right to left
* explicitly validate side left/right

**Comment by alex-courtis** [comment]
https://github.com/kyazdani42/nvim-tree.lua/commit/fbd421da713952288883db6c2fde754480db6363

**Comment by cmlaverdiere** [comment]
I was using `side: bottom` with this plugin and it was working fine for me, and I didn't notice any issues. Would you be willing to re-add them in with a warning that they aren't fully functional?

**Comment by alex-courtis** [comment]
> I was using `side: bottom` with this plugin and it was working fine for me, and I didn't notice any issues. Would you be willing to re-add them in with a warning that they aren't fully functional?

A _lot_ of things were broken with top/bottom, and functionality has subsequently been built that assumes left/right/float positioning.

What is the use case? A file explorer is tall and would result in a lot of wasted space when shown full width at the bottom or top of a normal wide-rectangular terminal. If you've got some other windows in your layout perhaps we could come up with some alternate means to arrange tall tree windows in your desired position.

I'm open to putting the functionality back in, but only in a "works everywhere" state. You could raise a PR to do this, however we will need to do _extensive_ testing.
