### ISSUE TITLE
incorrect render of file icons (folder icons are ok)

### ISSUE THREAD

**Issue by smartding** [kyazdani42/nvim-tree.lua#160]
I'm using suckless terminal st, and GoMono Nerd Font.
The folder icons are properly rendered, but only the left half of file icons are displayed. 
As shown in the following figure, I can only see the left half of file icons for lua, vim and git files. 
![pic-selected-201218-1517-52](https://user-images.githubusercontent.com/16423944/102585996-51bf3880-4144-11eb-97c8-b341f1fc2b9d.png)

**Comment by smartding** [comment]
It doesn't happen if I use a different terminal, e.g. alacritty.
But since the folder icons are properly rendered, I guess there might be a way to properly render the file icons.

**Comment by kyazdani42** [comment]
i think this is a terminal issue. Because icons sometimes can be 3/4 bytes long (unicode characters), either st doesn't write the icon whose length is more than 1 byte properly on 1 terminal glyph, or neovim don't play well with st. 
You could try pasting the unicode icon in your shell, and if it doesn't render normally, maybe you need a patch for st to properly handle unicode.
I believe folder icons are 1 byte long, and thats why they render normally.

**Comment by smartding** [comment]
I think the folder icons are wider than 1 byte, as you can see in the following screen shot, when I put the cursor on the folder icon, the right half of the icon extends beyond my cursor rectangle, and the folder icon is definitely wider than the letter `l` just above it. 

I think the lua file icon is about the same width as the folder icon. While the right half of the folder icon is correctly displayed, the lua file icon has its right half cut off.

![pic-selected-201219-2241-09](https://user-images.githubusercontent.com/16423944/102691987-633f3800-424b-11eb-91d7-ead6b8e7d69c.png)

**Comment by smartding** [comment]
I modified this line of luatree https://github.com/kyazdani42/nvim-tree.lua/blob/9810f8d8c9bf4ca8f5a677f10d41dee93edc6389/lua/lib/renderer.lua#L45

changed it into `        table.insert(hl, { hl_group, line, depth, depth + #icon+1 })`, and all the file icons are correctly displayed, as shown in the following screenshot. 
The change doesn't seem to have any side effect, I can create a PR if you like it.

![pic-selected-201219-2303-32](https://user-images.githubusercontent.com/16423944/102692483-80c1d100-424e-11eb-86b7-6484bf089f0a.png)

**Comment by akinsho** [comment]
I'm just poking my nose in tbh but this issue hasn't been reported before as far as I know and I don't see this issue using either alacritty or kitty terminal.

Not sure how this code change will affect other terminal emulators but it does seem likely that it might relate to how your terminal emulator handles rendering glyphs no? Do you see the same issue on other terminals? 

It seems likely that other plugins that use nerd fonts will cause this issue for you as well so it's better to find the root cause 🤷🏾‍♂️

**Comment by kyazdani42** [comment]
agree with akinsho. Not sure if there might be a c function that i can access from the vim api to get the proper length of the glyph.

**Comment by kyazdani42** [comment]
although a terminal emulator shoud properly handle unicode rendering. Ill try to see why st does not behave as every other terminals

**Comment by kyazdani42** [comment]
just found this https://github.com/LukeSmithxyz/st/issues/59

**Comment by smartding** [comment]
> Not sure how this code change will affect other terminal emulators but it does seem likely that it might relate to how your terminal emulator handles rendering glyphs no? Do you see the same issue on other terminals?

As I mentioned above, this issue doesn't happen on alacritty. 

It's definitely related to how terminals render glyphs. There's a variable called `cwscale` in `config.def.h` in st's source code, it controls the size of `character bounding-box`, if I set it around something around `1.35`, there would be no cut off for the file icons. But this setting also make all the characters spread apart horizontally, which looks ugly in my option.

**Comment by smartding** [comment]
> just found this [LukeSmithxyz/st#59](https://github.com/LukeSmithxyz/st/issues/59)

I just checked and I have the right locale setting, it's "LANG=en_US.UTF-8".

**Comment by smartding** [comment]
> agree with akinsho. Not sure if there might be a c function that i can access from the vim api to get the proper length of the glyph.

`#icon` is currently used in luatree to measure the `length` of a icon. But I think it only shows the number of bytes it takes to store the unicode value in memory, not how much space it will look on the screen. We do need some new api to get the proper length of a glyph

**Comment by akinsho** [comment]
👍🏾 fair enough, I've used `vim.fn.strwidth` for a similar issue before. That should work better than using the length since it will give you the display size of a string. It might be called something slightly different. But there is a vim function that does it already

**Comment by smartding** [comment]
I think I've figured out why folder icon and file icon behave differently. There's a little bug.
https://github.com/kyazdani42/nvim-tree.lua/blob/9810f8d8c9bf4ca8f5a677f10d41dee93edc6389/lua/lib/renderer.lua#L235 here you passed in the value `icon` returned from `get_folder_icon`, which __always appends a space after the icon__.
But https://github.com/kyazdani42/nvim-tree.lua/blob/9810f8d8c9bf4ca8f5a677f10d41dee93edc6389/lua/lib/renderer.lua#L45 here, you passed in the `icon` returned by `web_devicons.get_icon(fname, extension)`, __no space appended__.

So before we move to another set of api to measure the length of a glyph, we should first treat folder icon and file icon consistently, and change https://github.com/kyazdani42/nvim-tree.lua/blob/9810f8d8c9bf4ca8f5a677f10d41dee93edc6389/lua/lib/renderer.lua#L45  into `        table.insert(hl, { hl_group, line, depth, depth + #icon + 1 })`

I can create a PR if the above reasoning makes sense to you.

**Comment by kyazdani42** [comment]
indeed go for it :) using strwidth should be more appropriate too i think i use this in the refacto
