### ISSUE TITLE
current file no bg color 

### ISSUE THREAD

**Issue by xaotag** [kyazdani42/nvim-tree.lua#1617]
### Description

current file no bg color 
![image](https://user-images.githubusercontent.com/40427877/193396591-72c30fd8-3bb7-4ca6-949d-8a3516199a4f.png)
example
![image](https://user-images.githubusercontent.com/40427877/193396626-dcdd92ac-cb9e-4812-8382-3530aa255aad.png)

### Neovim version

```text
NVIM v0.8.0-dev-1189-gbafeb32b95
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

### Operating system and version

 5.19.12-arch1-1

### nvim-tree version

45d386a

### Minimal config

```lua
require("nvim-tree").setup {}
```

### Steps to reproduce

/

### Expected behavior

current file bg color 

### Actual behavior

current file no  bg color

**Comment by kyazdani42** [comment]
See `:help CursorLine` and `:help highlight` and `:help nvim-tree.highlights`
