### ISSUE TITLE
Double renaming is error

### ISSUE THREAD

**Issue by Stanislav-Lapata** [kyazdani42/nvim-tree.lua#163]
When I rename file twice that I have error.
![27905be76c2b75c6ad58b00ac948dab8](https://user-images.githubusercontent.com/12072329/102775296-9e518080-439d-11eb-9c3c-7253fe495ce1.jpg)
All next renamings are error.

**Comment by kyazdani42** [comment]
rename has some issues with buffers indeed. I'll fix them altogether, thanks for reporting :)

**Comment by kyazdani42** [comment]
well the other issue with buffer rename i cannot really fix but this one was fixed in latest master !
