### ISSUE TITLE
Is it possible to change the icons size?

### ISSUE THREAD

**Issue by zSucrilhos** [kyazdani42/nvim-tree.lua#164]
Hello! First of all many thanks for this AMAZING plugin! It's really awesome, it's fast and works very well out of the box.
I would like to know if it's possible to change the icons' size, I'd like to make the icons bigger, because they're so tiny in my screen. I've seen some screenshots on the README file in which the icons were significantly bigger than mine, so I decided to ask. Thanks in advance.

![image](https://user-images.githubusercontent.com/37763819/103155088-73cf4100-476a-11eb-95ef-ca75ee940f4e.png)

**Comment by kyazdani42** [comment]
hi, thanks for the kind words :)
i believe neither neovim nor the tree itself can do anything about icons. This is something that might related either to the fonts used by your terminal, or your terminal itsef and the way it handles unicode and utf-8.
I'd recommend trying terminals like alacritty and kitty, and something like nerd-fonts

**Comment by zSucrilhos** [comment]
Hello! Thank you for the response. So it's actually a fonts issue, I'm going to see if I can do anything about it, since I'm already using Alacritty. Thanks :)

**Comment by NullVoxPopuli** [comment]
@fP4rad0x did you figure anything out? I'd also like my icons a smidge bigger
