### ISSUE TITLE
Setting the icon of the directory with the symlink open

### ISSUE THREAD

**Issue by yamatsum** [kyazdani42/nvim-tree.lua#167]
Regular directories can be set to open icons.
I want to be able to set an icon with the symlink directory also open.

e.g.) 
```
let g:nvim_tree_icons = {
    \ 'folder': {
    \   'default': "",
    \   'open': "",
    \   'symlink': "",
    \   'symlink_open': "",
    \   }
    \ }
```

**Comment by kyazdani42** [comment]
i'll do that when i have some time, otherwise, you can submit a PR.
