### ISSUE TITLE
'winhl' is being overwritten

### ISSUE THREAD

**Issue by romgrk** [kyazdani42/nvim-tree.lua#17]
In my config files, I set the `winhl` option for LuaTree when it starts, but it's being overwritten. LuaTree should use `set winhl+=` to preserver existing options.

Btw, as soon as you merge the refactor PR I plan to help.

Below is a screenshot of the reason why I wanna modify it. Had to monkey-patch some files to make it.
![Screenshot from 2020-05-25 04-50-42](https://user-images.githubusercontent.com/1423607/82796512-a9faba00-9e43-11ea-8399-c92bc5eb9d63.png)

**Comment by kyazdani42** [comment]
I agree some color choices are not as good as they could be, i'll remove the override in the config too (or at least provide a proper Hl groups to highlight those, which is not obvious right now)
