### ISSUE TITLE
Preserve focused window

### ISSUE THREAD

**Issue by kraftwerk28** [kyazdani42/nvim-tree.lua#171]
Hi, I really enjoy your plugin, the best file-manager for me atm!
If I have at least one split and currently focused window is **not** top-left, then after opening and closing nvim-tree window, the focus gets re-setted to the top-left window (and if I open file with `o`, it also opens in the top-left). I tried to restore position using `line("'\"")`, but it always gives me `1`, which means cursor position isn't saved? Is there such option to solve this, or maybe some workaround?

**Comment by kyazdani42** [comment]
Hi thanks for the kind words :)
i'm not sure how to do this, maybe saving the window on NvimTreeToggle and setting the window on each call would work.

**Comment by n3wborn** [comment]
> Hi, I really enjoy your plugin, the best file-manager for me atm!
> If I have at least one split and currently focused window is **not** top-left, then after opening and closing nvim-tree window, the focus gets re-setted to the top-left window (and if I open file with `o`, it also opens in the top-left). I tried to restore position using `line("'\"")`, but it always gives me `1`, which means cursor position isn't saved? Is there such option to solve this, or maybe some workaround?

Same for me. I really enjoy using nvim-tree but for example, if I'm currently in fugitive window then close it, focus always return in nvim-tree window, which is not  the best thing to do in my opinion.  It would be really cool going back to last focused/active window !
Thanks a lot :)

**Comment by kyazdani42** [comment]
i think something with BufEnter/BufLeave could be worked out

**Comment by kyazdani42** [comment]
should be fixed in be184bd94e

**Comment by timsofteng** [comment]
@kyazdani42 still doesn't work on last commit...

**Comment by n3wborn** [comment]
> @kyazdani42 still doesn't work on last commit...

Commit has been reverted, as said in [https://github.com/kyazdani42/nvim-tree.lua/pull/421](https://github.com/kyazdani42/nvim-tree.lua/pull/421). It seems there's still no "proper way" to do this.

**Comment by kyazdani42** [comment]
Hi, yes there was too many issues with this commit, not sure how to do that without messing with other autocmd

**Comment by alex-courtis** [comment]
Looks like it's working now. I think the changes to close the nvim-tree buffer changed the behaviour.

Please reopen if you're still experiencing issues.
