### ISSUE TITLE
keep getting `Invalid buffer id`

### ISSUE THREAD

**Issue by davidsu** [kyazdani42/nvim-tree.lua#175]
I get the following message `Error executing lua ...ite/pack/packer/start/nvim-tree.lua/lua/lib/renderer.lua:284: Invalid buffer id: 7`, do you know what this is about?

**Comment by davidsu** [comment]
Without any understanding of the code whatsoever, I wrapped the body of `draw` with pcall, so far things seem to run smoothly.
For a tiny bit of context, I jump around through different projects a lot. This seems to happen when I'm jumping to different directories, `Error detected while processing BufEnter Autocommands for "*"

Also, I'm very impressed with the performance, I can easily see myself falling in love with this. Thanks

**Comment by akinsho** [comment]
I've also experienced this for quite a while and use it the same way i.e jumping around projects. I just kept forgetting to raise an issue for it 😅

**Comment by davidsu** [comment]
This plugin is AMAZING!!!
I'm facing an issue that after changing directory `NvimTreeFindFile` doesn't actually find the file. I found a workaround for it
```viml
nmap 1n :lua require('nvim-tree').buf_enter()<cr>:NvimTreeFindFile<cr>
```
this `buf_enter` forces a `update_root_dir` which isn't exposed.
It's probably related to the error I mentioned and my non-proper workaround using `pcall` so...

**Comment by davidsu** [comment]
I might be able to give a hand if you point me in the right direction.

**Comment by akinsho** [comment]
@davidsu I haven't really had a look at the root cause tbh so wouldn't know where to point you to sorry. Maybe @kyazdani42 would know where would be a good place to start

**Comment by kyazdani42** [comment]
Hi :)
well i don't really jump between projects so i've never seen this happening, but this might be happening because of a data race condition with async stuff.
