### ISSUE TITLE
Option to ignore filetypes/folders for auto_open

### ISSUE THREAD

**Issue by thorlucas** [kyazdani42/nvim-tree.lua#176]
Hi,

So I love the auto open functionality for the vast majority of cases.

**However**, when I open a new terminal tab and just need to enter nvim, I do *not* want lua tree to open. This means lua tree should not open automatically when the directory is my home directory (`~`).

Is there any way to do this currently? Could this be an added feature?

Thanks,

**Comment by kyazdani42** [comment]
hi !
if you would like to submit a PR go for it :) you might need to expand the on_enter option and update the related actions.

**Comment by kyazdani42** [comment]
exists under `setup { ignore_ft_on_setup = {'git' }`, closing

**Comment by harmtemolder** [comment]
I was about to open a new issue when I found this. I did find the `ignore_ft_on_setup` option before, but this only checks filetypes, not paths or directories:

https://github.com/nvim-tree/nvim-tree.lua/blob/f1c2d6d3723947d822930e66cd4d3351a3c0370a/lua/nvim-tree.lua#L282

@kyazdani42 Am I understanding the code wrong and is there a way to use this option to exclude directories? (In my use case `/var/tmp/`, for example.)

**Comment by kyazdani42** [comment]
You are properly understanding, we do not ignore folders or files. But the tree should not open when you open a file anyway. Open a new issue please, i'm not maintaining the plugin anymore :)

**Comment by alex-courtis** [comment]
Thanks Kiyan

See #1669
