### ISSUE TITLE
Add option to use .gitignore files to ignore paths

### ISSUE THREAD

**Issue by peach-lasagna** [kyazdani42/nvim-tree.lua#180]

**Comment by kyazdani42** [comment]
would be great indeed, behind an option because i believe it might impact performance a little

**Comment by afonsocarlos** [comment]
I can take this

**Comment by peach-lasagna** [comment]
first
![изображение](https://user-images.githubusercontent.com/59787538/112474955-d3a5aa00-8da2-11eb-92a6-2e7d33832489.png)

**Comment by afonsocarlos** [comment]
Haha, didn't know you were developing this already. That's fine, maybe I can help with something else then

**Comment by peach-lasagna** [comment]
Done. thanks, kyazdani!
