### ISSUE TITLE
Not opening in repository root

### ISSUE THREAD

**Issue by gegoune** [kyazdani42/nvim-tree.lua#184]
Have noticed that tree does not open in repository's root in case such as:

1. `~/ $ nvim` 
  a. open file with `Startify` that is part of git repository
  b. invoke `:NvimTreeFindFile` — tree is opened with root still being `~` (I use vim `vim-rooter` to change nvim's `pwd`)
  c. close tree buffer with `q` (or any other way)
  d. invoke `:NvimTreeFindFile` again — tree correctly opened in buffer's repository root directory

1.a correctly changes nvim's directory; `:pwd` return repository's root directory for opened file so `vim-rooter` does its job.

Other than that - the best tree plugin there is! Thanks!

**Comment by kyazdani42** [comment]
thanks :)
well yes i've disabled git-rooter because it conflicted with this and other plugins too, but i know cwd startup is a bit wonky, a refactoring is definitely needed here.

**Comment by cloggier** [comment]
I have noticed while making your plugin lazy load that it would not work at all and had to put

```lua
vim.cmd "doautocmd NvimTree BufEnter *"
```
into packer's `config` function for *nvim-tree*. With that in place I had no problem with tree opening in repository root. Perhaps that info will help you somewhat.

Thanks for all your work on that plugin and treesitter!

**Comment by kyazdani42** [comment]
your welcome :) well lazy loading is not working because of the way i setup nvim tree. I have to rework the setup tu be more lua like which would probably allow lazy loading

**Comment by cloggier** [comment]
With what you are doing in `plugin/` I don't really need to lazy load it at all, just tried ink the past and came over this 'accidental fix' for root issue.

**Comment by maxigaz** [comment]
`:NvimTreeToggle` still opens in my home folder the first time; I have to close and reopen the file viewer to make it open the directory the file is at. (This happens when I'm trying to open a session from Startify, with buffers inside `~/.config/nvim`.)

@cloggier I've tried your workaround, but I get the following error:

```
Error running config for nvim-tree.lua
Error in packer_compiled: Vim(lua):E5108: Error executing lua [string ":lua"]:52: [string "..."]:0: Vim(doautocmd):E216: No such group or event: NvimTree BufEnter *
Please check your config for correctness
```

Here's how I've set it up using Packer:

```
use {
  'kyazdani42/nvim-tree.lua',
  requires = {'kyazdani42/nvim-web-devicons', opt = true},
  config = function()
    vim.cmd([[doautocmd NvimTree BufEnter *]])
  end
}
```

Is this how you did it, or do I need to change anything?

**Comment by cloggier** [comment]
> use {
> 
>   'kyazdani42/nvim-tree.lua',
> 
>   requires = {'kyazdani42/nvim-web-devicons', opt = true},
> 
>   config = function()
> 
>     vim.cmd([[doautocmd NvimTree BufEnter *]])
> 
>   end
> 
> }
You are not lazy loading the plug-in. Try adding `keys` or `cmd` keys to packer (if I remember names well).

**Comment by maxigaz** [comment]
OK, I've tried the following:

```
use {
  'kyazdani42/nvim-tree.lua',
  requires = {'kyazdani42/nvim-web-devicons', opt = true},
  cmd = 'NvimTreeToggle',
  config = function()
    vim.cmd([[doautocmd NvimTree BufEnter *]])
  end
}
```

After running `:PackerCompile` and restarting Neovim, I no longer receive any errors, but running `:NvimTreeToggle` has the same results as before.

**Comment by cloggier** [comment]
Ah, sorry then, maybe something has changed internally since I had it working. No lazy loading it any more. Just waiting for git root bug to be fixed. :)

**Comment by cloggier** [comment]
@kyazdani42 I have noticed another interesting thing.

* start nvim in `~` directory, use fzf (or `:e`) to open file, open nvim-tree: no updating root to git root of opened file, still showing all files from `~`
* start nvim from any git repository, open file in any git repository (not necessary one from where nvim was started) - root gets updated nicely for each file (including after opening file from some other git repository).

* start nvim from any directory but `~` but not git repository - shows cwd as root (works)

**Comment by kyazdani42** [comment]
there has been this issue for quite some time, i still have to rework some internals in order to handle that properly. Thing is there are many ways users expect neovim to handle their root path and taking them all into account is rather tedious.

**Comment by gegoune** [comment]
Since above refactor (I think) was merged in that issue was sorted out, Unfortunately after updating plugin today it broke again. When I open open nvim from `~`, open some file and run `NvimTreeFindFile` nvm-tree's root is still `~`.

**Comment by kyazdani42** [comment]
why is the plugin supposed to change the root ? it's should update if a `DirChanged` autocmd is sent and `update_cwd` is set to true.

**Comment by gegoune** [comment]
Ah, sorry if I wasn't clear. I use rooter.nvim which changes cwd, that works, but as of today nvim-tree does not change its root, so it shows files all the way to my home directory.

**Comment by kyazdani42** [comment]
I think i've specified that the autocmd on bufenter should be nested because the `cd` will not be dispatched otherwise, this is unrelated to this plugin, the change was made in `project.nvim` after i asked, but the rooter.nvim maintainer did not yet answer.

**Comment by kyazdani42** [comment]
also the rooter.nvim has old logic related to nvim-tree that does not make sense to have. I think project.nvim would be a better plugin to use :)

**Comment by gegoune** [comment]
Ah yeah, but it was working recently actually. Not sure why and how. :) not at my computer at the moment but will run some checks and try to see if I can find commit that broke it.

**Comment by kyazdani42** [comment]
the setup 'broke' it because rooter.nvim explicitly does things for nvim-tree depending on the `g:loaded_tree` variable that i removed. I think rooter.nvim should not do logic just for a specific plugin because the implementation is _flawed_ :smile:

**Comment by gegoune** [comment]
Aha! I think it worked after forts setup commit though. I kept updating every day and only noticed today that it's not working again. 

Will change rooter to project when I get a chance and report back. Hopefully closing this ticket once and for all. 

Thanks for your patience! ❤️

**Comment by gegoune** [comment]
Just tried with project.nvim but nvim-tree still shows file structure all the way to $HOME.

**Comment by kyazdani42** [comment]
are you sure ? just tested out and it works like a charm :smile:

**Comment by maxigaz** [comment]
I'd just like to chip in and say that I've just updated, revised the config according to the README, and autocmd works perfectly now. Thank you!

**Comment by gegoune** [comment]
Interesting. It works if I set

```lua
require('nvim-tree').setup { update_cwd = true, }
```

Did not have that before, so perhaps it was because of that 'old' logic rooter.nvim had?

**Comment by gegoune** [comment]
Also have just noticed that with `update_focused_file.enabled = true` if I switch between buffers in different projects (pwd gets changed) nvim-tree will update root properly (yay!) but won't focus (and expand dirs) on newly selected file. It will show all collapsed directory structure.

**Comment by gegoune** [comment]
This is so odd. I have uninstalled project.nvim and reinstalled rooter.nvim to test if it works with `update_cwd`. It didn't, so I reverted back to project.nvim and it doesn't work again now.

**Comment by kyazdani42** [comment]
rooter.nvim used to manually call the change_dir function in nvim-tree :smile:
could you open an issue for the focus thing ?

**Comment by gegoune** [comment]
Will do when I get a sec to create minimal config, thanks!
