### ISSUE TITLE
[NvimTree] Unrecognized git state "D ".

### ISSUE THREAD

**Issue by boydkelly** [kyazdani42/nvim-tree.lua#185]
Hi... You asked for it.  Please open an issue with this message!  Thanks!

[NvimTree] Unrecognized git state "D ".

**Comment by kyazdani42** [comment]
Hi,
how did you manage to produce this git status ?

**Comment by cloggier** [comment]
Happened to me today after deleting file from gut repository with `vim-fugitive`'s `:Gdelete`.

**Comment by kyazdani42** [comment]
cannot manage to reproduce with vim-fugitive. How can a file be deleted and still be showned in index ? 
Would this mean git deletes a file but the file still is in the worktree ?

**Comment by cloggier** [comment]
Sorry, tried to replicate it on new repo but couldn't.

**Comment by osa1** [comment]
I'm having the same problem. You don't have to delete the file with fugitive, just do `git rm <some file>`.

**Comment by osa1** [comment]
It seems like you also have to close and open the directory in the tree. Full steps to reproduce:

- In a git repo with directories
- `git rm` a file in one of the directories.
- Open `nvim-tree.lua`, show the directory contents (i.e. open the dir with `<CR>`)

You should see `Unrecognized git state "D "` in the command line now.

**Comment by kyazdani42** [comment]
indeed, well i guess this is because the directory is tagged a "D " with porcelain status but the deletion is staged. I'll mark this just like deletion for a dir.

**Comment by osa1** [comment]
Closed via 58a5e4ab48f201a80d58af965cbaa8468ad64144.
