### ISSUE TITLE
How

### ISSUE THREAD

**Issue by thevan96** [kyazdani42/nvim-tree.lua#188]
How to open tree project like open buffer (not split)
Exam like defx.nvim:
![Screenshot 2021-01-22 at 20 05 12](https://user-images.githubusercontent.com/47932916/105494287-243e4f80-5ced-11eb-8c6a-8462053eb0e5.png)

**Comment by kyazdani42** [comment]
not feasible at the moment, and i believe this is related to #131 :)

**Comment by thevan96** [comment]
Thanks ad

**Comment by kyazdani42** [comment]
buffer handling must be refactored and scoped in its own module. Im quite busy lately with work and all so I cannot promise that it will be done soon.

**Comment by kyazdani42** [comment]
continue discussion on #200
