### ISSUE TITLE
Group empty folders

### ISSUE THREAD

**Issue by pidario** [kyazdani42/nvim-tree.lua#191]
Is there a way to accomplish this?
VSCode handles it pretty well and I believe it may be a good improvement especially for those, like me, who have to deal with java.

nvim:
[![2021-01-29T091151](https://user-images.githubusercontent.com/3647292/106249199-54687f80-6212-11eb-9924-36cae4d5a92d.png)](url)

vscode:
![2021-01-29T091245](https://user-images.githubusercontent.com/3647292/106249215-59c5ca00-6212-11eb-9089-8820332cfb45.png)

**Comment by akinsho** [comment]
This seems like it'd be useful although it's worth noting that it might make copying a file into one of the empty folders  or removing one of the empty folders pretty difficult.

Not that should necessarily be a blocker I just think a solution for those cases needs to also need considered as part of a solution.

**Comment by pidario** [comment]
Indeed. Maybe a solution might be to use the cursor to point the empty folder which the user want to use. I don't know if it's feasible, I'm just speculating.

**Comment by kyazdani42** [comment]
it might be doable, but would add complexity to the codebase (while still keeping performance as it is). I'm not sure if people would like this kind of feature, so it should also be hidden behind an option (i would personally not use this). 
If you wish to implement this, go for it, i'd accept a PR.

**Comment by pidario** [comment]
I don't have a lot of spare time and maybe even the required skills but I'll give it a try. If someone else reading this issue is interested in implementing this, please, let me know.
