### ISSUE TITLE
Question!?

### ISSUE THREAD

**Issue by MurdeRMelodY** [kyazdani42/nvim-tree.lua#192]
I'm not sure how to word this. How to navigate with "Visual Line" type movements instead of with a cursor?

**Comment by cloggier** [comment]
Try that:
```
❯ cat nvim/after/ftplugin/NvimTree.vim
setlocal cursorline
setlocal signcolumn=auto
```

**Comment by kyazdani42** [comment]
yes i guess i don't really care about that but if you want to provide a feature behind an option to disable cursor you could submit a PR and i'd gladly accept it !
