### ISSUE TITLE
Choose window to open file in

### ISSUE THREAD

**Issue by fgheng** [kyazdani42/nvim-tree.lua#196]
If I have two windows at least, I want to choose the window while I open a new file, how to do it? thank you very much.

**Comment by cj** [comment]
@fgheng coc-explorer has a great feature https://github.com/weirongxu/coc-explorer/blob/master/autoload/coc_explorer/select_wins.vim only if you have multiple windows open it allows you to choose the window buffer to open the file in.  Something similar could be done for nvim-tree.

Here is an example for NERDTree https://github.com/weilbith/nerdtree_choosewin-plugin

**Comment by fgheng** [comment]
thank you very much

**Comment by kyazdani42** [comment]
i agree it could be great if someone would give it a shot, i don't have much time lately

**Comment by fgheng** [comment]
hello, I found a script in someone's defx config file

```
function! s:selectWindow(filepath)
    if tabpagewinnr(tabpagenr(), '$') > 2
        if exists(':ChooseWin') == 2
            ChooseWin
        else
            if has('nvim')
                let input = input({
                            \ 'prompt'      : 'ChooseWin No.: ',
                            \ 'cancelreturn': 0,
                            \ })
                if input == 0 | return | endif
            else
                let input = input('ChooseWin No.: ')
            endif
            if input == winnr() | return | endif
            exec input . 'wincmd w'
        endif

        if &ft == 'defx'
            return
        else
            exec 'e' a:filepath
        endif

    else
        exec 'wincmd w'
        exec 'e' a:filepath
    endif
endfunction
```
It needs the path of the file, how I get the path of the current file node?

**Comment by kyazdani42** [comment]
I guess you could `require'nvim-tree.lib'.get_node_at_cursor().absolute_path`

**Comment by fgheng** [comment]
> I guess you could `require'nvim-tree.lib'.get_node_at_cursor().absolute_path`

thank you

**Comment by cloggier** [comment]
@fgheng Do you mind sharing working version and maybe a word or two how to set it up?
@kyazdani42 Would you confider adding this functionality directly to your plugin?

**Comment by kyazdani42** [comment]
i would, but in a lua fashion :)

**Comment by cloggier** [comment]
@kyazdani42 goes without saying. :)

**Comment by fgheng** [comment]
> @fgheng Do you mind sharing working version and maybe a word or two how to set it up?
> @kyazdani42 Would you confider adding this functionality directly to your plugin?

I am so sorry, I am learning how to get the value from lua in vimscript, emmmm......

**Comment by kyazdani42** [comment]
`v:lua` or `luaeval`

**Comment by NullVoxPopuli** [comment]
This would be a fantastic feature. Just migrated from coc-explorer, and this is the only feature I used that I'm missing :D

**Comment by sindrets** [comment]
I just put up a PR for a window picker. It's heavily inspired by coc-explorer's way of handling this, as I thought they handled it really elegantly. Give it a try if you have time:)
