### ISSUE TITLE
Two different indentations for the same file level ?!

### ISSUE THREAD

**Issue by ahmedkhalf** [kyazdani42/nvim-tree.lua#197]
Hello, I love this plugin but I believe there is a serious flaw. As you can see from the screenshot below the pdf file doesn't have an icon, therefore it is moved 2 characters to the left. This visual bug makes it very difficult for me to focus, and know the file locations with respect to one another.

![image](https://user-images.githubusercontent.com/36672196/107240944-ed35a100-6a43-11eb-89bf-7ce2cbdf42ac.png)

My solution is to either indent it by two characters to the right, or add a generic file icon.

**Comment by akinsho** [comment]
@ahmedkhalf you can make a PR to [`nvim-webdev-icons`](https://github.com/kyazdani42/nvim-web-devicons) to add an icon for `PDF`s or just use a default one as you've suggested. I think you can also provide an override for a filetype icon that doesn't exist. 

```lua
require'nvim-web-devicons'.setup {
 -- your personnal icons can go here (to override)
 -- DevIcon will be appended to `name`
 override = {
  pdf = {
    icon = "",
    color = "#428850",
    name = "Pdf"
  }
 }
};
```

I think the behaviour you are seeing was specifically requested because some people use this plugin without icons and do not want things to be indented if the icon is missing.

**Comment by ahmedkhalf** [comment]
Hello @akinsho, thank you very much for your suggestion, I will definitely consider doing a push request to `nvim-webdev-icons`.

But what if we fix the problem from the root? For the people who have icons enabled using `let g:nvim_tree_show_icons = { 'files': 1, }` Then we should add some indentation in case an icon doesn't exist, and for the people who disable `show_icons` for files then dont add indentation.

**Comment by akinsho** [comment]
I'll leave this up to @kyazdani42, If I remember correctly from a while back what you are describing as a problem was actually a solution that some other users preferred so I think the solution you suggest might just re-open old issues 🤷🏿 see #45 as one example but I believe this was discussed in a few places

**Comment by kyazdani42** [comment]
indeed this is a formatting i just prefer, i've tried multiple ones and i favored this one. I will probably not accept a PR that involves a formatting change like this sorry
