### ISSUE TITLE
add option to avoid having the cursor over the icons

### ISSUE THREAD

**Issue by ahmedkhalf** [kyazdani42/nvim-tree.lua#198]
Hello, I love this plugin but I believe there is a serious flaw. As you can see from the screenshot below my cursor is sitting above an icon; look bro, I love freedom (both in software and life), but this is just way too much and this visual bug makes it very difficult for me to focus.

![image](https://user-images.githubusercontent.com/36672196/107241734-b318cf00-6a44-11eb-960f-b5bdbb885de7.png)

My suggested solution is to add some kind of tab + conceal to avoid the cursor going into an icon. Merci.

**Comment by kyazdani42** [comment]
This `visual bug` as you say is just not a bug, nor does it bothers me. If this is some kind of feature you wish to implement, go for it, i wouldn't mind.

**Comment by elianiva** [comment]
https://user-images.githubusercontent.com/51877647/109299592-ed1d0a00-7867-11eb-8d40-99c68a2dc78c.mp4

Do you want something like this? I have an autocmd for that but it doesn't work correctly on certain conditions (it's rare though) and it also depends on your terminal.

```viml
augroup HideCursor
  au!
  au WinLeave,FileType NvimTree set guicursor=n-v-c-sm:block,i-ci-ve:ver2u,r-cr-o:hor20,
  au WinEnter,FileType NvimTree set guicursor=n-c-v:block-Cursor/Cursor-blinkon0,
augroup END
au FileType NvimTree hi Cursor blend=100
```

**Comment by ahmedkhalf** [comment]
@elianiva Oh wow perfect, this is amazing.
I just have one follow up question: how can I make the current line highlight have greater contrast only for the NvimTree buffer?

**Comment by elianiva** [comment]
Just add this autocmd and define your custom highlight group, `NvimTreeLine` in this case. 
```viml
  au WinEnter,FileType NvimTree setlocal winhighlight=CursorLine:NvimTreeLine
```

https://user-images.githubusercontent.com/51877647/109378391-adf0c680-7904-11eb-912b-903a5c1aa6e4.mp4

**Comment by ahmedkhalf** [comment]
Problem Solved, tnx.

**Comment by evolify** [comment]
> Do you want something like this? I have an autocmd for that but it doesn't work correctly on certain conditions (it's rare though) and it also depends on your terminal.
> 
>  simplescreenrecorder-2021-02-26_19.21.49.mp4 
> ```viml
> augroup HideCursor
>   au!
>   au WinLeave,FileType NvimTree set guicursor=n-v-c-sm:block,i-ci-ve:ver2u,r-cr-o:hor20,
>   au WinEnter,FileType NvimTree set guicursor=n-c-v:block-Cursor/Cursor-blinkon0,
> augroup END
> au FileType NvimTree hi Cursor blend=100
> ```

The latest version seem to not work when open new file.

**Comment by kyazdani42** [comment]
@evolify see #293
