### ISSUE TITLE
Deleting a newly created file error.

### ISSUE THREAD

**Issue by razak17** [kyazdani42/nvim-tree.lua#201]
Steps to replicate
1. Create a new file with the tree by typing "a".
2. Open the file.
3. Close the file
4. Try to delete the file from the tree by typing "d".

I get this

 error:
`E5108: Error executing lua ...nvim/site/pack/packer/start/nvim-tree.lua/lua/lib/fs.lua:87: Vim(bdelete):E516: No buffers were deleted`

PS: I don't get this error if I don't open the new file before deleting it.

**Comment by kyazdani42** [comment]
how do you close this file ? i wasn't able to reproduce.

**Comment by kyazdani42** [comment]
fixed in latest master
