### ISSUE TITLE
Remove current name of file when renaming

### ISSUE THREAD

**Issue by seblj** [kyazdani42/nvim-tree.lua#203]
I find it more intuitively that the current name of the file is not included when typing r for rename. This means you would have to press backspace numerous times before typing in the new name of the file. 

If renaming a file `Users/user/folder/test.c`, i want only `Users/user/folder/` to appear instead of `Users/user/folder/test.c`, so I can immediately type in the new name of the file. Could you fix this, or at least make this an option?

**Comment by kyazdani42** [comment]
I'll change this, you're right, but i don't have much time rn, if you could make a PR it would be better.

**Comment by seblj** [comment]
Should I make a PR for an option or change the default behaviour?

**Comment by kyazdani42** [comment]
go for changing default behavior, if people complain, we'll hide it behind an option.

**Comment by lucax88x** [comment]
First to complain :)

I would have added an option.

Maybe a good idea would have to have two separate commands, one for removing  the other for keeping, with r and c-r

**Comment by kyazdani42** [comment]
i'll add that then, i've used it today and indeed its not convenient for my use case

**Comment by lucax88x** [comment]
I think that there a case where you want a full rename and where you want just to rename a letter, so having both can be useful, imho.
