### ISSUE TITLE
Add ability to show an empty folder icon

### ISSUE THREAD

**Issue by cooper-anderson** [kyazdani42/nvim-tree.lua#204]
It would be nice if the folder icons could show an empty/outlined icon instead of the solid one when a folder is empty. I attempted to do this on my own and got it working, but only after the user first expands the folder as its contents have not yet been populated.

I figured that having the plugin populate one level deeper than it currently does would be pretty inefficient, so I decided to reach out here. If there is an easy way to check if a given folder is empty, let me know and I can get that pull request up pretty quickly.

![image](https://user-images.githubusercontent.com/21961037/108307869-abf86c00-717c-11eb-8d69-e43da4de61af.png)

In the above image is my current implementation; note the difference in the icons on `components` and `model`. I allowed for `folder.empty` and `folder.empty_open` config options in `nvim_tree_icons`.

If the solution does require populating folders one level deep, then perhaps this could be a config option that is disabled by default since it could possibly add a lot of overhead and unnecessary memory usage.

Anyway, amazing plugin, and I am happy to be contributing to it! :heart:

**Comment by kyazdani42** [comment]
Hi !
maybe this could be loaded on populate, when the node is a directory, you could check if the node has children. If it doesn't, by default, it's empty (i don't think this would take too much time).

**Comment by cooper-anderson** [comment]
Thanks for the info! It helped me get it working! I am making the PR right now.
