### ISSUE TITLE
errror: expected lua string

### ISSUE THREAD

**Issue by klooj** [kyazdani42/nvim-tree.lua#212]
i am receiving the following error when i toggle nvim-tree:

![image](https://user-images.githubusercontent.com/57016271/108792397-2a735600-754f-11eb-9658-48c46dc7a2c9.png)

for me, this issue appeared in commit 905afba (the second most recent). when i revert to commit 491fd68, there is no error. 

i've confirmed it occurs on ubuntu, raspbian, and big sur (all using my "not minimal" [config](https://github.com/klooj/nvimrc-lua)). i've also tried loading it in various ways with and without packer but the issue persists. 

let me know if I can be of more help.

**Comment by elianiva** [comment]
Sorry, I couldn't find where's your nvim-tree config, but if you have a default config from the old version which is `{"<CR>", "o"}`, you need to change it because reading from the source, the current implementation has been changed so it will only accepts a string.

**Comment by klooj** [comment]
nailed it.

**Comment by kyazdani42** [comment]
thanks @elianiva. I indeed changed the default config to make it easier for users to bind custom actions to the nvim-tree buffer. This has been needed for quite a while. 
If people use fzf or stuff like that, they could bind from the config to not make fzf open in the tree buffer like
```lua
vim.g.nvim_tree_bindings = {
  ["<C-p>"] = ":wincmd l | Fzf<CR>"
}
```
