### ISSUE TITLE
Unrecognized git state "RD". Please open up an issue on ...

### ISSUE THREAD

**Issue by vuki656** [kyazdani42/nvim-tree.lua#218]
![image](https://user-images.githubusercontent.com/8104698/109400385-c387df80-7948-11eb-90ec-8791d52b5a10.png)

This occurred when I renamed a `.ts` file to a `.tsx` file. 

Let me know if you need any more info.

Ubuntu 20.04
NVIM v0.5.0-dev+1114-g0c7610cf9
Build type: Debug
LuaJIT 2.1.0-beta3

**Comment by kyazdani42** [comment]
this looks like a strange git status. Did you remove the file at some point ?

**Comment by vuki656** [comment]
> this looks like a strange git status. Did you remove the file at some point ?

I don't believe so. Just renamed it.

After that initial error, it kept popping up very often for I'm assuming the same file if that's worth mentioning.

**Comment by kyazdani42** [comment]
i cannot reproduce this with your informations. RD would mean `renamed in index and deleted in worktree`. I'll try to reproduce this to better understand the meaning.

**Comment by vuki656** [comment]
> i cannot reproduce this with your informations. RD would mean `renamed in index and deleted in worktree`. I'll try to reproduce this to better understand the meaning.

Understandably, It was weird because as I said, it was only a rename, an action which I did many times before and there were no issues.

**Comment by patlux** [comment]
![20210406-193419_Screenshot](https://user-images.githubusercontent.com/4481570/113754136-35550500-970f-11eb-9a37-bf1fe36b1e6e.jpg)

Same with `AD`. It's on a new clear directory after running `git init`.

**Comment by kyazdani42** [comment]
@patlux could you provide the content of the directory ? i did not manage to reproduce.
