### ISSUE TITLE
Nvim Tree prevents gx mapping working

### ISSUE THREAD

**Issue by Akin909** [kyazdani42/nvim-tree.lua#22]
It seems like `g:loaded_netrw` is being set by `nvim-tree` at some point, which I probably wouldn't have noticed if not for the fact that I use `gx` often to follow links in nvim. I know Netrw interferes with other alternative tree plugins as this has been something I've seen across several plugins. But is it possible to avoid disabling it altogether or at least maintaining the `gx` behaviour. Maybe a replacement mapping to `gx` that calls loads netrw only for that purpose.

Not entirely sure how that would work tbh

**Comment by kyazdani42** [comment]
well leaving netrw would obviously conflict with nvim tree.
I think it wouldn't be very difficult to make that feature actually, it would take ~10 LOC

**Comment by kyazdani42** [comment]
The refactoring is almost done, is still have 2/3 quircks to fix but it should come soon, i'll add this in it.

**Comment by joshpetit** [comment]
I'm not sure if this is related, but I can't use `gx` to open links. I have this as my config:
```lua
    use {
        'kyazdani42/nvim-tree.lua',
        requires = 'kyazdani42/nvim-web-devicons',
        config = function()
            require'nvim-tree'.setup {
                disable_netrw = true,
                hijack_netrw = false
            }
        end
    }
```

and have tried both of them set to false, but I still receive this error:

```
E117: Unknown function: netrw#GX
E116: Invalid arguments for function netrw#BrowseX
```
Any ideas? I'd appreciate it thanks!
