### ISSUE TITLE
NvimTreeFindFile doesn't open a window in the current tab if it's open in other tab

### ISSUE THREAD

**Issue by kassio** [kyazdani42/nvim-tree.lua#225]
When trying to find the current file in the tree, if the file tree is already open on another tab,  nvim-tree change tabs to the current window opened.

I'm not sure if this is expected or if there's any configuration to change this behavior, I couldn't find in the docs. But, I'd expect a window to be opened in the current tab with the cursor in the current file position.

### Steps to reproduce

1. Open a file and NvimTree, [Tab1]
2. Open another file in another tab [Tab2]
3. From Tab2, call `NvimTreeFindFile`

#### Current Behavior

1. The current tab is changed to Tab1
2. NvimTree change the position to the file opened in Tab2

![nvim-file-tree](https://user-images.githubusercontent.com/120483/110475965-607d1200-80d9-11eb-9f67-d2be7ef2a05a.gif)

#### Expected Behavior

1. NvimTree Open a window in Tab2
2. NvimTree change the position to the file opened in Tab2

**Comment by kyazdani42** [comment]
indeed the behavior is not handled. I basically don't work with tabs, so the code is not really handling tabs very well.
