### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by kyazdani42** [kyazdani42/nvim-tree.lua#23]

**Comment by Akin909** [comment]
Here's a screenshot for the readme 👍 
<img width="1330" alt="Screenshot 2020-06-19 10 55 52" src="https://user-images.githubusercontent.com/22454918/85120697-84cb5280-b21b-11ea-8794-51257ac43a0f.png">

**Comment by stsewd** [comment]
A minimal tree :)

![Screenshot from 2020-08-16 20-21-06](https://user-images.githubusercontent.com/4975310/90349099-0e21ba00-dffe-11ea-8ac4-f7a6741f77ad.png)
