### ISSUE TITLE
Not changing root directory to the one that contains the .git

### ISSUE THREAD

**Issue by DimitrisMilonopoulos** [kyazdani42/nvim-tree.lua#230]
When opening a file from a git (ex. with startify) the explorer doesn't update its root directory to be the root of the project. Is there any way to achieve that? 

Thank you for this great file explorer :)

**Comment by kyazdani42** [comment]
thanks :)
Hum it should follow nvim's root cwd. What happens when you type `:pwd` ?

**Comment by ceuk** [comment]
Happens for me too.

If you use `:cd` to set the cwd (confirmed with `:pwd`) and then open nvim-tree, it shows the whole home directory

Further, if you use `<C-]>` to set the cwd and then run something like `:mksession! ~/.vim_session`, restart nvim and source the session file, nvim-tree goes back to ~ even if you had explicitly set the working directory.

**Comment by kyazdani42** [comment]
indeed i did not subscribe to the DirChanged, this should be added as an option maybe

**Comment by caheredia** [comment]
Having the same issue. When opening a file from startify, I expect to be dropped into the project root directory, not my home directory.

**Comment by kyazdani42** [comment]
i'll work on a path handling rewrite soon, i'll try and use different plugins / options to make sure the algorithm works as expected for every situations. 
In the meantime, please be patient :)

**Comment by kyazdani42** [comment]
should have been working for some time now. closing
