### ISSUE TITLE
Nvim tree lib.lua expected lua string and failed to rename buffer

### ISSUE THREAD

**Issue by TautvydasCerniauskas** [kyazdani42/nvim-tree.lua#231]
I've recently rebuilt my system and had to install Nvim from source code and update all of the packages.
Now I'm getting this error when running any of the following: `NvimTreeOpen`, `NvimTreeToggle` or `NvimTreeFindFile`.
```
Error executing vim.schedule lua callback: ...te/pack/packer/start/nvim-tree.lua/lua/nvim-tree/lib.lua:247: Expected lua string
Error executing vim.schedule lua callback: ...te/pack/packer/start/nvim-tree.lua/lua/nvim-tree/lib.lua:273: Failed to rename buffer
```
Nvim version: `NVIM v0.5.0-dev+1127-g667e3bfb6`

Is this a problem with the newest version of Nvim? Or an issue with the plugin?

**Comment by kyazdani42** [comment]
i have no issue with the latest version of neovim. Could you try updating the plugin and neovim again ?
also this looks super weird, nvim-tree/lib.lua line 247 is a local function definiton.

**Comment by TautvydasCerniauskas** [comment]
Should have closed this, since I have resolved it. 
The issue was with the fact that the rebinding default keymaps have changed. It's all resolved now.
