### ISSUE TITLE
Support changing cwd only in nvim tree with ":lcd"

### ISSUE THREAD

**Issue by kristijanhusak** [kyazdani42/nvim-tree.lua#234]
Hi,

what do you think about supporting "change dir" but only for nvim tree via ":lcd"?
I'm working on a project that has a lot of nested directories, but a lot of important things still needs to be taken from the project root. I want to narrow down the tree to show only the nested directory while keeping everything else functional like i'm on the project root.

At first this looks fairly simple to implement (Just expose function to do lcd instead of cd), but I'm not sure if there are any gotchas that I'm missing.

**Comment by kyazdani42** [comment]
could be useful indeed :) i'd like that, didn't even know this existed in vim !

**Comment by kristijanhusak** [comment]
I'm not sure about Vim, but I know Neovim supports it :)

**Comment by kristijanhusak** [comment]
I did a quick test by changing `cd` to `lcd` in the change dir function, and nothing was broken. I probably didn't test everything, but hopefully this is a simple change.

**Comment by kyazdani42** [comment]
nice :)
maybe some better path handling would be needed in order to achieve this properly.

**Comment by kyazdani42** [comment]
i've looked at the lcd / cd differences, and i agree, lcd looks better. I think i might need to test this out because i like to jump between projects and with lcd, lsps and stuff based on path like these don't get updated i believe

**Comment by kristijanhusak** [comment]
I think we should have a separate action and mapping for lcd, just to change the "preview" of the tree. In my case I would use it just to have better preview of nested directory, while retaining access to the cwd because of the lsps and everything.

**Comment by kyazdani42** [comment]
i agree. although i'm thinking about removing all those vim commands and write some docs on how to use the plugin and it's inner state. Then it'll be easier for people to write their custom commands, because at some point, i don't particularly want to overload the plugin of very specific use case features (although this one isn't).
Make a PR if you have some time, i might not be working much on the plugin until next month or so.

**Comment by kyazdani42** [comment]
Hi, i decided that indeed it would make more sense to use lcd in the end (in  3196205131a2d4)
