### ISSUE TITLE
 Expected lua string

### ISSUE THREAD

**Issue by lanox** [kyazdani42/nvim-tree.lua#237]
Hi,

I seem to be getting the following error message when trying to ```:NvimTreeToggle```, I was wondering if you could provide some feedback.

```
Error executing vim.schedule lua callback: ...otfiles/nvim/plugged/nvim-tree.lua/lua/nvim-tree/lib.lua:248: Expected lua string
```
Thanks
Lp

**Comment by kyazdani42** [comment]
duplicate #231, seems you're mapping table is inverted (i changed it some time ago)
