### ISSUE TITLE
Don't disable autocommands upon entering a buffer

### ISSUE THREAD

**Issue by rodamaral** [kyazdani42/nvim-tree.lua#241]
If my cursor is onto a nvim-tree node that represents an opened file, which is currently visible on the side of the tree, then pressing `<CR>` or `o` will correctly switch to the intended window, but without triggering BufEnter, WinEnter, etc. This is problematic, as many plugins or user configs depend on those events. For instance, my statusline (bubbly.nvim) uses events to detect the active buffer or beacon.nvim uses them to display the cursor jump animation.

This is caused by command `noautocmd wincmd`: https://github.com/kyazdani42/nvim-tree.lua/blob/f7ad4ce5f4c93c91aca00f0d9f10316c98471798/lua/nvim-tree/lib.lua#L188-L196

I'm not sure about the motivations behind such command, but at least for the `edit` mode under the described circunstances, removing this line would solve the issue.

**Comment by kyazdani42** [comment]
Hi, we did this back then because it caused some issues, we could try removing this for the *edit and see how it behaves

**Comment by kyazdani42** [comment]
i removed it in ce7b186
