### ISSUE TITLE
Different highlight of left column in tree buffer

### ISSUE THREAD

**Issue by regan3** [kyazdani42/nvim-tree.lua#243]
As seen in the image below the left column of the tree buffer has a different background highlight than the rest of the tree. This probably relates in part to the colorscheme I'm using but was wondering what highlight group is being used here and why it's different than, say, the line number columns in the non-tree buffers?

![tree_screenshot](https://user-images.githubusercontent.com/60856003/111922031-b81a6680-8a65-11eb-9258-fb1d40c62820.png)

**Comment by cloggier** [comment]
This is your `signcolumn` most likely.

**Comment by regan3** [comment]
Yep that's the one! I changed it to match the background. Thanks!
