### ISSUE TITLE
In which configuration can i change this Git icon for "deleted"?

### ISSUE THREAD

**Issue by hrqmonteiro** [kyazdani42/nvim-tree.lua#244]
![2021-03-22_14-27](https://user-images.githubusercontent.com/17055027/112032350-09386200-8b1b-11eb-9564-c5a618354762.png)

This red icon, how can i change it? (And it's color)

It is no one of this:

```
vim.g.nvim_tree_icons = {
    default = '',
    symlink = '',
    git = {
        unstaged = "",
        staged = "✓",
        unmerged = "",
        renamed = "➜",
        untracked = ""
    },
    folder = {
        default = "",
        open = "",
        empty = "",
        empty_open = "",
        symlink = ""
    }
}
```

**Comment by hrqmonteiro** [comment]
Actually is not, is the "deleted" one, i tried and now i was able to change it.

Also, i am trying to disable git icons, and i did this:

```
vim.g.nvim_tree_show_icons = {
  folders = 1,
  git = 0,
  icons = 1
}
```

But now, webdevicons stoped working, all of my icons show the "default" icon:

![2021-03-22_14-48](https://user-images.githubusercontent.com/17055027/112035003-e3f92300-8b1d-11eb-8088-208e0356af0e.png)

How can i fix it?

**Comment by kyazdani42** [comment]
hum my bad you were right this is not documented ...
i cannot reproduce your second issue though, maybe something to do with plugin load ordering ?

**Comment by hrqmonteiro** [comment]
That's what i thought. Actually webdevicons was indeed called after nvim-tree.

But now that i change it, it still is not showing the icons, only the defaults..

**Comment by kyazdani42** [comment]
what package manager do you use ?

**Comment by hrqmonteiro** [comment]
I use [https://github.com/savq/paq-nvim](paq).

**Comment by kyazdani42** [comment]
in your neovim plugin config for nvim-web-devicon, you set default = true, what happens if you remove that line ?

**Comment by hrqmonteiro** [comment]
> in your neovim plugin config for nvim-web-devicon, you set default = true, what happens if you remove that line ?

Same thing.

I am still with this problem... If i remove the git icons, all of the icons show the default one.
