### ISSUE TITLE
Git icons cause names to be misaligned

### ISSUE THREAD

**Issue by GaetanLepage** [kyazdani42/nvim-tree.lua#246]
Hello,

The git icons that appear in front of files/directories names are shifting them.
Would it be possible to add a shift to the files where there is no git icon so that they stay aligned ?
I think that NerdTree is tackling this issue in some way.

Maybe this behavior is intended and not expected to be fixed.

Thank you for this great project !

**Comment by kyazdani42** [comment]
Hi, this has been requested in #72 but not done yet, i would not be against that so long it doesn't affect performance :)

**Comment by GaetanLepage** [comment]
Ok great !
Yes, it could be either at the right or stay at the left, but shifting other ones of the same amount.

Glad it is planned anyway :)

Cheers

**Comment by kyazdani42** [comment]
:+1:

**Comment by kyazdani42** [comment]
should've been closed in #1203
