### ISSUE TITLE
Question? How to open a full screen tree when doing "nvim ."

### ISSUE THREAD

**Issue by alvarogalloc** [kyazdani42/nvim-tree.lua#248]
I used to use fern but while i am changing most of my vimscript config to lua, when i tried to change to nvim_tree-lua i encountered that when i put the nvim_tree_auto_open = 1 it opens the tree just in the width i specified, the thing is that i want that full width when it is the only buffer opened.

**Comment by kyazdani42** [comment]
hi ! this has been asked in #214 and #200 but not possible yet, i have to finish the buffer / window rework that i started last week before this is made possible.

**Comment by Alvaroalloc** [comment]
Should I close this since this problem is adressed to previous??

**Comment by kyazdani42** [comment]
don't worry, i'll close them alltogether once this is implemented

**Comment by kyazdani42** [comment]
closed in bac5633e1f7e7 `1.1.0`
