### ISSUE TITLE
Closing buffer exits neovim when NvimTree is open.

### ISSUE THREAD

**Issue by rafamadriz** [kyazdani42/nvim-tree.lua#252]
I can't have multiple buffers open with nvimtree because whenever I close a buffer it completely exits nvim. I've notice that in the README the second [screenshot](https://github.com/kyazdani42/nvim-tree.lua#screenshots) has multiple buffers open, I wanted to ask, what do you do when closing one buffer to avoid this behavior ? Or are those tabs ? Maybe this is happening just to me, idk.

## Closing buffer with NvimTree open:
![output](https://user-images.githubusercontent.com/67771985/112483152-acce8000-8d70-11eb-8c30-0c8671bfbda6.gif)
As you can see, it just exits neovim if NvimTree is open.

## Closing buffer without NvimTree open:
![notree](https://user-images.githubusercontent.com/67771985/112483523-033bbe80-8d71-11eb-8195-8ee229aa30c3.gif)
Here, it doesn't happen because NvimTree is closed.

**Comment by kyazdani42** [comment]
Hi ! this issue was raised multiple times, i believe you should disable the `nvim_tree_auto_close` option if you don't wan't to emulate the automatic window closing behavior.

**Comment by rafamadriz** [comment]
> i believe you should disable the nvim_tree_auto_close option if you don't wan't to emulate the automatic window closing behavior.

I already tried that, it closes the buffer without closing the session but what happens is that NvimTree takes the fullscreen, and after manually going to another buffer that's when finally, the buffer I wanted to deleted since the beginning disappears.

It's really annoying having to do all of that just to close one buffer and disabling `nvim_tree_auto_close` won't exit neovim when NvimTree is the last buffer (which personally, is what I want). Right now it's not possible closing buffers with NvimTree open without having side effects. Maybe this is a bug because of the side effects and the default behavior of doing `:bd` is not closing the session. 

### Workaround 
For anyone else having this problem, the best workaround I found right now was using [romgrk/barbar.nvim](https://github.com/romgrk/barbar.nvim), which includes the command `:BufferClose`, using that one instead of the builtin `:bd` seems to stop closing the session when NvimTree is open. However, it is not perfect, it doesn't handles splits correctly.  

It will be really nice if this gets fixed in the future, for now I think the workaround I found will make happy most users having the same problem, unless you are a heavy user of splits and of course, using another plugin just for this is not the finest solution.

Besides this problem, I've been enjoying this plugin a lot. I really like being able to create, rename and remove files within NvimTree. Thanks for your work.

**Comment by kyazdani42** [comment]
i tried to emulate the behavior for closing the tree when it's the last buffer but i did not manage to do this properly, because of the behavior of the `:bd` and `:bw` command which does not quit vim (and does not delete unnamed buffers). 
I could make this such as when the tree is the last buffer or the last buffer next to an unnamed one, it closes, but then when starting up, it would quit immediately. There are edge cases when working with buffers and as i prefer to work with windows... well you see my point. I think in #235 this discussed already if you want to take a look :)

**Comment by ccaseiro** [comment]
With [ojroques/nvim-bufdel](https://github.com/ojroques/nvim-bufdel) plugin installed and using the corresponding `BufDel` (instead of `bd`) I get the desired behaviour.

`BufDel` is implemented with something like(from a [reddit](https://www.reddit.com/r/neovim/comments/l8vyl8/a_plugin_to_improve_the_deletion_of_buffers/) post):
```lua
function delete_buffer()
  local buflisted = fn.getbufinfo({buflisted = 1})
  local cur_winnr, cur_bufnr = fn.winnr(), fn.bufnr()
  if #buflisted < 2 then cmd 'confirm qall' return end
  for _, winid in ipairs(fn.getbufinfo(cur_bufnr)[1].windows) do
    cmd(string.format('%d wincmd w', fn.win_id2win(winid)))
    cmd(cur_bufnr == buflisted[#buflisted].bufnr and 'bp' or 'bn')
  end
  cmd(string.format('%d wincmd w', cur_winnr))
  local is_terminal = fn.getbufvar(cur_bufnr, '&buftype') == 'terminal'
  cmd(is_terminal and 'bd! #' or 'silent! confirm bd #')
end
```

**Comment by y1rn** [comment]
```nvim_tree_auto_close``` was disabled
![Animation](https://user-images.githubusercontent.com/70128797/126470027-627f0c76-f68b-4251-890e-7db13469dd6d.gif)

**Comment by y1rn** [comment]
> `nvim_tree_auto_close` was disabled

i found this solution
```vimscript
noremap  <M-w>  <cmd> if &filetype != 'NvimTree' \| try \|bp \| bd # \|catch /.*/ \| bd \| endtry \| endif<CR>
```

**Comment by kyazdani42** [comment]
should be fixed for quite some time, closing.

**Comment by y1rn** [comment]
not seen any difference

> `nvim_tree_auto_close` was disabled ![Animation](https://user-images.githubusercontent.com/70128797/126470027-627f0c76-f68b-4251-890e-7db13469dd6d.gif)

**Comment by alex-courtis** [comment]
> I'm assuming this bug is considered fixed, but I'm seeing the exact same behaviour as @y1rn.

This functionality has been removed and is left to the user; see [6](https://github.com/kyazdani42/nvim-tree.lua#tips--reminders)

If you are experiencing a problem with the current nvim-tree, please raise a [bug](https://github.com/kyazdani42/nvim-tree.lua/issues/new?assignees=&labels=bug&template=bug_report.yml)
