### ISSUE TITLE
Unable to override <Esc> key

### ISSUE THREAD

**Issue by Himujjal** [kyazdani42/nvim-tree.lua#255]
`<Esc>` key is used to go one dir up which is hugely annoying.

I am not able to override it. In fact on pressing `:map` inside nvim-tree, sometimes the mapping is right and sometimes the mapping is wrong. I am not sure what is wrong in this case.

Is it possible to disable `<Esc>` as `dir_up` by default?

**Comment by kyazdani42** [comment]
just disable the key in `nvim_tree_bindings` :)

**Comment by kyazdani42** [comment]
```lua
vim.g.nvim_tree_bindings = {
   ["<Esc>"] = ""
}
```

**Comment by Himujjal** [comment]
The problem isn't that I don't know how to disable the `esc` key. Apologies for not making it clear. The problem is that the overriden mappings get overriden by the defaults sometimes and sometimes they don't.

**Comment by kyazdani42** [comment]
how do you mean sometimes the get overriden ? if your config doesn't change it shouldn't affect, and your bindings should always prevale on the plugin one.
otherwise: `vim.g.nvim_tree_disable_keybindings = 1`  and you map it by hand (something like `au FileType NvimTree my_mapping_function()`
