### ISSUE TITLE
Change drives in windows

### ISSUE THREAD

**Issue by kishikaisei** [kyazdani42/nvim-tree.lua#256]
There is no way to change drives on a windows machine, and if there is a method already, it isn't obviously documented.
Examples:
- coc-explorer: have a command `gd` to list the drives and navigate to them
- NerdTree: have a less elegant command `:NERDTree Z:\` but better than nothing

**Comment by kyazdani42** [comment]
indeed there is no `NvimTreeCd` command yet, does `:cd` work on windows machines ?

**Comment by kishikaisei** [comment]
Yup, does the trick. I got used to the coc-explorer quickfix like panel, but using `:cd ` is good enough.
So thanks, and I guess no extra feature is required, (the best kind of features 😆 )

**Comment by kishikaisei** [comment]
Oh, just did a premature close probably, `:cd` works only when nvim-tree is closed
To change drives:
1. Close nvim-tree if open
2. `:cd` to drive
3. Reopen nvim-tree

So it is a limitation I guess.

**Comment by kyazdani42** [comment]
I'll fix this :) it's not a limitation, i'll just add the command properly
