### ISSUE TITLE
Can't create when in empty directory

### ISSUE THREAD

**Issue by kishikaisei** [kyazdani42/nvim-tree.lua#259]
#### Issue description
Pressing the hotkey for `create` (a) when inside an empty directory does nothing, you have to be `CD`ed into an empty directory so the panel is basically empty.

#### Cause
My assumption is, since in an empty directory the cursor is on the path name, not on an actual item, the command doesn't work.

#### Steps to reproduce the issue
1.  Create an empty directory
2. `<CR>` into it (cd binding)
3. `a` (create binding) to create a file/folder 
❌ Nothing happens
✔ The ability to add file/folder

**Comment by kyazdani42** [comment]
indeed, not sure what the course of action should be here. I've been using my plugin for a long time and never tried to do that so it's not obvious to me which kind of ux solution we should apply here :)
