### ISSUE TITLE
Autocommand errors

### ISSUE THREAD

**Issue by Akin909** [kyazdani42/nvim-tree.lua#26]
I've encountered a few autocommand errors whilst using nvim tree
![tree-autocommand-error](https://user-images.githubusercontent.com/22454918/83339032-b5c20280-a2c1-11ea-9ce7-bba66dc28376.png)

and 

![nvim-tree-bug-msg](https://user-images.githubusercontent.com/22454918/83339049-c8d4d280-a2c1-11ea-9d44-9866ae0a691b.png)

I'm not sure exactly how to reproduce either of them unfortunately I haven't had enough time to debug. The config I'm currently using is

```vim
let g:lua_tree_auto_close = 1 " 0 by default, closes the tree when it's the last window
let g:lua_tree_follow     = 1 " On bufEnter find the current file
let g:lua_tree_bindings = {
      \ "edit": "o",
      \}
let g:lua_tree_ignore = [ '.git', 'node_modules' ]
```

I've also noticed that when I save a buffer nvim seems to block for like 1-2seconds. When I disable `nvim-tree` things go back to normal.

Sorry this isn't too detailed I'll do some more digging when I get a chance and update this

**Comment by kyazdani42** [comment]
okay i fixed the cursor position issue, which was an error in the order of function calls...
i didn't noticed for the save issue, but i didn't work on large repos, i tested on multiple repos at the same time and indeed, i found that refreshing git takes a long time, i'm gonna try optimize that, or i could make it asynchronous but i don't know if it would fix the issue properly.
Basically, i think the `system` calls to get the git status take too long to execute compared to the rest of the code, i don't really know if there is a way to fix this, i tried using the libuv spawn functions but they are non blocking and doing async in lua is quite a pain ...

**Comment by kyazdani42** [comment]
actually looking at the code i just realized i'm calling those system function for every node, which is definitely wrong, they should only be called for each root of the git trees and bufferized, i will fix that asap :)
