### ISSUE TITLE
Is there a way to remove this gray vertical bar?

### ISSUE THREAD

**Issue by gmr458** [kyazdani42/nvim-tree.lua#261]
![image](https://user-images.githubusercontent.com/53343401/113093925-70f34a80-91b6-11eb-9040-ea6cef285a19.png)
I have seen some screenshots of other users and this does not appear to them. I use Windows.

**Comment by cloggier** [comment]
It's `signcolumn` most likely. You can use `after/ftplugin/` or `autocmd FileType NvimTree localset signcolumn=<no|auto>` to turn it off for NvimTree buffers only. Or change your global setting.

**Comment by gmr458** [comment]
Thanks

**Comment by kyazdani42** [comment]
thanks @cloggier it is indeed :)

**Comment by cloggier** [comment]
@gmr458 Yes, please have a look here, it will shed some light onto what it does: https://learnvimscriptthehardway.stevelosh.com/chapters/12.html

Also it's best to wrap `autocmds` with `augroup`: https://learnvimscriptthehardway.stevelosh.com/chapters/14.html
