### ISSUE TITLE
Some synchronous job blocking editor for 500ms on file write

### ISSUE THREAD

**Issue by talbergs** [kyazdani42/nvim-tree.lua#267]
This change in configuration fixed this issue for me:
```diff
+ vim.g.nvim_tree_show_icons = {git = 0, folders = 0, files = 0}
- vim.g.nvim_tree_show_icons = {git = 1, folders = 0, files = 0}
```

**Comment by kyazdani42** [comment]
thanks for the information, i'll see what i can do. Indeed it blocks the editor when quitting and saving `:xa` which has been reported before :) with this i might be able to fix it easily.

**Comment by kyazdani42** [comment]
my issue did not come from this plugin after all, but from the `efm` language server. Closing this, follow up discussion on #172 as this seems not resolved for everybody.

**Comment by talbergs** [comment]
Are you sure? I do not have `efm` installed even.

**Comment by kyazdani42** [comment]
what happens if you use `set shell=/bin/bash` in your neovim config ?
