### ISSUE TITLE
Replaces existing files without any warning

### ISSUE THREAD

**Issue by s1n7ax** [kyazdani42/nvim-tree.lua#271]
When there is an existing file by the same name you are about to crate, It replaces the existing file.

steps:

- Create 'test.txt' file
- Enter some text
- Save and close
- Hit 'a' to create new file in nvim-tree
- Set the name 'test.txt' and hit enter

nvim-tree replaces the exiting file without any warning with an empty file.

**Comment by kyazdani42** [comment]
good catch, i'll fix that
