### ISSUE TITLE
Disable additional decorations

### ISSUE THREAD

**Issue by Shatur95** [kyazdani42/nvim-tree.lua#273]
I propose to add the ability to disable the decoration in bold of executable files. This can be useful if you are using an NTFS partition in which all files are executable by default. For example, how it looks on my machine:

![изображение](https://user-images.githubusercontent.com/22453358/113771778-7f98af00-972c-11eb-91ee-d2157714b4be.png)

Also it would be nice to have an option to disable underscore for `README.md` files.

**Comment by kyazdani42** [comment]
damn indeed it looks weird. NTFS is windows filesystem right ?
i think you can disable the underscore by overriding `NvimTreeSpecialFile` and setting `guisp=NONE` or something like that

**Comment by Shatur95** [comment]
> damn indeed it looks weird. NTFS is windows filesystem right ?

Yes :)

>  i think you can disable the underscore by overriding NvimTreeSpecialFile and setting guisp=NONE or something like that

Thanks! Maybe provide an option to just disable all decorations (including bolding for executable files)?

**Comment by cloggier** [comment]
I am trying to override `NvimTreeSpecialFile` in packer's `config` function, but it seems to be ignored.

**Comment by kyazdani42** [comment]
```lua
  vim.cmd "hi! def NvimTreeSpecialFile guifg=orange"
```
seems to work fine for me.
@Shatur95 i'd prefer not to overload this plugin with options that are not required, if users need to change color groups, they should just override them :)
