### ISSUE TITLE
launcher

### ISSUE THREAD

**Issue by aeosynth** [kyazdani42/nvim-tree.lua#274]
I want to launch/open (non-text) files while browsing, in a separate program. Even with netrw enabled, `gx` doesn't work.

**Comment by aeosynth** [comment]
Oops, I had to move the cursor, nevermind.

**Comment by aeosynth** [comment]
Hm `gx` only works if you are `cd`-ed to the file's directory and the filename doesn't contain spaces.

**Comment by kyazdani42** [comment]
not sure if the `gx` issue should be addressed with this plugin, as it's part of the netrw landscape. Should i close this ? I'm not sure what we can do to fix your issue in this plugin

**Comment by aeosynth** [comment]
I was hoping that this plugin could replace netrw completely, and add an `open` command. How would I create a custom command for this, can I send the absolute path of the selected item to a function?

**Comment by kyazdani42** [comment]
oh okay. My goal is not to replace all features of netrw, but to provide an easy to use and fast tree view with some integrations.
we previously had the gx command built in nvim tree but I removed it in favor of the netrw functionnality.
You could reproduce it quite easily though:
```lua
local node = require'nvim-tree.lib'.get_node_at_cursor()
vim.fn.system("xdg-open "..node.absolute_path)
```

**Comment by aeosynth** [comment]
Ok, thanks. Closing, but netrw is not functional as stated - only works if you use `cd`, doesn't work on filenames with spaces.

**Comment by kyazdani42** [comment]
I dont use netrw features so I cant say really. If someone wants to implement fixes for netrw compatibility, I wouldnt be against it but I dont think it matters too much :)
