### ISSUE TITLE
Feature Request: Option for Find File on Toggle

### ISSUE THREAD

**Issue by yashguptaz** [kyazdani42/nvim-tree.lua#275]
Currently, I toggle my nvim-tree using `<C-e>` (ctrl + e)
But every time I toggle it all my folders are collapsed.

I want to be able to toggle nvim-tree and be on the file which is open in my current buffer.

So what I want is an option with `:NvimTreeToggle` that works like `:NvimTreeFindFile` but can also close NvimTree.

This could be as simple as a setting in the NvimTree lua configuration for NvimTreeToggle option that I could turn on and off.

**Comment by sindrets** [comment]
@yashguptaz You could solve that with something like this:

```vim
function! NvimTreeFindToggle()
lua << EOF
    local nt_lib = require'nvim-tree.lib'
    if nt_lib.win_open() then
        nt_lib.close()
    else
        require'nvim-tree'.find_file(true)
    end
EOF
endfunction
```

But the problem of folders collapsing on toggle should already have been resolved, so make sure you have updated nvim-tree.

**Comment by kyazdani42** [comment]
i've never seen the folder collapsing on toggle though, maybe due to my config somehow. Thanks @sindrets for the quick answer, i think i should remove the default commands and describe a little the API in the documentation so the users can bind their own set of commands easily.

**Comment by kyazdani42** [comment]
many changes since last week, i consider this fixed based on what sindrets provided. Also the issue for the toggle should be completely fixed now.
