### ISSUE TITLE
Custom launcher with animate.vim

### ISSUE THREAD

**Issue by gasacchi** [kyazdani42/nvim-tree.lua#276]
Hi, i'm curious and try to make custom launcher with [animate.vim](https://github.com/camspiers/animate.vim)

some effort (i'm usually use moonscript, sorry if it's ugly ;) )
```lua
function M.custom_launcher ()
  require'nvim-tree'.open()                                                                            
  cmd "wincmd L | vertical resize 1"                                            
  cmd "call animate#window_percent_width(0.8)"
end
```
it did work, but not what i expected.

**Comment by kyazdani42** [comment]
could i have more information on your issue like:
- a minimal configuration
- what was not expected ?

**Comment by kyazdani42** [comment]
closing because missing information
