### ISSUE TITLE
Move to trash instead of delete

### ISSUE THREAD

**Issue by famiu** [kyazdani42/nvim-tree.lua#279]
Currently nvim-tree allows deleting a file permanently. I suggest moving them to trash by default if possible since it may sometimes be necessary to recover a deleted file, despite the confirmation prompt for deletion

**Comment by kyazdani42** [comment]
could be indeed useful for some people, although i'm not sure if the trash is located at the same place on every filesystem. Maybe something like `trash_path` could be nil or a string, if a string, then move the file to this location.

**Comment by Famiu** [comment]
Or maybe use external tools like trash-cli?

**Comment by kyazdani42** [comment]
i really dont want to use external dependencies like this, a trash path would be better handled internally because i could bind other things to it (like buffer handling). Removing needs deleting the buffer it its open, renaming needs renaming the buffer if its open.
Also trash-cli doesn't seem to support windows from what i see

**Comment by cloggier** [comment]
How about providing hooks that users could use to perform certain actions? I think this would allow for great extensibility without adding many different features directly to the plugin.

**Comment by Famiu** [comment]
> How about providing hooks that users could use to perform certain actions? I think this would allow for great extensibility without adding many different features directly to the plugin.

I approve. Alternatively we can provide a config to allow the user to specify a command format to move a file to trash

**Comment by kyazdani42** [comment]
what do you mean by hooks ? we added events lately on fs actions, but if you have another idea i wouldn't be against adding it to the plugin

**Comment by cloggier** [comment]
Ah, wasn't aware of that. It's probably the same concept. 

So can user override what delete does?

**Comment by kyazdani42** [comment]
nope, but i might add a soft-remove to fix this issue, or you could basically copy the delete code but use move instead of delete for now :)

**Comment by RaafatTurki** [comment]
I'll be speaking mainly for linux but this applies to windows and mac to some degree.

Trash support is a [freedesktop specification](https://www.freedesktop.org/wiki/Specifications/trash-spec/) which in a nutshell explains that the process of trashing a file isn't as simple as moving it elsewhere.

Generally speaking the trash directory would be `~/.local/share/Trash/` with the sub dirs `expunged`, `files`, and `info`.

Trashed files are thrown into `files` and for each of those a corresponding `.trashinfo` file is generated and placed in `info` containing things like the `DeletionDate` and the `Path` (that's how the restore functionality is possible).

Obviously a `.trashinfo` file is removed once its `files` counterpart is permanently deleted or restored, there's even more to it but that's what I can recall right now.

Other plugins like fern and chadtree did face this [exact](https://github.com/lambdalisue/fern.vim/blob/609610754b52d3d32616bd70094dcce3a88db3e6/doc/fern.txt#L1047) [issue](https://github.com/ms-jpq/chadtree/blob/a1d8f109efba85a98253b743a367e00a042df8cb/README.md#i-like-21st-century)
and they've simply used things like
- [trash-cli](https://github.com/andreafrancia/trash-cli)
- [gomi](https://github.com/b4b4r07/gomi)
- [trash](https://formulae.brew.sh/formula/trash)

**Comment by kyazdani42** [comment]
i see, i'm not using any trash on my system so if someone want to give it a go, go for it. Replacing the default delete command with a trash one, and a force delete command that would be the existing one (which i would personally still use) !

**Comment by famiu** [comment]
> Other plugins like fern and chadtree did face this [exact](https://github.com/lambdalisue/fern.vim/blob/609610754b52d3d32616bd70094dcce3a88db3e6/doc/fern.txt#L1047) [issue](https://github.com/ms-jpq/chadtree/blob/a1d8f109efba85a98253b743a367e00a042df8cb/README.md#i-like-21st-century)
> and they've simply used things like
> 
>     * [trash-cli](https://github.com/andreafrancia/trash-cli)
> 
>     * [gomi](https://github.com/b4b4r07/gomi)
> 
>     * [trash](https://formulae.brew.sh/formula/trash)
So the solution was in fact what I suggested at first, huh.

**Comment by kyazdani42** [comment]
sure, didn't know there was so many things about a trash folder we had to worry about.

**Comment by sandangel** [comment]
I suggest allowing the user to pass a callback function, and user can do whatever they want. Like Defx did. It's more flexible for both normal user and advance user.

**Comment by gegoune** [comment]
But you can already map a key to custom function. Just remap d mapping I guess.

**Comment by ExtinctAxolotl** [comment]
> But you can already map a key to custom function. Just remap d mapping I guess.
How would you implement that?

**Comment by gegoune** [comment]
Probably by wrapping call to trash-cli in lua function passing path of a node along. You might have to refresh tree after.

**Comment by ExtinctAxolotl** [comment]
```lua
function NvimTreeOSOpen()
    local lib = require"nvim-tree.lib"
    local node = lib.get_node_at_cursor()
    if node then
        vim.fn.jobstart("open '" .. node.absolute_path .. "' &", {detach = true})
    end
    lib.refresh_tree()
end
```
This method is a little buggy, but it works.

Later adding the keybinding:
```lua
vim.g.nvim_tree_bindings = {
    { key = "t", cb = ":lua NvimTreeTrash()<cr>" }
}

```

**Comment by ExtinctAxolotl** [comment]
The only problem is that the tree does not refresh, you need to refresh manually by pressing "R" even though the `lib.refresh_tree()` is called.

**Comment by gegoune** [comment]
I am not sure how `jobstart` works but perhaps it's somewhat async and refresh is happening straight away while `trash` is still running, try to put some sleep before it, or use blocking (if `jobstart` isn't blocking) execution method.

**Comment by ExtinctAxolotl** [comment]
```lua
function NvimTreeTrash()
    local lib = require"nvim-tree.lib"
    local node = lib.get_node_at_cursor()
    if node then
        vim.fn.jobstart("trash " .. node.absolute_path .. " &", {detach = true} )
    end
    vim.cmd("sleep 100m")
    lib.refresh_tree()
end
```
It works 乁(σヘσ)ㄏ

**Comment by ExtinctAxolotl** [comment]
Thank you @gegoune for your help!

**Comment by gegoune** [comment]
Yeah, so I was right, perhaps instead of putting timer in there you can somehow wait for jobstart to finish and only then refresh the tree, would be prettier solution. Sorry for not giving you exact solutions, I am not sure how to code it.

**Comment by sandangel** [comment]
> Yeah, so I was right, perhaps instead of putting timer in there you can somehow wait for jobstart to finish and only then refresh the tree, would be prettier solution. Sorry for not giving you exact solutions, I am not sure how to code it.

yeah, something like `await jobstart()` or `promise.then()` in javascript will be a better solution.

**Comment by sandangel** [comment]
```lua
    local lib = require('nvim-tree.lib')
    function NvimTreeTrash()
      local function on_exit(job_id, data, event)
        lib.refresh_tree()
      end
      local node = lib.get_node_at_cursor()
      if node then
        vim.fn.jobstart("trash " .. node.absolute_path, {
          detach = true,
          on_exit = on_exit,
        })
      end
    end

    local tree_cb = require('nvim-tree.config').nvim_tree_callback
    vim.g.nvim_tree_bindings = {
      { key = "d", cb = ":lua NvimTreeTrash()<CR>" },
    }
```

okay this is the full code I ended up with. Hope this help. ^^

**Comment by ExtinctAxolotl** [comment]
Works! Thank you! 🚀

**Comment by png261** [comment]
if you want to confirm before remove to trash you can use this function:

```lua
    function NvimTreeTrash()
        function get_user_input_char()
            local c = vim.fn.getchar()
            return vim.fn.nr2char(c)
        end

        function clear_prompt()
            vim.api.nvim_command('normal :esc<CR>')
        end

        function remove()
             local lib = require('nvim-tree.lib')
             local function on_exit(job_id, data, event)
                 lib.refresh_tree()
             end
             local node = lib.get_node_at_cursor()
             if node then
                 vim.fn.jobstart("trash " .. node.absolute_path, {
                     detach = true,
                     on_exit = on_exit,
                 })
             end
        end

        print("Are you sure ? y/n")
        local ans = get_user_input_char()

        if ans:match('^y') then
            remove()
        end

        clear_prompt()
    end

```

**Comment by RaafatTurki** [comment]
here's a cleaner function with a more native looking confirmation prompt
```lua
	function NvimTreeTrash()
		local lib = require('nvim-tree.lib')
		local node = lib.get_node_at_cursor()
		local trash_cmd = "trash "

		local function get_user_input_char()
			local c = vim.fn.getchar()
			return vim.fn.nr2char(c)
		end

		print("Trash "..node.name.." ? y/n")

		if (get_user_input_char():match('^y') and node) then
			vim.fn.jobstart(trash_cmd .. node.absolute_path, {
				detach = true,
				on_exit = function (job_id, data, event) lib.refresh_tree() end,
			})
		end

		vim.api.nvim_command('normal :esc<CR>')
	end
```
and don't forget to bind it 
```lua
vim.g.nvim_tree_bindings = {
	{ key = "d", cb = ":lua NvimTreeTrash()<CR>" },
}
```
also, whenever you restore from trash be sure to refresh the tree with `R`

**Comment by kyazdani42** [comment]
if someone would like to implement a trash method i wouldn't be against it by the way :smile:

**Comment by kyazdani42** [comment]
please open a PR for what you think is better :)
