### ISSUE TITLE
Consider 4 highlight groups for diagnostics

### ISSUE THREAD

**Issue by ChristianChiarulli** [kyazdani42/nvim-tree.lua#281]
NvimTreeLspDiagnosticsError
NvimTreeLspDiagnosticsWarning
NvimTreeLspDiagnosticsHint
NvimTreeLspDiagnosticsInfo

**Comment by kyazdani42** [comment]
i think it could also clash with git highlighting, but as this is done manually after tree has rendered, it might prevale. I'll test this and see if i can come up with a better ux solution

**Comment by ChristianChiarulli** [comment]
hmm, maybe just a sign with the higlight then, maybe with the option to highlight the test. That may be asking a lot though haha

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by kyazdani42** [comment]
I intended to use signs for bulk actions at some point but until then maybe that would be ideal indeed.

**Comment by kyazdani42** [comment]
i've added that with almost no config yet, looks good and i don't have to defer it ! done in b5ef2fb
