### ISSUE TITLE
Feature Request: A way to opt-out of default key bindings

### ISSUE THREAD

**Issue by davidxmoody** [kyazdani42/nvim-tree.lua#282]
Hi, thanks for the plugin, I've been using it for a while and really like it.

I have a minor issue with the way that key bindings are defined. For general navigation, I like to use the `o` key to trigger easymotion:

```
map o <Plug>(easymotion-overwin-f2)
```

However, the default nvim-tree keybindings override this. As far as I can tell, I would currently have two options if I wanted to opt-out of the nvim-tree default "edit" keybinding for that key:

1. Opt out of all keybindings (with `let nvim_tree_disable_keybindings=1`) and then figure out a way to bring back all the ones I still wanted (which I'm not really sure how to easily do)
2. Find some kind of binding that I can override in the config to bring back the default behaviour I want (maybe something like `["o"] = "<Plug>(easymotion-overwin-f2)",` except that that won't actually work due to the bindings being done with noremap and the `<Plug>` style not working with that)

However, I like the way of setting up keybindings with the `vim.g.nvim_tree_bindings` option as described in the docs. Without that, I'd have to figure out some other custom way to create the bindings in the buffer at the right time (if there's already a simple way to do that which I've missed, please let me know).

I think what would be ideal from my perspective would be a way to keep the keybinding setup that already happens but just to opt-out of the existing defaults. Opting out of the defaults would force a user to re-define everything they wanted (probably by copy-pasting from the docs first) but I think that would be fine and is what many other plugins do anyway.

A new flag could perhaps be added. Something like `let nvim_tree_disable_default_keybindings=1`

Or alternatively, the behaviour of the existing flag (`let nvim_tree_disable_keybindings=1`) could be changed to have that behaviour. If someone had already been opting out of keybindings then they probably weren't defining their own keybindings with `vim.g.nvim_tree_bindings` so it wouldn't really be much of a breaking change.

In terms of implementation, it would probably be a case of removing the early return in `set_mappings` and moving that check into `get_bindings`. I'm still pretty new to lua but would be happy to create a pull-request for this if you think it's a good idea.

**Comment by kyazdani42** [comment]
i think i'd like to keep the bindings simple. You can actually bind your plug function with `au Filetype NvimTree :lua vim.api.nvim_buf_set_keymap(0, 'n', 'o', '<plug>(easymotion-overwin-f2)` i think

**Comment by sindrets** [comment]
@davidxmoody A hacky workaround for this that I am using at the moment is to run this somewhere early (*not lazy loaded*) in your config:

```lua
-- Remove all default bindings.
require'nvim-tree.view'.View.bindings = {}
```

This way you are essentially "opting out of default keybindings" and NvimTree won't set any of the bindings that you don't specify in `vim.g.nvim_tree_bindings`.

**Comment by davidxmoody** [comment]
I just updated to the most recent version of the plugin and the new `custom_only` option does what I was asking for 👍 

For reference, I'm using something like this:

```
local tree_cb = require("nvim-tree.config").nvim_tree_callback

require("nvim-tree").setup({
  view = {
    mappings = {
      custom_only = true,
      list = {
        { key = {"<CR>", "i", "<2-LeftMouse>"}, cb = tree_cb("edit") },
      },
    },
  },
})
```
