### ISSUE TITLE
"➛" for symlink should be configurable

### ISSUE THREAD

**Issue by kabouzeid** [kyazdani42/nvim-tree.lua#283]
https://github.com/kyazdani42/nvim-tree.lua/blob/82b20f5b5ed741d2e6360990ee11a50f0cd253a4/lua/nvim-tree/renderer.lua#L279

The "➛" symbol when showing a symlink should be configurable. If you agree I can make a PR :)

**Comment by kyazdani42** [comment]
indeed, go for it
