### ISSUE TITLE
Option g:nvim_tree_hijack_netrw not works

### ISSUE THREAD

**Issue by Shatur95** [kyazdani42/nvim-tree.lua#286]
Option `g:nvim_tree_hijack_netrw = 0` does not work either by default or when specified explicitly. Opening a directory opens an empty buffer.

**Comment by kyazdani42** [comment]
did you also set `g:nvim_tree_disable_netrw = 0` ?

**Comment by Shatur95** [comment]
> did you also set g:nvim_tree_disable_netrw = 0 ?

No, I left this unchanged (default).

**Comment by Shatur95** [comment]
Here is my full configuration:

```lua
vim.api.nvim_set_keymap('', '<A-f>', '<Cmd>NvimTreeFindFile<CR>', { noremap = true })

vim.g.nvim_tree_follow = 1
vim.g.nvim_tree_group_empty = 1
vim.g.nvim_tree_show_icons = {
  git = 0,
  folders = 1,
  files = 1
}

vim.g.nvim_tree_icons = {
  default = ''
}

vim.g.nvim_tree_bindings = {
  ['l'] = '<Cmd>lua require"nvim-tree".on_keypress("edit")<CR>',
  ['h'] = '<Cmd>lua require"nvim-tree".on_keypress("close_node")<CR>',
}

-- Disable additional decorations
vim.cmd('highlight! default NvimTreeSpecialFile guifg=orange')
vim.cmd('highlight! default NvimTreeExecFile guifg=none guibg=none gui=NONE')
```

**Comment by kyazdani42** [comment]
nvim_tree_disable_netrw defaults to 1, which disables completely netrw. Please set this to 0 if you want netrw instead of nvim-tree

**Comment by Shatur95** [comment]
> nvim_tree_disable_netrw defaults to 1, which disables completely netrw. Please set this to 0 if you want netrw instead of nvim-tree

I'm sorry, I made a typo. I meant that `g:nvim_tree_hijack_netrw = 1` not works (default).
So, even without any configuration the command `nvim .` results to an empty buffer.

**Comment by kyazdani42** [comment]
i'm not sure what you mean:
nvim_tree_hijack_netrw = 1 -> will disable netrw for opening (but keeps its functionnalities)
nvim_tree_disable_netrw = 1 -> disable completely netrw, both view and functionnalities
These options are not supposed to do anything else than removing netrw view or functionnalities, if you wish to open nvim-tree automatically, use `nvim_tree_auto_open = 1`

**Comment by Shatur95** [comment]
> nvim_tree_hijack_netrw = 1

This option should open nvim-tree instead of netrw on directories, right?

**Comment by kyazdani42** [comment]
no this option only avoid netrw opening at all but doesn't do anything related to nvim-tree. I'll push something soon to implement the feature asked to open the tree when editing a directory

**Comment by Shatur95** [comment]
Thanks for the clarification. I would just expect this option to open `nvim-tree`.

What do you think about something like the following:

```lua
function M.hijack_directory()
  if vim.fn.isdirectory(vim.fn.expand('%')) == 0 then
    return
  end
  -- Call nvim-tree
end
```

Wit this autocmd:

```vim
autocmd vimrc BufEnter * ++nested lua require('nvim-tree').hijack_directory()
```

**Comment by kyazdani42** [comment]
its been asked before, i'm currently working on this :)

**Comment by Shatur95** [comment]
> its been asked before, i'm currently working on this :)

Ah, I thought to send PR myself. Okay, awesome, thanks! :)

**Comment by kyazdani42** [comment]
well i'm currently refactoring the whole buffer/window thing so i don't really want users to mess around with the existing code because i'd have to reimplement the feature anyway x)

**Comment by Nikola-Milovic** [comment]
Hey, any news on this? Using this setup 

```
local M = {}

function M.setup()
	local nvim_tree = require("nvim-tree")
	nvim_tree.setup({
		disable_netrw = true,
		hijack_netrw = true,
		respect_buf_cwd = true,
		view = {
			number = true,
			relativenumber = true,
		},
		filters = {
			custom = { ".git" },
		},
		update_cwd = true,
		update_focused_file = {
			enable = true,
			update_cwd = true,
		},
	})
end

return M
```

And when I `nvim .` in a directory, I still get netrw which doesn't seem like the default behavior

**Comment by alex-courtis** [comment]
> And when I `nvim .` in a directory, I still get netrw which doesn't seem like the default behavior

That sounds like a bug. I can't reproduce with my setup. Please raise a new [bug report](https://github.com/kyazdani42/nvim-tree.lua/issues/new?assignees=&labels=bug&template=bug_report.yml) with a minimal configuration that can replicate this. OS, neovim version etc. very important.

This is likely a timing issue; events at startup, especially with netrw, are unpredictable. I recall similar issues in the past. Perhaps there is a way to completely disable netrw...

**Comment by alex-courtis** [comment]
@Nikola-Milovic please try disabling netrw:

`:help netrw-noload`

Do this at the very start of your setup:
```vim
	:let g:loaded_netrw       = 1
	:let g:loaded_netrwPlugin = 1
```

**Comment by alex-courtis** [comment]
I've not been able to reproduce your setup... please provide a complete init.lua that demonstrates the issue.

What is `cmd = { "NvimTreeToggle", "NvimTreeClose" },` doing? Perhaps it is closing the tree on startup...

Let's follow this issue in #1270 

A practical solution might be to direct the users to explicitly set `g:loaded_netrw` as was successful in your case.
