### ISSUE TITLE
Allow configuring list of files for NvimTreeSpecialFile coloring

### ISSUE THREAD

**Issue by languitar** [kyazdani42/nvim-tree.lua#291]
I am not sure if this is really an nvim-tree issue, but maybe I can at least get a clue on how to find the origin.

In all projects, nvim-tree highlights README.md files in a strange way with indented filename and underlining. Files are without git modifications or other things:

![image](https://user-images.githubusercontent.com/1336287/114713941-ea03ad80-9d31-11eb-8aba-d2d7f9176f07.png)

There's no active highlight group in the respective line. Therefore, I don't know how to find out what is causing this. This also happens with complete defaults for the configuration and no icon configured for md or as a default.

**Comment by kyazdani42** [comment]
could not reproduce, the highlight group is NvimTreeSpecialFile. I highlight this as per the `exa` command which i use as ls replacement and i think looks good with my configs.
Could this may be related to how your terminal handles unicode character ?

**Comment by languitar** [comment]
Interesting, why can't I query the highlight group with [this vimscript function](https://github.com/languitar/config-nvim/blob/main/home/.config/nvim/autoload/myhelpers.vim#L9)?

Looking at the defined highlight groups, I can at least see why the entry gets underlined:
![image](https://user-images.githubusercontent.com/1336287/114829511-757d4d00-9dcb-11eb-9e44-a758fac4e8d3.png)

Do you understand how this happens? I have no special configuration for this highlight group in my own configuration and I also can't find a link to an existing group or a special underline declaration in this code base here.

**Comment by kyazdani42** [comment]
because this is a default, which is what i like. I think you should be able to override that. Maybe you cannot get the hl group with synID and synstack because i use luahl which is not handled like the vim hl, i'm not expert in that area but i believe this has something to do with extmarks and decorations (but i could be wrong)

**Comment by languitar** [comment]
Alright, interesting that there are two coloring approaches then... I've just had a look at the source how "special" is defined. Can the list of types somehow be configured? The documentation doesn't state anything in that direction. I suspect what is "special" is very subjective and being able to configure this would be a nice addition.

**Comment by kyazdani42** [comment]
i guess we could do that, i'm going to change the subject of the issue to match the required option configuration :)

**Comment by languitar** [comment]
Sounds like a good plan :) 👍

**Comment by kyazdani42** [comment]
i pushed 48b06ed which implements this, you can set `vim.g.nvim_tree_special_files = { }` with a list of filenames (refer to the docs for more information)

**Comment by languitar** [comment]
Thanks, works as expected :)
