### ISSUE TITLE
Option to disable signcolumn

### ISSUE THREAD

**Issue by sam20908** [kyazdani42/nvim-tree.lua#292]
I don't think this looks so good personally 😄 
![image](https://user-images.githubusercontent.com/18388795/114728960-69728c00-9cf4-11eb-8906-27f380358912.png)

Notice the signcolumn on the left.

**Comment by cloggier** [comment]
You can use autocommand on `NvimTree` filetype to disable it for the buffer.

**Comment by kyazdani42** [comment]
you can also change the color of your signcolumn. But i leave it here because it's a better default and i'm might use it for some features at some point.

**Comment by kyazdani42** [comment]
i've set signcollumn as normal in the window options to avoid these kind of weird looking sign columns in the future, closing this in the meantime :) you can indeed disable signcolumn when nvim-tree's buffer was loaded.

**Comment by mbenford** [comment]
@gegoune The autocmd solution doesn't seem to be working. The autocmd itself runs correctly, but `signcolumn` is overridden with `yes`.  Do you know what might be causing this behavior?

FWIW, here's my autocmd:

```vim
augroup CUSTOM
	autocmd!
  ...
	au FileType NvimTree setlocal signcolumn=no
augroup END
```

**Comment by gegoune** [comment]
@mbenford try `WinEnter,BufWinEnter` events rather than `FileType`.

**Comment by mbenford** [comment]
@gegoune same behavior. It seems like nvim-tree is always overriding the `signcolumn` option.

**Comment by gegoune** [comment]
```lua
require('nvim-tree.view').View.winopts.signcolumn = 'no'
```
seems to work. You were right, autocmds did not work for whatever reason.

**Comment by mbenford** [comment]
Thanks. I think this issue explains why it's not working: #364
