### ISSUE TITLE
Two issues with initialisation

### ISSUE THREAD

**Issue by cloggier** [kyazdani42/nvim-tree.lua#293]
Hey @kyazdani42, since rewrite of view library I am having trouble setting up autocommand for NvimTree.

I tried
- `BufWinEnter NvimTree` but it does not seem to be triggered on `require "nvim-tree".find_file(true)` (also tried `BufEnter` and `WinEnter`)
- `FileType NvimTree` but it gets triggered as soon as the plugin initialises even without opening tree buffer (so affects the buffer I don't want it to affect).

(Edit): It also seem to be not triggering auto commands such as `BufLeave,BufWinLeave,WinClosed NvimTree` when file is selected with `enter` or with `<c-{x,v}`.

What would be the correct way of doing it now?

Also, I have a very minor issue with express_line, plugin from @tjdevries setting up status line. It works just fine except for nvim-tree buffer, where it fails to set statusline on initial window opening. If I then switch windows and come back to Nvim-tree's one it does set statusline as expected. But opening, closing and opening Nvim-trees window does not work. Would you happen to know if that is an issue with express_line or nvim-tree?

**Comment by kyazdani42** [comment]
hmmm, well i've changed a bit the way the buffer/window handling is working. Basically i now create the buffer whenever the plugin is loaded, which i never destroy. BufEnter should work though. I never destroy the plugin because i use nvim_hide_win instead of nvim_close_win which does not delete the underlying buffer but only hides it, which might cause BufWinLeave, WinClosed command to never be called.
maybe nvim-tree is loading before the express_line plugin which will not add a status line to the window ? i'm not sure but i've notice my own status line has an issue removing it from the nvim-tree window as i want it too, i'm going to investigate this issue.

**Comment by evolify** [comment]
When I open a file via <CR>, BufLeave/WinLeave not triggered，how can I get it to work?

**Comment by evolify** [comment]
After update, it works, thank you @kyazdani42

**Comment by cloggier** [comment]
`BufLeave,WinClose NvimTree` is working again, awesome @kyazdani42 , thanks! But `WinEnter,BufWinEnter NvimTree` seems not to be triggered still.

**Comment by kyazdani42** [comment]
yep i'll do a bit more debugging tonight because this issue bothers me a little, i'm not sure where this comes from.

**Comment by kyazdani42** [comment]
haven't managed to get why the BufWinEnter doesn't trigger in nvim-tree's window :/ could it be that ?
```
nvim_win_set_buf({window}, {buffer})                      *nvim_win_set_buf()*
                Sets the current buffer in a window, without side-effects
```
WinEnter works fine though with NvimTree.

**Comment by kyazdani42** [comment]
yup this was the culprit, pushing the last fix !

**Comment by cloggier** [comment]
Works perfect, thank you very much!

**Comment by cloggier** [comment]
@kyazdani42 how about statusline issue? I know it's pretty minor. 😀 

Should I create separate one or would you mind reopening this one?

Thanks for all your great work!

**Comment by kyazdani42** [comment]
hum mine is working fine, i'm going to investigate. Reopening this in the meantime

**Comment by cloggier** [comment]
It works fine now, after some updates today. Thanks and apologise for the noise. Last issue before reaching perfection is git root detection. There is other ticket for it though.

You rock buddy!

**Comment by b0o** [comment]
I was wanting to run a function on `FileType NvimTree` but as @gegoune said this event gets triggered as soon as the plugin initializes which happens before my autocommand is defined.

It would be nice if there was a setting to configure this, like `g:nvim_tree_auto_init` which defaults to enabled (current behavior) but could be disabled if desired.

I ended up overriding `plugin/tree.vim` like this as a work around:


```vim
if !has('nvim-0.5') || exists('g:loaded_tree_override') | finish | endif

let s:save_cpo = &cpo
set cpo&vim

if get(g:, 'nvim_tree_disable_netrw', 1) == 1
    let g:loaded_netrw = 1
    let g:loaded_netrwPlugin = 1
endif

let s:nvimTreeStarted = 0

function! s:nvimTreeStart()
  if s:nvimTreeStarted == 1 | return | endif
  let s:nvimTreeStarted = 1
  augroup NvimTree
    au!
    if get(g:, 'nvim_tree_hijack_netrw', 1) == 1 && get(g:, 'nvim_tree_disable_netrw', 1) == 0
      silent! autocmd! FileExplorer *
    endif
    au BufWritePost * lua require'nvim-tree'.refresh()
    if get(g:, 'nvim_tree_lsp_diagnostics', 0) == 1
      au User LspDiagnosticsChanged lua require'nvim-tree.diagnostics'.update()
    endif
    au BufEnter * lua require'nvim-tree'.buf_enter()
    if get(g:, 'nvim_tree_auto_close') == 1
      au WinClosed * lua require'nvim-tree'.on_leave()
    endif
    au ColorScheme * lua require'nvim-tree'.reset_highlight()
    au User FugitiveChanged,NeogitStatusRefreshed lua require'nvim-tree'.refresh()
    if get(g:, 'nvim_tree_tab_open') == 1
      au TabEnter * lua require'nvim-tree'.tab_change()
    endif
    au SessionLoadPost * lua require'nvim-tree.view'._wipe_rogue_buffer()
    if get(g:, 'nvim_tree_hijack_cursor', 1) == 1
      au CursorMoved NvimTree lua require'nvim-tree'.place_cursor_on_node()
    endif
    if get(g:, 'nvim_tree_update_cwd') == 1
      au DirChanged * lua require'nvim-tree.lib'.change_dir(vim.loop.cwd())
    endif
  augroup END
endfunction

command! -bar NvimTreeStart call s:nvimTreeStart()

command! NvimTreeOpen NvimTreeStart | lua require'nvim-tree'.open()
command! NvimTreeClose NvimTreeStart | lua require'nvim-tree'.close()
command! NvimTreeToggle NvimTreeStart | lua require'nvim-tree'.toggle()
command! NvimTreeFocus NvimTreeStart | lua require'nvim-tree'.focus()
command! NvimTreeRefresh NvimTreeStart | lua require'nvim-tree'.refresh()
command! NvimTreeClipboard NvimTreeStart | lua require'nvim-tree'.print_clipboard()
command! NvimTreeFindFile NvimTreeStart | lua require'nvim-tree'.find_file(true)
command! -nargs=1 NvimTreeResize NvimTreeStart | lua require'nvim-tree'.resize(<args>)

if get(g:, 'nvim_tree_auto_init', 1) == 1
  call s:nvimTreeStart()
endif

let &cpo = s:save_cpo
unlet s:save_cpo

let g:loaded_tree_override = 1

```

**Comment by kyazdani42** [comment]
do not, i've removed plugin/tree.vim in the setup refactoring :smile: 
What's your use case to run an autocmd on filetype for nvim-tree ? Maybe this could be achieved some other way

**Comment by b0o** [comment]
@kyazdani42 Actually your refactoring fixed the issue for me, since now nvim-tree doesn't create the buffer until the setup function is called. Thank you!
