### ISSUE TITLE
Multi task

### ISSUE THREAD

**Issue by thevan96** [kyazdani42/nvim-tree.lua#298]
How to delete, copy, move multi-file/folder

**Comment by kyazdani42** [comment]
duplicate of #221

**Comment by xorander00** [comment]
Seconded, would be helpful in my case too.  I'm still a Lua newbie (but not a coding newbie), but if there's anything I can do to help, I'd be happy to contribute.  I can at least test, or maybe next week explore implementation if you can give me pointers on where to start.

**Comment by kyazdani42** [comment]
i think it would not be too hard to do. I'd create a batch operation dictionary in a new file (with new mappings), with `signs` for UI information (in the `signcolumn`), and once the batch operation is accepted, just run the operations one by one with help of `fs.lua`.

**Comment by thevan96** [comment]
@kyazdani42 Is this feature already available?

**Comment by alex-courtis** [comment]
> @kyazdani42 Is this feature already available?

It is still a work in progress.
