### ISSUE TITLE
Error when trying to execute the function "close node"

### ISSUE THREAD

**Issue by DilanGMB** [kyazdani42/nvim-tree.lua#299]
### Description
About two days ago, after syncronizing all my plugins, I noticed that my Nvim-Tree stopped working correctly, since I noticed that the function to close or collapse the node no longer fulfilled its function, giving me the following error when I tried to use it. "E5108: Error executing lua ...te/pack/packer/packer/start/nvim-tree.lua/lua/nvim-tree/lib.lua:338: attempt to call field 'winnr' (a nil value)", 
I have also noticed that when I navigate with the tree, the directories of a higher level (sometimes lower) than the one I am in suddenly close, and when I try to delete a file or a directory, when I use its key, it takes a long time to do it (I already checked if I had this map repeated, but in none of my maps intervenes the key assigned to the tree to perform this function).

In the following image you can see the error I mention, plus my configuration file for nvim-tree, which has nothing more than the default settings recommended in the official repository.
In my configuration file it is possible to notice that I have certain keys determined for the function that is failing, but when removing them the error is still presented. 

### Preview
![error](https://user-images.githubusercontent.com/65829671/114928250-ffdba600-9df7-11eb-81aa-a6edaeac08f6.png)

### Extra information:
- OS: Ubuntu 20.04
- Editor: NVIM v0.5.0-dev (LuaJIT 2.1.0-beta3)

**Comment by kyazdani42** [comment]
fixed in latest master, sorry for the inconvenience :)
