### ISSUE TITLE
Creating a directory

### ISSUE THREAD

**Issue by jemag** [kyazdani42/nvim-tree.lua#3]
First of all, I want to say that I am really enjoying this plugin so far, especially coming from having tried nerdtree -> coc-explorer -> defx.

I am wondering, is there a way to create a directory, just like you can create files from nvim-tree? If not, would it be something possible to implement?

**Comment by kyazdani42** [comment]
Hi,
I'm glad you're enjoying this plugin.
Currently, you can create a directory by adding a `/` to the end of a path.
Also, you can create directories dynamically when creating a file (like `/foo/bar/baz/file.txt`).
I don't really like the way i do file handling, i might work on a refactoring someday to make it easier to work with. If you have any ideas for the ux feel free to submit them :)

**Comment by martin-braun** [comment]
@kyazdani42 But what if I want to move a file to a new folder? I tried to rename the file, but it requires the folder to be in existence before-hand. Copying the file and removing the old one feels redundant. A force rename that runs `mkdir -p` of the `dirname` would be preferable.

**Comment by magoz** [comment]
Same question than @martin-braun. When renaming files, how can we force folder creation if they don't exist?

**Comment by alex-courtis** [comment]
Confirmed: `mkdir -p` behaviour is done for create, but not rename or copy to new path.

Raised #1818
