### ISSUE TITLE
Error executing lua view.lua - attempt to call field 'nvim_win_hide' (a nil value)

### ISSUE THREAD

**Issue by afonsocarlos** [kyazdani42/nvim-tree.lua#305]
After updating the plugin today I started getting the error

`E5108: Error executing lua .../.config/.nvim/plugged/nvim-tree.lua/lua/nvim-tree/view.lua:151: 
attempt to call field 'nvim_win_hide' (a nil value)`

**Comment by xcession** [comment]
same

**Comment by afonsocarlos** [comment]
Ok just figured out it's a problem with versioning. Neovim recently released the function `nvim_win_hide`, so just updating your `neovim` with its master HEAD should solve it!

**Comment by kyazdani42** [comment]
oh ! i didn't realize that this was all new :) thanks for noticing yourself !
