### ISSUE TITLE
Keybindings unresponsive

### ISSUE THREAD

**Issue by pedropmedina** [kyazdani42/nvim-tree.lua#308]
No sure what happened, but following the latest update none of the keybindings are working. I try deleting my custom keybinding and nothing. I followed the steps in the README. Am I missing something?

**Comment by williamboman** [comment]
I've been experiencing the same issue this week. I did a `git bisect` and it seems to have been introduced by ff814676d59bc9c721ebdb873390cdf960ec1442.

**Comment by kyazdani42** [comment]
works just fine for me, but the buffer is initialized only once if you don't delete it manually, so maybe as it's define very early in the setup process, you should define the `vim.g.nvim_tree_bindings` before sourcing the plugin. Maybe i should add that in the docs.

**Comment by pedropmedina** [comment]
@kyazdani42 not event the default key binding are working for me?

**Comment by kyazdani42** [comment]
i'd need really more informations than just 'is not working'. Could you please provide:
commit number
neovim version
a minimal sample config

**Comment by pedropmedina** [comment]
Hey @kyazdani42 can you take a look at my config here https://github.com/pedropmedina/dotfiles/tree/master/nvim. I'm up to date with your latest commit and here's my neovim version.

```
NVIM v0.5.0-dev+1260-ga6504ec33
Build type: Release
LuaJIT 2.1.0-beta3
```

**Comment by kyazdani42** [comment]
thanks, fixed in latest master. For the record, `not 0` is false in lua

**Comment by pedropmedina** [comment]
Thanks a lot @kyazdani42. What do you mean by ```not 0``` being false in lua? 
Also should the value for the options be an integer 1/ 0 or true/false when setting them in lua? 
e.g. ```vim.g.nvim_tree_gitignore = 1 or vim.g.nvim_tree_gitignore = true```

**Comment by kyazdani42** [comment]
i tried `if not vim.g.nvim_tree_disable_keybindings` before setting keybindings, and this is what was failing, thus i had to change it to `if vim.g.nvim_tree_disable_keybindings ~= 1`. Basically `0` is consider truthy in lua which i completely forgot about

**Comment by kyazdani42** [comment]
follow the docs, i usually ask for 1 or 0 values as it's easier for interoping with vim :)
