### ISSUE TITLE
Nvim-tree will affect the file highlighting after setting a color scheme.

### ISSUE THREAD

**Issue by AnthonyK213** [kyazdani42/nvim-tree.lua#310]
Neovim 0.5 on WSL and the same issue on Windows.  Tested with a minimized configuration.

**To reproduce**

Change the color scheme (`:colorscheme torte` e. g.), the highlight of nvim-tree will affect other buffers at the same lines.
Before setting color scheme:
![wsl_a](https://user-images.githubusercontent.com/29994167/115122593-46ddbd00-9feb-11eb-9463-c423d59be40b.jpg)
After `:colorscheme torte`:
![wsl_b](https://user-images.githubusercontent.com/29994167/115122609-56f59c80-9feb-11eb-87a7-e0b87ebfc5cb.jpg)

**Comment by kyazdani42** [comment]
isn't this just the cursorcolumn highlighting being changed that applies basically on every window ^^' ? i don't think this is nvimtree related, when setting colorscheme it will apply in every buffer.

**Comment by AnthonyK213** [comment]
The cursorcolumn is ok, the problem is inside  the red box I drew - the top few lines of lua code should be highlighted as comment, but they are highlighted the same as the buffer of nvim-tree in the second screenshot.

**Comment by kyazdani42** [comment]
indeed good catch ! the reset highlight was using the old `lib.Tree.bufnr` which is now `view.View.bufnr`. 
Fixed in latest master.
