### ISSUE TITLE
:NvimTreeToggle will close the tree in different tab

### ISSUE THREAD

**Issue by sainnhe** [kyazdani42/nvim-tree.lua#311]
## Steps to reproduce this bug

1. Open nvim and execute `:NvimTreeToggle`
2. Create a new tab and switch to it via `:tabnew`
3. Execute again `:NvimTreeToggle`

## Actual behavior

The tree window will be closed in the first tab.

## Expected behavior

Keep the tree window open in the first window, and create a new tree window in the second tab.

I don't know if this is a bug or a feature, but if this design is intentional, could you add a parameter that can create a new window in another tab?

**Comment by kyazdani42** [comment]
tab handling is not properly made yet, i should record windows per tab page (i did that in a previous attempt to refactor the whole plugin which i abandonned at some point due to the number of changes required and possible breaks).
I'll add that today
