### ISSUE TITLE
Not read mounted directory (sshfs)

### ISSUE THREAD

**Issue by lvim-tech** [kyazdani42/nvim-tree.lua#316]
nvim-tree not read directory when mounted with sshfs.
Any ideas?

**Comment by kyazdani42** [comment]
Hi, i'm not sure if there are some things we need to implement in order to use the tree in remote filesystems. I will check this out when i have some time.

**Comment by lvim-tech** [comment]
@kyazdani42 Thanks in advance

**Comment by S0mbr3** [comment]
It would be really lovely, being able to use it over mounted sshfs folders.

**Comment by kyazdani42** [comment]
related #425

**Comment by exdeniz** [comment]
I have the same problem with sshfg

**Comment by kyazdani42** [comment]
it's an issue with fuse and libuv, you need to set `UV_THREADPOOL_SIZE` to a higher value when launching neovim to allow libuv to wait for the files to load (because the fs is asynchronous)

**Comment by kyazdani42** [comment]
not sure then, i'm not a libuv expert myself :/ i'll try to see if other plugins have tackled this issue

**Comment by exdeniz** [comment]
I tried Defx and NerdTree, both work well.

**Comment by kyazdani42** [comment]
i guess so but none of them uses the libuv unfortunately (which makes this plugin fast). I'm not sure but maybe because i use synchronous libuv calls it fails, if i could manage to list the entries asynchronously, it might fix this issue.

**Comment by kyazdani42** [comment]
fixes in 7abec5e5943. Actually fs_scandir wasn't returning the file type which made all entries being ignored, running an fs_stat fixed the issue :)

**Comment by lvim-tech** [comment]
Perfect! Works! Thank you, @kyazdani42 !

**Comment by exdeniz** [comment]
Thank you, @kyazdani42 !
