### ISSUE TITLE
Empty nvim-tree on first time open nvim

### ISSUE THREAD

**Issue by vpeopleonatank** [kyazdani42/nvim-tree.lua#317]
## Step to reproduce
1. Open nvim
2. `:NvimTreeOpen`
3. Get empty nvim-tree
![image](https://user-images.githubusercontent.com/30976876/115198367-29f4d700-a11c-11eb-8f11-3177ff827e97.png)
4. Close and reopen nvim-tree, or `NvimTreeRefresh` will show files and folders
![image](https://user-images.githubusercontent.com/30976876/115198514-54df2b00-a11c-11eb-8e8c-c5bb63663965.png)

## Expected result
Show file and folders on first run

**Comment by kyazdani42** [comment]
hi, follow discussion on #280, you might be lazy loading the tree
