### ISSUE TITLE
Open tree without moving the cursor to it

### ISSUE THREAD

**Issue by litearc** [kyazdani42/nvim-tree.lua#318]
Is there a way to open (or toggle) the tree without moving the cursor to the tree window? It would be nice if there was an option. Thanks!

**Comment by sindrets** [comment]
@litearc You can implement that yourself with something like this:

```vim
function! NvimTreeToggleNoFocus()
lua << EOF
    local view = require'nvim-tree.view'
    if view.win_open() then
        view.close()
    else
        view.open()
        vim.cmd("wincmd p")
    end
EOF
endfunction
```

**Comment by kyazdani42** [comment]
i should start dropping default commands in favor of a better documentation :D I consider this as closed if you don't mind :)
