### ISSUE TITLE
[bug] there is a error when open nvim at $HOME dir

### ISSUE THREAD

**Issue by cossonleo** [kyazdani42/nvim-tree.lua#32]
Error detected while processing VimEnter Autocommands for "*":

E5108: Error executing lua .../.config/nvim/plugged/nvim-tree.lua/lua/lib/renderer.lua:39: attempt to get length of local 'extension' (a nil value)

**Comment by kyazdani42** [comment]
that's weird, im gonna take a look later today !

**Comment by kyazdani42** [comment]
@cossonleo could you give me the output of `ls -la` in your $HOME dir please?

**Comment by cossonleo** [comment]
@kyazdani42 Sorry, I can't reproduce the bug

**Comment by kyazdani42** [comment]
okay, I'll keep this open so if we can reproduce we'll fix this

**Comment by stsewd** [comment]
I'm getting a similar error with `:LuaTreeFindFile`

![Screenshot from 2020-06-20 19-18-31](https://user-images.githubusercontent.com/4975310/85213957-d7dffb00-b32a-11ea-8242-1801a6c9f50d.png)

**Comment by kyazdani42** [comment]
the error you mentionned here is different @stsewd

**Comment by kyazdani42** [comment]
please reopen this issue if it appears again
