### ISSUE TITLE
Highlight current file

### ISSUE THREAD

**Issue by PSeitz** [kyazdani42/nvim-tree.lua#322]
When opening a file in a buffer, the tree automatically expands to the file, which is cool.
It would be nice if it would be possible to highlight the file in the tree. I didn't find such an option, sorry if it already exists.

**Comment by sindrets** [comment]
If you have `g:nvim_tree_follow` enabled, which it sounds like you have, just make sure to enable `cusorline` in the NvimTree window.

**Comment by PSeitz** [comment]
Thanks, works. didn't know there is a cursor in unfocused buffers

**Comment by cloggier** [comment]
This `if` condition is unnecessary. You can simply do:

```viml
autocmd BufEnter NvimTree set cursorline
```
