### ISSUE TITLE
Tree side-view closes when re-editing (:e) file buffer or jumping across buffers

### ISSUE THREAD

**Issue by edementyev** [kyazdani42/nvim-tree.lua#323]
Hi! Thanks for your continuous work on this awesome plugin.

I have `vim.g.nvim_tree_quit_on_open = 0`.
After a recent update (a couple of days ago) tree closes every time I `:edit` a buffer, or move around buffers with `<C-o>` or `<C-i>`. My guess is that it's somehow related to BufEnter event, but couldn't find anything that can introduce such behavior. 
Full list of my options for nvim-tree:

```lua
vim.g.nvim_tree_auto_open = 1 --0 by default, opens the tree when typing `vim $DIR` or `vim`
vim.g.nvim_tree_indent_markers = 1 --0 by default, this option shows indent markers when folders are open
vim.g.nvim_tree_git_hl = 1 --0 by default, will enable file highlight for git attributes (can be used without the icons).
vim.g.nvim_tree_tab_open = 1 --0 by default, will open the tree when entering a new tab and the tree was previously open
vim.g.nvim_tree_hijack_netrw = 1 --1 by default, prevents netrw from automatically opening when opening directories (but lets you keep its other utilities)
vim.g.nvim_tree_side = 'left' --left by default
vim.g.nvim_tree_width = 30 --30 by default
vim.g.nvim_tree_ignore = {} --empty by default
vim.g.nvim_tree_gitignore = 0 --0 by default
vim.g.nvim_tree_auto_close = 0 --0 by default, closes the tree when it's the last window
vim.g.nvim_tree_auto_ignore_ft = {} --empty by default, don't auto open tree on specific filetypes.
vim.g.nvim_tree_quit_on_open = 0 --0 by default, closes the tree when you open a file
vim.g.nvim_tree_hide_dotfiles = 0 --0 by default, this option hides files and folders starting with a dot `.`
vim.g.nvim_tree_root_folder_modifier = ':~' --This is the default. See :help filename-modifiers for more options
vim.g.nvim_tree_width_allow_resize  = 0 --0 by default, will not resize the tree when opening a file
vim.g.nvim_tree_disable_netrw = 0 --1 by default, disables netrw
vim.g.nvim_tree_group_empty = 0 -- 0 by default, compact folders that only contain a single folder into one node in the file tree
vim.g.nvim_tree_lsp_diagnostics = 0 --0 by default, will show lsp diagnostics in the tree. See :help nvim_tree_lsp_diagnostics
vim.g.nvim_tree_show_icons = { ["git"]= 1, ["folders"]= 1, ["files"]= 1 }
```
Also I'm on neovim's latest `master` commit

**Comment by kyazdani42** [comment]
hi :)
could not reproduce with your config and neovim latest master.
could you provide me with a list of commands to run so i can reproduce this issue ?

**Comment by edementyev** [comment]
Apparently, this was an issue with [vim-stay](https://github.com/zhimsel/vim-stay), couldn't reproduce with minimal configuration, and after digging a little bit (which involved random plugin rip out 😃) found that disabling this plugin fixes my issue. Closing this issue. Thanks!

**Comment by jorgepurposeinplay** [comment]
@edementyev Thanks for posting the solution, I also had problems with vim-stay. I remembered having similar conflicts between vim-stay and other plugins before. If you still want to use vim-stay you can load the plugin after nvim-tree and both should work, at least it does for me.

**Comment by jmolero** [comment]
@edementyev Thanks for posting the solution, I also had problems with vim-stay. I remembered having similar conflicts between vim-stay and other plugins before. If you still want to use vim-stay you can load the plugin after nvim-tree and both should work, at least it does for me.
