### ISSUE TITLE
Changing symlink problems

### ISSUE THREAD

**Issue by cenk1cenk2** [kyazdani42/nvim-tree.lua#324]
Hello @kyazdani42 ,

I have been encountering a weird problem where it is reproducable with:

- There is a symlink in a folder.
- Deleting the symlink via terminal.
- Adding a new one via terminal.
- Refreshing `nvim-tree`

It always takes me back to the old symlink and never checks for whether symlink is changed during the refresh, is there a cache mechanism for it?

**Comment by kyazdani42** [comment]
Hi,
not sure what you mean here, there is a cache mecanism for refresh, but following what you did did not produce any strange behaviors. 
Could i have a minimal reproduction somehow ?

**Comment by sindrets** [comment]
I think he means that changing the link target of a symlink is not reflected in the tree, unless the symlink links to a directory. I put up a PR to fix this.
Minimal reproduction:

```sh
ln -s $(realpath ~/.zshrc) ./test-link
# The link is created in the tree and points to '~/.zshrc'
ln -sfn $(realpath ~/.profile) ./test-link
# The link node in the tree still points to '.zshrc'.
```

**Comment by kyazdani42** [comment]
ok i see, thanks for the PR again :)
