### ISSUE TITLE
Group folders in tree view

### ISSUE THREAD

**Issue by mvllow** [kyazdani42/nvim-tree.lua#329]
Is there an option to show all folders in a directory first, then the files below?

Edit: This may already be the behaviour, as it seems things got out of order when adding directories but restarting neovim shows them in proper order (with folders first). Feel free to close if this is intended 😌

**Comment by kyazdani42** [comment]
this is default behavior, when adding folder it goes in the right place for me (and even sorted by name so...) yep i'm closing this ^^
