### ISSUE TITLE
highlight gitignore icon doesn't highlight folder gitignore icon

### ISSUE THREAD

**Issue by kyazdani42** [kyazdani42/nvim-tree.lua#333]
refer to #320

**Comment by sindrets** [comment]
@kaykay38 Could you provide a minimal config that makes this reproducible? I am not seeing this behavior on my end.

**Comment by kaykay38** [comment]
@sindrets @kyazdani42 I have solved this issue. It was `g:nvim_tree_git_hl` I forgot to enable this. Thank you!
