### ISSUE TITLE
Showing incorrect and conflicting icons

### ISSUE THREAD

**Issue by Tinku10** [kyazdani42/nvim-tree.lua#336]
![nvimtree](https://user-images.githubusercontent.com/29244595/115718494-c75c3f00-a398-11eb-8071-06c514306254.png)

```NvimTree``` sometimes shows incorrect icons. 

In the image above, you can see the icons besides ```toggleterm.lua``` file are conflicting. It is detecting ```staged``` (check mark sign) file but it also marks it ```untracked``` (```-```) sign as well as ```unstaged``` (```o``` sign). 

It happened several times with me. Is there anything I am doing wrong? Here is my  [config file](https://github.com/Tinku10/nvim/blob/main/lua/plugins/nvimtree.lua) for ```NvimTree```.

**Comment by sindrets** [comment]
@Tinku10 If you run:

```sh
git status --porcelain=v1 | grep toggleterm.lua
```

I assume it should show something like

```
AM some/path/toggleterm.lua
```

This would imply that the file was previously untracked, it was then added to index, and then modified. This icon state is defined here:

https://github.com/kyazdani42/nvim-tree.lua/blob/96d8e20bffe3a330cc8bd5559650ddde5d34df1b/lua/nvim-tree/renderer.lua#L153-L157

So it is not a bug. But it seems to me like some of the current git icon states are unnecessarily verbose. If git can get away with using only 2 symbols for this state I think we can as well. For instance, VSCode uses only one symbol "M" and a color highlight for this state. Thoughts @kyazdani42 ?

**Comment by sindrets** [comment]
I personally think that using the icon combination "staged untracked" would suffice here. But like I explained, the current way is not wrong, and it means: File was previously untracked, then added to index, then modified. So the current icon state is *very* literal, but not wrong.

**Comment by Tinku10** [comment]
Okay, understood. Thanks @sindrets, should I keep this open until @kyazdani42  reply to your mention?

**Comment by sindrets** [comment]
He'll probably see it either way, so it's up to you:)

**Comment by kyazdani42** [comment]
Hi @Tinku10 , it is indeed very litteral, because i think it's the easiest way to inform the user about the specific state of a file. These are not conflicting, as sindrets said :)
What would you expect to see at first ?

**Comment by sindrets** [comment]
@kyazdani42 If I can give my 2 cents here: I think it's unnecessary to communicate that the file *was* untracked after it's been added. I think we should think about not making the file tree too cluttered. If Tinku10 had file icons enabled it would be 4 icons on one node here. I think we stand to gain from looking at how other editors handle VCS. Like I mentioned for instance vscode uses only 1 symbol and a color highlight for this exact state, and git itself never uses more than 2.

If the user ever needs very detailed information about the state of their files, they are better off using git directly anyway. I think we can safely change these:

```lua
{
    ["A "] = {
      { icon = icon_state.icons.git_icons.staged, hl = "NvimTreeGitStaged" },
      { icon = icon_state.icons.git_icons.untracked, hl = "NvimTreeGitNew" }
    },
    ["AM"] = {
      { icon = icon_state.icons.git_icons.staged, hl = "NvimTreeGitStaged" },
      { icon = icon_state.icons.git_icons.untracked, hl = "NvimTreeGitNew" },
      { icon = icon_state.icons.git_icons.unstaged, hl = "NvimTreeGitDirty" }
    },
}
```

To this:

```lua
{
    ["A "] = {
      { icon = icon_state.icons.git_icons.staged, hl = "NvimTreeGitStaged" },
    },
    ["AM"] = {
      { icon = icon_state.icons.git_icons.staged, hl = "NvimTreeGitStaged" },
      { icon = icon_state.icons.git_icons.unstaged, hl = "NvimTreeGitDirty" }
    },
}
```

What do you think?

**Comment by kyazdani42** [comment]
i guess it could work. A better impl would indeed be something like vscode, i'll see when i have some time if i can make the git rendering smarter.

**Comment by sindrets** [comment]
Sounds good. I'll put up a PR for my suggested change, if you don't mind?

**Comment by kyazdani42** [comment]
go for it

**Comment by Tinku10** [comment]
Thanks! I will close the issue now.
