### ISSUE TITLE
Highlights broken on sourcing vimrc

### ISSUE THREAD

**Issue by Akin909** [kyazdani42/nvim-tree.lua#34]
Just tried this out this plugin on my work mono repo of 100,000 files and approx 1500 subfolders and it was _so fast_ 😍 .

I'm still getting a few issues before I can make it my daily driver for work. I'll try and get a minimal vimrc reproduction once I get a chance.

<img width="931" alt="Screenshot 2020-06-05 12 20 57" src="https://user-images.githubusercontent.com/22454918/83871052-4025be80-a727-11ea-9669-dda65b958902.png">

**Comment by kyazdani42** [comment]
hey ! thanks :)
not sure i understand this issue, is the tree overwriting the highlight in your files ? are you sure it isn't related to something else ? I did not encounter something like that so i don't really know how to reproduce this ^^

**Comment by Akin909** [comment]
Yeah it's a pretty confusing one I'm not 100% sure what happening but the way I can reproduce it locally is it seems to be happening when I
1.) Open nvim tree
2.) Close nvim tree
3.) source my neovim config

I'll try with a minimal init.vim to make sure it isn't my config causing it, except the problem goes away when I don't have nvim tree loaded

**Comment by Akin909** [comment]
Okay so I managed to reproduce this with a minimal vimrc
```
call plug#begin(stdpath('data') . '/plugged')
Plug 'kyazdani42/nvim-web-devicons' " for file icons
Plug 'kyazdani42/nvim-tree.lua'
Plug 'rakr/vim-one' 
call plug#end()

colorscheme one
```

1) `nvim -u minimal.vim`
2) `LuaTreeOpen`
3) `LuaTreeClose`
4 `source /path/to/minimal.vim`

And the highlights are broken. Note, that if you try sourcing the minimal init.vim before `LuaTreeOpen` the highlights are fine

**Comment by kyazdani42** [comment]
well that's a strange one. I'm gonna investigate.

**Comment by kyazdani42** [comment]
ok well i found the bug. When sourcing, lua tree reevaluates even if it is closed, thus the Tree.bufnr is nil, which causes undefined behaviour. I'll push a fix, tell me if it fixes it on your side

**Comment by kyazdani42** [comment]
I'm closing this if everything is ok for you. Ask me to reopen if the issue still exists !

**Comment by Akin909** [comment]
Just tested it and it looks like it's fixed :+1:
