### ISSUE TITLE
If you close all visible buffers, nvimtree will open new buffers in new splits (not in current split)

### ISSUE THREAD

**Issue by gaetan-puleo** [kyazdani42/nvim-tree.lua#341]
Hi! I love your plugin.

I found a strange bug, I needed to test a lot of things to replicate it but here how to be sure to replicate it!

1 Take this minimal vimrc
```vim
call plug#begin()

Plug 'kyazdani42/nvim-tree.lua'

call plug#end()
```

2 Open nvim with an empty buffer with `nvim`.

3 type `:NvimTreeToggle`

4 Open a file with the `enter` key.
note: If you open a  new file after this, it will replace the previous file in the split (I think it's a wanted behavior).

5 close the split with a `:q`

6 Open a new file with the `enter` key (a split appear on the left now)

7 Go to the NvimTree Panel (ctrl+w and L) and open a new file again (a split will open on the middle now).

**Comment by kyazdani42** [comment]
Hi, i've been noticing these issues since a while. I will not be available for the next 2/3 weeks but when i'm back i'll fix that for sure. Thanks for the detailed repro though :)

**Comment by gaetan-puleo** [comment]
I just played around the function `M.open_file`.

It seems it can be related to `M.Tree.target_winid`, if this value in not correct you will split the screen again and again.

I think you need to call `M.set_target_win'` if no splits are `open`

I'm not sure at all of what I am saying, I wish I could help more but Lua is not my main language sorry :/ 

It's not urgent for me.

**Comment by sangdth** [comment]
I notice if I open a file at the beginning like `nvim ./something.js` then it will work fine. Open with bare `nvim` will cause this problem on my side.

Glad if you can fix it soon, still appreciate your works. Thank you.
