### ISSUE TITLE
Files are duplicating on calling NvimTreeToggle multiple times

### ISSUE THREAD

**Issue by 1bharat** [kyazdani42/nvim-tree.lua#342]
Config

```
use {
  'kyazdani42/nvim-tree.lua',
  cmd = 'NvimTreeToggle',
  config = conf.tree,
}

function conf.tree()
  vim.g["nvim_tree_indent_markers"] = 1
  vim.g["nvim_tree_follow"] = 1
  vim.g["nvim_tree_auto_close"] = 1
  vim.g["nvim_tree_width_allow_resize"] = 1
  vim.g["nvim_tree_side"] = "left"
  vim.g.nvim_tree_icons = {
    default =  '',
    symlink =  '',
    git = {
      unstaged = "✚",
      staged =  "✚",
      unmerged =  "≠",
      renamed =  "≫",
      untracked = "★",
    },
  }
  require"nvim-tree".on_enter()
end

```

Steps

- Open nvim-tree with `NvimTreeToggle`. Tree loads properly.
- Run the `NvimTreeToggle` twice again. Duplicate entries are created as in the screenshot.
- nvim-tree has the latest commits.

![Screen Shot 2021-04-24 at 7 31 03 pm](https://user-images.githubusercontent.com/6837979/115954329-b8f65a80-a533-11eb-9f84-6fda3673fc5e.png)
![Screen Shot 2021-04-24 at 7 31 36 pm](https://user-images.githubusercontent.com/6837979/115954374-feb32300-a533-11eb-8571-b941f74bdc27.png)

**Comment by sindrets** [comment]
Seems like this line in your config is being run on every toggle:

```lua
require"nvim-tree".on_enter()
```

I'm not very familiar with packer, so I don't know how you would configure this properly. But that is almost certainly the problem.

**Comment by sindrets** [comment]
Try to replace that line with this:

```lua
require'nvim-tree.events'.on_nvim_tree_ready(function ()
  vim.cmd("NvimTreeRefresh")
)
```

**Comment by 1bharat** [comment]
Thanks @sindrets. I used your code. It has fixed the issue for me. I am not seeing duplicate files and folders. nvim-tree lazy loads properly as well. 

```
require'nvim-tree.events'.on_nvim_tree_ready(function ()
  vim.cmd("NvimTreeRefresh")
end)
```
