### ISSUE TITLE
Can't toggle nvim tree

### ISSUE THREAD

**Issue by TornaxO7** [kyazdani42/nvim-tree.lua#343]
(I'm sorry I misclicked on "submitting" without any text. I'm writing it currently as another message here. Please wait a little bit)

**Comment by TornaxO7** [comment]
I have this mapping in my `init.vim`:
```vim
nnoremap <C-e> :NvimTreeToggle<CR>
```
Now if I press `<C-e>` for the first time. nvim-tree pops up as expected, but if I press `<C-e>` again, to close it, I'm getting this error message:
![image](https://user-images.githubusercontent.com/50843046/115956742-d2c97a80-a4fe-11eb-8ac1-6679f1ca43f3.png)

**Comment by sindrets** [comment]
Duplicate of #305. Update neovim.

**Comment by TornaxO7** [comment]
oh ok, thank you!
