### ISSUE TITLE
Turning off nvim_tree_highlight_opened_files not respected

### ISSUE THREAD

**Issue by vuki656** [kyazdani42/nvim-tree.lua#346]
I turned off `nvim_tree_highlight_opened_files` like so

![image](https://user-images.githubusercontent.com/8104698/115967283-11c4f380-a532-11eb-8b7a-e7ff92b717ba.png)

The reason I'm trying to turn it off, in the first place, is that it came turned on once #258 has been merged although I never explicitly enabled it. In the docs, it notes that by default it's turned off so that's strange.

But for some reason, it's still being highlighted. Am I doing something wrong? 

Could be due to my own config but I don't see how anything else could clash with it.

**Comment by sindrets** [comment]
You're not doing anything wrong. There was a bug in the implementation of that feature:

https://github.com/kyazdani42/nvim-tree.lua/blob/f39869514645b98ec30bc8826763c288b6cbdbef/lua/nvim-tree/renderer.lua#L301

That line should be `if vim.g.nvim_tree_highlight_opened_files == 1 then`.

Should be disabled if you set it to `nil`.  But it's strange that you say it was enabled by default, that should not be the case. It should only be enabled if you set it to a value that would be truthy in lua. That is, either `true` or anything that isn't `nil`.

**Comment by vuki656** [comment]
Oh, that makes sense.

If I set it to `nil` like so `vim.g.nvim_tree_highlight_opened_files = nil` I get an error `Key not found: nvim_tree_highlight_opened_files`

Is this issue being tracked anywhere else?

**Comment by sindrets** [comment]
Oh, my bad, apparently you can't set vim variables to `nil` unless they are already set it seems. But I just tested with:
```lua
vim.g.nvim_tree_highlight_opened_files = false
```

and that definitely works. 
And no, I don't think this is being tracked anywhere else.

**Comment by vuki656** [comment]
Yup that fixes it.

But it seems that opened folders are still highlighted unless you override it with `NvimTreeOpenedFolderName`.

Maybe there should be an option to enable/disable that as well, what do you think?

Also, is the fix for this just changing the if statement, if so I can open a PR.

**Comment by sindrets** [comment]
`NvimTreeOpenedFolderName` should be linked to `Directory` by default, so that shouldn't make a difference unless you have a colorscheme that changes this.

Yes, I think ensuring that all checks of the setting `vim.g.nvim_tree_highlight_opened_files` is strictly compared to `1` should fix this. Great if you put up a PR:)

**Comment by vuki656** [comment]
Alright, I'll take a look at that tomorrow.

Ill leave this open until PR.

**Comment by vuki656** [comment]
Hm, strange. 

I've changed it, to `vim.g.nvim_tree_highlight_opened_files == 1` and now when I change it back how it originally was, I cant reproduce.

By changed I mean I went to source code and changed it, restarted nvim but nothing changes.

**Comment by sindrets** [comment]
What exactly is it you can't reproduce?

**Comment by vuki656** [comment]
Opened files and folders being highlighted without the option being set, and with being set to 0.

**Comment by sindrets** [comment]
"without it being set" should never have happened in the first place, so somehow the option must have been set for you, somewhere. The only two values that are falsy in lua are `nil` and `false`, so setting it to anything other than that, including `0` will enable this option in current master. And that is the behavior I am seeing on my end. Do you see something else?

**Comment by vuki656** [comment]
I have no idea how it got set, I just know that I was turned on automatically without me ever touching it. Some weird stuff happening.

But as It seems to be fixed now I'll close this.

**Comment by sindrets** [comment]
Weird indeed. But this is still a bug though. The comparison should be strict. As it stands now, setting `vim.g.nvim_tree_highlight_opened_files = 0` will enable this option. Which is wrong. But alright, I can open the PR later.
