### ISSUE TITLE
Cannot Close nvim-tree E5108: Error executing lua ...e/pack/packer/start/nvim-tree.lua/lua/nvim-tree/view.lua:235: attempt to call field 'nvim_win_ hide' (a nil value)

### ISSUE THREAD

**Issue by arshadpakkali** [kyazdani42/nvim-tree.lua#348]
Error : E5108: Error executing lua ...e/pack/packer/start/nvim-tree.lua/lua/nvim-tree/view.lua:235: attempt to call field 'nvim_win_
hide' (a nil value)

installed nvim-tree through the packer.nvim plugin manager 
 here is the the packer config 
![2021-04-25-152107_1366x768_scrot](https://user-images.githubusercontent.com/43312830/115989659-ff53c400-a5dc-11eb-86e1-4d68327ffe7f.png)

![Error Screen Shot](https://user-images.githubusercontent.com/43312830/115988971-89019280-a5d9-11eb-8925-b9b7a0d4c2e4.png)

**Comment by elianiva** [comment]
`nvim_win_hide` was recently added (a month ago), try updating your neovim

**Comment by arshadpakkali** [comment]
@elianiva  thank you very much it works now, didn't notice that I was running behind
