### ISSUE TITLE
Invalid buffer id

### ISSUE THREAD

**Issue by Shatur95** [kyazdani42/nvim-tree.lua#350]
When I execute `:set background = light #or dark` before opening NvimTree (e.g. no valid NvimTree buffers exists), I get the following error:

```
E5108: Error executing lua ...ack/plugins/opt/nvim-tree.lua/lua/nvim-tree/renderer.lua:344: Invalid buffer id: 2
```

**Comment by sindrets** [comment]
Yep, it's because of this:

https://github.com/kyazdani42/nvim-tree.lua/blob/f39869514645b98ec30bc8826763c288b6cbdbef/lua/nvim-tree.lua#L191

Which is called on the `ColorScheme` event. We just need to make a check that the buffer is valid before calling this. I'll put up a PR to fix this later.
