### ISSUE TITLE
Lost unsaved files on folder deletion

### ISSUE THREAD

**Issue by mvllow** [kyazdani42/nvim-tree.lua#353]
Best to explain with a reproduction:
```
project_root/
├─ folder_a/
│  ├─ file_a
├─ file_b

```

Open both `file_a` and `file_b` and delete `folder_a`. This causes neovim to completely close, resulting in all unsaved changes to be lost.

Granted, this _is_ with `let g:nvim_tree_auto_close = 1`, but this still doesn't seem ideal. Disabling auto close results in a strange layout after deleting `folder_a`.

Edit: I think this may be similar to #149

**Comment by kyazdani42** [comment]
the auto close closes when the tree is the last opened _window_, which is the purpose of this feature that i developed well before understanding really how buffer and windows were working :) disabling auto close results in a normal behavior imo, i've been working like this for quite a while and it did not seem strange to me.
Would you have something to propose here or can i close this issue ? I'm not too sure in how you expect the tree to handle that.

**Comment by mvllow** [comment]
I guess what threw me off was the fact that if you delete an unopened file, everything works as expected. If you delete an opened file (even if you have 9 other files open) neovim closes completely, including unsaved buffers. I am also not familiar with window vs buffer etc. so if this doesn't sound like a bug feel free to close

Ideally you would be able to delete an open file and everything remain the same, instead of what looks like neovim crashing

**Comment by kyazdani42** [comment]
I'll see what i can do next week, i don't use this feature anymore so maybe i should remove it and only document it so users can extend it as they wish :)

**Comment by mvllow** [comment]
I believe 7d33b0f74a2399629e1d09a2c3fa1f32145ca1e3 closes this 😌

**Comment by kyazdani42** [comment]
@mvllow i think this PR is invalid actually it tries to close the window with the bufnr :confused: That's why it might be fixed :smile:
