### ISSUE TITLE
Netrw doesn't work even when hijack option is disabled

### ISSUE THREAD

**Issue by thorlucas** [kyazdani42/nvim-tree.lua#354]
I seem to be unable to use this with ssh. Say I have a host in my ssh config called "hive". How would I open the file explorer on that? Doing :e scp://hive/ doesn't work.

**Comment by thorlucas** [comment]
My bad, I missed issue #145. However, it seems that even setting:

```lua
vim.g.nvim_tree_disable_netrw = 0
vim.g.nvim_tree_hijack_netrw = 0
```

netrw does not work if this plugin is enabled. I have to disable nvim tree whenever I want to use netrw.

**Comment by thorlucas** [comment]
Ah, the settings must be set before `vim.cmd [[ packadd ... ]]` is called

**Comment by rmagillxyz** [comment]
> Ah, the settings must be set before `vim.cmd [[ packadd ... ]]` is called

Thanks so much. I spent way too much time trying to figure out why this wasn't working!
