### ISSUE TITLE
Can only CD into previous directories

### ISSUE THREAD

**Issue by jonathan-raines** [kyazdani42/nvim-tree.lua#355]
I'm using neovim nightly with [https://github.com/ChristianChiarulli/LunarVim](url) config file. It doesn't appear that he changes in any nvim-tree's default key bindings.

I can cd into previous directory by hitting "l" while over ".." but "Control + ] doesn't not work to cd into new directory. Am I misinterpreting the keybinding or is something else happening that's cancelling the keybind?

**Comment by sindrets** [comment]
You are not misinterpreting the keybinding, but it does work so it's probably got something to do with your config. With NvimTree focused, what's the output of `:verbose map <c-]>`?

**Comment by jonathan-raines** [comment]
![image](https://user-images.githubusercontent.com/5840124/116563504-b4ca9400-a8c9-11eb-9186-11fa7f8fb42d.png)

**Comment by sindrets** [comment]
Hm, that looks correct. You are invoking this keybinding while the cursor is on a folder node? Because if so, the problem lies elsewhere. You're gonna have to provide a minimal config that makes this reproducible, if I'm to be able to help you investigate this further.

**Comment by jonathan-raines** [comment]
https://github.com/jonathan-raines/LunarVim.git

This is my current configuration. If it needs to be more minimal, please let me know and I'll work on stripping it down further.

**Comment by sindrets** [comment]
That is far from minimal I'm afraid. When I say minimal config I mean a small `.vim` or `.lua` file that only sets up what is necessary to reproduce the problem. You can make nvim source this config instead of the default one by calling 

`nvim -u path/to/minimal.vim`. 

Example minimal config:

```vim
call plug#begin("~/.vim/plug")
Plug 'kyazdani42/nvim-web-devicons'
Plug 'kyazdani42/nvim-tree.lua'
call plug#end()
```

**Comment by jonathan-raines** [comment]
https://github.com/jonathan-raines/NeoRain

Here's a minimal config. Interestingly enough the cd functionality works in Neovide

**Comment by kyazdani42** [comment]
could this be related to how your terminal then ? check your terminal keybindings, sometimes they map to something else

**Comment by jonathan-raines** [comment]
That was it! I don't see any commands in Kitty defaulted to that key combo but changing the key bind did fix the issue! Thanks for taking a look.
