### ISSUE TITLE
Remove offset 2 char

### ISSUE THREAD

**Issue by yofriadi** [kyazdani42/nvim-tree.lua#359]
Hi, it is just question, in readme in screenshot 1 you can see that there is 2 char offset, but in screenshot 3 there is not.
how to remove this offset like in screenshot 3?

thankyou

**Comment by kyazdani42** [comment]
hi, there is no offset, the only thing is file icons being disabled i think. @stsewd it's your config right ?

**Comment by stsewd** [comment]
yeah, I started to embrace icons some weeks ago :smile:, but this is my previous config https://github.com/stsewd/dotfiles/blob/73db530a84c90c63ea0b6b947a2f9df94d0db3eb/config/nvim/init.vim#L309-L316

**Comment by yofriadi** [comment]
thanks guys, ya at first it is not obvious that there is space for icon in the left side, is it possible to move the icon to the right side? (also for git icon if possible)

I will close this anyway, thankyou

**Comment by kyazdani42** [comment]
moving the icons is not an option for this plugin sorry, it would probably complexify the rendering too much for its sake :)
