### ISSUE TITLE
Highlighting bug when folder icons are disabled and trailing slash is enabled

### ISSUE THREAD

**Issue by marioortizmanero** [kyazdani42/nvim-tree.lua#363]
For some reason the first character of every directory is white when both `vim.g.nvim_tree_add_trailing` and `vim.g.nvim_tree_show_icons.folders` are set to 1:

![image](https://user-images.githubusercontent.com/25647296/117043010-f6fe3600-ad0c-11eb-9da8-28baf2894ad3.png)

It doesn't seem to be an issue with icons:

![image](https://user-images.githubusercontent.com/25647296/117043045-02e9f800-ad0d-11eb-9a2f-0872242df3f1.png)

Nor without the trailing `/`:

![image](https://user-images.githubusercontent.com/25647296/117043221-3cbafe80-ad0d-11eb-9deb-e636f29f7c02.png)

My config:

```lua
vim.g.nvim_tree_add_trailing = 1  -- Append a trailing slash to folder names
vim.g.nvim_tree_show_icons = {    -- No icons
    git = 0,
    folders = 0,
    files = 0,
}
```

**Comment by kyazdani42** [comment]
fixed in 6c9927180f45
