### ISSUE TITLE
Revert padding to the left/right window border

### ISSUE THREAD

**Issue by marioortizmanero** [kyazdani42/nvim-tree.lua#364]
Can #150 be reverted? I agree with @kyazdani42 that "padding should be done by the terminal and not the programs inside it", and other file managers like NERDTree keep it with `signcolumn=no`. One could just add this to their alacritty config to have the same effect:

```yaml
window:
  padding:
    x: 10
```

The thing is that I can't even configure it to not have the padding again. If I manually use `:set signcolumn` after opening nvim-tree I do get rid of the extra column. But this doesn't work by default nor when I use something like `autocmd FileType NvimTree set signcolumn=no`.

**Comment by marioortizmanero** [comment]
I've managed to override the option with `require('nvim-tree.view').View.winopts.signcolumn = 'no'`, but I still think this should be a default.

**Comment by kyazdani42** [comment]
we use the sign column for lsp signs, so i prefer keeping it always open. Maybe some documentation would be nice in order for user to customize the tree view :)

**Comment by kyazdani42** [comment]
see https://github.com/kyazdani42/nvim-tree.lua/pull/805
