### ISSUE TITLE
Is there a way to hide the full path of the directory?

### ISSUE THREAD

**Issue by gmr458** [kyazdani42/nvim-tree.lua#368]

**Comment by siduck76** [comment]
I wanted this feature too! the fullpath doesnt look good :(
![image](https://user-images.githubusercontent.com/59060246/117397806-904e6780-af1a-11eb-887b-c6c477752205.png)

**Comment by kdav5758** [comment]
Same.

**Comment by siduck76** [comment]
@kdav5758 something like this? 

![image](https://user-images.githubusercontent.com/59060246/117692694-e7825f80-b1da-11eb-85c3-7ee4aaa692b5.png)

**Comment by gmr458** [comment]
@siduck76 It works. I have a question for you, how did you put that title "Explorer" in "nvimtree", it looks good.

**Comment by kyazdani42** [comment]
closing this since it seem to be resolved already

**Comment by vatosarmat** [comment]
How about an option to hide this title altogether? Many people have repo_name/branch in their status line, so the title in the explorer is redundant

**Comment by siduck76** [comment]
> How about an option to hide this title altogether? Many people have repo_name/branch in their status line, so the title in the explorer is redundant.
> Or let it show the path relatively to the project root. Vim builtin filename modifiers don't allow that

yeah I have the cwd displayed on my statusline too , I navigate via telescope or simply cd

**Comment by kyazdani42** [comment]
@vatosarmat the issue with that is that nvim-tree cwd is not the same as nvim's cwd so the 'title' is important to know in which folder you're located in. If you want more customization, could you open a new issue (or a PR ?) please :) ?
