### ISSUE TITLE
Error on save

### ISSUE THREAD

**Issue by michalenr** [kyazdani42/nvim-tree.lua#369]
I am having the following error when I save the file
```
Error detected while processing BufWritePost Autocommands for "*":
E5108: Error executing lua Vim:E117: Unknown function: sign_unplacelist
```

It is coming from this line and this commit
https://github.com/kyazdani42/nvim-tree.lua/commit/b5ef2fb7f81010a34994f4ab55e73df808b54d62#diff-b4d683774fedaa8bdc2f7107576331513b01888c09ab2fcfd44468ef976c1b08R51

**Comment by kyazdani42** [comment]
please upgrade your neovim version :)
