### ISSUE TITLE
Lost number column when open file from nvim-tree

### ISSUE THREAD

**Issue by vpeopleonatank** [kyazdani42/nvim-tree.lua#370]
# Reproduce:
Open nvim, open more than 3 buffers, toggle nvim-tree, back to one buffer, `:bd` to kill buffer, reopen opened buffer by using `:b `, sign column in file buffer disappear like below

![image](https://user-images.githubusercontent.com/30976876/117536978-5d929500-b028-11eb-8e7f-69ab23c37e49.png)

# Demo

https://user-images.githubusercontent.com/30976876/117537074-f0333400-b028-11eb-92ef-6879e0d4582b.mp4

**Comment by DanielPower** [comment]
I'm also experiencing this. It seems the first file I open will work fine, but the second file I open will both lose numbers, and will have a different color background (like nvim_tree's split does)

**Comment by DanielPower** [comment]
I wonder if it relates to https://github.com/kyazdani42/nvim-tree.lua/issues/341

**Comment by kyazdani42** [comment]
hi, i'm aware of this issue and it's a dup of #290, i yet have to find a way to properly manage that which i have not (which is why i tagged the issue with `help wanted` ^^)

**Comment by kyazdani42** [comment]
should be fixed in 4388338a6a1

**Comment by DanielPower** [comment]
The fix appears to work for me :)
Thanks!

**Comment by gegoune** [comment]
Ah, finally no messed up windows when accidentally opening stuff from nvim-tree. Awesome! :) ❤️

**Comment by williamboman** [comment]
Thanks ❤️!!

**Comment by gaetan-puleo** [comment]
GG
