### ISSUE TITLE
edit_close ?

### ISSUE THREAD

**Issue by cj** [kyazdani42/nvim-tree.lua#371]
Hey, I hope you're having a great weekend!

How would I go about adding `edit_close` command i.e.

```
      ["<CR>"]           = tree_cb("edit_close"),
      ["o"]              = tree_cb("edit"),
      ["l"]              = tree_cb("edit"),
```

I essentially want to edit the file but close nvim-tree on enter.

Cheers!

**Comment by kyazdani42** [comment]
maybe do a custom edit function by extending the on_keypress:
```lua
function your_custom_edit()
  require 'nvim-tree'.on_keypress('edit')
  require'nvim-tree'.close()
end
```

**Comment by kyazdani42** [comment]
you can bind to global with `function _G.some_func`, otherwise, you'll have to load your function from a module.

**Comment by yutkat** [comment]
`vim.g.nvim_tree_quit_on_open = 1`
