### ISSUE TITLE
Auto open tree when opening a file on startup

### ISSUE THREAD

**Issue by qazip** [kyazdani42/nvim-tree.lua#372]
I am trying to have nvim-tree shown as soon as vim opens. I tried the following:

`autocmd VimEnter * NvimTreeOpen`

Even though Nvim-Tree is shown, it is empty. I think it is opening in the wrong directory. If I click ENTER it does open some dir (the ".." dir").

**Comment by gaetan-puleo** [comment]
you need to set this option

```
let g:nvim_tree_auto_open = 1 "0 by default, opens the tree when typing `vim $DIR` or `vim`
```

**Comment by qazip** [comment]
Ah, I already have that actually. The issue is that I never open nvim with "nvim". I open it with "nvim file". And doing "nvim file" doesn't seem to work...? Is there any way to make it work with "nvim file"?

**Comment by kyazdani42** [comment]
opening at startup won't work when doing `nvim file`, i yet have to implement something to specify a list of option for opening on enter.

**Comment by cseelus** [comment]
@kyazdani42 An option to start it as the sole buffer would be nice.

Like when executing `nvim .` (with `let g:nvim_tree_auto_open = 1` set), switching to the Nvimtree buffer and typing `:only`.

**Comment by kyazdani42** [comment]
@cseelus i think this was request in another issue, but i guess it would not be too hard to implement, i'll work out something soon to make the auto open configurable
