### ISSUE TITLE
Trying to move up a directory on the root directory causes an error

### ISSUE THREAD

**Issue by akinsho** [kyazdani42/nvim-tree.lua#374]
When pressing `-` to `cd` upwards with the cursor on the root directory of the tree, this throws an error
`E5108: Error executing lua ...te/pack/packer/start/nvim-tree.lua/lua/nvim-tree/lib.lua:187: attempt to index upvalue 'fname' (a nil value)`. Looking at that line I guess it should also check that `fname` is not nil. I'm not really sure why fname is nil in this case tbh 🤷🏾 I was going to raise a PR to do a simple `fname and <rest-of-logic>` check but wanted to make sure this wouldn't just be covering up some other bug.

Also not sure if it is relevant or not but I've changed the `root_folder_modifier` to `:t` not sure if that is relevant or not though

**Comment by kyazdani42** [comment]
hotfixed this in 4706b749383b, it was just a mistake because node was { name = ".." } instead of nil so i had to add that check
