### ISSUE TITLE
Move cursor on file creation

### ISSUE THREAD

**Issue by kylechui** [kyazdani42/nvim-tree.lua#376]
I think that it would be convenient for the cursor to hover over newly created files in the tree. For example if you hit `a` and then typed `test.lua<CR>`, the cursor should automatically move to hover over `test.lua`. Adding this as either another option or default behaviour would be appreciated. Thanks for your work on the plugin!

**Comment by kyazdani42** [comment]
i guess it could be done, this is a small enhancement, if someone is willing to give it a go :)

**Comment by AlaaSaadAbdo** [comment]
I think this would also be convenient for creating directories, after creating a directory if it's focused on can start creating files there.

**Comment by kyazdani42** [comment]
fixed in d008e9d4a
