### ISSUE TITLE
C-t doesn't seem to open on a new tab?

### ISSUE THREAD

**Issue by satu** [kyazdani42/nvim-tree.lua#381]
I just installed the extension, and also managed to reproduced this bug with a minimal configuration with only nvim-tree.lua loaded. I'm using default setting for all the variables and keybindings.

When pressing C-t on a file, the file is opened in the same tab where the nvim-tree is open (effectively same behaviour as <CR>. This is different than what happens when pressing C-t in FZF or t in NERDTree. I verified that the other tools correctly open a new tab, and also that :tabnew works as intended.

Am I doing something wrong or is this a recent bug?
NVIM v0.5.0-dev+1326-g93aea8cee

**Comment by ysdexlic** [comment]
Also having the same issue

**Comment by kyazdani42** [comment]
indeed, i guess it's with the recent modification of the `open_file` function. @sindrets i think you forgot tabpage users :) I would send a patch but i do not have much time recently, i'll fix that when i have some more free time !

**Comment by sindrets** [comment]
My bad! @kyazdani42 I can fix this after you merge the window picker.

**Comment by ysdexlic** [comment]
Seems to be fixed, but the experience is a bit odd, it opens the file in a new tab but in the original tab the tree stays open but without focus. I think a better experience would be to respect `g:nvim_tree_auto_close` and to keep focus if it isn't set.

**Comment by sindrets** [comment]
@ysdexlic I just made it work exactly like it did before. But I agree with you, and the current documentation actually says that's how it's supposed to work. I'll open a PR later.
