### ISSUE TITLE
Question: Create file & focus file created

### ISSUE THREAD

**Issue by AlaaSaadAbdo** [kyazdani42/nvim-tree.lua#382]
Hi, 

Thanks for the awesome plugin, I have been using it and it's super fast in comparison to alternatives I have used before.

When creating a file or a dir using `a` they are not focused. Most of the time when I create a file I want it opened automaticall or at least focused so I can oven it in a split.

I was wondering if there's away to create a file using `a` and automatically focus it upon creation?

Cheers!

**Comment by kyazdani42** [comment]
not to be rude, but:
`:h nvim_tree_events`
```lua
events.on_file_created(function(data)
  for _, b in vim.api.nvim_list_bufs() do
    -- some matching mecanism with data.fname and window focusing
  end
end)
```

**Comment by AlaaSaadAbdo** [comment]
Thanks for the hint, will try my best :) appreciate you taking the time. Feel free to close the issue and I might comment the solutions back later here if I find one.

**Comment by kyazdani42** [comment]
```lua
events.on_file_created(function(data)
  vim.cmd("vsplit "..data.fname)
end)
```
maybe something like that ?

**Comment by kyazdani42** [comment]
or 
```lua
events.on_file_created(function(data)
  if #vim.api.nvim_list_wins() == 1 then
  vim.cmd("vsplit "..data.fname)
   else
   vim.cmd("wincmd l | edit "..data.fname")
end)
```

**Comment by AlaaSaadAbdo** [comment]
I will try both and get back to you. I will also look into focusing/finding the file in the tree without opening it. Thanks again for the help

**Comment by cloggier** [comment]
@kyazdani42 so the second snippet works (didn't try the first one yet) but noticed straight away that when creating new file, it gets open but cursor jumps to previously opened file (in nvim-tree buffer) rather than focusing on newly created one. How to do that?

Also, great thanks for all your hard work!!!

**Comment by kyazdani42** [comment]
i'll see when i have some time, maybe next week

**Comment by AlaaSaadAbdo** [comment]
Hi, 

I tried both snippets and I can confirm that the behaviour of not focusing the file in the file tree is there. It can be mitigated by calling the `:NvimTreeFindFile` in the snippet but I'm not sure whether or not that's an overkill. I also would like to note that the functionality that I mentioned was to focus the file in the tree without necessarily a mechanism to open it since that can apply for creating directories and files. I took a look into the `find_file()` function and `:NvimTreeFindFile` and it didn't look like one can pass a parameter to `:NvimTreeFindFile` this might not be how you wanted that function to behave. I'll keep on digging maybe I can find a suitable solution but so far I couldn't find an event that does that in the `:h nvim_tree_events`

Thanks again for the support. I'll communicate anything that I find that could be interesting or helpful.

**Comment by kyazdani42** [comment]
i guess calling `require'nvim-tree'.find_file(false)` would not be overkill and allow for not opening the tree

**Comment by AlaaSaadAbdo** [comment]
Calling `require'nvim-tree'.find_file(false)` after the file has been created and opened in either split or window, that solved the problem in case we want to open the file upon creating it. so at least we stay inside the file, yet the focus in the tree is still on the wrong file.

Is there a way just to create a file and focus that file in the tree without opening it?
I couldn't figure anything on my own while looking at the plugin code.

**Comment by AlaaSaadAbdo** [comment]
I guess the behaviour I asked about can be discussed in the enhancement issue #376
