### ISSUE TITLE
Tree empty if entering quickly after starting neovim

### ISSUE THREAD

**Issue by languitar** [kyazdani42/nvim-tree.lua#383]
This is split from the discussions in #280.

I do not use packer lazy loading for nvim-tree. Yet, when starting neovim and quickly entering the tree (with a leader mapping), the tree is often initially empty and I have to re-toggle or refresh it to get contents.

![image](https://user-images.githubusercontent.com/1336287/118609212-d0370980-b7ba-11eb-9353-dd179ecc5099.png)

This was the result of starting neovim and directly afterwards using my leader mapping leader-n. Setting debug="throw" did not surface anything.

My config is available here: https://github.com/languitar/config-nvim

Neovim is compiled daily and the plugins are updated along with that.

**Comment by kyazdani42** [comment]
i'm not too sure, i would need a minimal config at this point to reproduce. Which OS do you use ?

**Comment by languitar** [comment]
This is on Archlinux.

**Comment by languitar** [comment]
I can also reproduce this with the linked config on MacOS

**Comment by kyazdani42** [comment]
not sure how to reproduce this, i'm on arch linux with always up to date plugins/neovim too and i've never seen that issue without lazy loading.
Could you provide a minimal nvim with which you are sure this issue can be reproduced please ?

**Comment by sindrets** [comment]
This is quite easily reproducible by calling nvim with `nvim -c 'NvimTreeOpen'`. And I think it's pretty easy to fix as well. At the end of the init function we just need to check whether the tree window is already open, and refresh if it is.
