### ISSUE TITLE
Color customization

### ISSUE THREAD

**Issue by eprislac** [kyazdani42/nvim-tree.lua#384]
Would love a way to customize icon colors. Apologies if this is available as a config already, but I can't find any documentation for it.

**Comment by kyazdani42** [comment]
look toward `nvim-web-devicons`, you should call the `setup` function of this lib before other plugins initializes it, see it's readme, its well detailed :)

**Comment by n1ghtmare** [comment]
@kyazdani42 I've looked into the help for `nvim_tree_highlight` as well as the documentation for `nvim-web-devicons`, but couldn't find a solution - Is it possible to disable (or change) the color for all icons somehow?

**Comment by kyazdani42** [comment]
hi, sorry for the late answer.
Did you find a way to do this ?
You should use the `override` for nvim-web-devicon, or use vim's `:highlight` command.
