### ISSUE TITLE
Show new files on :cd

### ISSUE THREAD

**Issue by ahmedkhalf** [kyazdani42/nvim-tree.lua#387]
Hello, I am making a plugin that automatically changes pwd to the root directory using `vim.api.nvim_set_current_dir(project_root)`.

See [lsp-rooter.nvim](https://github.com/ahmedkhalf/lsp-rooter.nvim).

Here's the problem: whenever I change the directory I have to toggle the Nvim tree three times for me to see the see the project files:
1. open and realize it still point to old dir
2. close
3. open and finally see project files

Is there anyway to do this automatically whenever I change directory?

**Comment by kyazdani42** [comment]
could you use something like `require'nvim-tree.lib'.change_dir(foldername)` ?

**Comment by ahmedkhalf** [comment]
Thanks
