### ISSUE TITLE
Feature request: add an option to opt-out of certain icons

### ISSUE THREAD

**Issue by ysdexlic** [kyazdani42/nvim-tree.lua#388]
I think it'd be nice to choose which icons are used, for example I like using most of the git icons but I don't see the need in one for `ignored` as it's already grey'd out and in italics. I tried to remove it by setting is as an empty string but it still has the space before the folder/file name, see screenshot of node_modules:

![Screenshot 2021-05-20 at 10 12 20](https://user-images.githubusercontent.com/16815919/118952724-15427380-b954-11eb-9971-91aea7c1b5e3.png)

Perhaps if the icon is set to an empty string you could not render the extra space?

**Comment by kyazdani42** [comment]
i guess this is not ideal indeed, did you try to set `nil` for it ? I guess it'll crash but we never know :)

**Comment by kyazdani42** [comment]
hum this looks like a rendering bug to me, i'll fix that

**Comment by alex-courtis** [comment]
This rendering issue has been resolved.

This results in no icon being displayed:
```lua
vim.g.nvim_tree_icons = { git = { ignored = '' } }
```

The "different colour and italics" for ignored doesn't exist any more, so it's of questionable value.

I think we can close this @kyazdani42

**Comment by kyazdani42** [comment]
you are right, thanks for noticing :)
