### ISSUE TITLE
Filetype set after buffer window is created (maybe)

### ISSUE THREAD

**Issue by Akin909** [kyazdani42/nvim-tree.lua#39]
I'm seeing an issue when trying to use the `&filetype` hook for `LuaTree` to setup autocommands or a custom statusline for the buffer. I haven't looked through the code so this is a guess, but I wonder when the `ft` is being set. Currently if I set my statusline to change when it detects the `filetype=LuaTree` it doesn't work the first time. I also can't highlight the window using `winhighlight` because it doesn't seem to pick up the filetype.

I've tried using `coc-explorer` which also sets a filetype and things work fine.
If this isn't enough information please let me know I can try and do a minimal repro but I think just setting up an autocommand for `LuaTree` buffers should be enough to see that the autocommand won't work the first time the buffer is opened

**Comment by kyazdani42** [comment]
this is strange indeed, I'll try to fix this today.

**Comment by kyazdani42** [comment]
well i cannot find why it behaves that way. the filetype is set on buffer creation before being set to the window.
Could you provide me with the commands you are trying to run so i can test that issue deeper please ?

**Comment by Akin909** [comment]
@kyazdani42 I've just tried reproducing it locally using
```
call plug#begin(stdpath('data') . '/plugged')
Plug 'kyazdani42/nvim-web-devicons' " for file icons
Plug 'kyazdani42/nvim-tree.lua'
call plug#end()

augroup Setup
  autocmd!
  autocmd FileType LuaTree setlocal statusline=This\ is\ Lua\ Tree
  autocmd FileType LuaTree set winhighlight=Normal:ErrorMsg
augroup END
```

If you run either of those commands inside the lua tree buffer on their own i.e.
`:set winhighlight=Normal:ErrorMsg` that works but if you try and trigger this via an autocommand it doesn't work. Is that buffer ignoring autocommands somehow?

**Comment by kyazdani42** [comment]
for winhighlight, it happens because is set a winhighlight for Normal during window creation so it would override yours. You have documentation for winhighlights i believe (or at least i wrote which one i declare)
You can still add winhighlights that i don't declare with winhighliht`+`=
you might want to change the `LuaTreeNormal` hl group for this one.
Im going to investigate for your statusline thing but i tried other things and it just works.

**Comment by kyazdani42** [comment]
i moved some buffer local after window initialization and i set the filetype after buffer is set to the window, so everything should work as expected now.

**Comment by Akin909** [comment]
Awesome thanks for the super quick fix 🚀
