### ISSUE TITLE
Smart opening of nodes

### ISSUE THREAD

**Issue by Chaitanyabsprip** [kyazdani42/nvim-tree.lua#391]
if there is only one folder inside a folder, then expanding into it should automatically expand into the child folder.

**Comment by Chaitanyabsprip** [comment]
I dont understand what you mean by that. 
```
|
| - src/
     | - features/
     |         | - feature1/
     |                  | - file.ext
     | - UI/
          |
          |
```
expanding `features` folder should expand `feature1` folder as well, because it is the only folder and there are no other files or folder inside `features`.

**Comment by cloggier** [comment]
There is an option `nvim_tree_group_empty` to enable very behaviour you are after, have a look at readme/docs.

**Comment by Chaitanyabsprip** [comment]
okay, thank you!
