### ISSUE TITLE
Statusline issue with multiple windows

### ISSUE THREAD

**Issue by kristijanhusak** [kyazdani42/nvim-tree.lua#392]
After the recent update, my statusline messes up once I select a window.

Steps to reproduce:
* open 2 split windows
* Try to open some file, select for example `B`
* Check first window statusline, it prints an error.

Here's the screenshot:
![screenshot](https://i.imgur.com/atm9134.png)

And here's my statusline configuration: https://github.com/kristijanhusak/neovim-config/blob/bleeding-edge/nvim/lua/partials/statusline.lua

**Comment by sindrets** [comment]
My bad, I didn't realize `nvim_win_get_option` would return a string when it fails to get the value. I'll put up a PR to fix this.
