### ISSUE TITLE
reloading of folder broken with `ef57007`

### ISSUE THREAD

**Issue by felipesere** [kyazdani42/nvim-tree.lua#393]
After doing a regular update this morning, refreshing folders (automatic or manual) broke for me. It simply wont reload and I have to re-open vim to see the changes.  I locally reverted
 https://github.com/kyazdani42/nvim-tree.lua/commit/ef570074e0f73e59e24d41fba5db3b2db0fdc58c
and now everything is back to normal.

Not sure that change is specific to a version on neovim?

I'm on 
```
NVIM v0.5.0-dev+48e8057
Build type: Release
LuaJIT 2.1.0-beta3
```

**Comment by Samyak2** [comment]
I can confirm the same behaviour on `d6ab59fd5acb7c71b1a10ace5a522a720460ad6e`. `R` does not do anything.

Neovim version:
```
NVIM v0.5.0-dev+1282-gfbe18d9ca
Build type: Release
LuaJIT 2.1.0-beta3
```

**Comment by uyha** [comment]
Updating to the newer neovim solves the issue. My current neovim version is:
```
NVIM v0.5.0-dev+1345-g6dd04ed5f
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

**Comment by Samyak2** [comment]
That works! Thank you

**Comment by felipesere** [comment]
Yeah, updating to latest `mater` from neovim helped. Thanks!
