### ISSUE TITLE
[bug] error when closing (toggle) the tree

### ISSUE THREAD

**Issue by marekkon** [kyazdani42/nvim-tree.lua#40]
When I close (toggle) tree for the first time this error appears:
```
E5108: Error executing lua .../.local/share/nvim/plugged/nvim-tree.lua/lua/lib/lib.lua:252: Vim(lua):E5108: Error executing lua .../.local/share/nvim/plugged/nvim-tree.lua/lua/tree.lua:100: attempt to call field 'defer_fn' (a nil value)
```

When I try to open it again (toggle), this appears:
```
E5108: Error executing lua .../.local/share/nvim/plugged/nvim-tree.lua/lua/lib/lib.lua:231: Vim:E95: Buffer with this name already exists
```

**Comment by kyazdani42** [comment]
You must upgrade your neovim version to master, if you use neovim 0.4.x, please see the README for informations :)

**Comment by marekkon** [comment]
I use master (v0.5.0-503-g9816173fb)

**Comment by kyazdani42** [comment]
master is v0.5.0-553-gd8c5d122f.
Are you using arch linux ?

**Comment by marekkon** [comment]
Yes

**Comment by kyazdani42** [comment]
use `neovim-git` instead of `neovim-nightly` from the AUR which is out of date :)

**Comment by marekkon** [comment]
Ok, works. Thanks.
