### ISSUE TITLE
don't ask which window to open a new file to if we only have edit window (A) and quickfix (B)

### ISSUE THREAD

**Issue by svalaskevicius** [kyazdani42/nvim-tree.lua#400]
I have 3 windows open: editor, file tree and quickfix (with some LSP results), when I open a new file in the tree - it asks where do I want the file to end up. 

it would be good to filter out the quickfix window from the suggestions and just open the file.

**Comment by sindrets** [comment]
Yes, we should probably provide a way to exclude buffers that match certain file types or buf types.
