### ISSUE TITLE
Newest commit "Option for excluding buffers from the window picker" doesn't allow me to open files on Windows 10

### ISSUE THREAD

**Issue by Binx-Codes** [kyazdani42/nvim-tree.lua#402]
So i'm on Windows 10, and I tried opening a file using NvimTree. I was unable to as this error raised, and this had started happening after the latest commit. 

![image](https://user-images.githubusercontent.com/68950943/119838989-e197b880-bf14-11eb-96fb-bbf136f7d8c0.png)

**Comment by kyazdani42** [comment]
did you manage to fix this ? I did not see the issue come up myself

**Comment by Binx-Codes** [comment]
I wasn't able to fix the issue, but I did end up disabling the feature

**Comment by kyazdani42** [comment]
hum i don't personally own a windows machine so i cannot test it out sorry :/ looking at the code though, looks like something else is wrong because it doesn't rely on any linux specific thing, it fails to load a module's function.
