### ISSUE TITLE
Feature Request: Copy File

### ISSUE THREAD

**Issue by bugeats** [kyazdani42/nvim-tree.lua#406]
We already have rename (move) a file. I'm surprised you can also copy a file.

Only one slight problem:

> type c to add/remove file/directory to copy clipboard
> type y will copy name to system clipboard

Bummer that `c` is already used.

**Comment by kyazdani42** [comment]
I'm not sure i understand your request here, do you want to copy the filename or copy the file content in your system's clipboard ?

**Comment by sindrets** [comment]
This is a really strange issue. We already have copy file functionality, and you're even pointing it out:

> type c to add/remove file/directory to copy clipboard

What are you missing from the copy functionality currently provided?

**Comment by hoopes** [comment]
For me, nerdtree offers a "copy this file" operation - literally like `$ cp file1 file2` from the terminal. Useful for backing up a file quickly, copying the mode bits of one file to another, etc. Nothing to do with the clipboard, afaik, unless i'm drastically misunderstanding what `c` actually does. I'd like to humbly `+1` this feature request.

Side note, is there an obvious use case for "copy the filename"?

**Comment by hoopes** [comment]
GOT IT - definite misunderstanding on my part. If that's not what @bugeats was referring to, then my apologies for hijacking the issue. I think the term "clipboard" confused me - I was wondering "why would i not just use `yy` to copy the filename?".

Thanks for the info, and again, my apologies for issue-jacking.

**Comment by bugeats** [comment]
Sorry, my original description was so confusing. I'm a little embarrassed to read it just now. I'll try again and avoid being prescriptive and terse.

I use NERDTree. One of the things I do in NERDTree all the time is make copies of files in the working directory. For example, if I had a file `src/a.test.lua` with a bunch of boilerplate, It's easy for me to just copy it as `src/b.test.lua` and then modify the boilerplate in `src/b.test.lua`. In NERDTree, I accomplish this by moving the cursor to `src/a.test.lua` and pressing `m` ("show menu") and then pressing `c` ("copy the current node"). I'm then given the opportunity to edit the source file path to make the new target path. After I press enter the file is copied.

I would love to be able to do something similar in nvim-tree. If this is already possible, then it wasn't clear to me.

**Comment by sindrets** [comment]
@bugeats it is already possible. The workflow is slightly different. You move the cursor to a file node, press `c` to copy. Then move the cursor to the folder you wish to paste into (make sure it is not collapsed) and press `p`. Like I already said, if you paste into the same folder as the file was copied from you will be prompted to rename the file.

**Comment by bugeats** [comment]
That way sounds much nicer, thanks. I think when I originally read the docs, I got the wrong impression.

The docs currently say:

- type `c` to add/remove file/directory to copy clipboard
- type `p` to paste from clipboard. Cut clipboard has precedence over copy (will prompt for confirmation)

Maybe something like this would be better:

- type `c` to copy the file/directory object under the cursor.
- type `p` to paste an object from the clipboard. Pasted file/directory objects will create new files.

Heh, I dunno. I'm not feeling confident about my writing ability today.

**Comment by kyazdani42** [comment]
well i guess you are not wrong about that, i should clean the docs a little bit. Can i consider this issue closed then ?

**Comment by danielo515** [comment]
> @bugeats it is already possible. The workflow is slightly different. You move the cursor to a file node, press `c` to copy. Then move the cursor to the folder you wish to paste into (make sure it is not collapsed) and press `p`. Like I already said, if you paste into the same folder as the file was copied from you will be prompted to rename the file.

But that is not what nvim-tree does, in my case it just ignores the paste command and does nothing

**Comment by luanguimaraesla** [comment]
In my case, nvim-tree is ignoring `p` too. I can see the notification when I copy (`c`), but when I paste, nothing happens.

**Comment by alex-courtis** [comment]
> In my case, nvim-tree is ignoring `p` too. I can see the notification when I copy (`c`), but when I paste, nothing happens.

Please raise a [bug](https://github.com/kyazdani42/nvim-tree.lua/issues/new?assignees=&labels=bug&template=bug_report.yml) with a minimal config so that we may reproduce.

**Comment by mario-amazing** [comment]
@luanguimaraesla I have the same error, when I press the `p` button -> I see this float window -> rename the file - nothing happend.
<img width="316" alt="image" src="https://user-images.githubusercontent.com/9537753/191010633-d4890f45-09d0-4b3a-975d-fe6a76a0f40f.png">

But when I disable all of the UI plugins, I found that before rename I should press the `r` button for rename and only after that I should write a new file name.
<img width="649" alt="image" src="https://user-images.githubusercontent.com/9537753/191010166-537e34be-908d-4977-84d4-cff37fd02d21.png">

@alex-courtis could you fix required information in floating window ?(example on the first screenshot)

**Comment by alex-courtis** [comment]
> @alex-courtis could you fix required information in floating window ?(example on the first screenshot)

Happy to fix; there have been some problems in the past with floating inputs.

Please provide a [minimal config reproducer](https://github.com/kyazdani42/nvim-tree.lua/issues/new?assignees=&labels=bug&template=bug_report.yml) via a bug report that includes the other plugins I need to reproduce the issue.

**Comment by rockneverdies55** [comment]
I have the same problem. p command does nothing.

**Comment by alex-courtis** [comment]
> I have the same problem. p command does nothing.

Please raise a [bug report](https://github.com/nvim-tree/nvim-tree.lua/issues/new?assignees=&labels=bug&template=bug_report.yml) with a minimal configuration and steps to reproduce.

Please enable logging and attach the file so that we may better diagnose the issue.
See  `:help nvim-tree.log`
```lua
    log = {
      enable = true,
      truncate = true,
      types = {
        all = false,
        config = false,
        copy_paste = true,
        dev = false,
        diagnostics = false,
        git = false,
        profile = false,
        watcher = false,
      },
    },
```

**Comment by mangelozzi** [comment]
> Sorry, my original description was so confusing. I'm a little embarrassed to read it just now. I'll try again and avoid being prescriptive and terse.
> 
> I use NERDTree. One of the things I do in NERDTree all the time is make copies of files in the working directory. For example, if I had a file `src/a.test.lua` with a bunch of boilerplate, It's easy for me to just copy it as `src/b.test.lua` and then modify the boilerplate in `src/b.test.lua`. In NERDTree, I accomplish this by moving the cursor to `src/a.test.lua` and pressing `m` ("show menu") and then pressing `c` ("copy the current node"). I'm then given the opportunity to edit the source file path to make the new target path. After I press enter the file is copied.
> 
> I would love to be able to do something similar in nvim-tree. If this is already possible, then it wasn't clear to me.

I personally prefer the `NerdTree` style of copying, I find it less fiddly/pointy clicking with the keyboard.
I achieved the it with (has file completion):

```lua
local function copy_file_to(node)
    local file_src = node['absolute_path']
    -- The args of input are {prompt}, {default}, {completion}
    -- Read in the new file path using the existing file's path as the baseline.
    local file_out = vim.fn.input("COPY TO: ", file_src, "file")
    -- Create any parent dirs as required
    local dir = vim.fn.fnamemodify(file_out, ":h")
    vim.fn.system { 'mkdir', '-p', dir }
    -- Copy the file
    vim.fn.system { 'cp', file_src, file_out }
end

require('nvim-tree').setup { -- BEGIN_DEFAULT_OPTS
    view = {
        mappings = {
            list = {
                { key = "c", action = "copy_file_to", action_cb = copy_file_to },
            }
        }
    }
}

```
If its useful to others maybe we should add it to the wiki?

**Comment by alex-courtis** [comment]
> If its useful to others maybe we should add it to the wiki?

That's a great [Recipe](https://github.com/nvim-tree/nvim-tree.lua/wiki/Recipes)!

Please do add it.

**Comment by mangelozzi** [comment]
> Please do add it.

Thanks! ...done.

**Comment by neevek** [comment]
> If you're pasting it into the same directory, you will be prompted to rename it.
> 
> > Side note, is there an obvious use case for "copy the filename"?
> 
> Are you specifically referring to copying _only_ the filename? It's not very useful in my opinion. But the "copy relative / absolute path" functions are very useful for operating on files from the terminal etc.

**Comment by neevek** [comment]
@sindrets 
> If you're pasting it into the same directory, you will be prompted to rename it.

Renaming in this case is not the only option, it could be creating new file with the same file content, this is quite a normal behavior in many other editors. Also, there's already a `r` command to trigger renaming, I don't think `copy + paste ` triggering renaming makes much sense here.

**Comment by da-x** [comment]
If anyone wants an updated version, here it is -

```lua
local function my_nvim_tree_on_attach(bufnr)
  local function opts(desc)
    return { desc = 'nvim-tree: ' .. desc, buffer = bufnr, noremap = true, silent = true, nowait = true }
  end
  local api = require 'nvim-tree.api'

  api.config.mappings.default_on_attach(bufnr)

  local function nvim_tree_copy_file_to()
    local node = api.tree.get_node_under_cursor()

    local file_src = node['absolute_path']
    -- The args of input are {prompt}, {default}, {completion}
    -- Read in the new file path using the existing file's path as the baseline.
    local file_out = vim.fn.input('COPY TO: ', file_src, 'file')

    -- Create any parent dirs as required
    local dir = vim.fn.fnamemodify(file_out, ':h')
    vim.fn.system { 'mkdir', '-p', dir }
    -- Copy the file
    vim.fn.system { 'cp', file_src, file_out }
  end

  vim.keymap.set('n', 'c', nvim_tree_copy_file_to, opts 'Copy File')
end
```

Add `on_attach = my_nvim_tree_on_attach,` in setup.

**Comment by alex-courtis** [comment]
Thanks for the update @da-x 

I'd be most grateful if you updated the wiki version. Please remember to add your name next to the original author.
