### ISSUE TITLE
Reveal node in file explorer

### ISSUE THREAD

**Issue by cseelus** [kyazdani42/nvim-tree.lua#409]
First of all, thanks for this plugin. Its astounding how fast it is compared to NerdTree for huge folders (like `node_modules` usually is).

Maybe I missed it, but a shortcut to open the current node with the system file explorer (like Finder on macOS) would be a great addition. With NerdTree the shortcut was `r` (for reveal), which is already in use for rename with NvimTree, so maybe `f`(for file explorer) or `e` would be cool.

**Comment by cloggier** [comment]
It's not implemented in plugin itself but if you search through closed issues you will find some functions to do just that.

**Comment by cseelus** [comment]
For non folder nodes, this will just open the node with the default application set for the nodes file type (macOS).

**Comment by kyazdani42** [comment]
i'm not sure but isn't there netrw capabilities for that ?

**Comment by cseelus** [comment]
Yeah, netrw will also open the file under the cursor with the OS associated application by pressing `x`, but has no command like NerdTrees reveal, afaik.

**Comment by kyazdani42** [comment]
well i don't know which file explorer you use so i cannot make any assumption, thus this feature must be implemented on your side :) there are too many file explorers, i cannot handle windows + linux + macos like this. Adjust the provided function accordingly, i dont think it would be hard to do :)

**Comment by carlesba** [comment]
This is more a Lua issue but... how can that function be used? I can't find a way to map it into a keymap in lua

**Comment by cseelus** [comment]
@carlesba This is implemented now. You can open a file with the default system application by selecting it and pressing `s`.
