### ISSUE TITLE
Overriding icons requires complete map or causes errors

### ISSUE THREAD

**Issue by Akin909** [kyazdani42/nvim-tree.lua#41]
If a user doesn't specify items in the `lua_tree_icons` map vim fails to startup/crashes

<img width="1611" alt="Screenshot 2020-06-18 16 51 59" src="https://user-images.githubusercontent.com/22454918/85119497-c4913a80-b219-11ea-8984-d509f357684a.png">

### Steps to reproduce:
1. Add 
```vim
let g:lua_tree_icons = {
   \ 'folder': {
    \   'default': "",
    \   'open': ""
    \   }
```
2. Restart vim

The fix here is just to make sure to specify the whole thing, so not a huge issue this is just FYI since it's kind of a gnarly bug

**Comment by kyazdani42** [comment]
woops ! should have tested that before merging the refactoring ...

**Comment by kyazdani42** [comment]
fixed :) !
