### ISSUE TITLE
nvim_tree_special_files miss icons, setting doesn't work correctly

### ISSUE THREAD

**Issue by cseelus** [kyazdani42/nvim-tree.lua#410]
Don't know if its intentional, but `nvim_tree_special_files` are shown without a file icon:

<img width="254" alt="Screen Shot 2021-05-29 at 13 20 48" src="https://user-images.githubusercontent.com/3188392/120068380-b0d49200-c080-11eb-9c14-a3380a85ec9f.png">

Just copying the setting from the NvimTree README (`let g:nvim_tree_special_files = [ 'README.md', 'Makefile', 'MAKEFILE' ]`) into my NvimTree settings, and my projects `README.md` strangely has no special highlight anymore.

If I wanted to disable any special highlighting for files, using `let g:nvim_tree_special_files = [ ]` works as expected though.

**Comment by kyazdani42** [comment]
i'll look into it, this looks like a bug

**Comment by baahrens** [comment]
Had the same issue and looking at the source code it seems like it should be
```vim
let g:nvim_tree_special_files = { 'README.md': 1, 'Makefile': 1, 'MAKEFILE': 1 }
```
This works for me.
