### ISSUE TITLE
Use default file icon color for opened files 

### ISSUE THREAD

**Issue by siduck76** [kyazdani42/nvim-tree.lua#414]
Hi there! opened files are colored the same now , I want them to use their original file icon colors only 

![image](https://user-images.githubusercontent.com/59060246/120103442-3b92bb00-c16d-11eb-84eb-376ee226aa4e.png)

original file icon color : 
![image](https://user-images.githubusercontent.com/59060246/120103482-6715a580-c16d-11eb-867e-e5ab5f1469d6.png)

**Comment by siduck76** [comment]
> Hi there! opened files are colored the same now , I want them to use their original file icon colors only
>  
> ![image](https://user-images.githubusercontent.com/59060246/120103442-3b92bb00-c16d-11eb-84eb-376ee226aa4e.png)
> 
> original file icon color :
> ![image](https://user-images.githubusercontent.com/59060246/120103482-6715a580-c16d-11eb-867e-e5ab5f1469d6.png)

**Comment by kyazdani42** [comment]
hi ! What's the question exactly ? you could disable the opened_file feature if you wish

**Comment by siduck76** [comment]
@kyazdani42 I dont want to get the opened file's icon color to be changed :(

**Comment by kyazdani42** [comment]
please read `:help nvim_tree_highlight_opened_files` and update your configuration accordingly :)
