### ISSUE TITLE
Bug: NvimTree doesn't revert highlight active for statusline when closing it.

### ISSUE THREAD

**Issue by rafamadriz** [kyazdani42/nvim-tree.lua#416]
Nvim version: NVIM v0.5.0-dev+1359-g43956dea5
NvimTree: updated to latest commit. 

When toggling NvimTree the statusline doesn't go back to be active, and it stays with the highlight colors of inactive mode even though NvimTree is closed. Tested with feline and lualine, both have the same behavior. 

![nvim](https://user-images.githubusercontent.com/67771985/120116163-4bfb6380-c176-11eb-8977-13add203a53f.gif)

In this video see how the statusline is inactive when NvimTree is closed, the only way to fixed is by moving to another file/buffer.  

### Minimal init.lua to reproduce.

```lua
-- install packer
local fn = vim.fn

local install_path = "/tmp/nvim/site/pack/packer/start/packer.nvim"

vim.cmd [[set packpath=/tmp/nvim/site]]

local function load_plugins()
    local use = require("packer").use
    require("packer").startup(
        {
            function()
                use "wbthomason/packer.nvim"
                use "hoob3rt/lualine.nvim"
                use "kyazdani42/nvim-tree.lua"
            end,
            config = {package_root = "/tmp/nvim/site/pack"}
        }
    )
end

_G.load_config = function()
    require("lualine").setup()
end

if fn.isdirectory(install_path) == 0 then
    fn.system({"git", "clone", "https://github.com/wbthomason/packer.nvim", install_path})
    load_plugins()
    require("packer").sync()
    vim.cmd "autocmd User PackerComplete ++once lua load_config()"
else
    load_plugins()
    _G.load_config()
end
```

### Steps to reproduce:
1. Use minimal init.lua above.
2. Open a file.
3. Toggle NvimTree
4. Statusline will be inactive even after NvimTree is closed.
5. Move to another buffer/file and the statusline will get fixed.

### More context:
This has been happening for couple of days, I thought it was something wrong with my statusline, but no. 
1. It only happens when I toggle NvimTree. 
2. Doesn't happen with any other plugin with UI elements that I have (like undotree). 
3. Installed lualine just to test and it has the same behavior. 

Above a minimal init.lua to reproduce. And obviously this is a new thing, wasn't happening before.

**Comment by sindrets** [comment]
This was introduced by be184bd94e558b302461b359d02ed1b01f7154a1.

@kyazdani42 what problem is this commit supposed to solve? It seems to introduce various odd behaviors. Like the one described in the OP as well as making it impossible to use `wincmd p` if nvim-tree was the previous window.

**Comment by kyazdani42** [comment]
@sindrets it was supposed to solve another issue (setting the previous window from which the tree was opened) but i guess it did create new ones, i've seen that too. Maybe just doing noautocmd wincmd would do the trick ?
