### ISSUE TITLE
Settings not taking effect

### ISSUE THREAD

**Issue by jim-at-jibba** [kyazdani42/nvim-tree.lua#417]
Thanks for the awesome plugin.

I am not sure if I am missing something but cant seem to override the settings.

Adding:

`let g:nvim_tree_side = 'right'`

does not seem to have any effect.

Thanks

**Comment by jim-at-jibba** [comment]
Update: If I move the settings out of my `after/plugin/nvimtree.vim` file it works. Maybe I am not understanding how vim loads its files.

Thanks

**Comment by kyazdani42** [comment]
Hi ! 
it should work if you set the variable before the plugin initialization because the variable will then be used to set some internal variables, otherwise it will use the default config and setting the variable will have no effect afterwards

**Comment by cloggier** [comment]
@kyazdani42 Would be nice to have `setup` function type of initialising/configuring the plug-in. :)

**Comment by kyazdani42** [comment]
it's been on my personal roadmap for quite some time, but lately i've been to busy to implement it ^^ setup like this would require some internal readjustments and it's not such a small feature i'm afraid. I'll do that at some point for sure
