### ISSUE TITLE
Issue with Galaxyline in combination with Nvim-Tree

### ISSUE THREAD

**Issue by Artem-Schander** [kyazdani42/nvim-tree.lua#419]
Hi

Firstly, thank you for this package.
I created an [issue in the Galaxyline repo](https://github.com/glepnir/galaxyline.nvim/issues/177), but I think here is also the right place (at least) to share the workaround.

When I open Nvim-Tree, Galaxyline goes into short_list mode while Nvim-Tree is open (as expected), but it does not change back when I close it.

Here is a workaround for everyone experiencing the same behaviour.
```
if pcall(require, 'galaxyline') then
    vim.cmd('command! NvimTreeToggle lua require("galaxyline").load_galaxyline(); require"nvim-tree".toggle()')
end
```

**Comment by kyazdani42** [comment]
fixed by #421
