### ISSUE TITLE
Feature request: indent markers

### ISSUE THREAD

**Issue by Akin909** [kyazdani42/nvim-tree.lua#42]
This is a completely stylistic addition which I found quite nice in other file explorers e.g. `coc-explorer` below.

![image](https://user-images.githubusercontent.com/22454918/85153492-2d92a580-b24e-11ea-9a9f-d1aa9d46eebc.png)

maybe this could be added as a config option so anyone who does or doesn't like it can toggle it.

I had a quick look at the code to see if it could be added easily and looks like in the `renderer.lua` where the padding is added you could insert a special character one for most indents `|` and one at the end of that indent level (can't find the exact unicode symbol atm). Naively just inserting the symbol breaks the position based highlighting. I'm happy to dig into it when I have some free time if you haven't already had a look (if you think it's fine to implement)

**Comment by kyazdani42** [comment]
well i can take a look, i don't think it would be too hard to implement indeed :)
