### ISSUE TITLE
Unrecognized git state "UD"

### ISSUE THREAD

**Issue by uyha** [kyazdani42/nvim-tree.lua#420]
### Description
Warning `[NvimTree] Unrecognized git state "UD". Please open up an issue on https://github.com/kyazdani42/nvim-tree.lua/issues with this message.` is issued when opening a directory when that directory is git merging.

### Step to reproduce
1. Clone the following repo
```
git clone https://github.com/uyha/nvim-tree-issue.git
```
2. Do
```
git switch master
git merge origin/issue
```
3. Open the repo directory with `nvim-tree`

### Expected behavior
No warning issued

### Actual behavior
As description suggests

**Comment by kyazdani42** [comment]
fixed in 45c331230cf42
