### ISSUE TITLE
Disable statusline in file tree 

### ISSUE THREAD

**Issue by siduck76** [kyazdani42/nvim-tree.lua#424]
Hi there! Is it possible to disable the statusline in nvimtree? since nvimree's width is small so the statusline wouldnt be properly visible at all and I dont think there's any need of statusline in the file tree. 

looks bad :

![image](https://user-images.githubusercontent.com/59060246/120366770-ab4fa400-c32d-11eb-8e9b-29f661309445.png)
I made the statusline of inactive windows (StatuslineNC) look like a plain line 

![image](https://user-images.githubusercontent.com/59060246/120366669-91ae5c80-c32d-11eb-9631-2d03ed8a7c3f.png)

It would be nice if the statusline would be completely remvoed from nvimtree's window!

**Comment by kyazdani42** [comment]
i do this in my personal statusline, this should be part of the statusline api not nvim tree :)
although, you could maybe:
```vim
function! DisableST()
  return " "
endfunction
au BufEnter NvimTree setlocal statusline=%!DisableST()
```
works for me if i have no statusline enabled. This will not be implemented in nvim tree because it relies on the statusline, not nvim tree, maybe open a PR there, it's quite easy to do.

**Comment by siduck76** [comment]
@kyazdani42 I dont find that function in your nvim config! Im new to lua , could you write a lua function for it

**Comment by siduck76** [comment]
@kyazdani42 sorry to bother , Im new to lua and could you write a lua function for it

**Comment by kyazdani42** [comment]
this is not doable on nvim-tree side, you have to refer to the plugin developer for your statusline (i cannot handle every edge case for this feature, most people might not even want this).
The vim snippet might work though, did you test it out ?

**Comment by siduck76** [comment]
I use a lua config so that vimscript code didnt work

**Comment by siduck76** [comment]
@kyazdani42 statusline can be disabled in nerdtree 

https://github.com/preservim/nerdtree/issues/280

**Comment by kyazdani42** [comment]
this is not particularly something that i consider i should do in nvim tree because it's a window option that i don't manage by default so the users can basically bind an autocmd to set it themselves. I don't want to start providing setup like this or else i'd have to provide every window/buffer option one after the other.
look at [my config](https://github.com/kyazdani42/dotfiles/blob/d9a9035c6bea5b045a1f15f4055d8f84bffa157b/config/common/nvim/lua/statusline.lua#L111) to understand how i do this :)

**Comment by kyazdani42** [comment]
i think you might need to `vim.schedule` the lua function in order to apply the modification after the plugin you use sets the statusline value

**Comment by siduck76** [comment]
@kyazdani42 Is it possible to add a specific highlight for NvimTree's statuslineNc? something like NvimTreeVertsplit , which let me hide vertsplit near nvimtree. Maybe something similar could be done with statuslineNc

![image](https://user-images.githubusercontent.com/59060246/121236018-1d3a6700-c8b3-11eb-87c2-6022c7bbe8a7.png)

**Comment by kyazdani42** [comment]
you should be able to set `NvimTreeStatusLineNC`

**Comment by siduck76** [comment]
thanks! it looks much better now :D

![image](https://user-images.githubusercontent.com/59060246/121639538-4cff8f80-caaa-11eb-9710-f0dd96244ed7.png)

**Comment by JonathanLorimer** [comment]
How do we set `NvimTreeStatusLineNC`? I am having trouble figuring it out!

**Comment by siduck76** [comment]
> How do we set `NvimTreeStatusLineNC`? I am having trouble figuring it out!

hi NvimTreeStatusLineNC guibg=nvim_treebg guifg=nvim_treebg

**Comment by MGboyNew** [comment]
If you use **nvim-lualine**, it provides disabled_filetypes, which you can set to NvimTree. [nvim-lualine.disable_filetypes](https://github.com/nvim-lualine/lualine.nvim#disabling-lualine)

**Comment by riverajohan** [comment]
> If you use **nvim-lualine**, it provides disabled_filetypes, which you can set to NvimTree. [nvim-lualine.disable_filetypes](https://github.com/nvim-lualine/lualine.nvim#disabling-lualine).

For reference:
`    disabled_filetypes = { 'packer', 'NvimTree' }
`

**Comment by dave-kennedy** [comment]
This basically works in case you don't use nvim-lualine:

```
require('nvim-tree.api').events.subscribe(api.events.Event.TreeOpen, function ()
    vim.wo.statusline = ' '
end)
```

It doesn't work if you open the tree on VimEnter. Still trying to figure out why.

**Comment by alex-courtis** [comment]
> It doesn't work if you open the tree on `VimEnter`. See #1993.

Thank you

**Comment by ahbali** [comment]
> This basically works in case you don't use nvim-lualine:
> 
> ```
> require('nvim-tree.api').events.subscribe(api.events.Event.TreeOpen, function ()
>     vim.wo.statusline = ' '
> end)
> ```
> 
> It doesn't work if you open the tree on `VimEnter`. See #1993.

i had to change `api.events.Event.TreeOpen` to `"TreeOpen"` to make it work 

```lua
require('nvim-tree.api').events.subscribe("TreeOpen", function ()
     vim.wo.statusline = ' '
end)
```

**Comment by wenjie1991** [comment]
> > If you use **nvim-lualine**, it provides disabled_filetypes, which you can set to NvimTree. [nvim-lualine.disable_filetypes](https://github.com/nvim-lualine/lualine.nvim#disabling-lualine).
> 
> For reference: ` disabled_filetypes = { 'packer', 'NvimTree' }`

You can use the `lualine` extension to customize the status line for `nvim-tree`: [GitHub - nvim-lualine/lualine.nvim extension](https://github.com/nvim-lualine/lualine.nvim?tab=readme-ov-file#extensions)

**Comment by alex-courtis** [comment]
I have a status line with just the filetype for `NvimTree`, see https://github.com/alex-courtis/arch/blob/dd5d8f7458d928c6082bb36907c8b1ee015760d6/config/nvim/lua/amc/plugins/lualine.lua#L177

To disable completely, see `:help lualine-Global-options`
