### ISSUE TITLE
Option to put an arrow in front of the folder

### ISSUE THREAD

**Issue by yamatsum** [kyazdani42/nvim-tree.lua#426]
I want to display an arrow in front of the folder icon like atom or vscode.
![image](https://user-images.githubusercontent.com/42740055/120478362-bd8e1880-c3e7-11eb-8cc4-45dbb0e6d10d.png)

If I use nvim_tree_icons to set two characters(e.g. '> □'), it will be out of alignment with other than the folder.

**Comment by kyazdani42** [comment]
this should be done behind an option because we would need to make the whole tree displaced one from the left.
