### ISSUE TITLE
Pressing ESC goes up a directory. How to remap this?

### ISSUE THREAD

**Issue by d3fkon** [kyazdani42/nvim-tree.lua#429]
Pressing escape when in normal mode, goes up a directory in nvim-tree, which then need to be reset by using the `cd` key binding. Is there a way to disable this?

I have remapped the `dir_up` command to another key, but escape is bound this too by default?

**Comment by kyazdani42** [comment]
Hi, you could set `["<Esc>"] = ""` in the keymaps config

**Comment by d3fkon** [comment]
I can confirm that this doesn't work

**Comment by kyazdani42** [comment]
i'm not sure where you got that, but there is no escape key binded by default in the config actually...

**Comment by d3fkon** [comment]
So Escape key is not supposed to go up a directory?

**Comment by Himujjal** [comment]
https://github.com/kyazdani42/nvim-tree.lua/issues/255

Same issue here. Escape key actually goes up a directory. And to my surprise, it sometimes works (according to mapping) but sometimes it doesn't. This sometimes working thing is hard to explain and I have no idea how to debug. I did try mapping for `Esc` and `esc` both.

Here are my configs:

```lua
local tree_cb = require'nvim-tree.config'.nvim_tree_callback

vim.g.nvim_tree_bindings = {
  -- tried doing this
    ["<Esc>"] = tree_cb("toggle_ignored"),
    ["<esc>"] = tree_cb("close_node"),

    ["<CR>"] = tree_cb("edit"),
    ["o"] = tree_cb("edit"),
    ["<2-LeftMouse>"]  = tree_cb("edit"),
    ["<2-RightMouse>"] = tree_cb("cd"),
    ["<C-]>"] = tree_cb("cd"),
    ["<C-[>"] = tree_cb("dir_up"),
    ["s"] = tree_cb("vsplit"),
    ["i"] = tree_cb("split"),
    ["<C-t>"] = tree_cb("tabnew"),
    ["<BS>"] = tree_cb("close_node"),
    ["<S-CR>"] = tree_cb("close_node"),
    ["<Tab>"] = tree_cb("preview"),
    ["L"] = tree_cb("toggle_ignored"),
    ["H"] = tree_cb("toggle_dotfiles"),
    ["R"] = tree_cb("refresh"),
    ["a"] = tree_cb("create"),
    ["d"] = tree_cb("remove"),
    ["r"] = tree_cb("rename"),
    ["<C-r>"] = tree_cb("full_rename"),
    ["x"] = tree_cb("cut"),
    ["y"] = tree_cb("copy"),
    ["p"] = tree_cb("paste"),
    ["[c"] = tree_cb("prev_git_item"),
    ["]c"] = tree_cb("next_git_item"),
    ["q"] = tree_cb("close"),
}

```

**Comment by kyazdani42** [comment]
there is litterally no escape instance in the plugin, you should look in your configs you might have something overwriting this somehow.

**Comment by Netherdrake** [comment]
+1 same issue. Tried disabling other plugins to find a conflict, no luck.

**Comment by gegoune** [comment]
This does not happen to me. If yo think it's an issue with nvim-tree please open new issue as this one is pretty old and there was breaking change regarding key mappings since.

**Comment by alex-courtis** [comment]
Rather than binding to a NOP, you can simply unmap the key

```lua
vim.keymap.del('n', '<Esc>', { buffer = bufnr })
```

It could be that you have mappings other than normal mode. Take a look at `:cmap <Esc>` `:omap <Esc>` etc.
