### ISSUE TITLE
nvim_tree_follow does not work for files under directory named with [ or ]

### ISSUE THREAD

**Issue by tmwatchanan** [kyazdani42/nvim-tree.lua#431]
Regarding the option `let g:nvim_tree_follow = 1`, it does not follow the current location on the tree for the files that reside under directory named with `[` or `]`.

**Comment by kyazdani42** [comment]
this might be fixed by 58d7c8d1783, can you confirm ?

**Comment by kyazdani42** [comment]
had to revert because it completely broke the nvim_tree_follow feature.
I will investigate later but i believe i know where this comes from.
