### ISSUE TITLE
NvimTreeRefresh doesn't work

### ISSUE THREAD

**Issue by DanielPower** [kyazdani42/nvim-tree.lua#432]
Versions
```
MacOS 11.4
NVIM v0.5.0-dev+nightly-604-g192f89ea1                                                                                                                                                          
Build type: Release                                                                                                                                                                             
LuaJIT 2.1.0-beta3
nvim-tree.lua version: 8cf639c                                                                                                                                                                              
```

Configuration
```
vim.g.nvim_tree_ignore = { ".git", "node_modules", ".cache", "__pycache" }
vim.g.nvim_tree_auto_open = 0
vim.g.nvim_tree_auto_close = 0
vim.g.nvim_tree_follow = 1
vim.g.nvim_tree_git_hl = 1
vim.g.nvim_tree_indent_markers = 1

vim.api.nvim_set_keymap('n', '<C-_>', ':NvimTreeToggle<CR>', { noremap = true, silent = true })
```

Upon creating a new file or folder via nvim-tree, the file/folder does not appear.
Running `:NvimTreeRefresh` manually also does not make the new file/folder appear.

The only way I've found to make new files/folders appear is to completely exit Neovim, and re-open it.

**Comment by lucasvinhas** [comment]
In my case, creating a new file or folder outside nvim-tree also does not appear and does not update with `:NvimTreeRefresh`

**Comment by DanielPower** [comment]
I'm also experiencing this issue on Archlinux. So I can now confirm it is not a MacOS specific bug.

**Comment by phenax** [comment]
Same here on nixOS

**Comment by kyazdani42** [comment]
could not reproduce with the provided config, i've added a commit yesterday that broke the refresh but i reverted it afterwards. Does the issue still appear ? Also i've already noted a refresh issue in #253, maybe this is what you are experiencing ?

**Comment by Mechap** [comment]
I'm getting the same issue with NVIM v0.5.0-dev+1281-gecf075eb2

**Comment by phenax** [comment]
Updating neovim fixed this for me

**Comment by DanielPower** [comment]
This was entirely my fault. I had packer pointed at sindret's fork, to get the window picker feature, and forgot to point back to your repo when that got merged.

Switching back to your repo immediately fixed it. So this issue is invalid.
