### ISSUE TITLE
Feature Request: Add option for extra space between icon and filename

### ISSUE THREAD

**Issue by sjeon7** [kyazdani42/nvim-tree.lua#433]
For some fonts, file icons and filenames are too close which makes it harder to read.
![스크린샷 2021-06-05 오후 12 52 16](https://user-images.githubusercontent.com/26849596/120879223-dd4a5a00-c5fc-11eb-8cdd-7b40833e7172.png)
For the example above, the folder icon and filename "plugin" are too close.

I personally modify the spacing in renderer.lua, but it would be great if the spacing option for file icon and filename is provided.
![스크린샷 2021-06-05 오후 12 54 31](https://user-images.githubusercontent.com/26849596/120879271-2d292100-c5fd-11eb-82dd-cfceb284ccb2.png)
The picture above is an example of adding extra space(gap) between the file icon and filename.

Thank you for the great plugin!

**Comment by kyazdani42** [comment]
Hi ! could you tell me which font is causing this issue so i can reproduce ?

**Comment by sjeon7** [comment]
> Hi ! could you tell me which font is causing this issue so i can reproduce ? 

It is PragmataPro! The font is paid font so I will try to reproduce and report with non-paid nerd font patched fonts.

**Comment by sjeon7** [comment]
> Hi ! could you tell me which font is causing this issue so i can reproduce ?

Iosevka Nerd Font has a similar issue for .desktop types.
I used Iosevka Nerd Font from the link below.
https://www.nerdfonts.com/font-downloads

![스크린샷 2021-06-06 오후 5 36 00](https://user-images.githubusercontent.com/26849596/120918117-aa33c380-c6ed-11eb-879a-439832edd3af.png)

I guess this issue is not applicable to all fonts. However, adding the option for extra space between the file icon and the filename would be useful for some fonts.
I found that fern file tree viewer has a similar option(g:fern#renderer#nerdfont#padding).
https://github.com/lambdalisue/fern-renderer-nerdfont.vim/blob/master/doc/fern-renderer-nerdfont.txt

Thanks!

**Comment by kyazdani42** [comment]
i did not manage to enable iosevka font on my computer, not sure why, but i could implement this i don't think it would be too complicated

**Comment by kyazdani42** [comment]
should be closed by f1f14885f7
