### ISSUE TITLE
NvimTreeClose command doesn't work and throws error

### ISSUE THREAD

**Issue by phenax** [kyazdani42/nvim-tree.lua#434]
Got this error while trying to run `:NvimTreeClose` or `:NvimTreeToggle` (with the tree open)

### Error message

```
E5108: Error executing lua ...e/pack/packer/start/nvim-tree.lua/lua/nvim-tree/view.lua:247: attempt to call field 'nvim_win_hide' (a nil value)
```

### Nvim version

```
$ nvim -v
NVIM v0.5.0-dev
Build type: Release
LuaJIT 2.1.0-beta3
Compilation:
Compiled by nixbld

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/nix/store/3k95jc9mrrcrw45fnwndqv6b7j8dy78r-neovim-nightly/share/nvim"

Run :checkhealth for more info
```

**Comment by phenax** [comment]
`:help nvim_win_hide` doesn't return anything. Although `:help nvim_win_close` shows up. I tried using `nvim_win_close` instead of `nvim_win_hide` and it seems to work as expected. Not sure if the use case matches.

**Comment by kyazdani42** [comment]
update your neovim version please :) you are not using the latest master, nvim_win_hide is more than a month old i think

**Comment by phenax** [comment]
Update fixed it. Thanks!
