### ISSUE TITLE
Feature Request: Collapse the whole tree

### ISSUE THREAD

**Issue by vuki656** [kyazdani42/nvim-tree.lua#435]
Sometimes when you open a lot of files in the tree during work, the tree becomes messy so it would be nice to have a command to collapse the tree fully. I know you can collapse one level using `<BS>` but I would need to press it a few times to reset the tree fully. 

For example you could go from this:
![image](https://user-images.githubusercontent.com/8104698/120936958-06f1a700-c70b-11eb-9eae-b35dfb5115f8.png)

To this (with the help of `NvimTreeFindFile`):
![image](https://user-images.githubusercontent.com/8104698/120936985-2b4d8380-c70b-11eb-849d-c57df13cdd4b.png)

This used to be possible by using `NvimTreeToggle` twice and then `NvimTreeFindFile` but `NvimTreeToggle` no longer collapses it.

Thanks for the awesome plugin.

**Comment by kyazdani42** [comment]
```lua
function _G.collapse_nvim_tree()
  local lib = require'nvim-tree.lib'
  for _, node in pairs(lib.Tree.entries) do
    if node.open then
      node.open = false
    end
  end
  lib.refresh_tree()
end
```
until something proper is written this will do the trick (but only closes opened root directories). You could implement a better solution with a recursive function like you can find in `lib.lua`

**Comment by vuki656** [comment]
Thanks for the hint.

I'm not that experienced with nvim API and Lua but will give it a go.

**Comment by ceigh** [comment]
Manage this with:

```lua
local function collapseNode (node)
  local entries = node.entries
  if not entries then return end
  for _, e in pairs(entries) do collapseNode(e) end
  node.open = false
end

function _G.nvimTreeCollapse()
  local lib = require'nvim-tree.lib'
  collapseNode(lib.Tree)
  lib.refresh_tree()
end

require('nvim-tree').setup {
  view = {
    mappings = {
      list = {
        { key = 'X', cb = ':call v:lua.nvimTreeCollapse() | normal gg<cr>' },
      },
    },
  },
}
```

(recursive)

**Comment by vuki656** [comment]
> Manage this with:
> 
> ```lua
> local function collapseNode (node)
>   local entries = node.entries
>   if not entries then return end
>   for _, e in pairs(entries) do collapseNode(e) end
>   node.open = false
> end
> 
> function _G.nvimTreeCollapse()
>   local lib = require'nvim-tree.lib'
>   collapseNode(lib.Tree)
>   lib.refresh_tree()
> end
> 
> require('nvim-tree').setup {
>   view = {
>     mappings = {
>       list = {
>         { key = 'X', cb = ':call v:lua.nvimTreeCollapse() | normal gg<cr>' },
>       },
>     },
>   },
> }
> ```
> 
> (recursive)

Works great but seems a little slow.

**Comment by ceigh** [comment]
yes, this is a naive implementation :) ideally, (probably) close all the nodes of the first level in the first pass, and everything that is nested - in the background

**Comment by kyazdani42** [comment]
there is a `require'nvim-tree.lib'.collapse_all()` function to collapse the whole tree already :)
