### ISSUE TITLE
Why not support opening a specified directroy ? 

### ISSUE THREAD

**Issue by paopaol** [kyazdani42/nvim-tree.lua#436]
it only support open directory of current file.

**Comment by kyazdani42** [comment]
please make a clearer feature request, i do not understand what you are trying to say :)

**Comment by Louis-Amas** [comment]
I think he is trying to say that he want to be able to launch nvim-tree when 
`nvim dir/`

**Comment by kyazdani42** [comment]
i'm not sure, because doing `nvim dir` opens the tree on the directory already (with `vim.g.nvim_tree_auto_open=1`)

**Comment by linkinmedo** [comment]
@kyazdani42 I came here to search for a solution for the same thing if I understand him correctly here's the scenario.

let's say you opened vim like this
```
nvim ./directory/file.js
```

then opened the tree, it will be at the root with the directory we are inside collapsed while it would make sense to have that directory expanded in the tree view.

**Comment by paopaol** [comment]
Sorry, maybe I didn't express it clearly. I mean, is there any way to open a user-specified directory? For example: NvimTree /myproject1, :NvimTree /myproject2. The current command only supports opening the directory where the current buffer is located

**Comment by kyazdani42** [comment]
i see, it would not be very hard to do i think but not possible as of now. You could `let g:nvim_tree_update_cwd=1` and then use `:cd` to navigate between directories for now :)

**Comment by ChristianChiarulli** [comment]
For me this just opens a file named after the dir, not sure why....

like if I open `plugin/` it will create a buffer named plugin

same with `.`

**Comment by kyazdani42** [comment]
this is default vim behavior.

**Comment by ChristianChiarulli** [comment]
@kyazdani42 usually netrw takes over, note the message at the bottom ("." is a directory). 

![image](https://user-images.githubusercontent.com/29136904/123864213-7e74b980-d8f8-11eb-9302-fbb3deb47441.png)

It's possible I'm misunderstanding or misconfiguring something tho.

**Comment by kyazdani42** [comment]
@ChristianChiarulli this is another kind of feature that was asked before, it's out of the scope of this issue :)
refer to #248 #214 #200

**Comment by kyazdani42** [comment]
i'd like to tackle this but i have another issue that bothers me quite a lot that i need to fix first

**Comment by arowe92** [comment]
+1 For opening specific directories from the command
`:NvimTreeOpen ~/.config`
I use this functionality in some scripts that call NERDTree and would love to transfer the calls over :)

**Comment by kyazdani42** [comment]
you can `:e ~/.config`

**Comment by kyazdani42** [comment]
i think this can be closed now that nvim-tree support hijacking `:e dir` and `:vsplit dir`. I you really want NvimTreeOpen to implement this scenario, i could implement it. reopen this issue if this is the case
