### ISSUE TITLE
Refresh doesn't work on APFS filesystem 

### ISSUE THREAD

**Issue by vlstv** [kyazdani42/nvim-tree.lua#440]

**Comment by kyazdani42** [comment]
Hi, could this be related to #425 ?

**Comment by lzygmanski** [comment]
I had the same problem. Updating nvim fixed the issue -> https://github.com/kyazdani42/nvim-tree.lua/issues/425#issuecomment-857774517

**Comment by vlstv** [comment]
thanks @lzygmanski! upgrade helped
