### ISSUE TITLE
NvimTreeToggle for files in hidden directories

### ISSUE THREAD

**Issue by RaZ0rr-Two** [kyazdani42/nvim-tree.lua#442]
Using latest nvim nightly appimage and have the setting `let g:nvim_tree_follow = 1`. Whenever nvim tree is toggled for files in hidden directory, it only expands upto the lowest non-hidden folder in that file path. Works as expected after toggling `show dotfiles`. Is there a way to automate this for toggling dotfiles and showing the file if it is in a hidden directory?

**Comment by kyazdani42** [comment]
i guess you could hijack the refresh by checking the name of the file, and if it starts with a `.`, you toggle the hidden file then call the refresh. I'll add a snippet that demonstrate that when i have a bit of free time.

**Comment by RaZ0rr-Two** [comment]
Thanks for the help!

Also, are these two equivalent? (except for the ability to toggle)

1.  `NvimTreeToggle + let g:nvim_tree_follow = 1`
2.  `NvimTreeFindFile`

**Comment by kyazdani42** [comment]
they seem to be ^^
