### ISSUE TITLE
nvim-tree jumps to folder on file open

### ISSUE THREAD

**Issue by wirtsi** [kyazdani42/nvim-tree.lua#443]
Hey

not sure if this is a bug or a feature (and if the latter, how to disable it)

![nvim-tree](https://user-images.githubusercontent.com/276751/121527065-4e717f00-c9fa-11eb-8bb4-353c51a06f16.gif)

When opening a file from nvim-tree, the tree pane jumps to the folder of the file that was just opened. When going back to the tree view with C-w left then the tree jumps back to the project root.

What I would like to have is

The tree stays at the root level, the path to the currently open file is expanded. When moving to the tree window, the tree keeps the current state

Thanks & bests

**Comment by kyazdani42** [comment]
related to #441, i think you use autochdir or something like that. I've disabled the `nvim_tree_update_cwd` by default now so it should not happen

**Comment by wirtsi** [comment]
Thanks @kyazdani42, that fixed it
