### ISSUE TITLE
Unrecognized git state "AA".

### ISSUE THREAD

**Issue by yofriadi** [kyazdani42/nvim-tree.lua#444]
error: `[NvimTree] Unrecognized git state "AA". Please open up an issue on https://github.com/kyazdani42/nvim-tree.lua/issues with this  message.`

I think this is the same as other similar error, this happens when in mid merge conflict.

**Comment by kyazdani42** [comment]
i see thanks :)

**Comment by nicovak** [comment]
Got the same, happening on merge conflict

**Comment by kyazdani42** [comment]
fixed in 4a043ff5eb24
