### ISSUE TITLE
How to make <CR> be <C-]> without losing edit?

### ISSUE THREAD

**Issue by brendonrapp** [kyazdani42/nvim-tree.lua#447]
Instead of expanding folders, I want \<CR> to enter the folder the same way \<C-]> does when put on a directory.

But if I edit mappings to make \<CR> be "cd", then it loses its "edit" mapping when used on a file.

How can I make \<CR> be "cd" on folders and still "edit" on files?

**Comment by sindrets** [comment]
You're gonna have to do some custom scripting for that. Something like:

```lua
_G.NvimTreeConfig = {}

function NvimTreeConfig.cd_or_open()
  local lib = require'nvim-tree.lib'
  local node = lib.get_node_at_cursor()
  if node then
    if node.entries then
      require'nvim-tree'.on_keypress("cd")
    else
      require'nvim-tree'.on_keypress("edit")
    end
  end
end
```

And then in your mappings, you do:

```lua
{
  ["<CR>"] = ":lua NvimTreeConfig.cd_or_open()<CR>",
}
```

**Comment by kyazdani42** [comment]
to specific to implement, i'm going to mark this as documentation.

**Comment by liuxian1990** [comment]
The current version:

 if node.entries then  => if node.has_children ~= nil then

**Comment by kyazdani42** [comment]
now it's `node.nodes`

**Comment by alex-courtis** [comment]
Documented via [`print_path` example](https://github.com/kyazdani42/nvim-tree.lua#settings)
