### ISSUE TITLE
Showing buffer Titles in Tabline when opening multiple files 

### ISSUE THREAD

**Issue by Trid-collab** [kyazdani42/nvim-tree.lua#449]
Could you also share how to show the all buffers (title/name) in tabline in vim. What are the vim settings for the same. Today I get to see the buffer name on the top using "set showtabline=2" when I open a file using tabe, but I open a file using file tree plugin "nvim-tree" it does not show the buffer title in tabline even though when I buffers its shows the files in buffer.

**Comment by sindrets** [comment]
Neovim does not list buffers in the tabline by default. To achieve this you're gonna have to customize your `tabline`. See `:h setting-tabline`. There are of course also many plugins that already do this. Take a look at [nvim-bufferline](https://github.com/akinsho/nvim-bufferline.lua) and [barbar.nvim](https://github.com/romgrk/barbar.nvim) for instance.

**Comment by kyazdani42** [comment]
as @sindrets said, take a look at the plugins that aims to provide such feature :)
if you open a file using `<C-t>` it will show in the tabline because it will open in a new tab
