### ISSUE TITLE
Is there a way to align files to dirs when not using nvim-web-devicons?

### ISSUE THREAD

**Issue by stsewd** [kyazdani42/nvim-tree.lua#45]
Thanks very much for this plugin, I'm already using it as replace for nerdtree. I haven't found a way to make it look like second the pic below.

![](https://user-images.githubusercontent.com/4975310/85213695-694d6e00-b327-11ea-83fa-821b0badee10.png)
![](https://user-images.githubusercontent.com/4975310/85213714-9c8ffd00-b327-11ea-8006-b3fb6ed11c93.png)

I've already tried setting 

```vim
let g:lua_tree_icons = {
      \ 'default': ' ',
      \}
```

And something else, that isn't related to this, but `g:lua_tree_follow` defaults to 1, but in the docs it says it defaults to 0.

**Comment by kyazdani42** [comment]
i fixed the lua_tree_follow issue thanks for mentionning it.
I'll try and see what i can do, it might not be too hard to add.

**Comment by kyazdani42** [comment]
well i see an issue with this:
if you align your text under the folder text, it will look like these entries belong to the directory, although they are siblings of the dir and not children. How would you handle that ?

**Comment by kyazdani42** [comment]
well i see, nerdtree idents with 4 spaces in a subdir (which i don't quite like).\
I will consider this as a feature request, but if you could implement it yourself, it would save me much time :)
