### ISSUE TITLE
Tree does not refresh after neogit's operations

### ISSUE THREAD

**Issue by gegoune** [kyazdani42/nvim-tree.lua#451]
Hey @kyazdani42, hope you are doing well!

After staging, committing, etc files via [TimUntersberger/neogit](https://github.com/TimUntersberger/neogit) and returning to previous tab (by closing neogit's tab) which contains nvim-tree window one can see that  git status(es) is(are) not refreshed. I am not sure whether that is something that nvim-tree should support, if not, do you mind pointing towards possible solution?

Thanks

CC @TimUntersberger

**Comment by TimUntersberger** [comment]
We emit a `NeogitStatusRefreshed` user event when the status gets refreshed.

Either `nvim-tree` or the user would have to link this event with `:NvimTreeRefresh`

```vim
autocmd User NeogitStatusRefreshed :NvimTreeRefresh<CR>
```

**Comment by cloggier** [comment]
Amazing, thank you very much @TimUntersberger. @kyazdani42 is it something you think should land in nvim-tree?

**Comment by kyazdani42** [comment]
Hi ! I'm not too sure if this should go in the documentation or in the codebase, i'll think about it and come back with a better answer :)

**Comment by kyazdani42** [comment]
we'll add that in the codebase if more users come with the same issue

**Comment by kyazdani42** [comment]
i've added a better fix for neogit and gv to avoid opening nvim-tree, makes more sense :) 44678adc1e6ab

**Comment by gegoune** [comment]
As I replied in Neogit's issue, I think there was bit of misunderstanding, unless I misunderstand aforementioned fix. This is not to automatically open nvim-tree on Neogit's tabs? If so, that is not what that issue is about. Sorry if I did not make it clear. My original report was for nvim-tree retaining stale git information for files that had their git status changed by Neogit.

To test it:
- edit file tracked by git
- open nvim-tree, notice how it shows modified status
- open Neogit and stage that change
- close Neogit tab (`q`)

At this point nvim-tree will still report modified state rather than 'staged'. Running `NvimTrreeRefresh` updates tree, which I tried to automate by hooking into event emitted by Neogit, but it led to [that issue](https://github.com/TimUntersberger/neogit/issues/158).

**Comment by kyazdani42** [comment]
implemented this because i realized i had the same thing going on for fugitive. Closing.

**Comment by gegoune** [comment]
Effectively https://github.com/kyazdani42/nvim-tree.lua/commit/f178c8c8c5cb994326578a24d3296dde6f2e9bd3 is the same as autocommand I had set up which is the cause of the cursor flickering on buffer change. But now I can't disable it. :|

**Comment by gegoune** [comment]
Just tried with all my configuration removed, issue persists. Do you want me to open new issue to track it properly?

**Comment by kyazdani42** [comment]
should be properly fixed now, can you confirm ?

**Comment by gegoune** [comment]
Unfortunately it's still there. :| It looks slightly different now though, but it might just be me. I think it's slightly faster (blinking) and not taking as long any more, but definitely still there.

**Comment by kyazdani42** [comment]
just found the culprits and indeed, it's the abusive calls of the system and systemlist calls creating this cursor blink.
I'm not too sure how to fix that properly without rewriting the whole thing asynchronously.

**Comment by gegoune** [comment]
That's a great news, well, in a way. At least you can reproduce it and know the cause. Some time ago you have removed async thing, can look for revision if you want me to - do you think that might have had something to do with it?

**Comment by kyazdani42** [comment]
not really, i'm just receiving too many events now, maybe some guard mecanism like only one update for 300ms or so would be sufficient i believe.

**Comment by kyazdani42** [comment]
tried something that fix this on my computer, could you try latest master please ?

**Comment by gegoune** [comment]
Ah, I think this works just fine now! Did not see it flicker yet after switching buffers quite a few times. Nice one! Thanks a lot for looking into it!

**Comment by kyazdani42** [comment]
:+1: but i think i've seen some flickering sometime, actually, neogit sends its status update on each bufenter which makes a lot of unecessary rerenders on my end. @TimUntersberger do you know if this is expected ?

**Comment by gegoune** [comment]
I have noticed some extended load times for neogit, I think it tries to load git status too often/too early. I wouldn't mind having to wait a moment when invoking Neogit so it only runs its stuff when needed.
