### ISSUE TITLE
Feature request: NvimTreeFindFile close nvim-tree

### ISSUE THREAD

**Issue by kuznetsss** [kyazdani42/nvim-tree.lua#452]
Hello! Thank you for the plugin! It's very useful.

What do you think about making `NvimTreeFindFile` to work like `NvimTreeToggle` but it should open nvim-tree at the file of active buffer?

My current workflow is:
- `NvimTreeFindFile`
- Walk through tree to see what files are near and open some of them
- `NvimTreeToggle` to close nvim-tree

It would be useful to map opening and closing nvim-tree at one key. I know that I could add some logic to my mapping to achieve desired behaviour, but maybe it would be better to add such functionality to nvim-tree.

**Comment by sindrets** [comment]
This is a pretty niche feature. I think it's better left to scripting. You can easily achieve this functionality with something like this:

```lua
_G.NvimTreeConfig = {}

function NvimTreeConfig.find_toggle()
  local view = require'nvim-tree.view'
  if view.win_open() then
    view.close()
  else
    vim.cmd("NvimTreeFindFile")
  end
end
```

And then in your mappings, do something like:

```vim
nnoremap <leader>b <Cmd>lua NvimTreeConfig.find_toggle()<CR>
```

**Comment by kuznetsss** [comment]
Thank you. I'll add this to my config.

**Comment by cloggier** [comment]
@kyazdani42 mentioned a while ago that he would like to get rid of commands and let users script stuff. It would be nice to get most common use cases added to Wiki.

**Comment by sindrets** [comment]
Yeah, some API documentation is sorely needed. I might start writing it when I get some time.
