### ISSUE TITLE
Can't seem to resize the window at runtime

### ISSUE THREAD

**Issue by hoopes** [kyazdani42/nvim-tree.lua#454]
From the main page:
`You can edit the size of the tree during runtime with :lua require'nvim-tree.view'.View.width = 50`

This doesn't seem to have any effect for me, no matter what value i set. 

```
vim.g.nvim_tree_side = 'left'
vim.g.nvim_tree_auto_open = 1
vim.g.nvim_tree_auto_close = 1
vim.g.nvim_gitignore = 1
vim.g.nvim_tree_width_allow_resize = 1

vim.api.nvim_set_keymap('', '<Leader><Leader>t', ':NvimTreeToggle<CR>', { noremap = true })
vim.api.nvim_set_keymap('', '<Leader><Leader>f', ':NvimTreeFind<CR>', { noremap = true })
```

This is the set of values I have for the `nvim_tree` config. If you would want the entire vim config for all plugins, please let me know, I can provide it. 

Ultimately, I'm trying to increase the width of the tree when it's focused, and set it back to its original size when it's not. A feature request might be `nvim_tree_width_when_focused` and `nvim_tree_width_when_unfocused` or whatever that took number of columns (or percent of the width of the screen).

I'm trying to accomplish that with

```
vim.api.nvim_command([[
augroup ToggleNvimTreeSize
  autocmd BufEnter NvimTree :lua require'nvim-tree.view'.View.width = 60
  autocmd BufLeave NvimTree :lua require'nvim-tree.view'.View.width = 30
augroup END
]])
```

now, but it's not resizing anything :)

Thanks for the plugin!

**Comment by sindrets** [comment]
`View.width` is only applied when creating the window (i.e. toggling NvimTree). But if you only want to resize the window when it receives / loses focus, just use normal resize commands instead:

```vim
au WinEnter NvimTree :vertical res 60
au WinLeave NvimTree :vertical res 30
```

No need to offer this from the API.

**Comment by hoopes** [comment]
ah, sorry, i interpreted "runtime" to mean "while nvim is running". 

This is super great, thanks!!!!!!!
