### ISSUE TITLE
Can't create file in compacted folder

### ISSUE THREAD

**Issue by c3-pennsu** [kyazdani42/nvim-tree.lua#458]
If a directory has only one folder it got compacted in the tree as one group.

Somehow I can't create a new file in the directory if they are compacted when clicking on "a". When I tried to delete the previous folder it didn't allow me to.

**Comment by kyazdani42** [comment]
you cannot:
`let g:nvim_tree_group_empty=0` for now, i might implement a fix for that at some point

**Comment by c3-pennsu** [comment]
Thanks. I can do this in other tree solutions like NERDTree.

**Comment by kyazdani42** [comment]
i understand, but this plugin is quite new compared to nerd tree which is a few years old and i'm working on it on my spare time so sometimes features can take a while before being added. If you wished to implement it yourself, go for it :)

**Comment by kyazdani42** [comment]
closed in `1.2.4` (425f5ee) you can now add files anywhere on the system, you can remove the folder name to create a file between two grouped folders
