### ISSUE TITLE
Plugin not loaded by vim-plug

### ISSUE THREAD

**Issue by Altreus** [kyazdani42/nvim-tree.lua#459]
My brand new neovim installation has nothing but the plugins in the readme, plus a manual bind to test with:

```
call plug#begin(stdpath('data') . '/plugged')
" requires
Plug 'kyazdani42/nvim-web-devicons' " for file icons
Plug 'kyazdani42/nvim-tree.lua'
call plug#end()

nnoremap <C-n> :NvimTreeToggle<CR>
```

Nothing I do will cause `NvimTreeToggle` to be a recognised command.

However, if I install NERDTree by adding `Plug 'scrooloose/nerdtree', { 'on':  'NERDTreeToggle' }` (from the vim-plug readme) it works fine.

Something about nvim-tree is causing vim-plug (or nvim itself) not to recognise it as something to load once it is installed.

Edited to say:

The OS is Debian on Windows (the WSL "app"), which claims to be Debian 10.9 (Buster). nvim is installed from apt on that.

Edited again to say:

The nightly (currently NVIM v0.5.0-dev+1423-ge2d3ad7bc) picks it up. Not sure if the packaged version in debian is an intended target.

**Comment by baahrens** [comment]
It looks like the latest stable version for debian is `4.4.1` and this plugin doesn't load for anything that is not the nightly build.
ref: https://github.com/kyazdani42/nvim-tree.lua/blob/bfeaf4c8ef5ff24e93005da2561407a13ba69d4d/plugin/tree.vim#L1

**Comment by kyazdani42** [comment]
this plugin uses neovim nightly, it's specified in the readme
