### ISSUE TITLE
Plugin sets `splitbellow` globally

### ISSUE THREAD

**Issue by stsewd** [kyazdani42/nvim-tree.lua#46]
`splitbellow` is a global option.

```
'splitbelow' 'sb'	boolean	(default off)
			global

``` 

https://github.com/kyazdani42/nvim-tree.lua/blob/3bcfc70ea6759f40cc12e31e20f8b6c36f9ed2ac/lua/lib/lib.lua#L26

Actually, I can see other global options being set as well, like `sidescroll`

**Comment by kyazdani42** [comment]
fixed in master
