### ISSUE TITLE
Starting Neovim with a folder argument makes nvim-tree show current folder on terminal and not chosen folder

### ISSUE THREAD

**Issue by wiliamks** [kyazdani42/nvim-tree.lua#463]
I don't know if the title is clear enough, but let's say on the terminal i am on a folder like this
```
$ cd ~/tmp/example_workspace
$ tree
.
├── project1
│   └── src
│       └── main.c
└── project2
    └── foo.py
```
then I type
```
nvim project1/
```
then nvim-tree shows this tree
```
├── project1
│   └── src
│       └── main.c
└── project2
    └── foo.py
```
instead of this
```
├── src
│   └── main.c
```

Edit: nvm, just fixed it with this command on my ```init.vim```
```vim
autocmd VimEnter * if argc() == 1 && isdirectory(argv()[0]) && !exists('s:std_in') |
    \ wincmd p | enew | execute 'cd '.argv()[0] | endif 
```

**Comment by kyazdani42** [comment]
does not look like an issue on the plugin's end then ? i could not reproduce what you described

**Comment by wiliamks** [comment]
> does not look like an issue on the plugin's end then ? i could not reproduce what you described

yes, not an issue on the plugin, that's why I closed the issue.
