### ISSUE TITLE
Getting a prompt when trying to create a split when float is visible

### ISSUE THREAD

**Issue by andersevenrud** [kyazdani42/nvim-tree.lua#464]
If you for example run `lua vim.lsp.diagnostic.show_line_diagnostics()` and you get a popup, then navigate to nvim-tree and do ex <kbd>C-v</kbd> you'll get prompted to select which window to do a split (shown as `A` on the bottom) even though there's technically only one to choose from.

Also, If I press `B` in this case it creates a split, but the float stays open in the wrong location.

Initial state:

![01](https://user-images.githubusercontent.com/161548/122833931-07369880-d2ee-11eb-9197-ca08b136546a.png)

Open diagnostics float:
![02](https://user-images.githubusercontent.com/161548/122833947-0d2c7980-d2ee-11eb-9096-aecff7d1b64f.png)

Request split in nvim-tree:

![03](https://user-images.githubusercontent.com/161548/122833957-10c00080-d2ee-11eb-9c07-abb441ee8c93.png)

Choosing `B`:

![04](https://user-images.githubusercontent.com/161548/122833964-13225a80-d2ee-11eb-95ee-caacccd22975.png)

**Comment by kyazdani42** [comment]
Should be fixed in ed7f3851d17e37b, could you confirm ?

**Comment by andersevenrud** [comment]
@kyazdani42 Can confirm this fixes it. Thanks a lot!

**Comment by kyazdani42** [comment]
commit broke window picking entirely, i had to apply another patch, could you confirm it still work ?

**Comment by andersevenrud** [comment]
I can confirm that it still works.
