### ISSUE TITLE
Open a file in new tab, tree explorer always display the root folder

### ISSUE THREAD

**Issue by Kangaxx-0** [kyazdani42/nvim-tree.lua#465]
I am working on a project, the code repo structure like below

-A
  -- .git
  -- tests
  -- src
      -- react project
         -- 1
         -- 2
         -- 3
      -- Microservice 1
      -- Microservice 2
      -- Function xxx
      -- etc.
  -- documenation
  -- scripts
  -- pipelines
  -- xxx.sln(s)
  -- etc.

my PWD  is `/A/src/<react project>`, every time I launch nvim, the explorer folder looks fine and i saw 1,2,3, however, when I open up any file that resides in my PWD, nvim-tree explorer displays everything under the root folder.  If I close explorer and re-open it, it looks ok again. 

Below setting configs did not solve my issue:
- vim.g.nvim_tree_tab_open
- vim.g.nvi_tree_update_cwd 

Could you someone to help, please?

**Comment by pystardust** [comment]
I am facing a similar issue, the pwd is not being updated even tho I did
```
let g:nvim_tree_update_cwd = 1 
```
It updates for the nvim tree buffer but doesn't globally, retoggling nvimtree messes it up again.
I am currently using an older version fork of nerdtree https://github.com/simrat39/nvim-tree.lua where this works well till I find a fix.

**Comment by kyazdani42** [comment]
do you use something like `vim-rooter` or `autochdir` ?
