### ISSUE TITLE
Option to always show certain folders/files

### ISSUE THREAD

**Issue by cseelus** [kyazdani42/nvim-tree.lua#467]
An option like `let g:nvim_tree_always_show = [ 'some_folder' ]` would be nice.

Lets say you have `g:nvim_tree_gitignore` enabled, are within a JS/TS project where the `node_modules` folder is in your `.gitignore` but need to regularly access this folder via nvim-tree, this would come in handy.

**Comment by kyazdani42** [comment]
you could implement it if you wish :)

**Comment by kyazdani42** [comment]
this is already possible with the `filters.excluded` key
