### ISSUE TITLE
Width of the tree window resets to default after certain operations

### ISSUE THREAD

**Issue by johnnovak** [kyazdani42/nvim-tree.lua#468]
### Issue 1 - Width of the tree window is not remembered

1. Open the tree with 'open' or 'toggle'
2. Increase the size of the tree window with `<C-w>10>`
3. Toggle the tree window off, then back on
4. The tree window appears with the default width, not with the modified width

### Issue 2 - Width of the tree window is reset to default when opening a file

1. Open the tree with 'open' or 'toggle'
2. Increase the size of the tree window with `<C-w>10>`
3. Press Enter on a file to open it
4. The width of the tree window reverts to the default width

**Comment by kyazdani42** [comment]
for 1: you need to save the new width if you wish to preserve the width in `'nvim-tree.view'.View.width`
for 2: `let g:nvim_tree_width_allow_resize  = 1 "0 by default, will not resize the tree when opening a file`

**Comment by johnnovak** [comment]
1. Can't we introduce an option for this? e.g. `g:nvim_tree_preserve_width` would be much more convenient.
2. `g:nvim_tree_width_allow_resize` doesn't work, it seems this option has been removed (searching for `nvim_tree_width_allow_resize` in the repo yields no hits in the code, just in the help and the README)

**Comment by kyazdani42** [comment]
i guess we should implement something for resizing the tree, it would be convenient and i've been struggling with this for a long time. I'll work on that soon

**Comment by johnnovak** [comment]
> i guess we should implement something for resizing the tree, it would be convenient and i've been struggling with this for a long time. I'll work on that soon

Cool, sounds good, thanks. Maybe update the documentation in the meantime because as I said `nvim_tree_width_allow_resize` no longer exists.

**Comment by kyazdani42** [comment]
ill just reimplement it

**Comment by johnnovak** [comment]
I've just updated and tried it, and it doesn't work — the tree gets reset to the default whenever you open a file. Tried setting it explicitly to 1 in the config, same results.

**Comment by kyazdani42** [comment]
set it to `0` so it does not auto_resize.

**Comment by johnnovak** [comment]
> set it to `0` so it does not auto_resize.

Thanks, it works as expected when I set it to zero.

I think the doco could use some improvements; based on the wording of this option it's a bit unclear what "saved width" means (I thought it was the width I set with my windows resize commands).

```
Can be 0 or 1. When 1, it will resize the tree to it's saved width
when opening a new file.
Default is 1
```

**Comment by kyazdani42** [comment]
i think this can be closed :)

**Comment by spareslant** [comment]
Those who are looking for solution for
**Issue 1 - Width of the tree window is not remembered**

following works:

define following in your one of your lua config files or create a new file. Probably name it as "nvim-tree-additional-config.lua"

```lua
vim.g.nvimTreeWidth = 30
nvim_tree_toggle = function()
  local view = require("nvim-tree.view")

  open = function()
    require("nvim-tree").find_file(true)
  end

  close = function()
    view.close()
  end

  get_current_nvimtree_width = function()
    for _, buf in pairs(vim.api.nvim_list_bufs()) do
      if vim.bo[buf].ft == "NvimTree" then
        return vim.fn.winwidth(vim.fn.bufwinid(buf))
      end
    end
  end

  if view.is_visible() then
    vim.g.nvimTreeWidth = get_current_nvimtree_width()
    close()
  else
    view.View.width = vim.g.nvimTreeWidth
    open()
  end
end

return nvim_tree_toggle
```

Somewhere In your key mapping config file define following

```lua
local opts = { noremap = true, silent = true }
nvim_tree_toggle = require("nvim-tree-additional-config")
map("n", "<A-e>", "<cmd> lua nvim_tree_toggle()<CR>", opts)
```
Note: I am using <option-e>  key on mac to toggle the tree.

**Comment by alex-courtis** [comment]
@spareslant you can simplify this further with an automatic call to your width function. See `:help nvim-tree.view.width`.

**Comment by spareslant** [comment]
> 

@alex-courtis , I made the following change in my above code as you suggested.

```lua
  if view.is_visible() then
    vim.g.nvimTreeWidth = view.width.   -- changed line
    close()
  else
    view.View.width = vim.g.nvimTreeWidth
    open()
  end
end
```

Note: `local view = require("nvim-tree.view")` already defined in above code.

But it did not work. Following is the error
```
E5108: Error executing lua ...e/pack/packer/start/nvim-tree.lua/lua/nvim-tree/view.lua:111: attempt to index local 'size' (a nil value)
stack traceback:
        ...e/pack/packer/start/nvim-tree.lua/lua/nvim-tree/view.lua:111: in function 'get_size'
        ...e/pack/packer/start/nvim-tree.lua/lua/nvim-tree/view.lua:278: in function 'resize'
        ...e/pack/packer/start/nvim-tree.lua/lua/nvim-tree/view.lua:219: in function 'open'
        ...te/pack/packer/start/nvim-tree.lua/lua/nvim-tree/lib.lua:78: in function 'open_view_and_draw'
        ...te/pack/packer/start/nvim-tree.lua/lua/nvim-tree/lib.lua:105: in function 'open'
        ...m/site/pack/packer/start/nvim-tree.lua/lua/nvim-tree.lua:95: in function 'open'
        ...m/site/pack/packer/start/nvim-tree.lua/lua/nvim-tree.lua:164: in function 'find_file'
        /Users/aUser/.config/nvim/lua/cokeline-config/tree.lua:6: in function 'open'
        /Users/aUserl/.config/nvim/lua/cokeline-config/tree.lua:27: in function 'nvim_tree_toggle'
        [string ":lua"]:1: in main chunk
```

**Comment by alex-courtis** [comment]
I think you might be overthinking this; `nvim_tree_toggle` is not needed.

`view.width` is a simple function that nvim-tree calls for you to set the width.

You can store the width via the Resize event. See `:help nvim-tree-events`.

**Comment by erykjarocki** [comment]
in setup add

```
 actions = {
  open_file = {
    resize_window = false,
  },
},
```
to presever window size when opening the file

**Comment by nimaai** [comment]
please add the feature to be able to remember the last manually set width of the nvim-tree window.
