### ISSUE TITLE
Weird space before some specific icons

### ISSUE THREAD

**Issue by ichirou2910** [kyazdani42/nvim-tree.lua#475]
I just switched from coc-explorer to nvim-tree today. So far the experience is awesome, except for this thing.

In the image, the left side is coc-explorer and the other is nvim-tree. As you can see, there is a weird space before typescript and svg icon. Haven't found any weird space with other icons.

My config only has custom icons/color, the rests are default, and I'm 100% certain I didn't put any space there. Do you have any idea?

![image](https://user-images.githubusercontent.com/51302893/123785539-d9aba980-d902-11eb-968d-572f1c46c630.png)

**Comment by ichirou2910** [comment]
Something I just found, this prints out when I run `require'nvim-web-devicons'.get_icon("svg")` which is clearly reversed, same thing happened with typescript.

![image](https://user-images.githubusercontent.com/51302893/123787676-52136a00-d905-11eb-9cbd-039ea629980f.png)

After further investigating I found out typescript and svg icons are categorized in "Arabic"

![image](https://user-images.githubusercontent.com/51302893/123788004-b33b3d80-d905-11eb-98a1-23e121c8a4eb.png)

I guess this is a font issue? But I don't understand why it's normal in coc-explorer. My font is `JetBrainsMono Nerd Font`

**Comment by kyazdani42** [comment]
https://github.com/kyazdani42/nvim-web-devicons/issues/46
looks like this issue, i'm not sure why it happens though but with your help i might fix it :)

**Comment by kyazdani42** [comment]
i think this might be a terminal related issue. Lua might output rtl character and some terminal wont handle it properly (it works fine in alacritty).
if you use kitty, try using `force_ltr` in your config

**Comment by ichirou2910** [comment]
That's weird. I'm actually using Alacritty. So far I haven't seen a config option related. Did I miss something?

**Comment by ichirou2910** [comment]
Oh I found it. I'm using an older update version of alacritty. Reinstall the latest works fine.
