### ISSUE TITLE
Overriding mappings stopped working

### ISSUE THREAD

**Issue by kristijanhusak** [kyazdani42/nvim-tree.lua#481]
Hey,

I have this in my init.lua to override just a couple of mappings:

```lua
vim.g.nvim_tree_bindings = {
  { key = 's', cb = ':lua require"nvim-tree".on_keypress("vsplit")<CR>' },
  { key = 'C', cb = ':lua require"nvim-tree".on_keypress("cd")<CR>'}
}
```

I updated it according to the latest update, but then some mappings stopped working. I checked what's happening and figured out that `vim.tbl_extend` is being used to merge them. Issue with `vim.tbl_extend` is that it knows how to merge hashes/objects/dictionaries, but not arrays.

Example:

```lua
print(vim.inspect(vim.tbl_extend(
  'force', 
  { { 1 }, { 2 } }, 
  { { 3 } , { 4 } }
)))
```

Expectation is that we get all items in the result, but the result is only this:

```
{ { 3 }, { 4 } }
```

Which basically causes my configuration to override the first two item in the default bindings.

**Comment by jdansev** [comment]
I have an issue too which I think may be related. I have a few keybindings set up using the updated method and whenever I try to open a folder on the tree nvim says `Cannot make changes, 'modifiable' is off`

**Comment by kyazdani42** [comment]
this is a bug indeed I should've used table concat here. sorry I'll fix that in the morning

**Comment by kyazdani42** [comment]
should be fixed in 4a9a17b7f13ca

**Comment by kristijanhusak** [comment]
Works now, thanks!

**Comment by tkkcc** [comment]
I am on latest 933d69a, hit `a` still gives `Cannot make changes, 'modifiable' is off`. I use following settings.

```lua
local tree_cb = require'nvim-tree.config'.nvim_tree_callback
vim.g.nvim_tree_bindings = {
  -- ["I"]              = tree_cb("toggle_ignored"),
  ["H"] =               ":tabp<cr>",
  -- ["D"]              = tree_cb("toggle_dotfiles"),
}
EOF
```
And comment out `vim.g.nvim_tree_bindings` works.

**Comment by kyazdani42** [comment]
maybe update to master first, i added an informational message about referring to the documentation when using the old binding way.
