### ISSUE TITLE
nvimtree doesnt update the cwd 

### ISSUE THREAD

**Issue by siduck76** [kyazdani42/nvim-tree.lua#489]
Hi there! I have this issue : 

steps to reproduce it ( as shown in the video ) 

- cd ~/.config/nvim ( so the 1st cwd is this )
- run nvim  
- cd into anyfolder 
- open nvimtree and the it updates the cwd 

Try the same steps again but open nvimtree before doing cd into anyfolder , doesnt matter if cwd is changed , the nvimtree will only show old (~/.config/nvim as cwd and its dirs)

 

https://user-images.githubusercontent.com/59060246/125052643-d1512c80-e0c1-11eb-9609-af0b1a03fc27.mp4

**Comment by gukz** [comment]
Also, can you keep the working directory per tab?

**Comment by siduck76** [comment]
> Also, can you keep the working directory per tab?

tab? whats that . Btw I updated the video , check it and you'll understand the issue better.

**Comment by kyazdani42** [comment]
I think there is an option to make nvim tree update when cwd changes, on my phone right now so cannot give you the exact option but it should be listed in the readme and the docs

**Comment by siduck76** [comment]
> I think there is an option to make nvim tree update when cwd changes, on my phone right now so cannot give you the exact option but it should be listed in the readme and the docs

I have set vim.g.nvim_tree_update_cwd = 1 already :((

**Comment by kyazdani42** [comment]
Hum I'm going to test this on my machine when I have some time

**Comment by kyazdani42** [comment]
hum it works as expected on my machine, are you sure you set the option in the right place ?

**Comment by siduck76** [comment]
> hum it works as expected on my machine, are you sure you set the option in the right place ?

my config : https://github.com/siduck76/NvChad/blob/main/lua/plugins/nvimtree.lua#L27

It works for me only if I do cd before openinv nvimtree ,  like if I open neovim and cd into any folder and then open the nvimtree , it updates but if I open neovim , and open nvimtree before doing cd to any dir then the nvimtree doesnt update :(

**Comment by kyazdani42** [comment]
tried with your config and it still works as expected :/

**Comment by siduck76** [comment]
> tried with your config and it still works as expected :/

nvm it doesnt work if I set it to 1 , works with 0  . Didnt know lua had 1 as false xd

**Comment by kyazdani42** [comment]
what ? it works when setting 1 not when setting 0 :smile:
