### ISSUE TITLE
Broken indent markers for image files

### ISSUE THREAD

**Issue by Akin909** [kyazdani42/nvim-tree.lua#49]
@kyazdani42 looks like the latest commit broke handling of indent markers for image files.

![tree-indent-marker-bug](https://user-images.githubusercontent.com/22454918/85283641-9d3ea580-b485-11ea-8091-5b7b32bcf507.png)

This doesn't seem to have affected other filetypes though so not sure if images are special cased somehow

**Comment by kyazdani42** [comment]
damn these markers ! well it is not only jpg files, i'll fix that

**Comment by kyazdani42** [comment]
perfectly fixed in master :)

**Comment by Akin909** [comment]
Nice that works great thanks for the quick fix :+1: sorry it's become a bit of a hassle

**Comment by kyazdani42** [comment]
haha no worries, i use it now so it's not a hassle. And this kind of bug is fun to resolve, this project is full of algorithmic stuff :)
