### ISSUE TITLE
lua callback error whenever buffer is written

### ISSUE THREAD

**Issue by shadowninja55** [kyazdani42/nvim-tree.lua#490]
whenever i do `:w` i get this error at the bottom of neovim: `Error executing vim.schedule lua callback: /home/mark/.vim/plugged/nvim-tree.lua/lua/nvim-
tree/git.lua:141: malformed pattern (missing ']')`

**Comment by kyazdani42** [comment]
why is there a space between `nvim- tree` ? it should be `nvim-tree`. Also i might need more informations to reproduce like 
1) your os
2) your neovim version
3) your nvim-tree version
4) a minimal sample config ?

**Comment by shadowninja55** [comment]
seems to have been fixed after a reinstall of the plugin and downgrading to neovim 0.5.0.
