### ISSUE TITLE
How i can to close automatic Nvimtree

### ISSUE THREAD

**Issue by Johan-Palacios** [kyazdani42/nvim-tree.lua#491]
How I can to set a code for nvim Tree close automatic ?

**Comment by gegoune** [comment]
Automatic when? If at quit of nvim then there is option listed in README.

**Comment by Johan-Palacios** [comment]
When I open a new file, for example I open Nvimtree and I chose a file, later this I want to nvimtree close automatic

**Comment by gegoune** [comment]
Use: 
```viml
let g:nvim_tree_quit_on_open = 1 "0 by default, closes the tree when you open a file
```

It's in README. :)

**Comment by Johan-Palacios** [comment]
Thank you bro
