### ISSUE TITLE
Error when current directory contains invalid symbolic links

### ISSUE THREAD

**Issue by Frederick888** [kyazdani42/nvim-tree.lua#493]
Noticed a minor issue. When there are any invalid symbolic links, nvim-tree bumps into the following error:

```
Error executing vim.schedule lua callback: ...zhang/.vim/plugged/nvim-tree.lua/lua/nvim-tree/utils.lua:49: attempt to index local 'path' (a nil value)
```

To reproduce this issue, for example:
```sh
mkdir test
cd !$
touch README.md
ln -s ./nonexist ./foo
nvim README.md
```

Thanks for this plugin btw :)

**Comment by sansone931** [comment]
I also noticed this after updating. Changing the current directory with `<C-]>` to one with a broken symlink doesn't refresh the tree correctly either.

It looks like this commit introduces the problem: db9e70fde50ae3aa3b2942d493b5a868b3515211

**Comment by smartding** [comment]
> It looks like this commit introduces the problem: [db9e70f](https://github.com/kyazdani42/nvim-tree.lua/commit/db9e70fde50ae3aa3b2942d493b5a868b3515211)

sorry, didn't check for broken links.
