### ISSUE TITLE
No file content showed when opening folder which is not in current working directory

### ISSUE THREAD

**Issue by ericzzh** [kyazdani42/nvim-tree.lua#495]
nvim: 0.5
nvim-tree: lastest

https://user-images.githubusercontent.com/9389005/124712123-7ab4e880-df31-11eb-8ef6-32fd08fc37a7.mov

**Comment by errx** [comment]
broken by #487

**Comment by ono7** [comment]
I am having the same issue, it appears to work traversing directories forwards, just not backwards.  I thought I forgot to save a file, phew! :)

**Comment by kyazdani42** [comment]
should be fixed in 102c4c2332e
