### ISSUE TITLE
[NvimTree] Wrong configuration for keymaps, refer to the new documentation. Keymaps setup aborted

### ISSUE THREAD

**Issue by qiqiming** [kyazdani42/nvim-tree.lua#498]
nvim version

```
NVIM v0.5.0
Build type: Release
LuaJIT 2.1.0-beta3
```

update plugins using `:PlugUpdate`
I opened the neovim, I saw this prompt
![image](https://user-images.githubusercontent.com/28074433/125075624-720b1080-e0f1-11eb-9a0a-a898d61f23f4.png)

**Comment by gegoune** [comment]
Please consult documentation and amend how you are setting up your mappings. There was a change recently which requires changes to user configuration.
