### ISSUE TITLE
File empty when opening it from Tree higher than cwd

### ISSUE THREAD

**Issue by mlthlschr** [kyazdani42/nvim-tree.lua#503]
Files opened higher than the current cwd are empty. That is:

1. `nvim ~/code`
2. navigate to `~` within tree
3. open arbitrary file within `~` via the tree
4. file is empty

The only setting which could intervene with that is `nvim_tree_update_cwd = 1`, but as I understood this only triggers in case the cwd is changed from other sources than the tree (and the tree is not changing the cwd on navigating the hierarchy upwards).

Additional observation: the tree's split window `pwd` is correct (`~`), however the `pwd` of the empty file is the old one (`~/code`).

**Comment by kyazdani42** [comment]
it's been fixed this morning, please update to latest master.

**Comment by mlthlschr** [comment]
Perfect, thanks for your help and the great plugin :+1:
