### ISSUE TITLE
Variable users can reference to see if tree is open?

### ISSUE THREAD

**Issue by account-sxf** [kyazdani42/nvim-tree.lua#505]
I'd like to take different actions in my config depending on whether the tree is open.
I can create a variable to track this, but it seems like a hack. Is there one I could test for that is created by the plugin? If not this is a feature request :)

The specific behavior I want is that if I have the tree open and I close a tab, it closes the tree, then closes the tab, then reopens the tree. If the tree isn't open it doesn't need to try to reopen the tree. It might just be easier for this to be a feature request in itself.

Thank you for your time. This plugin is great!

**Comment by account-sxf** [comment]
Is that what this is for? `g:nvim_tree_tab_open = 1`

**Comment by kyazdani42** [comment]
sorry i've overlooked this: you can use `require'nvim-tree.view'.win_open()` to check if window is opened

**Comment by kyazdani42** [comment]
edit: use `is_visible` instead of `win_open`. Closing since there are no news.
