### ISSUE TITLE
Can't use "n" to repeat last search in help UI

### ISSUE THREAD

**Issue by erietz** [kyazdani42/nvim-tree.lua#506]
After pressing `g?` and entering the help menu, I tried to search for the pattern "rename" using `/ren`. Then, to get to the next occurrence of "rename" I tried to press `n` which did nothing. However, pressing `N` correctly resulted in moving backwards to the previous occurrence. This seems to be a bug and not the intended functionality.

**Comment by jackieli-tes** [comment]
same in the normal tree view. However I believe `let g:nvim_tree_hijack_cursor = 0` helps

**Comment by kyazdani42** [comment]
partially fixed in latest master, closing because i don't think i can do better than this :)
