### ISSUE TITLE
Few feature requests

### ISSUE THREAD

**Issue by kristijanhusak** [kyazdani42/nvim-tree.lua#51]
Hi,

very nice plugin, works really fast!

I have few feature requests that you might consider:

* Allow selecting files and operating on them (For example, multiple rename)
* DONE in #52: Introduce cut/copy/paste
* DONE IN #56: Add mappings for jumping to previous/next git changed file, something like `vim-gitgutter` does with `]c` and `[c`
* DONE in #53: Allow toggling visibility of ignored files

I'm currently using these features in [defx.nvim](https://github.com/Shougo/defx.nvim), and I'm also author of git and icons plugins for defx.

**Comment by kyazdani42** [comment]
think i can close this

**Comment by MKrbm** [comment]
Is the feature for allowing multiple copy & paste still in progress?

**Comment by alex-courtis** [comment]
> Is the feature for allowing multiple copy & paste still in progress?

That's done. You should be able to see them marked e.g.

2 copied
![20231031_093017](https://github.com/nvim-tree/nvim-tree.lua/assets/1505378/9532d0a3-1395-4a19-bacd-b31a4d02c3e4)

2 more cut
![20231031_093038](https://github.com/nvim-tree/nvim-tree.lua/assets/1505378/8a987239-6317-4573-bcf7-a22c934c6663)
