### ISSUE TITLE
Hide the file path at the top of nvim-tree

### ISSUE THREAD

**Issue by ayushsherpa111** [kyazdani42/nvim-tree.lua#516]
![image](https://user-images.githubusercontent.com/35552818/126028761-e8d47083-4ae3-4c73-9799-f645dd2c13a4.png)
Is there a flag to disable the path that is at the top of the tree?

**Comment by gegoune** [comment]
Maybe you can set `nvim_tree_root_folder_modifier` to an empty string?

**Comment by ayushsherpa111** [comment]
> nvim_tree_root_folder_modifier

i looked though the modifier list but they only mentioned different ways to shorten or display different aspect of the path. setting it empty just left me with an absolute path. :(

**Comment by kyazdani42** [comment]
this is a niche feature that i wont implement because it would break a lot of the code.
what you could do though is just hide the path:
```
hi NvimTreeRootFolder guifg=bg guibg=bg
```
