### ISSUE TITLE
Too slow.

### ISSUE THREAD

**Issue by ghost** [kyazdani42/nvim-tree.lua#518]
I don't known why, this plugin gets slow, especially when i open neovim or quit neovim.

**Comment by dulguuncodes** [comment]
I experience a similar issue, Neovim freezes when I decide to save a file and I happen to have nvim-tree open

**Comment by kyazdani42** [comment]
i do not experience such issues...
could you please provide:
- your neovim version
- nvim-tree version with which the bug appears
- OS and OS version you are using
- terminal, shell and versions of them
- a minimal sample config with which the issue arise ?

**Comment by dulguuncodes** [comment]
The issue was resolved by disabling the git integration as specified by #389

- Neovim Version
```
NVIM v0.5.0
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim/src/neovim-0.5.0/build/config -I/build/neovim/src/neovim-0.5.0/src -I/usr/include -I/build/neovim/src/neovim-0.5.0/build/src/nvim/auto -I/build/neovim/src/neovim-0.5.0/build/include
Compiled by builduser
```

- NvimTree Version: Latest commit
- OS: Arch Linux 5.10.50-1-lts
- Terminal + Shell: Alacritty 0.8.0, Fish 3.3.1
- Minimal configuration (requires packer.nvim)
```lua
-- lua/plugins.lua
local packer = require("packer")

return require("packer").startup(function()
        packer.use 'wbthomason/packer.nvim'
        packer.use 'kyazdani42/nvim-tree.lua'
end)
```
```
-- init.lua
require("plugins")
```

**Comment by mattbailey** [comment]
so, I am also a user of the fish shell, and this plugin is very slow on startup, writing files, and exiting nvim. It's probably an artifact of the fish shell's integration with git.

Once I set my nvim shell to dash, the problem completely resolved itself:

```lua
vim.cmd('set shell=/bin/dash')
```

**Comment by wgxh-cli** [comment]
> so, I am also a user of the fish shell, and this plugin is very slow on startup, writing files, and exiting nvim. It's probably an artifact of the fish shell's integration with git.
> 
> Once I set my nvim shell to dash, the problem completely resolved itself:
> 
> ```lua
> vim.cmd('set shell=/bin/dash')
> ```

Thanks! when i set my shell to zsh or bash, the issue was solved.
But, the issue can't solved by @dulguuncodes 's method.
@dulguuncodes, Have you solved this issue?

**Comment by dulguuncodes** [comment]
both my method and mattbailey's method worked for me

**Comment by kyazdani42** [comment]
yes i've noted that the fish shell gets quite slow with nvim tree.
if somebody could share his fish config I'd be happy to do some debugging.
I also noticed that my neovim is getting slower with a lot of git changes in a big repo, I'm pretty sure I can improve the performance if I do a bit of a refactoring of the git module so it's done in a job instead of in a `system` call which is synchronous and blocking.

**Comment by AlfredEVOL** [comment]
my config.fish is just some aliases and nvim tree still causes a block when i write a file (usually for a few seconds) but it works fine when my shell is bash.

**Comment by kyazdani42** [comment]
closing this in favor of #549
