### ISSUE TITLE
Make tagged releases

### ISSUE THREAD

**Issue by ljmf00** [kyazdani42/nvim-tree.lua#520]
The idea would be to add version tags using SemVer or similar to prevent breaking changes and encourage people to use version tags and therefore have reproducible plugin installations. Without tagging releases, people tend to use the latest master version and an introduced bug can break some vim distributions or users configs.

I would recommend looking at Semantic Versioning 2.0.0 specification [here](https://semver.org/).

**Comment by kyazdani42** [comment]
This is a very good idea. I should definitely use git tags now there are so many people using this.

**Comment by kyazdani42** [comment]
started adding tags in dc630d199a0ad593, i'll follow the specs for master releases for now on :)
