### ISSUE TITLE
Add NvimTreeIgnore functionality to toggle ignored files

### ISSUE THREAD

**Issue by ljmf00** [kyazdani42/nvim-tree.lua#521]
See NERDTree functionality for comparison https://github.com/preservim/nerdtree/blob/81f3eaba295b3fceb2d032db57e5eae99ae480f8/plugin/NERD_tree.vim#L40 .

**Comment by kyazdani42** [comment]
not sure what this is about ? this feature already exists

**Comment by kyazdani42** [comment]
if you want to map it by hand:
`lua require'nvim-tree.lib'.toggle_ignored()`
or with the default mapping `I`
