### ISSUE TITLE
[BUG] Focus/Unfocus from nvim tree without closing the nvim tree

### ISSUE THREAD

**Issue by Akianonymus** [kyazdani42/nvim-tree.lua#522]
Open nvim tree

Bug1: Now to unfocus from nvim tree and focus on another buffer, we have to close it

and without closing it, focusing on another buffer is only possible using mouse

Now nvim tree is opened but not focused

Bug2: How to focus back on nvim tree without closing it and open it again

**Comment by ramezgerges** [comment]
Try using window commands (:h window-move-cursor). The default window movement mappings are <c-w> h/j/k/l. For example, if your nvim-tree on the left is focused, doing <c-w>l will focus on the window to its right.

**Comment by kyazdani42** [comment]
did you read neovim's documentation ? some readings of `:help` might be needed :)

**Comment by Akianonymus** [comment]
@kyazdani42 My bad, i am pretty new to vim in general, didn't even tried to search in docs.

Thx
