### ISSUE TITLE
tree opens file as directory sometimes 

### ISSUE THREAD

**Issue by dunkeln** [kyazdani42/nvim-tree.lua#525]
on pressing 'o' or 'Enter' key the tree creates a "NEW DIRECTORY" in the name of the file as a blank buffer . 
![Screenshot 2021-07-20 at 3 49 09 PM](https://user-images.githubusercontent.com/46231179/126327060-18cc5985-5ac1-4fd8-a1e3-cbf86e9949eb.png)

**Comment by kyazdani42** [comment]
does this still happen ? I have never seen this before i must say

**Comment by dunkeln** [comment]
not anymore.I'll close the issue
