### ISSUE TITLE
auto_open not working

### ISSUE THREAD

**Issue by roychoo** [kyazdani42/nvim-tree.lua#526]
Hi, i tried enabled by setting
```g:nvim_tree_auto_open = 1``` 
but it is not working when i do ```nvim ./```, as i am new to lua, not sure how to debug this

**Comment by kyazdani42** [comment]
works for me, does this still happen ?

**Comment by kyazdani42** [comment]
closing this, old and auto_open in setup works just fine and has been greatly extended.
