### ISSUE TITLE
option to load automatically when calling `nvim` on a directory, but not when just `nvim`

### ISSUE THREAD

**Issue by ExpandingMan** [kyazdani42/nvim-tree.lua#528]
It would be nice to have the ability to load `nvim-tree.lua` automatically whenever it is called on a directory e.g. `nvim .` but *NOT* when just doing `nvim` with no arguments.  It seems that currently the options are linked and there is no way to separate them.

The reason this would be useful is because there are some plugins, such as [dashboard](https://github.com/glepnir/dashboard-nvim) which provide useful behavior for `nvim` where the tree isn't that useful, but it's still nice to have it when calling `nvim` on a directory explicitly.

**Comment by afonsocarlos** [comment]
I think this is related to #238 and is being fixed on PR #288 

A workaround to fix your problem for now maybe could be this https://github.com/kyazdani42/nvim-tree.lua/issues/238#issuecomment-800477384

**Comment by ExpandingMan** [comment]
Yes, this has been fixed.  Thanks!
