### ISSUE TITLE
Question: Is it possible to open nvim-tree with vim -c?

### ISSUE THREAD

**Issue by zeitchef** [kyazdani42/nvim-tree.lua#531]
I'm trying to setup an alias that would open a directory and automatically open nvim-tree, but I don't want this to be default behavior. I'm trying to use `vim -c` but it doesn't seem to work. Is this possible?

Options I've tried:

- `vim -c 'NvimTreeOpen'`
- `vim -c 'NvimTreeToggle'`
- `vim -c ':NvimTreeOpen'`
- `vim -c 'nvimtreeopen'`

Anybody doing something similar?

Edit: I've got `nvim` aliased to `vim`

**Comment by kyazdani42** [comment]
I'm going to extend the open feature as this is a request that many people made

**Comment by kyazdani42** [comment]
just tried this again, seems to work with your commands now :)
closing this, if it's not fixed for you, i'll reopen.

**Comment by zeitchef** [comment]
@kyazdani42 Do you mind sharing exactly which command worked for you? Neovim immediately exits for me when running any of the above commands.

**Comment by kyazdani42** [comment]
`vim -c 'NvimTreeOpen'` just works for me.
