### ISSUE TITLE
[Bug] The same file may be displayed twice

### ISSUE THREAD

**Issue by nabezokodaikon** [kyazdani42/nvim-tree.lua#532]
# Problems summary
The same file may be displayed twice.

## Expected
Can't see two of the same files.

## Environment Information (Required!)

 * nvim-tree.lua version(SHA1): d3e76b81e5b169af192dea4da0bd6f64faad2c36

 * OS: Mac

 * Vim/neovim version: NVIM v0.6.0-dev+69-gbebca7bbe

## The reproduce ways from Vim starting (Required!)

 1. Create `aaa` file.
 2. Create `bbb` file.
 3. Rename `aaa` file to `ccc`.
 4. Do `refresh`.

## Screen shot (if possible)
![スクリーンショット 2021-07-27 18 37 34](https://user-images.githubusercontent.com/3197942/127133751-9696e7fe-16e6-4de8-aaad-867e4c684ca1.png)

**Comment by gegoune** [comment]
Please look through existing issues, this has been reported more than once and discussed quite a lot.

**Comment by nabezokodaikon** [comment]
I see.

**Comment by gegoune** [comment]
It might actually be somewhat different as it's not duplicating all the files, just newly created one, is it?

**Comment by kyazdani42** [comment]
I've noticed that sometimes when renaming only. I'll take a look

**Comment by mortezadadgar** [comment]
> I've noticed that sometimes when renaming only. I'll take a look

As a side note I think it's better to automatically refresh nvim-tree after renaming a file or folder

**Comment by kyazdani42** [comment]
should be fixed now

**Comment by kyazdani42** [comment]
Should not happen anymore, since latest refactorings :)
