### ISSUE TITLE
Show folder arrow icons without folder icons

### ISSUE THREAD

**Issue by mastertinner** [kyazdani42/nvim-tree.lua#534]
I would like to have folder arrow icons but not folder icons. However, if I set the following:

```vim
let g:nvim_tree_show_icons = {
    \ 'git': 0,
    \ 'folders': 0,
    \ 'files': 0,
    \ 'folder_arrows': 1,
    \ }
```

Then the folder arrows are not displayed. If I set `folders: 1`, then both the folder icons and the folder arrow icons are shown. Is there any way of making it work with only the `folder_arrows` set to `1`?

**Comment by kyazdani42** [comment]
maybe just replace the folders icons with arrows

**Comment by mastertinner** [comment]
That's what I did as a workaround. Seems like the behavior I described is still a bug, no?

**Comment by kyazdani42** [comment]
dont think so, arrows are a complement to the folder icons, just disable the folder arrows and enable the folder icons and it should work as expected
