### ISSUE TITLE
Which autocommand is triggered when opening a file from nvim-tree?

### ISSUE THREAD

**Issue by sbmueller** [kyazdani42/nvim-tree.lua#536]
Hi,
I noticed that my autocmd for events `BufReadPre` and `FileReadPre` don't fire when opening a file from nvim-tree, only when directly opening a file per command line argument. Which autocmd event can I use for opening a file from nvim-tree?

**Comment by kyazdani42** [comment]
i guess `BufWinEnter` would be more appropriate in this case, because i haven't seen many plugins doing `:read` to read a file actually :)

**Comment by sbmueller** [comment]
Sorry, `BufWinEnter` and `BufEnter` both don't work as well :(.

**Comment by kyazdani42** [comment]
could you show me how you define the autocmd please ?

**Comment by sbmueller** [comment]
Sure:
```
au FilterReadPre,StdinReadPre,BufWritePost,BufReadPre,FileReadPre,BufWinEnter <buffer> lua require('lint').try_lint()
```

**Comment by kyazdani42** [comment]
you should wrap you autocmd in a group to avoid clashing with other commands :) then it should work as expected

**Comment by sbmueller** [comment]
Unfortunately it doesn't yet work forme. Though some debugging revealed the autocmd fires in any case with `BufWinEnter`. Probably an issue of the linter plugin, which shows no output when opening files with nvim-tree. Probably not a bug/issue here.

**Comment by sbmueller** [comment]
sorry closed by accident

**Comment by sbmueller** [comment]
It turns out the issue was the `<buffer>` group used to define the autocommands. It works fine with `*`. Still need to understand better what is going on, but issue resolved for me. Thanks!
