### ISSUE TITLE
Open LuaTree on multiple/all tabs

### ISSUE THREAD

**Issue by b0o** [kyazdani42/nvim-tree.lua#54]
I would love to have the ability to open LuaTree on multiple tabs. 

I use NERDTree with the [vim-nerdtree-tabs](https://github.com/jistr/vim-nerdtree-tabs) plugin, which basically makes the tree behave like a panel as found in apps like VSCode or Atom. 

This seems to be somewhat controversial (see [NERDTree#faq](https://github.com/preservim/nerdtree#can-i-have-the-nerdtree-on-every-tab-automatically)) but it best fits the way I use vim, and judging by the popularity of the vim-nerdtree-tabs plugin, I am not alone.

I would be happy to work on a PR if this is something amicable to the goals of the project but which you don't want to implement yourself.

P.s. wow, this is an excellent plugin. It is considerably faster than NERDTree. Great job Kiyan!

**Comment by kyazdani42** [comment]
I'd be quite happy with that. 
Maybe as an option so users who don't want this don't have to use it.
It should not be quite hard to implement, we should just redraw the tree buffer on some events like tab change.
If you want to implement this, go for it !
