### ISSUE TITLE
folder or file bookmarks

### ISSUE THREAD

**Issue by Trid-collab** [kyazdani42/nvim-tree.lua#540]
Thank you for this plugin. I like using it. 
Is there an option to Bookmark or Pin a folder or file on the top of the tree structure when nvim-tree is open

**Comment by adelarsq** [comment]
Duplicated from https://github.com/kyazdani42/nvim-tree.lua/issues/509

**Comment by kyazdani42** [comment]
thanks for the kind words but indeed it's a duplicate :) closing in favor of the other one.
