### ISSUE TITLE
How can I use fs.create_file?

### ISSUE THREAD

**Issue by sangdth** [kyazdani42/nvim-tree.lua#541]
Hi,

Currently I want to use the events to automatic create files inside folder. Most of the time I work with react, after making a component folder named `ExampleComponent` I always have to repeat creating `ExampleComponent/ExampleComponent.tsx` , `ExampleComponent/ExampleComponent.spec.tsx` and `ExampleComponent/index.ts`.

After reading the doc, I end up with this rough solution:
```
local events = require('nvim-tree.events')
local fs = require('nvim-tree.fs')
local split = require'helpers'.split

events.on_folder_created(
    function(data)
        local tempTable = split(data.folder_name, '/')
        local component_name = tempTable[#tempTable]

        local viewFilePath = data.folder_name .. component_name .. '.tsx'
        fs.create_file(viewFilePath)

        local testFilePath = data.folder_name .. component_name .. '.spec.tsx'
        fs.create_file(testFilePath)

        local indexFilePath = data.folder_name .. 'index.ts'
        fs.create_file(indexFilePath)
    end
)
```
But the `nvim-tree.fs` actually does not export the `create_file` (or ... does it? I don't know 😢  ), is there any way for me to archive the similar result?

Thank you.

--

Update:
In the mean time I have just copied the `create_file` function from your code base to use, but I would love to know a better way to re-use from the lib instead of copy/paste.

Result 😄 :

https://user-images.githubusercontent.com/1083478/128004936-554fb9be-aea7-4fd9-a527-708a83a71a87.mov

**Comment by jonathannerat** [comment]
plenary.nvim is a collection of functions / modules that has support for files as well. Check plenary.path module there for some ideas

**Comment by kyazdani42** [comment]
i will improve the fs management at some point, it's lacking a proper api
