### ISSUE TITLE
Add option to show/hide/sync tree window on every tab

### ISSUE THREAD

**Issue by kevinkleine** [kyazdani42/nvim-tree.lua#542]
In vim tabs contain windows, while in many non-vim editors tabs are inside a main editor panel with the option to have certain windows open regardless of tab. I find that very useful, especially for a file/project explorer. It might be possible to emulate this behavior, by opening a tree window in every tab and syncing its state. Might be a cool addition. Thank you for the plugin, I love it.

**Comment by kyazdani42** [comment]
i think this is already the case with `g:nvim_tree_tab_open`

**Comment by kyazdani42** [comment]
closing this since no news and option seems to exist already (under setup, open_on_tab)
