### ISSUE TITLE
Opening a tab with `g:nvim_tree_tab_open` set to 1 focuses the tree instead of the opened file

### ISSUE THREAD

**Issue by marene** [kyazdani42/nvim-tree.lua#544]
Hi!

First of all, thank you for the project, I think it's awesome!

I just started to use it recently and a couple of small things have been slightly bugging me (compared to what I was used to with nerdtree), the most prominent of which being that if I set `g:nvim_tree_tab_open` to always have a tree opened in every tabs I'm using, then every time I open a file in a new tab (be it by hitting `<C-T>` from the tree or simply `:tabnew /some/file`) then the window of the tree will be in focus instead of the one for the file I just opened, forcing me to `C-W` to the file's window.

I was wondering if there was an option (I looked through the documentation but I could very well be mistaken) to change that behaviour?

And if there are not, would that be because this is actually the wanted behaviour for this (and then I'll write something in my `init.vim` to change that), or is it an actual "issue" (and then I'd be willing to learn lua to try and propose a fix)?

Here is the simplified `init.vim` file I'm using to reproduce this issue:
```
call plug#begin(stdpath('data') . '/plugged')

Plug 'kyazdani42/nvim-web-devicons' " for file icons
Plug 'kyazdani42/nvim-tree.lua'

call plug#end()

let g:nvim_tree_auto_open = 1 "0 by default, opens the tree when typing `vim $DIR` or `vim`
let g:nvim_tree_auto_close = 1 "0 by default, closes the tree when it's the last window
let g:nvim_tree_tab_open = 1 "0 by default, will open the tree when entering a new tab and the tree was previously open
```

Again, thanks a lot for the plugin!

**Comment by marene** [comment]
Following this, I allowed myself to propose a PR: https://github.com/kyazdani42/nvim-tree.lua/pull/545 
It fixed it for me, maybe other people might find it useful 🙂

**Comment by kyazdani42** [comment]
should we close that then ?

**Comment by marene** [comment]
I was waiting to know what you thought of it, but now that the PR's been merged, yup, I'll go ahead and close it, thanks! 🙂
