### ISSUE TITLE
Reveal current file in nvim-tree

### ISSUE THREAD

**Issue by Hubro** [kyazdani42/nvim-tree.lua#546]
One thing I miss from VSCode is the ability to reveal the current file in the file tree. I mostly browse files using FZF, so when I open nvim-tree to do some file operations, the file I'm currently editing isn't focused. Very probably I have to open several nested folders to find it. In VSCode, just pressing "Reveal in Side Bar" saved me a lot of time:

![image](https://user-images.githubusercontent.com/597206/128514385-28ef44e8-0615-4c22-ae66-c71902f8aae9.png)

Is something similar possible in nvim-tree.lua?

**Comment by kyazdani42** [comment]
`:NvimTreeFindFile` ?

**Comment by Hubro** [comment]
> `:NvimTreeFindFile` ?

That's it! :grin: 

Is it not documented anywhere? I was unable to find it.

**Comment by kyazdani42** [comment]
`:help NvimTreeFindFile`

**Comment by Hubro** [comment]
Right, I meant for people who don't already know the command exists though... :smile:
