### ISSUE TITLE
Q: Is vim.g.nvim_tree_auto_close must be loaded before nvim-tree.lua?

### ISSUE THREAD

**Issue by cathaysia** [kyazdani42/nvim-tree.lua#547]
I using nvim-tree with packer, my dir structure like this:

```
.
├── init.lua
├── lua
│   ├── plugins
│   │   ├── init.lua
│   │   ├── nvimtree.lua
```

I load nvim_tree by:

```lua
    use {'kyazdani42/nvim-tree.lua',
        cmd = "NvimTreeToggle",
        config = function()
            require "plugins.nvimtree"
        end
    }
```

But if I put `vim.g.nvim_tree_auto_close=1` in plugins.nvimtree, it does't work. It works just when I put it before plugin.init:

```lua
vim.g.nvim_tree_auto_close=1
require "plugins"
```

How can I put it into `plugins.nvimtree` ? It's more beautiful than put that in init.lua

**Comment by kyazdani42** [comment]
i'm going to take on a rewrite of some module in the tree, specially the setup part to allow for easy lazy loading. For now, keep it this way because the tree initializes when nvim starts thus your auto_close option not working when set after.
