### ISSUE TITLE
Not loading on startup?

### ISSUE THREAD

**Issue by 9ebd7134** [kyazdani42/nvim-tree.lua#548]
My config.vim
```
call plug#begin()
[plugins]
 Plug 'kyazdani42/nvim-tree.lua'
  " Start page
  Plug 'mhinz/vim-startify'
call plug#end()
```

I only found start page to be the issue mentioned in the README.md. 
I need to :NvimTreeToggle or :NvimTreeStart when starting neoivm for it to show nvim tree. 
Is there a way for it to load on startup?

**Comment by kyazdani42** [comment]
`let g:nvim_tree_auto_open = 1`
