### ISSUE TITLE
get vim.g.nvim_tree_auto_open

### ISSUE THREAD

**Issue by aspeddro** [kyazdani42/nvim-tree.lua#550]
How can I get the value of `vim.g.nvim_tree_auto_open`  in neovim startup? 

```
:lua print(vim.g.nvim_tree_auto_open)
```
return 1

but
```lua
--init.lua
if vim.g.nvim_tree_auto_open == 1 then

end
```
return nil

**Comment by kyazdani42** [comment]
can you link your configuration? seems like you define it after the check

**Comment by aspeddro** [comment]
It was defined after. Fixed.
