### ISSUE TITLE
When deleting files too fast, the tree doesn't update

### ISSUE THREAD

**Issue by Hubro** [kyazdani42/nvim-tree.lua#552]
When I want to delete multiple files I press `d`, then `y` to confirm. If I do this twice in a row relatively fast (`dydy`) then nvim-tree won't update after the second deletion, and the second deleted file will still be displayed. If I try to delete this file, an error pops up saying "Could not remove <filename>".

This means that it's not possible to delete a few files quick by typing `dydydydy`, since I get stuck on an error message after the second deletion. I have to refresh (`R`) or manually move down to the next file.

To avoid this issue, I have to wait 1-2 full seconds between each deletion.

**Comment by kyazdani42** [comment]
it might be related to the asynchronous callback for deleting buffers. I'll check this out.

**Comment by kyazdani42** [comment]
should be fixed in 1.1.2 (d705feda5ac5d)

**Comment by Hubro** [comment]
Confirmed, works great now! :grin:
