### ISSUE TITLE
Display git status in signcolumn

### ISSUE THREAD

**Issue by mrossinek** [kyazdani42/nvim-tree.lua#553]
As I understand things right now, you leverage the signcolumn to display the lsp diagnostic status for files with potential issues.
While I like the idea of that, I'd rather use the signcolumn to display the git status information (thereby also preventing things like #72). Is that something you have thought about or would be willing to implement?

An additional cherry on top would be to have a configuraiton option whether git status signs are placed:
* to the right of file/folder names
* to the left of file/folder names
* in the sign column

Maybe you could leverage the same implementation to make the lsp diagnostic symbol location configurable in the same way? :thinking:

**Comment by kyazdani42** [comment]
Good idea I guess, but it would add quite a lot of code and I'm currently doing a big rewrite of the codebase so we will do that after :)

**Comment by sethen** [comment]
I second that it would be rad if we could pick where the git status icons go... Personally I would like them to the right of the directory

**Comment by kyazdani42** [comment]
it has been asked many times, the renderer needs a bit of a rewrite because it's quite messy as it is.

**Comment by alex-courtis** [comment]
I like the sign column idea.

**Comment by kyazdani42** [comment]
yes, that's why the renderer needs a big rewrite :smile:
