### ISSUE TITLE
Preview in a floating window

### ISSUE THREAD

**Issue by Hubro** [kyazdani42/nvim-tree.lua#554]
Currently, pressing `<Tab>` to preview a file will hijack an existing window. This is not a great user experience, since every time the user previews a file they have to pick a window, which adds an extra key press, and the user has to manually restore the original file to the window afterwards.

Since Neovim and Vim 8.2+ supports floating windows, why not make use of this here? :smile: 

On `<Tab>` press, a floating window could appear right next to the tree window with the preview contents. When nvim-tree loses focus, the preview window should close.

Bonuses:
- Single key press to preview a file
- No windows are hijacked
- Consistent experience no matter the amount of windows currently open

**Comment by kyazdani42** [comment]
Good idea, but I'd like to freeze new features for the meantime because I'm doing a big rewrite of the codebase to make it easier to extend !

**Comment by alex-courtis** [comment]
Tracking in #135
