### ISSUE TITLE
Add support for lua configuration

### ISSUE THREAD

**Issue by FedericoAntoniazzi** [kyazdani42/nvim-tree.lua#557]
Lot's of lua plugins can be configured using lua as well as vimscript.

## Expected behaviour
Current configuration supports only vim syntax so configuring it using lua would be:
```vim
vim.g.nvim_tree_side = "left"
vim.g.nvim_tree_width = 30
```
Stating to others plugins, a lua configuration would look like:
```lua
require'nvim-tree'.setup {
  nvim_tree_side = 'left';
  nvim_tree_width = 60;
}
```

**Comment by gegoune** [comment]
I believe @kyazdani42 is working on that at the moment.
As a sidenote, dont think nvim_tree prefixes are necessary for table's keys. Also Would be nice if those keys were more nested, grouped together semantically.

**Comment by FedericoAntoniazzi** [comment]
@gegoune Good point! Thank you for answering

**Comment by kyazdani42** [comment]
indeed i'm working on it, it will take some time because i'm reorganizing a lot of code too, and some surprises :smile:. Maybe in two weeks i'll have a full fledged testable version that i'll release under a dev branch, i will start tagging master with this one because it'll have a LOT of breaking changes.

**Comment by xiyaowong** [comment]
For now, you can customize a setup function just like this

```lua
local function setup(opts)
  for opt, value in pairs(opts) do
    if type(value) == 'boolean' then
      value = value and 1 or 0
    end
    vim.g['nvim_tree_' .. opt] = value
  end
end

setup {
  width_allow_resize = true,
  follow = true,
  highlight_opened_files = true,
  auto_resize = true,
  hide_dotfiles = false,
  indent_markers = true,
  ignore = { '.git', 'node_modules', '.cache', '__pycache__' },
  disable_window_picker = true,
}
```
It looks a little bit more convenient

**Comment by kyazdani42** [comment]
closing since this is almost finished (missing the renderer configuration, which will be done alongside refactoring the renderer).
