### ISSUE TITLE
vim-fugitive's :GBrowse not available anymore due to netrw being removed by this plugin

### ISSUE THREAD

**Issue by alexander-born** [kyazdani42/nvim-tree.lua#559]
As the title states vim-fugitive's `:GBrowse` is not working anymore when using this plugin.

Error message:
```
Netrw not found. Define your own :Browse to use :GBrowse
```

**Comment by alexander-born** [comment]
Sorry should have read the documentation more.
```viml
let g:nvim_tree_disable_netrw = 0 "1 by default, disables netrw
```

**Comment by nulty** [comment]
You can also follow the directions given by `vim-fugitive` and define the command. I've done this:

```vim
command -nargs=1 Browse silent exe '!xdg-open ' . "<args>"
```

So you can disable `netrw` and still have `GBrowse` work.

[vim-fugitive GBrowse customisation code](https://github.com/tpope/vim-fugitive/blob/v3.4/autoload/fugitive.vim#L6995-L7021)
