### ISSUE TITLE
Feature request: possibility to add custom icons to selected file types

### ISSUE THREAD

**Issue by FBorowiec** [kyazdani42/nvim-tree.lua#565]
First of all let me tell I was very glad to switch from NERDtree to nvim-tree, I think nvim-tree looks and 'feel' more slick! Thanks :)

The only thing I couldn't figure out is how to add custom icons to selected file types?

**Comment by FBorowiec** [comment]
Digging a little bit I think I misunderstood where does the actual link between icons and file types actually is set - nerdfonts in my case. So I guess that's where I should look set my icons

**Comment by kyazdani42** [comment]
Hi @FBorowiec, i don't think nerdfonts are the place you want to update your icon config :) maybe something like overriding icons in `nvim-web-devicons` or by setting the icons you need in the setup of nvim-tree ? or maybe i did not understand your question well. Hope you've find what you were looking for
