### ISSUE TITLE
[Feature Request] Setting/s to "auto over-jump" directories with just one child directory.

### ISSUE THREAD

**Issue by dzintars** [kyazdani42/nvim-tree.lua#566]
Hi. Thank you for your huge effort! Nice plugin.
NVim Lua integration opens a lot of new opportunities for making something better than we had before. :)

![image](https://user-images.githubusercontent.com/547420/129494822-eb11f895-065d-4be3-bc77-3bf0aa6e7a2d.png)
Imagine such structure.
To get to the `constants.ts` file with the regular navigation i should make a few more key strokes.
It would be nice to introduce setting/s which allows to "auto over-jump" empty directories and to show them in tree like 
```bash
├── packages
│   ├── app-modules/src/lib
│         └── constants.ts
```
I could be wrong but i think i saw similar behavior in VS Code and definitely in NERDTree (which is where i come from). While at first glance it could feel weird, but i think many NERDTree users would be happy for that. :)

**Comment by gegoune** [comment]
Try setting `nvim_tree_group_empty`.

**Comment by dzintars** [comment]
D'a heck..! i was literally reading every single setting... how could i miss that!? :)
