### ISSUE TITLE
Do not remount at `:pwd` when opening a file from outside the current scope

### ISSUE THREAD

**Issue by Gelio** [kyazdani42/nvim-tree.lua#568]
Hey :smile: 

I've been using nvim-tree for some time and I'm loving it! I do have one problem that would improve my workflow if it was solved.

I would suggest removing nvim-tree's behavior to reroot at `:pwd` after doing `<C-]>` and then opening a file from outside the directory that is currently used as nvim-tree's root.

For example:
1. Open nvim tree. `:pwd` is `a/`
2. Do `<C-]>` on `a/b/`
3. nvim-tree is rooted at `a/b/`
4. Open `a/c/file.ts`
5. nvim-tree keeps being rooted at `a/b/` (do **not** go back to being rooted at `a/`)

## Video

https://user-images.githubusercontent.com/889383/130327024-b62f152f-f8bb-481a-91ba-b3e5a0a2b0e1.mp4

After `C-]` in nvim-tree and opening the top buffer (which is visible in nvim-tree), all is well. However, after entering the bottom buffer which comes from some parent directory, nvim-tree goes back to `:pwd`. I don't want it to jump, I want it to stay where it is

## Rationale

Working with a deep directory structure I often want to work on some branch of that directory tree. However, often I need to reference a file from a different part of the project, which I open in a split. This automatically changes nvim-tree to be rooted at the previous `:pwd` and I have to do `<C-]>` each time I enter this buffer from another part of the project, which is annoying

**Comment by ivankovnatsky** [comment]
coming from nerdtree, also find this rather confusing, i would want the file opened to be in the same pwd as the entered nvim-tree buffer.

**Comment by kyazdani42** [comment]
could you work out something with `:help nvim_tree_update_cwd` or `:help nvim_tree_respect_buf_cwd` ?

**Comment by Gelio** [comment]
Unfortunately, these do not address my problem, but may be related to @ivankovnatsky's one.

To better illustrate what I have in mind, I've updated the issue with a video, maybe that helps

**Comment by ExtinctAxolotl** [comment]
I have the same issue with `nvim_tree_update_cwd` and `nvim_tree_respect_buf_cwd` set to `1`.
