### ISSUE TITLE
Keybinds not working

### ISSUE THREAD

**Issue by sethen** [kyazdani42/nvim-tree.lua#569]
Love the plugin but I can't seem to get keybinds working.  Here is my config:

```
local g = vim.g
local tree_cb = require'nvim-tree.config'.nvim_tree_callback

g.nvim_tree_indent_markers = 1
g.nvim_tree_add_trailing = 0
g.nvim_tree_bindings = {
	{ key = {"t"}, cb = tree_cb(":NvimTreeToggle") },
}
```

I want the tree to toggle when I press the `t` key, but for some reason this doesn't seem to work.  What am I missing here?

**Comment by kyazdani42** [comment]
these are the bindings inside the tree, i think you should map these yourself `:nnoremap <silent> t :NvimTreeToggle<cr>`
