### ISSUE TITLE
[Bug] Cannot open tree after opening file from single window tree

### ISSUE THREAD

**Issue by kristijanhusak** [kyazdani42/nvim-tree.lua#57]
I'm not sure if title is descriptive enough, but i'll give steps to reproduce.
Basically, when nvim-tree is last window, and you open file from it, later it errors out:

Steps:

* Open up neovim
* do `:LuaTreeOpen`
* close the other empty window that's on the right, this leaves only nvim-tree
* Find some file, open it
* Try `:LuaTreeToggle` or `:LuaTreeOpen`. Toggle throws error, open silently fails.

I guess there are 2 available fixes:

1. Always open a window in case when nvim-tree is only window available
2. Properly handle nvim-tree state after opening a file so it can be opened again

**Comment by kyazdani42** [comment]
mmh well that's unfortunate.
I have to refactor the window managing code because it has some issues.

**Comment by kristijanhusak** [comment]
Works now, thanks!

**Comment by kristijanhusak** [comment]
I found one bug with it. Looks like it overrides some things globally, for example `set number`. Here are steps to reproduce.

* Make sure you have `set number` in your init.vim
* Open up neovim
* do `:LuaTreeOpen`
* close the other empty window that's on the right, this leaves only nvim-tree
* Find some file, open it
* do `:LuaTreeOpen`, find some other file and open it in vertical split
* The new split window doesn't have numbers, but it should

**Comment by kyazdani42** [comment]
well ill try to fix this when im back from my holidays. Basically opening a file should always open to a new window, avoiding this kind of side effects.
