### ISSUE TITLE
Tabnew (Ctrl-t) window inherits options from NvimTree buffer

### ISSUE THREAD

**Issue by dcordb** [kyazdani42/nvim-tree.lua#570]
Thanks for this project.

If we go to NvimTree buffer and open a file on a new tab (with Ctrl-t), and then open a popup window, for example an FZF or Telescope popup, all windows opened after this will inherit the options of the NvimTree buffer, which is not right.

I think this is related to https://github.com/kyazdani42/nvim-tree.lua/pull/386.

**Comment by kyazdani42** [comment]
I'm not sure how nvim-tree settings could affect this as every option is set locally with `setlocal`, which should not affect the other windows... Could you specify some settings that get overriden so i can reproduce this consistently ?

**Comment by dcordb** [comment]
@kyazdani42 here are detailed steps to reproduce this:

1. Get the following gist on a folder on your machine: https://gist.github.com/dcordb/b976842b412825d37c0e80f62166d5bf
2. Go to that folder and execute `nvim -u init.vim`.
3. Inside neovim execute the command `:NvimTreeToggle`.
4. In NvimTree buffer, open the file `one.py` in a new tab (with Ctrl-T), notice here how the tabs and spaces are displayed (because of the `listchars` option).
5. Execute the command `:Telescope find_files` and select the file `two.py`.
6. Notice now that the background of buffer `two.py` is the same as NvimTree buffer, also notice how `listchars` are not displayed.

**Comment by kyazdani42** [comment]
could not reproduce with the steps, listchars is properly displayed in every window :/

**Comment by dcordb** [comment]
Yes it seems that I had an issue in my configuration, recently I changed  bunch of stuff and now I can't reproduce this. So I'll close this.
