### ISSUE TITLE
nvim_tree_side = 'bottom' settings

### ISSUE THREAD

**Issue by genesis-algorithms** [kyazdani42/nvim-tree.lua#573]
Hi, I have a couple of questions hope it's not wrong to ask them here.

1. How can I change the height of nvim-tree when nvim_tree_side is set to 'bottom'?
    I know that we can change the width with nvim_tree_width but it doesn't work when the side is set to 'bottom'.
2. Is it possible to make the nvim-tree panel not push the code upwards?

This is what I mean:

https://user-images.githubusercontent.com/5767281/129970068-2e9d79db-e6f9-4c6c-a022-4a8392c5ef98.mp4

**Comment by kyazdani42** [comment]
completely forgot this option was available. I'll push a fix for this

**Comment by genesis-algorithms** [comment]
@kyazdani42 It's pretty good for vertical monitor setups

**Comment by kyazdani42** [comment]
top/bottom management should be fixed in `1.5.1` (fb32f35d7fd92a7c8c)
