### ISSUE TITLE
Feature Request: Collapse Every Folders at Once

### ISSUE THREAD

**Issue by Jacob87** [kyazdani42/nvim-tree.lua#574]
Hi, first of all I just want to thank you for this awesome project. I can't work without it now 😄, but it would be very nice to have an option to collapse all folders at once with one key press. 

Maybe it's because I came from VSCode but this feature can be very useful when you start navigating in a big project, especially when you don't want to manually collapse each folder every time.

**Comment by kyazdani42** [comment]
You could hack a solution on your end, i don't think it would be too difficult :) or make a PR if you wish, also might be interesting to do a full collapse toggle function that would either close all directories or open all directories already explored.

**Comment by imreverse** [comment]
@Jacob87 in case you're still looking for the solution, [here](https://github.com/kyazdani42/nvim-tree.lua/issues/435) @kyazdani42 mentioned:
> there is a `require'nvim-tree.lib'.collapse_all()` function to collapse the whole tree already :)

**Comment by Jacob87** [comment]
omg I did not even notice it has been released, thank you so much guys!
