### ISSUE TITLE
I see this error every time I toggle a folder open or close

### ISSUE THREAD

**Issue by BooleanCube** [kyazdani42/nvim-tree.lua#576]
![image](https://user-images.githubusercontent.com/47650058/130067287-2854a251-4676-48d5-a297-e32d102e0d7d.png)

I am not sure what is the cause of this and im not fluent in lua either.

**Comment by kyazdani42** [comment]
looks like you nvim is out of date, what is the output of your `nvim --version` ?

**Comment by BooleanCube** [comment]
> looks like you nvim is out of date, what is the output of your `nvim --version` ?

My neovim version is 0.5.0
![image](https://user-images.githubusercontent.com/47650058/130338173-c5a845fa-0b31-411b-bff1-0a171a82ab8a.png)

**Comment by kyazdani42** [comment]
i think your version might be out of date for quite a while, what does `:help sign_unplacelist` returns ?

**Comment by BooleanCube** [comment]
I believe in the README.md the version 0.5 is up to date but just barely maybe thats been updated? other than this error(thats really annoying), NvimTree works just fine? So, you might want to update the README.md as well. Do you suggest I use a more updated version of nvim now?

![image](https://user-images.githubusercontent.com/47650058/131217186-33bf389b-9567-461d-8c0e-f99137202c33.png)


When I try `:help sign_unplacelist` I get this back:

![image](https://user-images.githubusercontent.com/47650058/131217173-d9598110-17c4-4c6c-99d9-9b023b982d37.png)

**Comment by kyazdani42** [comment]
seems like you are running an old development version of neovim 0.5, neovim 0.5 release works just fine for me

**Comment by kyazdani42** [comment]
closing this because it's unrelated to nvim-tree, please install a correct version of neovim :)
