### ISSUE TITLE
Feature request: Execute file under cursor

### ISSUE THREAD

**Issue by adelarsq** [kyazdani42/nvim-tree.lua#579]
First of all really thanks for this plugin 👏🏻. I am using it instead of NERDTree and I'm really liking. I have added support on my plugins for it and I'm already using daily ([neoline.vim](https://github.com/adelarsq/neoline.vim) and [vim-emoji-icon-theme](https://github.com/adelarsq/vim-emoji-icon-theme)).

Would be possible a feature to execute the file under the cursor? This trick can help a lot sometimes.

**Comment by kyazdani42** [comment]
hi @adelarsq, what do you mean by `executing the file` ? If it's something that you would like to implement, you could just make a function that gets `local node_absolute_path = require'nvim-tree.lib'.get_node_at_cursor().absolute_path` and do whatever you like with it :)

**Comment by adelarsq** [comment]
Nice! I think that will be possible with this.

**Comment by adelarsq** [comment]
This `get_node_at_cursor()` did provide even more data to work around. Thanks a lot. 
I will close the request.
