### ISSUE TITLE
LuaTreeFindFile doesn't automatically open tree

### ISSUE THREAD

**Issue by kristijanhusak** [kyazdani42/nvim-tree.lua#58]
For example, in NerdTree, running NerdTreeFindFile also opens the tree if it's not already opened. Here we need tree to be opened in order to execute the find. Is that on purpose ?

**Comment by kyazdani42** [comment]
Not really, i just didn't really think about it. I'll change that

**Comment by kristijanhusak** [comment]
Looks good.
There's small difference in behavior when the is opened or not.
When the tree is not opened, it opens it, finds the file, and focuses the tree.
When tree is opened, it finds the file, but it doesn't focus the tree.

Not really a big deal, just wanted to point that out.

**Comment by kyazdani42** [comment]
well ill fix this too, i didnt notice it.
thanks for the feedbacks though, its really helpful :)

**Comment by kyazdani42** [comment]
well ill fix this too, i didnt notice it.
thanks for the feedbacks though, its really helpful :)
