### ISSUE TITLE
Change filename color based on Git status

### ISSUE THREAD

**Issue by itscarlosecp** [kyazdani42/nvim-tree.lua#580]
I was wondering if there's an option to highlight the file or folder name based on git status. I found a few highlight groups for this but they are only applied to the git icons. Example below:

Current config:
![image](https://user-images.githubusercontent.com/47466248/130149093-2f701397-a628-45d9-b240-5652321dc04d.png)
I changed these file names by modified the following highlight groups: `NvimTreeGitDeleted`, `NvimTreeGitIgnored`, `NvimTreeGitDirty`, `NvimTreeGitRenamed`, `NvimTreeGitMerge`, `NvimTreeGitNew` and `NvimTreeGitStaged`. 

My goal is to achieve something similar to the default VSCode highlighting, were to full filename is highlighted:
![image](https://user-images.githubusercontent.com/47466248/130149366-4f05a0d5-37a2-44ee-98fe-0dccac491b92.png)

**Comment by kyazdani42** [comment]
could this be achieved with `:help nvim_tree_git_hl` ? I'm thinking about reworking the git implementation at some point to provide more flexibility on colors / icons, but it's not going to be soon :)
