### ISSUE TITLE
Cannot delete symlinks that points to directories

### ISSUE THREAD

**Issue by figsoda** [kyazdani42/nvim-tree.lua#581]
**To reproduce**:

```ShellSession
$ mkdir a
$ ln -s a b
```
press `d` on `b` in nvim tree 

**Expected behavior**: same as `rm b`

**Comment by kyazdani42** [comment]
the fs implementation has some flaws, i'll fix them alltogether after the setup refactoring is done

**Comment by kyazdani42** [comment]
should be fixed in `1.1.3` (79b968217ebd03)
