### ISSUE TITLE
Scrolling through tree only highlights single character

### ISSUE THREAD

**Issue by AshleighWilson** [kyazdani42/nvim-tree.lua#582]
Hi,

I really like this plugin but I have a question. On some of the screenshot, the whole filename and icon is highlighted as you scroll through the tree. However, on my configuration only a single character is highlighted (first character of filename by default). How can I get it to highlight the whole filename? Thanks.

**Comment by kyazdani42** [comment]
not sure what you mean ? `:help CursorLine` maybe ?

**Comment by AshleighWilson** [comment]
Hi, great thanks that has sorted it. I thought it was configuration in the plugin.
