### ISSUE TITLE
No icons displaying on tree

### ISSUE THREAD

**Issue by kaykhan** [kyazdani42/nvim-tree.lua#584]
Hi just installed this plugin and there are no icons on the tree, it does not look like the screenshots.

![image](https://user-images.githubusercontent.com/5202527/130355341-b638af95-a761-47e1-bd9f-f78aa0a61ff3.png)

**Comment by rodamaral** [comment]
Same issue for me. The icons used to appear, but some recent commit broke it.

**Comment by kaykhan** [comment]
@rodamaral did you happen to get this working?

**Comment by ahmedkhalf** [comment]
Are you using lunarvim? (We recently change the config of nvim tree on rolling branch, and I wanna see if related.

**Comment by kaykhan** [comment]
@ahmedkhalf No im not im using neovim

```
NVIM v0.6.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-vNq1vt/neovim-0.6.0~ubuntu1+git202108211152-50b30de20-adeb5640f=. -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim-vNq1vt/neovim-0.6.0~ubuntu1+git202108211152-50b30de20-adeb5640f/build/config -I/build/neovim-vNq1vt/neovim-0.6.0~ubuntu1+git202108211152-50b30de20-adeb5640f/src -I/build/neovim-vNq1vt/neovim-0.6.0~ubuntu1+git202108211152-50b30de20-adeb5640f/.deps/usr/include -I/usr/include -I/build/neovim-vNq1vt/neovim-0.6.0~ubuntu1+git202108211152-50b30de20-adeb5640f/build/src/nvim/auto -I/build/neovim-vNq1vt/neovim-0.6.0~ubuntu1+git202108211152-50b30de20-adeb5640f/build/include
Compiled by buildd@lgw01-amd64-052
```

**Comment by ahmedkhalf** [comment]
Oh okay glad its not an lvim problem, you could perhaps look at the way we configure nvim tree in lvim and see if toggling a setting fixes it for you.

**Comment by kaykhan** [comment]
Created a new config and tried it but still did not work

**Comment by kaykhan** [comment]
I think i found out what it was, dont use these default configurations in the readme.https://github.com/kyazdani42/nvim-tree.lua#setup there is something preventing the icons from loading

**Comment by rodamaral** [comment]
> @rodamaral did you happen to get this working?

My problem was actually due to packer. Nvm

**Comment by skelegorg** [comment]
on iterm2 on macos, try setting "use different font for non-ascii text" to true and selecting the standalone nerd fonts icon font if you don't have a patched font.
