### ISSUE TITLE
Cannot open a file in a new tab if current buffer is not written

### ISSUE THREAD

**Issue by Alan-Kuan** [kyazdani42/nvim-tree.lua#585]
Whenever I want to open a file in a new tab while current buffer is not saved, an error occurs that tells "E5108: Error executing lua ...site/pack/packer/opt/nvim-tree.lua/lua/nvim-tree/lib.lua:425: Vim(edit):E37: No write since last change (add ! to ove
rride)"

Looks like this is caused by this line in lib.lua.
```lua
vim.cmd("edit " .. vim.fn.fnameescape(filename))
```

Besides, I bind 't' to open a file in a new tab instead of the default '\<C-t\>'.

**Comment by kyazdani42** [comment]
isn't this default behavior with nvim ? What happens if you try to `:tabe filename` while current buffer is not saved ?

**Comment by Alan-Kuan** [comment]
I tested it (`:tabe filename` while current buffer is not saved), and I was able to open a file in a new tab successfully.

Actually, I expect to open a file in a new tab with nvim-tree's function, however, it failed when my current file was not saved due to the `edit` command in the function.

**Comment by Alan-Kuan** [comment]
I found a work around! Just turn on the `hidden` option of neovim like `vim.o.hidden = true`, and the problem was gone.
