### ISSUE TITLE
Don't Open Nvim-Tree When Accepting Text from a Pipe?

### ISSUE THREAD

**Issue by FOSSilizedDaemon** [kyazdani42/nvim-tree.lua#587]
Hello,

I am using `nvim-tree` as a replacement for `netrw` and am loving it. The only issue I have found is when I pipe text into `nvim`. I have `nvim-tree` configured to automatically open when I run
```
nvim DIR
```
as per the settings page. This normally is awesome, and I wanted to actually ask if you guys planned to add a fullscreen option for when you run `nvim` like this so it isn't a bunch of empty space, but there is one annoyance with using `nvim-tree` like this. I use `nvim` as my diff pager with `git` and sadly now when I run
```
git diff .
```
`nvim-tree` automatically opens. This seems to be because a non-named buffer is used, but I wanted to know if there is any way to have `nvim-tree` not open automatically when I do this or when I pipe text into `nvim`. Essentially, if the created buffer has any text within it then do not open `nvim-tree`. Is this possible?

Thank you for your time.

**Comment by kyazdani42** [comment]
hello, does this issue also happen when using nvim as manpager ? I use delta for git diffs, but nvim for manpages and it does not open the tree while doing that.
your solution could actually work, right now i check if the buffer is unnamed which causes some issues for this kind of thing actually.

**Comment by kyazdani42** [comment]
shold've been addressed in dc630d199a0ad593036d193232c6b338aa0407e3
