### ISSUE TITLE
Double entries when loading session

### ISSUE THREAD

**Issue by ahmedkhalf** [kyazdani42/nvim-tree.lua#590]
Reproduction:

1. Save current session when nvim-tree is **not open**. `:mksession!`
2. Load session using `nvim -S Session.vim`
3. Toggle nvim-tree

Double Entries:
![image](https://user-images.githubusercontent.com/36672196/130917927-4a0d2c01-f097-4abe-98fd-60978c6f4985.png)

**Comment by ahmedkhalf** [comment]
@kyazdani42  With the recent update, I am now getting a new error:

```
E5108: Error executing lua ...e/pack/packer/start/nvim-tree.lua/lua/nvim-tree/view.lua:306: Vim(buffer):E86: Buffer 2 does not exist
```

![image](https://user-images.githubusercontent.com/36672196/131225942-fb846049-905b-458f-8f7b-afc7a55b4f82.png)

**Comment by Iron-E** [comment]
Can confirm. There's no way to get the tree to show back up after this occurs, even if you reload the module

**Comment by kyazdani42** [comment]
should be fixed in 1.1.5 (4cc2abe)

**Comment by ahmedkhalf** [comment]
tnx!!

**Comment by nguyentritai2906** [comment]
Hey @kyazdani42 , 
I don't know if I should open a new issue but I got this error when restore a session with nvim-tree open.

Error when auto-restore session with vim-obsession
![image](https://user-images.githubusercontent.com/56184645/132981957-fe61462b-4756-4703-9636-e18ec3b4a292.png)

The line that caused error 
![image](https://user-images.githubusercontent.com/56184645/132982127-9ac79d1e-63d8-4922-a9a9-fc27758fbdfa.png)
