### ISSUE TITLE
marks capability like netrw 

### ISSUE THREAD

**Issue by TheSafdarAwan** [kyazdani42/nvim-tree.lua#595]
currently netrw has a great feature for adding marks on files. This is a great feature if you are working with multiple projects this feature is not available inside of nvim-tree can you add that capability that would be a great feature. Thanks

Edit: 
eg. if you are in netrw and you press mJ it will add the mark there (NOTE: mj will not work outiside of the netrw capital letters are for the global marks and small letters are for the local files) then if you didn't overide that mark by adding it agin in another place then if you press `m or 'm ( ` is for the exect location of the mark) it will take you where ever you added that mark.

**Comment by kyazdani42** [comment]
Hi, this feature has been asked many times :) sorry for the late answer, i've missed some issues during this summer and haven't got back to them.

**Comment by alex-courtis** [comment]
Please see work in progress #612
