### ISSUE TITLE
NvimTreeTogle broken after after #288

### ISSUE THREAD

**Issue by sdemura** [kyazdani42/nvim-tree.lua#596]
Two problems.
1. Call `:NvimTreeToggle`, and I'm asked if I want to quit neovim. Selecting yes quits neovim.

Expected behavior: nvim-tree should open.

2. Use `:Telescope find_files` to open a file, and then nvim-tree immediately opens to the side.

Expected behavior: nvim-tree should not open automatically after selecting a file with Telescope.

3. Very similar behavior when opening a file with a leader key.
Video demonstrating both above

https://asciinema.org/a/FMfAzFNGLQ0RbRNw7uqCK8KQ8

Relevant configs. (I use default nvim tree settings).
```
nnoremap <silent> <leader>nv :e ~/.dotfiles/init.vim<CR>
nnoremap <silent><leader>o :NvimTreeToggle<CR>
nnoremap <silent><leader>ff :NvimTreeFindFile<CR>
```

**Comment by kyazdani42** [comment]
should be fixed in 445d3fefa57ff `1.1.1`, could you confirm ?

**Comment by uyha** [comment]
Works for me

**Comment by kyazdani42** [comment]
closing this then in the meanwhile, if you find any other issues please report them :)

**Comment by sdemura** [comment]
Thanks @kyazdani42! It's working as expected now :)
