### ISSUE TITLE
Why update_base_dir_with_filepath ??

### ISSUE THREAD

**Issue by ahmedkhalf** [kyazdani42/nvim-tree.lua#598]
With the recent commit, `follow = 1` changes my PWD when I open a `help` file, and I don't like this since I have other rooter plugins that manage my PWD. All I want is the old behavior of my mouse following. If there is an important reason why this annoying feature was introduced please let me know.

**Comment by kyazdani42** [comment]
i understand this can be a little aggressive, i'll hide this behind an option

**Comment by kyazdani42** [comment]
fixed in `1.2.1` (see `g:nvim_tree_follow_update_path`)

**Comment by ahmedkhalf** [comment]
thnx!!!
