### ISSUE TITLE
Error E5108: Vim(buffer):E86: Buffer 2 does not exist

### ISSUE THREAD

**Issue by zeitchef** [kyazdani42/nvim-tree.lua#600]
After the last update, the plugin is reporting the above-mentioned error and open `nvim-tree` simply opens the current buffer in a sidebar.

<img width="1140" alt="Screen Shot 2021-08-29 at 11 11 40" src="https://user-images.githubusercontent.com/6670659/131245211-33c62f6f-0fa6-45d9-99ad-27ed226558bc.png">

**Comment by Shatur** [comment]
Can confirm. I bisected, the issue was introduced in 3bac5633e1f7e778d0bcb54a2ab612d5fbce1248.

**Comment by sanevillain** [comment]
I can confirm as well as I'm experiencing the same issue after the latest update

**Comment by lcrockett** [comment]
Can confirm too. `NVIM v0.5.0` with `LuaJIT 2.1.0-beta3` on both MacOS Big Sur and Linux Ubuntu 20.04.

**Comment by nepali-prabhat** [comment]
I can confirm too. Experiencing the same issue after latest update.

**Comment by Shatur** [comment]
Please, do not bump the issue without contributing a significant information. Use thumb up.

**Comment by ahmed-rezk-dev** [comment]
I have the issue right now as well. After updating.

**Comment by kyazdani42** [comment]
should be fixed in `1.1.5` (4cc2abe3e238d282)
