### ISSUE TITLE
double click doing visual selecting only

### ISSUE THREAD

**Issue by menash134** [kyazdani42/nvim-tree.lua#601]
Hi, today I updated the nvim-tree plug. I use tabby, putty, kitty terminals in windows to access my linux machine (ssh).
whenever i do double click then it is not opening the folder rather it is just visually selecting and changing the buffer. I switched to nerd-tree and it seems to work perfectly fine. Whenever there double click opens the folder /file.

Any help/yelp?

**Comment by menash134** [comment]
I uninstall the plugin and install again. It worked now. I don't know the problem. But I tried all the terminals like tabby, kitty putty all have the same problem and now its gone. strange. something to be noted .

**Comment by menash134** [comment]
I use nvimfindfile and it is  Happening again.

**Comment by kyazdani42** [comment]
cannot reproduce, can you share you keybinding config ?

**Comment by menash134** [comment]
I figured out that this problem happens after loading a session from "plugin/startify". If I normally start the nvim and nvim-tree is working properly. If I go into the startify session, it messes up my nvim-tree.

below is my session
let SessionLoad = 1                                                                                                                                                                                                                                                                                                                                                 
  2 let s:so_save = &g:so | let s:siso_save = &g:siso | setg so=0 siso=0 | setl so=-1 siso=-1                                                                                                                                                                                                                                                                           
  3 let v:this_session=expand("<sfile>:p")                                                                                                                                                                                                                                                                                                                              
  4 silent only                                                                                                                                                                                                                                                                                                                                                         
  5 silent tabonly                                                                                                                                                                                                                                                                                                                                                      
  6 cd ~/views/adshas0_ax_view_1                                                                                                                                                                                                                                                                                                                                        
  7 if expand('%') == '' && !&modified && line('$') <= 1 && getline(1) == ''                                                                                                                                                                                                                                                                                            
  8   let s:wipebuf = bufnr('%')                                                                                                                                                                                                                                                                                                                                        
  9 endif                                                                                                                                                                                                                                                                                                                                                               
 10 set shortmess=aoO                                                                                                                                                                                                                                                                                                                                                   
 11 badd +0 wlan2/linux-drivers/scalance_dpd/dpd_acl.c                                                                                                                                                                                                                                                                                                                  
 12 argglobal                                                                                                                                                                                                                                                                                                                                                           
 13 %argdel                                                                                                                                                                                                                                                                                                                                                             
 14 edit wlan2/linux-drivers/scalance_dpd/dpd_acl.c                                                                                                                                                                                                                                                                                                                     
 15 argglobal                                                                                                                                                                                                                                                                                                                                                           
 16 setlocal fdm=manual                                                                                                                                                                                                                                                                                                                                                 
 17 setlocal fde=0                                                                                                                                                                                                                                                                                                                                                      
 18 setlocal fmr={{{,}}}                                                                                                                                                                                                                                                                                                                                                
 19 setlocal fdi=#                                                                                                                                                                                                                                                                                                                                                      
 20 setlocal fdl=99                                                                                                                                                                                                                                                                                                                                                     
 21 setlocal fml=1                                                                                                                                                                                                                                                                                                                                                      
 22 setlocal fdn=20                                                                                                                                                                                                                                                                                                                                                     
 23 setlocal fen                                                                                                                                                                                                                                                                                                                                                        
 24 silent! normal! zE                                                                                                                                                                                                                                                                                                                                                  
 25 let &fdl = &fdl                                                                                                                                                                                                                                                                                                                                                     
 26 let s:l = 1 - ((0 * winheight(0) + 36) / 72)                                                                                                                                                                                                                                                                                                                        
 27 if s:l < 1 | let s:l = 1 | endif                                                                                                                                                                                                                                                                                                                                    
 28 keepjumps exe s:l                                                                                                                                                                                                                                                                                                                                                   
 29 normal! zt                                                                                                                                                                                                                                                                                                                                                          
 30 keepjumps 1                                                                                                                                                                                                                                                                                                                                                         
 31 normal! 0                                                                                                                                                                                                                                                                                                                                                           
 32 tabnext 1                                                                                                                                                                                                                                                                                                                                                           
 33 if exists('s:wipebuf') && len(win_findbuf(s:wipebuf)) == 0&& getbufvar(s:wipebuf, '&buftype') isnot# 'terminal'                                                                                                                                                                                                                                                     
 34   silent exe 'bwipe ' . s:wipebuf                                                                                                                                                                                                                                                                                                                                   
 35 endif                                                                                                                                                                                                                                                                                                                                                               
 36 unlet! s:wipebuf                                                                                                                                                                                                                                                                                                                                                    
 37 set winheight=1 winwidth=20 shortmess=filnxtToOFAI                                                                                                                                                                                                                                                                                                                  
 38 let s:sx = expand("<sfile>:p:r")."x.vim"                                                                                                                                                                                                                                                                                                                            
 39 if filereadable(s:sx)                                                                                                                                                                                                                                                                                                                                               
 40   exe "source " . fnameescape(s:sx)                                                                                                                                                                                                                                                                                                                                 
 41 endif                                                                                                                                                                                                                                                                                                                                                               
 42 let &g:so = s:so_save | let &g:siso = s:siso_save                                                                                                                                                                                                                                                                                                                   
 43 set hlsearch                                                                                                                                                                                                                                                                                                                                                        
 44 nohlsearch                                                                                                                                                                                                                                                                                                                                                          
 45 doautoall SessionLoadPost                                                                                                                                                                                                                                                                                                                                           
 46 unlet SessionLoad                                                                                                                                                                                                                                                                                                                                                   
 47 " vim: set ft=vim :

**Comment by menash134** [comment]
my nvim config is 
https://github.com/menash134/nvim

**Comment by menash134** [comment]
I had switched to NerdTree in nvimconfig. If you want to simulate the issue, kindly comment NerdTree mappings in ~/.config/nvim/init.vim

**Comment by kyazdani42** [comment]
session issues are well known and being worked on, i'll merge a patch soon
