### ISSUE TITLE
Select multiple files or directory and open them in tabs?

### ISSUE THREAD

**Issue by aegatlin** [kyazdani42/nvim-tree.lua#604]
I've probably just missed where this was discussed but looked for it and couldn't find it. I want to bulk edit a bunch of files and was hoping to find a way to multiselect the files of interest and open them in tabs. Is there a way to do that with this plugin?

**Comment by kyazdani42** [comment]
i'm going to implement the bulk selection today, and i'll leave the user to use the map to do whatever they want with it. but the issue has already been discussed multiple times i think in #51 #221 and #595 (i think)

**Comment by aegatlin** [comment]
since its been discussed multiple times I'll go ahead and close

**Comment by shubham-cpp** [comment]
Apologies if I'm being but how do you select multiple files. I know we could copy multiple files by manually selecting with c and then pasting with p. But lets say I wanna delete multiple files/directories how would I do that?

**Comment by kyazdani42** [comment]
i have to finish the PR but it's partially done in #612
