### ISSUE TITLE
Netrw Options not working 

### ISSUE THREAD

**Issue by Trid-collab** [kyazdani42/nvim-tree.lua#605]
It seems the following options are not working after the latest changes - it seems to have no effect to whatever value 0 or 1,  I change it to. 
g:nvim_tree_hijack_netrw             
g:nvim_tree_disable_netrw

I used both nvim-tree and netrw. Now I cannot use netrw with nvim-tree

**Comment by kyazdani42** [comment]
what do you mean by not working ? I haven't seen any changes on my end.

**Comment by kyazdani42** [comment]
I'll take a look into it tomorrow alongside the session thing, maybe i'll disable the directory hijacking if both disable and hijack netrw are false.

**Comment by Iron-E** [comment]
For me it's working partially. `netrw` never shows but I get an error message as if it should have. This only happens when doing `nvim <directory>`:

```log
Vim(call):E117: Unknown function: netrw#LocalBrowseCheck
Please check your config for correctness
Error detected while processing function <SNR>77_VimEnter[10]..<SNR>77_LocalBrowse:
```

**Comment by joriskoris** [comment]
Any news on this?

**Comment by hongphong177** [comment]
i meet this issue also :(

**Comment by kyazdani42** [comment]
should be working now, could you confirm (with the new setup options)

**Comment by Trid-collab** [comment]
Thanks it worked for me too

**Comment by kyazdani42** [comment]
closing this then :)
