### ISSUE TITLE
Can't use "q" to close nvim tree while opening nvim with a blank file

### ISSUE THREAD

**Issue by Trid-collab** [kyazdani42/nvim-tree.lua#606]
Sometimes I open just nvim without any files and arguments. It then opened the nvim-tree which I used to close using "q" and then perhaps use telescope project to jump into a file in another project. It was so much flexibile. 
Now when I try to use "q" it simply gives me the message the below and does'nt allow me to close the nvim tree. If I press y in this condition it simply quits and closes nvim.
Could we have the old option back

![image](https://user-images.githubusercontent.com/61322708/131863413-790d0e35-4c2c-4795-8d8d-89cfc640a84a.png)

**Comment by kyazdani42** [comment]
you maybe just gave me a hint on how to fix this behavior, instead of closing nvim when the tree is the last window or trying to close the tree when its the last window, maybe just swapping with another open buffer or with an empty one would do the trick.

**Comment by kyazdani42** [comment]
fixed in `1.2.3` (27caccba18bc8bba457ebc2f959fe0df82e27038)
