### ISSUE TITLE
How to show current filename selected on the tree in status

### ISSUE THREAD

**Issue by syrm** [kyazdani42/nvim-tree.lua#607]
When the filename is very long its more convenient if i can see the filename in the status than scroll to the right side to see the name fully.

So is it possible to show the current selected file in the tree in the status ?

**Comment by gegoune** [comment]
You can get current node by

```lua
local lib = require'nvim-tree.lib'
local node = lib.get_node_at_cursor()
```

and just display it in status line (you will need to change status line when entering nvim-tree window). What status line plugin, if any, do you use?

**Comment by syrm** [comment]
i'm using galaxyline, i'll try to set this, thank you

**Comment by kyazdani42** [comment]
hi, closing this since this seems good now. @syrm tell me if you need more informations :)
