### ISSUE TITLE
Can't create new file in Windows

### ISSUE THREAD

**Issue by Julpikar** [kyazdani42/nvim-tree.lua#610]
### Error in Neovim
`Could not create folder in \C:\`

### Cause
It seem error in http://github.com/kyazdani42/nvim-tree.lua/blob/master/lua/nvim-tree/fs.lua#L80. When in first iteration `path_to_create = ''` and path_join between empty string and `C:\\` will result `\C:\`.

**Comment by kyazdani42** [comment]
hi, could you try `1.2.5` (71122d798482e30c599d78aa7ae4a756c6e81a79) on latest master and tell me if this fixes your issue ?

**Comment by Julpikar** [comment]
It's worked, thanks :)

**Comment by phamhiep2506** [comment]
Please, fix it in Termux Android
![Screenshot_2021-09-05-15-34-10-671_com termux](https://user-images.githubusercontent.com/64464369/132120749-8323c2bd-163a-4eec-a5bc-401a05ef495b.jpg)

```vim
Could not create folder /data
/data/data/com.termux/files/home/Projects/react-app/src/component/
navbar/index.jsx was properly created
Press ENTER or type command to continue
```
