### ISSUE TITLE
Cannot override empty buffer with new opened file buffer

### ISSUE THREAD

**Issue by BlueDruddigon** [kyazdani42/nvim-tree.lua#615]
At the latest master branch, an option in https://github.com/kyazdani42/nvim-tree.lua#setup

`let g:nvim_tree_respect_buf_cwd = 1 "0 by default, will change cwd of nvim-tree to that of new buffer's when opening nvim-tree.` does not work for me.

I'm using LunarVim from [LunarVim](https://github.com/LunarVim/LunarVim) at the latest rolling branch.
I'm not sure if this issue belongs to [nvim-tree](https://github.com/kyazdani42/nvim-tree.lua) or [LunarVim](https://github.com/LunarVim/LunarVim).
Please help me fix this.

**Comment by kyazdani42** [comment]
what do you mean by `does not work` ? seems lunarvim enable the feature by default when the tree is active

**Comment by BlueDruddigon** [comment]
> what do you mean by `does not work` ? seems lunarvim enable the feature by default when the tree is active

I'm sorry. Let me explain the issue. in lunarvim, I've set these options
![image](https://user-images.githubusercontent.com/39997524/133220553-d3167df6-0013-48aa-ae16-f85f593a4fa8.png)
because I don't want the dashboard.
But when lunarvim opened, an empty buffer open and then, when I open a file, the buffer didn't be replaced by a new file. In the `dc630d1` commit the newly opened file will replace the empty buffer above. 
I don't know if it was a bug.

**Comment by kyazdani42** [comment]
Hello ! 
i still don't understand. how this relates to `nvim_tree_respect_buf_cwd` ?

**Comment by kyazdani42** [comment]
hi @BlueDruddigon, sorry for the late answer, is this issue still relevant ?

**Comment by micro-aries** [comment]
yes @kyazdani42  i opened the same issue yesterday the current behavior is that nvim tree takes the focus [cursor] when i open a file, i want nvim tree to detect that i opend a file a give the focus [cursor] to the file that i want to edit here is an example that is been used by nerd tree i want this from nvim tree

[ " Start NERDTree. If a file is specified, move the cursor to its window.
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * NERDTree | if argc() > 0 || exists("s:std_in") | wincmd p | endif ]

I Want Nvim Tree To change Focus when i open a file  From this 

![pic2](https://user-images.githubusercontent.com/100243267/155417377-5c206f01-3071-4e4f-8d8d-1dcf36b5a1e9.png)

TO This

![1pic2](https://user-images.githubusercontent.com/100243267/155417549-7a38c99f-eba2-46a2-a21f-62b5b2872a46.png)

**Comment by kyazdani42** [comment]
@micro-aries i don't think so. @BlueDruddigon pinging again.

**Comment by alex-courtis** [comment]
This should be resolved. 76d4ed5 added `hijack_unnamed_buffer_when_opening` and there has been a lot of improvements around that area since then.

Please reopen if you experience any further issues.
