### ISSUE TITLE
[Question] Is it possible to specify my own matcher for icons?

### ISSUE THREAD

**Issue by Looooopy** [kyazdani42/nvim-tree.lua#617]
So say I would like to use the docker icon on files "docker-compose*.yml"?

**Comment by kyazdani42** [comment]
i think you should look at https://github.com/kyazdani42/nvim-web-devicons/ but basically you should use the `add_icon` function to setup your own icons. Closing as this is not related to the tree itself.

**Comment by mrlectus** [comment]
> i think you should look at https://github.com/kyazdani42/nvim-web-devicons/ but basically you should use the `add_icon` function to setup your own icons. Closing as this is not related to the tree itself.

How is it not related to tree? If i create a file docker-compose-prod.yml should it know that is also a docker file?
