### ISSUE TITLE
Auto command for when window is closed and picking window automatically

### ISSUE THREAD

**Issue by augustocdias** [kyazdani42/nvim-tree.lua#620]
Hi,

First thanks for the plugin. It is really amazing.

I would like to ask if its possible to somehow create an auto command for when the window of the tree is closed. I basically set it `nvim_tree_quit_on_open` to 1 and since my `tabline` (I use barbar) plugin has not awareness of that I end up with my tabline screwed. 
So this is what I have to handle toggling and opening the tree at the moment:

```lua
-- NvimTree
function _tree_find()
    require'bufferline.state'.set_offset(31, 'FileTree')
    require'nvim-tree'.find_file(true)
end
function _tree_toggle()
    if require'nvim-tree.view'.win_open() then
        require'bufferline.state'.set_offset(0)
    else
        require'bufferline.state'.set_offset(31, 'FileTree')
    end
    require'nvim-tree'.toggle()
end
keymap('n', '<F2>', '<cmd>lua _tree_find()<CR>', no_remap_opt)
keymap('n', '<F3>', '<cmd>lua _tree_toggle()<CR>', no_remap_opt)
```

All works fine if the tree is not closed automatically if I open a file.

Another question is: is it possible to pick automatically a file? It always asks in which window I want to open and I'd like to just open in any.

**Comment by augustocdias** [comment]
I've been trying to create an `autocmd` for this... Somehow the function `win_open` still returns true when the `WinClosed` event is called

**Comment by jsgv** [comment]
Is it possible to automatically set the window to pick when `nvim_tree_disable_window_picker` is set to 1?

I just want it to select the last window I was active in. I attempted to figure it out, but it seems somewhat random to me how the window is automatically selected.

**Comment by augustocdias** [comment]
@kyazdani42 sry for the long delay. Things have been crazy at home.

Here is the tree open. Notice in the top the tabline for the tree and for the buffer.

![image](https://user-images.githubusercontent.com/1080789/140020653-0ec5d9e1-520e-40b7-8f1d-61a9ebc7c5fc.png)

When I press enter to open a file. It closes the tree as expected but the tabline doesn't update to remove the tree from it.

![image](https://user-images.githubusercontent.com/1080789/140020760-623a55fa-f8d1-4fd8-8dbb-b532788a56d3.png)

The expected result should be like this

![image](https://user-images.githubusercontent.com/1080789/140020969-3a0bc53d-c824-4f27-bb81-bea7c8645e55.png)

I was trying to debug the issue but as I said somehow the function `win_open` still returns true when the `WinClosed` event from the tree is called

**Comment by kyazdani42** [comment]
@jsgv you cannot right now. Except if only one windows is opened. We could add a custom open to open either with the picker or not.
@augustocdias i guess this is because nvim tree does not close the window, it only hides it. I might be reworking this behavior when i have some time.
Although win_open should not return true if the tree is closed, would that be because it runs too early ? Did you try schedule or defer the winclosed callback ?

**Comment by augustocdias** [comment]
I tried to create an auto command for auto close. But as I said the win_open was still returning true when it was called.

**Comment by kyazdani42** [comment]
did you try to `vim.schedule` the auto command to make sure the window is well closed ?
something like
```
au BufHidden NvimTree lua vim.schedule(function() print(require'nvim-tree.view'.win_open()) end)")
```

**Comment by augustocdias** [comment]
With the schedule, it works fine.

**Comment by kyazdani42** [comment]
closing this then, view should be refactored anyway to avoid this kind of thing.
