### ISSUE TITLE
Persist window size after resizing

### ISSUE THREAD

**Issue by DanielCardonaRojas** [kyazdani42/nvim-tree.lua#623]
It would be great if the width of the resized window width would be persisted after succesive toggles.

Is there an option for this ?

**Comment by kyazdani42** [comment]
`NvimTreeResize` ?

**Comment by kyazdani42** [comment]
I don't understand :disappointed: Could you be more specific or provide an example ?

**Comment by DanielCardonaRojas** [comment]
![nvim-tree-resize-example mov](https://user-images.githubusercontent.com/5472687/135497626-218b0529-bce9-41c9-adcd-7552601556c9.gif)

As you can see in this example nvim-tree always opens to a default size.
What I would like is if the second time I open the file explorer it would have the size of how I left it before. 

I might be missing some configuration option.

**Comment by kyazdani42** [comment]
not sure there is something i can do here, there is no such thing as WindowResize event, if there was one, i would have bind it to resize.
Maybe try overriding the `resize` command to also set `require'nvim-tree.view'.View.width = new_window_width` ?
If you cannot, maybe you could write an interval method that every second or two would check if the tree is open, if it's current window width is different than the one in the config, and if so, change it accordingly.
