### ISSUE TITLE
Neovim freezes for around 20 seconds when creating a file or folder.

### ISSUE THREAD

**Issue by Julian1620** [kyazdani42/nvim-tree.lua#625]
When I open neovim-tree and create a new file neovim freezes and I can't eddit anything for over 20 seconds.

**Comment by vadymbiliuk** [comment]
Same issue here :C

**Comment by vadymbiliuk** [comment]
Try set this in your options file vim.cmd('set shell=/bin/zsh')

**Comment by Julian1620** [comment]
It was indeed an issue with fish. bash or zsh works better

**Comment by kyazdani42** [comment]
see #549
