### ISSUE TITLE
Not an editor command: NvimTreeToggle

### ISSUE THREAD

**Issue by yngwi** [kyazdani42/nvim-tree.lua#639]
Hi,
after updating plugins with Vim-Plug today, Nvim Tree doesn't work anymore for me. It worked fine until yesterday but now no Nvim-Tree commands are available anymore. The plugin seems to be still installed, according to Vim-Plug. I haven't changed anything on my side.
Best,
Daniel

**Comment by CantoroMC** [comment]
You should call the setup function and the commands will be loaded.
Follow the wiki instructions.

**Comment by zeitchef** [comment]
I'm having a similar issue using Packer, everything setup normally. No commands are available.

**Comment by yyandrew** [comment]
Same here.

**Comment by zeitchef** [comment]
I just had a look at the README, and indeed some setup has changed. Following the instructions there got me back up and running.

**Comment by yngwi** [comment]
> 
> 
> You should call the setup function and the commands will be loaded.
> Follow the wiki instructions.

Thank you. I didn't realize that this changed. It's working now.
