### ISSUE TITLE
File operations use git if within repository and fs-object is tracked

### ISSUE THREAD

**Issue by weilbith** [kyazdani42/nvim-tree.lua#64]
Hey thanks for this cool plugin! :pray: 

I think it would be a cool feature to integrate git also into the operations to the file system. So if I call an operation to remove or rename on an object, it would be great if the git equivalent commands could be used. So to name `git-rm` and `git-mv`. Of course this should only be done when inside a git repository and if the object is actually tracked by git (already). I would not handle operations creating new objects.

Curious what you think about this idea. :upside_down_face:

**Comment by kyazdani42** [comment]
Hi,
well i don't really think this plugin should aim at such feature IMO. Git operations are separated from fs operations in my workflow.
If however, you wish to submit a PR that does not make the code more complicated, i will accept such feature.
