### ISSUE TITLE
Indent_markers not working?

### ISSUE THREAD

**Issue by CantoroMC** [kyazdani42/nvim-tree.lua#640]
This is my [configuration](https://pastebin.com/SjeLVYhP), I'm not sure if I am doing something wrong or not, but since the new configuration style, lua oriented, indent markers are not more showing and they fall back to the default arrow.

I have now looked the last commit and seen that also lsp_diagnostics has been ported to lua, I moved it into the setup function; and realized that even lsp diagnostics are not more rendered on the signcolumn(this is not cause of the lua variable but since a864b80bafeba6ea17d1a55e4c6f5e73f189f6bb, i believe).

**Comment by kyazdani42** [comment]
i've found out that importing nvim-tree before setting up global options has weird behavior. I'm investigating this.

**Comment by CantoroMC** [comment]
You're right moving it just before the setup function, works fine.

**Comment by kyazdani42** [comment]
ok just fixed this _partially_ in `1.3.6` (506d2e792a9b0ca). At least the rendering is now available for refactoring :smile:
