### ISSUE TITLE
[No Name] buffer creation when start neovim with `nvim .`

### ISSUE THREAD

**Issue by amirrezasadeqi** [kyazdani42/nvim-tree.lua#643]
Hi there!

First of all thanks for your nice project.

well, the problem is that when i open neovim in the current working directory using `nvim .`, it creates an empty `[No Name]` buffer. I think the problem started after `da26dfa` commit(excuse me that  i don't remember the exact commit that caused this problem). 

my `hidden` option is on and when i turn it off, still it creates it but disappears immediately. Also i I have the `dashboard` plugin installed, but I don't think this problem is related to the session management, because this problem is consistent in every directory even without saving a session.

**Comment by kyazdani42** [comment]
just fixed in `1.4.13`  (1fe211e). There was issues within the override logic.
