### ISSUE TITLE
[Feature Request] Uncollapse to focused file only and only when opening the tree (similar to `update_focused_file`)

### ISSUE THREAD

**Issue by lucasvianav** [kyazdani42/nvim-tree.lua#644]
Hey, thanks for this great plugin :)

Basically I'd like it to only uncollapse directories to show the focused file when opening NvimTree and re-collapse them when I close it. This way, everytime I open NvimTree, only the currently focused file will be shown. Maybe I'm misremembering things, by I think `coc-exporer` did this

**Comment by kyazdani42** [comment]
do you mean something like `NvimTreeFindFile` ?

**Comment by lucasvianav** [comment]
I wasn't aware of that command, but sound promising, I think I can make a function for what I want using it. But now even with `update_focused_file` disabled, NvimTree is not re-collapsing the directories I opened - which didn't happen before iirc. Any tips?

**Comment by kyazdani42** [comment]
just added a `lib.collapse_all` function that would help maybe ?
You could override the default behavior of the NvimTreeFindFile by doing
```vim
function! NvimTreeFindFileAfterCollapse()
  lua <<EOF
    require'nvim-tree.lib'.collapse_all()
    require'nvim-tree'.find_file(true)
  EOF
endfunction
```

**Comment by lucasvianav** [comment]
Working great now, thank you! I'll leave the function I'm using here in case someone else wants this behavior.

```lua
function _G.nvim_tree_toggle()
    local is_nvim_tree_loaded, nvim_tree = pcall(require, 'nvim-tree')

    if is_nvim_tree_loaded then
        if is_nvim_tree_open then
            nvim_tree.close()
            require('nvim-tree.lib').collapse_all()
            is_nvim_tree_open = false
        else
            nvim_tree.find_file(true)
            is_nvim_tree_open = true
        end
    end
end
```
