### ISSUE TITLE
Git status changes

### ISSUE THREAD

**Issue by kristijanhusak** [kyazdani42/nvim-tree.lua#65]
Hi,

is there any specific reason why folders have git status icon after, and files have it before? :)

I would like to make that consistent, and also to introduce an option to highlight the whole item when it is "dirty". What do you think about that?

**Comment by kyazdani42** [comment]
It looked better imho. Adding an option for that would be a little bit overkill, i'll see what i can do to make this more consistent (the code would actually be easier too)
