### ISSUE TITLE
No commands working on new Neovim 0.5.1

### ISSUE THREAD

**Issue by stoicAlchemist** [kyazdani42/nvim-tree.lua#650]
[No Commands](https://imgur.com/gallery/kACSPge) available on Neovim 0.5.1 :( 

Screenshot of list of commands starting with N: https://imgur.com/gallery/7psUzwh

**Comment by ewoutquax** [comment]
Since this morning, I'm getting this error:
5108: Error executing lua .../<username>/.vim/plugged/nvim-tree.lua/lua/nvim-tree/view.lua:247: attempt to concatenate local 'move_to' (a nil value)

**Comment by ExpandingMan** [comment]
I just tried backtracking and I find that NvimTree is broken for me as of [this commit](https://github.com/kyazdani42/nvim-tree.lua/commit/a864b80bafeba6ea17d1a55e4c6f5e73f189f6bb).

**Comment by stoicAlchemist** [comment]
I'm on nightly and this was working for me yesterday :(

**Comment by arsham** [comment]
I've seen this too, however I've fixed it by changes these:

```lua
vim.g.nvim_tree_auto_close      = 1
vim.g.nvim_tree_lsp_diagnostics = 1
-- etc.
```

Into these:

```lua
require('nvim-tree').setup {
  disable_netrw   = false,
  hijack_netrw    = false,
  auto_close      = true,
  lsp_diagnostics = true,
}
```

**Comment by ExpandingMan** [comment]
Oh, that's a nice surprise, the setup is better and the auto open behavior is much improved (doesn't open on `nvim` unless given a directory argument, this was driving me bonkers).  A deprecation message or whatever probably would have been in order, but cool, thanks all!

**Comment by ewoutquax** [comment]
Adding this line to the config works for me as well: `require('nvim-tree').setup()`.

I can now use the command `NvimTreeFindFile` as before

**Comment by stoicAlchemist** [comment]
Yeah, adding `require('ivim-tree').setup()` works but now my `g:vim_tree_XXX` config doesn't work, I'm assuming this has to do with changes...??? I'll try using Lua instead

**Comment by kyazdani42** [comment]
i've added a warning message information on load to inform the setup has changed ! but i have to wrap it in a schedule call to make sure all global options have loaded first, maybe `vim.schedule` is not available in 0.5.1 ?

**Comment by konart** [comment]
> i've added a warning message information on load to inform the setup has changed ! but i have to wrap it in a schedule call to make sure all global options have loaded first, maybe it doesn't work ?
> EDIT: if user do not specify any configuration option that have been moved to setup, i do not display a message to avoid useless noise.
> 
> Please check the documentation, configuration has indeed changed and some small improvments have been added.

> [NvimTree] following options are now set in the setup, please read the new documentation for the setup function: nvim_tree_follow

> E149: Sorry, no help for nvim_tree_follow

I think docs weren't updated yet?

**Comment by kyazdani42** [comment]
i think the message is not explicit enough :smile: should be something like
`following options (nvim_tree_follow) are now set in the setup function, please read its documentation (:help nvim-tree-setup)`

**Comment by stoicAlchemist** [comment]
Nice, I think the documentation solves this particular issue right? Thanks @kyazdani42 for the amazing work, your plugin was the only one that made me step away from NerdTREE
