### ISSUE TITLE
Inconsistent highlight between icon and name for git state [??]

### ISSUE THREAD

**Issue by saviocmc** [kyazdani42/nvim-tree.lua#651]
When ```vim.g.nvim_tree_git_hl = 1```, the renderer uses the highlights from [```local git_hl```](https://github.com/kyazdani42/nvim-tree.lua/blob/11659aaa658cf0e8aeae849daf2209355737e245/lua/nvim-tree/renderer/init.lua#L97) to render the node entry name. In this table, the state [??] is defined as [```"NvimTreeFileNew"```](https://github.com/kyazdani42/nvim-tree.lua/blob/11659aaa658cf0e8aeae849daf2209355737e245/lua/nvim-tree/renderer/init.lua#L129) (which *I think* is **correct**).

However, to render the git icon, the renderer uses the highlights from the other table [```local git_icon_state```](https://github.com/kyazdani42/nvim-tree.lua/blob/11659aaa658cf0e8aeae849daf2209355737e245/lua/nvim-tree/renderer/init.lua#L168). In this second table, the state [??] is defined as [```"NvimTreeGitDirty"```](https://github.com/kyazdani42/nvim-tree.lua/blob/11659aaa658cf0e8aeae849daf2209355737e245/lua/nvim-tree/renderer/init.lua#L201) (which *I think* is **incorrect**).

This is causing a mismatch between the icon file name highlight for the state [??].
![2021-09-27-14-15-47](https://user-images.githubusercontent.com/9142154/134955439-6b8a6000-c23c-42c2-bc6c-c53400449fa2.png)

**Question:** Why can't these tables be unified, as they represent the same git states?

**Comment by kyazdani42** [comment]
fixed in `1.4.3` (67f1d36). The tables are not unified because they don't return the same set of data and the Hl groups are also different, but i guess they could be unified if written in a better way.

**Comment by saviocmc** [comment]
Thanks for the quick fix!
