### ISSUE TITLE
nvim_tree_ignore is not working

### ISSUE THREAD

**Issue by gmr458** [kyazdani42/nvim-tree.lua#652]
In this image you can see how the .git folder is not hidden.
![captura](https://user-images.githubusercontent.com/53343401/134970892-07821c78-c0f6-4e02-9163-033b6f4eac3c.png)

**Comment by kyazdani42** [comment]
please read the documentation more carefully. I've specified that global options `vim.g.*` should be set _BEFORE_ the setup function call.
