### ISSUE TITLE
System open duplicates passed arguments and kills spawned processes on window close

### ISSUE THREAD

**Issue by piotr-machura** [kyazdani42/nvim-tree.lua#653]
When opening files with the `system_open` program all of the **previously** open files are passed as arguments to the `cmd`.
Eg. If I press `s` on `fileA` it will open, and if I press it again the file will open **twice** (three times if I press it again etc.)
I have tested it using a `myopen` script:
```bash
#!/bin/bash
echo "$@" >> ~/args.txt
```
Drop that in your `$PATH` and set the options like so:
```lua
require('nvim-tree').setup {
    system_open = { cmd  = 'myopen', args = {} },
}
```
Try opening a couple of files and you will see the list of args "grow", with the file names appended instead of being the only passed argument.

On another note (I believe this is related, or at least also originates [here](https://github.com/kyazdani42/nvim-tree.lua/blob/1b746744ad04c14d2cf260641750f77ec5f62635/lua/nvim-tree.lua#L112)), the spawned proceses seem to get killed on terminal window close, even if the opening program disowns them.

This can be reproduced with another script `myopen2`:
```bash
#!/bin/bash
nohup xdg-open "$1" &>/dev/null & disown # you may replace xdg-open $1 with any GUI program
```
If I invoke this script manually with `myopen2 somefile.pdf` and then close the terminal window the spawned pdf viewer remains alive (as expected). But if I set it as system open:
```lua
require('nvim-tree').setup {
    system_open = { cmd  = 'myopen2', args = {} },
}
```
then open somefile.pdf by clicking `s` in the tree and close the terminal window (the one with neovim in it) the pdf viewer gets killed. Stranglely, if I exit neovim first (with a simple `:qa`) and *then* close terminal window the pdf viewer will *not* get killed.

**Edit:** the  pdf viewer process is not owned by the terminal/shell/neovim (`ps -l <pdf viewer PID>` shows the PPID is 1), so the disowns/nohups are working. What is happening here?

**Comment by saviocmc** [comment]
@piotr-machura can you test if this solves the duplication issue for you?
https://github.com/kyazdani42/nvim-tree.lua/pull/655/files

**Comment by piotr-machura** [comment]
PR #655 does indeed fix the duplication issue, thank you so much! The process ownership remains an issue though.

**Comment by saviocmc** [comment]
My experience on linux using ```xdg-open``` is exactly the same as you reported for your ```myopen2```.
If I close the terminal **without** exiting nvim first, all spawned process are killed.
**But** if I exit nvim and **then** close the terminal, the other processes survive.

**Comment by piotr-machura** [comment]
The weird part is that `myopen2` spawns the xdg-open process (and the pdf viewer or whatever as a consequence) and **disowns** it, which means even though the neovim process owns `myopen2` and kills it when it is killed itself, the pdf viewer *should* survive. I imagine the process ownership looks like so:
```none
terminal emulator -> shell -> neovim -> myopen2 -/-> xdg-open (disowned/nohup)
```
So when the terminal emulator gets killed the children die with it, but xdg-open shouldn't (the pdf viewer's parent PID is 1, which essentially means "no parent process").

I imagine the error hides either [here](https://github.com/kyazdani42/nvim-tree.lua/blob/1b746744ad04c14d2cf260641750f77ec5f62635/lua/nvim-tree.lua#L136), where the process is spawned, or in [this](https://github.com/kyazdani42/nvim-tree.lua/blob/1b746744ad04c14d2cf260641750f77ec5f62635/lua/nvim-tree.lua#L152) libuv loop which handles the stderr, but I sadly know next to nothing about how exactly those things work.

**Comment by saviocmc** [comment]
You solved it! I just tested with your diff and all process now remains alive no matter what happens to the terminal or nvim. Adding the commit now to the PR. Thank you very much!

**Comment by kyazdani42** [comment]
should be fixed :) hanks @saviocmc and @piotr-machura, i might take a deeper look at this later on, it might be something going on with the libuv process management and its event loop wrongly interfacing with neovim's event loop, that's why i personally prefer using neovim jobs to manage this kind of stuff.
