### ISSUE TITLE
E492: Not an editor command: NvimTreeToggle

### ISSUE THREAD

**Issue by strogiyotec** [kyazdani42/nvim-tree.lua#656]
Hey , I just updated to the latest commit now all my configs are broken,  my version is on this commit `f8b5eb0bd84744a1434bae83692d6c7eb8dcb91a`
When I try to run `:NvimTreeToggle` nvim says that this command doesn't exist.  Does anyone have the same problem ?

**Comment by Yarnus** [comment]
I met the same situation on `f8b5eb0bd84744a1434bae83692d6c7eb8dcb91a `

**Comment by syuni** [comment]
It seems that you need to call `setup()`

https://github.com/kyazdani42/nvim-tree.lua#setup

**Comment by delfick** [comment]
that worked for me, thanks @syuni

**Comment by strogiyotec** [comment]
Works, thank you , will close the ticket

**Comment by williamboman** [comment]
Was a bit confused by this as well. I ran a git bisect and it seems to have been introduced in a864b80bafeba6ea17d1a55e4c6f5e73f189f6bb, FWIW. Probably on purpose due to new API
