### ISSUE TITLE
E492: Not an editor command: GitGutterLineNrHighlightsEnable

### ISSUE THREAD

**Issue by rbuchberger** [kyazdani42/nvim-tree.lua#657]
Hello! Thanks for the great plugin.

Since the recent update requiring a call to  `setup()`, I've been getting the following error on startup:

```
E5108: Error executing lua .../share/nvim/plugged/nvim-tree.lua/lua/nvim-tree/view.lua:93: Vim:E492: Not an editor command: GitGutterLineNrHighlightsEnable
```

Config: 
```vim
" plugin/nvim-tree/config.vim

nmap <silent> <leader>t :NvimTreeToggle<CR>
nmap <silent> gt :NvimTreeFocus<CR>

lua << EOF

require'nvim-tree'.setup({
  auto_close = true,
  lsp_diagnostics = true,
  view = {
    width = 40
    }
  }
)
EOF
```

I do have gitgutter installed, so maybe it's a load order problem? 

Thanks!

**Comment by kyazdani42** [comment]
this makes no sense :smile: Could it be related to some other config you have ?

**Comment by kyazdani42** [comment]
you have a `Filetype *` to start gitgutter, but maybe gitgutter hasn't loaded yet but the autocmd runs anyway because i set filetype on the nvim tree buffer.
Try to move the nvim-tree plug initialization after gitgutter's initialization ?

**Comment by rbuchberger** [comment]
Ahh, that was the problem. Removing the gitgutter autocommand fixes it. I think it was needed for an earlier version, becuase that autocommand isn't necessary for gitgutter any more and I still had it floating in my configs.

Thanks a ton for your help! I don't know if I would have worked it out on my own.
