### ISSUE TITLE
Question: Prevent width resize when closing a buffer and opening an existing one

### ISSUE THREAD

**Issue by francois-pasquier** [kyazdani42/nvim-tree.lua#658]
When I close a buffer, nvim-tree takes the whole space: This is ok.

Once I click on another buffer, nvim-tree takes half of the width.

Is it possible to make it go back to its previous width?

If it's not clear enough, I can share a short videoclip.

Cheers!

**Comment by dvdksn** [comment]
I have the same issue. I tried setting the width configuration parameter explicitly to 30 but opening a new buffer will still have nvim-tree take up half the window width.

**Comment by piotr-machura** [comment]
Try setting `view { auto_resize = true }` in your config. I believe this *used to* be the default, but was changed in the new config refactor.

**Comment by francois-pasquier** [comment]
> Try setting `view = { auto_resize = true }` in your config (have a look at the [README](https://github.com/kyazdani42/nvim-tree.lua#setup)). I believe this _used to_ be the default, but was changed to `false` in the new config refactor.

It doesn't seem to work for me :/

**Comment by dvdksn** [comment]
That setting worked for me. These are my current options: (no global vars)

```lua
require("nvim-tree").setup{
  update_focused_file = {
    enable = true,
  },
  disable_netrw = true,
  update_cwd = true,
  view = {
    auto_resize = true
  }
}
```

**Comment by francois-pasquier** [comment]
Nevermind, I have a typo in my config!

Cheers, it works perfectly!

**Comment by askfiy** [comment]
There is a terrible solution to this problem effectively.

We know that when the buffer is closed, nvim-tree fills the entire screen.

So I reopened nvim-tree after closing buffer and he was able to solve the problem.

(I use the bufferline plugin to manage buffers)

Key bindings:

```
map("n", "<C-q>", ":bdelete!<CR>:NvimTreeToggle<CR>:NvimTreeToggle<CR><C-w>l", opt)
```

**Comment by kyazdani42** [comment]
@piotr-machura thanks for answering this :)
