### ISSUE TITLE
NvimTreeToggle bound to key wont toggle

### ISSUE THREAD

**Issue by timoleistner** [kyazdani42/nvim-tree.lua#661]
So I've found that :NvimTreeToggle wont really toggle the tree because my cursor immediately switches to the nvim-tree split and therefore functions as opening the file under the cursor in a new tab and therefore wont close the tree again...
Previously I've got around this with the following option
`vim.g.nvim_tree_bindings = { { key = "<C-t>", cb = tree_cb("close") }, }`
but somehow this wont work anymore and I dont know how to change it back as the documentation is a bit misleading on how to define the keymappings inside the tree-split.
Any help would be appreciated.

**Comment by kyazdani42** [comment]
I moved the mappings inside the new `setup` function. You have all informations inside the documentation :)
