### ISSUE TITLE
toggle_help always opens help but often does not close it

### ISSUE THREAD

**Issue by snoblenet** [kyazdani42/nvim-tree.lua#662]
For me, `toggle_help` always opens help but often does not close it.

In the absence of a built-in `close_help` function, is there some way I can map its functional equivalent to `<esc>`?

**Comment by kyazdani42** [comment]
this is a bug that should be fixed, i'll see what i can do :)

**Comment by kyazdani42** [comment]
fixed in `1.4.10` (acfb3c0bfba93fe)
