### ISSUE TITLE
`autocmd BufReadPost * lua require'nvim-tree'.refresh()` causes error

### ISSUE THREAD

**Issue by gavynriebau** [kyazdani42/nvim-tree.lua#663]
### Steps to reproduce:

Add the following autocommand to your init.vim / init.lua file:

```vim
autocmd BufReadPost * lua require'nvim-tree'.refresh()
```

Start neovim with an the name of a file to open immediately, e.g.

```bash
$ nvim ~/.config/init.lua
```

### Expected result

The file should open without errors.

### Actual result

The following error will be printed when vim starts:

```
Error detected while processing BufReadPost Autocommands for "*":
E5108: Error executing lua ...ck/packer/start/nvim-tree.lua/lua/nvim-tree/populate.lua:162: bad argument #1 to 'fs_scandir' (string expected, got nil)
Press ENTER or type command to continue
```

### Background Info

I added the autocmd described above after finding that the nvim-tree's open file highlighting sometimes did not work (specifically when I opened a file from telescope plugin file finder).

The purpose of the autocmd is to automatically call `refresh()` when a new buffer has been opened and therefore ensure that the open file highlighting is correct.

After adding the autocmd I started seeing the error as described above.

**Comment by kyazdani42** [comment]
should be fixed in `1.4.11` (c0cd3aeb657313), reopen if it's not the case :)
