### ISSUE TITLE
Missing migration guide for new setup options

### ISSUE THREAD

**Issue by academo** [kyazdani42/nvim-tree.lua#665]
Coming here after an update let my editor without a working file explorer I saw that I had to run the setup function.

After running the setup function it notified me that two of my settings: `auto_open` and `follow` are now set in the setup function but I can't find them, where they renamed somehow? Perhaps a migration guide for the new setup options could help.

Additionally I don't want to sound ungrateful for the work you guys are doing but It is hard to update your plugins and suddenly having to spend now time in setting up plugins again when they were in order and working, perhaps you'd consider keeping some backwards compatibility for the migration of options?

Thanks!

**Comment by konart** [comment]
`:h nvim-tree` gives this  (at the moment of my comment)

```
To configure the tree (and make it runnable), you should call the setup
function.

>
    require'nvim-tree'.setup {
      disable_netrw       = true,
      hijack_netrw        = true,
      open_on_setup       = false,
      ignore_ft_on_setup  = {},
      auto_close          = false,
      open_on_tab         = false,
      hijack_cursor       = false,
      update_cwd          = false,
      lsp_diagnostics     = false,
      update_focused_file = {
        enable      = false,
        update_cwd  = false,
        ignore_list = {}
      },
      system_open = {
        cmd  = nil,
        args = {}
      },
      view = {
        width = 30,
        side = 'left',
        auto_resize = false,
        mappings = {
          custom_only = false,
          list = {}
        }
      }
    }
<

As options are currently being migrated, configuration of global options in
|nvim-tree-options| should be done BEFORE the setup call.
```

I'd appreciate some note in github readme too though. :)

**Comment by kyazdani42** [comment]
there are notes in the readme, although i prefer detailing in the vim documentation because i like to keep the readme simple. I'll write a migration guide in an issue because a lot of people have been having issues since.

**Comment by kyazdani42** [comment]
see #674
