### ISSUE TITLE
[BUG] Creating new file with cursor over the current directory folder fails

### ISSUE THREAD

**Issue by esdevver** [kyazdani42/nvim-tree.lua#667]
I hover over the current directory and press 'a' to create a new file. Upon pressing 'a', I get this error.

![cursor over current directory](https://user-images.githubusercontent.com/62915053/135293314-6b8cd8de-ccc6-466f-8b4a-3e666a58f364.png)

![Error message](https://user-images.githubusercontent.com/62915053/135293430-2e476177-9b1d-4c02-a458-79baaa8cea42.png)

`E5108: Error executing lua ...ite/pack/packer/start/nvim-tree.lua/lua/nvim-tree/fs.lua:66: attempt to get length of field 'name' (a nil value)`

I suspect this has to do with commit 2a5d529219a6d8fef0dd7d52141f4647cc4a0d19.
```lua
 if node.entries ~= nil and node_is_open then
    add_into = utils.path_add_trailing(node.absolute_path)
  else
    add_into = node.absolute_path:sub(0, -(#node.name + 1))
  end
```
Line 66 is the body of the else block. I think the else block is being reached when it shouldn't be. The if statement should be reevaluated.

**Comment by kyazdani42** [comment]
fixed in `1.4.9` (8a1377f233)
