### ISSUE TITLE
Options seem to be ignored and broken icon rendering (since upgrading)

### ISSUE THREAD

**Issue by samtgarson** [kyazdani42/nvim-tree.lua#669]
I recently upgraded from an older version (pre 1.0 I think), and have migrated my setup (as best I can, not always sure which old options map to which new options from the docs).

Screenshot here shows:
- broken icons being displayed, even though icons have been turned off in `nvim_tree_show_icons`
- text colour seems to be broken completely

![image](https://user-images.githubusercontent.com/6242344/135486336-068dc7df-d5e5-4e8a-8935-f99057774667.png)

Relevant setup file: 
```lua
vim.g["nvim_tree_ignore"] = { '.git', 'node_modules', '.cache'  }
vim.g["nvim_tree_git_hl"] = "1"
vim.g["nvim_tree_highlight_opened_files"] = "1"
vim.g["nvim_tree_root_folder_modifier"] = "':~'"
vim.g["nvim_tree_width_allow_resize"] = "1"
vim.g["nvim_tree_group_empty"] = "1"
vim.g["nvim_tree_quit_on_open"] = "1"
vim.g["nvim_tree_icon_padding"] = " "
vim.g["nvim_tree_window_picker_exclude"] = {
  filetype = {'fugitive'},
  buftype = {'terminal'}
}

vim.g["nvim_tree_special_files"] = { 'README.md', '.env' }
vim.g["nvim_tree_show_icons"] = {
  git = 0,
  folders = 1,
  files = 0,
  folder_arrows = 0,
}

vim.api.nvim_set_keymap('n', '<C-n>', ':NvimTreeToggle<CR>', {noremap = true})
vim.api.nvim_set_keymap('n', '-', ':NvimTreeToggle<CR>', {noremap = true})
vim.api.nvim_set_keymap('n', '<leader>n', ':NvimTreeFindFile<CR>', {noremap = true})

vim.g["nvim_tree_icons"] = {
  git = {
    unstaged = "○",
    staged = "●",
    unmerged = "⊜",
    renamed = "⊙",
    untracked = "⊕",
    deleted = "⊗",
    ignored = "⊘"
  },
  folder = {
    arrow_open = "▾",
    arrow_closed = "▸",
    default = "▸",
    open =  "▾",
    empty = "▸",
    empty_open = "▾",
    symlink = "▸",
    symlink_open = "▾",
  },
  lsp = {
    warning = "⊗",
    error = "⊗",
  }
}

require'nvim-tree'.setup {
  open_on_setup = true,
  auto_close = true,
  opens_on_tab = false,
  update_focused_file = {
    enable = true
  },
  lsp_diagnostics = true
}
```

[The rest of my dot files can be found here](https://github.com/samtgarson/dotfiles/blob/master/dot_config/exact_nvim/lua/plugins/_nvim_tree.lua)

Hopefully I'm doing something obviously wrong with my config?

**Comment by gegoune** [comment]
```lua
vim.g.nvim_tree_icons = {
  default = '',
}
```

that should do it. Default icon was added recently.

**Comment by samtgarson** [comment]
Thanks! 

I've also realised the colours were broken because I had my `1`s in quotes during the migration to lua.

Thanks for the quick reply. This plugin is great but the recent breaking changes to the options without any docs or migration support made for a really frustrating user experience 😓

**Comment by gegoune** [comment]
There is no migrations guide, indeed, but changes and fact of transition taking place right now is mentioned in readme.

**Comment by kyazdani42** [comment]
see #674 now :)

**Comment by samtgarson** [comment]
@kyazdani42 great! 🙌
