### ISSUE TITLE
Opening new file sometimes override window options.

### ISSUE THREAD

**Issue by kyazdani42** [kyazdani42/nvim-tree.lua#67]
I found one bug with it. Looks like it overrides some things globally, for example `set number`. Here are steps to reproduce.

* Make sure you have `set number` in your init.vim
* Open up neovim
* do `:LuaTreeOpen`
* close the other empty window that's on the right, this leaves only nvim-tree
* Find some file, open it
* do `:LuaTreeOpen`, find some other file and open it in vertical split
* The new split window doesn't have numbers, but it should

_Originally posted by @kristijanhusak in https://github.com/kyazdani42/nvim-tree.lua/issues/57#issuecomment-663122440_

**Comment by kyazdani42** [comment]
@kristijanhusak i wonder if this is a bug upstream. I've tried to open a new window in many different ways, but neovim always keeps opening the window with the tree window options, although there are supposed to be set locally.
I really don't know how to address that issue, this is not documented enough, i will need to dig into neovim's codebase to find this and it might be painful and take some time.
If you, by any mean, know how to address that, please redirect me to the proper documentation ^^'

**Comment by kristijanhusak** [comment]
@kyazdani42 Maybe it's bug in `nvim_win_set_option`. Try using `setwinvar` function and see how it works out.
