### ISSUE TITLE
What happens with vim.g.nvim_tree_follow

### ISSUE THREAD

**Issue by ChavaTI** [kyazdani42/nvim-tree.lua#671]
I've updated the plugin and figured out that `vim.g.nvim_tree_follow` isn't exits anymore.
How can do to simulate its functionality? or How can I do to the tree follow the path of my current file?

**Comment by gegoune** [comment]
You need to run setup function: https://github.com/kyazdani42/nvim-tree.lua#setup

**Comment by kyazdani42** [comment]
closing because this is related to migration.
