### ISSUE TITLE
update_cwd not working as expected

### ISSUE THREAD

**Issue by caenrique** [kyazdani42/nvim-tree.lua#673]
When using `update_cwd = true`  I open a new tab and execute `:tcd some/other/dir`. This changes the root directory. Going back to the previous tab triggers the event `DirChanged` but the root of the tree doesn't update accordingly.

I looked into the code and found that the function `M.change_dir(name)` is the problem. it's not doing anything in the case that the variable `event.changed_window` is set, but why should this be the case?

the documentation for this variable:
```
DirChanged			After the |current-directory| was changed.
				Sets these |v:event| keys:
				    cwd:   current working directory
				    scope: "global", "tab", "window"
				    changed_window: v:true if we fired the event
				                    switching window (or tab)
```

I would expect that if `DirChanged` is triggered switching window or tab is because the user did `lcd` or `tcd` (which is my case)

Can this at least be configurable?

Thanks!

**Comment by kyazdani42** [comment]
hello !
i could not properly reproduce, the root is updating correctly when i run `tcd`. Could you share your configuration and add more detailed steps to reproduce this please ?

**Comment by caenrique** [comment]
yes, It updates when I run `tcd`. The problem is that when I switch back to my other tab, it doesn't update the tree root, and the reason for that is what I pointed out.

I'll try to describe it better:

1. You have neovim open in folder A (tab 1)
2. you open a new tab and run `tcd B` (tab 2)
    - The tree root updates to B
3. you switch back to tab 1
    - The `DirChanged` event gets triggered.
    - Expectation: tree root should be changed back to A
    - What happens: tree root still points to B

**Comment by kyazdani42** [comment]
ah i see. i'm not sure why this behavior was introduced to be honest :smile: the more code goes in there, the more test are missing :(
I'll take a look a this when i have some time

**Comment by kyazdani42** [comment]
If this confuses some people i'll revert. I think i might have introduced this behavior because some people don't want their path to be changing automatically.
