### ISSUE TITLE
netrw default options disables spell files downloads

### ISSUE THREAD

**Issue by aleprovencio** [kyazdani42/nvim-tree.lua#675]
Hello,
I have `spelllang=pt_br,en` which means that when the spell files are not found vim automatically downloads it.

When `nvim-tree`'s `netrw` options are on (which is the default behavior), that won't happen.

**Comment by kyazdani42** [comment]
try not setting `disable_netrw` maybe netrw manages spell files download. Nvim-tree doesn't do anything else than touching netrw variable, i believe this is unrelated to this plugin :)

**Comment by kuznetsss** [comment]
Just had this problem too and it took some time to figure out that nvim do use netrw to download spell files and where netrw is disabled in my config. Are you sure it's a good idea to have `disable_netrw = true` by default?

**Comment by kyazdani42** [comment]
I guess it could be changed

**Comment by crazyminecuber** [comment]
I had the same problem as well. I think you should change the default if it causes no other known problems.

**Comment by kyazdani42** [comment]
it should not i guess. I'll change it then
