### ISSUE TITLE
Now requires `:NvimTreeOpen` to function

### ISSUE THREAD

**Issue by ryleelyman** [kyazdani42/nvim-tree.lua#677]
My expected behavior when doing, e.g. `nvr ~/path/to/directory/` or `:e ~/path/to/directory/` is that nvim-tree will open in that directory. What actually happens currently is that a blank buffer appears. After running `:NvimTreeOpen`, things work as expected. I'm using the default config; updating nvim-tree seems to have caused this.

**Comment by kyazdani42** [comment]
fixed in (137628a) `1.4.15`
