### ISSUE TITLE
None of the NvimTree* commands work

### ISSUE THREAD

**Issue by phenax** [kyazdani42/nvim-tree.lua#678]
When I run `:NvimTreeOpen` -
```
E492: Not an editor command: NvimTreeOpen
```

When I run `:lua require'nvim-tree'.open()`, I get a blank buffer open as a split and this error -
```
E5108: Error executing lua ...e/pack/packer/start/nvim-tree.lua/lua/nvim-tree/view.lua:247: attempt to concatenate local 'move_to' (a nil value)
```

The last commit that I found that works for me is `71122d798482e30c599d78aa7ae4a756c6e81a79`

**Comment by gegoune** [comment]
Follow read me, there were changes in how this plugin has to be set up. You need to run 'setup' function now.

**Comment by kyazdani42** [comment]
see #674

**Comment by wookayin** [comment]
It was a surprising change to me as well, because previously the plugin worked out-of-box without lua `.setup{}` call (which I personally don't like about lua-based vim plugins). Following the migration guide #674 and REAMDE.md, I was able to make it work again.
