### ISSUE TITLE
Nvimtree does not open when opening a dir with nvim it show nothing

### ISSUE THREAD

**Issue by mohammad5305** [kyazdani42/nvim-tree.lua#679]
$ nvim code/
![Screenshot from 2021-10-02 14-04-54](https://user-images.githubusercontent.com/71145952/135712741-566c8e1e-276a-42d9-b9fc-53cd2b1ed416.png)

when I open up nvimtree it show up home directory unless I open him a few time and it gonna show cwd directory

![image](https://user-images.githubusercontent.com/71145952/135712662-5c3c54bf-9a6a-44d6-9249-f86213e51d1a.png)

I just set 
lua require'nvim-tree'.setup{}
in config nothing else

neovim 0.5v

**Comment by kyazdani42** [comment]
should be fixed in `1.4.14` (8dbba0c)

**Comment by mohammad5305** [comment]
> should be fixed in `1.4.14` ([8dbba0c](https://github.com/kyazdani42/nvim-tree.lua/commit/8dbba0c2c9bf423c1b1a8c71954432399e3abc6d))

oh yes thank you
