### ISSUE TITLE
Not aligning to Right side

### ISSUE THREAD

**Issue by AliNisarAhmed** [kyazdani42/nvim-tree.lua#683]
I updated, but now I cannot align the tree to the right side. 

I have set the `nvim_tree_side` property to 'right' in my `nvimtree.lua` file like shown below in the first screenshot. I also tried setting this field in my global `init.lua` file but still does not work (second screenshot)

Has this option been removed?

![image](https://user-images.githubusercontent.com/35175560/135768697-ef63992d-cac8-4de3-974c-52f707be58fe.png)

![image](https://user-images.githubusercontent.com/35175560/135768748-85d210dc-22d3-47f5-ae4b-c82034b245be.png)

**Comment by kyazdani42** [comment]
see #674 , this option has been moved inside the `setup` call now.
