### ISSUE TITLE
Some quality of life changes to default mappings

### ISSUE THREAD

**Issue by RaZ0rr-Two** [kyazdani42/nvim-tree.lua#685]
Go to the right side to open into a directory and left to go back (arrow keys or h,l).

```
  { key = {"<2-RightMouse>", "<C-]>", "l","<Right>"},    cb = tree_cb("cd") },
  { key = {"-","h","<Left>"},                            cb = tree_cb("dir_up") },
```

I am not sure why left and right cursor movement in the tree browser would be required . There's also the 

```
  { key = "y",                            cb = tree_cb("copy_name") },
  { key = "Y",                            cb = tree_cb("copy_path") },
  { key = "gy",                           cb = tree_cb("copy_absolute_path") },

```

to deal with any requirements needing file or folder path.

It would be great if this was made default

**Comment by kyazdani42** [comment]
i'd agree for the copy part, although i'd like to avoid forcing functions on basic vim moving around, it might be confusing.
