### ISSUE TITLE
nvimtree closes without checking whether file is saved

### ISSUE THREAD

**Issue by youdaniel** [kyazdani42/nvim-tree.lua#686]
If nvim tree is open and `:q` is done on an unsaved file, the file closes without the usual neovim prompt:
![image](https://user-images.githubusercontent.com/39450656/135872132-ccb7e0c3-8cab-4f32-97d1-937a8b8a7709.png)

Caused me to lose some work today—I'm not too sure if this is a bug or something I can fix in the configuration.

**Comment by kyazdani42** [comment]
i think this is not related to nvim-tree, i've disabled it and if you have 2 buffers open, you modify one and close it with `:q`, it does not ask for change. Could this be upstream ?

**Comment by youdaniel** [comment]
Hm, it didn't seem to do that for me. I've tried nvim without any configuration (except set hidden), and it seems to give me that prompt properly. 

Please see the video below for the issue I'm having. 

https://user-images.githubusercontent.com/39450656/135900149-2546a904-a41f-445f-b052-e233de020cb2.mp4

**Comment by kyazdani42** [comment]
oh because you have `g:nvim_tree_auto_close` enabled.

**Comment by gegoune** [comment]
I do have that too and was 'bitten' by this few times before. Is there no way for nvim-tree to not quit with unsaved buffers?

**Comment by kyazdani42** [comment]
there might be ways to achieve that, but this strangely looks like a bug from neovim to me because it shouldn't allow to close a window without asking when the buffer is not saved right ?
