### ISSUE TITLE
print or popup file path (improvement)

### ISSUE THREAD

**Issue by grimgort** [kyazdani42/nvim-tree.lua#687]
It would be great if we could have a keyboard shortcut to show the file name.  file names often overflow
![image](https://user-images.githubusercontent.com/44238325/135887806-f8040b70-84bd-44af-b929-8331327aba90.png)

Also, an option to activate a popup information window, like coc-explorer would be great.
coc-explorer : 
![image](https://user-images.githubusercontent.com/44238325/135887294-b30307c0-ab37-40d3-afc2-14b6d8780eaf.png)

**Comment by kyazdani42** [comment]
i thought about this, wouldn't be too hard to implement i guess.

**Comment by alex-courtis** [comment]
implemented!
