### ISSUE TITLE
FindFile does not work properly when switching between projects

### ISSUE THREAD

**Issue by gegoune** [kyazdani42/nvim-tree.lua#690]
Hey @kyazdani42, with two different buffers opened from different projects (so triggering `DirChanged` by project.nvim for example) nvim-tree (now) correctly updates its root when switching between buffers. Unfortunately it does not highlight the opened buffer after switching.

So basically:
1. Open buffer `a` in project `A`, open nvim-tree with `NvimTreeFindFile`, notice how it uncollapsed all folders containing file `a`
2. Open buffer `b` in project `B`, notice how nvim-tree updated with new root and showing uncollapsed folders containing file `b`
3. Switch back to buffer `a`, notice how root of nvim-tree has changed but all directories are collapsed now and no `a` file is highlighted.

Above assumes that both `a` and `b` are in subdirectories of their respective projects and 

```lua
vim.g.nvim_tree_group_empty = 1
vim.g.nvim_tree_respect_buf_cwd = 1
vim.g.nvim_tree_root_folder_modifier = ':t:r'

require('nvim-tree').setup {
  auto_close = true,
  lsp_diagnostics = true,
  update_cwd = true,
  update_focused_file = {
    enable = true,
    update_cwd = true,
  },
}
```

configuration is used.

**Comment by kyazdani42** [comment]
fixed in `1.5.3`
