### ISSUE TITLE
No file icons when lazy loading with Packer

### ISSUE THREAD

**Issue by cloudlena** [kyazdani42/nvim-tree.lua#694]
I'm installing this plugin with [Packer](https://github.com/wbthomason/packer.nvim). This works fine, and all the icons are displayed. However, if I install it in Packer with the following configuration added (i.e. if I add lazy loading of the plugin):

```lua
opt = true,
cmd = {'NvimTreeOpen', 'NvimTreeToggle'},
```

Somehow, the file icons are not displayed anymore. I didn't change anything else. The folder icons and the folder arrow icons are still there.

**Comment by Jarmos-san** [comment]
To clarify the situation a bit further, here's a couple of screenshots to show the context:

Here's what `nvim-tree.lua` looks like with the above lazy-loaded configurations:

![image](https://user-images.githubusercontent.com/31373860/136247342-7069b47a-4203-4b78-8acf-59a1da6aadc6.png)

What's preferable is something like this as showcased through `nvim-telescope`:

![image](https://user-images.githubusercontent.com/31373860/136247450-888d0b91-7c3c-450b-ba1e-677e79ad2ba3.png)

Just for heads up, in my case, `nvim-web-devicons` is also lazy-loaded.

**Comment by kyazdani42** [comment]
could you try not lazy loading nvim-web-devicons and tell me if this is still an issue ?

**Comment by pejax** [comment]
I am installing this plugin with Vim-Plug (no lazy loading) - same problem, the 'file' and 'link' icons do not display. Everything else from the nvim_tree_icons block (git, folder) works fine.

Thanks for providing the plugin!

**Comment by kyazdani42** [comment]
@pejax did you override the configuration for these ? also note that it's better to setup `vim.g` variables before requiring nvim-tree

**Comment by pejax** [comment]
I swapped setting variables and requiring nvim-tree. I think that did the trick.
Thanks

**Comment by alex-courtis** [comment]
Looks like this one can be closed.

It might be easier if I had permissions to close/label issues @kyazdani42 ;)

**Comment by kyazdani42** [comment]
indeed !
