### ISSUE TITLE
[Feature Request] NvimTree as floating window

### ISSUE THREAD

**Issue by DanielPower** [kyazdani42/nvim-tree.lua#697]
I often like to reference the file tree, or use it to quickly navigate between files that I know are close together. But I don't find it useful to have the tree always on the left. I have three issues, two are easy to solve, and the other not so much.

1. It takes up space on the left when I don't need it.
Solution: Modify bindings so it auto-closes when I open a file.

2. It's too small to show the full path if I'm nested deeply.
Solution: Set NvimTree's width to be wider.

3. It re-flows the widths of other splits when opening and closing.
Solution: Unknown

Proposal: Allow NvimTree to be used as a floating window, similarly to Telescope.
Workflow: Pressing a keybind would pop up a centered floating window like Telescope, but containing your file tree. Upon opening a file, the floating window would close.
Benefits:
- It takes up no space when you're not using it
- It can be as large as you like without squishing other splits
- It won't cause splits to re-flow on open/close

**Comment by DanielPower** [comment]
Thank you for your response. I'm aware of and stated the solutions to the first two problems. This feature request is only for the third problem.

**Comment by gegoune** [comment]
Ah, apologies, misread your 'Solution's are *desired* solutions.

**Comment by kyazdani42** [comment]
i think this has already been requested in #135 and #554

**Comment by alex-courtis** [comment]
Tracking in #135
