### ISSUE TITLE
Migration message messes with firenvim plugin 

### ISSUE THREAD

**Issue by LoydAndrew** [kyazdani42/nvim-tree.lua#698]
There is a an open issue about that in https://github.com/glacambre/firenvim/issues/1196 
Long echo message disables start of firenvim plugin.
Is there an option to suppress below message, as for me I've migrated to the new setup and this message is also obsolete for me. 
![Screenshot_2021-10-06_17-20-56](https://user-images.githubusercontent.com/28489428/136222089-e8865092-e945-4efa-90c0-afeb49ad1622.png)

**Comment by kyazdani42** [comment]
just remove the `g:` variables associated to this message and it should not appear anymore.
