### ISSUE TITLE
slow when scrolling through folders, comparing to defx

### ISSUE THREAD

**Issue by sandangel** [kyazdani42/nvim-tree.lua#7]
it pretty slow when I scrolling down/up (j/k) through folders, comparing to defx

**Comment by kyazdani42** [comment]
well defx has 2K lines of python code and 1K line of vim code, where this plugin has 1K of lua code, that i wrote quite fast and didn't really want to spend time on optimizations. I do not have any issues with performance on my end though, so feel free to open a PR if you want this fixed.
