### ISSUE TITLE
changing highlight group doesn't work

### ISSUE THREAD

**Issue by smartding** [kyazdani42/nvim-tree.lua#700]
I use packer.nvim and I have the following configuration for nvim-tree.lua.

I'm trying to change the highlight group `NvimTreeIndentMarker` and `NvimTreeFolderIcon` as shown in the config below, but it doesn't work.

I tried running the two highlight commands before calling `require('nvim-tree').setup()`, but that didn't work either.

Running those two highlight commands after starting neovim does work.

What's the correct way to change highlight group for nvim-tree.lua?

```lua
  use {
    'kyazdani42/nvim-tree.lua',
    requires = 'kyazdani42/nvim-web-devicons',
    config = function()

      vim.g.nvim_tree_git_hl = 1
      vim.g.nvim_tree_ignore = { '.git', '.github' }
      vim.g.nvim_tree_indent_markers = 1
      vim.g.nvim_tree_show_icons = {
        git = 0,
        folders = 1,
        files = 1,
        folder_arrows = 0,
      }

      local tree_cb = require'nvim-tree.config'.nvim_tree_callback

      require('nvim-tree').setup {
        hijack_cursor = true,
        update_focused_file = {
          enable      = true,
        },
        view = {
          mappings = {
            list = {
              { key = "<C-p>", cb = tree_cb("refresh") },
            }
          }
        }
      }
      -- colors
      vim.api.nvim_command("highlight! link NvimTreeIndentMarker Directory")
      vim.api.nvim_command('highlight! link NvimTreeFolderIcon Directory')

      -- key mapping
      vim.api.nvim_set_keymap('n', '<F3>', "<cmd>lua require('nvim-tree').toggle()<CR>", { noremap=true, silent=true })

    end
  }
```

**Comment by kyazdani42** [comment]
did you manage to fix it ? if not, can you print the output of `highlight NvimTreeIndentMarker` after setting it ?

**Comment by smartding** [comment]
@kyazdani42 
I fixed it. It's not a issue of nvim-tree.lua
It turned out that those highlight commands sometimes don't work if I put the `colorscheme gruvbox` command in the config function of my color scheme plugin as below:
```lua
  use {
    'gruvbox-community/gruvbox',
    config = function()
      vim.api.nvim_command('colorscheme gruvbox')
    end
  }
```
The highlight commands work if I just put the `colorscheme gruvbox` command in `init.vim`.

Not sure why, but it's working.

**Comment by msva** [comment]
I've strange issue too: setting `NvimTreeFolderName` or any other `*Folder*` (and non `Icon`) groups works fine, but exactly `NvimTreeFolderIcon` have no effect, and folder icons are always have same color with folder names...

**Comment by msva** [comment]
Well, actually, looks like another thing is related here: if I redefine `NvimTreeSpecialFile` group, file's icon color also changes to defined in that group :shrug:
