### ISSUE TITLE
Dim nvim-tree when inactive

### ISSUE THREAD

**Issue by dbarrosop** [kyazdani42/nvim-tree.lua#704]
Hello,
first of all, this plugin is great :)

I have the following configuration to dim inactive panes:

```
vim.cmd([[
	hi ActiveWindow guibg=#191919
	hi InactiveWindow guibg=#282828
]])

vim.o.winhighlight = "Normal:ActiveWindow,NormalNC:InactiveWindow"
```
So I was wondering if it would possible to support NormalNC in this plugin so it dims automatically.

Thanks for this great plugin :)

**Comment by kyazdani42** [comment]
could you try https://github.com/kyazdani42/nvim-tree.lua/pull/705 and tell me if it works for you ?

**Comment by dbarrosop** [comment]
Yeah, you are right, that was the signcolumn, but it should followed the dimness too. I played a bit with this and I found that the problem seems to be the line `'SignColumn:NvimTreeNormal'`. If I remove that line it works as expected:

<img width="830" alt="Screenshot 2021-10-09 at 09 15 03" src="https://user-images.githubusercontent.com/6246622/136648327-4e1bb21f-cc75-417c-99a8-a94b3acd2b90.png">
