### ISSUE TITLE
disable dim nvim-tree when inactive

### ISSUE THREAD

**Issue by petertriho** [kyazdani42/nvim-tree.lua#709]
Hi,
https://github.com/kyazdani42/nvim-tree.lua/pull/705
This added the dim feature. Is there a way to disable this? I tried adding 
```
vim.cmd("autocmd FileType NvimTree setlocal winhighlight Normal:NormalSB,NormalNC:NormalSB,SignColumn:SignColumnSB")
```
but that didn't seem to do the trick.

I'm using tokyonight and it darkens the background of sidebars which is removed when inactive due to this change
![image](https://user-images.githubusercontent.com/7420227/136654800-dd8b224e-f57b-4514-a752-58a8169219a2.png)
![image](https://user-images.githubusercontent.com/7420227/136654805-a15f57f6-f76a-4264-ae60-98bfbcb22164.png)

Thanks!

**Comment by kyazdani42** [comment]
you should be able to set `NvimTreeNormalNC` to `Normal` or disable it now

**Comment by petertriho** [comment]
thank you `vim.cmd("highlight! default link NvimTreeNormalNC NormalSB"` worked
