### ISSUE TITLE
Unable to use :read <url>, or open a file using nvim <url>

### ISSUE THREAD

**Issue by Kranzes** [kyazdani42/nvim-tree.lua#718]
If i remember correctly opening/reading a file from a url requires netrw, which disabling it is currently impossible using the latest commits from master, the options that worked before to re-enable netrw no longer take effect.

**Comment by kyazdani42** [comment]
update_to_buf_dir   = {
    enable = true,
    auto_open = true,
  },
  you can disable this feature if you wish to use netrw to navigate.

**Comment by dylanpjx** [comment]
Am encountering the same issue

**Comment by cristian-heredia** [comment]
Same, the [GBrowse](https://github.com/tpope/vim-rhubarb) command from fugitive no longer works. 
```shell
Netrw not found. Define your own :Browse to use :GBrowse 
```

**Comment by kyazdani42** [comment]
@cristian-heredia you need to set `disable_netrw` to false in your config.
@Kranzes @dylanpjx can you share you config ? It should not hijack netrw if hijack_netrw and disable_netrw are false

**Comment by dylanpjx** [comment]
My initial config: 
```
require'nvim-tree'.setup {
  disable_netrw = false,
  hijack_netrw = false
}
```

Adding 
```
  update_to_buf_dir   = {
    enable = false,
    auto_open = false,
  },
```
fixed the issue as per your previous comment.

I encountered the issue when I ran `nvim dir`.

**Comment by kyazdani42** [comment]
update to buf dir will now be disabled if netrw is not at least hijacked :)

**Comment by cristian-heredia** [comment]
@kyazdani42 thanks for the suggestion, I'm getting the same error

```vim
let g:nvim_tree_window_picker_exclude = {
    \   'filetype': [
    \     'notify',
    \     'packer',
    \     'startify'
    \   ],
    \   'buftype': [
    \     'terminal'
    \   ]
    \ }
let g:nvim_tree_respect_buf_cwd = 1

nnoremap <C-n> :NvimTreeToggle<CR>
nnoremap <leader>n :NvimTreeFindFile<CR>

" a list of groups can be found at `:help nvim_tree_highlight`
highlight NvimTreeFolderIcon guibg=bluer

lua require'nvim-tree'.setup{disable_netrw = false, hijack_netrw = false}
  
```

**Comment by kyazdani42** [comment]
cannot reproduce i'm afraid, i can call GBrowse with your config.
