### ISSUE TITLE
Show git icons in files to the right as folders

### ISSUE THREAD

**Issue by stsewd** [kyazdani42/nvim-tree.lua#72]
![Screenshot from 2020-08-02 12-02-31](https://user-images.githubusercontent.com/4975310/89128024-11725d00-d4b8-11ea-88ea-5cb334439f17.png)

Folders show the git icon to the right, I'd like to do the same for files. I don't think there is a way to do that right now, so it would be a new setting

**Comment by kyazdani42** [comment]
there is a PR that will be merged soon.

**Comment by kyazdani42** [comment]
duplicate of #65

**Comment by kyazdani42** [comment]
i think i was wrong, the PR will only align icons to the left an not the right. If this is enough for you just close this, otherwise we'll make a PR to address this issue when we have some time.

**Comment by alex-courtis** [comment]
Following request in #246
