### ISSUE TITLE
opening a dir with nvim doesnt update cwd for the first time

### ISSUE THREAD

**Issue by siduck** [kyazdani42/nvim-tree.lua#720]
I have netrw disabled and nvim-tree lazy loaded with the following cmd : 
```
cmd = { "NvimTreeToggle", "NvimTreeRefresh"} 
```
Whenever I open a dir with nvim , ex : nvim dirname  , and then toggle nvimtree , the cwd doesnt update for the first time.

https://user-images.githubusercontent.com/59060246/137235149-13bc3135-e697-4a38-bd2f-9f58c3300d6d.mp4

I do have    update_cwd = true in my nvimtree setup!

**Comment by siduck76** [comment]
@kyazdani42 

https://paste.sh/DZnzL_MT#KpXmD28Ijn27cqjM1_Hhdvuy

**Comment by kyazdani42** [comment]
should be fixed
