### ISSUE TITLE
layout breaking on a specific file

### ISSUE THREAD

**Issue by arthurgehrke** [kyazdani42/nvim-tree.lua#724]
I'm trying to figure out what's causing this issue. 

![bug](https://user-images.githubusercontent.com/49957080/137374631-7a58633d-08c2-4086-8101-0505c6454bb2.png)
![image](https://user-images.githubusercontent.com/49957080/137374708-bd5b4f07-75c4-4196-b40e-dfa5e4f0f9d3.png)
![image](https://user-images.githubusercontent.com/49957080/137374865-f22b8045-dd7b-4125-bbb9-e01d1b9675a5.png)
Even using half screen 
![image](https://user-images.githubusercontent.com/49957080/137374952-3886c7d6-59fe-43bf-a314-a6e62993a6de.png)

**Comment by kyazdani42** [comment]
i think this might be due to some config option you have in your neovim configuration. But i cannot help you without more information :)

**Comment by kyazdani42** [comment]
hi, sorry for the late answer.
Did you manage to fix this issue ?

**Comment by kyazdani42** [comment]
@arthurgehrke ping

**Comment by alex-courtis** [comment]
@arthurgehrke Please try to replicate using the minimal configuration from the new bug report form: https://github.com/kyazdani42/nvim-tree.lua/issues/new/choose

That should allow you to easily add your configurations/plugins until you find something that is causing this.

**Comment by kyazdani42** [comment]
closing since no news, maybe with a better issue description it would help. Also this look strangely similar to another issue that was closed the other day.
