### ISSUE TITLE
Cant install nvim-tree & icons

### ISSUE THREAD

**Issue by Nils75owo** [kyazdani42/nvim-tree.lua#737]
I use vim-plug as my plugin manager and i added these lines at the bottom,
```
Plug 'kyazdani42/nvim-web-devicons' "for file icons
Plug 'kyazdani42/nvim-tree.lua' "nvimtree
```
ran `:PlugInstall`
and added 
```
lua require'nvim-web-devicons'.setup()
lua require'nvim-tree'.setup()
```
to my init.vim
and im getting the file not found error from lua

```
E5108: Error executing lua [string ":lua"]:1: module 'nvim-web-devicons'
 not found...

E5108: Error executing lua [string ":lua"]:1: module 'nvim-tree' not fou
nd...
```
on startup

my nvim version is v0.6.0-dev
and lua version 5.1.5

**Comment by mustafaergul** [comment]
@Nils75owo could you please give more about the config that you are using for the workaround? I am having the same issue and need to find out where and how to call these two plugins. Thanks

**Comment by Nils75owo** [comment]
@mustafaergul No sorry. I just ended up rewriting my entire config in lua and switching to packer. Now everything works fine.

**Comment by alg** [comment]
@mustafaergul In your init.lua place (recommended) initialization **after** "plug#end" call (not after the "Plug").
