### ISSUE TITLE
Add view to show open buffers only

### ISSUE THREAD

**Issue by cseickel** [kyazdani42/nvim-tree.lua#744]
I have this idea I'd like to implement, which is to have a file explorer which can be toggled between showing all files and only the files which are currently open. The purpose of this is to provide a good representation of the workspace for the current task you are focused on, both as a visual reminder and a way to switch buffers.

This an alternative to showing buffers as tabs (which I find confusing for some reason) or having a flat list of buffers that can be referenced on command with BufExplorer or :ls.  I have also tried leaving all my buffers open in small splits, but I don't always have the space for this. I think the best way to list your open buffers is as a vertical tree within their folder structure.

The workflow would be to:

1. show the full tree, 
2. open a few files, 
3. toggle back to "Open Buffers Only" mode
4. as buffers are opened via Go to Definition, Find References, Telescope, etc, they are added to the "Open Buffers Only" view
4. work...
5. occasionally jump to nvim-tree sidebar to switch buffers
5. toggle back to "All Files" mode to browse and open another file via folder navigation
6. back to "Open Buffers Only" mode
7. work...

I would be willing to code this and put in a PR. My questions are:

1. Are you interested in having this as a feature?
2. I gathered from other issues that there is a lot of refactoring going on right now, should I work off of a particular branch or wait for something else to be completed?
3. Any advice on the best way to go about this? I was thinking about injecting an if clause to filter the tree just before it renders if a flag is set from the toggle function.

**Comment by alex-courtis** [comment]
@cseickel any progress on your PR?

**Comment by cseickel** [comment]
Sorry @alex-courtis, I abandoned that PR and ended up creating my own tree plugin instead.

**Comment by alex-courtis** [comment]
Closing as it is covered by #1056

**Comment by x0y-gt** [comment]
I have searched in the docs and some PRs but unable to find how can I filter and see only the opened files?

**Comment by gegoune** [comment]
`:h nvim-tree.filters`

**Comment by rofrol** [comment]
`vim.api.nvim_exec('Neotree focus buffers left', true)`

https://github.com/nvim-neo-tree/neo-tree.nvim/wiki/Recipes#switch-between-filesystem-buffers-and-git_status

**Comment by resoliwan** [comment]
:h nvim-tree.filters.no_buffer

Just press B.

**Comment by x0y-gt** [comment]
Thanks @resoliwan ! 
But how did you know? can't find it in the help menu

**Comment by gegoune** [comment]
It's documented: `:h nvim-tree-opts-filters`.

**Comment by resoliwan** [comment]
```
*nvim-tree.filters.no_buffer*
Do not show files that have no |buflisted()| buffer.
Toggle via |nvim-tree-api.tree.toggle_no_buffer_filter()|, default `B`
For performance reasons this may not immediately update on buffer
delete/wipe. A reload or filesystem event will result in an update.
  Type: `boolean`, Default: `false`
```
