### ISSUE TITLE
NvimTree not working after migrating to setup function

### ISSUE THREAD

**Issue by jhoyospsh** [kyazdani42/nvim-tree.lua#748]
Hi everyone so after updating the setup function follwing the readme I'm receiving this error and when trying to run NvimTreeToggle I'm receiving an error "Not an edit command: NvimTreeToggle"

Every time I open neovim i receive the following error

```
[NvimTree] following options are now set in the setup (:help nvim-tree.setup): nvim_tree_auto_close | nvim_tree_update_cwd | nvim_tree_lsp_diagno
stics
```
Is there anything I'm doing wrong? I already set the options so I don't know what else should I been doing

If there is any extra information I should give you to help me with this error please let me know

**Comment by kyazdani42** [comment]
you might need to remove the leftover configuration options from your old config that are printed in this message.

**Comment by kyazdani42** [comment]
closing since no news, tell me if you need some help
