### ISSUE TITLE
nvim_tree_ignore doesn't work

### ISSUE THREAD

**Issue by ahhshm** [kyazdani42/nvim-tree.lua#752]
By adding this line to my init.vim I expected not to see some folders in nvim_tree, but it doesn't apply:
`let g:nvim_tree_ignore = ['.git', 'node_modules', '.cache', '.next']`
 
I even added this line that hides dotfiles, but it doesn't work too:
let g:nvim_tree_hide_dotfiles = 1

I've been using an old version of nvim_tree, and everything worked perfectly, but I recently updated the plugin, and it doesn't work. What's the problem?

**Comment by kyazdani42** [comment]
did you by any chance set the option after a `require'nvim-tree'` ? This might cause the plugin to work unexpectedly, since the refactoring is not yet complete there are some weird behaviors.

**Comment by ahhshm** [comment]
Thank you. I set the options after the `require('nvim_tree')`, and by placing them before the `require,` it works perfectly. 

So I close this issue :)
