### ISSUE TITLE
Can't open files from Tree

### ISSUE THREAD

**Issue by rampus-bit** [kyazdani42/nvim-tree.lua#753]
My tree was working perfectly, and then upon updating, it stopped functioning. I can only open it and look at the contents of a directory, but not actually open files.

My custom settings also seem to be ignored after the update.

**Comment by kyazdani42** [comment]
could this be fixed if you follow #674 ?

**Comment by msva** [comment]
I had same problem, and unfortunatelly, not, it doesn't **really** fix by migration of options.

if I have `update_to_buf_dir=false` then there is unneded empty buffer remains after nvim-tree opens the file.
And if I set it to `true`, `nvim-tree` fails to open the file (my suggestion is that it don't create the buffer for it somewhy).

I kinda avoided it by setting `update_to_buf_dir` to `false` and adding `bwipeout` to `VimEnter` autogroup.

**Comment by kyazdani42** [comment]
no followup on this, closing. @msva the empty buffer was fixed in the latest version
