### ISSUE TITLE
icons keep showing even when configured to hide

### ISSUE THREAD

**Issue by andykais** [kyazdani42/nvim-tree.lua#754]
setting the following config turns off some icons but others stay turned on. 

```lua
require('packer').startup(function(use)
  use { 'kyazdani42/nvim-tree.lua', requires = { 'kyazdani42/nvim-web-devicons' } }
end)

require('nvim-tree').setup()
vim.g.nvim_tree_show_icons = {
  git = 0,
  folders = 0,
  files = 0,
  folder_arrows = 0,
}
```
this is a screenshot before turning off icons
![screenshot(731)](https://user-images.githubusercontent.com/6627147/139167229-d33111a1-4f85-44e5-859b-cb92604bb876.png)

this a screenshot with the `nvim_tree_show_icons` turned off
![screenshot(732)](https://user-images.githubusercontent.com/6627147/139167354-0649f8f3-2e84-4556-a45f-8edfd4c01ba8.png)

I want to know if its possible to turn off _all_ icons (all the `[]` boxes are icons that are not a part of my current font)

**Comment by kyazdani42** [comment]
yes please put the `vim.g.nvim_tree_show_icons` before the `require'nvim-tree'` :)

**Comment by andykais** [comment]
perfect. This works. Thanks!
