### ISSUE TITLE
Few minor improvements

### ISSUE THREAD

**Issue by kristijanhusak** [kyazdani42/nvim-tree.lua#76]
Hey,

i really like the state of the plugin right now, it's really great. I'm completely switched to it.
I want to suggest few more improvements. Will work on them myself, just want a confirmation from your side:

1. Allow multiple keys for single action
I'm used to using `o` for open action, but sometimes I also try to use `<CR>`. Currently I can map only one of these.

2. Show current cwd at top
When I work on similar projects, sometimes i forget in which folder I am. Having the info at top (beside the `..`) would help. I'm aware that this will require changing all if checks where we have `if node.name == '..' then return end`, but it should not be a complicated change.

**Comment by kyazdani42** [comment]
Hey,
i'm completely for these if you wish to implement them, go for it :)

**Comment by kristijanhusak** [comment]
Implemented.
