### ISSUE TITLE
B is laggy

### ISSUE THREAD

**Issue by mkubasz** [kyazdani42/nvim-tree.lua#765]
After a recent update, while pushing the button on my keyboard "B", I have one big lag.
I checked and this plugin makes it.

**Comment by msva** [comment]
there is no mapping like `B` in `nvim-tree`

**Comment by mkubasz** [comment]
@msva When I enable nvim-tree normal b(back) is laggy :) I tried settings to optimize git, but it does not help.

**Comment by kyazdani42** [comment]
not sure what nvim-tree does have to do with that, as @msva said, there is not `B` mapping. Your issue might come from another plugin.
