### ISSUE TITLE
Neovim freezes (keybindings and  mode stops working) after installing nvim-tree

### ISSUE THREAD

**Issue by paridhi089** [kyazdani42/nvim-tree.lua#766]
So whenever I ` require('nvimtree-config')`  in my main `init.lua`, My neovim freezes after I quit it and start it again.  The navigation keys, Mode keys etc stops working. 

Once I remove the ` require('nvimtree-config`)`  or delete the nvim-tree lua folder from Packer folder, It starts Working again. Here is a link to my [configuration file](https://gitlab.com/TheDykeWhoLovesSwords/dot-files/-/tree/master/.config/nvim). Hope it helps you recreate the issue.

**Comment by VolkovIlia** [comment]
The same issue, <C + c> disable "some process" that make nvim freeze.

**Comment by kyazdani42** [comment]
require('nvimtree-config') is invalid. If you wish to import the config module, you need to `require('nvim-tree.config')`.
Note that this might break initialization if you don't call setup first.
