### ISSUE TITLE
E492: Not an editor command: NvimTreeToggle

### ISSUE THREAD

**Issue by antz22** [kyazdani42/nvim-tree.lua#767]
Hi, I use nvim-tree.lua (which is an awesome plugin!) on my arch linux desktop on neovim 0.5+, but I ran into an issue after not updating all of the neovim plugins for awhile.

I use nvim-tree with a .lua config file, and after updating nvim-tree to the latest version using vim-plug, when I try to use NvimTreeToggle vim tells me this: "E492: Not an editor command: NvimTreeToggle"

I am not really sure if I am missing something here. Apologies if I have not provided enough information, let me know if that is the case.

Here is a screenshot.

![2021-11-04_17-02](https://user-images.githubusercontent.com/59377837/140419690-d045dafc-4cb1-42ed-95a9-156122aeda42.png)

Here is the code for my nvim-tree config.

```lua
vim.g.nvim_tree_hide_dotfiles = 1
vim.g.nvim_tree_indent_markers = 1 
vim.g.nvim_tree_icons = {
    default = '',
    symlink = '',
    git = {
        unstaged = "",
        staged = "✓",
        unmerged = "",
        renamed = "➜",
        untracked = ""
    },
    folder = {
        default = "",
        open = "",
        empty = "",
        empty_open = "",
        symlink = ""
    }
}

vim.cmd("hi NvimTreeFolderIcon guifg = #61afef")
vim.cmd("hi NvimTreeFolderName guifg = #61afef")
vim.cmd("hi NvimTreeIndentMarker guifg=#545862")

vim.o.termguicolors = true 

require'nvim-tree'.setup {
  disable_netrw       = true,
  hijack_netrw        = true,
  open_on_setup       = true,
  ignore_ft_on_setup  = {},
  update_to_buf_dir   = {
    enable = true,
    auto_open = true,
  },
  auto_close          = false,
  open_on_tab         = false,
  hijack_cursor       = false,
  update_cwd          = false,
  diagnostics         = {
    enable = false,
    icons = {
      hint = "",
      info = "",
      warning = "",
      error = "",
    }
  },
  update_focused_file = {
    enable      = false,
    update_cwd  = false,
    ignore_list = {}
  },
  system_open = {
    cmd  = nil,
    args = {}
  },
  view = {
    width = 30,
    height = 30,
    side = 'left',
    auto_resize = false,
    mappings = {
      custom_only = false,
      list = {}
    }
  }
}

```

**Comment by elspecal** [comment]
Same issue here, using packer.nvim. None of the nvim-tree commands are recognised.

**Comment by kurtpeniket-ggapps** [comment]
I'm also having this issue, I have a similar setup to you @antz22.

**Comment by blqn** [comment]
I am facing same issue.

**Comment by queensferryme** [comment]
I think you need to `nvim_tree_hide_dotfiles` -> `filters.dotfiles`, check out #674.

**Comment by antz22** [comment]
I just tried the config with commenting out all vim.g commands and I get the same issue.

**Comment by CleoMenezes** [comment]
You can put it into your init.vim after nvim-tree loaded:

`lua require'nvim-tree'.setup {}`

**Comment by kurtpeniket-ggapps** [comment]
> You can put it into your init.vim after nvim-tree loaded:
> 
> `lua require'nvim-tree'.setup {}`

This worked for me, thanks @CleoMenezes !

**Comment by mrLuisFer** [comment]
> You can put it into your init.vim after nvim-tree loaded:
> 
> `lua require'nvim-tree'.setup {}`

This worked for me too, thx @CleoMenezes ;D

**Comment by elspecal** [comment]
> You can put it into your init.vim after nvim-tree loaded:
> 
> `lua require'nvim-tree'.setup {}`

Same here. Solved my issue too

**Comment by antz22** [comment]
Unfortunately I am getting another error with RainbowParentheses. I will open another issue and close this one. Thanks @CleoMenezes!

**Comment by kirillbobyrev** [comment]
Sorry for bumping the thread: calling `require'nvim-tree'.setup()` in `init.lua` after the plugin is load seems like a strange solution. Why doesn't `config = function() require'nvim-tree'.setup() end` that is recommended in the README does not work from within `packer` startup?

**Comment by duydang2311** [comment]
I configure `nvim-tree` in an external lua file `nvim-tree.lua` and include it in my `init.vim`. I have no clue why it isn't set up.
Turns out the file name `nvim-tree.lua` is identical with `nvim-tree` itself, and that's why including the external configuration file does not work as intended. The solution is just to rename the lua file.
Again, sorry for bumping the thread, but I notice that the author had the same mistake as mine.

**Comment by kyazdani42** [comment]
woups completely missed this issue. yes you should avoid calling a file with the same name as a plugin you are using. Also lazy loading the plugin works just fine since a month or two :)

**Comment by ssoteloserrano** [comment]
I noticed that actually nvim-tree appears to work after calling `require'nvim-tree'.setup()` due to an error in the setup. In my case I was trying to assign a resource that wasn't loaded. Also it was very useful for me to read about the nvim tree commands with: `:help nvim-tree-commands`

**Comment by simohauml** [comment]
> You can put it into your init.vim after nvim-tree loaded:
> 
> `lua require'nvim-tree'.setup {}`

This works for windows terminal. However, in my WSL2 Ubuntu, nvim load with error:
`
Error detected while processing /home/adminl/.config/nvim/init.vim:
line   13:
E5105: Error while calling lua chunk: ...onfig/nvim/plugged/nvim-tree.lua/lua/nvim-tree/utils.lua:12: attempt to index field 'fn' (a nil value)
`

**Comment by alex-courtis** [comment]
> This works for windows terminal. However, in my WSL2 Ubuntu, nvim load with error:
> `Error detected while processing /home/adminl/.config/nvim/init.vim: line 13: E5105: Error while calling lua chunk: ...onfig/nvim/plugged/nvim-tree.lua/lua/nvim-tree/utils.lua:12: attempt to index field 'fn' (a nil value)`

That's no good...

Which version of neovim are you running? 0.7.0 is the minimum supported.

It could also be a problem with your plugin manager.

Please attempt to run with a clean nvt-min.lua as per the [bug report](https://github.com/nvim-tree/nvim-tree.lua/issues/new?assignees=&labels=bug&template=bug_report.yml) form. That may indicate if it is a plugin manager problem or a neovim version.

**Comment by josearmandojacq** [comment]
> You can put it into your init.vim after nvim-tree loaded:
> 
> `lua require'nvim-tree'.setup {}`

If you are using lua -> `init.lua`
Just add it as `require'nvim-tree'.setup {}`

**Comment by Applicafroguy** [comment]
Check Neovim version, I was on v0.7. the new version supports v0.8. so I just updated Neovim and it worked.

**Comment by 3009aksingh** [comment]
How did you updated to v0.8, I used the ppa method but the max I could get to is NVIM v0.7.2. Please help.

**Comment by alex-courtis** [comment]
> How did you updated to v0.8, I used the ppa method but the max I could get to is NVIM v0.7.2. Please help.

I'm not familiar with PPA however it seems that there may be several different packages for neovim: https://launchpad.net/ubuntu/+ppas?name_filter=neovim https://launchpad.net/ubuntu/+ppas?name_filter=nvim

Perhaps you could use a different PPA package that contains the stable neovim 0.8

Perhaps you could use an official ubuntu package. On arch linux, the official neovim package is 0.8.

**Comment by sarunmrzn** [comment]
> Sorry for bumping the thread: calling `require'nvim-tree'.setup()` in `init.lua` after the plugin is loaded seems like a strange solution. Why does `config = function() require'nvim-tree'.setup() end` (that is recommended in the README) not work from within `packer` startup?

For me the issue was I was using on_attach method that was previously a hack to get around with a particular update, I removed the 'on_attach' function solved the issue.
