### ISSUE TITLE
when i try to open a folder in nvim as the nvim-tree hijacks the netrw but lsp gives me error

### ISSUE THREAD

**Issue by imSafdarAwan** [kyazdani42/nvim-tree.lua#768]
i know this is an lsp config error but doe's anybody know how to solve this whenever i open a folder from terminal in nvim it gives me this error 
![image](https://user-images.githubusercontent.com/87114084/140597796-6970271c-7d0f-47f7-8dd1-cc787a0c7476.png)
could any body help me to solve this
nvim tries to parse the nvimtree buffer to lsp so it gives me this error how can i ignore this behaviour

**Comment by kyazdani42** [comment]
nothing to do with nvim-tree :smile: closing

**Comment by kyazdani42** [comment]
You might have an issue in your lsp config, but the tree should never be sent to the lsp anyway (it doesn't match any valid filetype)
