### ISSUE TITLE
Termux

### ISSUE THREAD

**Issue by CanKolay3499** [kyazdani42/nvim-tree.lua#769]
Hi, I'm rewriting my neovim config with lua. Before using nvim tree I can create files/folders successfuly in the nerdtree but now I cant create files with nvimtree 
![Screenshot_20211106-135539_Termux](https://user-images.githubusercontent.com/80613396/140607194-fd833c29-e541-4091-88d0-7fa776c0d41a.jpg)

**Comment by kyazdani42** [comment]
hum this might be quite hard for me to reproduce :smile: not sure where to look, and debugging on mobile would be a nightmare.

**Comment by CanKolay5677** [comment]
Can you write some code that won't create `/data/data` folder in android? Because android wont allow to access `/data/data` folder without root.

![Screenshot_20211127-154731_Termux](https://user-images.githubusercontent.com/80613396/143681897-e2e24687-6d32-47a7-8273-6dd295dc6d1f.jpg)

**Comment by kyazdani42** [comment]
as you are able to test this, i'd suggest you to write the code in this case :)

**Comment by CanKolay5677** [comment]
I'm searching for that but I found this code in `fs.lua`

```lua
local success = luv.fs_mkdir(path_to_create, 493)```

What is 493 mean?

**Comment by HONESTFLY** [comment]
can you help me

**Comment by Ae-Mc** [comment]
Same problem

**Comment by Ae-Mc** [comment]
@CanKolay3499 I created fork and fixed the issue. You can use it for now until pull request not merged.
