### ISSUE TITLE
[Feature Request] Use a function to set up window width

### ISSUE THREAD

**Issue by queensferryme** [kyazdani42/nvim-tree.lua#770]
This is what I am doing currently. I want the nvim-tree's window width to be adaptive, and percentage is not working greatly -- e.g. `20%` is too much on a larger screen and too narrow on a smaller screen.

```lua
vim.cmd [[autocmd VimResized * lua require'nvim-tree.view'.View.width=NvimTreeWidth()]]
function NvimTreeWidth()
    local winwidth = vim.fn.winwidth(0)
    if winwidth <= 100 then
        return 30
    elseif winwidth <= 200 then
        return 40
    else
        return 50
    end
end

require'nvim-tree'.setup {
    --- ...
    view = {
        width = NvimTreeWidth(),
    },
}
```

I am not sure if this is technically feasible, but it would be nice to support passing a custom function to set up width like:
```lua
require'nvim-tree'.setup {
    --- ...
    view = {
        width = function()
            --- ...
        end,
    },
}
```

> BTW, `nvim-tree.lua` is really wonderful. Thank you for your work!

**Comment by queensferryme** [comment]
This shouldn't be too hard I believe?

https://github.com/kyazdani42/nvim-tree.lua/blob/fd3969ec986d739d9ab01b8ec5de051c45b475d2/lua/nvim-tree/view.lua#L247-L249

We can simply do something like:
```lua
if type(size) == "number" then 
   return size 
elseif type(size) == "function" then
  return size()
end
```
I would like to submit a PR implementing this if you @kyazdani42 find this proposal acceptable :)

**Comment by kyazdani42** [comment]
go for it :)

**Comment by queensferryme** [comment]
> go for it :)

Thanks! PTAL #848 👈

**Comment by 1478zhcy** [comment]
I using the following function to set up the window width,
```lua
width = function()
  local winwidth = vim.fn.winwidth(0)
  if winwidth <= 100 then
    return 30
  elseif winwidth <= 200 then
    return 40
  else
    return 50
  end
end,
```
but, it seems that the value of `winwidth` will always be 40 in any case, so the function always returns 30.

**Comment by kyazdani42** [comment]
winwidth will hardly be over 100 because it's the size of the window you pass as parameter, if you wish to get the width of neovim, you should do use `vim.go.columns` to get the number of columns.

**Comment by 1478zhcy** [comment]
Thanks a lot.
