### ISSUE TITLE
[feature request] possibility to easily avoid loading nvim-tree when it is not needed

### ISSUE THREAD

**Issue by msva** [kyazdani42/nvim-tree.lua#772]
It would be nice to have a way to tell `nvim-tree` to not load even in background when it is not needed (when `vim` was called to directly open file, and `nvim-tree` bufer didn't manually called by user).

It could help in some situations including following:
- you open a file living in big `git` repo, that have a bunch of index modifications, outdated from remote HEAD, and remote server is SLOOOOOOOW. In this situation vim takes eternity to load because of tons git calls under the hood.
- you trying to open remote file/directory (`netrw` kingdom since `nvim-tree` looks like don't support any remote activity). In this situation `nvim-tree` conflicts with netrw in many ways, and user will suffer either of disabling `netrw` (no remote functionality) or it's conflicts with `nvim-tree` if user will decide keep `netrw` enabled.

**Comment by gegoune** [comment]
I am pretty sure it will be up to user to call setup function whenever they want once all configuration variables are migrated to setup function. I really recall seeing @kyazdani42 mentioning it at some point.

**Comment by msva** [comment]
that way pretty badly covers the situation when user needs to have possibility to call NvimTreeToggle in runtime, but don't want nvim-tree to mangle with buffers before that.

To get this user will need to write custom function that will call setup first, and then call Toggle, and map that to key, instead of just mapping toggle there :)

**Comment by kyazdani42** [comment]
i'm aware initialization is not perfect. For now you could just lazy load the plugin.
> since nvim-tree looks like don't support any remote activity
not sure why you suppose that, it works fine using sshfs

**Comment by msva** [comment]
> using sshfs

Actually, that is is what I want to avoid: to mount all the remote hosts I can edit files on with sshfs. And add new one every time I get access to every new one...

with netrw it is possible to just `nvim {scp,sftp,https,whatever}://host/path` wthout pre-mounting anything..

And, actually issue itself is about not-loading nvimtree (well, actually, mostly about not-creating nvim-tree buffer) when `nvim` was used to open fle directly.

**Comment by kyazdani42** [comment]
@msva i see what you mean now, nvim-tree cannot load remote folders itself.

**Comment by msva** [comment]
Yes, and that is the point.

It wouldbe nice to somehow get following behaviour:

- if user opens `vim proto://host/path` - netrw do it's business in this buffer, and nvim-tree don't brake it's things.
- in other cases (say, user opens local directory with no file in nvim) - nvim-tree takes the place.
- although, would be nice no still get p1 behaviour on `:e proto://host/path`.

I'm trying to achieve that with different kludges, but with less luck than I want to ;)

**Comment by kyazdani42** [comment]
well you can just disable auto_open now and it should not load the tree. You should also disable `hijack_directories.auto_open`. Closing this because it was implemented :)

**Comment by kyazdani42** [comment]
Although the advanced things you are asking is a bit too much for the plugin and this very narrow use case. Just reimplement your own on_enter logic, where you would dispatch the setup with auto_open if the thing you open with has no `//` in it's bufname i guess.
