### ISSUE TITLE
Open tree for current buffer 

### ISSUE THREAD

**Issue by harrisoncramer** [kyazdani42/nvim-tree.lua#773]
First off, thank you for this awesome plugin! It's great.

Is it possible to configure the plugin so that the tree opens relative to the buffer's current location on your computer? For instance, I'll often originally open up nvim in `~/myfiles/folder/foo.js` and within the same session, edit a file in a different directory, for example at `~/anotherfolder/different/bar.js`. Currently, when inside that second directory, the tree opens within the original directory that nvim first opened in (the `~/myfiles/folder` directory).

Is it possible to open the tree dynamically based on which buffer is currently focused?

**Comment by msva** [comment]
`au BufEnter * if &ft != 'help' | silent! cd %:p:h | endif`

**Comment by msva** [comment]
(actually, checking for 'help' filetype is not that necessary, I guess)

**Comment by harrisoncramer** [comment]
Thank you! Worked perfectly, alongside the `vim_tree_respect_buf_cwd` setting.

**Comment by Toddgm** [comment]
> `au BufEnter * if &ft != 'help' | silent! cd %:p:h | endif`

sorry new to nvim, may i ask where should i add this command to, i have some problem as the issue owner has here.thx
