### ISSUE TITLE
Keep current PWD updated accross all buffers when changing directory in nvim-tree

### ISSUE THREAD

**Issue by ivankovnatsky** [kyazdani42/nvim-tree.lua#776]
I came from NERDTree and if I miss something, please navigate me to setup this.

1. when i do `C-]` the pwd in nvim-tree changes to what directory i entered
2. i open a file from the tree, check the `!pwd` -- as expected
3. go back to the tree and move up the hierarchy and choose another dir to enter
4. go back to a file/buffer from another dir, the pwd is the same as in 2., not as in 3. as i would want

Can I configure nvim-tree in a such a way to control pwd in nvim-tree for all the buffers?

**Comment by ivankovnatsky** [comment]
I see that if I open a buffer and open a new one, the pwd does get updated as expected.

**Comment by kyazdani42** [comment]
fixed in #874
