### ISSUE TITLE
the explorer does not focus on current file on the first open time.

### ISSUE THREAD

**Issue by thuan1412** [kyazdani42/nvim-tree.lua#777]
https://user-images.githubusercontent.com/36019052/140791133-b3c3b3ae-2c65-4be9-abea-aa7a62cfe964.mp4

**Comment by kyazdani42** [comment]
cannot reproduce. Please give me more informations.

**Comment by thuan1412** [comment]
My nvim's version is 0.6 and here is my nvim-tree configuration. https://github.com/thuan1412/NvChad/blob/main/lua/plugins/configs/nvimtree.lua.

**Comment by ShivamKumar2002** [comment]
+1
I am also facing same issue

**Comment by kyazdani42** [comment]
Is this still relevant ? The `update_focused_file.enable` should be true in the setup

**Comment by kyazdani42** [comment]
i believe this is fixed now, closing.
