### ISSUE TITLE
Error while calling lua chunk: Not an editor command: RainbowParentheses

### ISSUE THREAD

**Issue by antz22** [kyazdani42/nvim-tree.lua#781]
Hi, I ran into a problem after migrating to the new version of nvim-tree (although I'm not sure if that's the cause of this problem).

Here is the config I have for nvim-tree
```lua
vim.g.nvim_tree_hide_dotfiles = 1
vim.g.nvim_tree_indent_markers = 1 
vim.g.nvim_tree_icons = {
    default = '',
    symlink = '',
    git = {
        unstaged = "",
        staged = "✓",
        unmerged = "",
        renamed = "➜",
        untracked = ""
    },
    folder = {
        default = "",
        open = "",
        empty = "",
        empty_open = "",
        symlink = ""
    }
}

vim.cmd("hi NvimTreeFolderIcon guifg = #61afef")
vim.cmd("hi NvimTreeFolderName guifg = #61afef")
vim.cmd("hi NvimTreeIndentMarker guifg=#545862")

vim.o.termguicolors = true 

require'nvim-tree'.setup {
  disable_netrw       = true,
  hijack_netrw        = true,
  open_on_setup       = true,
  ignore_ft_on_setup  = {},
  update_to_buf_dir   = {
    enable = true,
    auto_open = true,
  },
  auto_close          = false,
  open_on_tab         = false,
  hijack_cursor       = false,
  update_cwd          = false,
  diagnostics         = {
    enable = false,
    icons = {
      hint = "",
      info = "",
      warning = "",
      error = "",
    }
  },
  update_focused_file = {
    enable      = false,
    update_cwd  = false,
    ignore_list = {}
  },
  system_open = {
    cmd  = nil,
    args = {}
  },
  view = {
    width = 30,
    height = 30,
    side = 'left',
    auto_resize = false,
    mappings = {
      custom_only = false,
      list = {}
    }
  }
}
```

I have also added lua require'nvim-tree'.setup {} in my init.vim. 
Here is a screenshot of the error I am getting.

![unknown](https://user-images.githubusercontent.com/59377837/141689804-4dc2bcac-1970-4588-bf9e-5536ff21ff31.png)

rainbow_parentheses is a plugin created by junegunn [here](https://github.com/junegunn/rainbow_parentheses.vim).

Let me know if I am missing information or if this issue doesn't belong here. Thanks!

**Comment by kyazdani42** [comment]
could be a loading issue, maybe load you junegunn plugin before nvim-tree ?

**Comment by carlesba** [comment]
I got the same error but it points at:
```
E5113: Error while calling lua chunk: ...ter/.config/nvim/plugged/nvim-tree.lua/lua/nvim-tree.lua:477: attempt to call
 field 'setup' (a nil value)
```

this is when nvim-tree is calling nvim-tree.git in the setup function. 

This was working before today's update. Last update was probably last Friday.

**Comment by kyazdani42** [comment]
Hi again sorry for the late answer.
Does this issue still arises ? I've never seen it myself.

**Comment by kyazdani42** [comment]
@carlesba ping :)

**Comment by kyazdani42** [comment]
closing then, let me know if this issue happens again :)
