### ISSUE TITLE
Massive performance issue since last update or so

### ISSUE THREAD

**Issue by Yugeniki** [kyazdani42/nvim-tree.lua#785]
Ever since last update it takes a while for folders to open in nvim. Before it was instantly opened, now it hangs for 1-3 seconds before opening.

I have tried in both init.vim and init.lua and there was no difference in the slowness. I have also checked to see if recently added filters are responsible but removing them does nothing. 

One thing that may be worthy of note is that nvim slows down to a crawl and starts having regular stutters after opening nvim tree.

**Comment by kyazdani42** [comment]
please see #549.
