### ISSUE TITLE
how to fix nvim-tree width and side?

### ISSUE THREAD

**Issue by LollipopFt** [kyazdani42/nvim-tree.lua#793]
when i first open nvim-tree, it is on the left with a certain width.
![image](https://user-images.githubusercontent.com/62802897/142875568-98e0de5c-621e-4059-9dbc-c8068590f421.png)
when i open a file, it can be seen that it still remains:
![image](https://user-images.githubusercontent.com/62802897/142875751-545f97db-5657-4e68-aaab-aab763f9381e.png)
when i do ```:bw``` on the code, it closes the window and fully exposes nvim-tree:
![image](https://user-images.githubusercontent.com/62802897/142875926-24024f61-e5e0-4d2c-a546-5818bbf1e791.png)
as you can see, there is still a file buffer on top, so i switch to that with ```:b```:
![image](https://user-images.githubusercontent.com/62802897/142876066-e735db5f-14de-4cc0-be3c-6c26f5e70e76.png)
here's the problem: nvim-tree now moves to the right, and takes up half the space. how do i fix it to how it was in the first image?

**Comment by kyazdani42** [comment]
could you provide your configuration ? 
maybe you need to 
`require'nvim-tree'.setup { view = { side = 'left', width = 30 } }` which is the default.

**Comment by DPDmancul** [comment]
Same problem. 

I have 
```lua
require"nvim-tree".setup{
  view = {
    auto_resize = true,
    side = "left",
  }
}
```
in my init.lua

`auto_resize = true` solved with problem, but `side = "left"` doesn't solve the side problem.

**Comment by kyazdani42** [comment]
Wasn't able to reproduce, and i lack informations. Closing this, if this happens again just ping me with a proper configuration and reproducible steps :)
