### ISSUE TITLE
Expose API of window picker

### ISSUE THREAD

**Issue by paakmau** [kyazdani42/nvim-tree.lua#794]
Hi, nvim-tree is a great plugin that I'm currently using.

Now I need to navigate to the windows containing the buffers of files. I found window picker is useful for this need. Finally I write something as follows.

```lua
vim.fn.pick_window = function()
    local target_winid = require("nvim-tree.lib").pick_window()
    if target_winid == -1 then
        target_winid = require("nvim-tree.lib").Tree.target_winid
    end
    vim.api.nvim_set_current_win(target_winid)
end
vim.api.nvim_set_keymap("n", "<leader>i", ":lua vim.fn.pick_window()<CR>", opts)
```

I think it will be nice if some API about the window picker can be exposed.

**Comment by kyazdani42** [comment]
I guess i'll be documenting / exposing apis once i've cleaned and stabilized the module.
