### ISSUE TITLE
NvimTree dont swtich view to new root

### ISSUE THREAD

**Issue by Grzanka99** [kyazdani42/nvim-tree.lua#795]
![image](https://user-images.githubusercontent.com/7966948/143325369-639aaed6-72e0-4e60-905e-e60aad4084f6.png)
Why even though I have other root directory (checked by pwd) tree keep it's root to place where was open? It was working long while ago and has been broken.

**Comment by Grzanka99** [comment]
After some struggling I finally found option to respect root but... I think It should be better documented on github

**Comment by iamdavidmartin** [comment]
can you share how you fixed this? i have the same issue.

**Comment by Grzanka99** [comment]
You need to add this two lines to your config
![image](https://user-images.githubusercontent.com/7966948/143448033-10490fd2-d852-4f86-8803-5320f2385045.png)
Eariel it was default as true ( i guess)

**Comment by kyazdani42** [comment]
sorry for the late answer, i guess it was not but i moved it inside the setup function so you global variables might not have worked. Closing this because the whole documentation needs a rewrite anyway.
