### ISSUE TITLE
Add nvim-tree filetype and re-apply colorscheme on sourcing init.vim

### ISSUE THREAD

**Issue by Akin909** [kyazdani42/nvim-tree.lua#8]
Firstly thanks for the awesome plugin, it's super snappy :100:

Sorry I bundled two issues in one.

### 1. Buffer Filetypes
I noticed that the plugin doesn't give the `nvim-tree` buffers specific filetypes so it's hard to set autocommands or use the filetype to do whatever a user might want with that buffer e.g. `nerdtree` or `coc-explorer` etc. buffers have a filetype so I could have line number on or off by setting a filetype autocommand or using a ftplugin file. Or in my statusline I can check the filetype and show a formatted name with an icon for that kind of buffer or hide the statusline in that buffer altogether :shrug:.

I'd be up for raising a PR for that if that interests you at all?

### 2. Buffer highlights disappear on sourcing init.vim
This is a fairly common issue with a lot of different plugins, as far as I can guess the highlights set in the `nvim-tree` buffer are only done once not on `Colorscheme` changed. Think a fix here would be register a function in the plugin to apply the highlights and call it when the colorscheme changes.

**Comment by kyazdani42** [comment]
Hi ! thanks for the kind words.
I'll make a PR when i have some time later today.

**Comment by kyazdani42** [comment]
also i have another issue with colors, i might also fix that in the same PR (colors do not apply properly for some colorschemes that don't set the `nvim_color_x` variables)
