### ISSUE TITLE
Symlinks don't have an icon

### ISSUE THREAD

**Issue by stsewd** [kyazdani42/nvim-tree.lua#80]
I don't use icons, but since it doesn't fallback to the `default` "icon" it doesn't get the padding like the other files.

![Screenshot from 2020-08-03 17-51-37](https://user-images.githubusercontent.com/4975310/89234642-07cd2000-d5b2-11ea-9b50-8caeac87a9b7.png)

**Comment by kyazdani42** [comment]
other files shouldn't get the padding, i fixed it in latest master. Closing this.

**Comment by stsewd** [comment]
Thanks, I can see this is fixed for special files, but symlinks still aren't aligned

![Screenshot from 2020-08-04 14-18-58](https://user-images.githubusercontent.com/4975310/89335303-74e9bf80-d65d-11ea-9096-81210742cfcf.png)

**Comment by kyazdani42** [comment]
they should be after your PR is merged
