### ISSUE TITLE
Backspace close directory node doesn't reflect visually

### ISSUE THREAD

**Issue by stoicAlchemist** [kyazdani42/nvim-tree.lua#800]
I just updated the plugin today I noticed that `<BS>` does close the currently opened directory sub-tree and moves the cursor to the parent directory node but visually it's still opened and traversable but hitting `<CR>` doesn't open directories or files.

To reproduce, open a directory tree that is at least 3 levels, hit `<BS>` twice to "logically" close the directory nodes, when the cursor is on the last directory, use navigation keys to go through the "closed" nodes and try hitting `<CR>` to open files, the result is no operation executed; after this, navigate to the "valid" parent node and use `<CR>` to trigger a close command and again to open the directory nodes which will correctly update the view of the directories.

**Comment by kyazdani42** [comment]
should be fixed in latest master.
