### ISSUE TITLE
Error when call the `NvimTreeToggle` after update Neovim nightly.

### ISSUE THREAD

**Issue by nyngwang** [kyazdani42/nvim-tree.lua#803]
## Neovim version

NVIM v0.6.0-dev+644-ge4976cbd2
Build type: Release
LuaJIT 2.1.0-beta3

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-e4976cb_1/share/nvim"

Run :checkhealth for more info

## Setup

I'm using `packer.nvim` with the following settings:

```
use {
  'kyazdani42/nvim-tree.lua',
  requires = {
    'kyazdani42/nvim-web-devicons'
  },
  config = function()
    require'nvim-tree'.setup {
      hijack_cursor = true,
      update_cwd = true,
      open_on_tab = true,
      view = {
        side = 'right',
        width = 45,
        auto_resize = false,
      },
      update_focused_file = {
        enable      = true,
        update_cwd  = true,
      },
      filters = {
        custom = { '.git', '__pycache__', '.DS_Store' }
      }
    }
    vim.g.nvim_tree_show_icons = {
      ['git'] = 1,
      ['folders'] = 0,
      ['files'] = 0,
      ['folder_arrows'] = 0,
    }
    vim.g.nvim_tree_highlight_opened_files = 1
    vim.g.nvim_tree_respect_buf_cwd = 1
    vim.g.nvim_tree_indent_markers = 1
    vim.g.nvim_tree_add_trailing = 1
  end
}
vim.api.nvim_set_keymap('n', ';', '<cmd>NvimTreeToggle<CR>', NOREF_NOERR_TRUNC)
```

## Error message

```
Error detected while processing CursorMoved Autocommands for "NvimTree":
E5108: Error executing lua ...m/site/pack/packer/start/nvim-tree.lua/lua/nvim-tree.lua:341: Column value outside range
stack traceback:
        [C]: in function 'nvim_win_set_cursor'
        ...m/site/pack/packer/start/nvim-tree.lua/lua/nvim-tree.lua:341: in function 'place_cursor_on_node'
        [string ":lua"]:1: in main chunk
```

**Comment by nyngwang** [comment]
After some testing this error will occur when I run `nvim path/to/my/file` but if I start from a folder `nvim path/to/a/folder/` then there will be no problem. Very weird.

**Comment by imSafdarAwan** [comment]
getting the same error

**Comment by imSafdarAwan** [comment]
downgraded to nvim-5.1 and now the problem that was still there was the git 
https://github.com/imSafdarAwan/nvim_conf/blob/6685c58612a5f6c9962e5e642f50100c822ead9b/lua/plugins/configs/nvim-tree.lua#L53 
this solved my problem 
and also if you have this remove it 
https://github.com/imSafdarAwan/nvim_conf/blob/6685c58612a5f6c9962e5e642f50100c822ead9b/lua/plugins/configs/nvim-tree.lua#L5

**Comment by imSafdarAwan** [comment]
by the way i updated to the nvim-0.6.0 and the error is not there anymore the same steps as mentioned on the uppaer reply

**Comment by nyngwang** [comment]
> by the way i updated to the nvim-0.6.0 and the error is not there anymore the same steps as mentioned on the uppaer reply

But I didn't setup the option.

**Comment by aleprovencio** [comment]
Offending commit seems to be [#6662b60](https://github.com/kyazdani42/nvim-tree.lua/commit/6662b60a2bb55f0c1eca4db54cba5c57c2b2daff).

Installing `nvim-tree` specifying the commit `#b853e10` does the trick as a temporary fix.

**Comment by nyngwang** [comment]
> Offending commit seems to be [#6662b60](https://github.com/kyazdani42/nvim-tree.lua/commit/6662b60a2bb55f0c1eca4db54cba5c57c2b2daff).
> 
> Installing `nvim-tree` specifying the commit `#b853e10` does the trick as a temporary fix.

Thanks for the temporary solution ;)

**Comment by nyngwang** [comment]
> I got the same error, but as stated on #437 try setting nvim_tree_hijack_cursor option to false fixed the problem for me. P.S I think this error is related to sessions since every time I sourced a session file and then toggled NvimTree the error would come up

The error disappears. But, the result make me more disappointed. When I wanted to expand a folder, it open a (I think) random file that is in the same folder as the current buffer where I triggered the `:NvimTreeToggle`.

**Comment by shlomocarmeter** [comment]
@nyngwang Seems like a weird behavior.. maybe you have an autocommand that triggers upon bufread/bufenter?

**Comment by kyazdani42** [comment]
Hi, sorry for the late answer, i've been very tired last months.
Can you tell me if this issue is still relevant ? I did not manage to reproduce.

**Comment by aleprovencio** [comment]
LGTM, @kyazdani42 !
