### ISSUE TITLE
Highlight groups in help/doc

### ISSUE THREAD

**Issue by adrian5** [kyazdani42/nvim-tree.lua#804]
1. It looks like [these](https://github.com/kyazdani42/nvim-tree.lua/blob/master/doc/nvim-tree-lua.txt#L653-L668) aren't actually in use.
2. Wouldn't it be clearer to list [these](https://github.com/kyazdani42/nvim-tree.lua/blob/master/doc/nvim-tree-lua.txt#L681-L685) as `NvimTreeNormal`, `NvimTreeEndOfBuffer`, etc.? That's what the user would likely override.

**Comment by kyazdani42** [comment]
Hi !
1 - what are 'these' you are talking about ? everything is used i believe.
2 - i'm not sure what you mean by these again :smile:

**Comment by adrian5** [comment]
Hehe, hello **kyazdani42**!

1. I'm trying to remember (the file has changed so the line numbers no longer match). I'm pretty sure my link was pointing [these](https://github.com/kyazdani42/nvim-tree.lua/blob/master/doc/nvim-tree-lua.txt#L699-L708), i.e.:

```
NvimTreeLuaIcon
NvimTreePythonIcon
NvimTreeShellIcon
NvimTreeJavascriptIcon
NvimTreeCIcon
NvimTreeReactIcon
NvimTreeHtmlIcon
NvimTreeRustIcon
NvimTreeVimIcon
NvimTreeTypescriptIcon
```
They don't appear to be in use anywhere unless I'm missing something.

2. I don't think I can remember what that as about :smile:

**Comment by kyazdani42** [comment]
good catch, these are very old and were replaced with nvim-web-devicons a long time ago. I'm removing this, thanks for pointing that out :)
