### ISSUE TITLE
File not focused on file creation (regression?)

### ISSUE THREAD

**Issue by macintacos** [kyazdani42/nvim-tree.lua#806]
It seems like the functionality that should've been introduced in #376 is not there anymore. When I create a file,the cursor doesn't focus it in the tree. Is there an option I should be setting to get this to happen, or should it be happening by default? I only have the following options enabled (removing them seems to not do anything):

```
hijack_cursor = true,
update_cwd  = true,
```

**Comment by aleprovencio** [comment]
I confirm, this seem related to #803

**Comment by axieax** [comment]
It seems that the pcall to `vim.api.nvim_win_set_cursor` in `view.lua` in the `M.set_cursor` function fails due to "Cursor position outside buffer". Perhaps the window was not refreshed in time?
