### ISSUE TITLE
Question: git highlight groups

### ISSUE THREAD

**Issue by adrian5** [kyazdani42/nvim-tree.lua#808]
I can observe `NvimTreeGitNew`, `NvimTreeGitDirty`, and `NvimTreeGitStaged` in action by _creating_, _editing_ and _staging_ files.

How can I cause `NvimTreeGitRenamed`, `NvimTreeGitDeleted`, `NvimTreeGitMerged` to appear? `git mv`, `git rm` and `git merge` do not have any visible effect here. Maybe I'm misunderstanding the feature, or my config is missing some flags.

Thanks!

**Comment by kyazdani42** [comment]
git merge can happen when a conflict happens (the file conflicting will have the icon/color for it)
git deleted happens on folders when a file has been deleted inside but the folder integration is a bit broken rn, i must fix it first.
the renamed i must say i have very rarely seen it, but should be when renaming a file
