### ISSUE TITLE
nvim-tree maybe blocks git (.git/index.lock)

### ISSUE THREAD

**Issue by faebebin** [kyazdani42/nvim-tree.lua#810]
I use neovim 0.5 and this plugin (nvim-tree.lua) without any custom config sofar. Just tried to `git rebase -i <commit>` and got a git error message `fatal: Unable to create 'X:/sources/project/.git/index.lock': File exists. ... If no other git process is currently running, this probably means a
git process crashed in this repository earlier. Make sure no other git
process is running and remove the file manually to continue. ` . Then first suspecting vim-fugitive I found this reply ( https://github.com/tpope/vim-fugitive/issues/1624#issuecomment-731840747 ) and finally removed this plugin and git works again. So not sure whether is actually this plugin but maybe also use Add --no-optional-locks to git status command if used at all.

**Comment by faebebin** [comment]
Update: after setting 
```
require("nvim-tree").setup({
  ...
	git = {
		enable = false,
		ignore = false,
		timeout = 500,
	},
  ...
})

```
The problem no more occurs.

**Comment by monsonjeremy** [comment]
This is a regression for sure. This did not happen in previous versions.

I think it may be a function of the size of the repository and the rebase. It works for me in some repos, but not in others. Trying to confirm this but it's something I suspect.

**Comment by monsonjeremy** [comment]
Setting the following works for me:
```lua
require("nvim-tree").setup({
  ...
	git = {
		enable = true,
		ignore = true,
		timeout = 40,
	},
  ...
})
```
But then upping the `timeout` to `50` makes it fail again:
```lua
require("nvim-tree").setup({
  ...
	git = {
		enable = false,
		ignore = false,
		timeout = 50,
	},
  ...
})
```

I think it may be a function of the size of the repo. Small repos will be fine since it finished in <50ms in most cases but anything larger and this will happen.

**Comment by faebebin** [comment]
That would make sense  as I am working on a probably big repo:

```
git gc
du -sh .git/
Enumerating objects: 31725, done.
Counting objects: 100% (31725/31725), done.
Delta compression using up to 8 threads
Compressing objects: 100% (9938/9938), done.
Writing objects: 100% (31725/31725), done.
Total 31725 (delta 20178), reused 31340 (delta 19880)
454M    .git/
```
