### ISSUE TITLE
Feature Request: NERDTree's Toggle Zoom

### ISSUE THREAD

**Issue by lanza** [kyazdani42/nvim-tree.lua#811]
If you press `A` in the `NERDTree` window it'll toggle the width of the window to ~98% of the terminal and back to normal. This is useful for files with long names and/or deeply nested directories.

**Comment by kyazdani42** [comment]
You could setup your own command for that.
```lua
local is_toggled = false
function _G.toggle_full_width()
  if is_toggled then
     require'nvim-tree'.resize(DEFAULT_SIZE)
  else
      require'nvim-tree'.resize('98%')
   end
  is_toggled = not is_toggled
end
```
and bind the function in the nvim-tree setup.

**Comment by gegoune** [comment]
`.resize` function does not seem to be doing anything for me. Tried with both percentage in string as well as integers.

**Comment by kyazdani42** [comment]
@gegoune could you elaborate ?

**Comment by gegoune** [comment]
@kyazdani42 I have long abandoned that function and cannot remember exactly what the issue was. Would you want me to revisit it?

**Comment by kyazdani42** [comment]
don't worry, i'll close this and if the author of the issue asks for help again i'll reopen :)

**Comment by mario-amazing** [comment]
@kyazdani42 Hey, maybe you could add this functionality to the plugin?

**Comment by alex-courtis** [comment]
> Because this feature is an emergency when you have a large project and need to see full paths to files.

There are some options available to you:
```vim
:help nvim-tree.view.adaptive_size
:help nvim-tree.view.adaptive_size
```

**Comment by kyazdani42** [comment]
Also, if you wish to bind this yourself: `<C-w>o` and `:NvimTreeResize`
