### ISSUE TITLE
Error whenever folder contains `.git` subfolder & can not access the folder.

### ISSUE THREAD

**Issue by Firwanaa** [kyazdani42/nvim-tree.lua#814]
I get this error whenever I try to access a folder contains `.git` subfolder, and I can not access this folder.

![image](https://user-images.githubusercontent.com/65984781/144186455-c0aef893-a3fc-4fd8-985d-0c344aa34dc3.png)
My configurations pretty simple:
```lua
vim.g.nvim_tree_width = 25
-- vim.g.nvim_tree_gitignore = 1
vim.g.nvim_tree_git_hl = 1 
vim.g.nvim_tree_indent_markers = 1 
require'nvim-tree'.setup {
open_on_setup = true,
auto_open = 1,
auto_close = 1,
git = {
    enable = true,
    ignore = true,
    timeout = 500,
  },
update_to_buf_dir   = {
 enable = true,
 auto_open = true,
  },
}

-- vim.cmd[[
-- nnoremap <C-n> :NvimTreeToggle<CR>
-- ]]
```

**Comment by xyl1t** [comment]
I also had this issue on macOS with Neovim v0.5, but since upgrading to the newest stable version of Neovim (v0.6.0), I no longer experience this issue.
![Screenshot 2021-12-01 at 20 58 57](https://user-images.githubusercontent.com/56483075/144304853-86a80349-18b7-445e-bdeb-8b5825a55661.png)

**Comment by Firwanaa** [comment]
> I also had this issue on macOS with Neovim v0.5, but since upgrading to the newest stable version of Neovim (v0.6.0), I no longer experience this issue. ![Screenshot 2021-12-01 at 20 58 57](https://user-images.githubusercontent.com/56483075/144304853-86a80349-18b7-445e-bdeb-8b5825a55661.png)

![image](https://user-images.githubusercontent.com/65984781/144306581-199f60a1-db43-447f-b838-4125c78d8b31.png)
  I'm on NVIM v0.6.0 as will

**Comment by ManeeshWije** [comment]
same issue on macOS with Neovim v0.6.0 :/

**Comment by kyazdani42** [comment]
I assumed the last commit fixes this issue, can you still reproduce ?

**Comment by Firwanaa** [comment]
> I assumed the last commit fixes this issue, can you still reproduce ?

Removed it and add it again, works fine now. Thanks a lot
