### ISSUE TITLE
Error in Windows when neovim running in git bash

### ISSUE THREAD

**Issue by dragove** [kyazdani42/nvim-tree.lua#816]
In windows, when neovim is running in git bash. nvim-tree encountered an error:

```
Error executing vim.schedule lua callback: ...\packer\start\nvim-tree.lua/lua/nvim-tree/git/runner.lua:55: attempt to index upvalue 'handle' (a nil value)
stack traceback:
        ...\packer\start\nvim-tree.lua/lua/nvim-tree/git/runner.lua:55: in function 'on_finish'
        ...\packer\start\nvim-tree.lua/lua/nvim-tree/git/runner.lua:74: in function 'cb'
        vim.lua:285: in function <vim.lua:285>
```

**Comment by Firwanaa** [comment]
same issue [#814 ](https://github.com/kyazdani42/nvim-tree.lua/issues/814)

**Comment by dragove** [comment]
> same issue [#814 ](https://github.com/kyazdani42/nvim-tree.lua/issues/814)

I don't know if it is really same. I encountered this problem in git-bash in widows system without a .git folder. However it runs well in powershell/cmd. And it also runs well in my Linux Environment

**Comment by Firwanaa** [comment]
> > same issue [#814 ](https://github.com/kyazdani42/nvim-tree.lua/issues/814)
> 
> I don't know if it is really same. I encountered this problem in git-bash in widows system without a .git folder. However it runs well in powershell/cmd. And it also runs well in my Linux Environment

I am on Linux, and had this issue only when `.git` exists.

**Comment by tarsobcaldas** [comment]
I'm running PowerShell on Windows Terminal and I'm having the same problem, specifically with .git folders.

**Comment by kyazdani42** [comment]
Mmh i rewrote the git implementation, it's running with libuv jobs now.
I do not have a windows environment to debug this properly, maybe someone could help fixing this ?

**Comment by kyazdani42** [comment]
Might be fixed, but maybe not. Can you confirm ?

**Comment by dragove** [comment]
> Might be fixed, but maybe not. Can you confirm ?

It's fixed! Thanks.
