### ISSUE TITLE
filtering not working?

### ISSUE THREAD

**Issue by snoblenet** [kyazdani42/nvim-tree.lua#819]
I have this config:

```
g.nvim_tree_indent_markers = 1
g.nvim_tree_quit_on_open = 1
require("packer").startup(function()
  use({
    "kyazdani42/nvim-tree.lua",
    requires = "kyazdani42/nvim-web-devicons",
    config = function()
      require("nvim-tree").setup({
        filters = { dotfiles = false, custom = { ".DS_Store" } },
        git = { enable = true, ignore = false },
        open_on_setup = true,
        update_cwd = true,
        update_focused_file = { enable = true, update_cwd = true },
        view = { width = 60 },
      })
    end,
  })
end
```
I get this result:

![image](https://user-images.githubusercontent.com/62277/144523728-fd1b0ebf-eb31-4ad5-95a3-bd3aee06e35c.png)

Any suggestions? Thanks.

**Comment by snoblenet** [comment]
Could it be that it is showing `.DS_Store` as a dotfile?

If yes, then I think the order of precedence needs to be reversed, so that `filters = { dotfiles = false, custom = { ".DS_Store" } }` shows all dotfiles other than `.DS_Store` files.

**Comment by gegoune** [comment]
I just tried

```lua
  filters = {
    dotfiles = false,
    custom = { '.git', 'node_modules', '.cache', '.DS_Store' },
  },
```
and am not seeing it on the tree list.

**Comment by jakubreron** [comment]
Same goes for me, I want to see my node_modules folder, but nothing changes if I modify the filters.

**Comment by kyazdani42** [comment]
could not reproduce with provided configuration :/ could something be going on with the way macos handles casing in filenames ? what happens if you set the filter to `.ds_store` instead ?

**Comment by gegoune** [comment]
@kyazdani42 Sorry if I wasn't clear in my previous comment; I can't reproduce that either and I am on macOS.

**Comment by kyazdani42** [comment]
not sure why this happens to @snoblenet though.

**Comment by snoblenet** [comment]
Weird. My current set-up is now working as expected.
