### ISSUE TITLE
Missing setting `g:nvim_tree_refresh_wait`

### ISSUE THREAD

**Issue by mattleong** [kyazdani42/nvim-tree.lua#820]
Searched through source code and couldn't find a reference to `g:nvim_tree_refresh_wait`. 

Search link:
https://github.com/kyazdani42/nvim-tree.lua/search?q=nvim_tree_refresh_wait

Is this now deprecated? Was it replaced with something else? Couldn't find any references or suggestions to alternatives in `:h nvim-tree`

**Comment by kyazdani42** [comment]
i indeed removed this option because it was causing all sort of undesired behaviors and inconsistencies.
