### ISSUE TITLE
How to ignore the .git directory?

### ISSUE THREAD

**Issue by bushblade** [kyazdani42/nvim-tree.lua#824]
Is it possible to ignore certain directories?
Currently nvim-tree ignores anything in my .gitignore but I still see the .git directory in the file tree.
Every time I use Fugitive nvim-tree jumps to opening my .git directory, but I'm not interested in what is in the .git directory.
I don't know if this is a bug, a feature request or I'm missing some needed config.
My current nvim-tree settings are...
```lua
vim.g.nvim_tree_indent_markers = 1
vim.g.nvim_tree_git_hl = 1
vim.g.nvim_tree_highlight_opened_files = 1

-- projects.nvim needs this setting
vim.g.nvim_tree_respect_buf_cwd = 1

require("nvim-tree").setup({
  auto_close = true,
  diagnostics = {
    enable = true,
    icons = {
      hint = " ",
      info = " ",
      warning = " ",
      error = " ",
    },
  },
  update_cwd = true,
  update_focused_file = {
    enable = true,
    update_cwd = true,
  },
})
```

**Comment by gegoune** [comment]
Try setting `filters.custom = {}`.

**Comment by bushblade** [comment]
Thanks @gegoune that works!

**Comment by gabroo** [comment]
when I put `.git` in my `.gitignore` it still shows up in the tree, even though every other entry in the file is ignored. 

is this replicable?

**Comment by bushblade** [comment]
Hi @gabroo 
You don't need to put .git in your .gitignore to hide it from the tree view.
Actually why would git ignore it's own tracking?
To ignore the .git directory in nvim-tree add...
```lua
  filters = {
    custom = { ".git" },
  },
```
to your setup table.
So it would look like...
```lua
require("nvim-tree").setup({
  auto_close = true,
  diagnostics = {
    enable = true,
    icons = {
      hint = " ",
      info = " ",
      warning = " ",
      error = " ",
    },
  },
  update_cwd = true,
  update_focused_file = {
    enable = true,
    update_cwd = true,
  },
  filters = {
    custom = { ".git" }, -- ignore .git
  },
})
```
Hope that helps.
