### ISSUE TITLE
is there any way to increase font size?

### ISSUE THREAD

**Issue by shaeinst** [kyazdani42/nvim-tree.lua#825]
i didn't find option to setup font size, is there any way to increase only tree's font size? if not, how about adding this feature?

**Comment by gegoune** [comment]
It's not up to nvim-tree or either nvim even. It's controlled by your terminal emulator which usually does not allow that sort of things. Maybe some GUI clients?

**Comment by shaeinst** [comment]
my mistake. i forget that font size controls by terminal itself.

**Comment by kyazdani42** [comment]
indeed :smile: closing this then.

**Comment by colorsu** [comment]
like vscode, the file tree's font is smaller than the code view.
