### ISSUE TITLE
Meaning of some code. Asking for permission to create wiki

### ISSUE THREAD

**Issue by bryant-the-coder** [kyazdani42/nvim-tree.lua#827]
what does the trash do? curios lol

**Comment by bryant-the-coder** [comment]
I will try to add a wiki for some configurations. if that is accepted.

**Comment by kyazdani42** [comment]
wiki for configurations would be overkill because you can just `:help nvim-tree.trash` for instance to get the 'advanced' configuration :)

**Comment by kyazdani42** [comment]
the wiki is here mostly for informational stuff and code snippets for features that i don't want to implement in the codebase

**Comment by bryant-the-coder** [comment]
Ok thx. But i accidental create a wiki home pg... Sorryyyyyy

**Comment by kyazdani42** [comment]
no worries :smile: closing this then.
