### ISSUE TITLE
How to hide hidden files

### ISSUE THREAD

**Issue by JosefLitos** [kyazdani42/nvim-tree.lua#828]
Is there any way to hide hidden files?
I appreciate your documentation very much, but I haven't managed to find a way to disable seeing hidden files by default or during its use.
Also, is there a way to close nvimtree after opening a file (like when used as default directory explorer, not every time)

**Comment by gegoune** [comment]
Both are described in readme:

`let g:nvim_tree_quit_on_open = 1 "0 by default, closes the tree when you open a file`

and 

```lua
filters.dotfiles = <bool>
```
might be what you are after. Also:

>I will toggle visibility of hidden folders / files
>H will toggle visibility of dotfiles (files/folders starting with a .)
