### ISSUE TITLE
Can we update `change_dir` to use `cd` instead of `lcd`?

### ISSUE THREAD

**Issue by svanharmelen** [kyazdani42/nvim-tree.lua#829]
I have some really unexpected behavior and tracked it down to the fact that `lcd` in used instead of `cd` [here](https://github.com/kyazdani42/nvim-tree.lua/blob/master/lua/nvim-tree/lib.lua#L458). Would it be possible to change that or to make it optional to change dirs using `cd`?

I mainly use the keymapping to change dirs in the tree view, but then the view starts to switch which dirs to show when I just trough buffers that were already open. Think #776 is also mentioning something along these lines.

If there is a way I can add a custom mapping to fix it for myself I would also be happy, but maybe even better to not use `lcd` at all?

**Comment by kyazdani42** [comment]
I used `cd` at first but people complained because they did not want nvim-tree to change the directory for the whole editor :smile:
Maybe introducing a config option would be appropriate.

**Comment by svanharmelen** [comment]
Ow really 😅 Different people, different preferences I guess 🙂

A config option would indeed be great!
