### ISSUE TITLE
`lua_tree_git_hl` doesn't update when not using git icons

### ISSUE THREAD

**Issue by stsewd** [kyazdani42/nvim-tree.lua#83]
```vim
let g:lua_tree_git_hl = 1

let g:lua_tree_show_icons = {
      \ 'git': 0,
}
```

If you change a file, the color doesn't get updated, according to the docs it should work without icons

**Comment by stsewd** [comment]
Also the mappings like `[c` don't work without icons

**Comment by kyazdani42** [comment]
well `[c` is based on icons so it cannot work. You can create an issue so we adapt the code to be based on git statuses instead of icons.
