### ISSUE TITLE
NvimTreeFindFileToggle command  does not find the file

### ISSUE THREAD

**Issue by numbcoder** [kyazdani42/nvim-tree.lua#831]
**OS**
macOS 12.0.1

**Neovim version**
NVIM v0.7.0-dev+676-g4306b395d

**Nvim-tree version**
commit 2e33b1654384921ec1cc9656a2018744f3f1ce81

**Describe the bug**
Execute `NvimTreeFindFileToggle` command, nvim-tree opened, but the tree is not expanded, and  the cursor is not focused on the file. 
If I expand the nvim-tree dir manually before execute `NvimTreeFindFileToggle` command, the command will be works well.

**To Reproduce**
1. Open a file with Telescope
2. Execute `NvimTreeFindFileToggle` command

Nvim-tree will be opened, but the cursor is not focused on the file.

**Expected behavior**
Nvim-tree will be opened, the dir will be expanded and the cursor will be focused on the file.

**Comment by kuznetsss** [comment]
The issue already exists (#783) but it was closed for some reason
