### ISSUE TITLE
Feature request: Clipboard indicators such as icons

### ISSUE THREAD

**Issue by Frederick888** [kyazdani42/nvim-tree.lua#832]
At the moment the only way to reveal current clipboard contents seems to be `:NvimTreeClipboard`.

It'll be nice to have some indicators for cut/copy such as icons/highlights/etc.

And a command to clear clipboard can also be useful.

**Comment by kyazdani42** [comment]
i guess it could be done with signs :) that's actually not a bad idea.

**Comment by alex-courtis** [comment]
Following in #1079
