### ISSUE TITLE
Bug: vim.lsp.diagnostic.get_count() is deprecated

### ISSUE THREAD

**Issue by GaetanLepage** [kyazdani42/nvim-tree.lua#833]
**OS**
Arch Linux

**Neovim version**
`NVIM v0.7.0-dev+697-g6063e07a0`

**Describe the bug**
The plugin seems to rely on `vim.lsp.diagnostic.get_count()` but the latter has been deprecated.

**To Reproduce**
Nothing special, just loading the plugin with 'diagnostics' enabled.

**Comment by gegoune** [comment]
@kyazdani42 I tried to get PR, but seems like response from `vim.lsp.diagnostic.get_all()` differs from `vim.diagnosic.get()`.

**Comment by GaetanLepage** [comment]
I didn't check that indeed...

**Comment by vtronko** [comment]
Duh. I hate when one plugin (telescope) decides to drop compatibility for <0.6.0, you update your neovim installation and suddenly realize everything else uses deprecated stuff heavily :P
