### ISSUE TITLE
Error while making any file 

### ISSUE THREAD

**Issue by Iamafnan** [kyazdani42/nvim-tree.lua#835]
**OS**
Android 10

**Neovim version**
NVIM V0.7.0-dev

**Nvim-tree version**
Master branch

**Describe the bug**
Getting error while making file

**To Reproduce**
Press `a` and add a file name

**Expected behavior**
The should be added to the directory

**Screenshot**
![IMG_20211209_201032](https://user-images.githubusercontent.com/80388154/145418376-2f52326d-f787-4cc7-ba1a-57c29aea9245.jpg)

**Comment by CanKolay5677** [comment]
https://github.com/kyazdani42/nvim-tree.lua/issues/769#issue-1046484403

**Comment by CanKolay5677** [comment]
#769

**Comment by CanKolay5677** [comment]
How you can installed neovim 0.7? I trying to compile but it gives errors.

**Comment by Iamafnan** [comment]
I have added a new repository which provides NVIM 0.7.0-dev

**Comment by CanKolay5677** [comment]
How?

**Comment by Iamafnan** [comment]
See this repo https://github.com/MrAdityaAlok/mradityaalok.github.io

**Comment by kyazdani42** [comment]
duplicate of #769 , closing this one :)
