### ISSUE TITLE
Custom icons do not replace the default after saving.

### ISSUE THREAD

**Issue by CleoMenezes** [kyazdani42/nvim-tree.lua#844]
**OS**
Fedora Workstation 35

**Neovim version**
0.5.1

**Nvim-tree version**
origin/master

**Describe the bug**
custom icons do not replace the default after saving. Am I doing something wrong?

**To Reproduce**
![image](https://user-images.githubusercontent.com/54215258/145843912-f2f8ffc1-d59f-4c0a-af59-f8bff3e6ed30.png)

**Comment by gegoune** [comment]
After saving what? Buffer to disk? It will not work unless you source the file and reinitialise nvim-tree (if that's even possible, never tried — just restart nvim).

**Comment by kyazdani42** [comment]
setup must be called after setting g: variables, it's documented though :smile:
