### ISSUE TITLE
Git highlight and icon doesn't appear on file

### ISSUE THREAD

**Issue by fedepujol** [kyazdani42/nvim-tree.lua#845]
**OS**
Windows 10

**Neovim version**
NVIM v0.6.0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compiled by runneradmin@fv-az152-703

**Nvim-tree version**
master branch

**Describe the bug**
When doing simple editing task on a file (changing and adding new lines) or delete the file or folder. The git status (highlight and icon) doesn't go all the way to the file and stops on the first folder.

![image](https://user-images.githubusercontent.com/26419570/145869047-be427a08-8577-41ec-bc2b-b7fef8bb9495.png)

I've modified the init.lua from the terminal folder and it doesn't get the highlight or the icon for the git status. However this doesn't happen on my linux machine.

**To Reproduce**
Modify/delete/add a new file/folder to current directory

**Expected behavior**
Get git highlight and icon for modified files/folder

**Comment by kyazdani42** [comment]
I'm not sure how to debug this, i do not have a windows environment to test this :/ maybe you could give it a try if you are good enough with windows debugging :smile:

**Comment by fedepujol** [comment]
I could try with some pointers! The strange thing is that it used to work on an older version (not sure which commit but I'll try to identify when it goes away). 

Where will be a good place to start debugging this?

**Comment by whitestarrain** [comment]
OS: win10
Neovim Version: V0.6.0

I have the same problem. but after reverting back to "08a29d3",it was fine.
Although the font color has changed to green.

![uTools_1639817224610](https://user-images.githubusercontent.com/55945266/146635294-89ff6d09-14a2-461f-b66f-03fbf583c0fe.png)

**Comment by gmr458** [comment]
For me on Windows, Git highlight only works on project root files and folders, but the files inside those folders don't have Git highlight.

In the image below the base.html file has been modified, but it is not highlighted, only the folder that contains it.
![image](https://user-images.githubusercontent.com/53343401/147373027-de4e8af4-4aaf-49fb-9116-82f768e588c5.png)

**Comment by tristone13th** [comment]
OS: win11
Neovim Version: V0.6.0

I have the same problem too.

**Comment by fedepujol** [comment]
@kyazdani42 The problem is how it handle the forward/backward slashes in Windows. It doesn't change all the all of them. 
I've modified this files and they begin to appeared like this:

```text
C:\Users\fp\AppData\nvim-data\site\paq\packs\start\nvim-tree.lua\lua/nvim-tree/git
C:\Users\fp\AppData\nvim-data\site\paq\packs\start\nvim-tree.lua\lua/nvim-tree/git/init.lua
C:\Users\fp\AppData\nvim-data\site\paq\packs\start\nvim-tree.lua\lua/nvim-tree/git/utilslua
C:\Users\fp\AppData\nvim-data\site\paq\packs\start\nvim-tree.lua\lua/nvim-tree/populate.lua
```

After a changing all backward slashes to forward slashes, the issue goes away.
