### ISSUE TITLE
Nvim-tree crash when I open a file in 'nvim-spectre' search result by pressing Enter

### ISSUE THREAD

**Issue by TeibbyZhang** [kyazdani42/nvim-tree.lua#846]
**OS**
macOS 12.0.1

**Neovim version**
NVIM v0.7.0-dev+704-gac2d140a3

**Nvim-tree version**
master

**Describe the bug**
If I have installed plugin 'lualine' by packer, lualine will get a error and I need quit nvim to resolve it, else I will be hard to do some actions in buffer.

![image](https://user-images.githubusercontent.com/26619125/145975011-fc43d11b-23e2-4aeb-abb0-9280a1f0425b.png)

**To Reproduce**
1. Install plugins: 'nvim-tree.lua', 'lualine', 'nvim-spectre';
2. Set `vim.g.nvim_tree_quit_on_open = 0`;
2. Open a project by cmd `nvim .`;
3. Search words by plugin 'nvim-spectre';
4. Choose one of search result and press `Enter`.

**Expected behavior**
I can do any actions as usually.

**Comment by kyazdani42** [comment]
hi @TeibbyZhang, sorry for the late answer, does this still happen to you ?

**Comment by alex-courtis** [comment]
Cannot reproduce. Looks to be a lualine issue, which has had a lot of commits in 2022.

Please reopen if you experience further issues.
