### ISSUE TITLE
Icon error

### ISSUE THREAD

**Issue by yueduz** [kyazdani42/nvim-tree.lua#849]
**OS**
archlinux

**Neovim version**
NVIM v0.6.0

**Nvim-tree version**
commit f408781a463c2edc3a49091b1bca5a18f790ee3d (grafted, HEAD -> master, origin/master, origin/HEAD)

**Describe the bug**
Icon error
![2021-12-16 18-54-51 的屏幕截图](https://user-images.githubusercontent.com/1448159/146360420-f1d82f16-3086-446b-bfff-c13655e17622.png)

**Comment by gegoune** [comment]
Seems like your font is not patched with nerd icons.

**Comment by yueduz** [comment]
![2021-12-16 19-47-27 的屏幕截图](https://user-images.githubusercontent.com/1448159/146366229-dcc594be-93bd-482f-8c26-006c30c11739.png)
I installed the font from https://www.nerdfonts.com/font-downloads, the file icon is displayed, but the other icons are still ugly.

The fonts on https://www.nerdfonts.com/font-downloads are patched, right?

**Comment by gegoune** [comment]
I would think so. Try some other font maybe?

**Comment by bryant-the-coder** [comment]
Try agave nerd font or hack nerd font. that works for me and i hope it helps :D

**Comment by yueduz** [comment]
> Try agave nerd font or hack nerd font. that works for me and i hope it helps :D

This looks better, but there are still some files without an icon. I think it should display a placeholder icon of an unknown file type. But nvim-tree seems to be an unknown class designed without an icon

**Comment by bryant-the-coder** [comment]
Can u show the non icon file?

**Comment by yueduz** [comment]
![2021-12-18 09-31-08 的屏幕截图](https://user-images.githubusercontent.com/1448159/146624519-9815ad22-df83-400a-ad55-226df4b97f21.png)

**Comment by bryant-the-coder** [comment]
Base on  my understanding, it is because they start with a .?

**Comment by bryant-the-coder** [comment]
Like.fultter or mayb the devicons doesnt support it

**Comment by vuki656** [comment]
@yueduz since those files don't have a recognizable file extension no icon is applied.

You can use the following setting to set the default fallback icon 

```lua
vim.g.nvim_tree_icons = {
    default = "",
}
```

Be sure to put that before the `setup` call.

**Comment by kyazdani42** [comment]
For proper font support, lets say you use something like `Noto sans mono`, you must install `Noto Sans Mono Nerd Font` and setup this font in your terminal. See [this list of font](https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts) to check if yours is supported.
