### ISSUE TITLE
Probable typo on README

### ISSUE THREAD

**Issue by cheeze2000** [kyazdani42/nvim-tree.lua#850]
**OS**
Operation system's name and version
Ubuntu 20.04.3 LTS
focal

**Neovim version**
NVIM v0.6.0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

**Nvim-tree version**
[0aec64d](https://github.com/kyazdani42/nvim-tree.lua/commit/0aec64d56c9448a039408228d410a01c41125d48)

**Describe the bug**
There seems to be a typo on the README, precisely on the [Settings](https://github.com/kyazdani42/nvim-tree.lua#settings) section.
```lua
{ key = "<BS>",                         cb = tree_cb("close_node") },
{ key = "<S-CR>",                       cb = tree_cb("close_node") },
```
I don't think both of these do the same thing. `<BS>` seems to "close_node" but `<S-CR>` feels like a "toggle_node" to me.

**To Reproduce**
Make a folder called A and have a folder B inside. Doing `<BS>` on B (while the folder is closed) will collapse A. On the other hand, doing `<S-CR>` will open B.

**Expected behavior**
Since they are documented exactly the same way, they should do the same thing. It might be a typo.

**Comment by kyazdani42** [comment]
look like it doesn't have anything to do, S-CR does not exist as far as i'm aware. Thanks for the notice, i'll remove it.
