### ISSUE TITLE
Is there a way to swap between drives in Windows 10?

### ISSUE THREAD

**Issue by ObsidianChickenz** [kyazdani42/nvim-tree.lua#852]
Is there any way for me to switch between C:\ and D:\ within nvim-tree?

**Comment by kyazdani42** [comment]
Hi, sorry for the late answer.
I think if you just `:cd D:\` it will do ?

**Comment by kyazdani42** [comment]
closing since no news.

**Comment by fukwho** [comment]
This should be reopened this still is a current issue. I have tried refreshing NvimTree, closing it and reopening but the `:cd D:\` command won't work.

**Comment by kyazdani42** [comment]
Could you open a proper issue ? There is almost no description in there and really hard for anyone to reproduce this and the author did not give any news since december.
