### ISSUE TITLE
Help wanted

### ISSUE THREAD

**Issue by bryant-the-coder** [kyazdani42/nvim-tree.lua#861]
Hi, i wanna ask how to lazy load nvim-tree? It throws me an error saying cant require nvim-tree.

**Comment by kyazdani42** [comment]
I'm not sure, i do not lazy load nvim-tree. Lazy loading support is partial at the moment, so i don't particularly recommend it. If you try to improve your startup time, try https://github.com/lewis6991/impatient.nvim
