### ISSUE TITLE
Having option to grow window width automatically

### ISSUE THREAD

**Issue by DanielCardonaRojas** [kyazdani42/nvim-tree.lua#865]
Would be awesome if the window could resize itself as more directories get opened when there is not enough space.

I thought out auto_resize would accomplish this but that seems to have another purpose.

**Comment by kyazdani42** [comment]
Sound like a very good idea, auto_resize is just to keep the size of the tree set by the user. I think you could work out something in the meantime by giving a function to the `width` parameter of nvim-tree.view and try to compute the length of the buffer ?
