### ISSUE TITLE
Staged folder is not shown as staged with git  icons after staging it

### ISSUE THREAD

**Issue by MarkoSagadin** [kyazdani42/nvim-tree.lua#869]
**OS**
`5.10.84-1-MANJARO`

**Neovim version**
```
NVIM v0.6.0
Build type: Release
LuaJIT 2.0.5
Compiled by builduser
```

**Nvim-tree version**
`0a2f6b0`

**Describe the bug**
I have started changing the git icons that are shown in the nvim-tree and I have noticed that that the git icon in-front of a folder does not change from a cross to a check tick when I add a folder with `git add`. I commented out any extra options and tried out to get the git signs working just with minimal configuration:
```
local status_ok, nvimtree = pcall(require, "nvim-tree")
if not status_ok then
	return
end

nvimtree.setup({})
```
 The problem still persists.

Below picture shows what I mean, before calling `git add lua` the icons are like this:
![image](https://user-images.githubusercontent.com/41839945/147372991-96bd64a9-cc2a-4745-bb95-7cc0157f54aa.png)

After I run `git add lua` the icons change like this:

![image](https://user-images.githubusercontent.com/41839945/147373013-d275bec0-015e-40c7-b366-4e5483dc38fb.png)

As you can see the files in the folder as properly checked as added, but the folders are not.

**Comment by MarkoSagadin** [comment]
Additionally I have not found this in the Readme, but is the Nvim tree supposed to refresh itself? In order to see changes in the git signs I either have to restart neovim or manually call `:NvimTreeRefresh` command.

**Comment by peeeyow** [comment]
Same issue on my side. I tried experimenting on `nvim_tree.setup.git.timeout` and `g:nvim_tree_git_hl` both did not work.  But weirdly enough, saving the staged file again, refreshes the git status in nvim-tree.

**Comment by kyazdani42** [comment]
nvim-tree doesn't refresh itself if using an external git command, it refreshes itself when using either `neogit` or `fugitive`.
This should be implemented, it is not yet, that's why it's showing 'dirty' instead of 'staged'.
