### ISSUE TITLE
[Discussion] How to open file in last active window?

### ISSUE THREAD

**Issue by dzintars** [kyazdani42/nvim-tree.lua#870]
Sometimes i need to compare multiple files which are open in several windows.
How can i select the window and open file in that specific window?
I believe this was somehow handled in NerdTree by remembering last active window.
In nTree every vsplit or hsplit creates new split which is fine.
But Enter or mouse click always uses top left window to open file.
I would like to control this behavior somehow.

**Comment by kyazdani42** [comment]
did you find the behavior ? it's implemented through the window picker
