### ISSUE TITLE
[auto-close bug] nvim quits when switching branches with the git-worktree plugin

### ISSUE THREAD

**Issue by lpanebr** [kyazdani42/nvim-tree.lua#871]
**OS**
`Ubuntu 20.04`

**Neovim version**
```
NVIM v0.7.0-dev+674-g24f9463dd
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by root@cortex

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"
```

**Nvim-tree version**
`* 0a2f6b0 kiyan: fix(dirchange): do not change dir when switching windows -   (grafted, HEAD -> master, origin/master, origin/HEAD) (14 hours ago)`

**Describe the bug**
`nvim quits when switching branches with the ThePrimeagen/git-worktree.nvim plugin.[1]`
[1] https://github.com/ThePrimeagen/git-worktree.nvim

**To Reproduce**
```
1. have nvim-tree installed
2. install nvim-telescope/telescope.nvim
3. install ThePrimeagen/git-worktree.nvim
4. configure a project for working with worktrees and try switching branches
```

**Expected behavior**
`nvim should not exit.`

**Comment by kyazdani42** [comment]
Hi ! do you have the `auto_close` option activated ?

**Comment by lpanebr** [comment]
it works. Thanks!
