### ISSUE TITLE
Weird behavior when changing buffers while notify popup is still present

### ISSUE THREAD

**Issue by dkeithdj** [kyazdani42/nvim-tree.lua#872]
With reference to issue #859

It works fine now, although there's some weird behavior where the popup will freeze when a new buffer is opened
but you can just CTRL-W-O it to close the popup. Not that I get errors often but there's that.

NOTE: This bug only occurs when you start nvim with nvim-tree such as `nvim .`

**Added gif for visualization**
![nvimRecordRecord](https://user-images.githubusercontent.com/42316655/147380702-0729c35c-f64a-444d-b887-aff99484b6cc.gif)

**Comment by kyazdani42** [comment]
Hi !
is this issue still present ?

**Comment by dkeithdj** [comment]
Hello, it's somewhat fine now, I can move through the file, but the notify popup won't close, it just stays there.

**Comment by kyazdani42** [comment]
Are you sure this is caused by nvim-tree ? I don't see why it would conflict with the notifier

**Comment by dkeithdj** [comment]
I think it's not with nvim-tree anymore, but will close now, as I can just <c-w>o it. Thankss
