### ISSUE TITLE
Why the `.config` file will be ignored by default?

### ISSUE THREAD

**Issue by nyngwang** [kyazdani42/nvim-tree.lua#879]
As title.

**Comment by nyngwang** [comment]
I just resolved the issue. I think the culprit is the `timeout` in the _default option_:

```
-- I didn't add the following fields inside `.setup { ... }`
-- git = {
--   enable = true,
--   ignore = true,
--   timeout = 500,
-- },
```

But the problem, i.e. A newly created file `.config`, which is not in the `.gitignore`, is not shown in the file tree.

```
git = {
  ignore = false,
},
```

**Comment by kyazdani42** [comment]
you dotfiles might be hidden `:help nvim-tree.filters` -> .dotfiles
