### ISSUE TITLE
The option `cb = tree_cb("trash")` broken

### ISSUE THREAD

**Issue by nyngwang** [kyazdani42/nvim-tree.lua#881]
**OS**
macOS

**Neovim version**
NVIM v0.7.0-dev+797-gb218d02c4

**Nvim-tree version**
lastest

**Describe the bug**
The option `cb = tree_cb("trash")` broken. After I pressed `y` the file is not moved to the trash can.

**Comment by harrisoncramer** [comment]
I thought this as well, but it turns out the implementation relies on a separate command line tool. You can install it with NPM, here: `https://github.com/sindresorhus/trash-cli`

**Comment by hermitmaster** [comment]
It would be nice to have this documented.

**Comment by kyazdani42** [comment]
I think it's already documented :
```
  - |trash.cmd|: the command used to trash items (must be installed on your system)
      type: `string`
      default: `"trash"`
```
closing this because its not broken :smile:
