### ISSUE TITLE
[question] how to open file into :vnew split using mouse

### ISSUE THREAD

**Issue by zigotica** [kyazdani42/nvim-tree.lua#882]
NOT A BUG

Hi, 

Is there a way to open a file into a previously open (and active) split (:vnew) by using the mouse? I keep getting asked to pick a window, which is really annoying. I know I can C-v using the keyboard to open a file into a new split, but it's not exactly the same. 

Thank you.

**Comment by kyazdani42** [comment]
maybe disable the `window_picker`, and bind your `<2-LeftMouse>` to the `vsplit` action in nvim-tree's mappings.
closing this in the meantime, if you cannot make it work tell me i'll reopen :)
