### ISSUE TITLE
[Question] Is there a way to control font weight for directories?

### ISSUE THREAD

**Issue by dzintars** [kyazdani42/nvim-tree.lua#883]
![image](https://user-images.githubusercontent.com/547420/148053677-a7a8070b-0106-4bb8-9d5c-c962973f56e2.png)
Not sure is that an issue of a theme as i don't use other themes, but i found that font weight of a directories is too distracting. Is there an option to make it regular font?
Also would like to make those guidelines less noticeable but still visible.
Any ideas?

**Comment by kyazdani42** [comment]
`:hi NvimTreeFolderName guifg=#yourcolor gui=NONE`
