### ISSUE TITLE
Unrecognized git state "T ".

### ISSUE THREAD

**Issue by miki725** [kyazdani42/nvim-tree.lua#885]
**OS**
Operation system's name and version

```
➜ cat /etc/*release
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
LOGO=archlinux-logo
```

**Neovim version**
output of `nvim --version`

```
➜ nvim --version
NVIM v0.6.1
```

**Nvim-tree version**
nvim-tree branch, commit or tag number

```
0a2f6b0b6ba558a88c77a6b262af647760e6eca8
```

**Describe the bug**

I get `Unrecognized git state "T ".` when opening tree

**To Reproduce**

Steps to reproduce the behavior

Not quite sure. I moved multiple files around. not even sure which file is causing the issue. how do I find the `T ` string in shell manually?

**Expected behavior**

**Comment by kyazdani42** [comment]
hum, this is strange.
`T = file type changed (regular file, symbolic link or submodule)`
Not sure what icon/color to set to this :smile:
