### ISSUE TITLE
ftplugin/NvimTree.lua always gets loaded

### ISSUE THREAD

**Issue by Zangetsu101** [kyazdani42/nvim-tree.lua#886]
**OS**
Ubuntu 20.04.3 LTS

**Neovim version**
NVIM v0.6.0

**Nvim-tree version**
0a2f6b0b6ba558a88c77a6b262af647760e6eca8

**Describe the bug**
So I have a ftplugin for NvimTree which gets loaded even if I start neovim with just "nvim" command.
Also I wasn't able to set the option "vim.wo.cursorline = true" from this script for whatever reason.

**To Reproduce**
1. Create a file ~/.config/nvim/after/ftplugin/NvimTree.lua
2. Start neovim with "nvim"
3. Run ":scriptnames" and the NvimTree.lua file should be there.

**Expected behavior**
The NvimTree.lua script should not have been loaded now should it?

**Comment by kyazdani42** [comment]
Hi, indeed, buffer/window management is a bit weird, because the buffer is loaded only once thus loading related files on startup...
I'll fix this issue in the next weeks. 
To set cursorline in the tree you could just:
`require'nvim-tree.view'.View.winopts.cursorline = true`

**Comment by Zangetsu101** [comment]
That worked. Thanks!
Is that documented somewhere?

**Comment by kyazdani42** [comment]
It is not, but since i'm planning a lot of small refactorings, i'll be writing a new documentation afterwards.

**Comment by kyazdani42** [comment]
closing this. By the way, now that the tree buffer is not hidden but destroyed and created you would be able to bind autocmd to it, and it would behave as expected.
