### ISSUE TITLE
gitignore support seems to be broken

### ISSUE THREAD

**Issue by johnnovak** [kyazdani42/nvim-tree.lua#888]
**OS**
Win 10, Mac OS X Big Sur

**Neovim version**
NVIM v0.6.0-dev+563-gb74916cfd
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az32-619

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info

**Nvim-tree version**
latest

**Describe the bug**
The gitignore support doesn't work, I'm using the default config from the README which should have gitignore support enabled by default. But enabling it explicitly doesn't do anything either.

**Comment by Abdelrahman-Shaddad** [comment]
I had this problem also. It appears after commit (6662b60a2bb55f0c1eca4db54cba5c57c2b2daff)

**Comment by johnnovak** [comment]
Hmm, no followup?

**Comment by kyazdani42** [comment]
hi, sorry for the late answer. I had hard time to maintain the issues of my open source project since a few months...
I'm might be more present starting february. I'll not be able to do anything next week as I'm taking holidays.
Please be patient, this is not my job I maintain it when I have some free time :)

**Comment by johnnovak** [comment]
Sure, thanks for the reply. It's just a quite basic important feature, and it has been flip-flopping between functional and completely broken for the past few months, that's all.

**Comment by kyazdani42** [comment]
Hi @johnnovak, gitignore support works fine for me, i think there was a windows fix merged for the git support lately, could you confirm this bug is still accurate ?

**Comment by johnnovak** [comment]
Thanks, I've just updated and can confirm that the bug seems to be gone, the gitignore file seems to be handled correctly. I'll report back if I find anything strange, but this seems promising. Great work!
