### ISSUE TITLE
How to disable nvim-tree.system_open

### ISSUE THREAD

**Issue by angarc** [kyazdani42/nvim-tree.lua#898]
**OS**
Operation system's name and version
Mac OS Monterrey 12.1

**Neovim version**
NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Monterey

**nvim-tree version**
Not sure how to check this, but I'm pulling in the plugin like this:
```lua
  use {
    'kyazdani42/nvim-tree.lua',
    requires = {
      'kyazdani42/nvim-web-devicons', -- optional, for file icon
    },
    config = function() require'nvim-tree'.setup {
      view = {
        auto_resize = true
      }
    } end
  }
```

This isn't really a bug, but I want to disable nvim-tree.system_open. Whenever I click "s" while nvim-tree is open and I'm in it, VSCode opens which is very annoying for my setup since I navigate vim windows with s in conjunction with a direction key such as sj sk sl or sh to move around the windows.

I tried looking in the config using `:h nvim-tree.system_open` and noticed that there are two options: `cmd` and `args` but both are set to `nil` and `{}` respectively by default, so I don't think those would help me.

If this isn't possible, is there a way to bind it to another key besides "s"?

Thanks!

**Comment by kyazdani42** [comment]
just disable the binding in the setup :) `:help nvim-tree.view` > view.mappings.list
