### ISSUE TITLE
Open NvimTree for a given path

### ISSUE THREAD

**Issue by quantum-booty** [kyazdani42/nvim-tree.lua#900]
I could get the path for a file using telescope, it would be cool if I could open NvimTree under that path.
using an api like:
```:NvimTreeOpen "/path/to/file_or_folder"```

**Comment by kyazdani42** [comment]
this has been asked many times, closing this because duplicate :)

**Comment by quantum-booty** [comment]
> this has been asked many times, closing this because duplicate :)

Could you please link the issue that tracks this? Ty!

**Comment by kyazdani42** [comment]
https://github.com/kyazdani42/nvim-tree.lua/issues/104
