### ISSUE TITLE
NvimTreeGitIgnored highlight group not working

### ISSUE THREAD

**Issue by devkvlt** [kyazdani42/nvim-tree.lua#903]
**OS**
macOS 12.1

**Neovim version**
v0.6.0

**Nvim-tree version**
Latest

**Describe the bug**
I set the following in my config but it has no effect. 
```
highlight NvimTreeGitIgnored guifg=#4B5262
```
Note: all the other highlighting groups that I set for NvimTree are working fine.

**To Reproduce**
Create file `foo`, add it to `.gitignore` then open NvimTree.

**Expected behavior**
The file `foo` should be highlighted with the color set for `NvimTreeGitIgnored`.

**Comment by kyazdani42** [comment]
did you manage to fix this ?

**Comment by devkvlt** [comment]
Yes
