### ISSUE TITLE
Integrated with which-key.nvim

### ISSUE THREAD

**Issue by defpis** [kyazdani42/nvim-tree.lua#905]
Can I bind a set of key mappings with which-key.nvim rather than config in nvim-tree’s options?

**Comment by kyazdani42** [comment]
I'm not sure what you mean by that ?

**Comment by alex-courtis** [comment]
For inspecting mappings, you can set the `buffer` [option](https://github.com/folke/which-key.nvim#-setup) in which-key, however that probably won't help you, as nvim-tree's buffer number will change.

You could clear all nvim-tree mappings and create which-key [mappings](https://github.com/folke/which-key.nvim#%EF%B8%8F-mappings) however once again, that needs a buffer number.

What you really need is the ability to set mappings for a buffer name regex i.e. `^NvimTree`. You could raise a feature request or PR for which-key.

**Comment by alex-courtis** [comment]
As an experiment, try setting up which-key to use bufnr 2, which is the number that nvim-tree will start with. Providing you don't open/close many windows it will be enough to prove the concept.

**Comment by alex-courtis** [comment]
@defpis have you experimented with which-key as above?

**Comment by alex-courtis** [comment]
Please reopen if you have any further information or questions.
