### ISSUE TITLE
Some default commands are broken after 4d22f9487da8d0a27b511fcc5d2741e93c43afcb

### ISSUE THREAD

**Issue by LoydAndrew** [kyazdani42/nvim-tree.lua#908]
**OS**
Ubuntu 20.10 x86_64

**Neovim version**

0.6.1

**Nvim-tree version**
latest

**Describe the bug**
Command quit with a default q keybinding produces error 
`E5108: Error executing lua ...acker/start/nvim-tree.lua/lua/nvim-tree/actions/init.lua:45: attempt to call field 'close' (a nil value)
stack traceback:
        ...acker/start/nvim-tree.lua/lua/nvim-tree/actions/init.lua:45: in function 'on_keypress'
        [string ":lua"]:1: in main chunk
`
Command g? produces error 
`E5108: Error executing lua vim/shared.lua:201: t: expected table, got nil
stack traceback:
        [C]: in function 'error'
        vim/shared.lua:608: in function 'validate'
        vim/shared.lua:201: in function 'tbl_filter'
        ...cker/start/nvim-tree.lua/lua/nvim-tree/renderer/help.lua:7: in function 'compute_lines'
        ...cker/start/nvim-tree.lua/lua/nvim-tree/renderer/init.lua:394: in function 'draw'
        ...te/pack/packer/start/nvim-tree.lua/lua/nvim-tree/lib.lua:48: in function 'on_keypress'
        [string ":lua"]:1: in main chunk
`
**To Reproduce**
My nvim-tree config
```lua

nvim_tree.setup({
    disable_netrw = true,
    higack_netrw = true,
    tree_follow = true,
    auto_close = true,
    update_cwd = true,
    tree_respect_buf_cwd = true,
    filters = {
        custom = {
            ".git",
            "node_modules",
            ".cache",
            "__pycache__",
            ".vscode",
            ".mypy_cache",
            ".idea",
        },
    },
    diagnostics = {
        enable = true,
        icons = {
            hint = "",
            info = "",
            warning = "",
            error = "",
        },
    },
    view = {
        width = 50,
        height = 50,
        side = "left",
        auto_resize = true,
    },
    follow_update_path = true,
    update_focused_file = {
        enable = false,
        update_cwd = true,
        ignore_list = {},
    },
})

```

**Expected behavior**
Default keybinding should be working.

**Comment by AnthonyK213** [comment]
Same. And `view.mappings.custom_only` doesn't work as well.

**Comment by Allaman** [comment]
quick workaround
```
cd ~/.local/share/nvim/site/pack/packer/start/nvim-tree.lua (or wherever your path is set to)
git checkout dc5eae65123c41908139cf6f095a062760604414
```
