### ISSUE TITLE
action_cb function in mapping

### ISSUE THREAD

**Issue by tsivinsky** [kyazdani42/nvim-tree.lua#918]
Hey, I'm trying to configure my nvim-tree config and want to add mapping for staging files. For that I need path to file relative to root directory but the only thing in node parameter is absolute path (as documentation says).

![image](https://user-images.githubusercontent.com/48863576/151607768-e124b56d-4445-4400-b0e4-455d15f921f4.png)

noob here. I don't know if i can somehow print lua table in neovim (i know about vim.inspect but it doesn't work here)

Thanks in advance!

**Comment by kyazdani42** [comment]
Hi ! there is no relative path that you can use in the node, but you can transform the absolute path with `:help fnamemodify` i believe. 
Otherwise you could just remove the first `n` characters of the string based on the length of the current pwd `vim.loop.cwd` or `:help :cwd`

**Comment by tsivinsky** [comment]
ok thanks
