### ISSUE TITLE
Svg icon is not displayed correctly

### ISSUE THREAD

**Issue by redfox-mx** [kyazdani42/nvim-tree.lua#920]
**OS**
Windows: Git bash (but i work over ssh session on xterm and ubuntu 20.04)

**Neovim version**
NVIM v0.6.0

**Nvim-tree version**
version match with commit id 2dfed89af7724f9e71d2fdbe3cde791a93e9b9e0

**Describe the bug**
Into NvimTree buffer file name is displayed in the opposite side of window and icon is displayed after file name (normal behavior is before)

![image](https://user-images.githubusercontent.com/20145660/151688831-fd4455ce-14df-4229-9b13-fdf4ef69b6a1.png)

![image](https://user-images.githubusercontent.com/20145660/151688847-e283cfce-d0b5-4a5c-893d-7fd5ef5ec177.png)

**To Reproduce**
init.vim
```vimL
plug#begin()

Plug 'kyazdani42/nvim-tree.lua'
Plug 'kyazdani42/nvim-web-devicons'

plug#end()
```
in after/plugin/nvimtree.lua
```lua
local g = vim.g

g.nvim_tree_show_icons = {
  git = 0,
  folders = 1,
  files = 1,
}

g.nvim_tree_root_folder_modifier = ':t'

g.nvim_tree_icons = {
  folder = {
    -- i chose arrows and chain icon for folders
  }
}

local nvim_tree = require'nvim-tree'
nvim_tree.setup({
  update_cwm = false,
  view = {
    autoresize = true
  }
}
```

**Expected behavior**
icons display normaly ? sorry, my English is not so good hahaha 

**Aditional info**
Node info (nvim-tree.lib.get_node_at_cursor)
```lua
{
  absolute_path = “/path/to/svg/file”,
  executable = false,
  extension = “svg”,
  git_status = “??”,
  name = “test.svg”,
}
```
nvim-web-devicon for svg (I didn't know that you have been created both repos, that's awsome)
```lua
local icons = {
  ["svg"] = {
     icon = "ﰟ",
     color = "#FFB13B",
     cterm_color = "215",
     name = "Svg",
   },
}
```

**Comment by kyazdani42** [comment]
Hi ! I'm not sure why this is happening but i have no way to test on windows unfortunately. It might be because of `rtl` characters. What happens if you set `*` as icon for the svg ?

**Comment by redfox-mx** [comment]
Works fine! About "It might be because of rtl characters." that's right, I was trying with other chars when I got the same behaviour with .babelrc. Patch fonts sometimes overlap Arabic or other rtl chars. I keep this explanation for people with the same problem

**Comment by pixelino** [comment]
I've got the same issue!

| OS | Terminal Emulator | Neovim Version | Nvim-Tree Version |
|-|-|-|-|
Windows 10 WSL | wintty | v.0.6.1 | latest |

Note: on Windows Terminal, this displays correctly (but other rendering issues occur in other plugins, which is why I don't use it)

![nvim-tree svg bug](https://user-images.githubusercontent.com/48772672/158691858-115450d6-8297-4500-b322-1383b3929dc4.PNG)

**Comment by redfox-mx** [comment]
> I've got the same issue!
> 
> OS	Terminal Emulator	Neovim Version	Nvim-Tree Version
> Windows 10 WSL	wintty	v.0.6.1	latest
> Note: on Windows Terminal, this displays correctly (but other rendering issues occur in other plugins, which is why I don't use it)
> 
> ![nvim-tree svg bug](https://user-images.githubusercontent.com/48772672/158691858-115450d6-8297-4500-b322-1383b3929dc4.PNG)

Thats no related to this plugin. It's all about your terminal emulator and your font. You can provide other symbols for svg extension and open a issue in wintty
