### ISSUE TITLE
Nvim-tree doesn't replace empty buffer

### ISSUE THREAD

**Issue by BlueDruddigon** [kyazdani42/nvim-tree.lua#921]
**OS**
Ubuntu 20.04

**Neovim version**
NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3

**Nvim-tree version**
nvim-tree master branch

**Describe the bug**
There is an empty buffer that appeared when opening nvim alongside with nvimtree buffer. What I expected the plugin does is when selecting a file from NvimTreeToggle buffer, that file will be opened in the position of the empty buffer if an empty buffer was represented. I don't know where this bug comes from but in ```dc630d199a0ad593036d193232c6b338aa0407e3``` and previous this issue does not exist! In the latest version of the plugin, I haven't recognized which of my config causes this.

**To Reproduce**

https://user-images.githubusercontent.com/39997524/151690471-00fd5b78-9b95-471c-a3b4-bcd253bbd9e9.mov
Here is the latest (branch master) version of nvim-tree plugin's behavior. And you will see that at the upper bar, the buffer will not be replaced like the video I provided below.

**Expected behavior**
Here is the result that I am expected the plugin does.
https://user-images.githubusercontent.com/39997524/151690444-2e22f13c-e97d-42e4-a407-49b43913159e.mov

Hope for your reply.

**Comment by kyazdani42** [comment]
Hi, I think your solution might work. I've been struggling to remove this empty buffer because it causes all sorts of strange behaviors.
I'll implement your solution when i have some time :)

**Comment by BlueDruddigon** [comment]
Glad to hear that from you, Kyaz!
Hope for your latest implementation!
Thank you!

**Comment by BlueDruddigon** [comment]
Thank you for your commitment!
But at the latest commit, the plugin works fine for git source locations but the normal directory didn't!
Could you fix that plz?

**Comment by kyazdani42** [comment]
i didn't understand that. What do you want me to fix ?

**Comment by kyazdani42** [comment]
it is already

**Comment by BlueDruddigon** [comment]
The behavior of the plugin is still the same for the normal directory tree, except the directory that contains the ```.git``` folder (the git repository). Its mean that your commit fix at git repository, not included the normal directory. I want that it still works for all kind of random directory!
