### ISSUE TITLE
Hijacking or standalone mode other than fixed vsplit layout

### ISSUE THREAD

**Issue by wookayin** [kyazdani42/nvim-tree.lua#926]
**OS**: Independent of OS
**Neovim version**: Independent of neovim version

**Nvim-tree version**: Latest (99d65af)

**Describe the bug**
When nvim-tree is working as a standalone mode or hijacking netrw, it should work as if it were a normal directory buffer. However, it only works as a vertical-splitted window on the left.

**To Reproduce**

For example, run `:split .`

**Expected behavior**: This should open the directory buffer in a "non-surprising way": open the directory window in the below or as a horizontally-split window.
**Current behavior**: It opens the nvim-tree window on the left (like `:20vsplit`).

Note: Compare with other similar plugins like NERDTree, coc-explorer, etc.

**Comment by gegoune** [comment]
This has been discussed numerous times already, you can search through other issues.

**Comment by wookayin** [comment]
Sorry. I searched for a similar issues with keyword `hijack`, `standalone` but didn't get one. I've found one #782 and let me move the discussion there. Your attentions would be appreciated given that this has been asked that many times.

**Comment by wookayin** [comment]
#782 is actually a different one (though related), so I will reopen it. Can you point me to some other issues?

**Comment by wookayin** [comment]
@kyazdani42 What do you think?

**Comment by kyazdani42** [comment]
something like `:help nvim-tree.update_to_buf_dir` ?

**Comment by wookayin** [comment]
@kyazdani42 Of course this option is enabled. But when this is enabled, the nvim-tree.lua window will always open in the left. I am asking that should not be the case.

**Comment by kyazdani42** [comment]
i'm not sure i understand properly. Do you ask something like https://github.com/kyazdani42/nvim-tree.lua/issues/860 ?

**Comment by wookayin** [comment]
Yes I think #860 requests the same one. Exactly this:

>  Also, I think it would be nice if the tree could open up in the current buffer instead of opening up in a fixed position("top", "left", "right", "bottom").

I think this is more than clear, and also in this issue I've described a very clear expected/current behavior. In short, nvim-tree should open in **the correct window** rather than a fixed sidebar-like window.

Please let me know if you still cannot understand what we are requesting.

**Comment by wookayin** [comment]
Let me close this as a duplicate of #860.
