### ISSUE TITLE
[FEATURE] Refresh tree on toggle

### ISSUE THREAD

**Issue by mercxry** [kyazdani42/nvim-tree.lua#927]
Hello, lately I've noticed that often I have to refresh the tree when I toggle because it's not up to date, since it's becoming an habit I was wondering if it is possible to have an option to refresh the tree when I NvimTreeToggle?

**Comment by kyazdani42** [comment]
you could do it yourself maybe, when mapping the command, run NvimTreeRefresh | NvimTreeToggle or a custom hook to detect if the tree is already opened.
Also closing because it's already been issued i believe.
