### ISSUE TITLE
Signcolumn bg showing on selected file

### ISSUE THREAD

**Issue by boppyt** [kyazdani42/nvim-tree.lua#929]
**OS**
Operation system's name and version
NixOS 22.05.20220202.f85152d (Quokka)

**Neovim version**
output of `nvim --version`
NVIM v0.7.0-dev
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by nixbld

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/nix/store/fn8i1l9hlp8v38akrskm77w2wzyxdmcl-neovim-unwrapped-master/share/nvim
"

Run :checkhealth for more info

**Nvim-tree version**
nvim-tree branch, commit or tag number
commit 99d65afd6ef05cc57f835451126e5c44db03cef1

**Describe the bug**
NvimTree shows Signcolumn highlight group's guibg color on the selected file/folder entry.

**To Reproduce**
Steps to reproduce the behavior
1. Open Nvimtree
2. See the signcolumn getting highlighted on the active entry

**Expected behavior**
Not sure if this is intentional, but I would expect it to not show the signcolumn's bg since it seems to be reserved for only diagnostics.
![image](https://user-images.githubusercontent.com/71049646/152477041-37e651d5-c845-43ec-a266-5325a6f605e3.png)

**Comment by kyazdani42** [comment]
Hi, i'm not sure about this to be honest. Could you provide a minimal config to reproduce this ?

**Comment by boppyt** [comment]
This seems to happen when you set `vim.opt.cul` to `true`.

Reproducible with https://github.com/kyazdani42/nvim-tree.lua#setup + jellybeans.vim colorscheme set

**Comment by boppyt** [comment]
I'm mostly confident that this is an issue on my end, closing.

**Comment by boppyt** [comment]
Upon further research I've found that the `number` option in `culopt` causes this problem (the default is `number,line`)

![image](https://user-images.githubusercontent.com/71049646/152772118-6f230d91-95a0-464e-9ca1-3e83d9008afc.png)
You can see that the part before the text has different color than the actual cursorline, which I believe is the color of the numbers.

The minimal config is the following:
```
require("packer").startup(function()
	use "kyazdani42/nvim-tree.lua"
	use "nanotech/jellybeans.vim"
end)

vim.opt.number = true
vim.opt.numberwidth = 2
vim.opt.cul = true
vim.opt.mouse = "a"

vim.cmd [[ colorscheme jellybeans ]]

vim.g.nvim_tree_add_trailing = 0
vim.g.nvim_tree_git_hl = 1
vim.g.nvim_tree_highlight_opened_files = 0
vim.g.nvim_tree_indent_markers = 1
vim.g.nvim_tree_quit_on_open = 0
vim.g.nvim_tree_show_icons = {
    folders = 0,
    files = 0,
    git = 0,
    folder_arrows = 0
}
vim.g.nvim_tree_symlink_arrow = " -> "

require'nvim-tree'.setup {
    filters = { dotfiles = false },
    disable_netrw = true,
    hijack_netrw = true,
    auto_close = false,
    open_on_tab = false,
    hijack_cursor = true,
    update_cwd = true,
    update_focused_file = { enable = true, update_cwd = false },
    view = { allow_resize = true, side = "left", width = 25, hide_root_folder = true }
}

**Comment by boppyt** [comment]
Just to make sure I've tested this on 3 other colorschemes, same result.

**Comment by kyazdani42** [comment]
could you open a PR to fix this :) ? just need to set the option in the view.lua -> winopts config
