### ISSUE TITLE
errors opening neovim in a directory

### ISSUE THREAD

**Issue by SrWither** [kyazdani42/nvim-tree.lua#934]
**OS**
FreeBSD 13.0-RELEASE-p6 amd64

**Neovim version**
NVIM v0.6.1
Build type: Release
LuaJIT 2.0.5

**Nvim-tree version**
nvim-tree master branch

**Describe the bug**
when i open neovim in a directory, example: `nvim mygame/` i get an error about there being a null value

**To Reproduce**
`nvim .`
![image](https://user-images.githubusercontent.com/59105868/152692963-1ebab973-30c1-4729-b25c-79b79ffc947e.png)

**Expected behavior**
![image](https://user-images.githubusercontent.com/59105868/152692938-a22ca86b-6bd4-459d-8bbf-3dbdd05bc5a9.png)

**Comment by Slotos** [comment]
Main setup function, calls setup on `View`, which sets up `au BufEnter,BufNewFile * lua require'nvim-tree'.open_on_directory()`, which gets a chance to call `open_on_directory` before `on_enter` is called, thanks to use of `vim.schedule`.

Being a newbie to both lua and vim plugin development, I'm struggling to untangle the chain of events. Naive attempts "fix" the error, but break the behaviours. After a few semi-blind attempts, I managed to get a "fix" that seems to not break things, but that's probably an illusion:

```diff
diff --git a/lua/nvim-tree.lua b/lua/nvim-tree.lua
index a60acd3..d167a8b 100644
--- a/lua/nvim-tree.lua
+++ b/lua/nvim-tree.lua
@@ -184,6 +184,10 @@ function M.open_on_directory()
   end
 
   view.close()
+  if lib.Tree == nil then
+    lib.init(false, vim.fn.getcwd())
+  end
+
   if bufname ~= lib.Tree.cwd  then
     ChangeDir.fn(bufname)
   end
```

**Comment by Slotos** [comment]
@kyazdani42 I believe a simple check added in 0573c68 doesn't fix the issue in its entirety. Compare `vim +":e dir"` with `vim dir`.

```
diff --git a/lua/nvim-tree.lua b/lua/nvim-tree.lua
index a60acd3..d167a8b 100644
--- a/lua/nvim-tree.lua
+++ b/lua/nvim-tree.lua
@@ -184,6 +184,10 @@ function M.open_on_directory()
   end
 
   view.close()
+  if lib.Tree == nil then
+    lib.init(false, vim.fn.getcwd())
+  end
+
   if bufname ~= lib.Tree.cwd  then
     ChangeDir.fn(bufname)
   end
```

This seems to fix it, but I'm not sure whether I'm triggering undesired side-effects here.

**Comment by kyazdani42** [comment]
i'm fixing it, i've made quite a bunch of internal changes today x)

**Comment by kyazdani42** [comment]
should work now
