### ISSUE TITLE
Error when running NvimTreeToggle

### ISSUE THREAD

**Issue by ericlake** [kyazdani42/nvim-tree.lua#935]
**OS**
macOS Monterey 12.2

**Neovim version**
output of `nvim --version`
```
$ nvim --version
NVIM v0.6.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@BigSur

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.6.0/share/nvim"

Run :checkhealth for more info
```

**Nvim-tree version**
nvim-tree branch, commit or tag number
I am seeing this on the master branch (0573c68fd714ae23596f45fbd0f6feb023b448fb)

**Describe the bug**
Starting with commit 8a6c7bae3ae2c36aedf1724416b22724e052ffb8 I am seeing the following error.

```
Error detected while processing CursorMoved Autocommands for "NvimTree":
E5108: Error executing lua ...site/pack/packer/opt/nvim-tree.lua/lua/nvim-tree/lib.lua:64: attempt to index field 'Tree' (a nil value)
stack traceback:
        ...site/pack/packer/opt/nvim-tree.lua/lua/nvim-tree/lib.lua:64: in function 'get_node_at_cursor'
        ...vim/site/pack/packer/opt/nvim-tree.lua/lua/nvim-tree.lua:213: in function 'place_cursor_on_node'
        [string ":lua"]:1: in main chunk
Press ENTER or type command to continue
```

**To Reproduce**
Pull any commit 8a6c7bae3ae2c36aedf1724416b22724e052ffb8 or newer and then try to run `:NvimTreeToggle`.

**Expected behavior**
The expected behavior is to see the tree with no error shown. I have verified that commit 8b27fd4 does not have this same issue so it must have been a change since then.

**Comment by kyazdani42** [comment]
cannot reproduce, can you share a minimal config please ?

**Comment by ericlake** [comment]
I am using AstroVim with this config https://github.com/kabinspace/AstroVim/blob/main/lua/configs/nvim-tree.lua. This is the plugin configuration too https://github.com/kabinspace/AstroVim/blob/main/lua/core/plugins.lua#L74-L81. The only change that I have in place at the moment is to set the commit for Packer to pull.

**Comment by kyazdani42** [comment]
@ericlake i pushed a modification, could you check it works ? i could not reproduce your error

**Comment by ericlake** [comment]
@kyazdani42 I just tested with the following commit and it seems that this issue I was seeing is no longer preset.

```
commit f173d280033d55a7f932a3bc30f6aae16ece08d6 (HEAD -> master, origin/master, origin/HEAD)
Author: kiyan <yazdani.kiyan@protonmail.com>
Date:   Sun Feb 6 20:09:59 2022 +0100

    fix: remove schedule for on_enter
```

Thank you for the quick response and fix.

**Comment by kyazdani42** [comment]
there might be some instabilities next days because i made a lot of internal changes today, globally should work fine but if you encounter any issue let me know.

**Comment by ericlake** [comment]
Will do.
