### ISSUE TITLE
Indexing error when opening files

### ISSUE THREAD

**Issue by MrQuasar173** [kyazdani42/nvim-tree.lua#936]
**OS**
Arch Linux (rolling)

**Neovim version**
0.6.1

**Nvim-tree version**
923e034

**Describe the bug**
When opening a specific file, I get the following lua error:
```
Error detected while processing BufEnter Autocommands for "*":
E5108: Error executing lua ...m/site/pack/packer/start/nvim-tree.lua/lua/nvim-tree.lua:136: attempt to index field 'Tree' (a nil value)
stack traceback:
        ...m/site/pack/packer/start/nvim-tree.lua/lua/nvim-tree.lua:136: in function 'update_base_dir_with_filepath'
        ...m/site/pack/packer/start/nvim-tree.lua/lua/nvim-tree.lua:154: in function 'find_file'
        [string ":lua"]:1: in main chunk
```
Nvimtree still works after I dismiss the error, and this error doesn't come up when I open a folder or
just run neovim without a location.

The plugin appears to be working great, but the error message is still annoying

**To Reproduce**
Open neovim to a specifc folder, with nvimtree installed through packer

**Expected behavior**
The file opens without any nvimtree related errors

**Comment by kyazdani42** [comment]
should be fixed in latest master, sorry for the inconvenience there might be some instability for ~1 day because i made a lot of internal changes today.
