### ISSUE TITLE
rename in command window

### ISSUE THREAD

**Issue by jieteki** [kyazdani42/nvim-tree.lua#94]
When use `r` to rename a file/folder, in command line there is a `rename` instruction , then press `CTRL-f` enter command history window, which will bring the instruction into this window. all is good for now.

The problem is, `nvim-tree` rename action only respond when command window is in `Insert mode`, when it's in `Normal mode`, press `Enter` nothing happens, while this behavior in most other file tree plugins.

![image](https://user-images.githubusercontent.com/2155893/91029557-7fcabb00-e631-11ea-9448-7bd9723f4aef.png)

**Comment by kyazdani42** [comment]
well i'll look into it when i have some time :)

**Comment by kyazdani42** [comment]
well not sure i know why, maybe that was a neovim bug, but i cannot repro anymore. Can you ?
