### ISSUE TITLE
Opening directory with `.` not working as expected

### ISSUE THREAD

**Issue by mmerle** [kyazdani42/nvim-tree.lua#947]
**OS**
macOS 12.2

**Neovim version**
v0.6.1

**Nvim-tree version**
`d8bf1adcdcc6a8a66c3dce5c29a4ef06e21dc844`

**Describe the bug**
When opening neovim with `nvim .` a blank buffer is opened with the name of `.`

![Screen Shot 2022-02-08 at 4 31 14 PM](https://user-images.githubusercontent.com/35971019/153079012-444c22a0-a84a-4b23-9d86-628dd647bb14.png)

**To Reproduce**
`nvim .`

**Expected behavior**
Before this commit (`d8bf1adcdcc6a8a66c3dce5c29a4ef06e21dc844`) neovim would open with nvim-tree and no buffer

**Comment by jdhao** [comment]
Same issue here, directory hijack does not work anymore with the latest master of nvim-tree.lua. It just opens a file with the same name instead of opening that directory.

**Comment by carlosala** [comment]
@kyazdani42 problematic commit is 7a19c3e

**Comment by kyazdani42** [comment]
could you share the config ? I cannot reproduce with mine

**Comment by carlosala** [comment]
Try to run `nvim .`, I don't have so much config.

**Comment by kyazdani42** [comment]
don't you think i've tried that :smile: ? 
If someone can share a small config to reproduce this i will be able to fix it.

**Comment by carlosala** [comment]
ups sorry hahaha.
I am loading the plugin with `vim-plug`, and sourcing the following lua file:
```lua
require("nvim-tree").setup({
  actions = { open_file = { quit_on_open = true } },
  git = { ignore = false },
})
```
But also with clean config I have the same problem:
```lua
require("nvim-tree").setup()
```

**Comment by tiaxter** [comment]
> don't you think i've tried that 😄 ? If someone can share a small config to reproduce this i will be able to fix it.

You could try this config:
```
require('nvim-tree').setup{
  hijack_cursor = false,
  disable_netrw = true,
  hijack_netrw = true,
  open_on_setup = false,
  auto_close = true,
  open_on_tab = false,
  update_cwd = true,
  git = {
    enable = false,
  },
  update_to_buf_dir = {
    enable = true,
    auto_open = true,
  },
  system_open = {
    cmd = nil,
    args = {},
  },
  update_focused_file = {
    enable = true,
  },
  view = {
    width = 40,
    height = 40,
    side = 'left',
    auto_resize = 0,
  }
}
```
