### ISSUE TITLE
Folder structure somewhat collapses on buffer save

### ISSUE THREAD

**Issue by punowo** [kyazdani42/nvim-tree.lua#948]
**OS** 
Arch Linux 5.16.7-zen2-1-zen
**Neovim version**
```
NVIM v0.7.0-dev+1012-gef6cedf820
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/sbin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions     -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security     -fstack-clash-protection -fcf-protection -Wp,-U_FORTIFY_SOURCE -Wp,-D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/main-builder/pkgwork/src/build/config -I/home/main-builder/pkgwork/src/neovim-git/src -I/usr/include -I/home/main-builder/pkgwork/src/build/src/nvim/auto -I/home/main-builder/pkgwork/src/build/include
Compiled by main-builder
```
**Nvim-tree version**
master/latest
**Problem**
https://asciinema.org/a/0kUfPioQKjqgawNnjfUZFvvR2
On a buffer save, the tree structure inside inside the nvim-tree.lua window "collapses" showing the buffer which is closest to the tree root. I would expect nothing to change. I don't think it's a bug, I think I've just misconfigured nvim-tree.lua and I would like some help.
**Configuration**
https://0x0.st/oX_S.lua

**EDIT:** Between the recording and the posting of the lua configuration I removed
```lua
update_focused_file = {
    enable = true,
},
``` 
but I am still  able to replicate this.

**Comment by kyazdani42** [comment]
hi ! do you somehow override the `signcolumn` option in nvim-tree ? (or on bufenter somewhere ?)

**Comment by punowo** [comment]
Hi. I have
```lua 
vim.opt.signcolumn = "yes" --in my options.lua
```
and 
```lua
use(
    {
        "beauwilliams/focus.nvim",
        config = function()
            require("focus").setup(
                {
                    signcolumn = true, --in my plugins.lua
                    cursorline = false,
                    number = false
                }
            )
        end
    }
)
```
I've just tried disabling the option inside focus.nvim but I could still recreate my issue. I actually can't remember why it is this way I remember that I only wanted to show the signcolumn on the focused window.
```bash
% grep -R "signcolumn" .
./nvim/lua/plugins.lua:                         --signcolumn = true,
./nvim/lua/options.lua:vim.opt.signcolumn = "yes"
./nvim/lua/config/nvim-tree.lua:                signcolumn = "no",
```
nvim configuration files -> https://0x0.st/oXOx.zip

**Comment by kyazdani42** [comment]
sign column should be true in nvim-tree either way, it's the default. Might be something within your config ?

**Comment by punowo** [comment]
> sign column should be true in nvim-tree either way, it's the default. Might be something within your config ?
yes, it is the default but I've changed that, as you can see from my grep. I believe focus.nvim tries to force signcolumn on the nvim-tree window.

**Comment by kyazdani42** [comment]
because the signcolumn opens up and closes. I'm going to check that in the next days see if i can reproduce

**Comment by s1n7ax** [comment]
This suddely happened to me after `PackerSync`. This broke within 2 to 3 weeks. I didn't do any changes to my configuration.

**Comment by kyazdani42** [comment]
can you try #967 and tell me if this fixes things for you ?

**Comment by punowo** [comment]
> can you try #967 and tell me if this fixes things for you ?

Sorry it doesn't.

**Comment by kyazdani42** [comment]
i still cannot reproduce :/ did you completely remove focus.nvim and reran PackerCompile ?

**Comment by punowo** [comment]
> i still cannot reproduce :/ did you completely remove focus.nvim and reran PackerCompile ?
Yes.
https://asciinema.org/a/LK6vdnaXXLYCocndGBiMoNpBk

**Comment by kyazdani42** [comment]
I stumbled upon the issue completely by mistake. It's actually due to a fail reload of grouped empty directories `a/b/c`. Now that i know how to reproduce i'll be able to fix it :)

**Comment by s1n7ax** [comment]
Now when I open a dir there is nothing. Man I don't remember a time I `PackerSync`ed and `nvim-tree` just work as expected.

https://user-images.githubusercontent.com/18459807/154864113-8860ce51-deaa-444b-b532-2d3573142b72.mp4

.
