### ISSUE TITLE
error when changing directory using ```change_dir()```

### ISSUE THREAD

**Issue by jedi2610** [kyazdani42/nvim-tree.lua#952]
**OS**
OS: arch linux

**Neovim version**
```
NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Nvim-tree version**

branch: `master`
commit: latest - f938bcb3aeb52790312f8ee1d56a013d417824bc

**Describe the bug**

i'm  working on a plugin `nvim-rooter.lua` to change the directory to the project root, and when i do
```lua
require('nvim-tree.lib').change_dir(dir)
```
i get the following error:

```
Error detected while processing BufEnter Autocommands for "*":
E5108: Error executing lua ...start/nvim-tree.lua/lua/nvim-tree/actions/change-dir.lua:13: attempt to index global 'TreeExplorer' (a nil value)
stack traceback:
        ...start/nvim-tree.lua/lua/nvim-tree/actions/change-dir.lua:13: in function 'change_dir'
        ...te/pack/packer/start/nvim-rooter.lua/lua/nvim-rooter.lua:25: in function 'change_dir'
        ...te/pack/packer/start/nvim-rooter.lua/lua/nvim-rooter.lua:89: in function 'rooter'
        [string ":lua"]:1: in main chunk
```

i guess this happens because i'm calling this before `nvim-tree` is loaded. if i am not wrong ofc. is this something i should take care of (with different autocmds instead of `BufEnter`) or something on your side? (sorry this is my first plugin so i'm still learning)

EDIT: i just tried using the `InsertEnter` autocmd and this error does not show up. so it's just that `nvim-tree` is not loaded just as i suspected.

possible ways to solve this are:
1. i should use a different autocmd
2. you should check that `TreeExplorer` is not `nil`
3. set a global variable that `nvim-tree` is loaded

if you want to do something about it tell me and i'm  happy to do a PR. ty

**Comment by jedi2610** [comment]
i'm doing
```vim
autocmd BufEnter * lua vim.schedule(function() require'nvim-rooter'.rooter() end)
```
and this solves the problem. guess i can close the issue

**Comment by kyazdani42** [comment]
why do you change the tree explorer root manually ? Users of nvim-tree should just `update_cwd = true` in their config if they wish to do so :)

**Comment by jedi2610** [comment]
oh, my bad. didn't know that option existed. ty
