### ISSUE TITLE
[Bug] `NvimTreeFindFile` do not reveal file in tree

### ISSUE THREAD

**Issue by younger-1** [kyazdani42/nvim-tree.lua#953]
**OS**
Win10 19043

**Neovim version**
NVIM v0.6.1
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compiled by runneradmin@fv-az152-430
Features: -acl +iconv +tui

**Nvim-tree version**
f938bcb 2022-02-08  (HEAD -> master, origin/master, origin/HEAD) fix: cleanup all dirs when hijacking window [kiyan]

**Describe the bug**
In windows, after open any file which attached by any LS configed by `nvim-lspconfig`, `NvimTreeFindFile` do not work properly on any further opened files attached by same LS. That is I can open nvim-tree but can not reveal the file in nvim-tree.

**To Reproduce**
1. Open a file in workspace and wait a few second until LS that attaches the file completes initialization
2. Open other file attached by the same LS. Note that no matter how you open it (by `e filename` or by `telescope` or by `goto definetion` of `LS`), this file's bufname is a full path starting with lower case of driver letter which cause the problem
3. `NvimTreeFindFile` or `NvimTreeOpen` can't put the cursor in that file in nvim-tree.

**Expected behavior**
`NvimTreeFindFile` or `NvimTreeOpen` can reveal the file in nvim-tree.

**Comment by younger-1** [comment]
Relative issues:
https://github.com/neovim/neovim/issues/16331
https://github.com/neovim/nvim-lspconfig/pull/1593
https://github.com/nvim-neo-tree/neo-tree.nvim/issues/97

**Comment by kyazdani42** [comment]
could you try to see what's the output of the `TreeExplorer.cwd` in nvim-tree ? Or if you could submit a patch for it, i'm not running windows :/

**Comment by younger-1** [comment]
`TreeExplorer.cwd` is a full path starting with lower case of driver letter like `c:\Users\younger\.config\nvim\lua\young\init.lua`
