### ISSUE TITLE
Missing delete icon in g:lua_tree_icons causes unrecognised git state error

### ISSUE THREAD

**Issue by akinsho** [kyazdani42/nvim-tree.lua#96]
Currently I specify my `g:lua_tree_icons` primarily to change the default git icons. I didn't notice a `deleted` key had been added and was experiencing an error message about an
`unrecognised git state Deleted`. It turns out this was because my global variable did not include this key.

I think this issue is probably because the table isn't deep merged with the defaults.
Just wanted to raise it so it's a known issue, I will have a look if I get time at some point.

**Comment by kyazdani42** [comment]
hi ! I'll look into this when i can :)

**Comment by kyazdani42** [comment]
This is strange, i do not have this issue.
here is my config:
```lua
  vim.g.lua_tree_icons = {
    default = '',
    git= {
      unstaged = "✗",
      staged = "✓",
      unmerged = "",
      renamed = "➜",
      untracked = "★"
    },
    folder = {
      default = "",
      open = ""
    }
  }
```

**Comment by akinsho** [comment]
@kyazdani42 sorry I think what I thought was the cause is wrong since I still get it even with the icon added. Think this issue is the same as #99
