### ISSUE TITLE
fast moving in nvim tree

### ISSUE THREAD

**Issue by mikaizhu** [kyazdani42/nvim-tree.lua#962]
In my nvim config, i nmap J 5j to move faster, how i set fast move mapping in nvim tree?

**Comment by kyazdani42** [comment]
`:help nvim-tree-mappings`
> { key = "J", action_cb = function() vim.cmd":normal 5j" end }

**Comment by kohane27** [comment]
The solution is in [how to set fast moving and close buffer · Issue #964](https://github.com/kyazdani42/nvim-tree.lua/issues/964)
