### ISSUE TITLE
how to set fast moving and close buffer

### ISSUE THREAD

**Issue by mikaizhu** [kyazdani42/nvim-tree.lua#964]
Hi, i asked this question before, but i don't konw why it doesn't work for me? there are two questions i want to ask.

1. why fast moving doesn't work?

my `nvim-tree.lua` config is :
```
require'nvim-tree'.setup {
  disable_netrw        = true,
  hijack_netrw         = true,
  open_on_setup        = false,
  ignore_ft_on_setup   = {},
  auto_close           = false,
  auto_reload_on_write = true,
  open_on_tab          = false,
  hijack_cursor        = false,
  update_cwd           = false,
  update_to_buf_dir    = {
    enable = true,
    auto_open = true,
  },
  diagnostics = {
    enable = false,
    icons = {
      hint = "",
      info = "",
      warning = "",
      error = "",
    }
  },
  update_focused_file = {
    enable      = false,
    update_cwd  = false,
    ignore_list = {}
  },
  system_open = {
    cmd  = nil,
    args = {}
  },
  filters = {
    dotfiles = false,
    custom = {}
  },
  git = {
    enable = false,
    ignore = true,
    timeout = 500,
  },
  view = {
    width = 30,
    height = 30,
    hide_root_folder = false,
    side = 'left',
    auto_resize = false,
    mappings = {
      list = {
      { key = "J", action_cb = function() vim.cmd":normal 5j" end },
      { key = "K", action_cb = function() vim.cmd":normal 5k" end },
    },
},
}
}
```
after i set this, i press 'J', it can't move fast in nvim-tree files

2. buffer closing problem

yesterday, i set `auto close = false`, then i use cmmand `:wq`, it can't close current buffer, but the nvim tree window fills the entire buffer, i want to close it when i close the current buffer, what i should do?

**Comment by gegoune** [comment]
> buffer closing problem

But that's exactly what `auto close = false` does. Set it to `true` to get your desired behaviour.

**Comment by kyazdani42** [comment]
forgot to tell you, you need to add an action name for your bindings:
`{ key = "J", action = "move_down_fast", action_cb = function() vim.cmd":normal 5j" end }`
And gegoune is right for 2)
