### ISSUE TITLE
Git file status icons won't update

### ISSUE THREAD

**Issue by victorheid** [kyazdani42/nvim-tree.lua#966]
**OS**
MacOS Monterey, Win10

**Neovim version**
```
NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by team+vim@tracker.debian.org

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

**Nvim-tree version**
Commit 0f7da14

**Describe the bug**
Git status Icons won't update and be stuck to whatever state it was at first time. Unless you navigate up a level and back into folder.

**To Reproduce**
- Open a git project 
- Open Nvim-tree
- Change a file and save
- Icon will not change to 'unstaged'
- Same happens for other changes like adding to staging area (in my case using Toggleterm/Lazygit), etc.
- NvimTreeRefresh / R key won't refresh it either

**Expected behavior**
Nvim-tree icons to update automatically

**Extra perhaps important info**
- Code diagnostic icons are working

**Comment by Gilgames000** [comment]
I have the same problem! I am on Arch Linux.
