### ISSUE TITLE
Open nvim-tree on VimEnter but without focus

### ISSUE THREAD

**Issue by kdauria** [kyazdani42/nvim-tree.lua#968]
I'm really enjoying this plugin, but I'm stuck trying to figure out how to open the nvim-tree window automatically when opening nvim _without_ focusing on it.

I've been able to toggle nvim-tree without focus using something like this:

```
function M.show()
    require('nvim-tree.view').open({ focus_tree = false })
end

function M.toggle(find_file)
    local nvimtree = require 'nvim-tree'
    local view = require 'nvim-tree.view'
    if view.win_open() then
        view.close()
    else
        if M.setup_config.update_focused_file.enable or find_file then
            nvimtree.find_file(true)
        end
        M.show()
    end
end

function M.show_on_startup()
    require('nvim-tree').open()
    vim.cmd('wincmd p')
    -- this wincmd does NOT work and I can't figure out a workaround
    -- focus is always on tree after entering vim
end

vim.cmd [[
    command! NvimTreeShowToggle lua require'plugins.configs.nvim-tree'.toggle()
    command! NvimTreeShowStartup lua require'plugins.configs.nvim-tree'.show_on_startup()
]]

vim.cmd [[
    augroup nvimtree
        autocmd BufEnter * if (winnr('$') == 1 && &filetype == 'NvimTree') | q | endif
        autocmd VimEnter * NvimTreeShowStartup
    augroup END
]]
```

But, no matter what I try, I can't figure out how to get what I want. When I was using CHADTree, I was able to use `CHADTree --nofocus`. I thought it might be due to other autocommands that the plugin is loading, but disabling them didn't help (assuming I did it correctly).

**Comment by ManInTheSuit** [comment]
Can confirm, I tried adding
```
NvimTreeToggle 
wincmd w
```
to my init.vim to get the desired functionality, but the window doesn't unfocus when using this. Toggling it normally and using :wincmd w does it in an already open nvim window.

**Comment by kyazdani42** [comment]
you can now call `require"nvim-tree".toggle(false, true)` to avoid focus

**Comment by yanzhang0219** [comment]
Hello @kyazdani42 
I found this feature by reading the source code. I think this feature should be mentions in doc, and I believe many users need it. Thank you very much.

**Comment by kyazdani42** [comment]
i added a mention in tips&reminders in the readme.

**Comment by ch4xer** [comment]
Sorry but it seems `require'nvim-tree'.toggle(false,true)` can not help me avoid focus...Don't know whether I miss something.
Here is my `init.lua`
```lua
vim.cmd('packadd packer.nvim')
require('packer').startup(
    function()
        use 'wbthomason/packer.nvim'
        use 'kyazdani42/nvim-tree.lua'
    end
)
require'nvim-tree'.setup {}
require'nvim-tree'.toggle(false,true)
```
After start nvim with command `nvim` or `nvim <filename>`, the cursor still focus on nvim-tree. The screenshot:
![image](https://user-images.githubusercontent.com/40637063/167061289-90bf6312-1b3d-4e8a-9bc5-c2903951b70b.png)

Plugins are up to date and neovim version is `v0.6.1`.

**Comment by kdauria** [comment]
@ch4xer , I was never able to get nvim-tree to avoid focus. I now use an alternative plugin.

**Comment by alex-courtis** [comment]
> Sorry but it seems `require'nvim-tree'.toggle(false,true)` can not help me avoid focus...Don't know whether I miss something.

`open_on_setup` will focus the tree when you have opened an empty buffer
`open_on_setup_file` will focus the buffer when you open with a buffer

The above are desirable and intended behaviour.

`:lua require'nvim-tree'.toggle(false,true)` will open the tree and focus will remain in the empty buffer. That is working.
It does not work when called immediately after tree setup i.e. from your init.

Options:
1. Try to make the call to toggle from setup work.
2. Add a proper feature to allow the focus to be shifted when opening on startup with an empty buffer. A modifier like `ignore_buffer_on_setup` could be created.

1 is hacky. This will not be pursued.
2 is a proper solution. Please raise a feature request @ch4xer . Describe exactly the behaviour you desire, proposing the configuration that would be used to achieve this behaviour.

Alex's opinion: this is a non-problem. `open_on_setup = false` and `open_on_setup_file = true` is a reasonable workflow. Open the tree when you need it from your new buffer. The feature will not be built by the nvim-tree team, however a PR will be accepted.

**Comment by ch4xer** [comment]
@alex-courtis Thanks for your response, I will try to do some hacky tricks.

**Comment by ch4xer** [comment]
I just add an async timer to toggle nvim-tree after setup work.
```lua
function tree_toggle_on_setup()
    require'nvim-tree'.toggle(false,true)
end
vim.fn.timer_start(500, tree_toggle_on_setup)
```

**Comment by kyazdani42** [comment]
@alex-courtis but looks like a bit weird to me that a hack is needed in order to make this work, should we raise a bug ?

**Comment by alex-courtis** [comment]
> @alex-courtis but looks like a bit weird to me that a hack is needed in order to make this work, should we raise a bug ?

Running `require'nvim-tree'.toggle(false,true)` in init.lua could be made to work however it will be very tricky, with autocommands etc.

Add `open_on_setup_focus_tree = true` default false is the only real option IMO.

**Comment by alex-courtis** [comment]
Added very specific feature to startup: https://github.com/kyazdani42/nvim-tree.lua/commit/0417d9148b6546bf4883b6e9750f992f980afbfe

**Comment by alex-courtis** [comment]
Unfortunately this change has been reverted due to many regressions: #1668

Please remove `focus_empty_on_setup` from your configuration.

A new mechanism to control startup behaviour is under way: #1669
