### ISSUE TITLE
How to duplate file

### ISSUE THREAD

**Issue by jieteki** [kyazdani42/nvim-tree.lua#97]
hi, I'm looking for a method to duplate file, like `copy` then `paste` and `rename`, walk through docs and didnot find a way to combine multiple command in one key, is there any ways to get that?  thanks !

**Comment by kyazdani42** [comment]
well that would be just rename imo ?
Rename also allows changing the file path

**Comment by jieteki** [comment]
`rename` rename a file in place, but not `duplicate`.  For `duplicate`, we result in having two files, actually..

**Comment by kyazdani42** [comment]
closed in #100
