### ISSUE TITLE
Cannot disable icons through g:nvim_tree_show_icons

### ISSUE THREAD

**Issue by agorgl** [kyazdani42/nvim-tree.lua#979]
Current configuration:
```
  ...
  -- File explorer
  use {
    'kyazdani42/nvim-tree.lua',
    config = function() require 'config.nvimtree'.config() end
  }
  ...
```
```
local M = {}
local g = vim.g

function M.config()
  local ok, plugin = pcall(require, "nvim-tree")
  if not ok then
    return
  end

  g.nvim_tree_show_icons = {
    git = 0,
    folders = 0,
    files = 0,
    folder_arrows = 0,
  }
  plugin.setup {}
end

return M
```

Running `echo g:nvim_tree_show_icons` shows that everything is set to 0, still icons are displayed in nvim-tree.

**Comment by agorgl** [comment]
Just found out that the relevant `g:` variables are used when requiring the `nvim-tree` module NOT when calling the plugin's `setup` function.

So far the documentation states:
```Note that options under the g: command should be set BEFORE running the setup function```.

This should be corrected to something like:
```Note that options under the g: command should be set BEFORE requiring the nvim-tree module and running the setup function```

**Comment by kyazdani42** [comment]
I guess so, i need to finish porting these to the setup anyway :) you can make a change in the doc in the meantime ?
