### ISSUE TITLE
Errors occur after the latest refactor merging

### ISSUE THREAD

**Issue by yanzhang0219** [kyazdani42/nvim-tree.lua#981]
See below. Thank you.

<img width="1673" alt="image" src="https://user-images.githubusercontent.com/11582667/153963749-e3de7d53-afa5-4265-a7d4-3162a902e507.png">

**Comment by will** [comment]
I think this sha avoids the error in the meantime:

``` lua
  use {"kyazdani42/nvim-tree.lua", commit="3f4ed9b6c2598ab8304186486a0" }
```

**Comment by yanzhang0219** [comment]
@will Yes. We can use the old version until this issue is solved.
