### ISSUE TITLE
view.lua 110 nil windows number error

### ISSUE THREAD

**Issue by ray-x** [kyazdani42/nvim-tree.lua#982]
**OS**
Operation system's name and version
Linux/Arch
**Neovim version**
output of `nvim --version`
NVIM v0.7.0-dev+1082-g046950f63
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by ray@ray-xps-arch
**Nvim-tree version**
nvim-tree branch, commit or tag number
Latest
**Describe the bug**
When toggle tree view, I got following error:
```
 Error executing lua ...ite/pack/packer/opt/nvim-tree.lua/lua/nvim-tree/view.lua:110: Expected Lua number
```

**To Reproduce**
Steps to reproduce the behavior
I am using following setup
```
  require("nvim-tree").setup({
    update_focused_file = {
      enable = true,
      update_cwd = true,
      ignore_list = {},
    },
    view = {
      auto_resize = true,
    },
  })
```

**Expected behavior**
No error.

The error :
```
  local wnr = winnr or M.get_winnr()
  if a.nvim_win_get_tabpage(wnr) ~= a.nvim_win_get_tabpage(0) then

```
I debug print wnr, and it is nil.  I think the latest API does not fallback nil to 0 for bufnr and winnr.

**Comment by kyazdani42** [comment]
I cannot reproduce you error. I will push a fix nonetheless
