### ISSUE TITLE
the cursor cannot be moved

### ISSUE THREAD

**Issue by ttbug** [kyazdani42/nvim-tree.lua#983]
**OS**
ArchLinux WSL

**Neovim version**
neovim 0.6.1

**Nvim-tree version**
nvim-tree branch master lastest

**Describe the bug**
When NvimTreeOpen for the first time, the cursor cannot be moved. 
It falls back to the 3f4ed9b6c2598ab8304 submission, and the function is normal.

**Comment by kyazdani42** [comment]
can you give me your configuration ? I cannot reproduce

**Comment by ttbug** [comment]
> can you give me your configuration ? I cannot reproduce

function config.nvim_tree()
    vim.g.nvim_tree_icons = {
        default = '',
        symlink = '',
        git = {
            unstaged = "✚",
            staged = "✚",
            unmerged = "≠",
            renamed = "≫",
            untracked = "★"
        }
    }
    vim.g.nvim_tree_ignore = { '.git', 'node_modules', '.cache', '.vscode'}
    local tree_cb = require'nvim-tree.config'.nvim_tree_callback
    require('nvim-tree').setup {
        --gitignore = true,
        git = {enable = true, ignore = false, timeout = 500},
        ignore = {'.git', 'node_modules', '.cache', '.vscode'},
        hide_dotfiles = true,
        open_on_tab = false,
        disable_netrw = true,
        hijack_netrw = true,
        auto_close = true,
        update_cwd = false,
        highlight_opened_files = true,
        auto_ignore_ft = {'startify', 'dashboard'},
        update_focused_file = {
            enable = true,
            update_cwd = true,
            ignore_list = {}
        },
        filters = {
            dotfiles = true,
            custom = {}
        },
        view = {
            width = 25,
            side = 'left',
            auto_resize = false,
            mappings = {
                custom_only = true,
                -- list of mappings to set on the tree manually
                list = {
                    {
                        key = {"<CR>", "o", "<2-LeftMouse>"},
                        cb = tree_cb("tabnew")
                    }, {key = {"<2-RightMouse>", "<C-]>"}, cb = tree_cb("cd")},
                    {key = "<C-v>", cb = tree_cb("vsplit")},
                    {key = "<C-x>", cb = tree_cb("split")},
                    {key = "<C-t>", cb = tree_cb("tabnew")},
                    {key = "<", cb = tree_cb("prev_sibling")},
                    {key = ">", cb = tree_cb("next_sibling")},
                    {key = "P", cb = tree_cb("parent_node")},
                    {key = "<BS>", cb = tree_cb("close_node")},
                    {key = "<S-CR>", cb = tree_cb("close_node")},
                    {key = "<Tab>", cb = tree_cb("preview")},
                    {key = "K", cb = tree_cb("first_sibling")},
                    {key = "J", cb = tree_cb("last_sibling")},
                    {key = "I", cb = tree_cb("toggle_ignored")},
                    {key = "H", cb = tree_cb("toggle_dotfiles")},
                    {key = "R", cb = tree_cb("refresh")},
                    {key = "a", cb = tree_cb("create")},
                    {key = "d", cb = tree_cb("remove")},
                    {key = "r", cb = tree_cb("rename")},
                    {key = "<C-r>", cb = tree_cb("full_rename")},
                    {key = "x", cb = tree_cb("cut")},
                    {key = "c", cb = tree_cb("copy")},
                    {key = "p", cb = tree_cb("paste")},
                    {key = "y", cb = tree_cb("copy_name")},
                    {key = "Y", cb = tree_cb("copy_path")},
                    {key = "gy", cb = tree_cb("copy_absolute_path")},
                    {key = "[c", cb = tree_cb("prev_git_item")},
                    {key = "]c", cb = tree_cb("next_git_item")},
                    {key = "-", cb = tree_cb("dir_up")},
                    {key = "s", cb = tree_cb("system_open")},
                    {key = "q", cb = tree_cb("close")},
                    {key = "g?", cb = tree_cb("toggle_help")}
                }
            }
        }
    }
end

**Comment by kyazdani42** [comment]
you have a `--gitignored = true` in your config, your lua file is invalid.

**Comment by adrian5** [comment]
I might be having a related issue, likewise since the recent update.

When opening nvim-tree from the [Startify](https://github.com/mhinz/vim-startify) screen, it occupies the entire window, instead of a side split. The cursor (j/k) no longer works. Toggling nvim-tree off and on _after_ that, I get the cursor function back.

Nvim-tree behaves normally when I already have a regular file buffer open.

**Comment by xfyuan** [comment]
> I might be having a related issue, likewise since the recent update.
> 
> When opening nvim-tree from the [Startify](https://github.com/mhinz/vim-startify) screen, it occupies the entire window, instead of a side split. The cursor (j/k) no longer works. Toggling nvim-tree off and on _after_ that, I get the cursor function back.
> 
> Nvim-tree behaves normally when I already have a regular file buffer open.

me too. I'm using the [alpha-nvim](https://github.com/goolord/alpha-nvim) as start screen.

**Comment by ChrisChou-freeman** [comment]
same problem, i'm using the [dashboard-nvim](https://github.com/glepnir/dashboard-nvim) as start screen

**Comment by kyazdani42** [comment]
The tree should not open when there is a buffer loaded on startup. I'll take a look in the next few days.

**Comment by ttys3** [comment]
> I might be having a related issue, likewise since the recent update.
> 
> When opening nvim-tree from the [Startify](https://github.com/mhinz/vim-startify) screen, it occupies the entire window, instead of a side split. The cursor (j/k) no longer works. Toggling nvim-tree off and on _after_ that, I get the cursor function back.
> 
> Nvim-tree behaves normally when I already have a regular file buffer open.

I also encountered the same problem

**Comment by alduro** [comment]
Same problem here. Same dashboard-nvim as start screen like @ChrisChou-freeman.
Trying to open Nvim-tree with no buffer and got this error message:
```
Error detected while processing CursorMoved Autocommands for "<buffer=1>":
E5108: Error executing lua ...are/nvim/site/pack/packer/start/alpha-nvim/lua/alpha.lua:490: Cursor position outside buffer
stack traceback:
        [C]: in function 'nvim_win_set_cursor'
        ...are/nvim/site/pack/packer/start/alpha-nvim/lua/alpha.lua:490: in function 'move_cursor'
        [string ":lua"]:1: in main chunk
```

**Comment by kyazdani42** [comment]
Issue was that dashboard is unnamed, and the buffer was hijacked, thus not working properly in nvim-tree :smile:

**Comment by adrian5** [comment]
Yup, works fine again with Startify too.
