### ISSUE TITLE
Nvim-Tree error 126: attempt to index global 'TreeExplorer' (a nil value)

### ISSUE THREAD

**Issue by ex4722** [kyazdani42/nvim-tree.lua#984]
**OS**
Arch Linux 5.16.0-arch1-1

**Neovim version**
NVIM v0.6.1
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az87-780

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/home/runner/work/neovim/neovim/build/nvim.AppDir/usr/share/nvim"

Run :checkhealth for more info

null-ls: require("null-ls.health").check()
========================================================================
  - INFO: no sources registered

nvim: health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: RelWithDebInfo

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $TERM_PROGRAM='tmux'
  - INFO: $COLORTERM='truecolor'

## tmux
  - OK: escape-time: 10
  - INFO: Checking stuff
  - WARNING: `focus-events` is not enabled. |'autoread'| may not work.
    - ADVICE:
      - (tmux 1.9+ only) Set `focus-events` in ~/.tmux.conf:
          set-option -g focus-events on
  - INFO: $TERM: tmux-256color

nvim-lsp-installer: require("nvim-lsp-installer.health").check()
========================================================================
## nvim-lsp-installer report
  - OK: neovim version >= 0.6.0
  - WARNING: **Composer**: not available
  - WARNING: **julia**: not available
  - OK: **tar**: `tar (GNU tar) 1.34`
  - OK: **gzip**: `gzip 1.11`
  - OK: **curl**: `curl 7.81.0 (x86_64-pc-linux-gnu) libcurl/7.81.0 OpenSSL/1.1.1m zlib/1.2.11 brotli/1.0.9 zstd/1.5.1 libidn2/2.3.2 libpsl/0.21.1 (+libidn2/2.3.0) libssh2/1.10.0 nghttp2/1.46.0`
  - OK: **wget**: `GNU Wget 1.21.2 built on linux-gnu.`
  - OK: **python3**: `Python 3.10.1`
  - OK: **node**: `v17.3.0`
  - OK: **PHP**: `PHP 8.0.14 (cli) (built: Dec 17 2021 14:16:47) ( NTS )`
  - OK: **Ruby**: `ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [x86_64-linux]`
  - OK: **Go**: `go version go1.17.6 linux/amd64`
  - OK: **bash**: `GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)`
  - OK: **sh**: `Ok`
  - OK: **RubyGem**: `3.2.29`
  - OK: **java**: `Ok`
  - OK: **npm**: `8.3.1`
  - OK: **javac**: `javac 17.0.1`
  - OK: **pip3**: `pip 20.3.4 from /usr/lib/python3.10/site-packages/pip (python 3.10)`

nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found 0.20.2 (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v17.3.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: cc (GCC) 11.1.0
  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - http           ✓ . . . ✓ 
  - supercollider  ✓ ✓ ✓ ✓ ✓ 
  - tlaplus        ✓ ✓ ✓ . ✓ 
  - zig            ✓ . ✓ ✓ ✓ 
  - toml           ✓ ✓ ✓ ✓ ✓ 
  - clojure        ✓ ✓ ✓ . ✓ 
  - pug            ✓ . . . ✓ 
  - commonlisp     ✓ ✓ ✓ . . 
  - vue            ✓ . ✓ ✓ ✓ 
  - jsonc          ✓ ✓ ✓ ✓ ✓ 
  - json           ✓ ✓ ✓ ✓ . 
  - vim            ✓ ✓ . . ✓ 
  - yaml           ✓ ✓ ✓ ✓ ✓ 
  - yang           ✓ . ✓ . . 
  - ninja          ✓ . ✓ ✓ . 
  - nix            ✓ ✓ ✓ . ✓ 
  - cpp            ✓ ✓ ✓ ✓ ✓ 
  - fusion         ✓ ✓ ✓ ✓ . 
  - dart           ✓ ✓ . ✓ ✓ 
  - ledger         ✓ . ✓ ✓ ✓ 
  - rst            ✓ ✓ . . ✓ 
  - bash           ✓ ✓ ✓ . ✓ 
  - fennel         ✓ ✓ . . ✓ 
  - html           ✓ ✓ ✓ ✓ ✓ 
  - teal           ✓ ✓ ✓ ✓ ✓ 
  - tsx            ✓ ✓ ✓ ✓ ✓ 
  - ql             ✓ ✓ . ✓ ✓ 
  - gomod          ✓ . . . ✓ 
  - glimmer        ✓ . . . . 
  - gowork         ✓ . . . ✓ 
  - c              ✓ ✓ ✓ ✓ ✓ 
  - graphql        ✓ . . ✓ ✓ 
  - rasi           ✓ ✓ ✓ ✓ . 
  - ruby           ✓ ✓ ✓ ✓ ✓ 
  - perl           ✓ . . . . 
  - jsdoc          ✓ . . . . 
  - lalrpop        ✓ ✓ . . . 
  - fish           ✓ ✓ ✓ ✓ ✓ 
  - vala           ✓ . . . . 
  - sparql         ✓ ✓ ✓ ✓ ✓ 
  - php            ✓ ✓ ✓ ✓ ✓ 
  - norg           . . . . . 
  - go             ✓ ✓ ✓ ✓ ✓ 
  - java           ✓ ✓ . ✓ ✓ 
  - kotlin         ✓ ✓ ✓ . ✓ 
  - make           ✓ . . . ✓ 
  - prisma         ✓ . . . . 
  - llvm           ✓ . . . . 
  - julia          ✓ ✓ ✓ ✓ ✓ 
  - turtle         ✓ ✓ ✓ ✓ ✓ 
  - ocaml          ✓ ✓ ✓ . ✓ 
  - devicetree     ✓ ✓ ✓ ✓ ✓ 
  - css            ✓ . ✓ ✓ ✓ 
  - cuda           ✓ ✓ ✓ ✓ ✓ 
  - scss           ✓ . . ✓ . 
  - svelte         ✓ . ✓ ✓ ✓ 
  - pascal         ✓ ✓ ✓ ✓ ✓ 
  - erlang         . . . . . 
  - json5          ✓ . . . ✓ 
  - beancount      ✓ . ✓ . . 
  - elixir         ✓ ✓ ✓ ✓ ✓ 
  - query          ✓ ✓ ✓ ✓ ✓ 
  - gdscript       ✓ ✓ . ✓ ✓ 
  - surface        ✓ . ✓ ✓ ✓ 
  - latex          ✓ . ✓ . ✓ 
  - bibtex         ✓ . ✓ ✓ . 
  - comment        ✓ . . . . 
  - eex            ✓ . . . ✓ 
  - godot_resource ✓ ✓ ✓ . . 
  - heex           ✓ ✓ ✓ ✓ ✓ 
  - cmake          ✓ . ✓ . . 
  - r              ✓ ✓ . ✓ . 
  - regex          ✓ . . . . 
  - ocaml_interface✓ ✓ ✓ . ✓ 
  - lua            ✓ ✓ ✓ ✓ ✓ 
  - python         ✓ ✓ ✓ ✓ ✓ 
  - ocamllex       ✓ . . . ✓ 
  - pioasm         ✓ . . . ✓ 
  - hjson          ✓ ✓ ✓ ✓ ✓ 
  - c_sharp        ✓ ✓ ✓ . ✓ 
  - hcl            ✓ . ✓ ✓ ✓ 
  - hocon          ✓ . . . ✓ 
  - javascript     ✓ ✓ ✓ ✓ ✓ 
  - typescript     ✓ ✓ ✓ ✓ ✓ 
  - rust           ✓ ✓ ✓ ✓ ✓ 
  - dot            ✓ . . . ✓ 
  - dockerfile     ✓ . . . ✓ 
  - glsl           ✓ ✓ ✓ ✓ ✓ 
  - scala          ✓ . ✓ . ✓ 

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

provider: health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: xclip

## Python 2 provider (optional)
  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
  - ERROR: Python provider error:
    - ADVICE:
      - provider/pythonx: Could not load Python 2:
          /usr/bin/python2 does not have the "neovim" module. :help |provider-python|
          /usr/bin/python2.7 does not have the "neovim" module. :help |provider-python|
          python2.6 not found in search path or not executable.
          /usr/bin/python is Python 3.10 and cannot provide Python 2.
  - INFO: Executable: Not found

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Multiple python3 executables found.  Set `g:python3_host_prog` to avoid surprises.
  - INFO: Executable: /usr/bin/python3
  - INFO: Other python executable: /bin/python3
  - INFO: Python version: 3.10.1
  - INFO: pynvim version: 0.4.3
  - OK: Latest pynvim is installed.

## Python virtualenv
  - OK: no $VIRTUAL_ENV

## Ruby provider (optional)
  - INFO: Ruby: ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [x86_64-linux]
  - WARNING: `neovim-ruby-host` not found.
    - ADVICE:
      - Run `gem install neovim` to ensure the neovim RubyGem is installed.
      - Run `gem environment` to ensure the gem bin directory is in $PATH.
      - If you are using rvm/rbenv/chruby, try "rehashing".
      - See :help |g:ruby_host_prog| for non-standard gem installations.

## Node.js provider (optional)
  - INFO: Node.js: v17.3.0
  - INFO: Nvim node.js host: /usr/lib/node_modules/neovim/bin/cli.js
  - WARNING: Package "neovim" is out-of-date. Installed: 4.10.0, latest: 4.10.1
    - ADVICE:
      - Run in shell: npm install -g neovim
      - Run in shell (if you use yarn): yarn global add neovim

## Perl provider (optional)
  - ERROR: perl provider error:
    - ADVICE:
      - "Neovim::Ext" cpan module is not installed

telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0
  - WARNING: fd: not found. Install [sharkdp/fd](https://github.com/sharkdp/fd) for extended capabilities

## Telescope Extension: `harpoon`
  - INFO: No healthcheck provided

## Telescope Extension: `media_files`
  - INFO: No healthcheck provided

vim.lsp: require("vim.lsp.health").check()
========================================================================
  - INFO: LSP log level : WARN
  - INFO: Log path: /home/ex4722/.cache/nvim/lsp.log
  - WARNING: Log size: 132542 KB

vim.treesitter: require("vim.treesitter.health").check()
========================================================================
  - INFO: Runtime ABI version : 13
  - OK: Loaded parser for bash: ABI version 13
  - OK: Loaded parser for beancount: ABI version 13
  - OK: Loaded parser for bibtex: ABI version 13
  - OK: Loaded parser for c: ABI version 13
  - OK: Loaded parser for c_sharp: ABI version 13
  - OK: Loaded parser for clojure: ABI version 13
  - OK: Loaded parser for cmake: ABI version 13
  - OK: Loaded parser for comment: ABI version 13
  - OK: Loaded parser for commonlisp: ABI version 13
  - OK: Loaded parser for cpp: ABI version 13
  - OK: Loaded parser for css: ABI version 13
  - OK: Loaded parser for cuda: ABI version 13
  - OK: Loaded parser for dart: ABI version 13
  - OK: Loaded parser for devicetree: ABI version 13
  - OK: Loaded parser for dockerfile: ABI version 13
  - OK: Loaded parser for dot: ABI version 13
  - OK: Loaded parser for eex: ABI version 13
  - OK: Loaded parser for elixir: ABI version 13
  - OK: Loaded parser for erlang: ABI version 13
  - OK: Loaded parser for fennel: ABI version 13
  - OK: Loaded parser for fish: ABI version 13
  - OK: Loaded parser for fusion: ABI version 13
  - OK: Loaded parser for gdscript: ABI version 13
  - OK: Loaded parser for glimmer: ABI version 13
  - OK: Loaded parser for glsl: ABI version 13
  - OK: Loaded parser for go: ABI version 13
  - OK: Loaded parser for godot_resource: ABI version 13
  - OK: Loaded parser for gomod: ABI version 13
  - OK: Loaded parser for gowork: ABI version 13
  - OK: Loaded parser for graphql: ABI version 13
  - OK: Loaded parser for hcl: ABI version 13
  - OK: Loaded parser for heex: ABI version 13
  - OK: Loaded parser for hjson: ABI version 13
  - OK: Loaded parser for hocon: ABI version 13
  - OK: Loaded parser for html: ABI version 13
  - OK: Loaded parser for http: ABI version 13
  - OK: Loaded parser for java: ABI version 13
  - OK: Loaded parser for javascript: ABI version 13
  - OK: Loaded parser for jsdoc: ABI version 13
  - OK: Loaded parser for json: ABI version 13
  - OK: Loaded parser for json5: ABI version 13
  - OK: Loaded parser for jsonc: ABI version 13
  - OK: Loaded parser for julia: ABI version 13
  - OK: Loaded parser for kotlin: ABI version 13
  - OK: Loaded parser for lalrpop: ABI version 13
  - OK: Loaded parser for latex: ABI version 13
  - OK: Loaded parser for ledger: ABI version 13
  - OK: Loaded parser for llvm: ABI version 13
  - OK: Loaded parser for lua: ABI version 13
  - OK: Loaded parser for make: ABI version 13
  - OK: Loaded parser for ninja: ABI version 13
  - OK: Loaded parser for nix: ABI version 13
  - OK: Loaded parser for norg: ABI version 13
  - OK: Loaded parser for ocaml: ABI version 13
  - OK: Loaded parser for ocaml_interface: ABI version 13
  - OK: Loaded parser for ocamllex: ABI version 13
  - OK: Loaded parser for pascal: ABI version 13
  - OK: Loaded parser for perl: ABI version 13
  - OK: Loaded parser for php: ABI version 13
  - OK: Loaded parser for pioasm: ABI version 13
  - OK: Loaded parser for prisma: ABI version 13
  - OK: Loaded parser for pug: ABI version 13
  - OK: Loaded parser for python: ABI version 13
  - OK: Loaded parser for ql: ABI version 13
  - OK: Loaded parser for query: ABI version 13
  - OK: Loaded parser for r: ABI version 13
  - OK: Loaded parser for rasi: ABI version 13
  - OK: Loaded parser for regex: ABI version 13
  - OK: Loaded parser for rst: ABI version 13
  - OK: Loaded parser for ruby: ABI version 13
  - OK: Loaded parser for rust: ABI version 13
  - OK: Loaded parser for scala: ABI version 13
  - OK: Loaded parser for scss: ABI version 13
  - OK: Loaded parser for sparql: ABI version 13
  - OK: Loaded parser for supercollider: ABI version 13
  - OK: Loaded parser for surface: ABI version 13
  - OK: Loaded parser for svelte: ABI version 13
  - OK: Loaded parser for teal: ABI version 13
  - OK: Loaded parser for tlaplus: ABI version 13
  - OK: Loaded parser for toml: ABI version 13
  - OK: Loaded parser for tsx: ABI version 13
  - OK: Loaded parser for turtle: ABI version 13
  - OK: Loaded parser for typescript: ABI version 13
  - OK: Loaded parser for vala: ABI version 13
  - OK: Loaded parser for vim: ABI version 13
  - OK: Loaded parser for vue: ABI version 13
  - OK: Loaded parser for yaml: ABI version 13
  - OK: Loaded parser for yang: ABI version 13
  - OK: Loaded parser for zig: ABI version 13
  - OK: Loaded parser for c: ABI version 13

**Nvim-tree version**
b1127c5deaca10e570ffbb33b4045b775971aaeb
Latest as of Feb 14

**Describe the bug**
Every couple of seconds a giant bloody error message pops up. 

**To Reproduce**
Just open any file and wait type a couple of keys

**Expected behavior**
Excepting nothing to happen

Heres a error low 
```
Error executing vim.schedule lua callback: ...nt_vgAha5a/usr/share/nvim/runtime/lua/vim/diagnostic.lua:663: Error executing lua: ...nt_vgAha5a/usr/share/nvim/runtime/lua/vim/diagnostic.lua:664: V
im(lua):E5108: Error executing lua ...packer/start/nvim-tree.lua/lua/nvim-tree/diagnostics.lua:126: attempt to index global 'TreeExplorer' (a nil value)
stack traceback:
        ...packer/start/nvim-tree.lua/lua/nvim-tree/diagnostics.lua:126: in function 'update'
        [string ":lua"]:1: in main chunk
        [C]: in function 'nvim_command'
        ...nt_vgAha5a/usr/share/nvim/runtime/lua/vim/diagnostic.lua:664: in function <...nt_vgAha5a/usr/share/nvim/runtime/lua/vim/diagnostic.lua:663>
        [C]: in function 'nvim_buf_call'
        ...nt_vgAha5a/usr/share/nvim/runtime/lua/vim/diagnostic.lua:663: in function 'set'
        ...gAha5a/usr/share/nvim/runtime/lua/vim/lsp/diagnostic.lua:209: in function 'handler'
        /tmp/.mount_vgAha5a/usr/share/nvim/runtime/lua/vim/lsp.lua:735: in function 'cb'
        vim.lua:285: in function <vim.lua:285>
stack traceback:
        [C]: in function 'nvim_command'
        ...nt_vgAha5a/usr/share/nvim/runtime/lua/vim/diagnostic.lua:664: in function <...nt_vgAha5a/usr/share/nvim/runtime/lua/vim/diagnostic.lua:663>
        [C]: in function 'nvim_buf_call'
        ...nt_vgAha5a/usr/share/nvim/runtime/lua/vim/diagnostic.lua:663: in function 'set'
        ...gAha5a/usr/share/nvim/runtime/lua/vim/lsp/diagnostic.lua:209: in function 'handler'
        /tmp/.mount_vgAha5a/usr/share/nvim/runtime/lua/vim/lsp.lua:735: in function 'cb'
        vim.lua:285: in function <vim.lua:285>
stack traceback:
        [C]: in function 'nvim_buf_call'
        ...nt_vgAha5a/usr/share/nvim/runtime/lua/vim/diagnostic.lua:663: in function 'set'
        ...gAha5a/usr/share/nvim/runtime/lua/vim/lsp/diagnostic.lua:209: in function 'handler'
        /tmp/.mount_vgAha5a/usr/share/nvim/runtime/lua/vim/lsp.lua:735: in function 'cb'
        vim.lua:285: in function <vim.lua:285>
```

**Comment by t-troebst** [comment]
Same issue here. I did a git bisect: the issue was introduced in https://github.com/kyazdani42/nvim-tree.lua/commit/6da74679449897dd95eaecaefe8dea80fc7eb3de. The problem disappears once nvim-tree has been opened once.

**Comment by venzen** [comment]
Same issue on Ubuntu 18.02 using nvim 0.6.1.
After the latest refactoring this diagnostic error fills the screen every few minutes:
```
Error executing vim.schedule lua callback: /usr/share/nvim/runtime/lua/vim/diagnostic.lua:663: Error executing lua: /usr/share/
nvim/runtime/lua/vim/diagnostic.lua:664: Vim(lua):E5108: Error executing lua ...packer/start/nvim-tree.lua/lua/nvim-tree/diagno
stics.lua:126: attempt to index global 'TreeExplorer' (a nil value)
```
It does seem to stop complaining after opening nvim-tree
