### ISSUE TITLE
No git info for tracked file when GIT_DIR and GIT_WORK_TREE are set and showUntrackedFiles=no

### ISSUE THREAD

**Issue by yanzhang0219** [kyazdani42/nvim-tree.lua#985]
**OS**
macOS 12.2 (the latest)

**Neovim version**
NVIM v0.7.0-dev+1083-g758d7726d

**Nvim-tree version**
[3f4ed9b](https://github.com/kyazdani42/nvim-tree.lua/commit/3f4ed9b6c2598ab8304186486a05ae7a328b8d49)

**Describe the bug**
No git info when GIT_DIR and GIT_WORK_TREE are set in `zshenv` and `showUntrackedFiles` is set to `no`.

**To Reproduce**
1. In zshenv, set
	```bash
	export GIT_DIR="$HOME/dotfiles"
	export GIT_WORK_TREE="$HOME"
	```
	where `$HOME/dotfiles` is a bare repo. 
	Then set `showUntrackedFiles` to `no` in `$HOME/dotfiles/config`.
2. Open an unstaged file like `~/file1` using Neovim
3. Then open `nvim-tree`, no git info shown on the tree. I already set `timeout` to a very large value like `500000`.

**Important**: If I remove `showUntrackedFiles=no`, the git info show as expected, just with a 2~3 seconds block when opening `nvim-tree`. However, If I set `showUntrackedFiles=no`, opening `nvim-tree` doesn't bring any block, and no git info. 

**Expected behavior**
The git info should show as expected. 

Thank you very much.

**Comment by kyazdani42** [comment]
if showUntrackedFiles is `no`, then git will not track untracked files which is why you have no information. What happens if you do:
`git status --no-optional-locks -u --porcelain=v1` ? The results of this command should be shown in the tree.

**Comment by yanzhang0219** [comment]
Thank you for your reply.

> if showUntrackedFiles is no, then git will not track untracked files which is why you have no information.

`file1` in my example above is tracked file. I `git add` it first. Then I open it and `nvim-tree` window. When I modify this file (it becomes unstaged), no info shown.

**Comment by kyazdani42** [comment]
did you run the command ? I believe if you modify the file, it must go back to untracked.

**Comment by yanzhang0219** [comment]
Thanks. 

> did you run the command 

I tried to run the command you provided in shell but it showed `--no-optional-locks` is an invalid option. 

> I believe if you modify the file, it might go back to untracked

I don't think so. Untracked files are the files that have not been git added yet. Once you git add a file, it will become tracked and staged. Then after you modify it, it becomes unstaged. 

Let's try another experiment.
Under `$HOME` directory, execute all below:
1. Create a bare repo `git init --bare $HOME/bare.git`
2. In zshenv, set git env
	```bash
	export GIT_DIR="$HOME/bare.git"
	export GIT_WORK_TREE="$HOME"
	```
3. In a new shell, under `$HOME`, let's create a file, and commit it
	```bash
	touch file1			# it is untracked
	git add file1		# it becomes tracked and staged
	git commit -m "first commit"
	```
4. Then we write something into this file
	```bash
	echo "hello" >> file1
	```
5. Next, let set showUntrackedFiles` to no. In `$HOME/bare.git/config`, append the code below
	```
	[status]
		showUntrackedFiles = no
	```
6. Then we run `git status` in the shell and the output is 
	
	<img width="627" alt="image" src="https://user-images.githubusercontent.com/11582667/154138826-7a813d89-e92e-42c6-9a42-d13815d7094b.png">

	It shows that file1 is modified and unstaged. Next, we open it via `nvim file1`, and then open `nvim-tree`, no git status information is shown next the file name. 

Thank you very much.

**Comment by kyazdani42** [comment]
--no-optional-locks should be a valid option. Can you try remove it from the list in git/runner.lua and try again to check ? It might change something.
Just by the way `man git`:
```
 --no-optional-locks
           Do not perform optional operations that require locks. This is equivalent to setting the GIT_OPTIONAL_LOCKS to 0.
```

**Comment by kyazdani42** [comment]
###

**Comment by yanzhang0219** [comment]
Okay I will try that right away. 
Do you my new detailed experiment above? Thank you.

**Comment by kyazdani42** [comment]
Sorry again you was not supposed to add the `-u` (that's showing the untracked file).

**Comment by kyazdani42** [comment]
It takes a lot of time to reproduce issues like this and fix them so sorry for the many things i ask you

**Comment by yanzhang0219** [comment]
> Sorry again you was not supposed to add the -u (that's showing the untracked file).

Okay. I was confused why you asked me add `-u`. Now after running it, I got this
<img width="1022" alt="Screen Shot 2022-02-16 at 13 06 19" src="https://user-images.githubusercontent.com/11582667/154357048-71f6b35c-dd88-489e-b345-ee931c1a1734.png">

Yes. It gave the same result as `git status`

> It takes a lot of time to reproduce issues like this and fix them so sorry for the many things i ask you

You put efforts into developing such a great plugin. As an user, to help you debug and make it more shining is what I should do, and I am really glad to.

**Comment by kyazdani42** [comment]
well looks like something wrong here. I'll give it a look tomorrow :)

**Comment by kyazdani42** [comment]
when you say:
```
export GIT_DIR="$HOME/dotfiles"
export GIT_WORK_TREE="$HOME"
```
shouldn't GIT_DIR be `$HOME/dotfiles/.git` ?
I could not reproduce with just the above. I have to set up a bare repo which might take some time, can you first confirm the `GIT_DIR` variable is correct ?

**Comment by yanzhang0219** [comment]
Oh, forget about it. Just follow and try the demo experiment I mentioned above, see https://github.com/kyazdani42/nvim-tree.lua/issues/985#issuecomment-1040731508. Thank you.

**Comment by kyazdani42** [comment]
Well i've set up the bare repo and i could still not reproduce :smile:

**Comment by yanzhang0219** [comment]
> I'm going to follow this bit by bit. Sorry

Okay, please. 😀

**Comment by kyazdani42** [comment]
Well i could reproduce. But it seems weird i have to investigate. Git gives me this:
```
git --no-optional-locks status --porcelain=v1 --ignored=matching
fatal: Unsupported combination of ignored and untracked-files arguments
```

**Comment by yanzhang0219** [comment]
> fatal: Unsupported combination of ignored and untracked-files arguments

If I run `git --no-optional-locks status --porcelain=v1 --ignored=matching`, I get the same thing. However, the command you asked me to run earlier is `git --no-optional-locks status --porcelain=v1`, not including `--ignored=matching`.

**Comment by kyazdani42** [comment]
sorry for all the noise, i should've tested first. It was indeed some kind of regression :)

**Comment by yanzhang0219** [comment]
>  it's actually when setting the option in the config

Yes. If I don't set `showUntrackedFiles = no` in `bare.git/config` and run `git --no-optional-locks status --porcelain=v1 --ignored=matching`, I get all the untacked files but no errors. But if it is set, the `fatal` error raised.

**Comment by kyazdani42** [comment]
can you try https://github.com/kyazdani42/nvim-tree.lua/pull/996 ? should fix this issue.

**Comment by yanzhang0219** [comment]
Nice! It is working like a charm now 👍 👍 👍 👍
So responsive and I really appreciate it and your efforts!
