### ISSUE TITLE
NvimTreeFindFile does not seem to work outside a project

### ISSUE THREAD

**Issue by socketwiz** [kyazdani42/nvim-tree.lua#986]
I thought `NvimTreeFindFile` would show the tree window with the file in the buffer selected in the tree.  This works as expected if you pick a file that is in a project.  However if you open a file outside the project and try to do a `NvimTreeFindFile` then it just opens the tree in the project root. Is this expected? Is there a way to get it to open the selected file regardless of whether or not you are in a project?

**Comment by gegoune** [comment]
I think there is bit of contradiction in your report:

> However if you open a file **outside the project** and try to do a NvimTreeFindFile then it just opens the tree **in the project root**.

And what is "project"? git repository?

I just tried opening file outside of git repository and `NvimTreeFindFile` correctly opened tree and highlighted current buffer.

**Comment by younger-1** [comment]
Actually, I notice that `NvimTreeFindFileToggle` and `NvimTreeOpen` (with `update_focused_file.enable`) can't not change the cursor in the tree for the current bufname. It could work before 6da7467 was introduced.

**Comment by socketwiz** [comment]
Strange. I suppose it could be something in my configuration. I will try with only this plugin installed and a clean config this even and report back the results.

**Comment by gegoune** [comment]
I am using `ahmedkhalf/project.nvim` and tested with it active, in case it made a difference.

**Comment by jorgebef** [comment]
I can confirm this issue running neovim 0.6.1 and MacOS.
Same steps and configuration as described above and also in issue #987 
If I can provide any information needed I am more than happy to.

**Comment by socketwiz** [comment]
I reproduced the problem even after stripping my configuration down to this single line:

```init.lua
-- init.lua
require('nvim-tree').setup {}
```

**Comment by kyazdani42** [comment]
Hi, looking at your issue it does not seem like a bug to me. Nvim-tree does not do git project root detection before finding a file, it only change directory to the one above the current displayed file if this file is not under the current root directory of nvim-tree.
Did i understand this correctly ?

**Comment by socketwiz** [comment]
> Nvim-tree does not do git project root detection before finding a file,

I don't think it should have to.  Maybe I don't understand how `NvimTreeFindFile` is supposed to work but my understanding is that when you execute it, whatever file you are looking at in the current buffer will be displayed in the tree when it opens.  I gave an example where this is not the case.

**Comment by kyazdani42** [comment]
there is a find-file configuration for nvim-tree that is targeted at this behavior that i cannot make it by default because it breaks a lot of configurations. If i understand correctly, this issue is neither a bug nor a feature, but missing to read `:help nvim-tree.update_focused_file` ?

**Comment by ricky-at-picnic** [comment]
That seems like an accurate assessment. I was unaware of that setting.  When I set:
```
  update_focused_file = {
    update_cwd  = true
  },
```
It now seems to work the way I was expecting.  My apologies for the false alarm.  Thank you for helping me figure this out!

**Comment by socketwiz** [comment]
Also, sorry, I accidentally replied with my work account.  I don't see any way to close this ticket, but it is resolved as far as I am concerned.  Thank you very much for your help.
