### ISSUE TITLE
The update_focused_file doesn't work in my side.

### ISSUE THREAD

**Issue by ChavaTI** [kyazdani42/nvim-tree.lua#989]
**OS**
Arch Linux
Linux 5.16.9-arch1-1

**Neovim version**
`NVIM v0.7.0-dev+1091-g3449405f3
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
`

**Nvim-tree version**
branch develop
commit 121f5c90374c6ba8a3fb33787ca508e8694b7d02

**Describe the bug**
I've enabled the `update_focused_file` option, but when I open the tree, it starts from the root, then I close it and open again and then open the nodes of my current opened file, but the cursor is still on the root.

**To Reproduce**
- Open and file in a random path of a project.
- Open the nvim_tree

The nvim_tree is opened in the root node.
![nvim-tree-issue](https://user-images.githubusercontent.com/35637860/154162031-3e39c86d-2da8-4d55-8f0e-e70337226be6.gif)
**Expected behavior**
The nvim_tree is opened in the current file or buffer that I'm using it.

**Comment by kyazdani42** [comment]
it's fixed in latest master.
