### ISSUE TITLE
Unrecognized git state "D "

### ISSUE THREAD

**Issue by jemag** [kyazdani42/nvim-tree.lua#99]
Getting the following message trying to navigate through a directory:

> [LuaTree] Unrecognized git state "D ". Please open up an issue on https://github.com/kyazdani42/nvim-tree.lua/issues with this message.

I can still navigate, but I will get that message each time I am trying to open a directory within that topmost directory that first had the error.

As for the git state, there doesn't seem to be anything out of the ordinary. I have some changes that have not been added to staging, and some that have been, including a deleted file in that directory giving the error messages.

**Comment by kyazdani42** [comment]
Hi,
I've seen that too. I should spend some time working on this when i can :) A small refactoring of the git api is needed in this repo ^^
