### ISSUE TITLE
NvimTreeFindFile opens tree but doesn't jump to file

### ISSUE THREAD

**Issue by weeman1337** [kyazdani42/nvim-tree.lua#991]
**OS**
Ubuntu 20.04.3 LTS

**Neovim version**
NVIM v0.6.1

**Nvim-tree version**
`master`

**Describe the bug**
`NvimTreeFindFile` opens the tree. But it doesn't jump to the file.

It breaks starting with this commit: https://github.com/kyazdani42/nvim-tree.lua/commit/6da74679449897dd95eaecaefe8dea80fc7eb3de

**Comment by kyazdani42** [comment]
is this still happening in latest master ? could you give me you nvim-tree setup config otherwise ?

**Comment by konart** [comment]
Latest master fixed this for me.

**Comment by arsham** [comment]
Latest master works. However there is a difference between whether the tree is open or not. The cursor jumps to a different location:

![tree-issue](https://user-images.githubusercontent.com/428611/154351621-525a5c9f-5c0a-44a8-b8a8-ea70d7991fce.gif)

**Comment by hoopes** [comment]
https://github.com/kyazdani42/nvim-tree.lua/issues/988

fixed after this

**Comment by arsham** [comment]
I just updated the plugin and it has the same behaviour.
Would you want me to continue this on the other issue?

**Comment by hoopes** [comment]
Seems like your issue is more specific - mine was just "jump to the tree".

**Comment by kyazdani42** [comment]
indeed it's not the same issue. Closing this, this is related to the cursor hijack not taking effect when setting current win. Not a big deal for now :) open an issue if you wish.
