### ISSUE TITLE
NvimTree no longer has a fixed width

### ISSUE THREAD

**Issue by siduck** [kyazdani42/nvim-tree.lua#992]
I updated nvimtree plugin yesterday and now my nvim is fullscreen :/ 
 
 
![image](https://user-images.githubusercontent.com/59060246/154275166-07b4575d-1251-4d03-9ad1-6df6a43659b3.png)

**Comment by HenryCROSS** [comment]
I suffered the same issue. 
Also, it somehow crashes the neovim when I hit the keybinding slowly when it is in the dashboard.

**Comment by konart** [comment]
> It's a feature. People wanted full screen tree and that's what it is I think.

Features shouldn't break the old behaviour.  Not without a notice at least.

**Comment by kyazdani42** [comment]
Well yes it's a feature that fixed a lot of issues :smile:
i pushed 76d4ed5 which should let you set `hijack_unnamed_buffer_when_opening = false` during setup

**Comment by siduck** [comment]
> Well yes it's a feature that fixed a lot of issues smile i pushed [76d4ed5](https://github.com/kyazdani42/nvim-tree.lua/commit/76d4ed5d770f521c060dbe053aaaadd7f1245b7e) which should let you set `hijack_unnamed_buffer_when_opening = false` during setup

i added that line to the setup but it still doesnt work :(

**Comment by kyazdani42** [comment]
if you open with `vim .` or `vim dir`, nvim-tree hijacks the directory buffer and opens fullscreen

**Comment by siduck** [comment]
> if you open with `vim .` or `vim dir`, nvim-tree hijacks the directory buffer and opens fullscreen

I just open neovim ( run nvim command ) and then do nvimtreetoggle, the default behaviour must have a fixed width like before at least.. Also I tried vim . , it opens the tree with fixed width for the first time and then opens fullscreen, cant I always keep the fixed width like before?

**Comment by kyazdani42** [comment]
i fixed the issue when opening manually. Does it fix your issue ?

**Comment by siduck** [comment]
> i fixed the issue when opening manually. Does it fix your issue ?

thx it works now! but nvimtreetoggle doesnt close with ( opening a dir with nvim i.e nvim command )

https://user-images.githubusercontent.com/59060246/154493439-546b4c14-2245-4600-8505-077ce6a1a002.mp4

**Comment by kyazdani42** [comment]
i do not understand this issue @siduck. Could you open an issue with a good explanation of the problem ? Your example is a bit too fast :smile:

**Comment by siduck** [comment]
> i do not understand this issue @siduck. Could you open an issue with a good explanation of the problem ? Your example is a bit too fast smile

oh i meant, nvimtreetoggle stopped working when i opened neovim with a dir i.e nvim dirname . but it works when i just open neovim and then do nvimtreetoggle o_o

**Comment by kyazdani42** [comment]
please open a new issue ? i'm not sure of the steps to reproduce since this issue has gone beyond its original subject.

**Comment by batusai513** [comment]
@kyazdani42 is there a way to not have the behaviour of opening full screen when running `:NvimTreeToggle` after opening nvim with `nvim .`? I've already added `hijack_unnamed_buffer_when_opening = false` and it is not working (still open full screen when there are no files opened).

here is my config:
```lua
local config = {
  disable_netrw = true,
  hijack_netrw = true,
  open_on_setup = false,
  ignore_buffer_on_setup = false,
  ignore_ft_on_setup = {
    "startify",
    "dashboard",
    "alpha",
  },
  auto_reload_on_write = true,
  hijack_unnamed_buffer_when_opening = false,
	hijack_directories = {
		enable = true,
		auto_open = false,
	},
  auto_close = false,
  open_on_tab = false,
  hijack_cursor = false,
  update_cwd = false,
  diagnostics = diagnosticsConfig,
  update_focused_file = {
    enable = true,
    update_cwd = false,
    ignore_list = {},
  },
	system_open = {
		cmd = nil,
		args = {},
	},
	git = {
		enable = true,
		ignore = false,
		timeout = 500,
	},
  view = {
    width = 30,
    height = 30,
    hide_root_folder = false,
    side = "right",
    auto_resize = false,
    mappings = {
      custom_only = false,
      list = {
        { key = { "l", "<CR>", "o" }, cb = tree_cb "edit" },
        { key = "h", cb = tree_cb "close_node" },
        { key = "v", cb = tree_cb "vsplit" },

      },
    },
    number = false,
    relativenumber = false,
		signcolumn = "yes",
  },
	filters = {
		dotfiles = false,
		custom = { "node_modules", ".cache" },
	},
	trash = {
		cmd = "trash",
		require_confirm = true,
	},
	actions = {
		change_dir = {
			global = false,
		},
		open_file = {
			quit_on_open = false,
		},
		window_picker = {
			enable = true,
			chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890",
      exclude = {
        filetype = { "notify", "packer", "qf", "diff", "fugitive", "fugitiveblame", },
        buftype  = { "nofile", "terminal", "help", },
      }
		},
	},
  quit_on_open = 0,
}
```

thanks for your help

**Comment by kyazdani42** [comment]
disable hijack_directories. `nvim .` opens the current directory so it hijacks it.
