### ISSUE TITLE
[Question] Adding a wiki-page

### ISSUE THREAD

**Issue by eddiebergman** [kyazdani42/nvim-tree.lua#993]
Hi @kyazdani42,

Great plugin :) I found I started liking it a lot more and finding it a lot more intuitive by re-mapping keys to perform custom actions that matched a similar setup with vim-vinegar. I made a [wiki-page](https://github.com/kyazdani42/nvim-tree.lua/wiki/h,-j,-k,-l--style-navigation-and-editing) as there was no restrictions. Let me know if this is okay and if not, feel free to remove it!

Best,
Eddie

**Comment by kyazdani42** [comment]
I made the wiki page open so people can contribute like this :) Thanks !
